lib/domains/ge/edu/unik.txt

added - Kutaisi University

---

lib/domains/us/ma/k12/plymouth/student.txt

Adds the domain for the Plymouth Public Schools (https://www.plymouth.k12.ma.us/)

Added the domain for the plymouth public schools

---

lib/domains/ma/isiam.txt

Website : https://isiam.ma/
IT related course : https://isiam.ma/programmes/2eme-cycle/

new school

---

lib/domains/tn/r-iset/kelibia.txt

Let's make PhpStrom Better together!

Add ISET KELIBIA

---

lib/domains/co/edu/usc.txt

Universidad santiago de Cali - https://www.usc.edu.co/

Add Universidad Santiago de Cali

---

lib/domains/cz/sps-karvina.txt

Střední průmyslová škola, Karviná, příspěvková organizace
web: http://www.spskarvina.cz/

Added school Stredni prumyslova skola Karvina

---

lib/domains/ge/edu/tesau.txt

Add IAKOB GOGEBASHVILI TELAVI STATE UNIVERSITY

Add Georgian university

---

lib/domains/org/hatboro-horsham.txt

Added my school,
Hatboro-Horsham High School in Hatboro-Horsham School District

Add Hatboro-Horsham High School

---

lib/domains/fi/hyria/edu.txt

Schools official website: https://www.hyria.fi/ 
About the school:  https://www.hyria.fi/international_hyria/about_hyria/adult_education
Software developer education: https://www.hyria.fi/koulutukset/hae_yhteishaussa/koulutustarjonta/tietojenkasittely_ja_tietoliikenne/tieto-_ja_viestintatekniikan_perustutkinto/ohjelmistokehittaja

Add edu.hyria.fi

---

lib/domains/org/thakureducation.txt

Hello Jetbrains team,
I would like to add my college to the domain list of approved educational institution.

Adding Thakur college of Engineering and Technology to the domain list

---

lib/domains/ua/edu/kpnu.txt

Request for  Kamianets-Podіlskyi National Ivan Ohiienko University

kpnu.edu.ua

---

lib/domains/id/ac/fisip-untirta.txt

Social and Polotical Sciences Sultan Ageng Tirtayasa University 
University Faculty Website: [fisip.untirta.ac.id](http://fisip.untirta.ac.id)
Student Email Domain: [fisip-untirta.ac.id](http://fisip-untirta.ac.id)

Added Social and Polotical Sciences Sultan Ageng Tirtayasa University

---

lib/domains/th/ac/pkru.txt

Add Phuket rajaphat university

---

lib/domains/de/gesamtschule-fischbach.txt

Hello!
I have added the domain gesamtschule-fischbach.de to the repository. It belongs to the German `Gesamtschule Fischbach`.
Website of the school: http://www.gesamtschule-fischbach.de/
Imprint of the school: http://www.gesamtschule-fischbach.de/impressum
Thanks a lot!

Add gesamtschule-fischbach.de

---

lib/domains/de/gesamtschule-fischbach.txt
lib/domains/de/pdr-kelkheim.txt

Hello!
I have added the domain pdr-kelkheim.de to the repository. It belongs to the German `Privatgymnasium Dr. Richter`.
School website: [https://www.pdr-kelkheim.de/](https://www.pdr-kelkheim.de/)
Imprint of the school: [https://www.pdr-kelkheim.de/impressum.html](https://www.pdr-kelkheim.de/impressum.html)
At [this link](https://www.pdr-kelkheim.de/wahlfaecher.html) a computer science course of the school is listed.
Thanks a lot!

Add pdr-kelkheim.de

---

lib/domains/ua/edu/wunu.txt

Add West Ukrainian National University

Add West Ukrainian National University

---

lib/domains/uk/co/cvms.txt

Hi there I am attending The Cardinal Vaughan Memorial School as a Sixth Form student, I am working on a school project we have been assigned and would be grateful to use JetBrains services for educational purposes strictly.
My school email address is 14ranasd@cvms.co.uk

School request

---

lib/domains/co/edu/uninpahu.txt

New file with name the university 
UNINPAHU - Fundación Universitaria Para El Desarrollo Humano, 
Name of the career-> Software Engineering

Add UNINPAHU university

---

lib/domains/org/la-pmn.txt

add PMN School https://www.la-pmn.fr/

---

lib/domains/ca/cchic/etu.txt

Official Website URL: 
https://cchic.ca/
URL of program offered (3 years/ 6 semester) :
https://cchic.ca/programmes/techniques-informatique/
Proof of official domain name:

Added my school - ca/cchic/etu.txt

---

lib/domains/my/edu/usim.txt

University website:
https://usim.edu.my
Bachelor of computer science: http://fst.usim.edu.my/program-structures/bachelor-of-computer-science-hons-information-security-and-assurance/

Added usim.txt

---

lib/domains/fr/inalco.txt

I added my school, INALCO (Institut national des langues et civilisations orientales) (https://www.wikiwand.com/en/Institut_national_des_langues_et_civilisations_orientales). I need to learn python for my classes because it's very important in automatic language processing. Thank you ! Our e-mail adresses are @inalco.fr

Added school INALCO

---

lib/domains/com/preciousheritageschool.txt

Create profile for Precious Heritage College, Ibadan, Oyo State, Nigeria.

Profile for Precious Heritage College, Nigeria

---

lib/domains/eg/edu/usc.txt

University Of Sadat City

---

lib/domains/ua/edu/wunu.txt

Add West Ukrainian National University

Create West Ukrainian National University

---

lib/domains/ec/edu/unibe.txt

Add  Universidad Iberoamericana del Ecuador

Add  Universidad Iberoamericana del Ecuador

---

lib/domains/uk/ac/howcollege.txt

Adding Heart Of Worcestershire College.
Example course: https://www.howcollege.ac.uk/courses/computing-and-it/2471/hnd-computing-app-development-level-5/
Thanks

Add Heart Of Worcestershire College

---

lib/domains/com/onmicrosoft/epshl.txt

Schoolwebsite: (https://www.epshl.de/)

Added EPSHL

---

lib/domains/co/edu/usco.txt

Website official https://www.usco.edu.co/

add Universidad Surcolombiana from Colombia

---

lib/domains/com/swbgs.txt

Add Sir William Borlase's Grammar School

---

lib/domains/schule/kkst/s.txt

Website: https://www.koenigin-katharina-stift.de/
IT Course: https://www.koenigin-katharina-stift.de/kkst/unsere-profile/imp/
Use of school email in Moodle: https://imgur.com/a/yB2ek8J

Königin Katharina Stift Gymnasium

---

lib/domains/org/brookeweston.txt

Brooke Weston Academy, UK - https://brookeweston.org/

Added Brooke Weston Academy's domain

---

lib/domains/br/com/einsteinlimeira.txt

Website:  http://www.einsteinlimeira.com.br/portal/
IT Course: http://www.einsteinlimeira.com.br/portal/14/27
Use of school email on Office 365: https://imgur.com/a/XwMaFs7

Add Einstein Limeira 

---

lib/domains/br/edu/imed.txt

Added Faculdade Meridional - IMED (imed.edu.br)

Added IMED

---

lib/domains/bj/unstim.txt

I add UNSTIM, Benin University domain to get the license of Jetbrains product for student from UNSTIM.

Add UNSTIM university domain

---

lib/domains/id/ac/uinsu.txt

Universitas Islam Negeri Sumatera Utara
http://www.uinsu.ac.id

Add Universitas Islam Negeri Sumatera Utara

---

lib/domains/it/edu/1circolopozzuoli.txt

https://www.1circolopozzuoli.edu.it/

Add I Circolo Didattico G. Marconi

---

lib/domains/es/edu/iunit.txt

Adding IUNIT

---

lib/domains/ru/ngknn.txt

Official website: https://ngknn.ru
link to the offered specialties: https://ngknn.ru/tekh/840-spetsial-nosti-dlya-postupayushchikh
link to document official email domain: https://ngknn.ru/images/Подтверждение_домена.pdf

Add ngknn.txt

---

lib/domains/com/onmicrosoft/lbiro.txt

National College of Informatics "Tudor Vianu", Bucharest, Romania http://portal.lbi.ro/

National College of Informatics "Tudor Vianu", Bucharest, Romania

---

lib/domains/co/edu/unipacifico.txt

http://www.unipacifico.edu.co:8095/web3.0/inicio.jsp
http://www.unipacifico.edu.co:8095/web3.0/institucional.jsp?opt=10&opt2=pg program engineering of systems

add universidad del pacifico from colombia

---

lib/domains/es/ceuandalucia.txt

To whom it may concern,
Thank you a lot for taking the time to review the application for adding the domain.
Sincerely,
Eduardo Díaz

added ceuandalucia.es domain

---

lib/domains/org/rvilleschools.txt

Program Of Studies:
http://robbinsvillehs.ss10.sharpschool.com/UserFiles/Servers/Server_265203/File/Guidance/Program%20of%20Studies/POS%202018%20-%202019%20updated.pdf#page=56
(Pages 56 and 55 have CS courses)
School:
http://robbinsvillehs.ss10.sharpschool.com/

Added Robbinsville High School

---

lib/domains/au/edu/westernsydney.txt

Added the Western Sydney University website for staff

Added westernsydney.edu.au

---

lib/domains/br/edu/ucsal.txt

School official website: https://www.ucsal.br/
Course website: http://noosfero.ucsal.br/graduacao/cursos/graduacao-tecnologica/analise-e-desenvolvimento-de-sistemas?view=true
Proof of e-mail domain: ![UCSAL - Official email reference](https://user-images.githubusercontent.com/60860485/109539862-8a628300-7aa0-11eb-8c0d-6cd48406b8cc.png)
Ps.: The picture was taken after successfully submiting your account info on https://portal.ucsal.br/ (which is our 'Student's Portal') and clicking on the 'E-MAIL INSTITUCIONAL' (institutional e-mail) option on the far right of the image.
Pps.: The reason I cropped my e-mail was so people didn't spam it. I can give a uncropped version if necessary.

Adding Salvador Catholic University

---

lib/domains/br/edu/ifpa.txt

Link: https://www.ifpa.edu.br/
Curso Superior de Tecnologia em Análise e Desenvolvimento de Sistemas do IFPA:
(Higher Technology Course in Analysis and Systems Development at IFPA):
Link of course: https://sigaa.ifpa.edu.br/sigaa/public/curso/portal.jsf?id=61837&lc=pt_BR

add ifpa.edu.br

---

lib/domains/de/doz-provadis-hochschule.txt

see also https://github.com/JetBrains/swot/pull/3056
Teachers at:
Provadis School of International Management & Technology AG
https://www.provadis-hochschule.de/

Add doz-provadis-hochschule.de

---

lib/domains/au/edu/myacu.txt

Added Australian Catholic University

---

lib/domains/pl/szczecin/wsb/student.txt

University URL: https://www.wsb.pl/szczecin/

Added student.wsb.szczecin.pl domain

---

lib/domains/co/edu/areandina/estudiantes.txt

Hello, this is the areandina URL: https://www.areandina.edu.co/es/content/estudiantes

Add areandina domain

---

lib/domains/id/ac/itnb.txt

Official Website https://itnb.ac.id/

Add Institut Bisnis IT&B

---

lib/domains/co/edu/unisinu.txt

When I try to get the student license with my email ending at @ unisinu.edu.co, GitHub throws an error saying, "Your email address does not belong to any university that we know of". So I think adding this domain could solve the problem.

Add unisinu

---

lib/domains/br/fae/sou.txt

Official website URL: https://www.fae.br/unifae/
https://www.fae.br/unifae/cursos/engenharia-de-software
Proof: 
(classroom)

Add UNIFAE

---

lib/domains/br/edu/unaerp/sou.txt

University Official Website: [https://www.unaerp.br/](https://www.unaerp.br/)
Computer Engineering Course URL: [https://www.unaerp.br/cursos/engenharia-da-computacao](https://www.unaerp.br/cursos/engenharia-da-computacao)
Proof of official email domain: 
(Student Portal)
(Google Classroom)

Added UNAERP

---

lib/domains/th/ac/ytc.txt

yala technical college

---

lib/domains/com/onmicrosoft/csssnina.txt

School website: https://www.csssnina.sk
This is the email our school provides us with to access office and to submit our assignments: firstName.lastName@csssnina.onmicrosoft.com
Also our school allows us to graduate from IT.

Add csssnina

---

lib/domains/br/edu/fanese/acad.txt

Official website URL: https://fanese.edu.br/
Course: https://fanese.edu.br/fan/lab/sistemas.html

Request for FANESE - SE

---

lib/domains/us/nc/k12/lee.txt

https://www.lee.k12.nc.us/lchs
https://www.lee.k12.nc.us/domain/1295

Add Lee County School System

---

lib/domains/lt/kvkedu.txt

Official Website: https://www.kvk.lt/en/
IT related course Informatics: https://www.kvk.lt/en/studies/informatics/
URL for an email domain: http://mail.kvkedu.lt/

Add Klaipeda State University of Applied Sciences

---

lib/domains/ca/csda.txt

Commission scolaire des Affluents

 Commission scolaire des Affluents

---

lib/domains/au/edu/nortwest.txt

[nortwest.txt](https://github.com/JetBrains/swot/files/6098964/nortwest.txt)

Added nortwest pty ltd.

---

lib/domains/us/mi/k12/clarkston.txt

Clarkston Michigan Community School District

Clarkston Community Schools

---

lib/domains/br/edu/fpp.txt

Our institution offers both a PhD programme and a specialization that both include bioinformatics in their curriculums.
It would be very valuable for our students to be included in JetBrains' "Products for Learning" initiative.
Links:
This is a link to the PhD program, please search for the word "bioinformática":
https://faculdadespequenoprincipe.edu.br/doutorado-em-biotecnologia-aplicada-a-saude-da-crianca-e-do-adolescente/
This is a link to the course curriculum:
https://faculdadespequenoprincipe.edu.br/wp-content/uploads/2015/08/MatrizcurricularBIO2015.pdf
This is a link to the curriculum of the Specialization in Molecular Biology:
https://faculdadespequenoprincipe.edu.br/wp-content/uploads/2020/11/ESPECIALIZACAO-BIOLOGIA-MOLECULAR.pdf
Thank you for the initiative!

Added fpp.edu.br

---

lib/domains/ua/edu/kmu.txt

Private higher educational establishment Kyiv Medical University kmu.edu.ua

add PHEE “Kyiv Medical University”

---

lib/domains/tw/org/yuntech.txt

add Yuntech(National Yunlin University of Science and Technology) org email

add yuntech.txt

---

lib/domains/br/edu/unifeob/sou.txt

Add Unifeob

---

lib/domains/ug/ac/cavendish/students.txt
students.txt

https://www.cavendish.ac.ug/
https://www.cavendish.ac.ug/programmes/bachelors-degrees/bachelor-of-science-in-computer-science/article

Please add my school

---

lib/domains/br/edu/iesp.txt

Adding University Center UNIESP
- the school official website URL
https://www.iesp.edu.br/
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
https://www.iesp.edu.br/cursos/graduacao/sistemas-de-informacao
https://www.iesp.edu.br/cursos/graduacao/sistemas-para-internet
- the school street address
Rodovia BR 230 Km 14 s/n Morada Nova, PB, 58109-303

Adding University Center UNIESP

---

lib/domains/academy/metis.txt

Organization name is `IT v kurze`
Our webpage is https://www.itvkurze.sk/
For our students we have emails in format `<name>.<surname>@metis.academy`. Here is our internal portal for students and teachers / lectors where they can log in using such email https://portal.metis.academy/
Here is direct link to see all our courses https://www.itvkurze.sk/studium
Here is link for one of our long-term courses (3 years) for position of Software Engineer https://www.itvkurze.sk/studium/metis-academy-software-engineer-metis-academy-german-language?backlink=%23filter%3Dnull
Thanks 🙂

Add metis.academy

---

lib/domains/ro/alexandrucelbun.txt

https://www.alexandrucelbun.ro/

the college website is alexandrucelbun.ro

---

lib/domains/my/edu/unimy/student.txt
student.txt

https://www.unimy.edu.my/
https://www.unimy.edu.my/programme/bachelor-of-engineering-honours-in-computer-engineering

Add UNIMY domain

---

lib/domains/id/ac/unibi/mhs.txt

I just added the Indonesian Business and Informatics University (UNIBI or Universitas Informatika dan Bisnis Indonesia) to the repository so that it can be checked by the JetBrains team and added it to the list of registered universities.
Official site of university can be visit [here](https://unibi.ac.id/).

Added UNIBI

---

lib/domains/iq/edu/coie-nahrain.txt

Al-Nahrain University College of Information Engineering
https://coie-nahrain.edu.iq
tamara.rafid@coie-nahrain.edu.iq

add coie-nahrain

---

lib/domains/org/ebrschools.txt

Website - https://brmhs.com/
https://brmhs.com/wp-content/uploads/2019/01/BRMHS-19-20-Course-Directory.pdf
Search for "computer science" in the above pdf to see our school's computer science courses offered.
On the homepage, if you navigate to about the school > Faculty/Staff > (any department) > and hover over any teacher's picture you can see that their email ends in @ebrschools.org. It is the domain that the district uses.

Baton Rouge Magnet High School

---

lib/domains/th/ac/vistec.txt

Vidyasirimedhi Institute of Science and Technology

Added @vistec.ac.th

---

lib/domains/co/edu/americana.txt

Add Corporación Universitaria Americana with domain 'americana.edu.co'

Add amerizana.txt

---

lib/domains/id/ac/sinus.txt

Add School STMIK Sinar Nusantara Surakarta

Add STMIK Sinar Nusantara Surakarta

---

lib/domains/co/edu/colmabrija.txt

It is requested to add the domain of the educational institution

Add colmabrija domain

---

lib/domains/ke/ac/kism.txt
lib/domains/ke/or/kism.txt

https://kism.or.ke
https://kiseb.or.ke

Added Kenya Institute of Supplies Management

---

lib/domains/com/my-campus-berlin/edu.txt

Add DHGS with domain 'my-campus-berlin'.

Add DHGS my-campus-berlin

---

domains/au/edu/sa/smc.txt
lib/domains/au/edu/sa/smc.txt

School Website: https://smc.sa.edu.au

Add my school to the JetBrains database

---

lib/domains/th/ac/psuwit.txt

Added PSUWittyanusorn school
domain : psuwit.ac.th

Added PSUWittyanusorn school

---

lib/domains/ps/edu/ppu.txt

adding PPU to the list of schools

adding PPU to the list of schools

---

lib/domains/lb/edu/usal.txt

Add University of sciences and arts in Lebanon 

---

lib/domains/com/lyceeastier.txt

Ajout du Lycée Polyvalent Astier, BTS SNIR

Creation de lyceeastier.txt

---

lib/domains/com/joyintlschool.txt

Huai'an Joy International School

---

lib/domains/ca/collegelacite.txt
lib/domains/org/lasalle-douala.txt

EST La Salle - Douala
Collège La Cité

Add 2 institutions

---

fud.txt
lib/domains/ng/edu/fud.txt

Federal University Dutse
[FUD](https://fud.edu.ng/)
[Fud Courses](https://fud.edu.ng/up.php)
- [ x] Students

Pull request for verification of Federal University Dutse

---

lib/domains/co/edu/teinco.txt

https://teinco.edu.co/
https://teinco.edu.co/index.php/programas-teinco/facultad-de-ingenieria-de-sistemas/ingenieria-de-sistemas/

Add Teinco

---

lib/domains/id/ac/uinmataram.txt

Add UIN Mataram

---

lib/domains/org/texasonlineprep.txt

School website: https://tops.k12.com/
This page https://tops.k12.com/contact-us.html contains an email ending in @texasonlineprep.org.
This page https://www.smore.com/r2hnb-tops-contact-guide, linked on the site at Who We Are -> School Resources -> TOPS Contact Guide, also contains several emails ending in @texasonlineprep.org.
If you look at some of the pages on the site, the school offers CS courses:
- https://tops.k12.com/our-curriculum/stride-career-prep.html
- https://tops.k12.com/our-curriculum/stride-career-prep/information-technology.html
Furthermore, the "High School Courses Overview" PDF (https://www.k12.com/content/dam/schools/tops/files/20-21SY-TOPS-9-12.pdf) linked on this page: https://tops.k12.com/our-curriculum/high-school.html has various CS courses such as "TCH100A-PBL …

Add Texas Online Preparatory School

---

lib/domains/at/bbs-rohrbach.txt

Added BBS-Rohrbach to the AT-Domains

Created bbs-rohrbach.txt

---

lib/domains/co/edu/iush/comunidad.txt

Univerisdad Salazar y herrera 
https://www.iush.edu.co/
dario.vallejop@comunidad.iush.edu.co

adding iush comunidad to allow students

---

lib/domains/id/ac/sttgarut.txt

Added Sekolah Tinggi Teknologi Garut to lib/domains/id/ac/

Added sttgarut.txt

---

lib/domains/id/ac/mercubuana-yogya.txt

add file `/lib/domains/id/ac/mercubuana-yogya.txt` to add domain` mercubuana-yogya.ac.id `to the repository

add file mercubuana-yogya.txt

---

lib/domains/it/mi/maxwell.txt

IIS J.C. Maxwell - Milano [ request to add ]
-----------------------------------------------------
High School of Milan, Italy 20132
Liceo Scientifico Scienze Applicate
Website: https://www.maxwell.edu.it
Google domain email: @maxwell.mi.it {` name.surname@maxwell.mi.it `}
**Institution/School Name:**
IIS J.C. Maxwell - Milano
**Instiution/School Website:**
https://www.maxwell.edu.it
**Email Users:**
pietro.tamburini@maxwell.mi.it
**Education Levels:**

Add Maxwell.txt

---

lib/domains/cz/gfp.txt

Grammar School of F. Palacky in Neratovice
Thank you.

Please add gfp.cz

---

lib/domains/id/ac/pelitabangsa.txt

Pelita Bangsa University
https://pelitabangsa.ac.id

add pelitabangsa.ac.id

---

lib/domains/kr/go/goe/bojeongh.txt

Bojeong High School

---

lib/domains/in/slrtce.txt

College SLRTCE ADDED

---

lib/domains/org/avhsd.txt

Request to add Antelope Valley Union High School District to list of schools.
https://www.avdistrict.org/

Add Antelope Valley Union High School District to list of schools

---

lib/domains/org/gsastl.txt

The school website is hs.gsastl.org

Added txt file for educational license

---

lib/domains/br/edu/veigadealmeida.txt

- Official website:
https://www.uva.br/
- Page of official website with long-term IT related course (Computer Science):
https://www.uva.br/content/ciencias-da-computacao
- Proof of organization recognizing domain (Screenshot of e-mail sent by the university giving access to the new student e-mail translated with google translate):

Please add Universidade Veiga de Almeida's student domain

---

lib/domains/es/rtve.txt

https://www.rtve.es/instituto/
https://es.wikipedia.org/wiki/Instituto_RTVE
https://es.linkedin.com/school/institutortve/
In this degree we have a subject of web audiovisual production, where we teach the creation of web for shows and streaming. The degree has a total duration of 2 years that is offered annually. Students and teachers have an email address domain: student@rtve.es. You can see the information in the following link.
https://www.rtve.es/rtve/20170714/produccion-audiovisuales-espectaculos/1238041.shtml

Add Instituto RadioTelevision Española

---

lib/domains/org/sebrsd.txt

Please add my new school https://www.sebrsd.org/

David Prouty High School

---

lib/domains/be/groeipunt.txt

CVO Groeipunt, adult education

CVO Groeipunt

---

lib/domains/org/lavelleprep/student.txt

Added Lavelle Prep School to the Student List :)

Added my School | Lavelle Prep

---

lib/domains/org/42network.txt

42network is the parent organisation which creates all pedago materials for all 42 campuses worldwide (42tokyo, 42seoul, 42lyon, 42paris etc...)

Added 42network as school (parent org for all 42 schools)

---

lib/domains/net/avccengg.txt

It is a educational institution from india.
http://www.avccengg.net/ (can verify)

please add this A.V.C. College of Engineering

---

lib/domains/ro/usm.txt

added Stefan cel Mare University of Suceava

Stefan cel Mare University of Suceava

---

lib/domains/id/ac/umkt.txt

Added Universitas Muhammadiah Kalimantan TImur

adding Universitas Muhammadiyah Kalimantan Timur

---

lib/domains/com/ecolescreatives/lyn.txt

Cinécréatis is a french cinema/3d school we use JetBrain software for post-production plugin.

Add CinéCréatis school

---

lib/domains/de/bkhaspel.txt

Emails for students are hosted under firstname.lastname@bkhaspel.de (IServ-Network)
Official School website is: https://bkah.de/

Added Domain of Berufskolleg am Haspel

---

lib/domains/br/edu/iscon.txt

Add Faculty ISCON
https://iscon.edu.br

Add iscon.txt

---

lib/domains/br/edu/unifacig/sempre.txt

|| LINK |
|--|--|
| Official website | [URL](https://unifacig.edu.br/) |
|Long-term (>1 year) IT related course is offered by the university|[Here](https://unifacig.edu.br/cursos/graduacao/analise-e-desenvolvimento-de-sistemas/) you will find information about the Systems Analysis and Development course|
|Proof that the university recognizes the domain|[Here](https://i.imgur.com/pxIEUex.png) you will find a screenshot of the access to e-mail with the university's domain|

Add Centro Universitario UNIFACIG

---

lib/domains/ma/ucd.txt

|         |     Link                      |
| --------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
|  Official website                                                                                   | [UCD](http://www.ucd.ac.ma/en/)   <br> schools : <br> - [ENSAJ](http://www.ensaj.ucd.ac.ma/) (Where i am from) <br/> - ...                                                                                   |
|  where a long-term (>1 year) IT-related course is offered                                           | …

Add Chouaib Doukkali University

---

lib/domains/ec/edu/umet/est.txt

add umet university of Ecuador

---

lib/domains/de/gesa-rhede.txt

Hello I'm the Luca from Germany and I wanna add my school
The school's website: [**Gesa Rhede**](https://www.gesamtschule-rhede.de/)

Added Rhede comprehensive school

---

lib/domains/es/juntadeandalucia.txt

Official page - https://iesjaroso.es/?page_id=10
Page for informatic FP (Formación Profesional) course - http://informatica.iesjaroso.es/

Add IES Jaroso

---

lib/domains/vn/edu/hlu/student.txt

Hanoi Law University
https://hlu.edu.vn/
**HLU provides an additional on-the-job training course about IT which lasts about 2 years along with the main training program. 2021 is the second year this course admits new students so it is very fresh.**

Add Hanoi Law University Domain

---

lib/domains/be/broeders.txt

Site:
http://www.broeders.be/
Informatic related course
http://www.handel.broeders.be/handel/contentpage.aspx?page=studieaanbodGraad3Informaticabeheer(tso)&mid=197

Added Broederscholen Hiëronymus

---

lib/domains/org/ssrvm.txt

SSRVM - Sri Sri Ravishankar Vidya Mandir India

Adding SSRVM School (ssrvm.txt)

---

lib/domains/us/va/k12/bedford.txt

Adding Bedford school district

Added Bedford school district

---

lib/domains/tz/ac/ilboru.txt

Please add Ilboru High School domain to the list of  domains.

add  ilboru.txt

---

lib/domains/de/igs-goettingen.txt

school website: https://www.igs-goe.de/

Add Georg-Christoph-Lichtenberg-Gesamtschule Göttingen-Geismar to school list

---

lib/domains/id/ac/isi.txt

add isi.ac.id

---

lib/domains/iq/edu/atu.txt

Adding Al Furat Al-Awsat Technical University

Adding Al Furat Al-Awsat Technical University

---

lib/domains/com/queensmetro.txt

**Add Queens Metropolitan High School ( *Fixed PR )**  
Queens Metropolitan High School
https://www.queensmetro.com/

Add Queens Metropolitan High School ( Fixed PR )  

---

lib/domains/pl/umcs/office.txt

Maria Curie-Skłodowska University
www.umcs.pl
www.umcs.pl/pl/logowanie-aktywacja,20299.htm
office.umcs.pl

Add Maria Curie-Skłodowska University

---

lib/domains/at/ac/borgstpoelten.txt

Please add BRG/BORG St. Pölten school to swot

Add BRG/BORG stp

---

lib/domains/ec/edu/pucesd.txt

PR for adding PUCESD domain to list
University url: https://pucesd.edu.ec/

Add PUCESD University to domains

---

lib/domains/de/landsh/schule.txt

Link: https://schulzentrum-sylt.de
E-Mail: gym.sz-sylt@schule.landsh.de

Added schulzentrum-sylt

---

lib/domains/ua/edu/mnau.txt

Contact person: volosyuk@mnau.edu.ua
Web site: https://www.mnau.edu.ua

Mykolayiv National Agrarian University

---

lib/domains/it/liceoscacchibari.txt

@philipto Sorry, I wrote the wrong site. The new school website is:
https://liceoscacchibari.it/
The PATH should now be correct. Thanks for your time!

Add Liceo Scacchi Bari

---

lib/domains/org/istemghs.txt

[School website](https://www.istemghs.org/)

iSTEM Early College High School

---

lib/domains/au/edu/qld/citipointe.txt

Request to add Citipointe Christian College. Website url is https://citipointe.qld.edu.au/

Request to add Citipointe Christian College

---

lib/domains/th/ac/panyarathighschool.txt

add panyarathighschool.txt to the repository
http://www.panyarathighschool.ac.th/

Add panyarat high school to the repo

---

lib/domains/br/com/faccar/edu.txt

The college mentioned below offers a 3-year system analysis graduation course and has a partnership with Google Classroom, any e-mail ended in @edu.faccar.com.br belongs to it, as anybody may check. Thanks in advance.
FACCAR's website:
https://www.faccar.com.br/cursos-de-graduacao

adding FACCAR file

---

lib/domains/uk/org/chartereastdulwich.txt

School website: https://www.chartereastdulwich.org.uk/

Added School Charter School East Dulwich

---

lib/domains/uk/co/hswv.txt

Added Highfields School to repository for JetBrains educational products.

Add school as .txt

---

lib/domains/br/edu/meta.txt

University official website URL: https://meta.edu.br/faculdade/
Course - Computer Engineering : https://meta.edu.br/faculdade/engenharia-de-computacao/

Add Grupo Meta

---

lib/domains/br/unorp.txt

Inclusion of the UNORP domain in the repository

New domain inclusion

---

lib/domains/au/edu/nsw/stgregs.txt

St Gregory's College

---

lib/domains/cz/ceskolipska.txt

link to my school home page: https://www.ceskolipska.cz/
link to our IT subject: https://www.ceskolipska.cz/studium-272/predmety-274/informatika-a-vypocetni-technika-334
link with mail address format proof: https://www.ceskolipska.cz/o-skole-275/lide-289
We really need to learn to work with Java web container. Will you help us, please?

added ceskolipska

---

lib/domains/co/edu/cues.txt

Website: https://www.cues.edu.co/
Address:
Carrera 50 No 79 – 155
Carrera 50 No 79 – 85
Barranquilla / Colombia

Add CUES to JetBrains Edu

---

lib/domains/cn/edu/smbu.txt
lib/domains/cn/edu/zyufl.txt

Website  
https://www.zyufl.edu.cn/  (Simplified Chinese)
https://en.zyufl.edu.cn/  (English)
School Name
ZheJiang YueXiu University 
浙江越秀外国语学院
Address
浙江省绍兴市越城区群贤中路2801号（镜湖校区）  会稽路428号（稽山校区）
No.428 Kuaiji Road, Yue Cheng District, Shaoxing, Zhejiang, China
Major: Digital Media Arts
Course: Web Design, Digital Image Processing
https://net.zyufl.edu.cn/755/list.htm   
Major: Digital Media Technology
Course: Data Structures and Algorithms, Digital Image Processing, Virtual Reality, Mobile App Development, Python Programming, Data Mining and Analysis
https://net.zyufl.edu.cn/szmtjs/list.htm
@ zyufl.edu.cn mail is mainly used by teachers

Add ZheJiang YueXiu University; Add ShenZhen MSU-BIT University

---

lib/domains/id/ac/stiemj.txt

domain: stiemj.ac.id
university: STIE Muhammadiyah Jakarta
location: Indonesia

Request license for STIE Muhammadiyah Jakarta

---

lib/domains/uk/org/bramptonmanor.txt

txt file for bramptonmanor.org.uk added

Add bramptonmanor.org.uk txt file via upload

---

lib/domains/br/org/ibfc.txt

Add the Instituto Brasileiro de Formação e Capacitação
Brazilian Institute of Training and Capacity Building

Including IBFC

---

lib/domains/net/alighieripascoli.txt

Added "alighieripascoli.net" domain

Added "alighieripascoli" domain

---

lib/domains/th/ac/chandra.txt

Add chandrakasem rajabhat university

Add files via upload of chandrakasem rajabhat university

---

lib/domains/au/edu/coderacademy.txt

Coder Academy operates Australia’s only accredited bootcamp.  We provide unique, innovative, and industry-driven educational experiences in Sydney, Melbourne, and Brisbane to equip Australians with the in-demand coding and technology skills they'll need to tackle the future of work.
Coder Academy's website:
https://coderacademy.edu.au/
Coder Academy's year long course:
https://coderacademy.edu.au/coding-courses/coding-bootcamps/gentech

Add coder academy bootcamp in Australia

---

lib/domains/com/essat-gabes-elearning.txt
lib/domains/com/essat-gabes.txt

Official Website:
http://www.essat-gabes.com/
E-learning Platform (Created specially to assure the continuity of lessons during covid-19 quarantine)
https://www.essat-gabes-elearning.com
this link is a "OneDrive" shared folder with a PDF describing our school and two screenshots of our office 365 for education account (the eligibility criteria for Office 365 for education are similar to those of JetBrains)
https://essatpriveegabes-my.sharepoint.com/:f:/g/personal/mohamed_nasr_essat-gabes_com/EsGQDSg9y25HqirF7nM-PhsBkwgX6KQMAldTEySCNNkUXA?e=poYWJ7
Thank you

Add ESSAT Gabes Domines to the list

---

lib/domains/hk/edu/cccmyc.txt

School Offical Website: 
https://www.cccmyc.edu.hk/
Prove of computer related course: 
https://www.cccmyc.edu.hk/doc/2021/School%20Curriculum%20Policy%20(Sept%202020%20).pdf (page9, 10)

Add CCCMYC Domain.

---

lib/domains/es/campusviu.txt

@campusviu.es are part of Valencian International University email address for campus utilization.
https://campus.viu.es/
https://www.universidadviu.com/

Add @campusviu.es emails

---

lib/domains/ua/edu/ugi.txt

Official Website:
https://ugi.edu.ua/
URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university:
https://ugi.edu.ua/programm/ekonomichna-kibernetyka/
https://ugi.edu.ua/en/programm/economic-cybernetics/

Add Ukrainian Institute of Arts and Sciences

---

lib/domains/co/edu/ibero.txt

add ibero university

---

lib/domains/org/miu.txt

add txt file to swot

---

lib/domains/com/junia/student.txt

Add the Junia schools
https://www.junia.com

Add Junia School

---

lib/domains/tw/edu/just.txt

Add the JinWen schools
https://en.just.edu.tw/ or https://www.just.edu.tw/app/home.php

Add the JinWen schools

---

lib/domains/us/in/k12/phm.txt

Add P-H-M School Corporation

---

lib/domains/id/ac/unirow.txt

I have fixed the domain location

Add UNIROW

---

lib/domains/rs/edu/fimek.txt

http://www.fimek.edu.rs/
http://www.fimek.edu.rs/en/about-us/about-university-business-academy-in-novi-sad.html

Add FIMEK UNIVERSITY 

---

lib/domains/se/newton/edu.txt

There was a problem with the domain at the school, it should be fixed now!

https://www.newton.se/

---

lib/domains/sk/svr.txt

Request to add my Slovak School

---

lib/domains/com/junia.txt

School web sites:
https://www.junia.com/en
https://www.isen-lille.com/
IT related courses at page 190 :
https://www.junia.com/en/wp-content/uploads/sites/11/2021/01/course-guide-JUNIA-2020-21.pdf

Added Junia Engineering School

---

lib/domains/iq/edu/alkafeel.txt

Add AlKafeel University - Iraq

Add AlKafeel University

---

lib/domains/au/edu/sa/pembroke.txt

school website: https://www.pembroke.sa.edu.au/
God bless you mate

Pembroke School, South Australia

---

lib/domains/cz/spstrutnov.txt

School webpage: https://www.spstrutnov.cz/
School mail: https://mail.spstrutnov.cz/
Proof that school uses this domain: https://www.spstrutnov.cz/kontakty

Add spstrutnov.cz

---

lib/domains/com/campusaula.txt

Official website: https://www.campusaula.com/

Adding Aula Campus

---

lib/domains/com/hzcollege.txt

add Huizhou Ecomonics And Polytechnic College

Huizhou Ecomonics And Polytechnic College

---

lib/domains/org/jeffcopublicschools.txt
lib/domains/us/co/k12/jeffco.txt
lib/domains/us/jeffcoschools.txt

This PR creates entries for Jefferson County Public Schools.
Domains include:
- https://jeffcoschools.us/
- https://jeffcopublicschools.us/
- http://jeffco.k12.co.us/

feat: entries for Jefferson County Public Schools (Jeffco)

---

lib/domains/br/edu/ifro.txt

Add ifro.edu.br domain

---

lib/domains/br/edu/universo/bh.txt

Adding Universo BH into university list

Universo BH

---

lib/domains/ec/edu/pucesi.txt

Pontificia Universidad Católica del Ecuador Sede Ibarra

Add PUCESI

---

lib/domains/pl/pijarzy/liceum.txt

School's website: https://www.liceum.pijarzy.pl/index.html
The school offers a 4 year course with extended Mathematics, Physics and IT, here's a link to the school's educational offer PDF: 
https://www.liceum.pijarzy.pl/storage/uploaded/Oferta-edukacyjna-2021-2022_12.02.2021.pdf
Here's a screenshot of my school Google account, created on the domain I want to add:

Add Liceum Ogólnokształcące Zakonu Pijarów im. Stanisława Konarskiego w Krakowie

---

lib/domains/it/edu/paolosarpi.txt

https://www.paolosarpi.edu.it/

add school ISIS Paolo Sarpi

---

lib/domains/br/edu/unirg.txt

Included Universidade Regional de Gurupi

Add Universidade Regional de Gurupi

---

lib/domains/tw/edu/nttu/ms109.txt

add my school , thx

---

lib/domains/org/district833/apps.txt

- [official website url](https://www.sowashco.org)
- [page where long-term IT courses are offered](https://erhs.sowashco.org/cms/one.aspx?portalId=1222088&pageId=2937348)
```
AP Computer Science
Computer Science
Computer Integrated Manufacturing
Computer Science and Software Engineering
Digital Electronics
Engineering Design and Development
```
- [proof this domain is used for emails](https://erhs.sowashco.org/cms/one.aspx?portalId=1222088&pageId=1222122)
```
Grade 9: Reena Paul & Molly Doran erhsgrade9@apps.district833.org
Grade 10: Alyssa Kreutzfeldt & Michele Johnston erhsgrade10@apps.district833.org
Grade 11: Denise Bertotto & Uyen Campbell erhsgrade11@apps.district833.org
Grade 12: Jennifer Benjamin erhsgrade12@apps.district833.org
```

Add apps.district833.org

---

lib/domains/pt/cscm-lx/in.txt

In secondary school, more specifically in the 12th grade, we study Computer Applications in relation to Python.
Official Website - www.cscm-lx.pt
Secondary Website - portal.cscm-lx.pt

Add cscm-lx.pt

---

lib/domains/ec/edu/uisek.txt

Add UISEK Ecuador
Universidad Internacional SEK Ecuador
https://www.uisek.edu.ec/
wilson.castro@uisek.edu.ec
jonathan.lemus@uisek.edu.ec
cristhian.tupiza@uisek.edu.ec
jorge.anazco@uisek.edu.ec

Add Unversidad Internacional Sek Ecuador

---

lib/domains/tr/edu/rdu.txt

Rauf Denktas University
www.rdu.edu.tr

Rauf Denktas Universitesi

---

lib/domains/net/jamesrumsey.txt
lib/domains/net/proof.txt

https://www.jamesrumsey.com/ is my school's website.

James Rumsey Technical Institute Application

---

lib/domains/ng/edu/osustech.txt

Add Ondo State University of Science and Technology to the list of schools in the codebase. 
The school is a valid school with the school website:
https://www.osustech.edu.ng
here is the link to ptume application one of the school application portal
https://app.osustech.edu.ng/
and here is my official school mail: 130404014@osustech.edu.ng

[ADD] osustech to list of schools

---

lib/domains/uk/org/thomasestley.txt

Added Thomas Estley Community College

---

lib/domains/in/kvsroguwahati.txt

Kindly Add my school name to the list of schools.

Added Kendriya Vidyalaya Namrup to the list

---

lib/domains/in/hindustanschools.txt

Added Hindustanschools.in

---

lib/domains/kr/icehs/iasa.txt

Incheon Academy of Science and Arts : http://iasa.icehs.kr/main.do

Add Incheon Academy of Science and Arts

---

lib/domains/nl/roctilburg.txt

Added ROC Tilburg

---

lib/domains/th/ac/rmutsv.txt

{Rajamangala University of Technology Srivijaya}
{https://www.rmutsv.ac.th/}

add RMUTSV

---

lib/domains/com/rmutsvmail.txt

University Website - [https://www.rmutsv.ac.th/en](https://www.rmutsv.ac.th/en)

add Rajamangala University of Technology Srivijaya

---

lib/domains/in/ac/kuk.txt

University Website - https://kuk.ac.in/
Engineering Department Website - https://www.uietkuk.ac.in/
Info - Student email exists with the University domain, not from the department. 
University Offers - 
1. Bachelors of Technology in Computer Science  - 4 yr
2. Master of Technology in Computer Science - 2 yr
3. Bachelors of Science (Major Computer Science) - 3 yr
4. Masters of Science (Major Computer Science) - 2 yr
5. Bachelor of Computer Application - 3 yr (Deptt. DCSA)
6. Masters of Computer Application - 3 yr  (Deptt. DCSA)
7. PhD in Computer Science Related Fields 
and many courses can be found on the website

Add Kurukshetra University, Kurukshetra

---

lib/domains/by/ggplp.txt

Add Gomel State Professional Lyceum of Instrumentation domain

add ggplp.txt

---

lib/domains/de/bbs-me.txt

+Adding BBS|ME public vocational school

+Adding school from Hanover - Germany

---

lib/domains/krd/edu/duhokcihan.txt

Cihan University - Duhok

---

lib/domains/nz/school/kingshigh.txt

Added Kings High School

---

lib/domains/au/edu/qld/somerset.txt

Somerset College on the Gold Coast: https://www.somerset.qld.edu.au/

Somerset College

---

lib/domains/ca/myucwest.txt

University Canada West domain.

University Canada West domain

---

lib/domains/uk/org/ealingfields.txt

Added file as requeste by JetBrains. Thank you.

Added File Ealing Fields High School

---

lib/domains/id/sekolahmuridmerdeka.txt

https://www.sekolahmuridmerdeka.id/
Hi JetBrains. I add an email domain with sekolahmuridmerdeka.id Sekolah Murid Merdeka -  is a Blended Learning School  in Indonesia.
https://dapo.kemdikbud.go.id/sekolah/AC9BE28633955985CF42

Add Sekolah Murid Merdeka @sekolahmuridmerdeka.id

---

lib/domains/br/tc/tcero.txt

Added Escola de Contas do Tribunal de Contas de Rondônia

Added Escola de Contas do Tribunal de Contas de Rondônia

---

lib/domains/uk/ac/worthing.txt

https://www.worthing.ac.uk/study-courses/course-list?term=Computing_%26_IT

Add Worthing College

---

lib/domains/lk/ac/nsbm.txt

**NSBM Green University**
Website - https://www.nsbm.ac.lk
Address - Mahenwaththa, Pitipana, Homagama, Sri Lanka
Courses
- https://www.nsbm.ac.lk/faculties/faculty-of-computing/
- https://www.nsbm.ac.lk/course/bsc-honours-in-software-engineering/

Add NSBM Green University (nsbm.ac.lk)

---

lib/domains/ru/rksi/it.txt

Added Rostov-on-Don College of Communication and Computer Science

---

lib/domains/id/ac/unama.txt

Add Universitas Dinamika Bangsa / Dinamika Bangsa University / UNAMA

Add Universitas Dinamika Bangsa

---

lib/domains/com/onmicrosoft/opolelo3.txt

Highschool site: ~~http://www.lo3.opole.pl/index2.php~~
Edit: Now it is just https://www.lo3.opole.pl.

Added domain opolelo3.onmicrosoft.com.

---

lib/domains/pl/eduwarszawa/uczen.txt

This is a collactive domain for most of Warsaw primary and middle schools. This is only way to validate student licences from those institutions.

Warsaw public schools (collective domain)

---

lib/domains/com/npskrm.txt
npskrm.txt

I have added my school file in the correct location please add the domain to the website

Adding School NPS Koramangala

---

lib/domains/org/saratogausd.txt

School Website: https://www.saratogausd.org/redwood

Redwood Middle School

---

lib/domains/it/edu/itisvallauri.txt

Itis G.Vallauri: https://www.itisvallauri.edu.it/

Add ITIS G.Vallauri

---

lib/domains/ua/edu/krpd.txt

Official website : https://www.duet.edu.ua/en

Add domain for State University of Economics and Technology

---

lib/domains/cat/inscamidemar.txt

New school added to the list

---

lib/domains/net/lcieducation.txt

1. College URL - https://www.lasallecollege.com/
2. My Course URL(2 years) - https://www.lasallecollege.com/business-and-technologies-school/aec-computer-programmer-analyst
3. Parent institution URL - https://www.lcieducation.com/

Adding LaSalle College Montreal

---

lib/domains/vn/edu/phuocbinh.txt

Dear teams,
Please add Phuoc Binh University.
Thanks and regards,

Add Phuoc Binh University

---

lib/domains/it/einaudicorreggio.txt

Re-upload the correct file of Luigi Einaudi school

Add Einaudi Correggio

---

lib/domains/tw/edu/hdut/mail.txt

Added Hungkuo Delin University of Technology

---

lib/domains/au/edu/apc.txt

Australian Pacific College added

---

lib/domains/br/edu/univag.txt

Univag - Centro Universitário official website: http://www.univag.com.br/

Add univag.edu.br to domain list

---

lib/domains/br/edu/unisepe.txt

Add University Unisepe

---

lib/domains/cn/edu/gpnu.txt

Guangdong Polytechnic Normal University
广东技术师范大学
http://www.gpnu.edu.cn/
https://jkxy.gpnu.edu.cn/
http://mail.gpnu.edu.cn/?hl=en_US

add Guangdong Polytechnic Normal University

---

lib/domains/br/edu/fho.txt
lib/domains/br/edu/fho/fho.txt

http://www.fho.edu.br/home.php
http://vestibular.fho.edu.br/cursos/?tag=sistemas-informacao
http://vestibular.fho.edu.br/cursos/?tag=engenharia-computacao
https://registro.br/tecnologia/ferramentas/whois/?search=fho.edu.br
http://www.fho.edu.br/tutoriais-aulas/arquivos/Aluno_Orientacao_Criacao_Email.pdf
Address Av. Dr. Maximiliano Baruto, 500 - Jd Universitário - Araras - SP - Brasil

domain fho.edu.br

---

lib/domains/rs/edu/msstankovic.txt

MS Stankovic

---

lib/domains/ca/perimeterinstitute.txt

Website https://perimeterinstitute.ca/
Info about funding:
https://perimeterinstitute.ca/funding
(inc. a $100 million commitment from the governments of Ontario+Canada)

Add Perimeter Institute, Waterloo, Canada

---

lib/domains/br/edu/senaisp.txt

Official website: https://eletronica.sp.senai.br/
IT related course: https://eletronica.sp.senai.br/curso/80458/109/superior-de-tecnologia-em-eletronica-industrial?Parent=571

Adding senaisp.edu.br domain

---

lib/domains/ua/edu/nupp.txt

a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university
- https://nupp.edu.ua/en/page/os-122-kn-b-en.html
a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.
- https://nupp.edu.ua/en/page/contacts.html

Add The National University «Yuri Kondratyuk Poltava Polytechnic» (Ukraine)

---

lib/domains/com/onmicrosoft/iisfortunato.txt

IIS Giustino Fortunato, Pisticci (MT)
High School in Pisticci, Italy
Official Website: http://www.iisgiustinofortunato.it
Information about IT Department: http://www.iisgiustinofortunato.it/index.php?option=com_content&view=article&id=359&Itemid=1438
We have three years of IT specialization in the 3th, 4th and 5th year with a focus on programming 
http://www.iisgiustinofortunato.it/files/MTIS011001/Quadro_orario_ITT.pdf

create IIS Giustino Fortunato txt file

---

lib/domains/tw/edu/tn/nnkieh.txt

School's Offical Website: https://hs.nnkieh.tn.edu.tw/

Add NNKIEH

---

lib/domains/vn/edu/haugiang.txt

Website: https://haugiang.edu.vn/

Add Department of Education and Training of Hau Giang Province

---

lib/domains/no/vgs/krokeide.txt

Add Krokeide VGS

---

lib/domains/es/colegiotorremalmuerta.txt

Website: https://colegiotorremalmuerta.es/

Add Public school Torre Malmuerta

---

lib/domains/nl/tukampen.txt

A dutch university in kampen
http://www.tukampen.nl

Add TUKampen

---

lib/domains/org/mcdonogh.txt

https://www.mcdonogh.org/
https://www.mcdonogh.org/pdf/Upper%20School%20Course%20Description%20Guide%202020-20211.pdf
- Computer Science and Digital Arts
https://www.mcdonogh.org/community/students/technology-resources/student-device-program

Add McDonogh School

---

lib/domains/iq/edu/esraa.txt

Add Esraa University

---

lib/domains/ie/stmunchinscollege.txt

Emails:
@stmunchinscollege.ie
&
Website:
stmunchinscollege.com

Add St. Munchin's College, Corbally, Limerick, IRL

---

lib/domains/ro/ecotgm.txt

Website: https://colecotransilvaniatgm.ro/

Add "Transilvania" Economic College of Târgu Mureș

---

lib/domains/br/org/isd/edu.txt

**Domain:** [edu.isd.org.br](http://www.institutosantosdumont.org.br/en/)
**Website:** http://www.institutosantosdumont.org.br/en/
**Master Program in Neuroengineering:** http://www.institutosantosdumont.org.br/en/master-program-neuroengineering/
**Domain recognition:** http://www.institutosantosdumont.org.br/area-do-aluno/
https://goo.gl/maps/megS79TVszY8QfPz6

Add Edmond and Lily Safra International Institute of Neurosciences

---

lib/domains/sg/edu/ofs.txt

https://www.ofs.edu.sg/
https://www.ofs.edu.sg/schools/hs/courses/descriptions/#ib-comp-science

Add OFS Singapore

---

lib/domains/lk/edu/sltc.txt

Sri Lanka Technological Campus (sltc.edu.lk) domain added

sltc added to the domains

---

lib/domains/sg/edu/ite.txt

{Institute of Technical Education}
{https://www.ite.edu.sg}
Email Users
[x] Students
[x] Academic/Teaching Staff
Other/Support Staff
Alumni
Graduate School
College (University) or Undergraduate School or equivalent
[x] Community College or equivalent
High School or equivalent
Elementary School or equivalent

Added Institute of Technical Education (Singapore)

---

lib/domains/eg/edu/bisc.txt

Add British International School Cairo

---

lib/domains/com/moringaschool/student.txt

a coding boot camp in Nairobi, Kenya

add Moringa School

---

lib/domains/in/banasthali.txt

Adding My University Name Banasthali Vidyapith.

Adding Banasthali Vidyapith(My University Name)

---

lib/domains/ro/scoalaprincipesamargareta.txt

{Scoala Gimnaziala Principesa Margareta}
{ https://www.scoalaprincipesamargareta.ro/ }
Email Users
[x] Students
[x] Academic/Teaching Staff
Other/Support Staff
Alumni
Graduate School
[x]
College (University) or Undergraduate School or equivalent
Community College or equivalent
[x]High School or equivalent
Elementary School or equivalent
FTR: Proof of ownership: https://www.rotld.ro/whois/?domain=scoalaprincipesamargareta.ro

Scoala Principesa Margareta(new request)

---

lib/domains/jp/ac/u-gakugei.txt

Tokyo Gakugei University has some IT-related courses.
https://www.u-gakugei.ac.jp/english/faculty/
- Informatics Education
- Technology Education
- Education by Artificial Intelligence

Add Tokyo Gakugei University

---

lib/domains/net/vossie.txt

Eduvos
https://www.eduvos.com/

vossie.txt

---

lib/domains/net/vossie.txt

Revert "vossie.txt"

---

lib/domains/ng/edu/interlinkpolytechnic.txt

please add Interlink Polytechnic

Please add Interlink Polytechnic, Ijebu-Jesa, Osun Statee

---

lib/domains/ae/ac/hbmsu.txt

[Hamdan Bin Mohammed Smart University](https://www.hbmsu.ac.ae/)
[Masters in Project Management](https://www.hbmsu.ac.ae/study/masters/master-project-management)
[Leadership](https://www.hbmsu.ac.ae/about/hbmsu-in-brief/leadership)
[Overview](https://www.hbmsu.ac.ae/about/hbmsu-in-brief)

Added Hamdan Bin Mohammed Smart University

---

lib/domains/com/dnsalbarsha.txt

added a new shcool

---

lib/domains/co/edu/jefferson.txt

Create Colegio Jefferson

---

lib/domains/bo/edu/fcpn.txt

Add Universidad Mayor de San Andres - Facultad de Ciencias Puras y Naturales
Add  University Major of San Andres - Faculty of Pure Science and Nature

Add Universidad Mayor de San Andres - Facultad de Ciencias Puras y Naturales

---

lib/domains/th/ac/dru.txt

- University Official Website [https://www.dru.ac.th/](https://www.dru.ac.th/)
- Computer Science Division Website __(I think they working on new website, so it might have a connection timeout issues)__ [https://sci.dru.ac.th/sci.com/](https://sci.dru.ac.th/sci.com/)

Add entry for Dhonburi Rajabhat University

---

lib/domains/cn/edu/shou.txt

i am not sure what do you mean by " connection timed out; no servers could be reached" that you ever said in my previous pull request, as i cannot reach out to you.
!!! PLEASE
ping www.shou.edu.cn (rather than ping shou.edu.cn), it seems our school does not open the direct domain without "www.", but our email address is ***@shou.edu.cn
its official website is https://www.shou.edu.cn
located in Shanghai, China.
its IT college has many courses like: Computer Sience and Technology, Software Engineering, and so on.
all courses are 4 years for bachelor degree):
https://xxxy.shou.edu.cn/6622/list.htm
https://zsjy.shou.edu.cn/2020/0714/c15533a272876/page.htm

please see my comments, thanks a lot

---

lib/domains/tw/edu/tnua/gmcc.txt

Hi I'm a student of Taipei National University of Arts. I would like to use your awesome IDE for my development. Thanks!

add tw edu tnua

---

lib/domains/in/edu/sies.txt
lib/domains/in/edu/sies/gst.txt

sies is a name of the college which has many extentions and sies gst (South Indian Education Society Graduate School Of Technology) provides IT courses the domain of students end with ".gst.sies.edu.in" this is the official site if our college http://www.siesgst.edu.in/

Added South Indian Education Society (sies)

---

lib/domains/in/ac/bmsce.txt

I have added BMS College of Engineering, Bangalore. The official site of college is http://bmsce.ac.in/

Added BMSCE Bangalore

---

lib/domains/com/salesianosdosa.txt

We request a license for the programming department.
Degree in Multi platform App Developer (2 courses program).
https://www.salesianosdosa.com/oferta-educativa/fp-grado-superior/#tab-id-6-active
Qualified as Level 1 (Universitary studies) in the
European Higer Education Area and Bologna Process:
https://www.ehea.info/
Every day languages:
- c
- c++
- java
- python
- .NET
- BASH
- MYSQL
Other:
- Ruby
- PHP
- kotlin

Salesianos Domingo Savio

---

lib/domains/ie/corketb.txt

Website - https://carrigtwohillcc.ie/

Added domain

---

lib/domains/ie/st-andrews/students.txt

Add St. Andrew's College Dublin https://www.sac.ie

Add St. Andrew's College Dublin https://www.sac.ie

---

lib/domains/my/edu/perdanauniversity.txt

added perdana university

---

lib/domains/net/ism-sabis.txt

Website: https://internationalschoolmn.com/
(ism-sabis.net also redirects here)

Add The International School of Minnesota (ism-sabis.net)

---

lib/domains/ac/unikam.txt

Website: [University of Kamina](https://unikam.ac)
We are a **Public University**, we organize several faculties including that of Computer Sciences. We are submitting our **license application**for JetBrains tools for our students to learn in the rules of the art. Thank you and frank collaboration.

Add Université de Kamina

---

lib/domains/org/ushschool/student.txt

Website : http://ushschool.org/

Add Upper Shirley High

---

lib/domains/br/edu/fieb.txt

School's official website:
https://fieb.edu.br/
IT and tech courses offered:
https://fieb.edu.br/curso/eletroeletronica/
https://fieb.edu.br/curso/informatica-para-internet/
https://fieb.edu.br/curso/manutencao-e-suporte-em-informatica/
https://fieb.edu.br/curso/informatica/
https://fieb.edu.br/curso/redes-de-computadores/
WHOIS:
https://registro.br/tecnologia/ferramentas/whois/?search=fieb.edu.br

Add FIEB to the domain list

---

lib/domains/se/ecutbildning.txt

Website: https://ecutbildning.se/
My program that I am teaching in: https://ecutbildning.se/utbildningar/webbutvecklare-inom-net/goteborg/
Proof of the domain: ![image](https://user-images.githubusercontent.com/67270174/123122530-627b9e80-d446-11eb-8e89-ff320405c0c4.png)
Thanks!

The old domain edu.ecutbildning.se is no longer in use

---

lib/domains/cn/edu/sdust.txt

Add Shandong University of Science and Technology

---

lib/domains/my/edu/inhouse.txt

The college of Kuala Lumpur, Malaysia.

update IHM College

---

lib/domains/nl/elu.txt

I have started to study Software Engineering course at ELU this year and I would like to contribute adding this uni to the list and allow other students know JEtBrains

Adding elu to repo

---

lib/domains/de/pfh-goettingen.txt
lib/domains/de/pfh.txt

Domain changed from pfh-goettingen.de to pfh.de

Update and rename pfh-goettingen.txt to pfh.txt

---

lib/domains/ru/ukrtb.txt

https://www.ukrtb.ru/
https://www.ukrtb.ru/about/obrazovanie/

adding UKRTB domain

---

lib/domains/de/ajc-bk/students.txt

Pages with Information about Informatic:
https://www.ajc-bk.de/2009/index.php?option=com_content&view=article&id=202&Itemid=5
https://www.ajc-bk.de/2009/index.php?option=com_content&view=article&id=65&Itemid=5

Added AJC-BK

---

lib/domains/in/net/sai.txt
lib/domains/in/net/saicloudschool.txt

I'm really sorry, but there seems to be a mistake. Instead of sai.txt, it should be saicloudschool.txt. I've made the necessary changes and need your approval for this PR.

Update sai.txt to saicloudschool.txt

---

lib/domains/cn/edu/zjvtit.txt

Add Zhejiang Institute of Communications

---

lib/domains/in/ac/lnmiit.txt

Added The LNM Institute Of Information Technology, Jaipur, Rajasthan, INDIA.
[https://www.lnmiit.ac.in/](https://www.lnmiit.ac.in/)

Added LNMIIT

---

lib/domains/th/ac/mwit.txt

add Mahidol Wittayanusorn to educate domain

Add Mahidol Wittayanusorn

---

lib/domains/de/dzne.txt

German name: Deutsches Zentrum für Neurodegenerative Erkrankungen (DZNE)
Translated: The German Center for Neurodegenerative Diseases
I am a Ph. D. candidate currently employed by the DZNE. I am still awaiting my enrollment (been accepted) to the [Charite](https://en.wikipedia.org/wiki/Charit%C3%A9); however, I still think DZNE should be in this list. The DZNE employs over a hundred graduate students at a time for **DOCTORAL** research of neurodegenerative diseases, for academical purposes.
The license from my old institution just ran out, and I would be without my favorite IDE for at least two months.
Engilsh website: https://www.dzne.de/en
Ph. D. research page: https://www.dzne.de/en/jobs/your-opportunities-at-the-dzne/career-opportunities-for-early-career-researchers/doctoral-researcher …

The German Center for Neurodegenerative Diseases 

---

lib/domains/in/bnmit.txt

University website: https://www.bnmit.org

Added B. N. M. Institute of Technology

---

lib/domains/es/uc3m/alumnos.txt
lib/domains/es/universidadeuropea.txt

Added 2 missing domains:
@universidadeuropea.es
@alumnos.uc3m.es

added UEM and UC3M mail alternative

---

lib/domains/th/ac/piriyalai.txt

Add tops domain level for Piriyalai school

add Piriyalai school

---

lib/domains/edu/somaiya.txt

Added K.J Somaiya Institute

---

lib/domains/org/lshigh.txt

Main Website: https://www.lsprep.org/ (lshigh.org redirects there as well)
[CS Courses](https://www.lsprep.org/apps/pages/index.jsp?uREC_ID=1005885&type=d&pREC_ID=1317193 )
Email Validation PDF (end of page 43 and beginning of 44) : [Student handbook](https://www.lsprep.org/apps/pages/index.jsp?uREC_ID=1010940&type=d&pREC_ID=1320179)

Add La Salle Catholic College Prepratory

---

lib/domains/se/varberg/edu.txt

Add Campus Varberg

---

lib/domains/com/cusdstudent.txt

Clovis Unified School District in Clovis, California, USA

Add Clovis School District

---

lib/domains/th/ac/northbkk.txt

add domain northbkk

---

lib/domains/in/edu/annauniv.txt

University website: https://www.annauniv.edu/
Link to the departments page: https://www.annauniv.edu/department/index.php
Link to the Department of Computer Science and Engineering: http://cs.annauniv.edu/
Website of KDC (Knowledge Data Centre): https://www.aukdc.edu.in/ (This the portal through which we do stuff like paying fees, etc)
For details regarding the email ids provided by the university: https://www.aukdc.edu.in/email-guidelines/

added Anna University

---

lib/domains/uk/ac/aru.txt

Website: https://aru.ac.uk/
Computer courses: https://aru.ac.uk/study/course-search?keywords=computer&location=&levelofstudy=Undergraduate&modeofstudy=&faculty=&availability=
Page where to find email domain: https://aru.ac.uk/contact-us -> answers@aru.ac.uk
Thank you.

Add Anglia Ruskin University domain

---

lib/domains/edu/azwestern.txt

Add Arizona Western College

---

lib/domains/np/edu/tu/ac.txt

Website: https://amritcampus.edu.np/
College Page for CS/IT Faculty:
https://amritcampus.edu.np/departments/computer-science/
Provides Bachelor level IT course of 4 years (8-semesters).
The college has a valid microsoft teams id. Here is a screenshot of ms-teams
Email id: is at top left corner
Another from teams app.

Adds Amrit Science Campus, Kathmandu, Nepal

---

lib/domains/in/ac/gehu.txt

* [Official Website](https://www.gehu.ac.in/content/gehu/en.html)
* [4 years B. Tech course URL](https://www.gehu.ac.in/content/gehu/en/academics/engineering/computer-science-and-engineering/dehradun/courses-offered.html)
* Address: Ambala-Dehradun-Haridwar Rd, Chaudhary Colony, Subhash Nagar, Dehradun, Uttarakhand 248171
* Official website itself has the gehu.ac.in domain.

Added GEHU, Dehradun

---

lib/domains/in/sxconlineclass.txt

Add St. Xavier's College(Autonomous) Kolkata
SXC URL-> https://www.sxccal.edu/
Computer Science MSc. Department SXC-> https://www.sxccal.edu/m-sc-computer-science/
sxconlineclass.in  was recently provided to us for conducting online classes during Covid . Hence it is not listed in the official St. Xavier's College (Autonomous) Kolkata website.

Add St. Xavier's College(Autonomous) Kolkata

---

lib/domains/id/sch/smkn7-smr.txt

Official school website: [https://smkn7-smr.sch.id](https://smkn7-smr.sch.id)

Add smkn7-smr.sch.id

---

lib/domains/at/ac/sfu/mail.txt

Adding Sigmund Freud University in Vienna: https://en.wikipedia.org/wiki/Sigmund_Freud_University_Vienna

Adding SFU

---

lib/domains/id/ac/unisayogya.txt

Adding Universitas 'Aisyiyah Yogyakarta

Add Domain for Universitas 'Aisyiyah Yogyakarta

---

lib/domains/net/ndoverneuil.txt

Name: Notre Dame les Oiseaux Verneuil / NDO Verneuil
Website: https://www.ndoverneuil.com/
Email: name@ndoverneuil.net

Add the domain of my school 

---

lib/domains/pl/mil/akademia/student.txt

to easy find the university in english here is https://www.studies-in-english.pl/serwis.php?s=2332&pok=68768&id=466 link with information about university.
here is redirect link independent to school website in Polish language. https://www.wojsko-polskie.pl/aszwoj/o-akademii/

according to the instructions of add this file

---

lib/domains/in/edu/veltech.txt

Reverts JetBrains/swot#11867
Sir/ Madam, I have raised another request as i am unable to get the free pass and saying institution is not their

Revert "Create veltech.txt"

---

lib/domains/sk/piaristi-pd.txt

Add domain "piaristi-pd.sk"

---

lib/domains/de/jfg-augsburg/stud.txt

https://jakob-fugger-gymnasium.de/
https://jakob-fugger-gymnasium.de/lernen-am-jfg/faecher-a-z/informatik

Jakob-Fugger-Gymnasium Augsburg hinzugefügt

---

lib/domains/za/ac/myuct.txt

student email using @myuct.ac.za
course website: https://cs.uct.ac.za

web: https://uct.ac.za [ University of Cape Town ]

---

lib/domains/eus/olabide.txt

Add Olabide Ikastola Koop. Elk.

Add Olabide Ikastola Koop. Elk.

---

lib/domains/ci/edu/ujlg.txt

Université Jean Lorougnon Guédé
https://ujlog.ci/

Added university "Université Jean Lorougnon Guédé" to domains list

---

lib/domains/br/edu/unichristus.txt

Official site: https://unichristus.edu.br/
Page of the Information Systems course: https://unichristus.edu.br/graduacao/sistemas-de-informacao/
Currently, the domain unichristus.edu.br is available only for teacher's emails, not for students.

Adding Centro Universitário Christus - Unichristus

---

lib/domains/vn/edu/ispace.txt

Request add My school (iSPACE vocational training college - Trường Cao đẳng An ninh mạng iSPACE) to JetBrains' list
My school's website: www.ispace.edu.vn
Thanks & Best Regards!

Trường Cao đẳng An ninh mạng iSPACE

---

lib/domains/de/mpia.txt

Alias to already existing mpia-hd.mpg.de

Add mpia.de

---

lib/domains/net/zszwolsztyn.txt

Zespół Szkół Zawodowych Wolsztyn
[file.zip](https://github.com/JetBrains/swot/files/6790496/file.zip)

Please add ZSZWolsztyn

---

lib/domains/br/edu/fcarp.txt

College: http://fcarp.edu.br/ 
TI Course: http://fcarp.edu.br/nossos-cursos/graduacoes/gestao-da-tec-da-inf/identificacao

Added Fcarp.edu.br

---

lib/domains/ro/e-racovita.txt

Add National College "Emil Racovita" http://www.e-racovita.ro to the school list.

Add National College "Emil Racovita" Cluj-Napoca

---

lib/domains/sn/edu/isep-thies.txt

institut supérieur d'enseignement professionnelle de thies

---

lib/domains/tr/edu/erbakan.txt

E-Mail Domain for Academic Members

Necmettin Erbakan University

---

lib/domains/de/bs-erlangen.txt

add berufsschule erlangen

---

lib/domains/id/or/alghifaribatanghari.txt

https://www.alghifaribatanghari.or.id

Add "Muhammadiyah Boarding School Abudzar Al-Ghifari"

---

lib/domains/net/sandi.txt

San Diego Unified School District
All staff emails use the sandi.net domain
District webpage at https://www.sandi.net

Added sandi.txt for SDUSD

---

lib/domains/co/edu/unihorizonte.txt

Add Unihorizonte Colombia
https://www.unihorizonte.edu.co

Add Unihorizonte Colombia

---

lib/domains/ae/ac/aau.txt

Adding new university domain for access to educational purpose

Adding University domain for educational purpose

---

lib/domains/ec/edu/ulvr.txt

Universidad Laica Vicente Rocafuerte de Guayaquil

Universidad LVR

---

lib/domains/au/edu/kaplanstudent.txt

Add Kaplan Business School

---

lib/domains/fr/esh64.txt

Create Ensemble Scolaire Hazparne

---

lib/domains/ua/edu/op/stud.txt

1. https://opu.ua/en
2. https://opu.ua/en/education/programs
3. https://opu.ua/en/staff/staffaccount

add new ua edu op domain

---

lib/domains/au/edu/academies/studentmail.txt

Domain: studentmail.academies.edu.au

Added Academies Australasia

---

lib/domains/ua/edu/nlu.txt

Yaroslav Mudryi National Law University, UA

added nlu.edu.ua

---

lib/domains/cn/edu/cduestc.txt

the university official website URL:http://www.cduestc.cn/

add Chengdu College of University of Electronic Science and Technology

---

lib/domains/ca/thecea.txt

Adding Langara Centre for Entertainment Arts

Langara centre for entertainment arts

---

lib/domains/nz/school/whangamata.txt

Added Whangamata Area School

---

lib/domains/it/edu/iti-marconi.txt

My pull request

---

lib/domains/hk/edu/elegantia/stu.txt

School website: [Elegantia College (Sponsored by Education Convergence)](https://www.elegantia.edu.hk/)
Students-mail-format(end with) : `@stu.elegantia.edu.hk`
Lesson proof and Teaching Schedules : http://web.elegantia.edu.hk/subjects/comp/cit_teacher.html

Add-student-mail-format

---

lib/domains/ug/ac/kab.txt

Kabale University
www.kab.ac.ug
offers Bachelor of Computer Science

Kabale University

---

lib/domains/br/edu/cesmac/academico.txt

*@academico.cesmac.edu.br
https://cesmac.edu.br/

add CESMAC university

---

lib/domains/ec/edu/lametro.txt

Instituto Metropolitano de Diseño, "La Metro"

Instituto Metropolitano de Diseño, "La Metro"

---

lib/domains/com/wildcodeschool.txt
lib/domains/com/wildcodeschool/student.txt

Adding Wild Code School from Europe !

Wild code school added

---

lib/domains/education/aivancity.txt

Adding aivancity (https://www.aivancity.ai/)

aivancity.education

---

lib/domains/kr/go/goe/suwondasanm.txt

Please add my middle school to the list.
Thank you.

Please add my middle school to the list.

---

lib/domains/study/sit.txt
lib/domains/university/sit.txt

I have created a study folder for adding SIT. I have also an official letter from a university .

Add SIT to study

---

lib/domains/net/zszwolsztyn.txt
lib/domains/si/osbrod.txt

Add Osnovna Sola Vizmarje Brod

Add Osbrod.si

---

lib/domains/es/esdmadrid.txt

Pull request to include ESDMadrid (Madrid School of design) to the list of Schools and email domain setup

Add ESDMadrid

---

lib/domains/my/edu/intec.txt

Please Add Intec Education College

---

lib/domains/co/edu/colegionuevocampestre.txt

https://www.colegionuevocampestre.edu.co/

Please add school nuevo campestre

---

lib/domains/br/unitoledo.txt

http://www.unitoledo.br
http://www.unitoledo.br/graduacao/cursos/

Include domain

---

lib/domains/org/lendi.txt

Website for college: https://lendi.org/
Admission procedure mentioning course duration: https://lendi.org/index.php?option=com_content&view=article&id=278&Itemid=1276
Page showing `lendi.org` email addresses for faculty: https://lendi.org/index.php?option=com_content&view=article&id=203:contact&catid=2&Itemid=781

Adds Lendi institute of engineering and technology

---

lib/domains/org/gfacademy.txt

Adding Greens Farms Academy (GFA) High School - gfacademy.org (Westport, CT, USA)

Adding Greens Farms Academy

---

lib/domains/com/fondespierre.txt

Official Website : https://fondespierre.com/

Add Fondespierre RH

---

lib/domains/global/dwight.txt

School's website: [https://www.dwight.edu/dwight-global-online-school](url)
Address: 291 Central Park West, New York, NY 10024, United States
Page showing IB Computer Science HL (two-year course): [https://www.dwight.edu/academics/introduction-to-the-ib/curriculum-guide/diploma-program](url)
You'll find the computer science course if you scroll down and open the "Technology" dropdown.
I can show proof that I was given an email ending in @dwight.global by the school through an email that the school's registrar sent to me and my family when I was first admitted.
You'll find a PDF of the email below.
[Gmail - Fwd: Felipe - Preparing for Next Year at Dwight Global.pdf](https://github.com/JetBrains/swot/files/6942821/Gmail.-.Fwd.Felipe.-.Preparing.for.Next.Year.at.Dwight.Global.pdf)

Add school: Dwight Global

---

lib/domains/de/rheinahrcampus.txt

E-mail Prefix : @rheinahrcampus.de

New University Rhein-Ahr-Campus Hochschule Koblenz 

---

lib/domains/org/fcusd/student.txt

Added new School - Sutter Middle School (https://www.fcusd.org/SMS)

---

lib/domains/my/edu/moe-dl.txt

Every student in Malaysia has a MOE email as this: `m-<6-digits>@moe-dl.edu.my`. As many schools are involved, I am not sure that how should I fill `moe-dl.txt`. It is now the school I am currently in, edit it if necessary.
I will be appreciated if you could add this to the repo.  Thanks in advance.

Add government schools in Malaysia

---

lib/domains/org/staracademies/ebpreston.txt

added org/staracademies/ebpreston.txt 
School : Eden Boys’ School, Preston
Website:  https://www.edenboyspreston.com

Please Can you add my High School.

---

lib/domains/il/k12/amalnet/na.txt

Add "Multidisciplinary science and arts Amal Nahariya" school

---

lib/domains/tz/ac/mustudent.txt

Added mustudent.ac.tz domain

---

lib/domains/au/edu/vit/student.txt

I added Files for the domain student.edu.au

Added Victoria Institute of Technology

---

lib/domains/au/edu/vit/student.txt
lib/domains/ua/edu/nuph.txt

We are using JetBrains products for support and customization LMS Moodle

Add nuph.edu.ua domain

---

lib/domains/au/edu/aib/study.txt

Adding school Australian Institute of Business

Adding aib.edu.au

---

lib/domains/bo/edu/fhumanidades-uagrm.txt

Each faculty is managed independently from the University, which is why we have a different domain for each faculty

Add the Faculty of Humanities of UAGRM

---

lib/domains/us/ma/k12/lynnfield.txt

Website: https://www.lynnfield.k12.ma.us/high/
Link to Course: https://drive.google.com/file/d/11JIKf6rXUhx5rTzmi98E1B4vDSgtMi3M/view (Page 26, Page 28 on PDF).
Link with domain proof: https://www.lynnfield.k12.ma.us/high/contact-us/

Added lynnfield

---

lib/domains/co/edu/systemplus.txt

SystemPlus - Red Nacional de Educación 
SystemPlus - National Education Network

Add - SystemPlus - Red Nacional de Educación

---

lib/domains/ph/edu/cu.txt

Add Capitol University domain cu.edu.ph

Add cu.edu.ph domain

---

lib/domains/co/edu/pca.txt

https://pca.edu.co/wp/
https://pca.edu.co/wp/ingenieria-de-sistemas/

Add Politécnico de la Costa Atlántica University

---

lib/domains/au/edu/pac.txt

Add Prince Alfred College

---

lib/domains/tw/edu/tpcu.txt

university web : https://www.tpcu.edu.tw/bin/home.php

Added Taipei City University of Science and Technology

---

lib/domains/se/theindiequest.txt

The Indie Quest is a game development school in Sweden, offered by the Tingsryd municipality as part of the Swedish public education for adults. 
The school physically takes place at Spelkollektivet, a co-working space for game developers.
Main URL: https://www.theindiequest.se
Page specifying the length of the course (can be completed as fast as 1 year, but students are officially enrolled for 18 months): https://www.theindiequest.se/curriculum/
Official municipality site showing information about the school (in Swedish): https://tingsryd.se/barn-och-utbildning/vuxenutbildning/yrkesutbildningar-som-ger-jobb/spel-och-programutveckling/
Note: The licenses would only be used by the students at The Indie Quest, not the people working from Spelkollektivet.

The Indie Quest

---

lib/domains/id/ac/uma/staff.txt

please approve this pull request for added **University of Medan Area**, Indonesia, Thank You

Register Campus University of Medan Area

---

lib/domains/my/edu/kuptm.txt

Link for official website - http://www.kuptm.edu.my/
URL for IT-related course - http://www.kuptm.edu.my/index.php/bachelor-of-information-techology-honours-in-computer-application-development

Adding Kolej Universiti Poly-Tech Mara Kuala Lumpur

---

lib/domains/tw/edu/ltu/stumail.txt
lib/domains/tw/edu/ltu/teamail.txt

Thanks for your help ~ 
add two email format of Ling Tung University . 
please have a look

Add Ling Tung University  . Teacher & Student Email  format.

---

lib/domains/br/edu/unirios.txt
unirios.txt

We have the Graduate Course of Information Systems, and our students could develop in high level when use a full Program.

Add University Center of São Francisco's River (UNIRIOS)

---

lib/domains/com/ltuc/student.txt

Add student.ltuc.com

---

lib/domains/no/gokstadakademiet.txt

https://www.gokstadakademiet.no/
https://www.gokstadakademiet.no/backend-utvikling
https://www.gokstadakademiet.no/kontaktoss

Add Gokstadakademiet

---

lib/domains/se/tabyenskilda/student.txt

Add Täby Enskilda Gymnasium

---

lib/domains/ua/ck/phymly.txt

add new Fyzyko-Matematycheskyy Lytsey "PHYMLY"

---

lib/domains/be/stben.txt

Communauté scolaire Saint-Benoît, Habay-la-Neuve

Add stben domain

---

lib/domains/br/edu/ufcat/discente.txt

Add [UFCAT](https://catalao.ufg.br/) domain in JetBrains.

Add domain UFCAT

---

lib/domains/at/hak-liezen.txt

Hello, I want to add my school.
if you need a real url: https://hak-liezen.at

add my school: hak-liezen

---

lib/domains/org/vumc.txt

Hello,
I am academic staff supporting research at Vanderbilt University Medical Center. We contacted Jetbrains Sales inquiring about discounted licenses for academic research usage, and were told that we can apply for student / teacher licenses for this.
Official VUMC Website and email domain: https://www.vumc.org/
Example of an IT-focused educational offering by VUMC - Masters or Doctoral degrees in Bioinformatics: https://www.vumc.org/dbmi/education/predoctoral_training
VUMC is closely linked but a distinct entity to Vanderbilt University (vanderbilt.edu), and both institutions have research labs and graduate students.

Add Vanderbilt University Medical Center - vumc.org

---

lib/domains/br/edu/ufopa/discente.txt

Official Website: http://www.ufopa.edu.br/
Computer Science Subjects: http://www.ufopa.edu.br/cienciadacomputacao/ofertas-de-disciplinas/2020-primeiro-semestre/2020-primeiro-semestre-bcc
Screenshot of University Webmail: https://i.imgur.com/qlBGNce.png
Other important links about university email:
http://www.ufopa.edu.br/ufopa/comunica/noticias/discentes-devem-obter-e-mail-institucional-para-acessar-plataformas-de-ensino-remoto/
http://www.ufopa.edu.br/ufopa/comunica/noticias/ctic-cria-dominio-de-e-mail-institucional-para-discentes-da-ufopa/

Add UFOPA - Universidade Federal do Oeste do Pará

---

lib/domains/tr/edu/gaziantep/student.txt

The email domain can be verified with the following URLs.
http://www.gaziantep.edu.tr/google-apps/
http://www.gaziantep.edu.tr
https://www.gantep.edu.tr/
http://mail2.gantep.edu.tr/

Add a new university domain "Gaziantep University"

---

lib/domains/net/uni-gjilan.txt

I added the University Kadri Zeka from Gjilan, Kosovo.
https://www.uni-gjilan.net/en/contact/

Added University Kadri Zeka

---

lib/domains/pk/edu/nu/student.txt

Added National University of Computer and Emerging Sciences Pakistan to this repository.
University Domain: https://nu.edu.pk
The students email looks like this : @nu.edu.pk
Email domain validation: https://hunter.io/verify/i140535@nu.edu.pk
Can take a look into [this](https://nu.edu.pk/home/ContactUs) as a reference.

Added FAST NUCES Pakistan domain

---

lib/domains/de/thga.txt

Technische Hochschule Georg Agricola
University of Applied Sciences Georg Agricola
https://www.thga.de/

Please Add University of Applied Sciences Geog Agricola to the Repository

---

lib/domains/vn/edu/hpmu.txt

add-new-school : hpmu.edu

---

lib/domains/ua/edu/khmnu.txt

site university - https://www.khnu.km.ua/root/page.aspx

Please add university Khmelnytsky National University

---

lib/domains/academy/htk.txt

University of Applied Sciences Europe GmbH (ehem. BiTS/ btk) - Berlin, Hamburg, Iserlohn

---

lib/domains/uk/co/utc-silverstone.txt

College website: https://www.utc-silverstone.co.uk/
Curriculum page, showing computer science as a course: https://www.utc-silverstone.co.uk/curriculum/a-level/
Page proving email structure and domain name: https://www.utc-silverstone.co.uk/contact-us/teaching-staff-2/

Add files via upload - Silverstone UTC, UK

---

lib/domains/uk/co/iscaexeter.txt

Add Isca academy 

---

bredonschool.txt
lib/domains/uk/co/thekingsschool.txt

https://www.thekingsschool.co.uk/

New Request for The King's School

---

lib/domains/kr/hs/dolma.txt

Add dolma.hs.kr

---

lib/domains/org/obps.txt

I added my school to the Lib -> Domains -> Org
Our Site https://www.oldbridgeadmin.org

added Old Bridge Township Public Schools

---

lib/domains/ua/edu/knlu.txt

Added .txt file which contains univ name

Kyiv National Linguistic University

---

lib/domains/jp/seian.txt

Nice to meet you.
I would like to send a pull request to add Seian University of Art and Design to the JetBrains Student Pack.
Thank you very much for your cooperation.

add Seian University

---

lib/domains/nl/Amalyceum.txt
lib/domains/nl/amadeuslyceum.txt

School name : Amadeus Lyceum
Schooldomain: amadeuslyceum.nl
School contact: https://amadeuslyceum.nl/contact

Request to Add domain of my school

---

lib/domains/ee/viljandiwaldorf.txt

Viljandi Vaba Waldorfkool added

Viljandi Vaba Waldorfkool added

---

lib/domains/org/fulton58.txt

Fulton Public Schools in Fulton, Missouri, USA

Add Fulton Public Schools

---

lib/domains/com/ucreativa.txt

This is the formal request for adding the Universidad Creativa to the student program

Add Universidad Creativa domain

---

lib/domains/mx/tecvalles
lib/domains/mx/tecvalles.txt

Please could you add my University?
[Tecnológico Nacional de México Campus Instituto Tecnológico de Ciudad Valles](http://www.tecvalles.mx/web/)

Add tecvalles.mx

---

lib/domains/vn/edu/penphy.txt
lib/domains/vn/edu/thcsthuanhung.txt

Add domain **thcsthuanhung.edu.vn** and **penphy.edu.vn**
> We add 2 domains because our school uses 2 domains to provide Email for Teachers and Students (Proof of using 2 domains in **4. An URL of a page at the official school website that says that students use this email domain**).
**1.** The school official website URL
**https://thcsthuanhung.edu.vn/** 
**2.** The school street address, including the city
**Tan Phu Area, Thuan Hung Ward, Thot Not District, Can Tho City, Vietnam**
**3.** An URL of a page on the official website where the school offers an IT-related long-term course
- https://thcsthuanhung.edu.vn/to-toan/introduction-to-php-syllabus-60.html
- https://thcsthuanhung.edu.vn/to-toan/introduction-to-web-design-syllabus-61.html
- …

Create thcsthuanhung.txt and penphy.txt

---

lib/domains/ca/qc/csdraveurs/edu.txt

Website URL: https://erabliere.cssd.gouv.qc.ca
Address: 500 Rue de Cannes, Gatineau, QC J8V 1J6

Add ca.qc.csdraveurs.edu Domain

---

lib/domains/vn/edu/cantho.txt

**Sở GD&ĐT Cần Thơ**
Department of Education and Training of Can Tho City
Website : http://cantho.edu.vn/

Add cantho.edu.vn

---

lib/domains/it/lum.txt

University official website: [https://www.lum.it](https://www.lum.it/en/)
URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: [Bachelor of Science degree in Engineering Management](https://www.lum.it/en/management-engineering/)
IT related courses:
- Fundamentals of computer science
- Databases and Information Systems
- Machine Learning and Artificial Intelligence
Contacts: [https://www.lum.it/rubrica](https://www.lum.it/rubrica/)

Add LUM University

---

lib/domains/id/ac/undira.txt

Add files via upload - Add undira

---

lib/domains/de/hgs-singen.txt
lib/domains/online/hgs-singen.txt

Hohentwiel Gewerbeschule Singen
https://hgs-singen.de 
IT: https://hgs-singen.de/Profil-Informationstechnik.html
Teachers: @hgs-singen.de
Students: @hgs-singen.online

Add 2 domains for Hohentwiel Gewerbeschule Singen

---

lib/domains/eg/edu/alsafwa.txt

>###  the website have some urgent bugs but we working on it

Add domain : eg - edu - alsafwa

---

lib/domains/vn/edu/tkh.txt

Trường trung học phổ thông Thanh Khê, Đà Nẵng City, VietNam
http://tkh.edu.vn/

tkh.edu.vn

---

lib/domains/in/snuindia.txt

University Domain: https://snuniv.ac.in/
Student Email ID: pratik.009169@snuindia.in
Student Email ID is provided on www.snuindia.in domain

Added Sister Nivedita University

---

lib/domains/br/edu/faculdadescearenses.txt

Add Faculdade Cearense 🇧🇷

---

lib/domains/hr/efri.txt

Added Univerity of Rijeka, Faculty of Economics and Business to domain

Added EFRI to hr domain

---

lib/domains/uk/org/bristolfreeschool.txt

Add Bristol Free School to lib please.

---

lib/domains/com/supdeweb-strasbourg.txt

Hi, I wanted to add my school :
[https://supdeweb.com/strasbourg/](https://supdeweb.com/strasbourg/)

Adding Supdeweb Strasbourg

---

lib/domains/se/edugrade/edu.txt

https://edugrade.com/
https://edugrade.com/yh-utbildning/it/agil-javautvecklare-distans/

edu.edugrade.se

---

lib/domains/nz/school/stpeterspn.txt

Link to school website: [https://www.stpeterspn.school.nz/](https://www.stpeterspn.school.nz/)

Add St Peter's College

---

lib/domains/pl/edu/stonabemowie.txt

STO School Complex are looking forward to give their students an opportiunity to use the best Dev Tools :D

stonabemowie.edu.pl

---

lib/domains/be/dbhaacht.txt

Hello,
We like to use the intellij product for Education.
Is it possible to add the domain for use.
Thans, Robin

Add dbhaacht.be

---

lib/domains/in/edu/sbjit.txt

Added S. B Jain Institute

---

lib/domains/vn/edu/nttu.txt

Add domain : vn - edu - nttu

---

lib/domains/sg/edu/ics.txt

Hi id like to add our school to the license

Add my School to the list

---

lib/domains/com/idbbxl.txt

Add idbbxl.com

---

lib/domains/it/linkstudents.txt

For More information: https://www.unilink.it/

Add request 'Link Campus University', Rome, Italy

---

lib/domains/id/ac/ubl.txt

Official University Website: https://ubl.ac.id/
The official website where a long-term (>1 year) IT related study is offered by the university : http://fik.ubl.ac.id/

Adding Bandar Lampung University

---

lib/domains/pl/edu/brzozowa5.txt

High school where one of the faculties is computer science.
School website: https://brzozowa5.edu.pl/

Add high school

---

lib/domains/es/easda.txt

Add EASDA Alicante domain easda.es

Add EASDA Alicante

---

lib/domains/ua/edu/istu.txt

Add ISTU Univeristy

---

lib/domains/com/ecole-webstart.txt
lib/domains/com/mjm-design.txt

Those twos school were added with fr domain. But we need to have com domain too.
schools 's websites : 
https://mjm-deisgn.com
https://ecole-webstart.com

update two schools with com domain

---

lib/domains/uk/co/nottinghamhigh.txt

Notthing really to say. just need this to apply for a student licence

Add a licence for nottingham high school

---

lib/domains/ke/ac/jooust.txt

University URL: https://www.jooust.ac.ke/
URL for long term course offered: https://www.jooust.ac.ke/index.php/2016-03-08-12-16-32/2016-03-11-10-55-30/schools/school-of-informatics-and-innovative-systems-2

Added JOOUST

---

lib/domains/ua/edu/zsea/stu.txt

Webpage: https://www.znu.edu.ua/
Address: 66, st. Zhukovsky, m. Zaporizhzhya, 69600, Ukraine
Phone +38 061 228 75 08

Add Zaporizhzhia National University

---

lib/domains/ua/edu/lnau.txt
lib/domains/ua/lviv/lnau.txt

the university official website: http://lnau.edu.ua/
IT-related course is offered by the university: http://lnau.edu.ua/lnau/index.php/uk/f-s/mex/kafinfteh2020/infokafinfteh.html
contacts: http://lnau.edu.ua/lnau/index.php/uk/xsa.html
other may be useful links: 
http://lnau.edu.ua/lnau/index.php/uk/f-s/mex/kolektfakinfteh20.html
http://lnau.edu.ua/lnau/index.php/uk/f-s/mex/kafinfteh2020/navrobinfteh2020.html

add Lviv National Agrarian University

---

lib/domains/it/edu/liceoischia.txt

The school's main website is https://liceoischia.edu.it

Add Liceo Statale "Ischia"

---

lib/domains/th/ac/cmkl.txt

Request licenses for CMKL University (https://www.cmkl.ac.th)

Added CMKL University domain

---

lib/domains/com/soraschools.txt

Sora is an accredited online high school based in Atlanta, Georgia. They have an engineering track that requires JavaScript and TypeScript programming, for which IntelliJ Ultimate would be excellent.
https://soraschools.com/

Add Sora High School (https://soraschools.com/).

---

lib/domains/dz/inttic.txt

Add INTTIC Oran to JetBrains Products to get free access to all the products that JetBrains are provided.

Add INTTIC Oran

---

lib/domains/org/morgank12.txt

Morgan County Schools District, Alabama
AP Computer Science
[Morgank12.org Website](https://www.morgank12.org)

Add Morgan County School District, Alabama, USA

---

lib/domains/sa/gov/moe/rg.txt

Please merge change for adding Saudi government school

Added Saudi government school

---

lib/domains/ro/liceupetrila.txt

https://liceupetrila.ro
https://liceupetrila.ro/oferta-educationala/ (Computer Science related field - program of 4 years of study)

Add liceupetrila.ro domain

---

lib/domains/hk/edu/cihe.txt

URL: https://www.cihe.edu.hk/en/home/index.html
School of CIS URL: https://cis.cihe.edu.hk
Course provided by CIS: https://www.cihe.edu.hk/en/schools-and-offices/schools-and-departments/school-of-computing-and-information-sciences/introduction/index.html

Register CIHE in school list

---

lib/domains/fr/estia/etu.txt

Adding ESTIA to university license support

Add ESTIA university files via upload

---

lib/domains/iq/edu/huc.txt

The following link is for the Department of medical equipment technology engineering in the middle of the page there is a dropdown for Department Curriculum, you can see that in stage 1 they take Computer engineering, and in stage 2 Computer science
https://huc.edu.iq/medeng.php
Please use google translate as the website is still in development and as of me writing this the website is only in the Arabic language 
You can see in webometrics website for web ranking of universities we are at the rank 112 in Iraq
https://www.webometrics.info/en/aw/iraq?page=1
An URL of a page at the official website that says that students use this email domain:
https://huc.edu.iq/Students_lg.php

Al-Hadi University College

---

lib/domains/eg/edu/aiu.txt

Add Alamein International University

---

lib/domains/br/org/fundacaofemar.txt

Created fundacaofemar.txt

---

lib/domains/sg/edu/sas.txt

Adding My School to Jetbrains SWOT

Adding Singapore American School

---

lib/domains/org/nordakademie.txt

Added NORDAKADEMIE University of Applied Sciences

Added NORDAKADEMIE University of Applied Sciences

---

lib/domains/cn/ac/iccas.txt

our institute site is  http://www.ic.cas.cn , please add this mail domain, thanks

add iccas.ac.cn domain

---

lib/domains/com/maharishividyamandirch.txt

Maharishi Vidya Mandir, Chennai,  India

Maharishi Vidya Mandir

---

lib/domains/org/bphawks.txt

https://www.bpsd.org/bethelparkhighschool_home.aspx
309 Church Road
Bethel Park, PA, United States of America 15102
https://www.bpsd.org/BPHSMath.aspx
https://www.bpsd.org/Downloads/BPSD%20Schoology%20login%20directions2.pdf

Adding School Email

---

lib/domains/us/pusd.txt

School given emails for Pasadena, California @pusd.us
https://www.pusd.us/ District Site

Add Pasadena Unified School District emails

---

lib/domains/org/alpinesd
lib/domains/org/alpinesd.txt

adding school to JetBrains

---

lib/domains/de/onbtineuss.txt

I have 2 more years to go, so it would be nice if i could continue to use your software for my lessons.

JetBrains student program

---

lib/domains/ng/edu/dui.txt

Url of the schools website: https://dui.edu.ng/
Url of one of the courses offered: https://dui.edu.ng/department-of-physical-mathematical-sciences/#1586000257705-8592a6d1-c304

added dominican university ibadan

---

lib/domains/pl/edu/pwsz-gniezno/studenci.txt

Add PWSZ Gniezno

---

lib/domains/vn/edu/ldxh.txt

Add University of Labour Social Affairs 2
Website: http://ldxh.edu.vn/

Add University of Labour Social Affairs 2

---

lib/domains/id/ac/poliupg.txt

our site is https://www.poliupg.ac.id, please add this mail domain, thanks

add Politeknik Negeri Ujung Pandang

---

lib/domains/co/edu/unimonserrate.txt

Fundación Universitaria Monserrate - Unimonserrate

Solicitud de Licencia Académica

---

lib/domains/de/max-eyth-schule/schueler.txt

Added the Max-Eyth-Schule in Kassel, Germany. 
[Their website](https://www.max-eyth-schule.de).

Max-Eyth-Schule

---

lib/domains/hu/uni-mate/stud.txt

I see that at the moment only Phd student addresses work. I added the undergrad address.

Add MATE University Student

---

lib/domains/id/ac/itpln.txt

I'm adding the Institut Teknologi PLN Jakarta domain.

adding Institut Teknologi PLN Jakarta domain

---

lib/domains/uk/co/ewellcastle.txt

URL to proof of Computer Science study at A-level
https://www.ewellcastle.co.uk/sixth-form/the-curriculum/
[ewellcastle.txt](https://github.com/JetBrains/swot/files/7520481/ewellcastle.txt)

Request to add Ewell Castle School

---

lib/domains/bg/trakia-uni.txt

trakia-uni.bg

---

lib/domains/th/ac/jv.txt

domain jv.ac.th from Thailand
(ChakkaratWittaya School)
https://www.jv.ac.th

Add domain jv.co.th

---

lib/domains/it/lum/studenti.txt

University official website: [https://www.lum.it](https://www.lum.it)
URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: [Bachelor of Science degree in Engineering Management](https://www.lum.it/en/management-engineering/)
IT related courses:
Fundamentals of computer science
Databases and Information Systems
Machine Learning and Artificial Intelligence
Contacts: [https://www.lum.it/rubrica](https://www.lum.it/rubrica)

Add LUM University - student accounts

---

lib/domains/de/rbbk-dortmund.txt

Added rbbk-dortmund.de as new technical vocational college.

Added rbbk-dortmund.de

---

lib/domains/hu/szamalk-szalezi.txt
lib/domains/hu/szamalk-szalezi/diak.txt

SZÁMALK-Szalézi Technikum és Szakgimnázium

Adding SZÁMALK-Salesian Technical School

---

lib/domains/pl/liceumwchmurze.txt

Liceum w Chmurze added

---

lib/domains/my/edu/aswara.txt

We offer a 3 years degree course in game production, we use Unity as one of our game development tool, kindly prefer  https://www.aswara.edu.my/webportal/ms/fakulti-animasi-multimedia/ where the website is in our native language.

add aswara.txt

---

lib/domains/nz/school/pakuranga/student.txt

Website: https://www.pakuranga.school.nz/
Email: xxxx@student.pakuranga.school.nz

Add files via upload - Pakuranga College, New Zealand

---

lib/domains/tn/rnu/isim.txt

Adding "Higher Institute of Informatics of Medenine" located in Tunisia.

Added my current Institute

---

lib/domains/co/edu/uvirtual.txt

Adding "Universidad Virtual Internacional" located in Colombia.

adding Universidad Virtual Internacional

---

lib/domains/it/edu/liceochinimichelangelo.txt

Hello, 
I'm a Computer Science teacher at a public school in Camaiore, Lucca, Italy. I'd like to qualify for Student/Teacher licenses for Clion.
Thank you!
Francesco Volpi.

Hi! Italian Computer Science teacher here!

---

lib/domains/pl/edu/tzndg/student.txt

This is the main school domain: https://tzndg.edu.pl/

Added Techniczne Zakłady Naukowe w Dąbrowie Górniczej

---

lib/domains/pl/kopernikus.txt

ZS 6 im. Mikołaja Kopernika
sekretariat@kopernikus.pl
- [x ] Elementary School or equivalent

Please add ZS 6 im. Mikołaja Kopernika

---

lib/domains/org/lrsd.txt
lib/domains/org/lrsd/students.txt

District Website - https://www.lrsd.org
Proof of valid domains - https://www.lrsd.org/cms/lib/AR02203631/Centricity/Domain/4/Online%20Resources%20-%202020.pdf

Add Little Rock School District

---

lib/domains/tn/ucar/istic.txt

Created istic.txt

---

lib/domains/mm/edu/kyauksetu.txt

Hi, Sir, This is my fixed file txt. Pls: re check again. I'm sorry for the inconvenience.

{Re} adding Technological University of Kyaukse

---

lib/domains/mm/edu/tukalay.txt

Sir, Please Check My Request. Thank you.

Added Technological University of Kalay

---

lib/domains/com/mygbiz/ust-ics.txt

Adding University of Santo Tomas
Adding the URL link for UST (University of Santo Tomas)
https://www.ust.edu.ph/

Added file for University of Santo Tomas

---

lib/domains/mm/edu/hbtu.txt

Sir, please merge my university, thank youuu!

Add Technological University of Hmawbi

---

lib/domains/cz/gymspit.txt

Please add my school
[https://gymspit.cz/](https://gymspit.cz/)

Gymnázium Špitálská

---

lib/domains/in/net/gkmims.txt

Providing college URL - "https://www.gkmims.net.in/b.sc.php"

Adding GKMIMS to jetbrains college list

---

lib/domains/lv/riga/edu.txt
lib/domains/lv/rvt/students.txt

Added e-mail domain for Riga schools (`@edu.riga.lv`).

Riga schools

---

lib/domains/lt/azuolynogimnazija.txt

http://www.azuolynogimnazija.lt/

klaipedos azuolyno gimnazija

---

lib/domains/it/edu/isrosselliaprilia.txt

New High School Carlo e Nello Rosselli

---

lib/domains/ru/spcras.txt

website https://spcras.ru/ ; IT related course: https://spcras.ru/education/postgraduate/

add SPC RAS

---

lib/domains/org/rtnj.txt

Added Randolph Middle School

---

lib/domains/education/ukr/harmony.txt

**Domain for G Suite for Education:** `harmony.ukr.edu`
**Lyceum main site**: `gymnasium-boyarka.in.ua` (different due to few renames in past 10 years)

Added Bayarka Academic Lyceum _Harmony_.

---

lib/domains/cn/edu/sxie.txt

Please add Shanxi Institute of Energy, thank you.

Add Shanxi Institute of Energy

---

lib/domains/pl/edu/sp341.txt

Hi,
Please add sp341.edu.pl domain.
As proof, whois entry for the domain:
https://dns.pl/en/whois?domainName=sp341.edu.pl

Add sp341.edu.pl

---

lib/domains/eu/schoolmath.txt

- the school official website URL: https://omg-bg.com/
- the school street address, including city and country: https://goo.gl/maps/H4NAtziVnfKw7twV7
Thanks in advance.

add High School of Mathematics "Acad. Kiril Popov"

---

lib/domains/in/amceducation.txt

Colleg Official Website URL: https://www.amceducation.in/
URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university :  https://www.amcgroup.edu.in/AMCEC/Best-Computer-Science-Engineering.php

Add amceducation.in

---

lib/domains/ru/yakit.txt

Non-state professional educational institution "Yakutsk College of Innovative Technologies"
НПОУ "Якутский колледж инновационных технологий"
https://yakit.ru

Add collage

---

lib/domains/fr/isae-ensma/etu.txt

Add isae ensma

---

lib/domains/cr/go/mep/est.txt

This is a college in Costa Rica, San Jose, which have a various specialty in IT area. Here is a website https://cotepecos.co.cr/ hope you will accept my request. Email is belong to ministry of education of costa rica, you can recognize it by "mep" part in email, which means "ministerio de educacion publica".

add COTEPECOS college

---

lib/domains/uk/org/bclschool.txt

Ofsted url: https://reports.ofsted.gov.uk/provider/27/102171

Add bclschool.txt

---

lib/domains/gr/aspete/mec.txt

The official website of the University is: 
https://www.aspete.gr/index.php/en/

Add mec.aspete.gr

---

lib/domains/br/edu/auden.txt

https://auden.edu.br/Posgraduacao/Educacao
Acessibilidade, Tecnologia Assistiva e Educação Inclusiva (Accessibility, Assistive Technologies and Inclusive Education)

Add Auden Educação

---

lib/domains/pl/edu/pbs.txt
lib/domains/pl/edu/utp.txt

The university changed its name in 2021.

Add pbs.edu.pl

---

lib/domains/com/liceovirgilioroma.txt

https://liceovirgilioroma.edu.it/

Add liceovirgilioroma.txt

---

lib/domains/org/fwisd/students.txt

Fort Worth ISD is a school district in Texas, with many of its high schools offering courses in computer science, game development, etc.

Added FWISD

---

lib/domains/id/ac/amikompurwokerto/mhs.txt

Homepage : https://www.amikompurwokerto.ac.id/
Signed-off-by: Firman Fathoni <firmanfathoni@pm.me>

Add Universitas AMIKOM Purwokerto

---

lib/domains/de/mpg-bb.txt

Homepage of the school: http://mpg-bb.de/

Add MPG Böblingen

---

lib/domains/pl/mojasiodemka.txt

Fixed PR against #13178.
School's homepage - https://mojasiodemka.pl/.

Added domain mojasiodemka.pl

---

file/lib/domains/il/org/tad/ironihei.txt
lib/domains/il/org/tad/ironihei.txt

Added school domain file

---

lib/domains/ph/edu/tip.txt

Home Page: https://tip.edu.ph
Email URL: https://tip.edu.ph/mail.php

Add Technological Institute of the Philippines

---

lib/domains/com/onmicrosoft/bntuby.txt

https://bntu.by/en
https://bntu.by/en/faculties/fitr

Add Belarusian National Technical University

---

lib/domains/de/mpg/mpl.txt

Institute webpage: https://mpl.mpg.de/
Example for course offering to teach machine learning and AI principles: https://mpl.mpg.de/divisions/marquardt-division/teaching/

Add MPL Erlangen

---

lib/domains/ru/sibguti/stud.txt

{Siberian State University of Telecommunications and Information Sciences}
{[Website URL](https://sibsutis.ru/)}
v.suraev@stud.sibguti.ru

[NEW] add subdommen sibguti

---

lib/domains/kr/hs/ksa.txt

School's homepage: https://www.ksa.hs.kr/

Add domain ksa.hs.kr

---

lib/domains/pl/opole/wsb/student.txt
pl/opole/wsb/student.txt

Add new domain: student.wsb.opole.pl

Add WSB university

---

lib/domains/my/edu/cempaka.txt

Cempaka International School Damansara Heights

cempaka.txt

---

lib/domains/eu/lublin/zsel/gsuite.txt

technikum.zsel.lublin.eu
https://www.zsel.lublin.eu/wykaz-klas/technikum55592/technik-teleinformatyk55592
http://nowa.zsel.lublin.eu/kierunki/technik-teleinformatyk/

Add Technical School Complex in Lublin 

---

lib/domains/tw/edu/dila.txt

Website:  https://www.dila.edu.tw/

Add dila.txt

---

lib/domains/il/org/ort/holon.txt

Add Ort Holon High School

---

lib/domains/at/hakvb.txt

Website: https://hakvb.at/
IT related course: https://hakvb.at/ausbildung/digbiz/

Add Austrian Handelsakademie Vöcklabruck

---

lib/domains/ge/itvet.txt

Add Information Technologies Academy
website: http://itvet.ge/

Add Information Technologies Academy

---

lib/domains/edu/kongu.txt
lib/domains/in/ac/kongu.txt

College Domains:
[https://kongu.ac.in](https://kongu.ac.in)
[https://kongu.edu](https://kongu.edu)

Added Kongu Engineering College Domains

---

lib/domains/ua/edu/onua.txt

Website: https://onua.edu.ua/
Website ENG: https://onua.edu.ua/en/

Add National University Odesa Law Academy

---

lib/domains/de/musin/muenchen/gmm.txt

Hi!
Our website: https://gym-muc-moosach.musin.de/
The students emails differs from the address (but afaik, there is no @gym-muc-moosach.musin.de address).
Yes, it is a secondary school, but we do have normal it classes where we are allowed to work with IntelliJ (and yes, it is installed on most of the student devices there). We learn SQL there and code with Java. I'd really appreciate the enterprise edition (I am also using it to develop my stuff at home). In addition we have extra lessons every week, where students can learn programming. We do pretty much all languages there (currently focused on python)
Thanks!

Add Gymnasium München Moosach

---

lib/domains/org/lccsnj.txt

adding Learning community charter school

---

lib/domains/com/h-is/student.txt

Main website: [https://www.h-farm.com/it/education/college](https://www.h-farm.com/it/education/college)
Example of IT course: [https://www.h-farm.com/it/education/college](https://www.h-farm.com/en/education/college/bachelor-degrees/digital-management)
Proof of student email: <img width="1168" alt="Screen Shot 2021-12-28 at 10 17 57 PM" src="https://user-images.githubusercontent.com/65074104/147632835-4b04edf3-b2a5-4ea6-b0d6-86e1b14a324a.png">

Add H-Farm International School to the repo

---

lib/domains/com/groupeiam.txt

https://www.groupeiam.com/
https://www.groupeiam.com/iam-tech/

Add African Institute of Management

---

lib/domains/net/gymkatzelsdorf/student.txt

added domain for my schools email addresses like <lastname>.<firstname>@student.gymkatzelsdorf.net

added my schools domains

---

lib/domains/uk/co/mynsb.txt

Northampton School For Boys
[Website URL](https://www.nsb.northants.sch.uk/)

Add Northampton School For Boys (NSB)

---

lib/domains/de/osztiem/schueler.txt

Add OSZ TIEM

---

lib/domains/id/ac/poltektegal.txt
lib/domains/id/sch/sman1tegal.txt
lib/domains/id/sch/sman4tegal.txt

- Politeknik Harapan Bersama - https://poltektegal.ac.id/
- SMA Negeri 4 Tegal - https://sman4tegal.sch.id/
- SMA Negeri 1 Tegal - https://sman1tegal.sch.id/

Add poltektegal.ac.id, sman4tegal.sch.id and sman1tegal.sch.id

---

lib/domains/eg/edu/fief.txt

Add Future High Institute Of Engineering In Fayoum to JetBrains.

Future High Institute Of Engineering In Fayoum

---

lib/domains/lt/erudito.txt

Erudito Licejus is an IB world School

Erudito Licejus

---

lib/domains/mk/edu/ibu.txt

Add International Balkan University

---

lib/domains/eu/kielce/e-zsel.txt

Official URLs:
* Landing page: [https://www.zse-kielce.edu.pl](https://www.zse-kielce.edu.pl)
* Student page: [https://ezse.pl](https://ezse.pl)
The course is called "technik programista" (software engineering). Although I was unable to find a page with an offer, there is a [blog post](https://www.zse-kielce.edu.pl/index.php/strefa-pracodawcy/wspolpraca/1069-podpisanie-umowy-pomiedzy-przodujaca-w-branzy-it-firma-infover-a-zespolem-szkol-elektrycznych-2019) on the official website about the course being introduced in 2019. If a different proof is required, please let me know.
**Proof of e-mail being official (screenshot of the previously mentioned _ezse.pl_ website):**
Translation:
_Log in to a school account on the domain e-zsel.kielce.eu_

Add "Technikum nr 4 im. Ryszarda Kaczorowskiego w Kielcach"

---

lib/domains/ro/moisil.txt

Grigore Moisil National College (Bucharest)

---

lib/domains/com/onmicrosoft/ghsede.txt
lib/domains/de/GHSE Emmendingen/students.txt

Gewerbliche und Hauswirtschaftlich-Sozialpflegerische Schulen Emmendingen
ghsede.onmicrosoft.com
The users will be students 
GHSE is a High School
[ghsede.txt](https://github.com/JetBrains/swot/files/7810231/ghsede.txt)

Add Gewerbliche und Hauswirtschaftlich-Sozialpflegerische Schulen Emmendingen

---

lib/domains/ca/cimf.txt

CIMF is a french international school, with algorithm classes in it

Adding the CIMF school file

---

lib/domains/com/sheldonisd.txt

{C.E. King High School}
https://www.sheldonisd.com

Add SheldonISD.com

---

lib/domains/br/unc.txt

Adding repository for Universidade do Contestado - UnC
https://www.unc.br/

Add Universidade do Contestado - UnC

---

lib/domains/ca/myucw.txt

**Website:**
https://ucanwest.ca
**MyUCW Portal**
MyUCW portal is a gateway for students to access their course materials, communicate to students and staff
https://www.myucwest.ca

Add University Canada West

---

lib/domains/edu/ncmich.txt

https://ncmich.edu
https://catalog.ncmich.edu/preview_program.php?catoid=13&poid=1796

Added ncmich.edu / ncmich.txt

---

lib/domains/br/com/descomplica.txt

Add Faculdade Descomplica.
Add Descomplica College.

Add Faculdade Descomplica file

---

lib/domains/kr/smit.txt

add smit to the list

---

lib/domains/my/edu/uts/student.txt

university domain name changed from ucts to uts.

added uts.txt

---

lib/domains/ca/on/rsgc.txt

Added rsgc.txt file to the .on.ca domains list.

Add files via upload per license request

---

lib/domains/de/mpg/mpp.txt

Website: https://www.mpp.mpg.de/

Add the Max Planck Institute for Physics

---

lib/domains/us/in/k12/ngsc.txt

Added Indiana K12 domain to the US folder.

Added Indiana K12 domain

---

lib/domains/vn/edu/ntu-hn.txt

please add Nguyen Trai University

create Nguyen Trai University

---

lib/domains/dz/estin.txt

This is a state/public school founded a couple of years ago.

Create estin.txt for the estin.dz domain

---

lib/domains/au/edu/catholic/cardijn.txt

Added Cardijn Collage
*@cardijn.catholic.edu.au

Added Cardijn Collage

---

lib/domains/ch/bene-edu.txt

Add Benedict Schule Luzern

---

lib/domains/nl/over-y/leerling.txt

Added over-y

---

lib/domains/de/gymnasium-babelsberg.txt

Fachbereich Informatik | Bertha-von-Suttner-Gymnasium Babelsberg:
https://www.youtube.com/watch?v=6Cx8ZMLLDmg

Add Bertha von Suttner Gymnasium Babelsberg

---

lib/domains/br/com/fasipe.txt

Add Unifasipe University.

---

lib/domains/org/itiangioy.txt

school homepage: https://www.itiangioy.edu.it/
proof of school domain:

Add ITI G.M. Angioy 

---

lib/domains/org/lcisd/students.txt

https://www.lcisd.org/departments/academics/cte/programs-of-study/cte-courses#Information

Adding Lamar LCISD, 

---

lib/domains/vn/edu/utehy.txt

Add the domain for Hung Yen University of Technology and Education.
University website: http://www.utehy.edu.vn/#/
IT faculty website: https://fit.utehy.edu.vn

Add Hung Yen University of Technology and Education

---

lib/domains/at/hakneumarkt.txt

Adding "Bundeshandelsakademie Neumarkt am Wallersee" - hakneumarkt.at

Add HAK Neumarkt

---

lib/domains/ie/fingalcc.txt

Fingal Community College
[www.fingalcc.ie](https://www.fingalcc.ie)

Fingal Community College

---

lib/domains/com/indusschoolpune.txt

URL to School Site: https://www.indusschool.com/international-school-pune/
The school follows the IB board (International Baccalaureate) and offers IB MYP Digital Design (grades 6-11) and IB Diploma Computer Science Program (grades 11-12). Link to IB Computer Science HL: https://www.ibo.org/globalassets/publications/recognition/4_computerhl.pdf
We use ManageBac to organise our homework and tasks. This screenshot of the about page shows the recognised email address.

Add Indus International School, Pune

---

lib/domains/us/fl/k12/nassau.txt

Sorry I don't know how my name ended up like this.

Add Fernandina Beach Middle School

---

lib/domains/uk/acesmat/hbk.txt

Revert 11743 master

---

lib/domains/academy/cloud-campus.txt

I add my training center to your repository to allow me and the student of my class to have a jetBrains license.
thank you

add cloud campus academy

---

lib/domains/com/kosinka.txt

**Add Kosinka**
Institution/School Name :
Střední škola technická a obchodní Olomouc, Kosinova 4 Czech Republic
Official site :
https://www.kosinka.com/
example email : example@kosinka.com

Add Kosinka

---

lib/domains/tw/edu/meiho/go.txt

school name
https://www.meiho.edu.tw/files/11-1000-2254.php?Lang=en
mail
https://www.meiho.edu.tw/files/14-1000-37139,r11-1.php?Lang=zh-tw

Add school in TW - MeiHo University

---

lib/domains/pl/info/lo1.txt

Official website: https://lo1.info.pl/

add lo1.txt

---

lib/domains/cn/edu/ccmu.txt

Institution/School Name :
Capital Medical University, Beijing, China
Official site :
https://www.ccmu.edu.cn/
example email : example@mail.ccmu.edu.cn
Only on-campus students can sign up for e-mail addresses with such domain names：
https://cdn.jsdelivr.net/gh/jlatch1/figure-bed@main/image/16433851218431643385120861.png
This school has IT related majors, you can read the introduction in ：https://bes.ccmu.edu.cn/xxsz_48/swyxxxxxx_11232/index.htm
The Biomedical Engineering School of Capital Medical University also offers master's degree in computer application technology(计算机应用技术) ：https://yjsh.ccmu.edu.cn/zsgz/lnqk/107370.htm

Add Capital Medical University

---

lib/domains/de/ms-muc.txt

Meisterschulen am Ostbahnhof, München

Meisterschulen am Ostbahnhof, München 

---

lib/domains/it/copernicopasoli.txt

Istituto Istruzione Superiore Statale
Copernico Pasoli
Verona
[{Website URL}](https://www.copernicopasoli.edu.it/wordpress/indirizzo-di-studio/sistemi-informativi-aziendali/)

Added Copernico Pasoli Institute

---

lib/domains/it/edu/luigidellerba.txt

I.I.S.S. Dell'Erba, Castellana Grotte (BA), Italy, added.

I.I.S.S. Dell'Erba, Castellana Grotte (BA), Italy, added.

---

lib/domains/pl/zsdil.txt

add Zespol Szkol Technicznych i Lesnych w Zywcu

---

lib/domains/br/edu/sumare.txt

Faculdade Sumare 
[{Website URL}](https://sumare.edu.br/)
1210780@sumare.edu.br

Add University Sumare to domain

---

lib/domains/uk/co/barrbeaconschool.txt

Barr Beacon School do a computer science A-Level and BTEC Information Technology (IT) course

Added Barr Beacon School

---

lib/domains/us/ma/k12/norwood.txt

Added Norwood High School to domain list

Added Norwood High School to domain list

---

colegiovivas.txt
lib/domains/com/colegiovivas.txt

https://colegiovivas.com
https://colegiovivas.com/web2/content/ciclo-superior-de-desarrollo-de-aplicaciones-multiplataforma

Add Colegio Vivas

---

lib/domains/schule/akbk.txt

Official website: https://akbk-horrem.de/
Proof can be found [here](https://www.akbk-horrem.de/fileadmin/user_upload/downloads/einwilligung_zeitweilig_O365_20201202.pdf).

Add Adolf Kolping Berufskolleg

---

belajar.txt
lib/domains/id/ac/amikmahaputra.txt
lib/domains/id/belajar.txt
lib/domains/id/sch/sman1serangbarujuara.txt
lib/domains/id/sch/sman2balige.txt

AMIK Mahaputra, Yasop, SMAN 2 Balige, SMAN 1 Serang Baru, and Belajar.ID

Add some perks

---

lib/domains/th/ac/aims.txt

Please add my school name on the list.

Added my school - AIMS

---

lib/domains/br/senai/aluno.txt

Please add SENAI - DF to your repo.

Adding SENAI - DF to repo

---

lib/domains/org/mibdu.txt

Added domain for MBA - International Business Delhi University

Added domain MIBDU

---

lib/domains/org/hcesonepat.txt

**Adding hcesonepat in org domain of JetBrains**

Adding hcesonepat in org domain of JetBrains

---

lib/domains/org/scmsgroup.txt

My pull-request which had a first stage verification was closed when i resetted the branch accidently 
Reference: https://github.com/JetBrains/swot/pull/13555
Official college site: https://scmsgroup.org/sstm

SCMS School Of Technology and Management

---

lib/domains/it/itczappa.txt

Request for school ITCS Gino Zappa Saronno to be added to JetBrains

Request to add my school to JetBrains

---

lib/domains/stoplist.txt

https://www.africanleadershipacademy.org/
add African Leadership Academy (pre-university with CS course)

add African Leadership Academy

---

lib/domains/in/ac/nitsri.txt

Institution Name: **National Institute of Technology Srinagar**
Official Website: **https://nitsri.ac.in/**

Add National Institute of Technology Srinagar

---

lib/domains/net/sabis/aisriyadh.txt

This adds the AisRiyadh branch of Sabis to the SWOT system of JetBrains.
An email address is structured like this
MSYED@aisriyadh.sabis.net
If you go to sabis.net my school's website should load

Added AISRiyadh - Sabis

---

lib/domains/id/ac/polsri.txt

See polsri diploma programs here: https://www.polsri.ac.id/programs

please add Politeknik Negeri Sriwijaya

---

lib/domains/tr/edu/trabzon.txt

Trabzon University added

---

lib/domains/cz/zsnachodovci.txt

Added my school's email (We all got a email in 2020 cuz covid and we needed online class :D)
School's website: https://www.zsnachodovci.cz/
yes our schools email is long don't juge

Added ZŠ na Chodovci

---

lib/domains/cn/edu/zisu.txt

Zhejiang International Studies University, Zhejiang, China
Official site:
https://www.zisu.edu.cn/
https://www.zisu.edu.cn/english/
Wiki:https://en.wikipedia.org/wiki/Zhejiang_International_Studies_University
Student email example:example@st.zisu.edu.cn
Login website:http://mail.st.zisu.edu.cn/
Department of Computer Science:https://kjxy.zisu.edu.cn/info/1009/1807.htm

Add st.zisu.edu.cn(Zhejiang International Studies University)

---

lib/domains/de/ohg-bensberg.txt

My School "Otto-Hahn-Gymnasium Bergisch Gladbach" changed its domainname from ohs-bensberg.de to ohg-bensberg.de because of a system change. 
I don't know if we have to remove the old domainname or if you do it automatically when we send in a new one. Every student has a new emailadress with the new domainname so it would be no problem if you remove the old name "ohs-bensberg.de"
School website URL: https://ohg-bensberg.de
Link to our information about IT courses: https://ohg-bensberg.de/index.php/unterricht/faecher/naturwissenschaften/informatik

Added OHG-Bensberg.txt

---

lib/domains/fr/asso/toulouse-ort.txt

https://ort-france.fr/nos-formations/metier-du-numerique-et-informatique/bac-5-infrastructures-cybersecurite-alternance-eris

ORT Toulouse

---

lib/domains/info/groupe-aen.txt

Our school website : https://www.groupe-aen.info/
One of our five years IT related course : https://www.groupe-aen.info/intech/#postbac-2
And a list of students of one of our classes from the courses' manager that we use, showing that all their email addresses are on the domain.
Sorry, all these are in French as we are a French school.

Please add our school

---

lib/domains/de/gsso.txt

Add Grafenberg school
https://gsso.de/

Add Grafenberg school

---

lib/domains/br/com/ceuma.txt

required licence study for university ceuma

licence study - ceuma

---

lib/domains/cn/edu/ahpu.txt

Institution/School Name :
Anhui Polytechnic University, Anhui, China
Official site : https://www.ahpu.edu.cn/
Wiki:https://en.wikipedia.org/wiki/Anhui_Polytechnic_University
Student email example : example@stu.ahpu.edu.cn
This school has IT related majors, you can read the introduction in ：
https://www.ahpu.edu.cn/jsjyxxgc/5461/list.htm

Add stu.ahpu.edu.cn(Anhui Polytechnic University)

---

lib/domains/cn/edu/chzu.txt

Chuzhou University, Anhui, China
Official site:http://www.chzu.edu.cn/
Wiki:https://zh.wikipedia.org/wiki/%E6%BB%81%E5%B7%9E%E5%AD%A6%E9%99%A2
Student email example:example@mail.chzu.edu.cn
[https://imgur.com/a/mE2ncMm](https://imgur.com/a/mE2ncMm)
School of Computer and Information Engineering:https://csci.chzu.edu.cn/

Add mail.chzu.edu.cn(Chuzhou University)

---

lib/domains/cn/edu/jgsu.txt

Jinggangshan University, Jiangxi, China
Official site:
http://www.jgsu.edu.cn/
http://english.jgsu.edu.cn/
Wiki:https://en.wikipedia.org/wiki/Jinggangshan_University
Student email example:example@jgsu.edu.cn
Institute Of Computer Application Technology:http://computer.jgsu.edu.cn/
IT related major:http://ei.jgsu.edu.cn/xkjs/xkgk/201008/t20100816_5357.htm

Add Jinggangshan University

---

lib/domains/cn/edu/swun.txt

Southwest Minzu University, Sichuan, China
Official site:http://www.swun.edu.cn/(https://english.swun.edu.cn/)
Wiki:https://en.wikipedia.org/wiki/Southwest_Minzu_University
Student email example:example@stu.swun.edu.cn
Department of Computer Science and Engineering：https://jkxy.swun.edu.cn/

Add stu.swun.edu.cn(Southwest Minzu University)

---

lib/domains/org/chorustrust/silverdale.txt

https://www.silverdale-chorustrust.org/

Add silverdale school

---

lib/domains/fr/stagiairesifa.txt

pull request to add IFA to license in jetbrains
https://www.metz-numeric-school.fr/fr

pull request ifa license

---

lib/domains/com/threepoints/student.txt

Add threepoint school

---

lib/domains/gr/edu/ist.txt

Website:  https://ist.edu.gr/
CS Course: https://ist.edu.gr/en/course/bsc-hons-computer-science/
Andrea Syggrou Ave. 68, Athens 117 42 , Greece

Add ist.edu.gr

---

lib/domains/org/ueuromed/vac.txt

**official website of the university:** 
http://ueuromed.org/
**English version of the official website:**
http://ueuromed.org/en

Add ueuromed.org

---

lib/domains/pl/edu/sp12w.txt

Szkoła Podstawowa nr 12 im. Powstańców Śląskich w Warszawie

Added Szkoła Podstawowa nr 12 im. Powstańców Śląskich w Warszawie

---

lib/domains/id/ac/unjaya/ftti.txt

Add Universitas Jenderal Achmad Yani Yogyakarta

---

lib/domains/br/fafire/grad.txt

Add the Frassinetti university of Recife "FAFIRE"

 add university Fafire

---

lib/domains/it/uniud/spes.txt

**Homepage:** 
https://www.uniud.it/
**An example of IT-related graduate courses (in Italian):** 
https://www.uniud.it/it/didattica/corsi-offerta/area-scientifica/scienze-matematiche-informatiche-multimediali-fisiche/laurea/informatica/informatica
**A proof showing that the school provides this as an official mail domain for the students (in Italian):** https://www.uniud.it/it/servizi/servizi-informatici/email-studenti

Add University of Udine student email: @spes.uniud.it

---

lib/domains/com/grietcollege.txt

Please add my university/college info.
Gokaraju Rangaraju Institute of Engineering & Technology - http://www.griet.ac.in/

Adding my university/college info

---

lib/domains/cn/scun.txt

Institution/School Name :
Sichuan Minzu College, Sichuan, China
Official site :
https://www.scun.edu.cn/
example email :
example@scun.edu.cn
This school has IT related majors, you can read the introduction in ：
https://zjc.scun.edu.cn/info/1064/1125.htm

Add Sichuan Minzu College

---

lib/domains/br/com/faculdadedescomplica/aluno.txt

- Official university website: https://descomplica.com.br/faculdade/
- IT course page https://descomplica.com.br/faculdade/tecnologia/ciencia-da-computacao/
- Screenshot with the email I received from the university's main contact with the e-mail credentials (auto translated by google, original is in Portuguese) https://files.catbox.moe/l15zzt.png

Added Descomplica college

---

lib/domains/pl/edu/mup/student.txt

Homepage: https://www.uczelniaoswiecim.edu.pl

Add MUP oswiecim

---

lib/domains/kz/qmu.txt

Медицинский Университет Караганды
Medical University of Karaganda

Add qmu.kz
