lib/domains/it/itsaltoadriatico/stud.txt

https://www.tecnicosuperiorekennedy.it/
recently changed name from ITS Kennedy to ITS Alto Adriatico.
Domains: itsaltoadriatico.it and tecnicosuperiorekennedy.it

Add ITS Alto Adriatico

---

lib/domains/tr/edu/iu/ogr.txt

Istanbul University Web Page in English: https://www.istanbul.edu.tr/en/_
The student mail addresses specified with @ogr.iu.edu.tr
You can follow the link of [Istanbul University Student Mail System](https://ogr.iu.edu.tr/) the mail address extension top of the page.

Istanbul University mail address extension fixed

---

lib/domains/it/bo/luxemburg.txt

The official website: [https://www.luxemburg.bo.it/](https://www.luxemburg.bo.it/)
[This document](https://www.luxemburg.bo.it/pvw/app/default/pvw_img.php?sede_codice=BOIT0005&doc=2555937&inl=1) states that "Informatica" is a course that lasts for 3 years.
And in [this page](https://www.luxemburg.bo.it/pagine/informativa-g-suite) is written that the school offer a mail address for his students.

Add domain luxemburg.bo.it

---

lib/domains/eg/edu/suezuni/fci.txt

- University name: Suez University
- City: Suez
- Country: Egypt
- Faculty: Computers and Information (Computer Science)
- Website: https://suezuni.edu.eg/index.php/en
-  Proof with a screenshot is attached.

Added domain @fci.suezuni.edu.eg Suez University

---

lib/domains/at/ac/aim/stud.txt

University website: https://aim.ac.at/en/
IT related course: https://aim.ac.at/programme/mba-it-management/
Proof of a link between FH Burgenland (AIM) and the domain "stud.aim.ac.at" (just search for the string "stud.aim.ac.at"): https://fh-burgenland.libanswers.com/faq/244284

added Austrian Institute of Management (FH Burgenland)

---

lib/domains/es/educaand/g.txt

The ``g.educaand.es`` domain is used across all Andalusia starting 2021/2022 with the intention of unifying the corporate email addresses across the whole autonomous region (""state"").
This is referenced in the official page of Junta de Andalucía: https://www.juntadeandalucia.es/educacion/eaprendizaje/gsuite/
Cite:
> (...) The Consejería de Educación y Deporte de la Junta de Andalucía, after an agreement, has created the domain g.educaand.es for the management of these accounts for the Andalusian public schools. (...)
<details>
<summary>Original (Spanish)</summary>
La Consejería de Educación y Deporte de la Junta de Andalucía, tras el convenio firmado , ha creado el dominio g.educaand.es para la gestión de estas cuentas para los centros educativos andaluces de titularidad pública. …

fix: update institution name of g.educaand.es

---

lib/domains/fr/u-psud.txt

The university's domain name is : https://www.universite-paris-saclay.fr/
But our emails have a **different** domain name is the abbreviation of the original domain name : **_u-psud.fr_**
Here is an example of a mail address 
```
firstName.lastName@u-psud.fr
```

Add : paris-saclay university

---

lib/domains/org/rzjhs.txt

School Home Page: https://www.rzjhs.org
Address: 1095 Lake Cook Road, Deerfield, IL 60015 (Shown at bottom of home page.)
Page showing course: https://drive.google.com/file/d/15osEB73HazabsGeweEuiX0mbqCPONBNR/view (Page 9)

Add Rochelle Zelle Jewish High School Domain

---

lib/domains/pl/edu/zst-sopot.txt

**Please add Zespół Szkół Technicznych w Sopocie on Street Wejherowska 1 to school list**
*Official School Domain: http://zstsopot.pl*
*Students & Teacher domain* **zst-sopot.edu.pl**

Add Zst Sopot (Zespol Szkol Technicznych w Sopocie) from Poland

---

lib/domains/hk/edu/wahyan.txt

Add Wah Yan College Hong Kong to JetBrains.

Wah Yan College Hong Kong

---

lib/domains/fr/malrauxbethune.txt

Hi, here is the addition of André Malraux high-school located in Bethune. (:

Add André Malraux Highschool (located in Bethune, France)

---

lib/domains/br/com/sempreunama.txt

Another domain owned by UNAMA
Universidade da Amazônia - UNAMA is a part from Ser Educational Group

University add: UNAMA - Ser Educational Group

---

lib/domains/dk/aaks.txt
lib/domains/dk/aarhus/aarhus/aaks.txt

This should be the right domain, @aaks.dk. 
A whois lookup results in:
`Domain:               aaks.dk
DNS:                  aaks.dk
Registered:           1998-05-13
Expires:              2022-06-30
Registrar:            Eurodns S.A
Registration period:  1 year
VID:                  no
DNSSEC:               Signed delegation
Status:               Active
Registrant
Handle:               ***N/A***
Name:                 Aarhus Kommune
Attention:            Thomas Pedersen
Address:              Rådhuspladsen 2
Postalcode:           8000
City:                 Aarhus C
Country:              DK
`
Which says the domain is owned by Aarhus.

Add Aarhus Municipality Schools with the correct domain this time.

---

lib/domains/br/com/alunosmaristas.txt

Add the domain for Marista Arquidiocesano school. School website: https://arquidiocesano.colegiosmaristas.com.br/

Add Marista Arquidiocesano

---

lib/domains/education/sabel.txt

Sabel Schulen (https://sabel.com/) is a group of private schools in Germany. Students of both Sabel Schulen and GBS Schulen (which belongs to Sabel and offers vocational trainings related to IT; read more here: https://gbsschulen.de/berufsfachschule/) get a @sabel.education email-address which they can use for the time of their training.

Add @sabel.education

---

lib/domains/org/ecscollege.txt

the school official website URL: https://www.ecscollege.org/
the school street address, including city and country: Soul Clinic First Turning Point, Paynesville 2228, Liberia
an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course: https://www.ecscollege.org/?page_id=26
a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.: You can see our domain name in the official website of the National Commission on Higher Education of Libya(http://www.nche.gov.lr/content/institutions), about you said before to open is spam content, because the National Commission on Higher Education website may be disturbed by advertising, please refresh to enter a few more times on it! Thanks a …

Add Evangel Christian Seminary & College

---

lib/domains/br/fumec.txt

Fumec University already exists, it is only in edu/ directory. The email of the students finishes with @fumec.br and not @fumec.edu.br probably this one is destined for professors.
Official Site: [http://www.fumec.br](http://www.fumec.br)

Add Fumec University in 'br/' directory out of 'edu/'

---

lib/domains/edu/adams.txt

In 2012, Adams State College was renamed to Adams State University.  This commit reflects the name change
Sources: https://blogs.adams.edu/thepawprint/adams-state-takes-steps-to-change-name-to-university/, https://web.archive.org/web/20170104234838/http://www.adams.edu/news/may1214.php

Rename Adams State College to Adams State University

---

lib/domains/mm/edu/miit.txt

Domain - miit.edu.mm
School Name(EN) - Myanmar Institute of Information Technology
School Name(MM) - မြန်မာသတင်းအချက်အလက်နည်းပညာတက္ကသိုလ်

add miit.edu.mm

---

lib/domains/fr/afpa.txt

AFPA is a public professional reconversion university for adult.
University official website URL : https://www.afpa.fr/
URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university : https://www.afpa.fr/formation-qualifiante/concepteur-developpeur-informatique

Adding afpa.fr

---

lib/domains/dk/eucsj/unv.txt

School URL: https://www.eucsj.dk/htx/htx-koege.aspx

add high school: EUCSJ HTX Køge

---

lib/domains/pl/collegiumwitelona.txt
lib/domains/pl/collegiumwitelona/studenci.txt

As The Witelon State University of Applied Sciences in Legnica legally changed its name to Collegium Witelona Uczelnia Państwowa (:gb: Witelon Collegium State University, @collegiumwitelona), I'm requesting for adding new email domains to your list.
The new address: https://collegiumwitelona.pl/
Page about CS studies: http://www.wzi.pwsz.legnica.edu.pl/artykul-166-ki
Contact page with the domain in question included: http://www.pwsz.legnica.edu.pl/strona-684-teleadresowe-1
Domain `@collegiumwitelona.pl` is for teachers and `@studenci.collegiumwitelona.pl` for students.

@collegiumwitelona

---

lib/domains/pl/bochnia/zs1.txt

Please add Zespół Szkół Nr 1 im. Stanisława Staszica w Bochni to school list
School Official Website: https://zs1.bochnia.pl
School Location: City: Bochnia, Street: Windakiewicza 23, Country: Poland
School offers long-term course (5 years): https://zs1.bochnia.pl/rekrutacja/oferta-dydaktyczna
Major courses offered at the school associated with computer science are:
- technik informatyk(IT technician)
- technik programista(programmer technician).
Students & Teacher email domain: zs1.bochnia.pl

Add zs1 Bochnia (Zespol Szkol Nr 1 im. Stanislawa Staszica w Bochni) from Poland

---

lib/domains/it/edu/gobettivolta/studenti.txt

Added studenti.gobettivolta.edu.it.
Previously this school used .gov.it, but the address is now .edu.it.
School website: [www.gobettivolta.edu.it](http://www.gobettivolta.edu.it)

Added studenti.gobettivolta.edu.it domain

---

lib/domains/cn/edu/bwu.txt

Beijing Wuzi University, Beijing, China
Official site:https://www.bwu.edu.cn/index.htm
Wiki:https://en.wikipedia.org/wiki/Beijing_Wuzi_University
Student email example:example@bwu.edu.cn
Notice on opening campus mailbox for all undergraduate and graduate students(If students graduate, their email will be cancelled):https://nic.bwu.edu.cn/info/9365/58733.htm
IT related major:https://yjsb.bwu.edu.cn/info/1017/4665.htm

Add Beijing Wuzi University

---

lib/domains/com/omnesintervenant.txt

https://www.omneseducation.com
https://www.omneseducation.com/ecoles/ece/
https://www.ece.fr/programmes/programme-grande-ecole-ingenieurs
/
Omnes is the new group name of INSEEC. 
Inside this group there is the ECE, an engineering university in electronics where I teach computer science.
the domain omnesintervenant is used for teachers at Omnes (intervenant is a synonym of teacher in French)

omnesintervenant.txt

---

lib/domains/cz/jirovcovka.txt
lib/domains/net/jirovcovka.txt

Two domains:
jirovcovka.net 
and  e-mail alias domain
jirovcovka.cz
Google hosted cloud - Google Workspace for Education. 
Our websites: https://www.gymji.cz/ and https://www.jirovcovka.net (new pages)

Adding Gymnázium, České Budějovice, Jírovcova 8

---

lib/domains/uk/org/huntington-ed.txt

Official Website: [School](https://huntingtonschool.co.uk/)
Email domain they use: huntington-ed.org.uk
Course: [Computer Science](https://huntingtonschool.co.uk/sixth-form/subjects/computer-scicence/)
Them recognising it as a school email: [YT Tutorial with timestamp](https://youtu.be/4nZro7tih3s?t=16) found on the school site listed as "How to access Microsoft Teams" [Student Learning](https://huntingtonschool.co.uk/students/student-online-learning/
) I can't really find any other mention of it online, Sorry.

Added huntington school york

---

lib/domains/ch/bbzbl-it.txt
lib/domains/ch/gibmit.txt

The school was merged with an other school and the new name is now BBZBL, see this PDF in German: https://www.bbzbl.ch/wp-content/uploads/2019/12/GIBML-Jahresbericht-2018-Muttenz-Layout_fertig.pdf
The Domain for the students of the IT part of the school is bbzbl-it.ch

renamed school to BBZBL IT

---

lib/domains/cn/edu/fynu.txt

Fuyang Normal University, Anhui, China
Official site:http://www.fynu.edu.cn/
Wiki:https://en.wikipedia.org/wiki/Fuyang_Normal_University
Student email example:example@stu.fynu.edu.cn
School of Computer and Information Engineering:http://www.fynu.edu.cn/xxgc/jxgz/jxdg.htm

Add stu.fynu.edu.cn(Fuyang Normal University)

---

lib/domains/cn/edu/hytc.txt

Huaiyin Normal University, Jiangsu, China
Official site:https://www.hytc.edu.cn/
Wiki:https://zh.wikipedia.org/wiki/%E6%B7%AE%E9%98%B4%E5%B8%88%E8%8C%83%E5%AD%A6%E9%99%A2
Student email example:example@stu.hytc.edu.cn
The School of Computer Science and Technology of Huaiyin Normal University:https://cs.hytc.edu.cn/

Add stu.hytc.edu.cn(Huaiyin Normal University)

---

lib/domains/kr/go/goe/ggm.txt

https://goe.go.kr/ (Gyeonggi Province Office of Education)

Adding goe.go.kr

---

lib/domains/tw/edu/tyc/clhs/gm.txt

Add the school in Taiwan of The Affiliated Zhongli Senior High School of National Central University.
Official site: https://www.clhs.tyc.edu.tw/
Wiki: https://zh.wikipedia.org/wiki/%E5%9C%8B%E7%AB%8B%E4%B8%AD%E5%A4%AE%E5%A4%A7%E5%AD%B8%E9%99%84%E5%B1%AC%E4%B8%AD%E5%A3%A2%E9%AB%98%E7%B4%9A%E4%B8%AD%E5%AD%B8

Add school in TW-CLHS

---

lib/domains/de/lernsax/manos-dresden.txt

Website: https://manos-dresden.de
IT-Course: https://manos-dresden.de/faecher/fk-informatik
Lernsax is linked on the homepage and all e-mail addresses related to the school end in manos-dresden.lernsax.de.

Add Martin-Andersen-Nexö-Gymnasium Dresden

---

lib/domains/net/hillsideschool.txt

University official website: https://hillsideschool.net
URL of a page where a long-term (>1 year) IT related course is offered: https://www.hillsideschool.net/academics/innovation-center-at-hillside
URL of a page showing that the university recognizes the domain as an official email domain for the enrolled students: https://www.hillsideschool.net/about/directory. You can see the email addresses that correlate to the faculty.

Add hillsideschool.txt

---

lib/domains/it/peano.txt

Official school website: https://www.iispeano.edu.it, it can also be reached using https://www.peano.it

Add Domains

---

lib/domains/eu/altesgymnasium.txt

- official website URL: https://altesgymnasium.de/
- adress: Theaterwall 11, 26122 Oldenburg, Germany
- proof of computer science courses: https://altesgymnasium.de/elementor-informatik/ (page for "Informatik" (Computer Science) as a subject at the school) - If you click on the "Wochenstunden" (weekly hours) button under "Sekundarstufe II" (upper secondary), you will see that there are hours for "Kurs auf erhöhtem Niveau" (advanced course). So it follows the German school system, in upper secondary (higher education) you always take advanced courses for two years.
- proof of the correctness of the email domain: https://altesgymnasium.de/wp-content/uploads/2020/03/IServ-_Einverst%C3%A4ndnis.pdf - This is a consent form for the use of "IServ", the communication platform used by the school. …

Add Altes Gymnasium Oldenburg

---

lib/domains/de/evhn/stud.txt

1. The official university website is https://www.evhn.de
2. The course "Quantitative Methoden der Wirtschaftswissenschaften"/"Quantitative Methods of Economics" is related to IT. The course covers the area of statistics. More details about the course can be found in this PDF file https://www.evhn.de/sites/default/files/media/downloads/modulhandbuch_m.ww_ab_sose_2022.pdf
3. The email domain for students is specified here https://www.evhn.de/studierende/service-fuer-studierende/it-referat/e-mail-fuer-studierende.

Added the email domain of 'Evangelische Hochschule Nürnberg'.

---

lib/domains/cn/edu/gist.txt

The Global Institute of Software Technology (苏州高博软件技术职业学院, [official website](http://www.gist.edu.cn/)) is a full-time general institution of higher learning organized by Wuzhong Group and Gaobo Education Management (Suzhou) Co., Ltd. and approved by the Jiangsu Provincial People’s Government and filed by the Ministry of Education. It was founded in March 2007. There are [School of Information and Software](http://sis.gist.edu.cn/), School of Mechanical and Electrical Engineering, etc. There are currently nearly 6,000 students.

Add Global Institute of Software Technology

---

lib/domains/es/escuelaestech.txt

Adds Escuela es[tech] -- https://escuelaestech.es
> A URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university
https://escuelaestech.es/tecnico-superior-en-desarrollo-de-aplicaciones-multiplataforma-presencial/

Add Escuela es[tech]

---

lib/domains/br/edu/faculdadeideal/alunos.txt

- Official site URL: https://www.wyden.com.br/faci
- Address: Tv. Tupinambás, 461, Belém, Brazil
- Proof of long-term (>1 year) course: On the official site (https://www.wyden.com.br/faci), go to the section "Pesquisar Cursos" (Search Courses) and select "Pará" in the first box, "Faci" in the second box, then finally the courses list will load in the third box where you can see "Ciência da Computação" (Computer Science) among the first results. Also, there's another website with the courses list and you can go directly to Computer Science with this URL: https://inscricoes.facieducacional.com.br/curso/ciencias-da-computacao
- Proof of email domain: On this URL (https://blog.wyden.com.br/noticias/central-de-contatos-faci/) you can find a list of teacher's institucional emails with the …

Add Faculdade Ideal Wyden

---

.github/workflows/release.yml

Hi, thanks to this repo, it saved my time collecting educational emails.
It's a lightweight and convenient library for developers, but I found it non-user-friendly to read or get the list of educational emails.
In this PR, I create a Github Action to build and run `src/swot/Compiler.kt` for each commit, and then release the output `out/artifacts/swot.txt` on Github Release.
Base on it, the user can conveniently download (or write code to download) the `swot.txt` file from the page of Github Release. (an example is the [following](https://github.com/zhangt2333/swot/releases))
Note that I name the release `latest` (The new one will overwrite the old one), because I have observed that your repo has a lot of commits and it's not a good idea to create releases for every commit (unless the old …

Add github-action to build and release swot.txt

---

lib/domains/uk/org/bryncelynnog.txt

Please Add
https://bryncelynnog.org.uk/
Bryn Celynnog Comprehensive School
Bryn Celynnog Bungalow, Penycoedcae Rd, Beddau, Pontypridd CF38 2AE
United Kingdom

Add Bryncelynnog Comprehensive School

---

lib/domains/uk/org/bonitas/ranelagh.txt

School website: https://ranelagh.bonitas.org.uk/
Courses: https://ranelagh.bonitas.org.uk/exam-boards/ - Computer Science offered at both GCSE and A Level - both 2 years.
Image showing that domain is accepted for emails: 
(site here: https://ranelagh.bonitas.org.uk/guidance/)

Added Ranelagh School under ranelagh.bonitas.org

---

lib/domains/berlin/rlg.txt

Rosa-Luxemburg-Gymnasium is a German gymnasium/academy/high school. The school's home page is https://www.rlo-berlin.de/cms3/, however, emails have the domain rlg.berlin.

Add Rosa-Luxemburg-Gymnasium (rlg.berlin)

---

lib/domains/pl/edu/elodz/zsp5.txt
lib/domains/pl/lodz/p/liceum.txt

Official websites:
https://zsp5lodz.pl/
https://liceum.p.lodz.pl/

Add Technical High School of Lodz and ZSP nr 5 Lodz

---

lib/domains/sh/school.txt

Our school.sh domain email is the official student email for the Center for Arts and Technology college. Our staff domain email (which corresponds to our official marketing website) is digitalartschool.com. You can reach me personally at kcarisse@digitalartschool.com. We would like to get the school.sh domain email usable so that our students can also benefit from increased access to the JetBrains code editor suite.
Here is an example of one IT related course spanning a length of 1.5 years https://digitalartschool.com/programs/network-security
Here is an example of students with the school.sh domain email within our teams environment:

adding student email domain for Center for Arts and Technology college

---

lib/domains/uk/ac/ardenuniversity.txt

The university official website URL:
https://arden.ac.uk
A URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: 
https://arden.ac.uk/our-courses/undergraduate/computing-degrees/bsc-hons-computing?source=google&medium=cpc&campaign=arden-de-brand-worldwide-search
Screenshot proof that students use ardenuniversity.ac.uk domain for email access:
https://drive.google.com/file/d/16fXGiqF0cDRlj9ez03WII0BTLjp-JZOt/view?usp=sharing

Arden University

---

lib/domains/com/eleve-istp.txt

1. Website URL : https://www.istp.fr/
3. IT related course (3 years) : https://www.istp.fr/etudiants/formations-dingenieur-en-apprentissage/formations/ingenieur-en-systemes-electroniques-embarques-isee/
Can be translated in english as a **Master’s Engineering Degree in Electrical Embedded Systems**
4. The whois data shows that the "eleve-istp.com" domain is owned by ISTP (field "Organization")
URL: https://www.whois.com/whois/eleve-istp.com

Add ISTP domain

---

lib/domains/ke/ac/mmarau.txt
lib/domains/ke/ac/mmarau/student.txt

- the school official website : https://mmarau.ac.ke
- the school address: Narok County, Nairobi, Kenya
- IT-related long-term course: https://www.mmarau.ac.ke/bachelor-of-science-in-information-science/
- our school emails end with mmarau.ac.ke, and students are assigned emails @student.mmarau.ac.ke

add Maasai Mara University

---

lib/domains/nz/ac/lincolnuni.txt

The university official website URL: https://www.lincoln.ac.nz/
A URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: https://www.lincoln.ac.nz/study/study-programmes/programme-search/master-of-applied-computing/
A URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students: https://www.ithelp.lincoln.ac.nz/how-to-guides/download-office365/ You can find _your lincolnuni.ac.nz email_ on the page regarding student email and MS Office package.

Added the domain for Lincoln student email

---

lib/domains/in/res/tifr.txt

Official website: www.tifr.res.in
Official name: Tata Institute of Fundamental Research
Website of the Computer Science department at the institute: https://www.tcs.tifr.res.in/

add the tifr.res.in domain

---

lib/domains/uk/ac/edinburghcollege.txt

Adding Edinburgh College domain for computer science students and teachers - https://edinburghcollege.ac.uk

Adding in edinburghcollege.ac.uk

---

lib/domains/org/pcastudentemail.txt

School website: https://www.plymouthchristian.org/
Engineering courses: https://www.plymouthchristian.org/wp-content/uploads/2021/06/2021-22-Secondary-Course-Description-Catalog.pdf (pages 35-36)

Add Plymouth Christian Academy.

---

lib/domains/eg/edu/metmans.txt

official website
https://metmans.edu.eg/
official email
info@metmans.edu.eg

adding Misr higher institute of commerce and computers in Mansoura (MET Academy) domain

---

lib/domains/de/musin/muenchen/thg.txt

See https://thg.musin.de,
other schools from Munich of the same type (called "Gymnasium" in Bavaria/Germany) are already present in this repository, for example
- https://github.com/JetBrains/swot/blob/master/lib/domains/de/musin/muenchen/gmm.txt
- https://github.com/JetBrains/swot/blob/master/lib/domains/de/musin/muenchen/lpg.txt
- ...

Add Theresien-Gymnasium München

---

lib/domains/email/evb.txt

We would like to add a new additional domain _evb.email_ which is used by the students of our school.
See this pull request for my initial request to add the domain _evb-gymnasium.de_: [Add Engelbert-von-Berg-Gymnasium #14119](https://github.com/JetBrains/swot/pull/14119#issue-1227114561).
**Website of school:** 
https://evb-gymnasium.de/

Add Engelbert-von-Berg-Gymnasium additional domain

---

lib/domains/org/dekalbschoolsga.txt

Dekalb County Schools, K-12, in metro Atlanta, GA, US. - https://dekalbschoolsga.org
* In the [curriculum](https://www.dekalbschoolsga.org/curriculum/high-school/) under "Information Technology" there are Computer Science and Programming sections that describe the courses that could utilize JetBrains products.
* When showing [how students can email their teachers](https://www.dekalbschoolsga.org/wp-content/uploads/2020/08/Students-Sending-an-Email-through-O365.pdf), it shows this dekalbschoolsga.org domain is used for email communications (see page 2).

Adds Dekalb County School District

---

lib/domains/uk/ac/sanger.txt

Wellcome Sanger Insitute is a research institute located in Cambridge, UK - world-leading in the use of large-scale genomic data to advance biology. The institute runs a PhD and Masters programmes (together with the University of Cambridge) and offers other training opportunities in computational biology and IT areas (apprenticeships, internships): https://www.sanger.ac.uk/about/study/

Adding Wellcome Sanger Insitute

---

lib/domains/uk/ac/qmu.txt

NB: E-mail is on the bare domain, but website only response on www.qmu.ac.uk

Added Queen Margaret University, Edinburgh

---

lib/domains/org/corsigaldus.txt

Galdus offers a software developer course
Source: https://www.galdus.it/sviluppatori-informatica/

Add 'corsigaldus.org' domain

---

lib/domains/cz/gympb.txt

Official website: https://gympb.cz/
IT courses: http://gympb.cz/wp-content/dokumenty/svp.pdf in sections 5.18 - 5.20 and apendix 40, 51, 52.
Proof that the school ownes the domain: https://www.nic.cz/whois/domain/gympb.cz/

Adding gympb.txt

---

lib/domains/com/onmicrosoft/schlaun.txt

In Muenster we´re all using Iserv: `nameOfTheStudent@[college].ms.de` emails (pascal, stein, and many more, just look up the results: https://www.google.com/search?q=iserv+ms.de), but in my college we can´t use the email address to text with other email addressers than `@schlaun.ms.de`. Luckily we also have a `nameOfTheStudent.jcs@schlaun.onmicrosoft.com` email address we can use for all this kind of stuff.
The URL of my college is: http://www.schlaun-gymnasium.de/
IT-related long-term (>1 year) course: http://www.schlaun-gymnasium.de/fach/informatik/
Please feel free to contact me if you have any questions!

http://www.schlaun-gymnasium.de/

---

lib/domains/uk/ac/psc.txt

Courses at: https://psc.ac.uk/courses/2023/compsci/
Proof domain is used by students:

Add psc.ac.uk

---

lib/domains/ca/epsb/share.txt

- School's official website URL is [https://rosssheppard.epsb.ca](https://rosssheppard.epsb.ca)
- 13546 111 Ave NW, Edmonton, AB T5M 2P2, Canada
- Offering CS and robotics course, see [https://rosssheppard.epsb.ca/academics/career-technology-studies/](https://rosssheppard.epsb.ca/academics/career-technology-studies/)
- Page that recognizes share.epsb.ca as an official student email [https://epsb.ca/news/students/howtoaccessonlinelearning.html](https://epsb.ca/news/students/howtoaccessonlinelearning.html)

Add Ross Sheppard High School

---

lib/domains/fr/lyceesaintnicolas.txt

Extensions differ between web site and e-mail domain :
* Web site : lyceesaintnicolas.com
* e-mail address domain name : lyceesaintnicolas.fr

Add Lycee Saint Nicolas Paris

---

lib/domains/uk/ac/cityofglacol.txt

Domain for students' accounts for City of Glasgow College (cityofglacol.ac.uk). Main domain for college: cityofglasgowcollege.ac.uk

City of Glasgow College added to the list

---

lib/domains/bo/edu/ccc.txt

Adds C.C.C. School, a HS located in Cochabamba, Bolivia

Add High School

---

lib/domains/uk/ac/bhasvic.txt

Official Website URL:
bhasvic.ac.uk
URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university:
https://www.bhasvic.ac.uk/courses/computer-science-a-level

Add Brighton Hove and Sussex Sixth Form College

---

lib/domains/school/oclock.txt

This is an equivalent to the oclock.io domain (already approved).
but we have made changes to our email strategy for some current and future students

Adding oclock.school

---

lib/domains/uk/ac/truropenwith/ghs.txt

Truro & Penwith College (UK), they use the domain @truro-penwith.ac.uk (already added) and @ghs.truropenwith.ac.uk - you can verify from the domain whois the college owns both domains. 
2 Year Computing BTEC: https://www.truro-penwith.ac.uk/courses/btec-level-3-national-extended-diploma-in-it-computing-games/
Extra info: A tweet to show they use email addresses from both domains - https://twitter.com/Truro_Penwith/status/1529112160537821185
Cheers

Add Truro & Penwith College Gmail (GHS) domain

---

lib/domains/do/edu/unicda.txt

Added new domain for Universidad Dominico Americana as it uses both icda.edu.do and unicda.edu.do

Added new domain for Universidad Dominico-Americana

---

lib/domains/hk/edu/clsmss.txt

Add Chiu Lut Sau Memorial Secondary School in Hong Kong to the database.
[School Website](https://www.clsmss.edu.hk/)
Address: 7 Yuen Long Tai Yuk Rd, Yuen Long, Hong Kong

Add clsmss in HK

---

lib/domains/fr/ip-paris.txt

add IPP Paris:
Name: Institut polytechnique de Paris (IP Paris)
Web: https://www.ip-paris.fr/en
Address: 5 Av. Le Chatelier 2ème étage, 91764 Palaiseau, France
Phone: +33 1 69 33 33 33

add Institut polytechnique de Paris

---

lib/domains/tz/ac/jriit.txt

The official Institute URL is https://jriit.ac.tz

Added jriit.ac.tz domain

---

lib/domains/no/rogfk/elev.txt
lib/domains/no/rogfk/skole.txt

I also added an english name for `elev.rogfk.no` (our student tenant)
Edit, website of all 31 schools: https://www.rogfk.no/vare-tjenester/skole-og-utdanning/opplaring-i-skole/skoler-i-fylket/videregaende-skoler-og-fagskole/
`skole` (employees) = school
`elev` = pupil

Add educator tenant for Rogaland Fylkeskommune

---

lib/domains/ro/cnvais.txt

Colegiul National Vasile Alecsandri is a national college in Iasi, Romania.
https://cnvais.ro

add Colegiul National Vasile Alecsandri

---

lib/domains/ch/ehl.txt

As mentioned in their press release:
https://news.ehlgroup.com/ehl-ecole-hoteliere-de-lausanne-becomes-ehl-hospitality-business-school

Changed name of EHL

---

lib/domains/de/pmhs.txt

added the Philipp-Matthäus-Hahn-Schule Nürtingen [(https://www.pmhs.de)](https://www.pmhs.de).
Link to page showing computer science related course: (e.g. https://www.pmhs.de/vollzeit/technisches-gymnasium/ - "Informatik" or https://www.pmhs.de/vollzeit/technisches-berufskolleg-1/ - "Informationstechnik") 
Link showing teacher e-mail addresses: https://www.pmhs.de/organisation-ablauf/schulleitung/
Student mails end on @pmhs.de too, but have more than three characters.

(+) added pmhs.de

---

lib/domains/se/taby/skola.txt

Official website: https://www.taby.se/ava-gymnasium/
Data and media technology education page: https://www.taby.se/ava-gymnasium/avas-program/teknik-innovation2/information--och-medieteknik/ 
the email used for students is firstname.lastname@skola.taby.se
and for teachers and admins is firstname.lastname@taby.se
however i could only find teacher and admin emails on the website and no proof for the student accounts execpt for my own email wich is a student email.
if that is not sufficient evidence here is the offical school mail <avagymnasium@taby.se>;

Add Åva gymnasium

---

lib/domains/cat/autonoma.txt
lib/domains/es/cragenomica.txt

Add cragenomica.es which is the domain for the reserachers of CRAG in UAB a leading in centre in agricultural genomics where lots of Phd, Master and undergraduate stundents use bioinformatics and would fancy the acces to JetBrains tools

Add CRAG from UAB

---

lib/domains/au/edu/qld/bbc.txt

Institution: Brisbane Boys' College
Location: Brisbane, Australia
Education: Primary and Secondary School (Elementary, Middle, and High School equivalent)
Email Users: Students, Academic Staff, Support Staff
Website: https://www.bbc.qld.edu.au
Proof of Email Domain: https://www.bbc.qld.edu.au/key-contacts
Proof of IT Courses: https://www.bbc.qld.edu.au/wp-content/uploads/2021/10/Curriculum-Handbook-2022_Senior-compressed.pdf#page=5

Add Brisbane Boys' College

---

lib/domains/ca/ab/gprc.txt
lib/domains/ca/nwpolytech.txt

Grande Prairie Regional College (GPRC) was renamed to Northwestern Polytechnic ([https://www.nwpolytech.ca/news/display.html?ID=2065](https://www.nwpolytech.ca/news/display.html?ID=2065)). AFAICT all email domains were changed to nwpolytech.ca
GPRC was originally added to this repository in #3612
Homepage: https://www.nwpolytech.ca/
Example program: https://www.nwpolytech.ca/programs/computer-systems-technology.html
Screenshot of the webmail login (can confirm if you click "Webmail" in the top-right corner of the homepage):

Rename gprc.ab.ca to nwpolytech.ca

---

lib/domains/si/sckr/vss.txt

name: Višja strokovna šola ŠC Kranj
website: https://sckr.si/vss/
same organization already has high school verified (sts.sckr.si)

vss sckr UNI

---

lib/domains/uk/ac/reading/student.txt

official university website: https://www.reading.ac.uk/
long-term IT related course: https://www.reading.ac.uk/ready-to-study/study/2022/computer-science-ug/bsc-computer-science
university recognising the domain: https://www.reading.ac.uk/digital-technology-services/service-catalogue/office-365

Add University of Reading

---

lib/domains/uk/ac/gateshead.txt

College homepage:
https://www.gateshead.ac.uk/
Computing course:
https://www.gateshead.ac.uk/courses/higher-national-diploma-hnd-computing-and-devops
Page demonstrating that student email addresses have 123456@students.gateshead.ac.uk format:
https://www.gateshead.ac.uk/how-get-google-classroom

Please add Gateshead College to academic institutions

---

lib/domains/eu/csvvg.txt

This PR adds the "CS Vincent van Gogh" high school to the school names list.
- [Official website URL](https://www.csvincentvangogh.nl/) (this differs from the student email, which has the csvvg.eu domain)
- CS Vincent van Gogh offers two IT related courses
- Informatics (no URL available, however, there are some references in downloadadle PDFs in https://www.csvincentvangogh.nl/downloads-en-protocollen)
- Robotics (https://www.csvincentvangogh.nl/robotklas)
- Email proof: I currently do not have access to my school email address since I am switching schools. On the contact page, there are mentions of the email address (https://www.csvincentvangogh.nl/contact-1) as well as in the school informational document (page 30, [here](https://www.csvincentvangogh.nl/files/domains/www.csvincentvangog …

Add CS Vincent van Gogh (NL)

---

lib/domains/gh/edu/ait.txt

I added the Accra Institute of Technology domain name to JetBrain swot in order for students and lecturers with their school email to be granted free licenses for JetBrains tools.

Added Accra Institute of Technology

---

lib/domains/hk/edu/cpce-polyu/common.txt

Official website: https://cpce-polyu.edu.hk
IT related programme:
[Associate in Information Technology](https://www.hkcc-polyu.edu.hk/en/programmes/associate-degree/programmeDetails.php?sid=17)
[Bsc (Hons) in Applied Sciences (Information Systems and Web Technologies)](https://www.speed-polyu.edu.hk/programme/applied-sciences-iswt)
Remark: HKCC and SPEED are operate by CPCE, PolyU
Proof:

Add Domain for CPCE-PolyU

---

lib/domains/org/jankollar.txt

Added Jan Kollar Gymnasium located in Bački Petrovac, Serbia.
https://www.jankollar.org/

Created jankollar.txt

---

lib/domains/pl/katowice/sltzn.txt

Adding 
Śląskie Techniczne Zakłady Naukowe
ul. Sokolska 26
40-086 Katowice, Poland
http://www.sltzn.katowice.pl/

add stzn.katowice.pl

---

lib/domains/org/millasd.txt
lib/domains/org/pcia.txt

Washington public school's Mill A School District #31 recently changed instructor emails to @millasd.org, and student email to @pcia.org. Added new domains to support this.
For verification:
- Mill A School district website is (by redirect): https://millasd.org
- Pacific Crest Innovation Academy website is not using new domains yet, but is at: https://pacificcrestia.org/
Thanks.

Added new domains from Mill A School District #31 / PCIA

---

lib/domains/cl/csangabrielcoquimbo.txt

Colegio San Gabriel Arcangel, the domains seems only to be used with Google Workspace for education due to pandemic, not sure

Colegio San Gabriel Arcangel

---

lib/domains/org/weldre4.txt

Add Windsor High School from Windsor Colorado.
https://whs.weldre4.org/

Add Windsor High School

---

lib/domains/lv/citadaskola.txt
lib/domains/lv/edu/liepa6vsk.txt

We have two domains
* liepa6vsk.edu.lv is used for Gmail (redirects to main domain)
* citadaskola.lv is Office365 (as well as main domain for homepage)

Add Liepājas Raiņa 6. vidusskola

---

lib/domains/net/es-rm.txt

School website: https://www.es-rm.eu/
This [page](https://www.es-rm.eu/index.php/en/academics/student-support-services) mentions that members of the staff have `@es-rm.net` emails. Not sure if that is sufficient to prove that students also get email addresses from that domain.

Add European School RheinMain

---

lib/domains/vn/edu/huce.txt

This one is the update to the **nuce.txt** file in the same folder. 
My university has changed the **official website** to: https://huce.edu.vn/. 
The old website which is: https://www.nuce.edu.vn/ has an announcement to redirect to the new website (since 15/11/2021).
New student's email will use **@huce.edu.vn** instead.
Please keep the old **nuce.txt** file since old students still using the old domain **@nuce.edu.vn**.
Thank you!

Add Hanoi University of Civil Engineering

---

lib/domains/uk/ac/stcg.txt

Website: https://stcg.ac.uk
List of all IT courses at the college: https://stcg.ac.uk/courses?keywords=computing&t=1
Examples of longer term courses:
* https://stcg.ac.uk/kingston-college/computing-and-it/software-development-technician-apprenticeship-level-3 (2y)
* https://stcg.ac.uk/kingston-college/computing-and-it/software-developer-apprenticeship-level-4 (3y)
* https://stcg.ac.uk/merton-college/computing-and-it/level-2-certificate-understanding-coding (1y)
Screenshot of email message details showing the college domain:

Add South Thames Colleges Group domain

---

lib/domains/tw/edu/usc/gm1.txt

An URL of a page at the official school website that says that students use this email domain
https://sites.google.com/a/g2.usc.edu.tw/g2/home

Add Shih Chien University gm1 domain

---

lib/domains/uk/ac/ke6n.txt

https://ke6n.ac.uk/
Offers A-level computer science (3rd level of education, years 12-13, 16+, UK)
https://ke6n.ac.uk/course/computer-science/

Add King Edwards College, Nuneaton

---

lib/domains/de/musin/muenchen/gg.txt

Request to add the Gisela-Gymnasium München-Schwabing to the list.
- offical school website URL: http://www.giselagym.musin.de/
- school address: Arcisstraße 65 80801 Munich
- IT related course: http://www.giselagym.musin.de/index.php/faecher/faecher-nut-sport/informatik/46-faecher/informatik/142-informatik-am-gisela
- school's wikipedia article: https://de.wikipedia.org/wiki/Gisela-Gymnasium

Request to add the Gisela-Gymnasium München-Schwabing

---

lib/domains/th/ac/cdti.txt

Just a sidenote, the vocational school is like a subset inside an Institute. So they use the same domain. The name for the institute is `Chitralada Technology Institute`.

Add Chitralada Vocational School

---

lib/domains/org/stpaulseoul.txt

Saint Paul Preparatory Seoul is an American international high and middle school based in Seoul, South Korea. It provides its high school students computing courses such as AP Computer Science and Intro to Computer Science. They are both full year courses.

Saint Paul Preparatory Seoul

---

lib/domains/org/popeprep.txt

Pope John Paul II Preparatory School Official Website: https://www.popeprep.org
Course offerings: https://www.popeprep.org/academics/curriculum - includes AP Computer Science and honors/intro to computer science for high school students.

Pope John Paul II Preparatory School

---

lib/domains/us/andoverma/k12.txt
lib/domains/us/andoverma/student.txt

Our school system has updated email domains from k12.andoverma.us to student.andoverma.us and this pull request reflects that change.

Updating Andover Public Schools Email Domain

---

lib/domains/de/hamburg/hlg.txt

Official website: https://www.hlg-hamburg.de
IT related course: https://www.hlg-hamburg.de/wp-content/uploads/2021/11/Profilangebot-2022.pdf
- see column 8 (Experimentieren, Simulieren, Interpretieren), row 2 (Profil begleitendes Fach 1)
- course is "Informatik", lasting 2 years (the entire "Oberstufe")
URL is recognized as official email domain: https://www.hlg-hamburg.de/kontakt/

Add domain hlg.hamburg.de

---

lib/domains/ec/edu/pucesm.txt

The university official website URL: https://pucem.edu.ec/
IT course offered by the university: https://pucem.edu.ec/grado/ingenieria-software
Screenshot showing that the domain is recognized by the university: https://i.postimg.cc/Jn2Z4p8J/sc-domain.png

Added PUCESM to domains

---

lib/domains/uk/org/cambridgeast.txt

URL: cambridgeast.org.uk or cast.education
2-year Computer Science A-level course: https://www.cambridgeast.org.uk/sixth-form/curriculum/computer-science
also 3-year CompSci GCSE course: https://www.cambridgeast.org.uk/Years-9-11/Curriculum/Computer-Science

Cambridge Academy for Science and Technology

---

lib/domains/org/ncclschool.txt

Adding Newark Center for Creative Learning, it is a non-profit private K-8 school in Newark DE
More info at https://www.ncclschool.org/

Adding NCCL School - Newark Center for Creative Learning

---

lib/domains/com/qegsonline.txt

The official website URL for QEGS Blackburn is https://www.qegsblackburn.com/ The email domain is qegsonline.com
This is a link to their comp sci course: https://www.qegsblackburn.com/sixth/a-level-subjects/computer-science/

Add files via upload for QEGS Blackburn

---

lib/domains/us/nc/k12/chccs.txt

just an extension of https://github.com/JetBrains/swot/pull/15555, which added the student domain. Teachers/Admins have a different address. (______@chccs.k12.nc.us)

Teacher/admin domain for Chapel hill-Carrboro city schools

---

lib/domains/de/buhmann-hannover.txt
lib/domains/de/buhmann.txt
lib/domains/schule/buhmann.txt

buhmann-hannover.de doesnt exist (anymore?).
Main url is https://buhmann.de which is also used by most teachers for mails, and https://buhmann.schule which is used for emails by students and some teachers.
(Proof from #7922: https://buhmann.de/wp-content/uploads/sites/5/2019/09/Buhmann_Festschrift_2016.pdf)

Update Buhmann school domains

---

lib/domains/uk/ac/gcs.txt

Campus 1,
Tycoch Rd, Sketty, Swansea SA2 9EB
Campus 2,
Belgrave Rd, Gorseinon, Swansea SA4 6RD,
Campus 3,
Units 1&2, Jubilee Ct, Swansea SA5 4HB,
Campus 4,
77 Walter Rd, Uplands, Swansea SA1 4QA
Campus 5,
Sketty Ln, Sketty, Swansea SA2 8QF
https://www.gcs.ac.uk - College URL
https://www.gcs.ac.uk/full-time-course/information-technology-btec-extended-diploma - IT/CS course
https://www.gcs.ac.uk/staff-student-portal - Domain confirmation

Add Gower College Swansea

---

lib/domains/in/ac/vitstudent.txt

vit.ac.in is the domain for faculty email ids. This domain is already added. The domain for student email ids is vitstudent.ac.in

Add student domain for Vellore Institute of Technology

---

lib/domains/ke/ac/kibu.txt

The university official website URL: https://kibu.ac.ke/
A URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: https://kibu.ac.ke/academic-programs/undergraduate-programmes/bachelor-of-science-in-information-technology/

Add an entry of Kibabii university

---

lib/domains/ca/qc/cegep-lanaudiere.txt
lib/domains/ca/qc/cegep-lanaudiere/etu.txt

Add domain for cegep-lanaudiere.qc.ca for teachers and change school name for the "etu" subdomain (new school name)

Cegep-lanaudiere

---

lib/domains/uk/ac/wqe.txt

**DOMAIN** 
https://wqe.ac.uk
**COURSES**
https://wqe.ac.uk/our-courses/a-levels/
Note: the website above has IT and computer science a levels, but there are also IT related Vocational courses (e.g. Level 3 diplomas)
**PROOF**
I don't have difinitive proof I can show that the school email is "person"@wqe.ac.uk, if I did it would have helped me quite a bit in the enrollment process. However, if you go anywhere on the wqe website, you'll find that they all have that sort of email

Adding WQE as a school (Wyggeston & Queen Elizabeth I College) 

---

lib/domains/py/edu/sansebastian.txt

Adding new domain for Universidad Autonoma San Sebastian . 
sansebastian.edu.py

Adding new domain for Universidad Autonoma San Sebastian  

---

lib/domains/dk/iba.txt

IBA Erhvervsakademi Kolding - IBA.DK

Adding new domain for IBA Erhvervsakademi Kolding

---

lib/domains/cn/bttc.txt

Added Baotou Teachers College
Webpage [http:](https://www.bttc.edu.cn/)  or [http:](https://www.bttc.cn/)

Added bttc.cn

---

lib/domains/cz/pbis.txt

**official website URL**: https://www.nordangliaeducation.com/pbis-prague   
**IT related activities**: There are programming courses but they don't appear on the website. There are also year round STEM extracurricular activities: https://www.nordangliaeducation.com/pbis-prague/outstanding-experiences#extracurricular-activities   
**school recognizes the domain**: At the contact us page the official e-mails are using the pbis.cz domain. https://www.nordangliaeducation.com/pbis-prague/contact-us

Create pbis.txt (Prague British International School)

---

lib/domains/de/gym-mellendorf.txt

Pull requests adds the Gymnasium Mellendorf, a gymnasium School in Germany to the lib.

Add Gymnasium Mellendorf to database

---

lib/domains/id/sch/smamuhammadiyah1jkt.txt
lib/domains/id/sch/smamuhammadiyah1jkt/student.txt

- the school official website URL: https://smamuhammadiyah1jkt.sch.id/
- the school street address, including city and country: Jalan Kramat Raya No.49 RT.03/RW.04 Kec. Kramat Kel. Senen - Central Jakarta - Indonesia
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course [Here](https://smamuhammadiyah1jkt.sch.id/ekstrakurikuler/)
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students. [Here](https://media.smamuhammadiyah1jkt.sch.id/wp-content/uploads/2022/12/06114728/Screenshot-from-2022-12-06-11-45-55.png)

Add SMA Muhammadiyah 1 Jakarta to List

---

lib/domains/vn/edu/ptnk.txt

I would like to request to add my school, VNU-HCM High School for the Gifted, to the directory.
Here is some additional information:
- The school is designated as a "high school for gifted students", and as such has been admitting students into its Informatics class alongside other specialized classes. Admission information for school year 2022-2023 is provided [here](https://ptnk.edu.vn/thong-tin-tuyen-sinh-ptnk-nam-hoc-2022-2023/) (in Vietnamese).
- Contact information can be found on the official school website (same as domain).
- Students and teachers alike can access webmail via a button on the navigation bar of the school website.
- The school's parent institution, [Viet Nam National University HCMC](https://vnuhcm.edu.vn/), has already been added to this directory.

Add VNU-HCM High School for the Gifted

---

lib/domains/jp/ac/tdj.txt

Added Todaiji Gakuen High School.
Official website: https://www.tdj.ac.jp/

Added Todaiji Gakuen High School

---

lib/domains/es/gva/edu/alu.txt

This domain is not specific to a school center, but to all the students of the centers of the new CDC (Digital Collaborative Center) project of the Valencian Community.
More information about CDC (Spanish): https://portal.edu.gva.es/cdc/es/inicio_cas/
Clarification: The emails ``@edu.gva.es`` are also used for university students but ``@alu.edu.gva.es`` is the new domain that is used for students of all levels of education.

Add @alu.edu.gva.es

---

lib/domains/ke/ac/uoeld.txt

Website: www.uoeld.ac.ke
Verify our programmes here: https://uoeld.ac.ke/sites/default/files/academic_programmes/Final%20Inside%20UoE%20A5%202018%20Landscape%20Academic%20Programmes.pdf
University of Eldoret owns the domain: uoeld.ac.ke

Add University of Eldoret

---

lib/domains/np/edu/eemc.txt

Everest Engineering College was formerly recognized as Everest Engineering College. This institution is providing  IT and Computer related  Bachelors of Engineering degrees since 2001 A.D. I am applying so that i can get my student license and use these awesome IDEs.
https://www.eemc.edu.np/contact

Added Everest Engineering College name and domain urls

---

lib/domains/gt/edu/mesoamericana.txt

followed instructions in order to add Mesoamericana University located in Guatemala. 
Reference Link: http://mesoamericana.edu.gt/

adding mesoamericana university

---

lib/domains/com/e-cdp.txt

Hi, I added the College de Paris university group to the list of domains. Thank you in advance for your approval.
University website: https://www.collegedeparis.com
University official email domain for the students (@e-cdp.com): https://support.collegedeparis.com/hc/fr/articles/5310139595549-Initialiser-mon-e-CDP-ID

Add University Collège de Paris, 75001 Paris, FR

---

lib/domains/com/onmicrosoft/ismonnet.txt

I have added IIS Jean Monnet, like requested on JetBrains help page, the official website of school is ismonnet.edu.it, but the student mail are on @ismonnet.onmicrosoft.com
Please can you add these school?
Thx

Adding IIS Jean Monnet

---

lib/domains/de/waldorf-augsburg.txt

Add domain of the Freie Waldorfschule Augsburg (waldorf-augsburg.de)
https://github.com/FreieWaldorfschuleAugsburg
https://waldorf-augsburg.de/
https://www.waldorf-augsburg.de/schule/schulleben/digitalisierung/
(school provides a min. 1 max. 2 year long programming course, see "Schülerengagement")
https://elektronisch.dev/
(see blue box "Freie Waldorfschule Augsburg" for further details)

Add waldorf-augsburg.de

---

lib/domains/np/edu/acme.txt

acme.edu.np domain added for [Acme Engineering College](https://www.acme.edu.np/)
Official website: https://www.acme.edu.np/
Programs offered: [Bachelors in Computer Engineering, 4 Years](https://www.acme.edu.np/p/bachelor-in-computer-engineering-4-years-63)
Programs offered: [M.Sc. in Information System Engineering, 2 Years](https://www.acme.edu.np/p/m-sc-in-information-system-engineering-2-years-65)

acme.edu.np domain for acme engineering college

---

lib/domains/ge/edu/ssu.txt

Original name: საქართველოს საავიაციო უნივერსიტეტი
English name: Georgian Aviation University
Website: https://ssu.edu.ge/

Added a new university

---

file/lib/domains/com/iescomercio.txt
lib/domains/com/iescomercio.txt

- College Official Website: https://iescomercio.com/
- '> 1 year IT related course offecered by IES Comercio: https://iescomercio.com/images/historico/Oficina/folletos/Trip_Inform%C3%A1tica.pdf or https://iescomercio.com/oferta-educativa (scrolling down, after secondary courses).
- proof 1: Screen shot of a warning message showed in the gmail interface because I sent an email from another corporative account (unirioja.es) to my students (before I get the iescomercio.com one). Now, if I read the message, it alerts me saying "take care, this account (...@unirioja.es) is very similar to (...@iescomercio.com) but it does not belong to your domain.
- proof 2: an email sent from the corporative account.

IES Comercio

---

lib/domains/ca/torontomu.txt

Ryerson University recently changed their name to Toronto Metropolitan University. Added the new domain of @torontomu.ca

Adding TorontoMetUniversity Domain

---

lib/domains/ke/ac/mut/student.txt

The Murang'a university of technology is a public university in Murang'a, Kenya.
Checkout the university's [website](https://www.mut.ac.ke/)

added murang'a university to list

---

lib/domains/com/rondebosch.txt

Rondebosch Boys' Schools is a network of public boy's primary and secondary schools in Cape Town, South Africa registered with the [National Department of Basic Education](https://www.education.gov.za) in South Africa.
**Domain** - <https://rondebosch.com>
**High school** - _Web:_ <https://rondebosch.com/high/contact/> | _Telephone:_ +27 (21) 686 3987  
**Prep school** - _Web:_ <https://rondebosch.com/prep/contact/> | _Telephone:_ +27 (21) 686 4635
**Address:** Rondebosch Boys' High School  
Canigou Avenue, Rondebosch 7700, Cape Town, South Africa. 
**Email:** [infoline@rondebosch.com](mailto:infoline@rondebosch.com)  
**Office Hours:** 08:00 – 15:30 (GMT+2)
The school offers Information Technology subjects in both Preparatory and High School levels. Please find the academic pages related …

Add Rondebosch Boys' Schools

---

lib/domains/mk/edu/next.txt

- The university official website URL, if it is different from the domain you are submitting: 
https://next.edu.mk/
- A URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university
https://next.edu.mk/softversko-inzenerstvo-i-inovacii/

Add Brainster Next College

---

lib/domains/org/utcncst.txt

The school website is utcn.org.uk

Added University Technical Collage Norfolk

---

lib/domains/np/edu/kist.txt

Established in 1995, KIST is now a top +2 college in Nepal that offers high standard NEB + 2 Science & Management courses, a range of top quality Bachelor’s degrees – BBA, BIM, BIT, BBS & BSc Microbiology – followed by excellent Master’s degrees – MBS & MSc Microbiology.
Domain: https://kist.edu.np/introduction

Added kist college domain

---

lib/domains/ro/edu/nt/cni.txt

\lib\domains\ro\edu\nt\cni.txt for @cni.nt.edu.ro
http://cni.nt.edu.ro/new/
IT course: http://cni.nt.edu.ro/new/index.php/profil/
RO: Colegiul National De Informatica Piatra Neamt, Romania 
EN: National College of Computer Science Piatra Neamt, Romania
Address: Romania, Piatra-Neamț, Str. Mihai Viteazu, Nr. 12, 610226

Adding a new School for RO domain

---

lib/domains/eg/edu/deltauniv.txt

Name : Delta University for Science & Technology
Location : Egypt
Official Domain : deltauniv.edu.eg

adding Delta University in Egypt to domains deltauniv.edu.eg

---

lib/domains/net/lcieducation.txt

Added "LaSalle College Institute - Vancouver" for "@lcieducation.net"

Added LaSalle College Institute Vancouver

---

lib/domains/cn/net/shouhua.txt
lib/domains/com/shohzyxy.txt

The school's official domain name has been changed from shouhua.net.cn to shohzyxy.com
official website:shohzyxy.com
it website:http://www.shohzyxy.com/index.php?c=article&a=type&tid=15

The school's official domain name has been replaced

---

lib/domains/ke/ac/karu/s.txt

University URL - https://karu.ac.ke/
IT-related course URL - https://karu.ac.ke/course/bachelor-of-science-in-computer-science/

Domain name for Karatina university

---

lib/domains/uk/sch/kent/bordengrammar.txt

Added file for Bordengrammar school @ kent.sch.uk
School is a mixed secondary AND higher education offering A-Level studies.
https://www.bordengrammar.kent.sch.uk/sixth-form/ks5 in which an OCR computer science A-Level is offered.

Add UK Borden Grammar School

---

lib/domains/lv/lumii.txt

Added Institute of Mathematics and Computer Science, which is part of University of Latvia and organises UL's CS master study programm.

Add lumii.txt for an institute of University of Latvia

---

lib/domains/au/edu/nsw/cranbrook.txt

website url: https://www.cranbrook.nsw.edu.au/
Proof IT course is offered: https://www.cranbrook.nsw.edu.au/wp-content/uploads/2022/09/Information-for-Overseas-Families-Brochure-March-2022.pdf 
- p6 software design and development ( 2 year course year 11 and 12)
Proof of domain: 
At the bottom of 
https://www.cranbrook.nsw.edu.au/ 
there are emails with the @cranbrook.nsw.edu.au domain for each school that cranbrook has

Adds Cranbrook school

---

lib/domains/ph/edu/hcdc.txt

School name: Holy Cross of Davao College
Address: Sta. Ana Avenue corner C. Guzman Street, Barangay 14-B, Davao City, Philippines
Website: https://www.hcdc.edu.ph/

added Holy Cross of Davao College

---

lib/domains/kr/re/kist.txt

Korea Institute of Science and Technology domain is "kist.re.kr"

Added Korea Institute of Science and Technology Domain

---

lib/domains/de/musin/muenchen/mtg.txt

Hi there,
the Maria-Theresia-Gymnasium in Munich is already contained in swot (see de/musin/mtg.txt).
Time has passed and the email addresses they are now issuing to their students use @mtg.muenchen.musin.de
So this PR is about adding this new domain to swot
Best regards

Added new domain of MTG in Munich

---

lib/domains/jp/kosen-ac/oita.txt

The following is a description of what was pointed out.
- the school official website URL　
　→ https://www.oita-ct.ac.jp/
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
　→ https://onct.oita-ct.ac.jp/seigyo/
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students
　

"National Institute of Technology, Oita College"

---

lib/domains/np/edu/nec.txt

The Nepal Engineering College was established in 1994 as the first privately led not-for-profit social organization providing engineering education in Nepal and is the largest engineering college in terms annual student intake as well as in terms of area. Its main campus is located at Changunarayan, Bhaktapur
Domain: https://nec.edu.np/

Added Nepal Engineering College Domain

---

lib/domains/us/de/k12/ncs.txt

School website: https://newarkcharterschool.org/
At the High School, we offer a CompSci STEM pathway.  
This page shows our email domain: https://newarkcharterschool.org/student-technology-support

Adding Newark Charter School

---

lib/domains/edu/iu.txt

New students and faculty are encourage to use the iu.edu domain for new email address creation and in some cases those users will not have the campus specific ones already included in this project (Ex: iub.edu, iuk.edu, etc.). 
More can be found here: https://kb.iu.edu/d/aufj.

Adding iu.edu for system-wide Indiana University domain

---

lib/domains/fr/icea-edu.txt

Institut Catholique Européen des Antilles (ICEA)
URL : https://icea-edu.fr/

Add European ICEA Catholic Institute

---

lib/domains/uk/ac/libf.txt

Website: https://www.libf.ac.uk
Course: https://www.libf.ac.uk/study/undergraduate/bsc-(hons)-in-finance-investment-and-risk
Staff domain: libf.ac.uk
student domain: edu.libf.ac.uk

add London Institute of Banking and Finance (LIBF)

---

lib/domains/org/saviochs.txt

adding St Dominic Savio High School located in Austin Texas
https://www.saviochs.org/

add St Dominc Savio High School

---

lib/domains/uk/ac/nclan/my.txt

Main website: [https://www.nclanarkshire.ac.uk/](https://www.nclanarkshire.ac.uk)
List of computing related courses available at this College: [https://www.nclanarkshire.ac.uk/courses/computing-and-digital-technologies](https://www.nclanarkshire.ac.uk/courses/computing-and-digital-technologies)
Email login recognising official domain for students:

Adding 'New College Lanarkshire' 

---

lib/domains/ph/edu/stellamarisdavao.txt

Hi @philipto 
This is related to this previous  [PR](https://github.com/JetBrains/swot/pull/17006) you close this because you mention that there is a sign of fraud, but you open the wrong url. The correct url of the school is https://www.stellamarisdavao.edu.ph/
which is this
And has its certificate is here

add stellamarisdavao.txt

---

lib/domains/kr/go/goe/woosungh.txt

I added an high school in the Republic of Korea.
official website URL: https://woosung.hs.kr
Street Address: `Gocheon-Dong 496, Uiwang-si, Gyeonggi-do `

Add: WooSung High School

---

lib/domains/pl/2lopoznan.txt

School website: http://2lo.poznan.pl/
School IB official page: https://www.ibo.org/school/001349/  (this one is in English)
School address: Matejki 8/10, Poznań, Poland

added Second High School in Poznań

---

lib/domains/uk/sch/northumberland/wark.txt

Addition of a school (Wark C of E School): https://www.warkprimaryschool.co.uk/

Addition of Wark C of E School

---

lib/domains/uk/ac/crick.txt

add Francis Crick Institute domain

---

lib/domains/br/edu/etfbsb.txt

WHOIS:
https://registro.br/tecnologia/ferramentas/whois/?search=etfbsb.edu.br
EXPLAIN:
This domain is used internally students to access tools, as Google for Education. The main site is https://www.ifb.edu.br

Add etfbsb.edu.br

---

lib/domains/mx/edu/cbtis71.txt

Add `CBTis 71` or `Centro de Bachillerato Tecnológico, industrial y de servicios 71`.
It's a high school located in Veracruz, Mexico.
Website: https://cbtis71.edu.mx

Add CBTis 71

---

lib/domains/it/iismatteifortunato.txt

Reverts JetBrains/swot#17173
Hi, i'm reverting this pull request because you used a wrong domain for the emails, the official domain for the emails is: example@didamatteifortunato.it
The proof is here as you can see: https://www.iismatteifortunato.edu.it/ufficio-relazioni-pubblico/
Check the emails present in that page...
I'm writing this because i tried to apply for the license, but the website says that the email i used is not valid

Revert "Add files via upload"

---

lib/domains/uk/sch/bristol/cotham.txt

Add record for Cotham School.
cotham.bristol.sch.uk
(https://www.cotham.bristol.sch.uk)
JetBrains support ref 5057224

Add Cotham School

---

lib/domains/uk/sch/herts/parmiters.txt

Added Parmiter's School, High Elms Ln, Watford WD25 0UU
parmiters.herts.sch.uk

Parmiters School

---

lib/domains/org/donboscocairo.txt

Istituto Tecnico Industriale Salesiano (Salesian Industrial Technical Institute) - Don Bosco Cairo.
Official site: https://donboscocairo.org

Add extraterritorial Italian school of Cairo

---

lib/domains/np/edu/heraldintlcollege.txt

Founded in 2063 B.S. (2006 A.D.) under the umbrella of Herald Education Network, Herald International College has emerged as one of the best academic institutions in Nepal. It is run by a team of dedicated educationists, professionals and renowned academicians. Our students, faculties and staff share a commitment to work hard for the advancement of our society. 
Here is official site: [heraldintlcollege.edu.np](url)

add: Herald International Collage from Nepal

---

lib/domains/com/newburyportschools.txt

This domain covers the entire Newburyport Public School District for students.

Added the Newburyport Schools Domain (Newburyportschools.com)

---

lib/domains/uk/sch/hants/brookfield.txt

This domain belongs to Brookfield Community School, a secondary school based in Hampshire, UK. The school offers GCSE computing courses and has a physical site with over 1750 students in attendance. It is recognised by the UK government as an official state-run education establishment.
> Website: https://brookfield.hants.sch.uk
> Government confirmation: https://get-information-schools.service.gov.uk/Establishments/Establishment/Details/116419

Add Brookfield Community School

---

lib/domains/com/onmicrosoft/pccegoa.txt

Padre Conceicao College of Engineering is an Engineering college affiliated with Goa University, India.
Website: https://pccegoa.edu.in/

Add Padre Conceicao College of Engineering

---

lib/domains/gt/edu/itics.txt

Official site:
https://itics.edu.gt/
Another domain that proves .edu.gt domain it's working https://nube.itics.edu.gt

Adding ITICS Guatemala

---

lib/domains/us/ny/k12/lvcsd.txt

lvcsd.k12.ny.us Domain changed to locustvalleyschools.org

LVCSD Domain changed

---

lib/domains/au/edu/aiict.txt

URL: https://aiict.edu.au/.
URL for courses: https://aiict.edu.au/courses/ (specific course: https://aiict.edu.au/courses/certificate-iv-in-information-technology-networking/).

Add aiict.edu.au

---

lib/domains/online/linkiafp.txt

Linkia FP 
**Official Website**
Website: https://linkiafp.es/
Currently studying: https://linkiafp.es/fp-grado-superior-desarrollo-de-aplicaciones-web-a-distancia/   which is a IT-related long-term course (2 years)
I think they changed the domain for their emails from linkiafp.es to linkiafp.online for this semester, since the domain used to end with "@linkiafp.es" last semester. The one I'm using right now is marccabanapinlac7393@linkiafp.online.

Add LinkiaFP new domain

---

lib/domains/at/kunstuni-linz.txt

The [University of Art and Design Linz](https://kunstuni-linz.at/) (a.k.a. University of Arts Linz) switched to a new official domain name sometime last year.
The old domain, [for which there already exists a file](https://github.com/JetBrains/swot/blob/master/lib/domains/at/ufg.txt), redirects to the new domain but continues to be in active (and exclusive, AFAIA) use for some services.
Students can also essentially still use the old domain for email, see [the IT dept's homepage](https://kunstuni-linz.at/IT-Services.1298+M52087573ab0.0.html) (scroll past the images for the text update), which is why I'm adding a new file rather than renaming the old one.

Add new domain for existing uni

---

lib/domains/mx/edu/conalepmex.txt

Colegio de Educación Profesional Técnica del Estado de México
Pertenece a la Secretaría de Educación del Gobierno del Estado de México
Identificado con el dominio conalepmex.edu.mx

CONALEP Estado de México

---

lib/domains/pl/edu/elodz/lo26.txt

Official website URL: https://www.lo26.pl/
A URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: https://www.lo26.pl/a/oferta-edukacyjna-202324
A URL of a page  showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students: https://www.lo26.pl/contact/ (official contact email addresses are under submitted domain)

Add XXVI LO High School in Łódź, Poland

---

lib/domains/org/ferraris.txt

the university official website URL: https://www.itiferraris.edu.it/
http://2.228.35.46/accessorapido/orario/sttIndex.htm
a URL of a page showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students: 
https://www.itiferraris.edu.it/attachments/article/330/Ottenere%20e%20Installare%20Office%20365.pdf

Added ITI Galileo Ferraris School

---

lib/domains/uk/ac/tameside.txt

Links to IT courses offered:
- [16-18 School Leavers](https://www.tameside.ac.uk/pages/courses_search.aspx?a=9&x=a) (e.g. [Level 3 Computing](https://www.tameside.ac.uk/pages/course_info.aspx?x=178284))
- [Adults](https://www.tameside.ac.uk/pages/courses_search.aspx?a=9&x=c) (e.g. [Higher National Diploma in Computing](https://www.tameside.ac.uk/pages/course_info.aspx?x=179501))
The college provides emails to students in the format: <STUDENT_NUMBER>@tameside.ac.uk e.g. `123456@tameside.ac.uk`
Unfortunately, I could not find a public link that proves this directly, however, you can see a reference to this fact in [the student portal](https://lbox.tameside.ac.uk/ProPortal/_CCC/Authentication/CCCLogin.aspx):
> Your username for Student Portal is simply your student number
(don't put …

Create tameside.txt in /uk/ac

---

lib/domains/org/syossetschools.txt

Syosset Senior High School is part of the wider Syosset Central School District. Even though it is a high school, it does offer a lot of  Higher Level Education Courses, including but not limited to, A.P. courses, SUPA courses, and many more.
a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the school:
https://www.syossetschools.org/Page/659
(Also here is the Curriculum guide website, where you can see all the different Courses Syosset Senior High School has to offer):
https://www.syossetschools.org/domain/283
(Found a better document that satisfies the requirement)
https://www.syossetschools.org/cms/lib/NY50000216/Centricity/Domain/291/SHS%20Online%20Learning%20Plan.pdf

Adding Syosset CSD, primarily for Syosset HS

---

lib/domains/uk/sch/bristol/redlandgreen.txt

[Redland Green](https://www.redlandgreen.bristol.sch.uk)
[North Bristol Post 16](https://www.nbp16c.org.uk)

Added Redland Green North Bristol Post 16 center

---

lib/domains/com/debhiss.txt

Debhiss School (debhiss.com)
Daunne English Boarding Secondary School, Bardaghat-4, Nawalparasi(BSW), Lumbini, Nepal

Debhis School (debhiss.com) added

---

lib/domains/cn/edu/xaufe.txt

Official website(in chinese): [https://www.xaufe.edu.cn](https://www.xaufe.edu.cn)
We have a Information Institute provided CS and SE major, see the intro page(also in chinese): [https://www.xaufe.edu.cn/yxsz1/xxxy1.htm](https://www.xaufe.edu.cn/yxsz1/xxxy1.htm) for more details.
We use `@xaufe.edu.cn` as a school issued email suffix for students, you can view it at the [email login page(also, in chinese)](https://mail.xaufe.edu.cn/). The `@mail.xaufe.edu.cn` suffix is for faculty use.
Last, I use the school issued email as a git commit email to let you make sure it's vaild for use.

Add Xi'An University of Finance and Economics

---

lib/domains/mx/edu/uan.txt

The email domain for the university is uan.edu.mx. My institution is added outside of the "edu" folder in the base MX, and I have already tried accessing the products with different domain endings like .com. However, it says that my email does not belong to any university. I hope that by adding it, it will work.

add the edu domain for the Universidad Autonoma de Nayarit

---

lib/domains/kr/go/cbe/sangdang-h.txt

- name:
- (KR) 상당고등학교
- (EN) Sangdang High School
- official website URL: https://school.cbe.go.kr/sangdang-h

Add Sangdang High School

---

lib/domains/uk/sch/derbyshire/queenelizabeths.txt

School website URL (matches email domain requested): https://www.queenelizabeths.derbyshire.sch.uk/
Computer Science A-Level course (2 years) described on p16 of the sixth-form prospectus available on the school URL: https://www.queenelizabeths.derbyshire.sch.uk/wp-content/uploads/sites/5/2022/10/Sixth-Form-Prospectus-2023-24-web.pdf

Add Queen Elizabeth's Grammar School, Derbyshire, UK

---

lib/domains/uk/ac/sheffcol.txt

Institution:
The Sheffield College is a UK based college level institution that offers a variety of qualification levels, among them are university equivalent IT related qualifications (such as ones mentioned below).
Website:
https://www.sheffcol.ac.uk/
Official Email Domain:
@sheffcol.ac.uk
Email Users:
[X] Students
[X] Teachers
[  ] Alumni
Examples of longer term (>1yr) University level IT related courses available:
HNC Computing (2yrs):
https://www.sheffcol.ac.uk/courses/page/8F245574-F215-495C-B58F-C33E0A957907
BA Hons Game Design (3yrs):
https://www.sheffcol.ac.uk/courses/page/FD211490-A2FC-43E0-AC5E-A52F1D7C5D32
Address:
There are many campus' but the main 2 are as follows:
The Sheffield College, City Campus, Granville Road, Sheffield, S2 2RL, UK
Hillsborough Campus, Livesey Street, …

Added 'The Sheffield College' as a valid domain.

---

lib/domains/hu/gde.txt

Previously added as gdf.hu, became University instead of College this year GDF->GDE
Offical website:
https://gde.hu
Courses (long term, BSc):
https://gde.hu/computer-science-engineering
Teachers with email domain:
https://gde.hu/oktatok

Dennis Gabor University, Budapest

---

lib/domains/ie/tus.txt

Add the Technical University of the Shannon. Ireland

Add TUS - Technical University of the Shannon, Ireland

---

lib/domains/uk/sch/derbyshire/tibshelf.txt

Official domain:
https://www.tibshelf.derbyshire.sch.uk/
Relevant IT course lasting longer than 1 year:
https://www.tibshelf.derbyshire.sch.uk/page/?title=Computer+Science&pid=78
Page with recognition of .sch.uk domain name in email addresses:
https://www.tibshelf.derbyshire.sch.uk/page/?title=How+to+get+in+touch&pid=99
Student email login portal:
https://outlook.com/students.tibshelf.derbyshire.sch.uk

Add Tibshelf Community School

---

lib/domains/au/edu/kbs.txt

Add the latest domain name for Kaplan Business school - kbs.edu.au  Existing one is kaplanstudent.edu.au.

Add Kaplan Business School

---

lib/domains/pl/edu/zst-radom.txt

Please add Zespół Szkół Technicznych
im. Tadeusza Kościuszki w Radomiu to school list
School Official Website: https://zst-radom.edu.pl/
School Location: City: Radom, Street: Bolesława Limanowskiego 26/30, Country: Poland
School offers long-term course (5 years): https://zst-radom.edu.pl/index.php/kierunki-ksztalcenia-2/
Major courses offered at the school associated with computer science are:
technik informatyk(IT technician)
technik programista(programmer technician).
Students & Teacher email domain: zst.radom.pl

Add zst Radom (Zespół Szkół Technicznych im. Tadeusza Kościuszki w Radomiu) from Poland

---

lib/domains/no/agderskolen.txt
lib/domains/no/agderskolen/elev.txt
lib/domains/no/vgs/tangen.txt

The Aust Agder and Vest Agder county in Norway has been combined and is now called Agder. All highschool studens in this new county are now included in this domain.
Tangen is located in Agder. The tangen domain is exclusivly for the employees of Tangen highschool. Our students is part of hte Agderskolen domain.

Added Tangen domain and updated Agderskolen description.

---

lib/domains/vn/edu/qnu/st.txt

Please add Quy Nhon University to the school list
School Official Website: https://qnu.edu.vn/
School Location: 170 An Duong Vuong street, Quy Nhon City, Viet Nam Country

Quy Nhon University - (Viet Nam)

---

lib/domains/br/com/sempreuni7.txt
lib/domains/br/edu/uni7.txt

Modified from "uni7.edu.br" to "sempreuni7.com.br".

change Centro Universitário 7 de Setembro (University Center September 7)

---

lib/domains/mx/edu/cobaej.txt

COBAEJ is a high school.
Our school offers training in computer science, where we teach our students about programming.
https://cobaej.edu.mx/directorio?type=academic-offer

Add COBAEJ (Colegio de bachilleres del estado de Jalisco)

---

lib/domains/de/drsneuwied.txt
lib/domains/de/drsschueler.txt

Page of the school: https://www.drsneuwied.de/
Page of the long term it course: https://www.drsneuwied.de/index.php/bildungsangebote/berufsschule/it-berufe/fachinformatikerin (We have "Ausbildung" in germany, which is 3 years long by default.)
Proof that drsschueler.de is also part of the school: Is there a good way I can proof that without doxxing myself? 😅I have Outlook and MS Teams, which *could* be used as screenshots, but what part do you need as proof?
Background-Information about the 2 domains:
Teacher emails use drsneuwied.de and students use drsschueler.de. Sadly the website doesn't show any students mails, which is why I can't link the page to proof that.

Add David-Roentgen-Schule Neuwied

---

lib/domains/pl/edu/zst-radom.txt
lib/domains/pl/radom/zst.txt

Please change domain of Zespół Szkół Technicznych
im. Tadeusza Kościuszki w Radomiu school
School Official Website: https://zst-radom.edu.pl/
School Location: City: Radom, Street: Bolesława Limanowskiego 26/30, Country: Poland
School offers long-term course (5 years): https://zst-radom.edu.pl/index.php/kierunki-ksztalcenia-2/
Major courses offered at the school associated with computer science are:
technik informatyk(IT technician)
technik programista(programmer technician).
Students & Teachers email domain: zst.radom.pl

Change domain of zst Radom (Zespół Szkół Technicznych im. Tadeusza Kościuszki w Radomiu) from Poland 

---

lib/domains/fr/es-be.txt
lib/domains/net/es-be.txt

My school uses `es-be.net` for my email but `es-be.fr` for their website.
Website : https://es-be.fr/lycee-saint-michel/
IT Course : https://es-be.fr/wp-content/uploads/2021/05/Combinaisons-des-sp%C3%A9cialit%C3%A9s-en-classe-de-1%C3%A8re-%C3%A0-SMDB.png
> "NSI" stands for _Numérique et sciences informatiques_ which means _Digital and computer sciences_
Email Domain Proof : 
I couldn't find a better proof but I can attach other screenshots if needed.

Add Saint Michel des Batignolles

---

lib/domains/university/miva.txt

Official website: https://miva.university/
Page for a 4-year programme: https://miva.university/bsc-in-computer-science/

Adding Miva Open University latest domain.

---

lib/domains/org/marsk12.txt

It is the domain for the Mars Area School District (located in Mars, PA).

Register marsk12.org as school domain

---

lib/domains/com/stswithuns.txt

This domain belongs to St Swithun's, a secondary school and sixth form college based in Winchester, UK. The school offers computing courses and has a physical site with over 700 students in attendance. It is recognised by the UK government as an official education establishment.
> Website: https://stswithuns.com/
> Government confirmation: https://get-information-schools.service.gov.uk/Establishments/Establishment/Details/116534

Add St Swithun's

---

lib/domains/id/ac/ft-umt.txt

Requested to add new Education Institution domain called "@ft-umt.ac.id"
UMT stands for Universitas Muhammadiyah Tangerang or Muhammadiyah University of Tangerang in english, UMT is a university located in Tangerang City, Banten, Indonesia.
FT stands for Fakultas Teknik or Engineering Faculty in english.
UMT is registered under the Ministry of Education, Culture, Research, and Technology of Indonesia.
Official site : https://umt.ac.id/ft/

Requested Fakultas Teknik UMT domain

---

lib/domains/ua/com/boiko.txt

https://boiko.top/ is the official website.
You can also check the information provided by https://kh.isuo.org/schools/view/id/11711.

Add Boiko School domain

---

lib/domains/ae/nasdubai.txt

Added to .ae domains. https://nasdubai.ae for school website and more information.

Nord Anglia International School Dubai Addition

---

lib/domains/ke/ac/must.txt

University official website URL
> https://www.must.ac.ke/
URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university
> https://sci.must.ac.ke/bachelor-of-science-in-computer-science/
URL of a page showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.
> https://research.must.ac.ke/about-6/
The above url redirects to research page where the email is provided. The email has a domain for the university

- Added top level domain for must

---

lib/domains/org/esuhsd.txt
lib/domains/org/esuhsd/students.txt

Makes all subdomains available for East Side Union High School District. Previously, only the student subdomain was included, which left the educators out.
Domain: [esuhsd.org](https://www.esuhsd.org)

Update East Side Union High School District

---

lib/domains/sa/edu/rcjy.txt

rcjy.edu.sa is associated with teachers and students of Jubail Industrial College
There are programs for a Bachelor's degree in Computer Science and a Diploma in Information Technology majors

Add - Jubail Industrial College

---

lib/domains/de/osrw.txt

School Name:
Oberschule Rauschwalde Görlitz
School Website:
[osrw.de](https://osrw.de)
Education Level: High School or equivalent

Add osrw.de

---

lib/domains/uk/ac/cirencester.txt

Added cirencester.ac.uk domain. A college in South West England.

Added cirencester

---

lib/domains/br/com/cogna.txt

The cogna.com.br is a conglomeration of universities, and the teachers don't have more email for specific domain of universities.

Added  cogna.com.br domain

---

lib/domains/com/hw.txt
lib/domains/com/hwemail.txt

@hw.com is used for teachers and @hwemail.com is used for students. There is no site hosted at hwemail.com, but there are detailed whois records: https://www.whois.com/whois/hwemail.com

Adds Harvard Westlake School

---

lib/domains/ch/gymneufeld.txt
lib/domains/ch/lerbermatt.txt

Hi
While I don't have professional affiliations with both institutions these days I used to work for both and thus know them. They are (with minor differences) following the same curriculum in the canton of Bern, Switzerland as institutions already registered using the following domains:
* gymkirchenfeld.ch
* mygymer.ch
* gymburgdorf.ch
* stud.gymthun.ch
| Institution | Official websites | Computer Science Courses |
| ---------- | ---------- | ---------- |
| Gymnasium Neufeld | https://www.gymneufeld.ch/ | https://gymneufeld.ch/gymnasium/bildungsangebot/ |
| Gymnasium Lerbermatt | https://www.lerbermatt.ch/ | https://informatik.lerbermatt.ch/ |
I hope I got everything right

Add Gymnasium Lerbermatt and Neufeld

---

lib/domains/uz/jdpu.txt
lib/domains/uz/jspi.txt

Please update to our new domain as our institute has changed to university status!
https://uz.wikipedia.org/wiki/Jizzax_davlat_pedagogika_universiteti

Update and rename jspi.txt to jdpu.txt

---

lib/domains/fr/esad-pyrenees.txt

Add ESAD to the french domains
ESAD (Ecole supérieur d'art et de design des Pyrénées => Pyrenees College of Art and Design) is a public institution of higher artistic education whose studies lead to national diplomas.
The school's curriculum includes courses in design and web-design in particular, with students developing web and programming projects.
Here is the school's [website](https://esad-pyrenees.fr/) and the [Wikipedia page](https://fr.wikipedia.org/wiki/%C3%89cole_sup%C3%A9rieure_d'art_et_de_design_des_Pyr%C3%A9n%C3%A9es), both in French

Add ESAD to fr domains

---

lib/domains/uk/sch/lincs/kings.txt

Main website: https://kings.lincs.sch.uk/
TKSG is not only a secondary school, higher courses in Computer Science are provided: https://kings.lincs.sch.uk/computingalevel

Add King's School Grantham

---

lib/domains/uk/org/busheymeads.txt

Add Bushey Meads Secondary School which is based in Bushey, Hertfordshire
https://busheymeads.org.uk/

Bushey Meads Secondary School, UK

---

lib/domains/de/gghi.txt

* official website: https://www.goethegymnasium-hildesheim.de/
* offers computer science classes up until graduation: https://www.goethegymnasium-hildesheim.de/index.php/component/k2/item/278-informatikunterricht
* uses ISERV platform with gghi.de as a domain: https://www.goethegymnasium-hildesheim.de/index.php/component/k2/item/115-iserv

Add gghi.de

---

lib/domains/stoplist.txt

unicaen.fr is corresponding to file /lib/domains/fr/unicaen.txt

unicaen.fr is not a fraud

---

lib/domains/tr/edu/bogazici.txt

Bogazici University is in the process of converting its domain from `boun.edu.tr` to `bogazici.edu.tr`. So I'm adding the new domain to accommodate this change. 
- add `lib/domains/tr/edu/bogazici.txt`
- the file contents are the same as `lib/domains/tr/edu/boun.txt` 
- `boun.txt` [permalink](https://github.com/JetBrains/swot/blob/1730645625e2efea27c6aaa35e88ffd579128c0c/lib/domains/tr/edu/boun.txt) and `bogazici.txt` [commit link](https://github.com/JetBrains/swot/commit/43822e6742f858fe04bfdc782ee08095c20bccbe). 
Check out the new [bogazici.edu.tr](https://bogazici.edu.tr) page, it is the same as [boun.edu.tr](https://boun.edu.tr) currently both are available and `boun.edu.tr` redirects to the new page.

Add New Bogazici University Domain

---

lib/domains/uk/ac/wsfc.txt

Official website URL: https://www.wsfc.ac.uk/
Proof of Computer Science A Level on website: https://www.wsfc.ac.uk/courses/a-levels/computer-science-a-level/

Add Worcester Sixth Form college

---

lib/domains/mz/ac/up.txt

This PR submits 1 mozambican university to the list of educational institutions:
Universidade Pedagógica de Maputo - [up.ac.mz](https://up.ac.mz/)

Add Maputo Pedagogical University to the list - Mozambique

---

lib/domains/uk/ac/ual.txt

Add ual.ac.uk as an approved domain. This is the email domain of University of arts London.
They offer a range of computing related courses as part of their creative computing institute, including BSc Computer Science: https://www.arts.ac.uk/subjects/creative-computing/undergraduate/bsc-hons-computer-science
The universities website can be found here: https://www.arts.ac.uk/

Add ual.ac.uk domain

---

lib/domains/com/stephenperse.txt

Adding Stephen Perse Foundation, based in Cambridge, UK, to the list of schools.

Added Stephen Perse Foundation file

---

lib/domains/uk/sch/southwark/kingsdale.txt
lib/domains/uk/sch/southwark/students.txt

This school is a High School, but it offers a Sixth Form program. 
The real domain for the email is @students.kingsdale.southwark.sch.uk but I had trouble trying to add that.
School Website:
https://kingsdalefoundationschool.org.uk/
Sixth Form Program Info:
https://s3-eu-west-1.amazonaws.com/sh22-kingsdalefoundationschool-org-uk/media/downloads/kfssixthformstudyprogrammescoursesforseptember2024year12entry.pdf

Adding Kingsdale Foundation School

---

lib/domains/it/unipegaso/studenti.txt

https://www.unipegaso.it/
URL of a page that has a long-term IT course:
https://www.unipegaso.it/lauree-triennali/informatica-per-le-aziende-digitali
URL of a screenshot that shows an email which states that Università Telematica Pegaso granted me an email with this domain to use as an institutional email https://gyazo.com/a74a61e09292ff4a4dd3df499efdab44

Add Pegaso University

---

lib/domains/com/bishanoi.txt
lib/domains/com/bisvietnam.txt
lib/domains/com/bvishanoi.txt
lib/domains/com/bvisvietnam.txt
lib/domains/net/bishanoi.txt
lib/domains/net/bisvietnam.txt
lib/domains/net/bvishanoi.txt
lib/domains/net/bvisvietnam.txt

British International School, Hanoi
School Official Website : https://www.nordangliaeducation.com/bis-hanoi
Address : Hoa Lan Road, Vinhomes Riverside, Long Bien District, Hanoi, Vietnam
Student email : @bishanoi.net or @bishanoi.com
British International School, Ho Chi Minh City
School Official Website : https://www.nordangliaeducation.com/bis-hcmc
Address : 246 Nguyen Van Huong Street, Thao Dien Ward, Thu Duc City, Ho Chi Minh City, Vietnam
Student email : @bisvietnam.com or @bisvietnam.net
British Vietnamese International School, Hanoi
School Official Website : https://www.nordangliaeducation.com/bvis-hanoi
Address : 72A Nguyen Trai Street, Thanh Xuan District, Hanoi, Vietnam
Student email : @bvishanoi.com or @bvishanoi.net
British Vietnamese International School, Ho Chi Minh City …

Add NAE Schools in Vietnam

---

lib/domains/ng/edu/fcepkn.txt

Second, with the new email for this institution, a new address is necessary due to changes in government policy and, hence, service providers.

Add FCEP to swot Institution List

---

lib/domains/de/hnbk.txt

This is the domain for all staff of the Heinz-Nixdorf-Berufskolleg. The website is also on the same domain (https://hnbk.de/)

Add Domain for Staff Mail Addresses for Heinz-Nixdorf-Berufskolleg

---

lib/domains/com/aecarcavelos.txt

Carcavelos High School or "Escola Secundária de Carcavelos"(in Portuguese) is a high school located in Carcavelos, Lisbon. It has around 2000 students and has 3 types of courses related to science, one being science and technologies(equivalent to computer science in english).

Carcavelos High School

---

lib/domains/org/ddecnc.txt

Addition of the email address of the Blaise Pascal private high school (ddec).

add ddecnc.org mail adress

---

lib/domains/org/mytusd.txt

Foothill High in Santa Ana offers AP CSA and AP CSP classes to its students where JetBrains products would be helpful.

Add Foothill High School

---

lib/domains/net/bbs2leer.txt

Website is https://bbs2leer.de although https://bbs2leer.net also works. 
Example of a school email: exampl2023@bbs2leer.net

Add BBS2Leer domain

---

lib/domains/sg/edu/nexus.txt

Nexus International School (Singapore)
https://www.nexus.edu.sg/
https://www.nexus.edu.sg/secondary/
- Scroll down and click "IGCSE" and "IB Diploma Programme"
- Key word: "Computer Science"
School email domain:
[First name].[Last name].[Graduation year]@nexus.edu.sg

Free licenses to students from Nexus Singapore

---

lib/domains/ng/edu/cuab.txt

domain: cuab.edu.ng
https://cuab.edu.ng/college-of-information-and-communication-technology/

Add Crescent University, Abeokuta

---

lib/domains/com/hudsonhs.txt

Hudson High School of Learning Technologies in NYC 
[hudsonhs.com](https://hudsonhs.com/)

adding hudson high school of learning technologies

---

lib/domains/id/ac/ars.txt

[Ars University](https://ars.ac.id) is a private campus located in Bandung, West Java, Indonesia. Students here learn programming from C++, Java and WEB using extremely old and no longer unsupported IDE & Code Editor. I want to take this opportunity to add this campus to Jetbrains supported domain so our lecturers and students will able to start using latest and feature-rich IDE from Jetbrains to teach their students for better learning experience.
Regards,
Kelvin D Marlian
ARS University Students

Add ARS University to supported domain

---

lib/domains/ac/khu.txt
lib/domains/kr/ac/khu.txt

khu.ac.kr
Request a full request for use on Kyung Hee University's global campus.
The existing Kyung Hee University email is currently approved on swot and I don't know if that email domain is still used that was registered in the past, but the university is using khu.ac.kr domain.
So, I would like to request additional approval for that domain.

Include Kyunghee University global campus

---

lib/domains/academy/greta-cfa-aquitaine.txt

The GRETA-CFA Aquitaine is an educational institution based in the Aquitaine region of France. It operates as a Training Center for Apprenticeship (CFA) and is affiliated with the GRETA network, which focuses on providing vocational training and education. 
https://greta-cfa-aquitaine.fr/

Add GRETA-CFA Aquitaine

---

lib/domains/net/iesportocristo.txt

School Name: IES Porto Cristo
School Website: https://iesportocristo.net/
IT-Oriented Major: https://drive.google.com/file/d/1BjxhZ8_jOnc0m_opSW-4sIAiYHNXorTn/view

Added IES Porto Cristo

---

lib/domains/uk/sch/nottingham/emmanuel.txt

Adds the Nottingham Emmanuel School to SWOT
School website can be found here:
https://www.emmanuel.nottingham.sch.uk/
Curriculum here:
https://www.emmanuel.nottingham.sch.uk/learning/curriculum-overview/
Computer Science is an optional course available from Year 10

Add Nottingham Emmanuel School

---

lib/domains/uk/sch/flintshire/flint.txt
lib/domains/wales/flinthighschool.txt

School Website: https://www.flinthighschool.wales/
School Curriculum: https://www.flinthighschool.wales/curriculum/curriculum-overview
School emails addresses are administered the **local council** and have a different domain from the school website, email address domains are: @flint.flintshire.sch.uk.
**Local council** is: https://www.flintshire.gov.uk
School List for Flintshire: https://www.flintshire.gov.uk/en/PDFFiles/Lifelong-Learning/Schools/School-Admissions/Schools-List-2023-2024.pdf 
Flint High School Page 17:

Adding Flint High School flint.flintshire.sch.uk & flinthighschool.wales

---

lib/domains/ch/phsz.txt

Please add Schwyz University of Teacher Education 
https://www.phsz.ch/
Bachelor: https://www.phsz.ch/ausbildung/bachelorstudium/studiengaenge-und-studienformate
Master: https://www.phsz.ch/ausbildung/masterstudium
a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students:
https://www.phsz.ch/person/raffael-meier

Add PHSZ - Schwyz University of Teacher Education

---

lib/domains/br/edu/undf.txt

It's a public University from Brazil's capital, Brasília - Distrito Federal since 2022
example e-mail: teacher@undf.edu.br
related links
[Web site - teacher's room](https://undf.edu.br/)
[Official web site](https://universidade.df.gov.br/a-undf/)
[Wikipedia - UnDF](https://pt.wikipedia.org/wiki/Universidade_do_Distrito_Federal_Jorge_Amaury)
[Linkedin - UnDF](https://br.linkedin.com/company/undf-universidade-do-distrito-federal)
[Press coverage about UnDF](https://g1.globo.com/df/distrito-federal/df2/video/undf-autoriza-a-criacao-de-seis-novos-cursos-de-graduacao-11471095.ghtml)
[Interview with Simone Benck: Creation of the University of the Federal District (UnDF)](https://www.praxia.ueg.br/index.php/atatot/article/download/13083/9217)

Adding UnDF - Universidade do Distrito Federal

---

lib/domains/uk/org/clsg.txt

Please Merge to add City of London School for Girls , in London UK

Added clsg.org.uk for Students of City of London School for girls

---

lib/domains/net/flvs/flvsft912.txt

The existing domain for Florida Virtual School does not cover most students attending FLVS. The domain `flvsft912.flvs.net` however, covers all students in FLVS' highschool segment.

Update Florida Virtual School

---

lib/domains/ro/e-cdloga.txt

CD Loga Highschool is already included as "@cdloga.ro", but this is for the administrator and teachers emails.
Students emails received the @e-cdloga.ro domain, therefore we need to add this domain too, so that our students can access the students offers.
Highschool website: http://cdloga.ro
Highschool mathematics-informatics (4 years - highschool): http://cdloga.ro/specializarea-matematica-informatica/
Thank you!

Add CD Loga Highschool students email domain

---

lib/domains/pl/wroclaw/edu.txt

High School website
https://lo14.wroc.pl/
Here it is offering a computer science class for 4 years (last year recruitment page)
https://lo14.wroc.pl/rekrutacja-do-liceum-ogolnoksztalcacego-nr-xiv-na-rok-szkolny-20232024,123,pl
edu.wroclaw.pl is a domain shared by High Schools and Universities in Wroclaw
Here is the page where is says, that every educational institution managed by Gmina Wroclaw (local goverment) is allowed to use this platform (includes e-mailing service).
https://pe.edu.wroclaw.pl/kontakt
Since PyCharm is basically the only choice of a code Editor/IDE for the python language on the graduation exam, and is used for universities, student/educational license might help students.

edu.wroclaw.pl domain added

---

lib/domains/th/ac/sirin.txt

Please ass Sirindhorn School.
Official web site: https://sirin.ac.th/
Personnel of science and technology subjects: https://sirin.ac.th/science-department/
Our school currently uses Google's email service and many other services, so school staff's email addresses end in @sirin.ac.th which must be approved by our school's appointed email administrator only.

Please add Sirindhorn School (Thailand).

---

lib/domains/de/iserv-schillerschule.txt

- Official school homepage: https://www.schillerschule-hannover.de/
- Student E-Mails are registered on the `iserv-schillerschule.de` domain, a link to it is present on the right sidebar ("Iserv")
- Proof of long-term cs-courses: https://www.schillerschule-hannover.de/informatik/

Add Schillerschule Hannover

---

lib/domains/in/ac/licet.txt

Added Loyola-ICAM College of Engineering & Technology, Chennai, Tamil Nadu, India.
**Official Website**: https://licet.ac.in/
**Wikipedia**: [Link](https://en.wikipedia.org/wiki/Loyola-ICAM_College_of_Engineering_and_Technology)
**Map**: [Link](https://maps.app.goo.gl/bMjkjFYoS82b53eG8)

add loyola-icam (licet) - india

---

lib/domains/ph/edu/perpetual.txt

Microsoft domain for the University of Perpetual Help System DALTA, used by 3 campuses in the same school system (perpetual.edu.ph)
This email domain is strictly for student use (not accessible publicly), and is compliant of the requirements needed for school/university registration for JetBrains products.

Add University of Perpetual Help System DALTA

---

lib/domains/ie/lcetb/learner.txt

Added the official domain of Limerick college of further education (LCFE).
official domain: https://www.lcfe.ie/ & https://lcetb.ie/
apart of other FET colleges verified under the IE section

Add Limerick college of further education (LCFE)

---

lib/domains/eu/hsg-berlin.txt

School website: https://hsg-berlin.de/
The eu-domain is for student and teacher mails only (and the internal learn management system).
The school offers computer science courses for high school age students (~ 14-18 years old). Teaching content includes - for example - Kotlin, databases, data protection and social effects of IT.

Add Heinrich Schliemann Gymnasium

---

lib/domains/np/edu/nistbanepa.txt
lib/domains/np/edu/nistcollege.txt

Nist College,
Nayabasti Nala Road, Banepa 45210
There are two domains of this college, 
1.nistbanepa.edu.np
2.nistcollege.edu.np
both of them are workable, and I have updated both in this pull request. I hope this PR will be merged

Nist College

---

lib/domains/lv/jak.txt

Added domain file for the Jēkabpils Tehnoloģiju Tehnikums
Official websites URL: https://jekabpils.jttehnikums.lv/
URL For IT related course (Programming 4 years): https://jekabpils.jttehnikums.lv/lv/programmas/programmesana/
URL for @ jak domain confirmation (Teachers page with their email (including mine), that contains @ jak domain): https://jekabpils.jttehnikums.lv/lv/skola/skolotaji/

Domain file for Jēkabpils Tehnoloģiju Tehnikums

---

lib/domains/gr/uoc/physics/edu.txt

Official website: https://www.physics.uoc.gr/
Websites of courses related to IT:
- https://elearning.physics.uoc.gr/?lang=en
- https://www.physics.uoc.gr/en/courses/65
- https://www.physics.uoc.gr/en/courses/157
Webmail website: https://webmail.physics.uoc.gr/
The edu prefix is for students only

Add Physics subdomain for University of Crete

---

lib/domains/uz/tatunf.txt

**Nukus branch of Tashkent University of Information Technologies named after Muhammad al-Khwarizmi**
**Website:** https://tatunf.uz/
**Location:** https://maps.app.goo.gl/Ymh7T1VNA1719NVR8

Nukus branch of Tashkent University of Information Technologies 

---

lib/domains/it/edu/depretto.txt

IT High School in Schio (province of Vicenza), Italy
site: https://www.depretto.edu.it/
domain @depretto.edu.it

ITIS De Petto Schio

---

lib/domains/ca/sd33online.txt

Student Email of sd33.bc.ca 
Though in my attempts pinging sd33online.ca failed even though it is a registered domain and used by students.

Add School District 33 Student Email

---

lib/domains/br/gvmail.txt

Add gvmail.br as another Fundação Getúlio Vargas (www.fgv.br) mail domain.

Add Fundação Getúlio Vargas another mail domain

---

lib/domains/org/dci-student.txt

Official website: https://digitalcareerinstitute.org
Long term course: https://digitalcareerinstitute.org/courses/java-backend-programming/

Adding DCI

---

lib/domains/fr/lyceecoetlogon.txt

Official Website: https://lyceecoetlogon.fr/
Or rather: https://lycee-coetlogon.ac-rennes.fr/ since it redirects us
Student email : @lyceecoetlogon.fr

Lycee Coetlogon add

---

lib/domains/nl/maaslandcollege.txt

I've added the Maaslandcollege domain to be able to use the Educational License of the JetBrains IDE's.

Add Maaslandcollege Domain

---

lib/domains/de/ms/kant.txt

The immanuel Kant Gymnasium is a public school in 48165 Münster, Germany. The public school website is kant-hiltrup.de.

add Immanuel Kant Gymnasium Hiltrup (kant.ms.de)

---

lib/domains/fr/isae-supmeca.txt

ISAE-Supméca is a French engineering school (master's degree).
From [English version of engineering program](https://en.isae-supmeca.fr/training/training/):
> Structure of the core teachings:
> Scientific education covering: applied mathematics, IT, industrial automation and IT, mechanical and structural engineering, materials, fluids and energy engineering.
Support page of IT service from school intranet with mention of “first_name.name@isae-supmeca.fr”:
[isae-supmeca.fr_email-domain.pdf](https://github.com/JetBrains/swot/files/14343205/isae-supmeca.fr_email-domain.pdf)

Add domain isae-supmeca.fr.

---

lib/domains/com/sbe5d.txt

Domain for emails has changed for Shenley Brook End School, Milton Keynes, UK from .org.uk to .com one.
It doesn't appear to be possible to automatically verify emails with .com domain.
@philipto Can you review and approve, please?

Modified domain for Shenley Brook End School, Milton Keynes, UK

---

lib/domains/jp/ac/ibaraki/vc.txt

Our university changed the university member's personal email domain from '@ibaraki.ac.jp' to '@vc.ibaraki.ac.jp' 7 or 8 years back. However there has been no application to JetBrain on this matter.
Ibaraki University is a national educational institution recognized by the Japanese government, and it offers a full four-year undergraduate education, as well as a two-year master's program and a three-year doctoral program.
Ibaraki University is a comprehensive university with professors in the fields of literature, science, agriculture, and engineering, including research and development related to the computer field.
It is hoped that this request will be approved by the JetBrain reviewers.
Thank you.
PS:A screenshot of an email "related to an induction session hosted by the school" has …

Add a new Fourth-level domain of Ibaraki University

---

lib/domains/uk/org/egglescliffe.txt

Adding Egglecliffe School & Sixth Form College
https://egglescliffe.org.uk/
https://egglescliffe.org.uk/sixth-form/choosing-a-course/
Students are issued an email in format SurnameXYY@egglescliffe.org.uk Where X = a first name initial and XX are two numeric digits.  e.g. DoeJ99@egglescliffe.org.uk

feature: Added Egglescliffe School & Sixth Form to uk org domains

---

lib/domains/jp/nsgcl.txt

Optional Info:
Official Webpage : [https://www.ncc-net.ac.jp/](url)

Added NCC (Niigata Computer College)

---

lib/domains/de/bs1-landshut.txt

If the title is too long it can be shortened to "Add Staatl. BS1 Landshut/BFI" or "Add Staatl. Berufsschule 1 mit BFI"
The Vocational School for Informatics (Berufsfachschule für Informatik) is a sub-school located physically and administratively within the Public Vocational School 1 Landshut. Both offer a long-term IT-related course and use the same domain for students and teachers.
[IT course at the Public Vocational School 1 Landshut](https://bs1-landshut.de/abteilungen/informationstechnik/ueberblick)
[Vocational School for Informatics](https://bfi-landshut.de)
[Proof that the domain is in use as an official email domain](https://bs1-landshut.de/abteilungen/informationstechnik/team) (only contains teacher's email addresses, but students use the same upper-level domain, I just couldn't …

Add Staatliche Berufsschule 1 Landshut mit Berufsfachschule für Informatik

---

lib/domains/at/ac/gmi-tirol.txt

Medical University of Innsbruck (Austria), Institute of Legal Medicine
```bash
whois gmi-tirol.ac.at
domain:         gmi-tirol.ac.at
registrar:      
registrant:     MUI1323603-NICAT
admin-c:        <data not disclosed>
tech-c:         <data not disclosed>
tech-c:         <data not disclosed>
nserver:        ns1.i-med.ac.at
nserver:        ns2.i-med.ac.at
changed:        20140418 10:08:43
source:         AT-DOM
personname:     
organization:   Medizinische Universitaet Innsbruck
street address: Christoph-Probst-Platz 1
postal code:    A-6020
city:           Insbruck
country:        Austria
phone:          +435129003
e-mail:         it-services@i-med.ac.at
nic-hdl:        MUI1323603-NICAT
changed:        20140415 11:30:00
source:         AT-DOM
```

Medical University of Innsbruck (Austria), Institute of Legal Medicine

---

lib/domains/de/mpg/ip.txt

The Max Planck Institute for Innovation and Competition (ip.mpg.de) is a member of the Max Planck Society.
Website: https://www.ip.mpg.de/en/

add ip.mpg.de - Planck Institute for Innovation and Competition

---

lib/domains/id/sch/pahoa/sekolah.txt

Official site is https://pahoa.sch.id . A school in Indonesia that cater pre-school up to senior high school.

Add Sekolah Terpadu Pahoa

---

lib/domains/br/cesupa/prof.txt

University official website UR: https://www.cesupa.br/
URL of the science computer course: https://www.cesupa.br/Graduacao/Ciencia_Computacao/
proof of domain: https://drive.google.com/file/d/1ZGbeaM_NVVdSWmvyJVTDDvTBiPPYkA2W/view?usp=sharing

Adding the prof.cesupa.br domain

---

lib/domains/es/implika.txt

Implika is a Professional Institute in Spain (https://www.implika.es).

Add "implika.es" as a domain.

---

lib/domains/net/jcsds.txt

added my school
The link for the school email is www.jcsds.net but the actual school website is www.jchigh.org

Added JCHS to lib/domains/net

---

lib/domains/tw/edu/kh/kshs/student.txt

School site:
https://www.kshs.kh.edu.tw/
School email:
example@student.kshs.kh.edu.tw
School address:
No. 50, Jianguo 3rd Rd., Sanmin Dist., Kaohsiung City 807302 , Taiwan (R.O.C.)

Add Kaohsiung Senior High School

---

lib/domains/ph/edu/donbosco.txt

Official website http://one-bosco.org/ members https://donboscocanlubang.edu.ph/ https://donboscomakati.edu.ph/ https://www.dbtarlac.edu.ph/ http://dbst.edu.ph/
Don Bosco College - Canlubang offers BS Information Technology which is similar/related to BS Computer Science in the Philippines
https://donboscocanlubang.edu.ph/college-admission/
This shows the email with domain donbosco.edu.ph (aside from the domain is shown in the main website http://one-bosco.org)
http://dbst.edu.ph/contact-us/

Add Don Bosco Educational Centers (DBEC) - PHL

---

lib/domains/org/gimvic.txt
lib/domains/si/gimvic.txt

Gimnazija vič. Slovenija.
Gimnazija in Ljubljana Slovenija.
official website: [GIMVIC](https://www.gimvic.org/)

Gimnazija vič

---

lib/domains/id/sch/smkpgringadirojo-pct.txt

Hi JetBrains
Please add my school into swot 
SMK PGRI Ngadirojo is Located at Pacitan, Indonesia
Here is a Screenshoot of Web and Maps of SMK PGRI Ngadirojo
Here is a Proof of cPanel Access into SMK PGRI Ngadirojo
Thank you so much for your attention 😃

Add SMK PGRI Ngadirojo

---

lib/domains/cn/edu/yzu/365.txt
lib/domains/cn/edu/yzu/stu.txt

[Yangzhou University](https://www.yzu.edu.cn) has 3 available email domains infact:
- *@yzu.edu.cn for faculties
- *@stu.yzu.edu.cn for students
- *@365.yzu.edu.cn is special, the mailbox will automatically allocate to users when creating a Microsoft 365 account. Unlike *@yzu.edu.cn and *@stu.yzu.edu.cn, it is operated by Microsoft Outlook 21vianet.

Add 3rd-level domain name for Yangzhou University

---

lib/domains/com/mybpp.txt

Add a new university named as BPP University in the list of universities. It is situated in London, UK

adding request for bpp

---

lib/domains/kr/cneo365/hongseong.txt

School website: http://hongseong.cnehs.kr
School address: 49 Honghak-ro, Hongbuk-eup, Hongseong-gun, Chungcheongnam-do, Republic of Korea

add hongseong high school

---

lib/domains/org/cifpperedesongall.txt

adding college to apply for license "Centre integrat Formació Profesional Pere de Son Gall"
https://cifpperedesongall.org
Higher degree of development applications
domain teachers: @cifpperedesongall.org
domain students: @a.cifpperedesongall.org

CIFP Pere de Son Gall

---

lib/domains/uk/sch/herts/queens.txt

Add Queens' School, Bushey which is based in Bushey, Hertfordshire
https://www.queens.herts.sch.uk/

Queens' School, Bushey, UK

---

lib/domains/de/rub/edu.txt
lib/domains/de/ruhr-uni-bochum/edu.txt

Changes to the mail (https://www.it-services.ruhr-uni-bochum.de/ias/mailkonzept.html). Students may have @edu.rub/ruhr-uni-bochum.de aswell as old students that still have the @rub/ruhr-uni-bochum.de Mail. Changes are needed, because alumnis also have their own suffix.

Mail-Concept

---

lib/domains/nl/gomaruscollege.txt

Adds Gomarus College, a High School in Groningen, Netherlands offering a computer science course [[source](https://163.wpcdnnode.com/gomaruscollege.nl/wp-content/uploads/2023/09/pta-6gym-vp1-23-24-1-10-23-1.pdf) linked at [Examen & PTA](https://gomaruscollege.nl/praktische-informatie/leerlingen/examen-en-pta/)].
Students are assigned an email with a 6-digit number and the requested domain, eg. 123456@gomaruscollege.nl

Add Gomarus College

---

lib/domains/ma/eigsica.txt

I added the domain of the École d'ingénieurs en génie des systèmes industriels de Casablanca (Engineering school in Industrial Systems Engineering of Casablanca). The school offers a 5 year formation for obtaining a general engineering degree recognized both by the french and moroccan states. The formation contains many courses including IT

add the EIGSI Casablanca

---

lib/domains/net/kkos.txt

KKG is a maths and CS focused school in Berlin, Germany.
We offer advanced CS courses (2 years) from 11th to 12th grade. Students can also enroll into "Frühstudium", an early offer to start CS courses from university early before graduation.
https://www.kaethe-kollwitz-gymnasium.de/fachbereiche/mint/informatik/
kkos.net is used for mails only. The abbreviation stems from "Käthe-Kollwitz-Oberschule", the former name of the school.

Add KKOS Berlin to list of schools

---

lib/domains/uk/ac/heartofyorkshire.txt

https://www.wakefield.ac.uk/
Long term IT course evidence:
https://courses.wakefield.ac.uk/PSWebEnrolment/webenrolment.aspx?page=~/webcontrols/coursedisplay.ascx&CourseInformationID=5222
Recognized email domain evidence:
https://moodle.wakefield.ac.uk/

Add Heart of Yorkshire Education Group

---

lib/domains/net/mail-formateur.txt

Add of EPSI France computer sciences school (www.epsi.fr) with emails domain mail-formateur.net belonging to group Competences et Developpement, IFAG Paris. 
the university official website URL, if it is different from the domain you are submitting : www.epsi.fr
a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university : https://www.epsi.fr/programmes/ingenierie-informatique/
a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students. 
[Pull Request to add EPSI mail-formateur.net domain.pdf](https://github.com/JetBrains/swot/files/15313666/Pull.Request.to.add.EPSI.mail-formateur.net.domain.pdf)

Fork for EPSI computer sciences school

---

lib/domains/org/set/westleigh.txt

Another commit to add The Westleigh School (part of Shaw Education Trust). Was detected as fraud last time but thought I would try again.

Add The Westleigh School

---

lib/domains/br/com/eterj.txt

- [Official website URL](https://eterj.com.br/)
- [URL of the long-term IT-related course offered](https://www.eterj.com.br/nossos-cursos/informatica)
- Screenshot of the recognition of the domain as the official domain:

Add Technical School of Rio de Janeiro

---

lib/domains/th/ac/triamudom/student.txt

Added Triamudom Suksa School per request from school director and student 
Website : traimudom.ac.th
Location : 227 Phaya Thai Rd., Pathum wan, Pathum Wan, Bangkok, 10300

Added Triamudom Suksa School

---

lib/domains/org/hccts/student.txt

Add Highlands Community Charter and Technical Schools – Sacramento to domain list

Add Highlands Community Charter and Technical Schools

---

lib/domains/au/edu/cit.txt

Canberra Institute of Technology uses cit.edu.au for teaching staff and students.cit.edu.au for students.
students.cit.edu.au appears to already be in the list of approved domains.

Canberra Institute of Technology

---

lib/domains/nz/ac/kiwi.txt

**Kiwi College of New Zealand**
**https://kiwi.ac.nz/**

Add kiwi.txt for Kiwi College of New Zealand

---

lib/domains/net/ferrarispancaldo.txt

Add IIS Ferraris - Pancaldo (ferrarispancaldo.net) to domains
Official website is, however, https://ferrarispancaldo.edu.it/ as our Ministry of Education recently refreshed the domains for all schools

Add IIS Ferraris - Pancaldo (ferrarispancaldo.net)

---

lib/domains/de/iserv-schiller-schule.txt

- gymnasium official website: https://www.schiller-bochum.de/
- URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: https://www.schiller-bochum.de/joomla/index.php/lernen/unterrichtsfaecher?view=article&id=17:informatik&catid=15:faecher
- a URL of a page or some other proof showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students: https://www.schiller-bochum.de/joomla/images/Lernen/Downloads/Medienkonzept.pdf (please refer to page 10)

Add Gymnasium Schiller-Schule Bochum

---

lib/domains/de/berufskolleg-technik.txt

- [Official website](https://berufskolleg-technik.de/)
- [Long-term IT related course](https://berufskolleg-technik.de/berufsschule/) (This is a German vocational school. Here the three-year apprenticeship "Fachinformatiker"/IT specialist is taught.)
- The main domain berufskolleg-technik.de now also gets used for student email accounts.

new student domain for berufskolleg technik

---

lib/domains/in/net/uktech.txt

Please add Veer Madho Singh Bhandari Uttarakhand Technical University (UTU) with the domain 'uktech.net.in' to the list of domains. 
The official website is https://uktech.ac.in/en.

Add Uttarakhand Technical University

---

lib/domains/edu/missioncollege.txt
lib/domains/edu/westvalley.txt
lib/domains/edu/wvm.txt

Adding domains for West Valley - Mission Community College District, which is a California Community College district for West Valley College and Mission College.
Student emails for _both_ campuses are always at the subdomain `mywvm.wvm.edu`, and teaching staff may have emails at the parent domain `wvm.edu` as well as the two campus domains `westvalley.edu` and `missioncollege.edu`
Links:
[WVM District Home Page](https://www.wvm.edu/Pages/default.aspx)
[West Valley College Home Page](https://www.westvalley.edu/)
[Mission College Home Page](https://missioncollege.edu/)
[West Valley Comp. Sci. Program (Certificate Only)](https://www.westvalley.edu/catalog/departments/computer-science.html)
[Mission Comp. Sci. Program (Certificate and …

Add West Valley - Mission Community College District

---

lib/domains/pl/edu/eans-nt.txt
lib/domains/pl/edu/eppuz.txt

The university has changed its name from Podhalańska Państwowa Uczelnia Zawodowa to the Akademia Nauk Stosowanych w Nowym Targu. Therefore, the web and email domains have been changed. (old www domail: https://ppuz.edu.pl, old email domain eppuz.edu.pl)
* the university official website URL: https://ans-nt.edu.pl/
* a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: https://ans-nt.edu.pl/kandydat/studia-i-stopnia/informatyka-ekonomiczna/
*a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students: https://ans-nt.edu.pl/student/ksztalcenie-zdalne/
(google classroom section)

Update university email domain eppuz.edu.pl to eans-nt.edu.pl

---

lib/domains/th/ac/rmutt/mail.txt

The RMUTT has 2 email domains for their students
- `*@rmutt.ac.th` this is for teacher and the students in master degree or above
- `*@mail.rmutt.ac.th` this is for Bachelor students
The present commit has only domain for the master degree student, so I'm going to add a Bachelor student's domain by simply added the `/lib/domains/th/ac/rmutt/mail.txt`

Add *@mail.rmutt.ac.th

---

lib/domains/org/mountvernonschool.txt

School name: The Mount Vernon School
Email Domain: mountvernonschool.org
Website: www.mountvernonschool.org
Address: 510 Mount Vernon Hwy, Atlanta, GA 30328
Course: https://docs.google.com/document/d/16ROP2MeUeh6sHZwk_SdJWKKeEwfgMqBabMkBieRrfYw/edit#heading=h.3yyw2j45qj64

added the mount vernon school

---

lib/domains/md/itstep/student.txt

Adding the `itstep.md` domain for STEP IT Academy.
Official website  - https://itstep.md
Software Course 2 years with study plan: https://itstep.md/software-development 
Proof of official email domain - so for like global organization Step It Academy uses .org domain in Moldova is infomd@itstep.org how you see from contact page https://itstep.md/contacts_14
But for students from Moldova, they create emails like this Ceba_yp56@student.itstep.md   with the md domain.
if you need more proofs the mail domain is valid please reach to me at  Ceba_yp56@student.itstep.md

Added Step IT Academy domain

---

lib/domains/de/kmg-fn.txt
lib/domains/de/kmgfn.txt

Added the Karl-Maybach-Gymnasium Friedrichshafen.
Teachers use the kmg-fn.de domain
Pupils use the kmgfn.de domain
Both domains are linked to each other. When being on kmg-fn.de you can click on IServ on the header. Then you land on a subdomain of kmgfn.de When clicking the "impressum" on the bottom of this login-screen, you're back on kmg-fn.de
Thanks!

added Karl-Maybach-Gymnasium Friedrichshafen

---

lib/domains/uk/sch/herts/highfield.txt

The Highfield School and Sixth Form
highfield.herts.sch.uk
GCSE Computer Science course and A-Level Computer Science
https://www.highfield.herts.sch.uk/84/sixth-form-courses
The Google Classroom user guide on this page has proof of the domain being used for students.
highfield.herts.sch.uk/53/digital-learning

Added Highfield School and 6th form to domains

---

lib/domains/nz/school/st-peters.txt

St Peter's College is in Auckland, New Zealand.

Add St Peter's College into this list.

---

lib/domains/ua/dp/kneu.txt
lib/domains/ua/edu/duet.txt

Add "State university of economics and technology" from Kryvyi Rih
Dnipropetrovs'ka oblast.
Site: https://www.duet.edu.ua/en
Mail domain: kneu.dp.ua and duet.edu.ua

Add State university of economics and technology

---

lib/domains/edu/deanza.txt

De Anza College is part of the Foothill-De Anza Community College District. The district domain is [already approved (fhda.edu)](https://github.com/JetBrains/swot/blob/master/lib/domains/edu/fhda.txt)
University URL: https://www.deanza.edu
URL showing list of 2-year college degree programs and certificates: https://www.deanza.edu/academics/degrees-and-certificates.html
URL with instructions on requesting a student email address: https://deanza.edu/students/email.html

Add deanza.edu email domain, student emails are @student.deanza.edu

---

lib/domains/az/edu/wcu.txt

Add Western Caspian University
- Website: https://wcu.edu.az/en
- Example for a long-term (>1 year) IT related course: https://wcu.edu.az/en/faculties/computer-engineering
**Note:** 
This is a new domain for https://github.com/JetBrains/swot/blob/master/lib/domains/az/edu/wu.txt, which is already listed in this repository. The university renamed itself as "Western Caspian University" in 2017. You can verify this by visiting https://wu.edu.az, it will redirect you to the new domain https://wcu.edu.az.
Not deleting the old domain because it is still owned and used by the university.

Add Western Caspian University

---

lib/domains/edu/southalabama/jagmail.txt

Also present under old domain at lib\domains\edu\usouthal.txt
University of South Alabama
School page:
https://www.southalabama.edu/
Computer Science Page:
https://www.southalabama.edu/colleges/soc/
Confirmation of usage of *@jagmail.southalabama.edu
https://www.southalabama.edu/services/jagnet/about.html

New email domain for University of South Alabama

---

lib/domains/de/tu-dortmund.txt
lib/domains/edu/udo.txt

Hey there, 
in this PR I'm adding another domain of the Technische Universität Dortmund (from Germany, Dortmund): `udo.edo`.
Also, I'm changing the spelling in the file `de/tu-dortmund.txt` to the official spelling, as written on https://www.tu-dortmund.de/en/.
Here are some background information and links:
- _Technische Universität Dortmund_ is the official German name
- _TU Dortmund_ is an commonly used abbreviation of the German name (as in the domain name)
- _TU Dortmund University_ is the translated English name used on the English site
- Information about the mailing system and the domains can be found in the [FAQ](https://service.tu-dortmund.de/en/faq) (search for _edu_). 
- Website in German: https://www.tu-dortmund.de/
- Website in English: https://www.tu-dortmund.de/en/
- …

Add `udo.edo` of TU Dortmund University (Technische Universität Dortmund)

---

file/lib/domains/org/mathfineco.txt
lib/domains/org/mathfineco.txt

Institut MathFinEco
mathfineco.edu
mathfineco.edu@gmail.com 
info@mathfineco.org
Ajout de l'Institut MathFinEco pour permettre aux étudiants d'obtenir des licences éducatives pour les produits JetBrains.

Ajout de l'Institut MathFinEco

---

lib/domains/uk/sch/Kent/folkestonegirls.txt
lib/domains/uk/sch/kent/folkestonegirls.txt

Folkestone School for Girls
Offering Computer Science at GCSE and ALevel : https://www.folkestonegirls.kent.sch.uk/what-we-do-and-why-we-do-it/curriculum/computing/

Add folkestonegirls 

---

lib/domains/nz/school/mytekura.txt

Adding "Te Aho O Te Kura Pounamu", the New Zealand Correspondence School.
Email Domain: mytekura.school.nz
Main Site: www.tekura.school.nz
This is the domain that we have for student email addresses however the main website is www.tekura.school.nz. Not really sure why they do it this way but they do 🤷‍♂️

Add Te Aho O Te Kura Pounamu

---

lib/domains/kr/ac/yju/g.txt

URL : https://www.yju.ac.kr/kr/index.do
IT-related courses URL : https://computer.yju.ac.kr/index.php?mid=page_VrJT47
A URL that is recognized by the university as an official email domain : https://itcenter.yju.ac.kr/xe_board_notice/6834
The URL recognized by the university as the official email domain says: “As a student of the university, you can use MS Office 365 and Windows 10 for free with your issued Gmail account (id@g.yju.ac.kr).” This page also provides instructions on how to sign up for university email and how to install MS Office 365 and Windows 11.

add: YEUNGJIN UNIVERSITY

---

lib/domains/kr/ac/halla/hu.txt

A year ago, I received student authorization in the following email format.
@hu.halla.co.kr
When I tried to renew the education pack this time, there was no information about the university I attended.
[Halla University homepage](https://www.halla.ac.kr/mbs/kr/index.jsp)
[Pages of Computer Science, Halla University](https://computer.halla.ac.kr/main/main.php)
[Computer Science Curriculum Guide Page](https://computer.halla.ac.kr/edu/02.php)

Add university email domain for Halla University

---

lib/domains/pk/edu/ceme/mts.txt

This domain is used for student email in the Department of Mechatronics Engineering, CEME, NUST, Pakistan
The official website is: https://ceme.nust.edu.pk/

Adding domain for CEME, NUST, Pakistan

---

lib/domains/edu/umss/est.txt

Add domain est.umss.edu for Universidad Mayor de San Simón.
- Official university URL: http://www.umss.edu.bo
- IT-related course URL: https://posgrado.fcyt.umss.edu.bo/dicscv2
- Proof of domain:
Thank you for considering this request!

Add domain est.umss.edu for Universidad Mayor de San Simón

---

lib/domains/edu/santarosa/bearcubs.txt

[School Website](https://www.santarosa.edu/)
[Domain Proof](https://welcome.santarosa.edu/bearcubs-email) Video at 1:28. Finding an official source for the bearcubs.santarosa.edu domain is difficult. This is the best I could find. But I am a student and can confirm that this is the domain for student emails. 
[Course Catalog](https://catalog.santarosa.edu/)

Add Santa Rosa Junior College

---

lib/domains/edu/nwscc/webmail.txt

This PR adds the domain `nwscc.edu` for Northwest-Shoals Community College.
- **Institution Name**: Northwest-Shoals Community College
- **Website**: [https://www.nwscc.edu](https://www.nwscc.edu)
- **Email Domain**: `nwscc.edu`
Thank you for considering this addition!

### Add Northwest-Shoals Community College

---

lib/domains/edu/af/afacademy.txt

https://www.usafa.edu/ now hosts emails as @afacademy.af.edu

Add USAFA as afacademy.txt

---

lib/domains/kr/ac/cku.txt

1. Official website URL : https://www.cku.ac.kr/sites/cku/index.do
2. IT related course( >1 year) : https://www.cku.ac.kr/software/806/subview.do
3. proof that the university recognizes the submitted domain as official student email. : https://www.cku.ac.kr/cku/515/subview.do (E-mail 주소 : ID@cku.ac.kr)

Add Catholic Kwandong University

---

lib/domains/edu/sdccd/student.txt

Added student.sdccd.edu subdomain for San Diego Community College District students

Added student.sdccd.edu subdomain

---

lib/domains/edu/uhv.txt

The University of Houston–Victoria (UHV) is a public university in Victoria, Texas. It is part of the University of Houston System. Its campus spans 20 acres (8.1 ha) in Victoria with a satellite location in Katy, Texas. Founded in 1971, UHV has an enrollment of over 4,300 students.
* School official Web site: https://www.uhv.edu
* School street address: \
University of Houston-Victoria
3007 N. Ben Wilson St.
Victoria, TX 77901
(361) 570-4848
* URL of an IT-related long-term course:
* BS Computer Science: https://www.uhv.edu/natural-applied-science/undergraduate-degrees/computer-science/
* MS Computer Science: https://www.uhv.edu/natural-applied-science/graduate-degrees/computer-science/

Submit University of Houston - Victoria

---

lib/domains/edu/uni-pr.txt

Added University of Prishtina domain. A university from Kosovo, which was established in 1969.

Add University of Prishtina file

---

lib/domains/edu/mass/necc.txt
lib/domains/edu/necc/student.txt

- Two domains to be added (faculty: necc.mass.edu, student: student.necc.edu)
- college domain - https://www.necc.mass.edu/
- Faculty domain is the same as the college main domain
- 2-year degree program - https://www.necc.mass.edu/academics/credit-programs/computer-information-science/computer-science-associate-degree/ 
- student email domain format is described in second paragraph in bold - https://www.necc.mass.edu/student-life/support-services/technology-help/student-email/office-365-help-login/

Add Northern Essex Community College

---

lib/domains/th/ac/act/teacher.txt

The same domain.
https://www.act.ac.th/m1-3_II.php
https://www.act.ac.th/m4-6_Digital-Sci.php
Used by teacher although no proof is anywhere to be found. Mentions of the (sub)domain is found around the school.

Added `*@teacher.act.ac.th`

---

lib/domains/uk/ac/don.txt

Education provider website: https://don.ac.uk
Course example: https://don.ac.uk/courses/dfc00466-ict-systems-and-principles-for-it-professionals-cg-diploma-level-3/

Doncaster College

---

lib/domains/edu/middlesex.txt

Add Middlesex Community College, please.
Our email domain has changed from middlesex.mass.edu to middlesex.edu. Our college website is still https://middlesex.mass.edu/

Add Middlesex Community College, please. See long description.

---

lib/domains/de/zsl-rss.txt

zsl-rss.de is a mail-only domain for a subdivision of www.zsl-bw.de

Add Domain zsl-rss.de

---

lib/domains/edu/hopkins.txt
lib/domains/edu/hopkins/students.txt

Hopkins School uses [faculty-identifier]@hopkins.edu for teachers and [student-identifier]@students.hopkins.edu for students. Both are added in this commit. 
[Here is our Computer Science curriculum offerings.](https://www.hopkins.edu/curriculum-detail?fromId=221609&LevelNum=181&DepartmentId=2730) You will also see on that page two example emails of teachers using the proper domain. We do not show any student emails publicly.

Add Hopkins School domain for faculty and students

---

lib/domains/edu/pict.txt

college name: PUNE INSTITUTE OF COMPUTER TECHNOLOGY
college website: https://pict.edu/
Computer Engineering Course at college: https://pict.edu/CE-dept/
Offers 4-year BE course and 2-year ME course
proof of domain, contact mail of HOD of dept ends in @pict.edu, enclosed in black rectangle, under contact information:

Adding domain for PICT, Pune

---

lib/domains/uk/org/abbeyparkschool.txt

Edit: The website is [abbeyparkschool.org.uk](https://abbeyparkschool.org.uk), but for some reason the www redirect doesn't support https, so your browser may complain if you go to @ and not www, for that reason I'd say go to [www.yadada.org.uk](https://www.abbeyparkschool.org.uk)
Edit 2:
Look in the bottom left corner of the screen when hovered over the email us button. The domain is admin@abbeyparkschool.org.uk
https://github.com/user-attachments/assets/ca75490f-4cf7-4d62-8a28-a26de8ce2519
Edit 3:
The email is also found in the footer.
Edit 4: fix link lol

Add Abbey Park School to /lib/domains/uk/org/abbeyparkschool.txt

---

lib/domains/br/edu/unifeso.txt
lib/domains/vc/com/unifeso.txt

Official site of Unifeso University
https://www.unifeso.edu.br/
Computer Sciente course page on Unifeso's site
https://www.unifeso.edu.br/cursos/graduacao/ciencia-da-computacao
Students panel: 
Please, note (marked in the image below) that the email address provided from the university to their students has the 'unifeso.com.vc' suffix. Therefore, consider that both domains belongs to Unifeso University.
https://portalint.unifeso.edu.br/FrameHTML/web/app/edu/PortalEducacional/login/

Please Add Unifeso

---

lib/domains/pr/sanignacio.txt

The school to be added is "Colegio San Ignacio de Loyola", which is located in San Juan, Puerto Rico (U.S. territory). domain name for the official email addreses: @sanignacio.pr

Adding file for new High School entry

---

lib/domains/com/stowevalley.txt

`stowevalley.com` is the domain for teachers and students at the Stowe Valley Multi-Academy Trust (https://www.stowevalleymat.com/)
This is a collection of primary and secondary schools in the UK.
Southam College is one member of this trust that offers a Computer Science A-Level: https://www.southamcollege.com/sixth-form (see [course description](https://resources.finalsite.net/images/v1697724237/southamcollegecom/zjvo7ugxuvnwbvhf8od0/CourseDescriptionComputerScience.pdf))
Proof that Southam College is a member of the Stowe Valley MAT is in the fat footer on the main page: https://www.southamcollege.com/ and also the footer on https://www.stowevalleymat.com/
The actual domain `stowevalley.com` is shown as a contact address here: https://www.stowevalleymat.com/about (for the trust) and …

Add Stowe Valley Multi Academy Trust

---

lib/domains/de/theresianum-mainz.txt

Homepage: https://www.theresianum-mainz.de
Computer science on Homepage: https://www.theresianum-mainz.de/lernen/mint/informatik
Me (Martin Hühne) as head of the computer science faculty: https://www.theresianum-mainz.de/kontakt/fachleitungen
Currently, we teach computer science in a 3-year-course (grades 10 to 12) as part of the highest general German school degree ("Abitur"). In two years, we will add a secondary education course in grade 7 continuing to grades 8 and 9 as well as an advanced/intensive course for grades 10 to 12 for students who want to specialize in computer science even more.

Gymnasium Theresianum Mainz added

---

lib/domains/net/ogsd.txt

I suggest adding Oak Grove School District using `ogsd.net` domain. This is the domain that educators and students use for their email addresses. This school district covers several schools in San Jose, California, USA. 
The district covers Herman Intermediate https://herman.ogsd.net/ and AdVENTURE option http://www.adventurestemprogram.com/ with STEM programs.
For details please see https://www.ogsd.net/

Add Oak Grove School District, CA, USA

---

lib/domains/nl/ictaa.txt
lib/domains/nl/ictaa/student.txt

Official name of the applied university: ICT Academie Apeldoorn.
We offer a four-year, accredited Bachelor of Science degree in Computer Science.
Official website URL: https://www.ictaa.nl/
Long-term (>1 year) IT related course is offered by the university: https://www.ictaa.nl/hbo-software-engineer
Domain which you are submitting as an official email domain for the enrolled student: https://www.ictaa.nl/3rdpartysoftware

new educational institution

---

lib/domains/edu/unwsp.txt
lib/domains/edu/unwsp/students.txt

I have added the University of Northwestern St. Paul to the list of approved domains. All student emails end with @students.unwsp.edu, and all professor emails end with @unwsp.edu.

Add University of Northwestern St. Paul

---

lib/domains/edu/mdc.txt

Fixed the name of the Miami Dade College institution.
Reason: The name of the Miami Dade College is not "_Miami Dads College_".
Such wrong name was added by the owner of this account: https://github.com/philipto, on August 2nd 2024. 
**Notes:**
1. The domain mdc.edu is used by all the Miami Dade College's employees (the MDC students use the domain mymdc.net).
2. The Miami Dade College is located at Miami, Miami-Dade County, Florida, USA.
3. The MDC Website is this one: https://www.mdc.edu/

fix_mdc_edu_domain_college_name

---

lib/domains/kr/hs/has.txt

Related to [this pr](https://github.com/JetBrains/swot/pull/13584), make a new pr for school's email subdomain.
This school use hana.hs.kr domain via Google Workspace, and use has.hs.kr domain via Microsoft 365. 
Currently this domain is not connected to school's official website, but the ownership of this domain can be found in WHOIS record. (Address and AC-Email's domain - hana.hs.kr)

Register Hana Academy Seoul's e-mail Subdomain

---

lib/domains/edu/hfcc/hawkmail.txt

Add domain hawkmail.hfcc.edu
Official URL: https://www.hfcc.edu/
All college IT programs: https://www.hfcc.edu/programs/computer-information-systems
Information Systems Program:  https://catalog.hfcc.edu/programs/computer-information-systems-aas
Technology page lists "Hawkmail", the official email for students (Gmail based) (subdomain of hfcc.edu).
https://www.hfcc.edu/student-services/technology

Add domain: hawkmail.hfcc.edu

---

lib/domains/se/hitachigymnasiet.txt

HitachiGymnasiet rebranded from ABB Industri Gymnasiet (Old URL: https://abbgymnasiet.se/)!
Proof:
Website: https://vasteras.hitachigymnasiet.se/
Contacts: https://vasteras.hitachigymnasiet.se/om-oss/personal
Educations: https://vasteras.hitachigymnasiet.se/teknikprogrammet

HitachiGymnasiet

---

lib/domains/ba/rs/ues/etf/student.txt

What this change does?
- Registers Faculty of Electrical Engineering in East Sarajevo (Bosnia and Herzegovina) as an educational institution recognized by JetBrains in order for it's students to be able to apply for Student licenses.
- Url to the Web Site of the University in East Sarajevo: https://www.ues.rs.ba/en/ues/ 
- Url to the Web Site of the Faculty of Electrical Engineering in East Sarajevo: https://www.etf.ues.rs.ba/eng/
- My student email is: dragana.divljan.1755@student.etf.ues.rs.ba

Registering Faculty of Electrical Engineering in East Sarajevo to the List of Registered Educational Institutions in JetBrains

---

lib/domains/edu/coloradomesa/mavs.txt

I instructor was able to get the license through his university email but because professors and students had different email names the students aren't able to get this benefit. So I am doing this pull request to hopefully fix this as the only difference is between @coloradomesa.edu and @mavs.coloradomesa.edu. 
Please email me at aaavila@mavs.coloradomesa.edu if this runs into any issues. Thank you!

adding Colorado Mesa University

---

lib/domains/edu/alamo/student.txt

The alamo.edu domain is already in use for faculty, but we are now adding student.alamo.edu for students.

Added alamo colleges student domain

---

lib/domains/kr/ac/kduniv.txt

Official website is https://www.kduniv.ac.kr/kor/Main.do
The email domain is v.kduniv.ac.kr

Add domain for Kyungdong University

---

lib/domains/edu/keiseruniversity/student.txt
src/lib/domains/edu/keiseruniversity/student.txt

Keiser University has its main subdomain for staff and faculty and also a subdomain "students.keiseruniversity.edu" for students.

Register Keiser University Student Subdomain to Jetbrains List

---

lib/domains/edu/pstu.txt

There is a link to the [university](https://pstu.edu/uk/). 
The university includes [Faculty of information technologies](https://pstu.edu/uk/fakultety-2/fakultet-informaczijnyh-tehnologij/), so there are obviously IT study programs. For example, [one of Computer Science programs for postgraduates](https://pstu.edu/uk/educational_program/informaczijni-systemy-ta-tehnologiyi/).
University-issued emails are with @pstu.edu and @students.pstu.edu. Students can use either the first option or the second one. To check, you can look at list of student's emails on the official website, [here](https://pstu.edu/uk/studentu/stud_e-mail/).

Add pstu.edu domain

---

lib/domains/in/ac/jyothyit.txt

The domain for Jyothy Institute of Technology is missing in the swot repo, and it has to be added for student verification.

Add Jyothy Institute of Technology Domain (jyothyit.ac.in)

---

lib/domains/info/ozenne.txt

I put my university in ```.info``` because our email is like ```[name]@ozenne.info```, even though our site is in ```.fr```.
Official university Website: https://eugene-montel.mon-ent-occitanie.fr/
Whois : https://who.is/whois/ozenne.info

Add Ozenne University

---

lib/domains/nz/school/icl.txt

Domain: icl.school.nz
Name: ICL Graduate Business School

ICL Graduate Business School

---

lib/domains/uk/sch/doncaster/hillhouse.txt

Hi there,
This pull request was recently denied due to the domain being 'hillhouse.uk', since then an email forward has been set up so that students can use the 'hillhouse.doncaster.sch.uk' domain for email too.
Website is: https://thehillhouseschool.com
Offers Comp. Science A Level, along with university preperation classes.
Thanks.

Added Hill House School

---

lib/domains/edu/frostburg.txt
lib/domains/edu/umd.txt

frostburg.edu must not have existed when this repo was created - seemed to have been piggy-backing off of its parent college's domain but has not for some time. All other University System of Maryland domains have been split off already.
Link: [https://www.frostburg.edu](url)
IT course link: [https://www.frostburg.edu/academics/majorminors/bachelor/bachelor-in-computer-science.php](url)
Unsure how to confirm email outside of use in faculty information: [https://www.frostburg.edu/academics/colleges-and-departments/computer-science/faculty--staff.php](url)

Frostburg domain ungrouped from UMD

---

lib/domains/edu/sctcc/my.txt

1.) College URL: [](https://sctcc.edu/open-house?utm_source=GA&utm_medium=max&utm_campaign=general&utm_id=openhouse&gad_source=1&gclid=Cj0KCQjw8--2BhCHARIsAF_w1gxZncqJVfXWF7pOGgWYsSRAK8MbWMaSinGfjCd2XkYWiSQI5BCG01kaAuHCEALw_wcB)
2.) IT Related courses: [](https://sctcc.edu/degrees-programs/computer-programming)
3.) Steps ![Page-005463](https://github.com/user-attachments/assets/582e0f03-8213-444c-b080-5bcd71cf9ef3):
* Scroll down the page from the above, look for 'COMPUTER PROGRAMMING INSTRUCTOR' (or Ctrl + F to search)
* Joseph Silman instructor
* Professor has his email address as JSilman@sctcc.edu
* It's not set as @my.sctcc.edu because as a student we have the `my.` included whereas instructors do not

Saint Cloud Technical Community College (my.sctcc.edu) Addition Request

---

lib/domains/uk/ac/stockport.txt

For some reason it looks like stockport college has several domains used for emails.
you can validate this yourself by going on the github student page and putting the shool as Stockport College as it list all the formats.

Add stockport college other domain

---

lib/domains/kr/ac/svu.txt

HOMEPAGE : [https://www.svu.ac.kr/ ](https://www.svu.ac.kr/)
University name : SEOUL VENTURE UNIVERSITY
ADDRESS : 405, Bongeunsa-ro, Gangnam-gu, Seoul, Republic of Korea (06097)

add university domain svu.ac.kr

---

lib/domains/edu/mesacc.txt

https:/www.mesacc.edu/programs/computer-science - CS degree program
Mesa Community College, 1833 W Southern Ave., Mesa, AZ 85202 
A comprehensive 2-year College with several 4-year BAS degrees, including one in Data Analytics and Programming: https://www.mesacc.edu/programs/map/data-analytics-and-programming-bas

Adding Mesa Community College: www.mesacc.edu - main website

---

lib/domains/edu/uj.txt

This request is to add `edu/uj.txt` to `domains`. The school is the University of Jamestown, which is located in Jamestown, North Dakota. Students will initially use WebStorm for this course: https://uj.smartcatalogiq.com/en/2024-2025/2024-2025-undergraduate-catalog/courses/tech-technology/400/tech-441/. The uj.edu domain is used by the university for all student email accounts. Thanks!

Adding University of Jamestown (uj.edu)

---

lib/domains/ca/qc/gouv/cssdn.txt

Part of CSSDN (Centre de Service Scolaire des Navigateurs)
English: School Services Center of Navigateurs

Centre d'Education aux Adultes des Navigateurs

---

lib/domains/edu/laverne.txt

Added domain for University of La Verne.
- **Official website**: [https://laverne.edu/](https://laverne.edu/)
- **IT-related course**: [https://artsci.laverne.edu/compsci/](https://artsci.laverne.edu/compsci/)
- **Proof of domain usage**: The president’s page shows the official email domain: [https://laverne.edu/president/](https://laverne.edu/president/)

Add University of Laverne

---

lib/domains/in/ac/gla.txt

Added domain (gla.ac.in) of GLA University.

Added GLA University Domain

---

lib/domains/net/hillsidek12.txt
lib/domains/org/hillsidek12.txt

makes hillsidek12.net and .org as recognized educational domains

adds Hillside Public Schools to  Domain List

---

lib/domains/ro/cnc.txt

Added the domain for "Carol I" National College, Craiova

Domain for "Carol I" National College, Craiova

---

lib/domains/uk/ac/btc.txt

Bridgwater & Taunton College is a college/university in Somerset, England. It offers a variety of courses in the Computer Science space, one of them being: https://www.btc.ac.uk/courses/higher-education/computing-digital-industries/computing-and-digital-technologies-foundation-degree/. The email address for BTC is `@btc.ac.uk`.

Add Bridgwater & Taunton College

---

lib/domains/edu/greenriver.txt

- student.greenriver.edu was already added, but greenriver.edu separately is needed for faculty.

Add greenriver.edu domain.

---

lib/domains/kr/ac/cufs.txt

Hi team, I added 'cufs.ac.kr' domain, an acronym of the "Cyber Hankuk University of Foreign Studies" in Korea.
* https://www.cufs.ac.kr/eng/main.do

added the "cufs - Cyber Hankuk University of Foreign Studies"

---

lib/domains/org/gh-is.txt

**YOUNITED, the Givat Haviva International School's** domain name is younitedschool.org, but current student emails are still stuck with the gh-is.org domain, so that is being registered instead. The old gh-is.org domain redirects to younitedschool.org as proof of usage.
We have a 2-year Computer Science course which follows the International Baccalaureate Diploma Programme, as seen in https://younitedschool.org/academics/. The school is located in Israel's Haifa District.

Adding the domain of YOUNITED, the Givat Haviva International School

---

lib/domains/it/cref.txt

CREF website: www.cref.it
CREF is a public research institution that offers a phd program in physics: https://www.cref.it/la-ricerca/phd/ The official emails of all the students are available in each student's page, all with a cref.it domain.

Add CREF domain

---

lib/domains/academy/tynecoast/nef.txt
lib/domains/uk/co/nefuturesutc.txt

My school changed its domain from the old nefuturesutc.co.uk to the new one, nef.tynecoast.academy
This PR Removes the old domain and adds the new one.

North East Futures changed domain.

---

lib/domains/be/eci-liege.txt

https://eci-liege.info is the official site, but they use @eci-liege.be for email, I forgot to add it in my first pull request.
Everything is the same as #23756 
You can see they own the domain here: https://www.dnsbelgium.be/fr/whois/info/eci-liege.be/details

Add .be for ECI

---

lib/domains/at/bruckneruni.txt

> the university official website URL
https://www.bruckneruni.at
> a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university
https://www.bruckneruni.at/en/institutes/composition-conducting-and-computer-music/studium
* Computer Music 
* Postdigital Lutherie
> a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.
On https://www.bruckneruni.at/en/university/international-relations/erasmus/erasmus-student-mobility-outgoing under "Application Procedure" it says:
> Please use only your student e-mail address (...@student.bruckneruni.at)

adds bruckneruni.at

---

lib/domains/berlin/kkg/iserv.txt

Official homepage is https://www.kaethe-kollwitz-gymnasium.de/service/
On the linked page, under "IServ Portalseite" you see the reference to the domain I am adding here. This domain and the other one already in the repository (kkos.net) will run in parallel.

added new domain to KKG Berlin

---

lib/domains/com/safamadrid/a.txt

Hola, solicito incorporar este colegio al repositorio.
Colegio: Sagrada Familia de Madrid (SAFAMADRID)
URL: https://safamadrid.com

Colegio Sagrada Familia de Madrid

---

lib/domains/org/eaportal.txt

The eaportal.org domain is given to students of the South American division of the Seventh-Day Adventist educational system.
Official site: http://www.educacaoadventista.org.br/
Spanish version of the site for non-Portuguese speaking countries: https://www.educacionadventista.com/
This specific domain is used by students to log into the school portal.

Add: eaportal.org domain

---

lib/domains/hu/njit.txt

Request to add the "njit.hu" domain, belonging to the BMSZC John von Neumann Secondary School, or it's Hungarian name, "BMSZC Neumann János Informatikai Technikum" in Budapest, Hungary. I've noticed that the "njszg.hu" domain is also present in the lib, this was the old domain of this school, before its renaming a few years ago.

Addition of the njit.hu domain.

---

lib/domains/com/ulc-icam.txt

La Faculté d’ingénierie ULC-Icam est cogérée par l’Université Loyola du Congo et le groupe Icam. 
https://www.ulc-icam.com/presentation/

Add Faculté d'ingénierie ULC-Icam, www.ulc-icam.com

---

lib/domains/fr/lycee-berthelot/eleves.txt

Website: https://lycee-berthelot.fr
This is an high school but it provides higher education through France's exclusives "CPGE" (i.e: public preparatory classes for commercial and engineering schools).

Adding "Lycée Marcelin Berthelot", a french school

---

lib/domains/edu/usca.txt

Adding the domain for the University of South Carolina, Aiken (usca.edu)

Add Univeristy of South Carolina, Aiken

---

lib/domains/kr/ac/bist/go.txt

I would like to get my school's domain verified.
The domain in question was issued through a Google student account, and a school domain(bist.ac.kr) cannot be issued through any other method, so we are requesting this.
School URL : https://www.bist.ac.kr/univ/main/index.php
Domain Course : https://computer.bist.ac.kr/contents/contents_view.php?site_id=computer&TREE_NO=1660&DEPTH=3

Add go.bist.ac.kr domain (This is our school's Google student account.)

---

lib/domains/ph/edu/sti/carmona.txt

STI College's Website: https://www.sti.edu/
School Addresses: Lot 2A Brgy. Maduya, Carmona, Cavite, Philippines
IT related courses: [Bachelor of Science in Information and Technology](https://www.sti.edu/programs-details.asp?p=Mw==)
Proof of Email Domain:

Added STI College Carmona

---

lib/domains/ca/lakeheadschools.txt

Hello,
Superior Collegiate& Vocational Institute is a Canadian high school in Thunder Bay (lakehead district).The schools including universities in Canada do not use the domin name ".edu", instead, they all use the domin name of "schoolname.ca", so these schools do not meet your requirement. The information is available on its [website](https://superior.lakeheadschools.ca/). Please kindly add the school on your list so that  I can register as a student.
Thank you for you time and support.
Regards

Add Superior Collegiate & Vocational Institute(a Canadian high school in Thunder Bay)

---

lib/domains/de/bs-intra.txt

@bs-intra.de
Offizielle Website der Schule: https://www.bsz-roth.de/
IT-bezogener Kurs: https://www.bsz-roth.de/berufsfachschule-fuer-informatik/anwendungsentwicklung/
Nachweis der Domain-Nutzung:

Add bs-intra domain

---

lib/domains/org/scuolacampostrini.txt

**Official School Website**: https://scuola.campostrini.it/
**Istitutional Website**: https://www.campostrini.it/

Added Istituto Campostrini

---

lib/domains/edu/gntc.txt

Adds [Georgia Northwestern Technical College](https://gntc.edu). I am in the [cybersecurity degree program](https://gntc.smartcatalogiq.com/en/2024-2025/semester-catalog/programs-of-study-business-and-cyber-related-technologies/cybersecurity-is23-associate-of-applied-science-degree/).

add Georgia Northwestern Technical College (gntc.edu)

---

lib/domains/kr/ac/koje/office.txt

Document Name: 2024 Admissions Guide for International Students
URL: https://enter.koje.ac.kr/site/resource/koje/enter/file/2024%20Admissions%20Guide%20for%20International%20Students(regular)240430.pdf
Description: This document includes information regarding the official email domains (@office.koje.ac.kr) used by the university staff responsible for student admissions. The provided link is to an official document that helps verify the authenticity of the domain being submitted.
The University Website: https://www.koje.ac.kr/www

Add office.koje.ac.kr domain

---

lib/domains/cn/edu/huel.txt

Add Henan University of Economics and Law.
Official website: https://www.huel.edu.cn/

Add huel.edu.cn

---

lib/domains/gr/auth/ece.txt

Website of university (Aristotle University of Thessaloniki) https://www.auth.gr/en/
Mention of top-level email domain from official page (near end of page -- also in screenshot) https://it.auth.gr/en/institutional-account-guide/
Website of ECE school (https://ece.auth.gr/en/home/). Note at the bottom under contact, the requested subdomain can be observed.
Could not procure a full up-to-date undergraduate curriculum in English, I quote instead an excerpt from the general information page (https://ece.auth.gr/en/general-information/).
> The curriculum comprises the core (semesters 1-5) and 3 parallel specializations (semesters 6-10).
The core cycle is common to all students and provides the necessary background knowledge in mathematics, physics and informatics, as well as in Electrical and …

Create ece.auth.gr entry

---

lib/domains/de/wgmail.txt

Unfortunately, https://wgmail.de does not redirect to the homepage of the school. You can find the homepage here: https://www.wolkenberg-gymnasium.de/.
I hope it's still possible to verify that the wgmail.de domain is affiliated with the school. (I've seen a few @wgmail.de addresses used on the homepage).
If you need me to do anything more for verification, please reach out.

Added Wolkenberg Gymnasium Michendorf

---

lib/domains/fi/jamsa/edu.txt

Adds Jämsän lukio (official translation Jämsä General Upper Secondary School, Finnish equilevant of a high school)
https://www.jamsa.fi/en/child-care-and-education/education-and-child-care-upper-secondary-education/
Page on the Finnish National Agency of Education's Studyinfo: https://opintopolku.fi/konfo/en/oppilaitos/1.2.246.562.10.89836037138

Add Jämsän lukio

---

lib/domains/edu/jessup.txt

Jessup University is a private university based in Rocklin, CA 95765, with campuses in Rocklin CA, San Jose CA and Portland OR. Please review and approve for using JetBrains products using an educational license. Thank you.

Adding Jessup University's domain to the repo.

---

lib/domains/bd/edu/diu.txt

Daffodil International University is one of the leading universities in Bangladesh offering many long term IT related courses. The university uses multiple domains for email. diu.edu.bd is one of them.
website link: https://daffodilvarsity.edu.bd/
https://diu.edu.bd/ also redirects to https://daffodilvarsity.edu.bd/

add diu.edu.bd

---

lib/domains/de/bs-ffb/schueler.txt

- Added domain for Staatliche Berufsschule Fürstenfeldbruck to allow students access to JetBrains educational products.
- Updated lib/domains/de/bs-ffb/ directory to include schueler.txt which is the subdomain domain used for students
This is the official school website: [https://www.bs-ffb.de/](bs-ffb.de)

feat: Add Staatliche Berufsschule Fürstenfeldbruck to JetBrains/swot

---

lib/domains/ke/ac/kisumupoly.txt

**Add The Kisumu National Polytechnic**
_The university's official website URL_: https://kisumupoly.ac.ke/
_A URL of a page on the official website where a long-term (>1 year) IT-related course is offered by the university: 
https://kisumupoly.ac.ke/computer-and-informatics/
https://application.kisumupoly.ac.ke/Home/PublicProgramDetails?id=9909172b-5586-43a5-bfb0-05eb07c801f1

Add The Kisumu National Polytechnic

---

lib/domains/mx/uvp.txt

I am submitting this pull request to add the domain uvp.edu.mx to the SWoT repository. This domain belongs to the Universidad del Valle de Puebla (UVP), a higher education institution in Mexico. The inclusion of this domain will allow students and faculty members from UVP to request free educational licenses for JetBrains products.
the university official website URL:   https://uvp.mx/

Add UVP domain for students

---

lib/domains/edu/london.txt

london.edu for london business school is suggested to be added to the edu domain directory, Thank you so much

Adding London Business School domain to the list

---

lib/domains/edu/franciscan.txt

Domain is franciscan.edu, which is also the website, https://franciscan.edu.
It offers a 4-year Software Engineering program, catalog page [here](<https://franciscan.smartcatalogiq.com/2024-2025/undergraduate-catalog-2024-2025/academic-programs/engineering/software-engineering/>).

Add Franciscan University of Steubenville

---

lib/domains/edu/toronto/cs.txt

Request to add University of Toronto's Computer Science department to the approved domain list

Add UofT CS email domain

---

lib/domains/be/maredschool.txt

Ajout du domaine pour Collège Saint-Benoît de Maredsous.
Site officiel : https://college.maredsous.be/
Le site ne possède pas de page d'inscription pour l'utilisation de se domaine dans les études. Mais celui-ci est bien présent dans l'option sciences économiques et PES.

add maredschool

---

lib/domains/uz/fdu.txt

Adding Fergana State University to the JetBrains Student License program. The official domain is fdu.uz.

Add Fergana State University domain file (fdu.uz)

---

lib/domains/kr/seoultech.txt

the university official website URL,
https://en.seoultech.ac.kr/
The university email domain is `@seoultech.ac.kr`
Seoul National University of Science and Technology (Seoultech) was established in 1910, originally starting as "Kyungsung Technical School." After undergoing several transformations, it was officially renamed Seoul National University of Science and Technology in 1993.
Currently, Seoultech operates 9 colleges and 47 undergraduate and graduate programs, serving approximately 14,000 students and over 600 faculty members. The university offers excellent education and research across various fields, including engineering, science, humanities, social sciences, and business.
Seoultech has a strong tradition in engineering, particularly in IT and computer engineering, and provides …

update univ list

---

lib/domains/bg/nvu.txt

Add the domain of bulgarian National Military School(Natsionalno Voenno Uchilishte in bulgarian, hence the NVU abbreviation) to the known domains. Reference to the website of the institution https://www.nvu.bg/bg

Add nvu.bg to the known university domains

---

lib/domains/org/cjits.txt

Add cjits.org domain to JetBrains' recognized domain list.

added cjits.org domain for licenses.

---

lib/domains/au/edu/aih/students.txt

[AIH Website](https://aih.edu.au/)
AIH from 30th August 2024 moved its email service provider from Gmail to Microsoft Outlook and have started using domain `students.aih.edu.au`
[Gmail - Reminder your student email has transitioned from Gmail to Microsoft Outlook.pdf](https://github.com/user-attachments/files/17786645/Gmail.-.Reminder.your.student.email.has.transitioned.from.Gmail.to.Microsoft.Outlook.pdf)

Added Australian Institute of Higher Education updated student email address

---

lib/domains/kr/go/cberi.txt

‘cberi.go.kr’ is the domain address for emails provided to high school students in North Chungcheong Province, South Korea. This domain is owned by the Chungcheongbuk-do Education Research and Information Institute.

Add cberi.go.kr

---

lib/domains/es/upm.txt

Engineering university in Madrid, Spain
URL: https://www.upm.es/
IT course details: [Computer Engineering (offered since 2009)](https://www.etsiinf.upm.es/?id=gradoingenieriainformatica/visiongeneral) (etsiinf prefix corresponds to the Computer Science faculty)
Software Engineering, Hardware Engineering, Data Science and many other IT courses offered. 
Proof of domain:
- Current students have "@alumnos.upm.es": domain is shown in [email login portal](https://www.upm.es/webmail_alumnos/?_task=mail&_mbox=INBOX) ('alumnos' means students in Spanish)
- Faculty has "@upm.es": domain also shown in [email login portal](https://www.upm.es/webmail_personal/)
- Alumni are not given an email address
Thus, "upm.es" has been added in the pull request as is shared by students and faculty.

Universidad Politécnica de Madrid (UPM)

---

lib/domains/org/mcusd709.txt

- The web site for the school district is https://www.morton709.org/
- The high school has two [Advanced Placement CS courses](https://docs.google.com/document/d/1xyLEcWqNIJnYOvHmEZ5MUGxgUAGqN1rZIARhm4tBn_Y/edit?tab=t.0#heading=h.sa6i4qgb6ubg). One of them is a yearlong course taught entirely in Java.

Add Morton Unit School District 709

---

lib/domains/no/afk.txt

Starting from this school year viken.no is replaced with 3 different domains. This can be seen in the url in this [file](https://github.com/JetBrains/swot/blob/master/lib/domains/no/viken.txt).
https://afk.no/lillestrom-vgs/kontakt-oss/ is Lillestrøm videregående's contact us page and you can see a bunch of @afk.no emails.
https://afk.no/royken-vgs/utdanningstilbud/ shows Røyken videregående's programs list which includes some programs related to programming and information technologies.
Both the student and the teachers have their name and the first couple letters of their surname followed by @akf.no as their e-mails.
F.eks: Patrick Jane could have [janepa@afk.no](mailto:janepa@afk.no)

Create afk for schools in Akershus

---

lib/domains/edu/url/iqs-blanquerna.txt

This corresponds to  Instituto Químico de Sarriá (Universidad Ramon Llull)

Add domain iqs-blanquerna.url.edu

---

lib/domains/nz/org/tekura.txt

the current domain for Te Kura is outdated, mytekura.school.nz is not used anymore (at least for new accounts). tekura.org.nz is now used.
Also see on this page under the "Set up Te Kura Google Account" dropdown: https://www.tekura.school.nz/learn-with-us/get-started/get-started-online/

tekura.org.nz

---

lib/domains/fr/bginette.txt

The St-Genevieve preparatory class is an higher education institution which prepare French students to enter engineering school.
https://en.wikipedia.org/wiki/Lyc%C3%A9e_priv%C3%A9_Sainte-Genevi%C3%A8ve
https://www.bginette.com/

Added Sainte-Genevieve preparatory class

---

lib/domains/ro/szekelymikokollegium.txt

Link to the school's official website:
https://www.szekelymikokollegium.ro/

Added Székely Mikó National College

---

lib/domains/id/sch/smkn1pacitan.txt

SMK Negeri 1 Pacitan is a State-owned vocational high school located in Pacitan Regency, East Java, Indonesia

add domain for SMK Negeri 1 Pacitan

---

lib/domains/bd/edu/sgps.txt

I am submitting a request to add **Saratnagar Government Primary School** to the JetBrains educational institutions list.
**Details:**
- **School Name**: Saratnagar Government Primary School  
- **Domain**: sgps.edu.bd  
- **Address**: Saratnagar, Pabna District, Bangladesh  
- **Official Website**: [https://sgps.edu.bd/](https://sgps.edu.bd)
**Supporting Information**:
1. The domain `sgps.edu.bd` is officially used by the school for communication and email services.
2. Saratnagar Government Primary School is an educational institution that provides long-term foundational courses for students in primary education, fostering academic development in the region.
If you need additional proof or documentation, please let me know!

add sgps.edu.bd

---

lib/domains/np/edu/texascollege.txt

Description
This pull request adds the domain texascollege.edu.np to the JetBrains/swot repository to enable students and faculty of Texas International College, located in Nepal, to apply for free JetBrains educational licenses.
Details
Domain: texascollege.edu.np
Institution Name: Texas International College
Location: Kathmandu, Nepal
Verification
The domain is owned by Texas International College and is used for official email addresses of students and faculty.
Checklist
Added lib/domains/np/edu/texascollege.txt
File includes the institution name only.
Verified the domain format follows repository guidelines.

Add texascollege.edu.np for free educational licenses

---

lib/domains/ph/edu/sti/davao.txt

- **Website:** [davao.sti.edu](https://davao.sti.edu)
- **Note:** STI College has already been added previously, but only for other branches and not the Davao branch

Add STI College of Davao

---

lib/domains/fr/institut-g4.txt

Ajout de l'Institut G4 www.institut-g4.fr, ecole supérieur en formation d'informatique

Add institut G4 France

---

lib/domains/uk/ac/bcot/student.txt

“This PR adds the domain bcot.ac.uk for Basingstoke College of Technology to enable students and staff to use JetBrains educational tools.”

Add bcot.ac.uk Basingstoke College of Technology

---

lib/domains/edu/uft.txt

They use `@uft.cl` domain for teachers, `@uft.edu` for students.
Web page domains: `uft.cl`, `finis.cl` (main one), `finisterrae.cl`
computer science: `https://admision.finis.cl/carrera/ingenieria-civil-en-informatica-y-telecomunicaciones/`
they mention giving edu mails here: `https://finis.cl/estudiantes/recursos-estudiantiles/`, `https://finis.cl/wp-content/uploads/2024/04/instructivo-ingreso-a-plataformas.pdf` page 7

Added uft.edu (Finis Terrae University)

---

lib/domains/edu/umw.txt

Here is one of multiple examples of long-term programs related to IT offered at the University of Mary Washington: https://www.umw.edu/study/areas/computer-science/
Also, the mail.umw.edu email domain is already included in this repository. That subdomain is used exclusively for students, while faculty use the root domain umw.edu (being submitted now).

Add umw.edu to list of email domains

---

lib/domains/eu/cifpfbmoll.txt

CIFP Francesc de Borja Moll (Spain).
Educational center with vocational training in IT.
- Official webpage: https://www.cifpfbmoll.eu/
- Long term courses: https://www.cifpfbmoll.eu/cfgs-desenvolupament-daplicacions-web/
- Proof of the email domain for students: https://www.cifpfbmoll.eu/github-campus-program/

Add CIFP Francesc de Borja Moll

---

lib/domains/pk/edu/iac.txt

The institute URL is [iac.edu.pk](https://iac.edu.pk/) and here is the [google profile](https://g.co/kgs/JkbztVf)

iac.edu.pk domain added

---

lib/domains/net/parklandsd.txt

This helps all parkland high school students obtain a license to Pycharm. The school website is here: https://phs.parklandsd.org/
and our emails are (7 digits) followed by @parklandsd.net

Adding parkland high school domain

---

lib/domains/de/glh.txt

Add Domain for GLH (Gymnasium Lüneburger Heide).
Official website: https://www.glh.de/
Explicit mentioning of computer science (informatik) classes: https://www.glh.de/unterricht-gymnasium-privatschule-lueneburg/

Add glh.de

---

lib/domains/nrw/rbg.txt

[Rudolph-Brandes-Gymnasium](https://www.rudolph-brandes-gymnasium.de/)
As the domain isn't listed on the website you can use a whois lookup to verify that the registrar is the Rudolph-Brandes-Gymnasium.

Rudolph-Brandes-Gymnasium

---

lib/domains/co/edu/educacionbogota.txt

Soy docente en un colegio que pertenece a la secretaría de educación del Bogotá 
Los dominios que entregan son educacionbogota.edu.co
Agradezco la ayuda que me puedan brindar. Gracias.

solicitud para incluir la secretaría de educación de Bogotá, Colombia

---

lib/domains/vn/edu/lqddn.txt

School's website: http://www.thpt-lequydon-danang.edu.vn/
Wiki: https://en.wikipedia.org/wiki/L%C3%AA_Qu%C3%BD_%C4%90%C3%B4n_High_School_for_the_Gifted,_Da_Nang

Add Le Quy Don High School 

---

lib/domains/pl/szczecin/zsee.txt

ZSEE - Zespół Szkół Elektryczno-Elektronicznych im. prof. Maksymiliana Tytusa Hubera w Szczecinie formerly known as
TME - Technikum Elektryczno Elektroniczne w Szczecinie
https://tme.edupage.org/
https://tme.szczecin.pl/
https://www.facebook.com/p/Zesp%C3%B3%C5%82-Szk%C3%B3%C5%82-Elektryczno-Elektronicznych-ZSEETME-100040041257203/?locale=pl_PL

ZSEE school added

---

lib/domains/at/hochschule-burgenland.txt

Hochschule Burgenland (english name University of Applied Sciences) is a university in Austria. It was formerly known as Fachhochschule Burgenland and is actually in the repository to be found at lib/domains/at/fh-burgenland.txt. However since our rebranding at the end of 2024 the school is known as Hochschule Burgenland and the system does seem to not regocnize it anymore, I think it could be that our E-Mail-Addresses were changed to fit the rebranding. If my fork was to be merged you would find the new file at lib/domains/at/hochschule-burgenland.txt.
Our Website: https://hochschule-burgenland.at/

Add Hochschule Burgenland

---

lib/domains/edu/uwi/mycavehill.txt

Official website URL: https://www.cavehill.uwi.edu/home
IT related course URL: https://www.cavehill.uwi.edu/fst/cmp/programmes/undergraduate/computer-science.aspx
Proof showing that the university recognizes the email domain: https://www.cavehill.uwi.edu/cits/services/for-students/mycavehill-student-mail.aspx

Add University of the West Indies at Cave Hill domain

---

lib/domains/cat/insjaumemimo.txt

Added "Institut Jaume Mimó", from Cerdanyola del Vallès, Spain.
I'd like to clarify that, although it might seem that the domain of **Institut Jaume Mimó** is [agora.xtec.cat](https://agora.xtec.cat/iesjaumemimo/), this is not the actual domain of the school, that is a different domain that all public schools in Catalonia use, and it's not often used on mails for that reason.
The school's actual domain is insjaumemimo.cat. You can verify this in this [link](https://educaciodigital.cat/iesjaumemimo/moodle/login/index.php) (where students log in), where there is a button to automatically log in with any mail with the @insjaumemimo.cat domain.
You can also find the site where students log in by clicking the "Moodle" button on the [homepage](https://agora.xtec.cat/iesjaumemimo/).

Add Institut Jaume Mimó

---

lib/domains/id/ac/ppns/student.txt

Adding Politeknik Perkapalan Negeri Surabaya to JetBrains SWOT
**Official Institution Name**: Politeknik Perkapalan Negeri Surabaya (PPNS)
**English Name**: Shipbuilding Institute of Polytechnic Surabaya (SHIPS)
**Location**: Surabaya, Indonesia
**Email Domain**: student.ppns.ac.id
**Official Website**: https://ppns.ac.id/

Added Politeknik Perkapalan Negeri Surabaya

---

lib/domains/edu/hampshire.txt

Add Hampshire College (hampshire.edu) to recognized domains.

Add hampshire.edu domain

---

lib/domains/no/tromsfylke.txt

**Official website:** https://nordtroms.vgs.no/
**Proof of domain usage:**
- https://nordtroms.vgs.no/kontakt-oss/kontaktinformasjon/
- https://www.tromsfylke.no/AnsattOversikt.aspx?pkid=9395&MId1=433#/details/27174a98-a274-4ae3-bc01-696befccf56d
**IT-related course:** https://nordtroms.vgs.no/utdanningstilbud/informasjonsteknologi-og-medieproduksjon/

Added domain tromsfylke.no for Nord-Troms Videregående Skole

---

lib/domains/au/edu/icms/students.txt

official website URL: https://www.icms.edu.au/
address: 151 Darley Rd, Manly NSW 2095, Australia
IT related course: https://www.icms.edu.au/courses/undergraduate/bachelor-of-Information-Technology/
domain: https://www.icms.edu.au/contact/

Add ICMS (International College of Management, Sydney) domain

---

lib/domains/com/coursdiderot.txt

the school official full name, no abbreviations please : Cours Diderot
the school official website URL : https://www.coursdiderot.fr/
the school street address, including city and country : La page contact avec les adresses de tous nos campus : https://www.coursdiderot.fr/contact/
an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course : https://www.coursdiderot.fr/bts-services-informatiques-organisations/

Request to add coursdiderot.com

---

lib/domains/ca/qc/cslsj.txt

Hello, here is the PR regarding the addition of the Jean-Gauthier school of the Lac Saint-Jean school board located in the province of Quebec in Canada. The school is a public school of the Lac-Saint-Jean School Services Center. Thank you
https://csslsj.gouv.qc.ca/
https://ecolejeangauthier.com/

cslsj scool added to domains in Canada => province of Quebec

---

lib/domains/edu/IC.txt

International College (IC) Lebanon
https://www.ic.edu.lb/welcome
https://www.ic.edu.lb/academics/steam
ic.edu.lb
The `ic.edu.lb` email domain is actively used by students and staff for educational purposes. Let me know if you need additional information or documentation.

Add ic.edu.lb domain

---

lib/domains/br/unisal/aluno.txt

Hello, in 2020 there was an update in Emails from UNISAL (the university I study computer engineering) in Brazil, and accordingly to Brazilian data laws, they need to change from RA@aluno.sj.unisal.br to RA@aluno.unisal.br (removing the .sj). So I've created this domain to match the new pattern of my university email.

Adding unisal generic domain

---

lib/domains/se/gritgames.txt

Grit Academy (gritacademy.se) has started a new 2-yr program for game developers. Students are learning to code in C++ and C# together with Unreal Engine and Unity. These students will be using gritgames.se as their email domain instead of gritacademy.se - but it is still the same school. This is the reason I request to add this domain.

Added additional domain for Grit Academy

---

lib/domains/nz/school/ths.txt

adding Taradale High School (high school in Napier, Hawke's Bay, NZ)

adding Taradale High School

---

lib/domains/ph/edu/kld.txt

Please Add Kolehiyo ng Lungsod ng Dasmariñas (English name: College of City of Dasmariñas)
Official Facebook Link: https://www.facebook.com/KLDOfficialFBPage
Official Website Link: https://www.kld.edu.ph
BS in Information Systems Program Included in the Website: https://www.kld.edu.ph/degree-programs/

Added Kolehiyo ng Lungsod ng Dasmariñas

---

lib/domains/uk/ac/johnruskin.txt

Address: John Ruskin College, Selsdon Park Road, South Croydon, CR2 8JJ
Website: https://www.johnruskin.ac.uk/
Domain: @johnruskin.ac.uk

Add johnruskin.txt

---

lib/domains/es/canariaseducacion.txt

This pull request adds the domain `canariaseducacion.es` to the repository.
- **Official website of the organization:**  
[https://www.gobiernodecanarias.org/educacion](https://www.gobiernodecanarias.org/educacion)
- **URL of a page offering long-term IT-related courses:**  
[Curso de Desarrollo de Aplicaciones Web](https://todofp.es/que-estudiar/grados-d/grado-superior.html)
- **Proof that the domain is officially used for students:**  
The domain `@canariaseducacion.es` is the official email domain provided to students by the Consejería de Educación, Universidades, Cultura y Deportes - Gobierno de Canarias. This can be verified on their official website or email-related pages.
If additional details or clarifications are needed, please let me know. Thank you for reviewing this request!

Add canariaseducacion.es domain

---

lib/domains/hu/bme/mm.txt

Domain `mm.bme.hu` is used by teachers of the Dept. of Applied Mechanics in:
Budapest University of Technology and Economics 
(Faculty of Mechanical Engineering)
IT-related courses offered by the university: [Computer Engineering courses (BSC, MSC)](https://www.vik.bme.hu/en/education/programs/)
Programming-related course offered by the faculty: [Mechanical Engineering Modeling MSC](https://www.mm.bme.hu/spec/solidmech)
URL of a page showing that the university recognizes the domain: [mm.bme.hu/contact](https://www.mm.bme.hu/contact)
Thanks for reviewing the PR in advance.

Added Dept. of Applied Mechanics (Budapest University of Technology and Economics)

---

lib/domains/edu/sccollege.txt

Santiago Canyon College (https://sccollege.edu)
SCC is a "2 year" community college located in Orange County, California.
They offer Computer Science as an "Area of Study": https://sccollege.edu/academics/areasofstudy/computerscience/SitePages/Home.aspx

Adding Santiago Canyon College as an approved domain

---

lib/domains/edu/atlantic.txt

Additional information:
[https://www.atlanticcape.edu](https://www.atlanticcape.edu/)
Faculty  emails are in the form [username@atlantic.edu](mailto:username@atlantic.edu)
Thank you for reviewing this request!

Added Atlantic Cape Faculty Email Domain

---

lib/domains/edu/illinoistech.txt

New student addresses for Illinois Institute of Technology use `illnoistech.edu` instead of the "legacy" domain of `iit.edu`. Both domains are valid but students enrolled prior to 2025 have iit addresses and new students have illnoistech addresses.

add new IIT domain for Outlook addresses

---

lib/domains/in/ac/pdpu/sot.txt

University URL: https://pdeu.ac.in/school-of-technology
Also active: https://sot.pdpu.ac.in/
Courses offered: https://pdeu.ac.in/courses
Note:
University underwent a name change from Pandit Deendayal Petroleum University (PDPU) to Pandit Deendayal Energy University (PDEU)
Emails for students still use pdpu.ac.in but website has been changed to pdeu.ac.in

Added Pandit Deendayal Energy University

---

lib/domains/au/edu/vic/albertparkcollege.txt

School:
Albert Park College
Website:
https://albertparkcollege.vic.edu.au

Added albertparkcollege to domain/au/edu/vic

---

lib/domains/mx/edu/unistmo/sandunga.txt

Dentro del repositorio ya existía una entrada para la Universidad del Istmo, específicamente con el dominio bianni. Sin embargo, la universidad utiliza diferentes dominios de correo electrónico para sus distintos campus.
En este caso, se ha agregado un nuevo dominio sandunga, que corresponde a otro campus de la misma universidad.
Gracias por revisar y considerar esta solicitud. Quedo atento a cualquier comentario.

Añadir dominio "sandunga" para la Universidad del Istmo

---

lib/domains/ca/senecapolytechnic.txt

Adding senecapolytechnic.ca to list of post-secondary institutions in Canada.
Seneca College recently changed its domain from senecacollege.ca to senecapolytechnic.ca

senecapolytechnic.ca

---

lib/domains/in/ac/nits.txt
lib/domains/in/ac/nits/che.txt
lib/domains/in/ac/nits/civil.txt
lib/domains/in/ac/nits/cse.txt
lib/domains/in/ac/nits/ece.txt
lib/domains/in/ac/nits/ei.txt
lib/domains/in/ac/nits/hum.txt
lib/domains/in/ac/nits/math.txt
lib/domains/in/ac/nits/mba.txt
lib/domains/in/ac/nits/mech.txt
lib/domains/in/ac/nits/phy.txt

| Institute                        			| eMail Domain		|
|-------------------------------------------	|------------------	|
| National Institute of technology, Silchar       | nits.ac.in 	|
| Department/School                         	| eMail SubDomain  	|
|-------------------------------------------	|------------------	|
| Civil Engineering                         	| civil.nits.ac.in 	|
| Mechanical Engineering                    	| mech.nits.ac.in  	|
| Computer Science & Engineering            	| cse.nits.ac.in   	|
| Electronics & Communication Engineering   	| ece.nits.ac.in   	|
| Electronics & Instrumentation Engineering 	| ei.nits.ac.in    	|
| Physics                                   	| phy.nits.ac.in   	|
| Chemistry                                 	| che.nits.ac.in   	|
| …

Added various NITS departments

---

lib/domains/sa/edu/fikr.txt
lib/domains/sa/edu/fikrgs.txt

A previous PR (https://github.com/JetBrains/swot/pull/20013) added Dar Alfikr Schools to the repo, but added it under the `fikrgs.edu.sa` domain, which is the domain for the Girls branch. I've added the male branch's domain (`fikr.edu.sa`). and updated the other domain's file to state that it's for the Girls' branch.

Add fikr.edu.sa, modify fikrgs.edu.sa

---

lib/domains/pl/edu/pwr.txt
lib/domains/pl/edu/pwr/student.txt

- Added subdomain given by Wrocław University of Science and Technology to students (@student.pwr.edu.pl)
- Updated university name in existing entry (@pwr.edu.pl) to current English official name and added official Polish name
Links for verification:
- Main university site: [https://pwr.edu.pl/en/](https://pwr.edu.pl/en/)
- Page saying @student.pwr.edu.pl e-mails are used by students: [https://di.pwr.edu.pl/uslugi/poczta/pierwsze-logowanie](https://di.pwr.edu.pl/uslugi/poczta/pierwsze-logowanie)
- Page related to currently started IT bachelor degree studies: [https://wit.pwr.edu.pl/en/students/programme-of-study/2024-2025-academic-year---1st-level](https://wit.pwr.edu.pl/en/students/programme-of-study/2024-2025-academic-year---1st-level)

Added Wrocław University of Science and Technology

---

lib/domains/fr/saintmichelannecy.txt

Email adresses with domain name saintmichelannecy.fr are given to our students.
More information about courses on https://www.st-michel.fr/formations/etablissement-superieur/formations/bachelor-csi-apprentissage

Add UFA Saint Michel, domain name saintmichelannecy.fr

---

lib/domains/edu/aie.txt

The Academy of Interactive Entertainment operates in the United States with a physical campus in Seattle, WA and Lafayette, LA and uses the `aie.edu` domain.
This addition covers the use of staff/faculty e-mail addresses under `aie.edu` and students under `students.aie.edu`.
- Official Website URL - https://aie.edu/
- Long-term: Seattle offers a [Game Programming](https://aie.edu/program/seattle/advanced-diploma-game-programming/) is a 4 Semester program spanning two years.
- Proof of Usage (excerpt from public-facing IT documentation): 
This is related, but distinct from https://github.com/JetBrains/swot/pull/4310 which recognizes `aie.edu.au` e-mail addresses but not `aie.edu`; the `.au` being for the Australian-facing staff and students.

Add AIE (US)

---

lib/domains/bd/ac/manarat.txt

Manarat International University is a private university in Bangladesh, established in 2001. It offers undergraduate and graduate programs in various disciplines, including CSE, EEE, Civil Engineering, Business Administration, Journalism, and English. With two campuses in Dhaka, Bangladesh.
website: https://manarat.ac.bd

Manarat International University added, established 2001

---

lib/domains/edu/clovis.txt

Official URL:
https://www.clovis.edu/
2-Year Associates Programming related degrees:
https://www.clovis.edu/cis/index.aspx
Overall general (though incomplete list of) Degree Plans and certificates:
https://www.clovis.edu/programs/
The college is physical and has been fully standalone since the 1990's (was a subdivision of a larger University before that, but it outgrew them).
Employee (Faculty, Admin, and other education related staff; contractors and outside people do not get emails) emails end with @clovis.edu
Student (recently active only, after 100 days at end of term students lose email access, they do not gain access to an email until they have registered and been admitted to a course and will immediately lose it if they drop their courses for any reason) emails end with …

Add `clovis.edu`

---

lib/domains/kz/edu/rii.txt

Added rii.edu.kz (Рудненский индустриальный университет) as a university email domain for JetBrains student licenses.
Official university website: https://www.rii.edu.kz/

Added rii.edu.kz to JetBrains/swot student license eligibility

---

lib/domains/com/onmicrosoft/hhbkde.txt

Add Domain hhbkde.onmicrosoft.com for Heinrich-Hertz-Berufskolleg in Düsseldorf Germany
Official Website is https://hhbk.de
Internal Suport Website is https://hhbk.support 
There are the personal o365 email

Add hhbkde.txt

---

lib/domains/de/log-web.txt

Adds the Lichtenberg-Oberstufen-Gymnasium (Bruchköbel, Hesse, Germany) to the list of known schools.
Domain: https://log-web.de.
It is a German High School, which also provides a course in IT (https://log-web.de/informatik/).

Add Lichtenberg Oberstufen Gymnasium

---

lib/domains/edu/lumcon.txt

Add Louisiana Universities Marine Consortium to edu domain.

Add Louisiana Universities Marine Consortium

---

lib/domains/ar/edu/empa.txt

Adding domain support for EMPA: Avellaneda Public University School 
1. Official site: https://www.empa.edu.ar/
2. Long duration careers could be seen at homepage https://www.empa.edu.ar/ "Carreras" section with 4+ years careers being shown
3. The University domain is the same as email domain

Adding empa.edu.ar domain for supporting its users

---

lib/domains/br/com/soubraseducacional.txt

Adicionando o domínio "soubraseducacional.com.br" para permitir que alunos e professores da Unibras solicitem licenças educacionais da JetBrains.
https://faculdadeunibras.com.br/nortegoiano/

Adicionando domínio da Unibras para acesso educacional

---

lib/domains/kr/ac/dst/i.txt

adding i.dst.ac.kr from https://www.dst.ac.kr

Daejeon Institute of Science and Technology

---

lib/domains/hu/gr-szechenyi.txt

1. [The domain ](https://gr-szechenyi.hu/) used in the email system redirects to a domain that hosts mostly websites of technical high schools all around Hungary: [https://szek-szechenyi.www.intezmeny.edir.hu/](https://szek-szechenyi.www.intezmeny.edir.hu/)
2. Example of a [5 year long course](https://szek-szechenyi.www.intezmeny.edir.hu/kepzeseink/technikum-szakkepzo) about software development:
3. The domain used in email addresses for the school's teachers and selected students (note that not every student gets a personal email address automatically) is listed as the main way of contacting the institution.

Added Széchenyi István Technical School of Engineering

---

lib/domains/gr/sch.txt

Adding 15° ΓΕΛ Αθηνών/15th general high school of athens

Adding 15° ΓΕΛ Αθηνών

---

lib/domains/nz/school/whs.txt

Add Wellington High School, Wellington, New Zealand https://www.whs.school.nz

Add Wellington High School

---

lib/domains/ro/colegiulunirea.txt

Added colegiulunirea.ro for Colegiul Național "Unirea" in Târgu Mureș, Romania. This domain is used for the school's official website and email addresses issued to students and staff.

Add colegiulunirea.ro to the list of academic domains

---

lib/domains/ch/rafisa.txt

Rafisa Informatik GmbH offers vocational education for authistic pers…ons in the IT industry at seven different locations in Switzerland. rafisa.ch is used as the Email domain for the students as well as for the trainers. See https://rafisa.ch/en/  for details

Rafisa Informatik GmbH offers vocational education for authistic students

---

lib/domains/de/rh-koeln/ext.txt

In this pull request, I want to add the Rheinische Hochschule Köln (formerly known as Rheinische Fachhochschule Köln) to known universities. 
https://rh-koeln.de/

Add Rheinische Hochschule Köln to known universities

---

lib/domains/jp/anabuki-college/c.txt
lib/domains/net/anabuki-college/c.txt

This pull request adds Anabuki Computer College to the list of supported educational institutions.
Anabuki Computer College is a recognized educational institution that meets the eligibility criteria for the JetBrains Educational License Program.
Thank you for considering this addition!
https://web.anabuki-college.net/

Add Anabuki Computer College to JetBrains Educational License Program

---

lib/domains/de/wbsedu.txt

This pull request adds the domain `wbsedu.de`, which is used by WBS TRAINING AG, a recognized educational institution in Germany.
- Official website: https://www.wbstraining.de/
- Official name (in native language): WBS TRAINING AG
- Email domain used by students: @wbsedu.de
WBS TRAINING AG provides certified educational programs and vocational training, and students receive institutional email addresses under the `wbsedu.de` domain.
Please note: This PR corrects a previous mistake that referred to a non-existent `.edu.ng` domain. This version uses the correct `.de` domain for Germany.
Thank you for reviewing!

Add wbsedu.de domain for WBS TRAINING AG

---

lib/domains/ua/nure.txt

Hi, this small MR aims to update the correct name of the NURE university, Ukraine.
Official website: https://nure.ua/en/

Update the proper official name of NURE university

---

lib/domains/kr/ac/taejae.txt

This pull request adds TAEJAE UNIVERSITY to the JetBrains/swot repository.
- University Name: TAEJAE UNIVERSITY
- Website: https://www.taejae.ac.kr
- Student Portal: https://portal.taejae.ac.kr
- Email Domain: taejae.ac.kr
- The official student and faculty email addresses use the domain `taejae.ac.kr`.
- Here is a screenshot showing the email login page or portal (attached or linked):
The university is an accredited higher education institution in South Korea, offering degree programs to undergraduate and graduate students.
Thank you for reviewing this request.

Add TAEJAE UNIVERSITY (taejae.ac.kr)

---

lib/domains/pl/edu/elektronik.txt
lib/domains/pl/elektronikonline.txt

School official website: https://elektronik.edu.pl
A list of available courses of study at the school: https://elektronik.edu.pl/index.php/2015-05-15-10-49-45/kierunki-ksztalcenia-w-roku-szkolnym-2025-2026
E-mails for teachers are contained in the domain @elektronik.edu.pl
Mail for students is contained in the domain @elektronikonline.pl

Add Elektronik Radom

---

lib/domains/mx/edu/f-idiomas.txt

This pull request adds the domain for Universidad Autónoma "Benito Juárez" de Oaxaca (UABJO) to the JetBrains/swot repository. UABJO is a public university located in Oaxaca, Mexico, and offers a variety of undergraduate and postgraduate programs, including Computer Science and related fields.

Add UABJO - Facultad de Idiomas de Oaxaca

---

lib/domains/edu/coloradomesa.txt

Adding coloradomesa.edu domain. We have two email domains, @coloradomesa.edu for staff/faculty and @mavs.coloradomesa.edu for students.
https://www.coloradomesa.edu/information-technology/how-to.html under Synchronizing CMU Mail

adding coloradomesa.edu domain

---

lib/domains/eu/c-a-g.txt

Bahnhofstraße 53
49661 Cloppenburg
https://c-a-g.de/ (Homepage)
https://c-a-g.eu/ (IServ - **mail**, files, tasks, etc.)
The domain for mail is `c-a-g.eu` instead of `c-a-g.de` because IServ runs on `c-a-g.eu`.
https://c-a-g.de/index.php/unterricht
https://c-a-g.de/index.php/startseite/kontakt

Added Clemens August Gymnasium Cloppenburg

---

lib/domains/de/dhsn/edu.txt

This PR adds the _Duale Hochschuule Sachen_ E-Mail domain used by students, `edu.dhsn.de`.
The institution was previously called _Berufsakademie Sachsen_. This name is included in the `edu.txt`.
In the interest of getting the domain added quicker:
> the university official website URL, if it is different from the domain you are submitting
- Homepage of the institution: https://www.dhsn.de/ (Unfortunately only available in German)
- Note that the previous name is mentioned on this Homepage ("_Berufsakademie Sachsen is now called..._")
> a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university
- For example: https://www.dhsn.de/studienangebot/detail/medieninformatik
> a URL of a page or some other proof (.pdf or a screenshot are OK) …

Add "Duale Hochschule Sachsen" domain

---

lib/domains/in/edu/kahedu.txt

Added the domain file for Karpagam Academy of Higher Education to support JetBrains student license.

Add Karpagam Academy of Higher Education (kahedu.edu.in)

---

lib/domains/edu/eicc/live.txt

This fork is to allow Eastern Iowa Community Colleges to the list comprising the @live.eicc.edu domain for student email addresses.
Official Website: https://eicc.edu
IT Courses: https://eicc.edu/classes-programs/pathway/information-solutions/programming/
Email Domain Information:  There isn't a good screenshot on any specific page to show the live.eicc.edu domain, but you can see in the email section that they are using Microsoft Live 365 which is why the sub-domain is live.eicc.edu.  More information here:  https://eicc.edu/eicc-for/current-students/accessing-eicc-accounts.aspx

Add EICC community colleges to the list - live.eicc.edu

---

lib/domains/org/edubridgeschool.txt

This pull request adds `edubridgeschool.org` to the JetBrains SWoT repository.
- School name: Edubridge International School
- Website: https://edubridgeschool.org
- Email domain proof: edubridgeschool.org (provided via JetBrains school file)

Add Edubridge International School domain

---

lib/domains/ar/edu/ifts24.txt

This pull request adds the domain `ifts24.edu.ar` to the list of recognized educational institutions.
**Institution name:** Instituto de Formación Técnica Superior N.º 24  
**Website:** https://www.ifts24.edu.ar  
**Official domain used by students and staff:** ifts24.edu.ar  
**Justification:**
- IFTS N.º 24 is a public higher education institution located in Buenos Aires, Argentina.
- Students and teachers use email addresses under the `@ifts24.edu.ar` domain.
- You can verify the institution’s official website at https://www.ifts24.edu.ar.
- Contact emails such as `bedelia@ifts24.edu.ar` or `soportecampus@ifts24.edu.ar` are visible on the site.
This addition will allow students from IFTS N.º 24 to apply for free JetBrains educational licenses.

Add ifts24.edu.ar to JetBrains educational domains

---

lib/domains/it/edu/liceobonghi-rosmini.txt

The Liceo Bonghi-Rosmini is a lyceum located in Lucera (FG), Italy. It offers a specialized track called "Scienze Applicate" (Applied Sciences), which includes computer science and programming as part of the curriculum. In this course, students use programming languages like Python and often work with JetBrains IDEs such as PyCharm or IntelliJ IDEA.

bonghi rosmini in lucera FG Italy.

---

lib/domains/it/itisvc.txt

Adding ITI Faccio from Vercelli - Italy
School web site https://nuke.itisvc.it

Adding ITI Faccio Vercelli - Italy

---

lib/domains/kg/tsiauca.txt

Hi, Add TSI AUCA, please
the university official website URL:  https://tsiauca.kg/
description:
https://tsiauca.kg/software_engineering_and_social_transformations
courses:
https://ecourse.auca.kg/enrol/index.php?id=6706
https://ecourse.auca.kg/enrol/index.php?id=6704
https://ecourse.auca.kg/enrol/index.php?id=6683
https://ecourse.auca.kg/enrol/index.php?id=6752
https://ecourse.auca.kg/enrol/index.php?id=6707
https://ecourse.auca.kg/enrol/index.php?id=6737
https://ecourse.auca.kg/enrol/index.php?id=6741
https://ecourse.auca.kg/enrol/index.php?id=6742
but you cannot to see full course, because you need enrollment key and of NDA issues

Added TSI AUCA

---

lib/domains/nz/ac/twoa/akonga.txt

Added akonga.txt file to support student domain of Te Wananga o Aotearoa.

Add Te Wananga o Aotearoa (akonga.twoa.ac.nz)

---

lib/domains/edu/iilm.txt

Adding the domain iilm.edu for IILM University, Greater Noida.

Add IILM University

---

lib/domains/id/ac/stikomyos/student.txt

Menambahkan domain stikomyos.ac.id ke dalam daftar institusi pendidikan untuk mendukung permintaan lisensi pelajar JetBrains.

Add Sekolah Tinggi Ilmu Komputer Yos Sudarso

---

lib/domains/bd/edu/gonouniversity.txt

Added the official university domain gonouniversity.edu.bd to support student verification for JetBrains educational license. The domain belongs to Gono Bishwabidyalay, and the official website for reference is: https://gonouniversity.edu.bd

Add gono university domain for JetBrains verification

---

lib/domains/it/unibo.txt

add unibo.it domain (University of Bologna - italy)

university of bologna unibo.it domain

---

lib/domains/ch/zh/edu.txt

The @stud.edu.zh.ch domain, which is assigned to our students, is already in your list of domains. The present commit adds the domains without "stud", which are used by educators, see https://www.kzn.ch/personen/lehrpersonen

Add @edu.zh.ch

---

lib/domains/cn/tsinglan.txt
lib/domains/org/tsinglan.txt

Tsinglan School recently changed its official email domain to tsinglan.org.
Official Website URL: https://www.tsinglan.cn/
other proof:
The ‘Email' on the bottom navigator has already switched to @tsinglan.org, and all the contact emails on the website have already changed.

Move tsinglan.txt to org

---

lib/domains/ar/edu/udc.txt

Agregar dominio `udc.edu.ar` correspondiente a la Universidad del Chubut.
- 🌐 Sitio web oficial: https://udc.edu.ar/
- 📚 Curso relacionado con IT: Tecnicatura Universitaria en Desarrollo de Software
- https://udc.edu.ar/carreras/desarrollo-de-software/
- 📧 Confirmación del dominio: El sitio oficial usa el dominio `udc.edu.ar` y los correos institucionales también (ej: contacto@udc.edu.ar)
Nombre en el archivo: Universidad del Chubut

Adding udc.edu.ar

---

lib/domains/net/escolasobidos/alunos.txt

Adding the domain alunos.escolasobidos.net for Escola Básica e Secundária Josefa de Óbidos.
- Official website: https://escolasdobidos.com/website/
- The school offers long-term courses including IT-related subjects.
- The domain is used officially for student emails.
Thank you for reviewing!

 Add alunos.escolasobidos.net domain for JetBrains student licenses

---

lib/domains/vn/edu/lqd.txt

Our school, Le Quy Don High School for the Gifted Students in Vietnam, uses the custom domain "@lqd.email" to assign emails to students and staff. This file includes the official name of the school in both Vietnamese and English.

Add Le Quy Don High School for the Gifted Students

---

lib/domains/mx/edu/itparral.txt
lib/domains/mx/tecnm/parral.txt

Hello, In my previous request, I was informed that the domain parral.tecnm.mx had been removed from the trusted list due to past abuse, and that technical details about the vulnerability could be shared only with authorized university representatives so it could be resolved.
I am an authorized technical representative of a TecNM campus Parral. Although I have limited local control over parral.tecnm.mx, I do manage the domain itparral.edu.mx directly. We are currently working on enabling parral.tecnm.mx alongside itparral.edu.mx, but the process for parral.tecnm.mx is handled at a higher, non-local level.
To ensure our students can continue to benefit from JetBrains educational licenses while the main domain issue is addressed, would it be possible to register itparral.edu.mx as a trusted …

itparral.edu.mx domain

---

lib/domains/net/ueg-leer.txt

The school's website can be accessed at [www.ueg-leer.de](http://www.ueg-leer.de/). The email addresses of students and teachers are under the domain ueg-leer.net, as the school platform “IServ” is operated under this domain.
Here is proof (in German) that the domain ueg-leer.net is used by the school: https://www.ueg-leer.de/?view=article&id=1613:fragen-zu-iserv&catid=117

Add Ubbo-Emmius-Gymnasium

---

lib/domains/ch/wksbildung.txt

This pull request adds the domain **`wksbildung.ch`** to the repository so that students and staff of **Verein Wirtschafts- und Kaderschule KV Bern (Association for Business and Management Training Commercial Association Bern)** can be recognized for academic licensing.
* Added file: `lib/domains/ch/wksbildung.txt`
* Content includes the full name of the institution in German and English.
I would like to use JetBrains educational licenses, but the **`wksbildung.ch`** domain is not yet listed in the repo. Adding this domain will enable JetBrains products for students and staff of WKS Bildung.

Added wksbildung.ch domain.

---

lib/domains/id/ac/uqgresik/mhs.txt

Universitas Qomaruddin Gresik, it's located in Gresik, East Java, Indonesia

Add Universitas Qomaruddin Gresik

---

lib/domains/nl/sagadriehuis.txt

This PR adds the domain `sagadriehuis.nl` for Saga Driehuis (Netherlands).
Students with emails under this domain (e.g., [marijn.hendriks@sagadriehuis.nl](mailto:marijn.hendriks@sagadriehuis.nl)) should be eligible for JetBrains student licenses.
School Name: Saga Driehuis
Country: Netherlands
Website: https://www.sagadriehuis.nl/

Add Saga Driehuis

---

lib/domains/in/edu/rishihood/nst.txt

This PR adds the domain `nst.rishihood.edu.in` for Newton School of Technology, Rishihood University (India).
Students with emails under this domain (e.g., kammati.a23csai@nst.rishihood.edu.in) should be eligible for JetBrains student licenses.
School Name: Newton School of Technology, Rishihood University
Country: India
Website: https://www.rishihood.edu.in

Add Newton School of Technology, Rishihood University

---

lib/domains/in/edu/kmit.txt

My college's name was not a part of the JetBrains' education doamins. So here I am adding the domain for my college ending with **kmit.edu.in**

Adding KMIT domain

---

lib/domains/uk/ac/hruc.txt

Added the Harrow, Richmond and Uxbridge College Domains (HRUC)
https://www.hruc.ac.uk/

Added the HRUC colleges

---

lib/domains/ph/edu/stcecilia.txt
lib/domains/ph/edu/stecilia.txt

This pull request adds the stcecilia.edu.ph domain for St. Cecilia's College - Cebu.
The previous request had a typo (stecilia.edu.ph).
Please approve so students can apply for JetBrains Student Licenses using their @stcecilia.edu.ph emails.

Add stcecilia.edu.ph domain for St. Cecilia's College - Cebu

---

lib/domains/bd/ac/jstu.txt

Jamalpur Science and Technology University (Bengali: জামালপুর বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়) is a government financed public university of Bangladesh. It was established on 28 November 2017 by the Act No. 24 of 2017 as the 44th public university of Bangladesh. Later it was renamed in 2024 as Jamalpur Science and Technology University. 
Current Website: https://jstu.ac.bd/
Wikipedia: https://en.wikipedia.org/wiki/Jamalpur_Science_and_Technology_University
Current Domain: jstu.ac.bd
Previous Name: Bangamata Sheikh Fojilatunnesa Mujib Science & Technology University
Previous Website: https://bsfmstu.ac.bd
Previous Domain: bsfmstu.ac.bd
* **Official website URL:** https://jstu.ac.bd/
* **Street address (including city & country):** Melandaha, Jamalpur-2012, Bangladesh …

Added Jamalpur Science & Technology University , Bangladesh

---

lib/domains/in/edu/vce.txt

This pull request adds the domain vce.ac.in.
Official website: https://www.vce.ac.in
A page with long-term IT-related courses: https://vce.ac.in/departments/cse/about-cse-department.php
(This page lists B.Tech courses including Computer Science programs.)
Proof that this domain is officially recognized by the college:

Add domain vce.ac.in for Vasavi College of Engineering

---

lib/domains/id/ac/umpo.txt

This PR adds the domain umpo.ac.id to the list of supported domains used for JetBrains student license verification.
For an information Universitas Muhammadiyah Ponorogo (UMPO) is a private Islamic university located in Ponorogo, East Java. It has 7 faculties and around 24 study programs (from Diploma through Postgraduate).

feat: add unversity of muhammadiyah ponorogo domain

---

lib/domains/jp/ac/teu/edu.txt

Add domain edu.teu.ac.jp for Tokyo University of Technology
official website : https://www.teu.ac.jp/english/index.html

add domain edu.teu.ac.jp

---

lib/domains/in/edu/pestrust.txt

This pull request adds the @pestrust.edu.in domain so that students and staff of PES Modern College of Engineering can request free educational licenses for JetBrains tools.

Add PES Trust pedtrust.edu.in domain for educational JetBrains licenses

---

lib/domains/pl/edu/po.txt

Adding the _**po.edu.pl**_ domain, so lecturers at Opole University of Technology can benefit from using the JetBrains products:
- [The university official website URL](https://po.edu.pl/?lang=en)
- [Faculty of Computer Science](https://wi.po.edu.pl/)
- [An email that uses the domain added with this PR](https://po.edu.pl/pracownicy/salama-hassona/)

Adding po.edu.pl domain

---

lib/domains/abused.txt
lib/domains/th/ac/mahidol.txt

Mahidol University has two domain names currently: mahidol.edu and mahidol.ac.th. New staff will only have mahidol.ac.th as this comes with the new email systems. Blocking this domain will block access for new staff.

Add mahidol.ac.th back to trusted list

---

lib/domains/tw/edu/ntsu.txt

This PR adds the domain for National Taiwan Sport University (ntsu.edu.tw) 
to the JetBrains swot repository for student verification.
Official website: https://www.ntsu.edu.tw/
The domain corresponds to the school's official email system and is valid for student verification.
Thank you for your time and review!

Add National Taiwan Sport University (ntsu.edu.tw) domain

---

lib/domains/jp/ac/isct.txt

- Official website URL: https://www.isct.ac.jp/en
- a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: https://educ.titech.ac.jp/is/eng/
- a URL of a page showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students: https://portal.isct.ac.jp/en/sys/gmail/

Add Institute of Science Tokyo

---

lib/domains/uk/ac/bedford.txt

Domain for Bedford College Group

bedford.ac.uk
