lib/domains/ch/regentschool.txt
add regentschool.ch
website : www.regentschool.ch
=> Add Regentschool.ch

ac-arcus.txt, lib/domains/eu/ac-arcus.txt
=> For ac-arcus

lib/domains/cn/edu/xpu.txt
Xi’an Polytechnic University 西安工程大学
School official website: https://en.xpu.edu.cn/
The website of computer Science: https://jsjxy.xpu.edu.cn/English.htm
The website of the mail system: https://mail.xpu.edu.cn/
=> add xpu.txt

lib/domains/cat/ilg.txt
Official site: https://www.inslaguineueta.cat/
=> Added Institut La Guinaueta

lib/domains/ec/edu/tecsu.txt
=> Add tecnologico sudamericano

lib/domains/net/cvsd.txt
=> Added CVSD to the list

lib/domains/br/edu/souclaretiano.txt
Add student e-mail domain souclaretiano.edu.br.
Homepage: claretiano.edu.br
=> Add souclaretiano.edu.br

lib/domains/schule/nrw/ema.txt
=> Add Ernst Moritz Arndt Gymnasium Bonn

lib/domains/br/gov/inmetro.txt
Inmetro is a Brazilian national institute that offers [Metrology](https://www.gov.br/pt-br/servicos/candidatar-se-ao-processo-seletivo-para-a-pos-graduacao-em-metrologia-e-qualidade-mestrado-profissional) and [Biotechnology ](https://www.gov.br/inmetro/pt-br/centrais-de-conteudo/noticias/inscricoes-abertas-para-os-cursos-de-pos-graduacao-em-biotecnologia) Pos-Graduate programs. Both  programs have strong foundations in computer science, where one of the focuses of the programs is to develop solutions for Industry 4.0 . In addition, Inmetro offers a [Technical Course in Cyber Security](https://www.gov.br/inmetro/pt-br/assuntos/ensino-e-pesquisa/ensino-tecnico/curso-de-seguranca-cibernetica) whose general objective is to train professionals in Information Technology, with the ability to …
=> Add inmetro.gov.br to the list of domains

lib/domains/com/risewpu.txt
Official Website -https://mitwpu.edu.in/ , Courses Url - https://admissions.mitwpu.edu.in/
Attachment shows the email being used with domain.
=>  Official Website -https://mitwpu.edu.in/ , Courses Url - https://admissions.mitwpu.edu.in/

lib/domains/dk/slagelse-gym.txt
Collage Campus Slagelse [https://www.slagelse-gym.dk/](https://www.slagelse-gym.dk/)
=> Collage Campus Slagelse

lib/domains/it/edu/iisscalamandrei.txt
Add i.i.s.s Calamandrei school to JetBrains
=> Add i.i.s.s Calamandrei school to JetBrains 

lib/domains/br/edu/ufj.txt
- https://ufj.edu.br -> https://portalufj.jatai.ufg.br
- https://computacao.jatai.ufg.br/
- https://portalufj.jatai.ufg.br/n/139109-e-mail-institucional-da-ufj-ja-esta-em-funcionamento
=> add UFJ domain

lib/domains/ca/qc/grasset.txt
https://www.institut-grasset.qc.ca/
=> Added Institut Grasset

lib/domains/ua/edu/iir.txt
Added Institute of International Relations Kyiv
=> add iir.edu.ua to domain list

lib/domains/ng/edu/uniabuja.txt
school website: https://uniabuja.edu.ng
=> add The University of Abuja

lib/domains/br/edu/faculdadefama.txt
Register Faculdade Metropolina de Anapolis.
=> Register Faculdade Metropolitana de Anapolis

lib/domains/cz/ssphzuh.txt
https://www.ssphzuh.cz/obory-vzdelani/elektrotechnika
https://www.ssphzuh.cz/about-school
=> add domain ssphzuh.cz

lib/domains/ca/rmc-cmr.txt
Add additional domain for Royal Military College of Canada.
=> Add additional domain for RMCC

lib/domains/com/aditanarcollege.txt
Added the Aditanar College Arts and Science, Tuticorin, Tamil Nadu, India
=> Added the Aditanar College

lib/domains/cn/ac/cea-igp.txt, lib/domains/tw/edu/tajen/student.txt
中国地震局地球物理研究所
Institute of Geophysics, China Earthquake Administration (IGPCEA for short)
https://www.cea-igp.ac.cn/
[tyx@cea-igp.ac.cn](mailto:tyx@cea-igp.ac.cn)
---
The Institute of Geophysics, China Earthquake Administration (IGPCEA for short) is a national scientific research institution of public welfare with a 70-year glorious history. IGPCEA was formerly known as the Institute of Geophysics of Chinese Academy of Sciences, and was transferred to the China Seismological Bureau (later renamed China Earthquake Administration) in 1971. Since this integration, IGPCEA has been one of the most …
=> Add CEA-IGP

lib/domains/do/edu/centroeducativoinvironda.txt
Centro Educativo Invi-Ronda
https://centroeducativoinvironda.edu.do
[diogenespolanco@centroeducativoinvironda.edu.do](mailto:diogenespolanco@centroeducativoinvironda.edu.do)
=> Add Centro Educativo Invironda

lib/domains/vn/edu/wass.txt
Add WASS education 
Our Web: [wass.edu.vn](http://wass.edu.vn/)
=> Add WASS School

lib/domains/org/bishopireton.txt
=> Add Bishop Ireton High School

lib/domains/cz/4zsmb.txt
Website of school: https://www.4zsmb.cz/
=> 4 ZŠ T.G.Masaryka and MŠ Mladá Boleslav Request

lib/domains/ec/edu/uisrael.txt
Hi, i am adding domain with the follow details:
Name in Spanish: Universidad Israel
Name in English: Israel University
Country: Ecuador
City: Quito
Web Site URL: https://www.uisrael.edu.ec
MyEmail:e1711445773@uisrael.edu.ec
My Rol : Student
=> Adding domanin of Universidad Israel

lib/domains/br/edu/ufob.txt
Universidade Federal do Oeste da Bahia:
URL: https://ufob.edu.br/
STEM URL: https://ufob.edu.br/pesquisa/cti
Financial and governance URL, including public open documents URL: https://ufob.edu.br/a-ufob/transparencia-e-prestacao-de-contas/
Electrical Engineering Course URL: https://ufob.edu.br/ensino/graduacao/engenharia-eletrica
Thanks in advance.
=> added UFOB

lib/domains/id/ac/stmik-mi.txt
=> Add STMIK Mardira Indonesia Domain

lib/domains/id/ac/unis.txt
Please add this domain [unis.ac.id](https://unis.ac.id).
Universitas Islam Syekh Yusuf Tangerang.
Thanks.
=> Add Universitas Islam Syekh Yusuf Tangerang

lib/domains/mu/ac/mdx.txt
**Website**
https://www.middlesex.mu/
**Technology related course:**
https://www.middlesex.mu/courses/undergraduate/bsc-honours-information-technology
**To check Email:**
https://www.middlesex.mu/get-in-touch/mdx-mauritius-virtual-connect
Click on your application button
=> Adding MDX to Domains

lib/domains/us/ny/k12/csh.txt
Website: https://www.csh.k12.ny.us/
=> Added Cold Spring Harbor

lib/domains/cz/gymzn.txt
=> Add Gymnázium Dr. Karla Polesného

lib/domains/fr/labom2iformation.txt
Added m2iformation school to JetBrains to get intellij ultimate for learning
=> m2iformation

lib/domains/cl/estudiantesunap.txt
https://www.unap.cl/
https://www.admisionunap.cl/pregrado/iquique/ingenieria-civil-en-computacion-e-informatica
=> add domain estudiantesunap

lib/domains/org/brunswicksd.txt
Maine High School with multiple courses in programming, namely Computer Programming in Python and AP Computer Programming in Java.
https://brunswicksd.org
=> Brunswick High School

lib/domains/cl/ipleones/alumnos.txt, lib/domains/cl/ipleones/docentes.txt
=> Accounts for Students and Teachers.

lib/domains/be/inda/student.txt
**The website url:** https://inda.be
**A proof that student.inda.be is the domain name for student emails:** https://inda.be/actu/adresse-mail-eleve#:~:text=Tous%20nos%20%C3%A9tudiants%20recevront%20une,est%20joint%20%C3%A0%20ce%20courrier.
_(the site is in french)_
=> Add student.inda.be domain

lib/domains/edu/bcm.txt
Please help us add domain bcm.edu for Baylor College of Medicine
Official website URL: https://www.bcm.edu
Graduate School Currilum: https://www.bcm.edu/education/graduate-school-of-biomedical-sciences/curriculum
Courses list (Page 13, QUANTITATIVE & COMPUTATIONAL BIOSCIENCES, Graduate School Bulletin.pdf): https://bcm.app.box.com/s/chuvlsowfvft8d2p6ja1nnosghi6rqf7
Proof that BCM recognize .bcm.edu as its official domain for the enrolled students
=> Create bcm.txt for adding domain bcm.edu 

lib/domains/ca/yorkhouse.txt
Thank you for adding our school.
=> York House School

lib/domains/fr/esiea/et.txt, lib/domains/fr/intechinfo/et.txt
Official website for INTECH INFO school: https://www.intechinfo.fr/
Officiel website for ESIEA school: https://www.esiea.fr/
INTECH INFO long term IT related course: https://www.intechinfo.fr/formation-informatique/cycle-m-expert-informatique/
ESIEA long term IT related course: https://www.esiea.fr/formations/diplome-dingenieur/
Proof showing that the university recognizes the domain:
=> Add INTECH and ESIEA schools

lib/domains/org/scls-sh.txt
SCLS is short for Shanghai Soong Ching Ling School.
=> add scls domain

lib/domains/de/privatgymnasium-weinheim.txt
Adds Privatgymnasium Weinheim which has a strong and profound concept on IT learning and learning with technical devices
=> Add Privatgymnasium Weinheim

lib/domains/vn/edu/lttc.txt
=> TRƯỜNG CAO ĐẲNG LÝ TỰ TRỌNG TP. HỒ CHÍ MINH

lib/domains/id/ac/stmik-tasikmalaya.txt
--> https://stmik-tasikmalaya.ac.id/new/
--> https://drive.google.com/file/d/11O51Zo3EiF755USTgf-5DWfx8N1uE--C/view?usp=sharing
=> add stmik tasikmalaya

lib/domains/au/edu/sydney/uni.txt
=> add new domain extension for university of Sydney

lib/domains/it/itsincom.txt
Foundation website: https://itsincom.it/ and [courses list](https://itsincom.it/corsi/)
Proof of student email domain:
[proof.pdf](https://github.com/JetBrains/swot/files/8490751/proof.pdf)
Fixed after mistake in #13980
=> Add ITS Incom - Busto Arsizio (Varese), Italy

lib/domains/uk/ac/glyndwr.txt, lib/domains/uk/ac/glyndwr/mail.txt
Wrexham Glyndwr University
[{Wrexham Glyndwr University}](https://glyndwr.ac.uk/)
Computer Science degrees - https://glyndwr.ac.uk/courses/undergraduate-courses/computer-science/
=> Added Wrexham Glyndwr University.

lib/domains/dz/centre-univ-mila.txt
Here is the official website of the university 
http://www.centre-univ-mila.dz/?lang=en
=> adding Centre univ de Mila

lib/domains/at/schottengymnasium.txt
Schottengymnasium der Benediktiner in Wien
https://www.schotten.wien/schottengymnasium/
https://www.schotten.wien/informatik/
=> Add Schottengymnasium

lib/domains/uk/ac/northumbria.txt
https://www.northumbria.ac.uk/
Emails that match the `...@northumbria.ac.uk` can be found in:
https://www.northumbria.ac.uk/study-at-northumbria/courses/computer-science-bsc-ft-uuscsi1/
=> Add Northumbria University

lib/domains/uk/ac/bathspa.txt
University website: https://www.bathspa.ac.uk
Page evidencing bathspa.ac.uk domain for email addresses: https://www.bathspa.ac.uk/about-us/contact/
Example of an IT related course that lasts over 1 year: https://www.bathspa.ac.uk/courses/ug-creative-computing/
=> Add Bath Spa University

lib/domains/ng/edu/fcepankshin.txt
=> Add fcepankshin to institution list

lib/domains/de/bbz-rd-eck/sus.txt
BBZ Berufsbildungszentrum Rendsburg-Eckernförde
For easier translation: This is a german school.
It offers both higher education and apprenticeships.
URL to the homepage:
https://www.bbz-rd-eck.de/
URL to the IT education
https://www.bbz-rd-eck.de/bildungsangebote/duale-ausbildung/it-berufe/
(Fachinformatiker für Anwendungsentwicklung = Application development)
Proof of the E-Mail for the top-level:
https://www.bbz-rd-eck.de/online-sekretariat/schulbuero/
(Kontaktdaten = Contact information)
I can't really find a proof for the "sus" (Schülerinnen und Schüler = Pupils). But it's used to seperate students from staff or teachers. As a last effort i will add a screenshot of my Microsoft Teams account from this institute.
=> feat: Added school

lib/domains/uk/ac/sheffield.txt
Website: www.sheffield.ac.uk
Email: @sheffield.ac.uk
Institution: Major (Russell Group of 24 top universities) UK University with 28,000 students. Offers research, undergraduate and postgraduate courses.
=> Add sheffield.ac.uk (The University of Sheffield)

lib/domains/de/gymnasium-frechen.txt
My schools website is: https://www.gymnasium-frechen.de/
Our computer science course is here: https://www.gymnasium-frechen.de/wp-content/uploads/2018/04/Informatik.pdf
Our school emails end with: @gymnasium-frechen.de
If there is anything else I can help with, please contact me
=> Added file

lib/domains/tr/k12/aci/my.txt
The school website: https://www.aci.k12.tr
School email prefix: `*@my.aci.k12.tr`
=> Submit 'American Collegiate Institute'

lib/domains/br/edu/bahiana.txt
Escola Bahiana de Medicina e Saúde Pública
Bahiana School of Medicine and Public Health
=> added bahiana.edu.br

lib/domains/com/onmicrosoft/balticinstitute.txt
Added my school's details to the GitHub repository.
=> Created balticinstitute.txt

lib/domains/lk/edu/icbtcampus/student.txt
ICBT Kandy Campus Sri Lanka 
icbt.lk
icbtsis.lk
=> ICBT Kandy Campus Sri Lanka 

lib/domains/cz/labyrinthschool.txt
Add Labrinthschool to the schools list
=> Labyrinthschool submission

lib/domains/br/edu/camporeal.txt
Campo Real University
https://camporeal.edu.br
=> Add Campo Real University

lib/domains/org/stjohnshigh.txt
Main URL : www.stjohnshigh.org
URL to course listings: https://www.stjohnshigh.org/curriculum-detail?fromId=177604&LevelNum=1163&DepartmentId=20961
=> Add St Johns High School file

lib/domains/org/morrishs.txt
Website: https://www.morrishs.org/
=> Add Morris Community High School

lib/domains/uk/ac/lancaster.txt
Requesting to add Lancaster University to the repository
- [University Website](https://www.lancaster.ac.uk/)
- [Software Engineering @ Lancaster University](https://www.lancaster.ac.uk/study/undergraduate/courses/software-engineering-bsc-hons-g602/)
- [University Email Formats](https://answers.lancaster.ac.uk/display/ISS/IT+accounts+help) - Please see the final entry in the table "_Username formats for different services_"
=> Add Lancaster University

lib/domains/com/oxcoll.txt
I am a student at Oxford International College. Could you add it to the Student License listings, please? Thank you.
https://www.oxcoll.com/
=> Oxford International College

lib/domains/tr/edu/ankarabilim.txt
University name isAnkara Science University
Site is https://international.ankarabilim.edu.tr/
[file.zip](https://github.com/JetBrains/swot/files/8577635/file.zip)
=> University add request

lib/domains/uy/edu/anima.txt
=> Added Anima - Technological Baccalaureate to swot

lib/domains/com/hamidaligirlsintercollege.txt
The URL of the school is - http://hamidaligirlsintercollege.com
They teach web development to class 9-10 students in PHP as a part of teaching computer science. A community edition of PHP Strom would work but then it is not available. It will be great to get the license for PhpStorm
=> http://hamidaligirlsintercollege.com/edu/about.html

lib/domains/tw/edu/wzu/student.txt
Added Wenzao Ursuline University
=> Added Wenzao Ursuline University

lib/domains/pl/edu/zstie.txt
Official website: https://zstie.edu.pl/
Email: [uczen-dandrzejewski@zstie.edu.pl](mailto:uczen-dandrzejewski@zstie.edu.pl)
Name of the school: Zespół Szkół Teleinformatycznych i Elektronicznych we Wrocławiu [Technical High School nr 7 in Wroclaw, Poland]
=> Add zstie.edu.pl [ZSTIE]

lib/domains/br/edu/cefsa/faculdade.txt
official website URL: http://faculdadesalvadorarena.org.br/
long-term IT course: http://faculdadesalvadorarena.org.br/cursos/engenharia-de-computacao/
URL of domain: https://aluno.cefsa.edu.br/ or http://webmail.cefsa.edu.br/
=> Add Faculdade Salvador Arena

lib/domains/uk/ac/bolton.txt
Website: https://www.bolton.ac.uk/
=> Add University of Bolton

lib/domains/ua/kiev/ktgg.txt
Website: https://ktgg.kiev.ua/uk/
=> Add college KTGG 

lib/domains/uk/ac/bradford.txt
Adding the University of Bradford email domain to the list
=> Added bradford.txt for the University of Bradford domain

lib/domains/br/edu/ifrs/osorio.txt
We added IFRS Osório to list of domains.
=> Added IFRS Osório to list

lib/domains/eu/gikn.txt
This is a private high-school which focuses on IT and Computer Science. It's located in Plovdiv, Bulgaria. It offers Programming, Artificial Intelligence and Graphic Design as its main profiles for students to choose from. Studying involving IT and Computer Science happens over a period of 4 years. It mainly focuses on C++, C#, HTML & CSS, Javascript. SQL, MongoDB and a few other.
Website of the school: https://gikn.eu/
Note: Website is only available in the native language - Bulgarian
=> Add school CHPGIKN Academic Blagovest Sendov

lib/domains/de/evb-gymnasium.txt
**Official name of school:** 
Städtisches Engelbert-von-Berg-Gymnasium
**Website:** 
https://evb-gymnasium.de/
**Email domain name can be seen on:** 
[https://evb-gymnasium.de/index.php/impresssummenue](https://evb-gymnasium.de/index.php/impresssummenue) or [https://evb-gymnasium.de/index.php/wir-ueber-uns/kontaktmenue](https://evb-gymnasium.de/index.php/wir-ueber-uns/kontaktmenue)
=> Add Engelbert-von-Berg-Gymnasium

lib/domains/com/lawrencesheriffschool.txt
email domain is @lawrencesheriffschool.com
=> Add lawrence sheriff school

lib/domains/net/mgschools.txt
[School Website](https://www.mononagrove.org/mghs/)<br />
[Course Handbook](https://docs.google.com/document/d/1exr-Nok6yNVxtl-L5R0b0hgy0i_yFol57D3EMgneFFY/edit) (Go to page 13, or search for `Computer Science`)<br />
=> Added Monona Grove Highschool

lib/domains/jp/kosen-ac/kushiro.txt
College Website: https://www.kushiro-ct.ac.jp/
IT-related courses offered by National Institute of Technology, Kushiro College: [Information Enginnering field (情報工学分野)](https://www.kushiro-ct.ac.jp/sstudy/div-info/)
The document certifying that college owns kushiro.kosen-ac.jp: [2_MFA導入説明(Authenticator).pdf](https://github.com/JetBrains/swot/files/8608842/2_MFA.Authenticator.pdf)
The above PDF file explains to students how to set up multi-factor authentication in Office365. An example of a student's email address can be found on page 4.
=> Add National Institute of Technology, Kushiro College

lib/domains/cn/ac/cigit.txt
Add Chongqing Institute of Green and Intelligent Technology, Chinese Academy of Sciences
=> Add CIGIT, Chinese Academy of Sciences

lib/domains/as/ais, lib/domains/net/aisschool.txt
Official Website: https://aisch.ae/
School Email Domain: info@aisschool.net
the school street address, including city and country: PO Box 87727 6th Street, Al Qusais 1, Dubai United Arab Emirates
Thank you!
=> Add AIS, American International School

lib/domains/au/edu/catholic/rokstu.txt
I hope I am doing this right, never done it before.
The email addresses go *@rokstu.catholic.edu.au
Here is the link to their website: https://www.rok.catholic.edu.au/
=> Add catholic education rockhampton diocese

lib/domains/org/pearlandisd.txt, pearlandisd.txt
AP Computer Science Class: https://www.pearlandisd.org/Page/19550
=> Jayden Lu- Glenda Dawson High School

lib/domains/com/onmicrosoft/sgxanten.txt
The school's website is http://www.ssgxanten.de and the emails are _xy_@sgxanten.onmicrosoft.com (yes, with one `s` less than the website)
It offers IT classes from grade 10 to grade 12 (see here http://www.ssgxanten.de/service-infos/infos/oberstufe/).
=> Created sgxanten.txt

lib/domains/cz/jaroska.txt
=> add jaroska.cz

lib/domains/id/ac/politanipyk.txt
Dear JetBrains 
thanks for Free Educational Licenses
website [politanipyk.ac.id](https://politanipyk.ac.id/)
=> add politanipyk

lib/domains/it/sssrome.txt
The school has an iLab that includes development as a part of the curriculum. A Python class is offered for first- and second-year students. The school site that showcases the Ilab is: https://sssrome.it/flagship-programs and you can confirm that this is the institution's official email because the accrediting agencies show that this is the website of the school. you can check that on: https://councilofinternationalschools.secure.force.com/Map/exmapanythingSchoolInfo?Id=0010Y00000bHE4LQAW
=> St Stephens School Rome Request

lib/domains/org/alastudents.txt
https://www.africanleadershipacademy.org/
add African Leadership Academy (pre-university with CS course) in johannesburg.
this request is for student's domain (alastudents) which is different from teachers'.
=> add students' domain for African Leadership Academy

lib/domains/si/spletni-studij.txt
https://www.b2.eu/en/vocational-college/about-the-school
=> Added B2 Vocational school

lib/domains/vn/edu/daihocthudo.txt
Xin vui lòng, thêm trường của tôi, Cảm ơn bạn.
Hanoi Metropolitan University (HNMU)
=> add Hanoi metropolitan university

lib/domains/co/edu/usta.txt, lib/domains/co/edu/ustabuca.txt
Universidad Santo Tomas
Santo Tomas University
Website: http://www.ustabuca.edu.co/
=> feat(university): add university ustabuca

lib/domains/uk/ac/ebi.txt
as told to do by the jetbrains website when applying for an educational license
=> added the ebi to the directory of .ac.uk domains

lib/domains/org/cmseducation.txt, lib/domains/org/cmselearning.txt
Info:
`cmseducation.org`: For staff
`cmselearning.org`: For students
For confirmation (`cmselearning.org`):
https://students.cmsitportal.org/Login.aspx: Requires login from a `cmselearning.org` e-mail ID (and it can be confirmed that `cmsitportal.org` is a part of the CMS organization because there are `cmseducation.org` e-mail IDs in its "Contact Us" section (https://www.cmsitportal.org/contactus)
=> Adding City Montessori School to the list

lib/domains/pl/edu/elodz/lo25.txt
Proof that this domain is recognized by the school: https://25lo.pl/strona/kontakt
=> Add XXV LO High School in Łódź

lib/domains/org/sbs.txt
Thank you so much for providing this program.
The website of my School is: https://sbs.org
It is a High School in Stony Brook, Long Island, NY, USA.
=> Add The Stony Brook School to the list

lib/domains/th/ac/pim.txt
=> add pim.ac.th

lib/domains/com/voxelschool.txt
This is and digital arts school (3D, videogames, web, design, animation)
Located close to the center of [Madrid](https://g.page/EscuelaVoxel?share) with modern installations.
Useful Jetbrains tools:
- Pycharm; 3D scripting Maya
- WebStorm, Web and web design
- Rider, Unity C# programing
[https://voxelschool.com/](https://voxelschool.com/#)
=> Add Voxel School to the directory

lib/domains/uk/ac/st-andrews.txt
I add the University of St Andrews into the list, which is an univeristy in UK
=> add University of St Andrews into the list

lib/domains/de/weg-schwabach.txt
Wolfram-von-Eschenbach-Gymnasium Schwabach
[https://www.weg-schwabach.de/](url)
=> Added weg-schwabach.de

lib/domains/info/glenrosetigers.txt
Official Website:
* http://www.grisd.net/
---
IT Related Course:
* http://www.grisd.net/campuses/glen-rose-high-school/grhs-campus-life/grhs-stem-academy/
* https://imgur.com/a/2OGbwTq
---
University recognizes email:
* http://www.grisd.net/namaste-course/canvas-and-google-assignments-lti-1-3-2022/
* https://imgur.com/ysHhCgO
=> Add glenrosetigers.info domain

lib/domains/eu/hbbk.txt
Hi JetBrains team,
Please grant access for my university domain.
Thanks so much!
=> Adding my university domain for license registration

lib/domains/com/onmicrosoft/esstu.txt
Website:
https://esstu.ru
Proof(instruction):
https://esstu.ru/uportal/document/view.htm?documentId=24244&departmentId=75
=> Added East Siberia State University of Technology and Management mail domain

lib/domains/net/ckziu/uczen.txt
Hi!
I (and my schoolmates) would be very glad if our school could get access to your tools.
Thanks in advance and wish a good day.
=> Adding my school domain for license registration

lib/domains/ec/edu/uide.txt
=> Add UIDE domain

lib/domains/ge/edu/alte.txt
https://alte.edu.ge/
Georgia, Tbilisi, University St. N2 ZIP: 0177
https://alte.edu.ge/storage/files/192-angular-in-depth.pdf
=> Add email domain for Alte University

lib/domains/uk/co/aesessex.txt
Anglo European School, Ingatestone, Essex, UK
https://www.aesessex.co.uk/
https://www.aesessex.co.uk/curriculum/technology/digital-comms/
https://www.aesessex.co.uk/wp-content/uploads/2021/05/Media-Studies-Year-11.pdf (a gcse course that takes over 2 years to complete and we have a international baccalaureate for computer studies should you wish to partake in it)
=> Added aesessex.co.uk

lib/domains/info/mksumdu.txt
Here's a link to the college license data: https://registry.edbo.gov.ua/university/883 .
And here's the college website: https://mk.sumdu.edu.ua/ .
Not sure if that information is needed, but I hope it would be useful.
=> Added Machine building professional college of Sumy State University

lib/domains/uk/ac/blackburn/live.txt
University Homepage
https://www.blackburn.ac.uk/university/
3 Year Bsc(Hons) course (Levels 4 to 6)
https://www.blackburn.ac.uk/course/degree/software-development-bsc-hons/ST3021A21
Email Domain ownership 
https://www.blackburn.ac.uk/welcome/student-email/
=> Add Blackburn University Centre Domain - live.blackburn.ac.uk

lib/domains/br/edu/unifipmoc.txt
Centro Universitario UNIFipMoc
=> Centro Universitario UNIFipMoc

lib/domains/cn/ac/shao.txt
Add Shanghai Astronomical Observatory, Chinese Academy of Sciences
http://english.shao.cas.cn
=> Add Shanghai Astronomical Observatory

lib/domains/pl/edu/mickiewicz.txt
Official school's website: [https://mickiewicz.edu.pl/](https://mickiewicz.edu.pl/)
=> Add IV LO in Warsaw

lib/domains/org/thegraysonschool.txt
Add The Grayson School (thegraysonschool.org), a private high school for gifted students in Radnor, PA, USA.
=> Added The Grayson School (thegraysonschool.org)

lib/domains/pl/edu/uap.txt
Webpage: https://uap.edu.pl/
Course we use coding: https://uap.edu.pl/uczelnia/wydzialy/wydzial-animacji-i-intermediow/
=> Add University of the Arts Poznan

lib/domains/am/meduni.txt
=> Meduni.am added for ysmu

lib/domains/ng/edu/funai.txt
AEFUNAI Website: https://funai.edu.ng/
Faculty of Engineering and Technology: https://funai.edu.ng/sp/faculty/s/faculty-of-engineering-and-technology
https://funai.edu.ng/sp/department/s/mathematics-computer-science-statistics-informatics
=> Added Alex Ekwueme Federal University Ndufu Alike Ikwo in ng/edu domain

lib/domains/school/hei.txt
School website: https://hei.school/
School program link: https://drive.google.com/file/d/14VrAfPIkvleDNSCZExzW6oMhBLfr-sgI/view
=> Adding Haute Ecole en Informatique

lib/domains/uk/org/tmet/ivc.txt, uk/org/tmet/ivc.txt
https://www.impingtoninternational.org.uk/
https://www.impingtoninternational.org.uk/download/computer-science-2/?wpdmdl=2051&refresh=6290ebb6033961653664694
=> Impington International College

lib/domains/br/edu/uniceplac/esoftware.txt
=> I added the generated file for br.edu.uniceplac following the directory structure

lib/domains/tw/edu/hwu/mail.txt
=> Add Hsing Wu University

lib/domains/do/edu/ucateba.txt
Adding Catholic Technological University of Barahona to repository.
=> Adding new university.

lib/domains/pl/edu/3lo.txt
=> added a domain for 3lo in chorzow

lib/domains/kr/go/gne.txt
http://seokdong-m.gne.go.kr/seokdong-m/main.do
=> Add Seokdong Middle School

lib/domains/br/gov/mg/educacao.txt
Please add Secretaria de Educação de Minas Gerais to the repository.
https://www.educacao.mg.gov.br
=> Add Minas Gerais Department of Education

lib/domains/fr/cciformation49.txt
https://www.cciformation49.fr/formation/bts-services-informatiques-aux-organisations-sio-option-sisr/
=> Add CCI Formation 49

lib/domains/net/garlandisd.txt
Adding Garland ISD
Domain: https://garlandisd.net/
=> Adding GarlandISD

lib/domains/br/edu/faculdadedombosco.txt
Add faculdadedombosco.edu.br domain
[Main Site](https://faculdadedombosco.net/pt/)
=> Add faculdadedombosco.edu.br domain

lib/domains/us/ca/k12/cv.txt
Add domain for Castro Valley High School
https://cvhs.cv.k12.ca.us
=> add domain for Castro Valley High School

lib/domains/ca/sainteanne.txt
School Website: https://sainteanne.ca
=> Added Sainte-Anne

lib/domains/ve/edu/iutcm.txt
Instituto Universitario de Tecnologia Cristobal Mendoza
www.iutcm.edu.ve
=> added Iutcm.edu.ve institute

lib/domains/org/trinityschoolnyc.txt
https://www.trinityschoolnyc.org/
=> Add Trinity School NYC to JetBrains catalogue

lib/domains/de/bbs-schueler.txt
Official page: https://www.bbs-walsrode.de/
IT related courses: https://www.bbs-walsrode.de/index.php/bildungsangebot/berufliches-gymnasium/technik.html#pruefungsfaecher
Proof that @bbs-schueler.de is the domain for the email: https://www.bbs-walsrode.de/index.php/service/vertretungsplan.html
=> Added "Berufsbildende Schulen Walsrode"

lib/domains/us/fl/k12/marion.txt
Homepage: https://www.marionschools.net/marionfl
Information Technology Academy: https://www.marionschools.net/Page/52032
Early College Program: https://www.marionschools.net/domain/2860
Proof of official email: https://www.marionschools.net/domain/23414
=> Added marion.k12.fl.us

lib/domains/ma/ensam-casa.txt
Hi,
I am engineering student in National School of arts and crafts in Casablanca, Morocco.
I wish to enlist my school in the list of schools supported by Jetbrains to have access to student licences for Jetbrains products.
My school's website is: http://ensam-casa.ma
Thank you.
Kind Regards
=> Added ensam-casa.txt

lib/domains/il/k12/amalnet/ld.txt
Please add this high school in Tel Aviv
=> Add Amal Lady Davis High School in Tel Aviv

lib/domains/au/edu/qld/vnc.txt
=> Villanova College QLD AU

lib/domains/lk/kingscollege.txt, lib/domains/uk/org/eduk.txt
https://eduk.org.uk/information-technology/
https://eduk.org.uk/wp-content/uploads/eduk/information-technology/EDUK-Level-3-Diploma-in-e-commerce.pdf
https://eduk.org.uk/wp-content/uploads/eduk/information-technology/EDUK-Level-4-Diploma-in-Web-Design.pdf
https://eduk.org.uk/wp-content/uploads/eduk/information-technology/EDUK-Level-5-Diploma-in-Web-Design.pdf
https://eduk.org.uk/wp-content/uploads/eduk/EDUK-Student-Registration.pdf
=> https://eduk.org.uk/

lib/domains/cn/org/cass.txt
中国社会科学院大学（University of Chinese Academy of Social Sciences）
https://www.ucass.edu.cn/
https://se.ucass.edu.cn/info/1053/1004.htm
=> 中国社会科学院大学（University of Chinese Academy of Social Sciences）

lib/domains/id/ac/pnl.txt
Official Website: http://pnl.ac.id
=> add Politeknik Negeri Lhokseumawe by @muhdavi

lib/domains/ch/gymkirchenfeld.txt, lib/domains/ch/mygymer.txt
Official website:
https://www.gymkirchenfeld.ch/
Computer Science Courses (2 years each):
https://informatik.mygymer.ch/
Microsoft Azure screenshot showing both domains:
=> Gymnasium Kirchenfeld, Switzerland

lib/domains/br/edu/uninga.txt
https://www.uninga.br/
https://www.uninga.br/curso/engenharia-da-computacao-2/
=> Add Centro universitário Ingá - Uningá

lib/domains/org/lsf.txt
Uploaded lsf.txt to the Lib / Domains / Org - on behalf of a Foundation of schools in Leicestershire - to be able to utilise JetBrains for students and staff.
=> Add lsf.org into swot

lib/domains/uy/edu/bios.txt
Add Instituto BIOS Uruguay
https://www.biosportal.com/
https://bioselearning.com/
=> Add Instituto BIOS Uruguay

lib/domains/us/ma/k12/longmeadow.txt
https://lhs.longmeadow.k12.ma.us/
=> Add Longmeadow High 

lib/domains/cz/gym-tisnov.txt
Grammar School, Tišnov
[{Website URL}](https://www.gym-tisnov.cz/)
=> Add files via upload Grammar School, Tišnov

lib/domains/do/edu/itsc.txt
Official Website: https://www.itsc.edu.do/
Academic Offer: https://www.itsc.edu.do/index.php/academicos/
Software engineering associate degree program: https://www.itsc.edu.do/index.php/informatica/
Contact Info: https://www.itsc.edu.do/index.php/directorio/
[![2022-06-18-08-32.png](https://i.postimg.cc/Nj3Qmjyb/2022-06-18-08-32.png)](https://postimg.cc/18KxZPrN)
=> Add: Community Higher Technical Institute

lib/domains/nl/hyperionlyceum.txt
Added `hyperionlyceum.nl` (Hyperion Lyceum) to the domain library.
=> Add hyperionlyceum.nl (Hyperion Lyceum)

lib/domains/cz/oavm.txt
Website: https://www.oavm.cz/
IT: https://www.oavm.cz/obory/
=> Added oavm.cz

lib/domains/eg/edu/eaeat-academy.txt
- Website: https://www.eaeat.edu.eg/En/Default.aspx
- Study Duration: https://www.eaeat.edu.eg/En/Cu_StudyDuration.aspx
=> Add EAEAT University

lib/domains/eg/edu/ohi.txt
the university official website URL: 
https://www.ohi.edu.eg/
URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students :
https://www.ohi.edu.eg/Contactus.aspx
https://www.ohi.edu.eg/DynamicPage.aspx?id=206
=> 6 of October High Institute For Architecture Engineering

lib/domains/iq/edu/alrasheedcol.txt
=> add al-rasheed university collage

lib/domains/br/senai/estudante/go.txt
Faculty website: https://senaigoias.com.br/home
Systems Development Course > 1 year: https://senaigoias.com.br/faculdade-fatesg-curso-fatesg-graduacao
The e-mail created by the faculty can be confirmed by contacting the faculty, they have not put anything that links the e-mail to the faculty as requested. > https://senaigoias.com.br/fale-conosco
=> Senai Fatesg

lib/domains/de/igs-sassenburg.txt
https://www.igs-sassenburg.eu/
=> adding igs-sassenburg.txt

lib/domains/uk/ac/bexhillcollege.txt
Full Time A Level Computer Science Course - at Bexhill College:
https://www.bexhillcollege.ac.uk/docs2/full_courses/EyFEEEkkZFoBgRpOQn.shtml
=> Added Bexhill College

lib/domains/co/edu/unireformada.txt
Corporación Universitaria Reformada
https://www.unireformada.edu.co/
Email User
crista.vega@unireformada.edu.co
[x] Students
[x] Academic/Teaching Staff
Other/Support Staff
Alumni
[x] Graduate School
[x] College (University) or Undergraduate School or equivalent
Community College or equivalent
High School or equivalent
Elementary School or equivalent
=> Add unireformada.edu.co

lib/domains/com/onmicrosoft/zsm01.txt
school website: https://zsm1.bydgoszcz.pl/
school contact: https://zsm1.bydgoszcz.pl/strony/kontakt/
email example: name.secondname@zsm01.onmicrosoft.com
=> Zespół Szkół Mechanicznych nr 1 w Bydgoszczy

lib/domains/vn/edu/epu.txt
electric power university (Đại học điện lực)
https://epu.edu.vn/
haittcntt@epu.edu.vn
=> Add electric power university

lib/domains/de/iu-akademie.txt
Some ohter Email from the IU Internationale Hochschule GmbH are already in the repository.
The Email i have added is for persons who make a courses instead of complete Bachelor degree.
=> Added iu-akademie.txt

lib/domains/education/ukr/sc1.txt
Add Brovary #1 school (Ukraine)
=> Add Brovary #1 school (Ukraine)

lib/domains/org/deensacademy.txt, lib/domains/th/ac/siamtech.txt
Kindly request you to add Deens Academy to let the primary class students to learn C / C++
=> Please Add Deens Academy

lib/domains/br/edu/ies/aluno.txt
-  **official website URL:** https://www.ies.edu.br/index.asp
- **long term URL:** https://www.ies.edu.br/ensino/graduacao/tecnologicos/redes_computadores.asp"
=> Instituto de Ensino Superior da Grande Florianópolis

lib/domains/id/ac/pnm.txt
official website https://www.pnm.ac.id/
=> Add Politeknik Negeri Madiun

lib/domains/ae/ac/iat.txt
Creating this pull request to add the school's Institute of Applied Technology to use JetBrains software for learning purposes.
=> Adding IAT as domain for ae.ac domain

lib/domains/it/itstechtalentfactory.txt
https://www.itstechtalentfactory.it/
https://www.itstechtalentfactory.it/i-nostri-corsi/its-full-stack-developer-with-cloud-technologies/
=> Links on the comment below

lib/domains/th/ac/chula/student.txt
Add Chulalongkorn University subdomain for students
=> feat(student.chula): add Chulalongkorn subdomain

lib/domains/eg/edu/merit.txt
University official website URL:  https://www.merit.edu.eg/
=> New university: MERIT UNIVERSITY-EGYPT (MUE)

lib/domains/br/com/escoladotrabalhador40.txt
- Website Official URL: https://escoladotrabalhador40.org.br/
- Catalog of available courses: https://escoladotrabalhador40.org.br/download/catalogo-de-cursos_lista_2800422-oficial/
- A program of the Ministry of Labor and Welfare in partnership with Microsoft that prepares workers for the new challenges of the job market. The "Digital Pathway Program" aims to centralize and promote training initiatives focused on the development of digital skills and professional insertion aimed at 4.0 Economy.
- Full training is available in the form of short courses called "trails". In total there are more than 800 hours of class.
=> Website URL: https://escoladotrabalhador40.org.br/

lib/domains/school/dalet.txt
=> added dalet school

lib/domains/ca/mymhc.txt
This PR enables support for students of Medicine Hat College, Canada.
=> Add Medicine Hat College

lib/domains/net/wths.txt
=> Added wths

lib/domains/ng/edu/uniuyo.txt
Added University of Uyo, Nigeria
=> Added University of Uyo

lib/domains/id/ac/umri/student.txt
>student.txt
Universitas Muhammadiyah Riau
=> Add Students Universitas Muhammadiyah Riau

lib/domains/ug/ac/vu/students.txt
Add Victoria University Kampala
=> Add Victoria University Kampala

lib/domains/de/ruhr-gymnasium.txt
Website: https://ruhr-gymnasium.de/ (In German)
=> Add Ruhr-Gymnasium Witten

lib/domains/in/ac/apsshankarvihar.txt
Website:  https://apsshankarvihar.ac.in/
=> Add Army Public School, Shankar Vihar

lib/domains/nl/rocgilde.txt
This time without the changes to student.
=> Add Gildeopleidingen

lib/domains/de/rbbk-do.txt
=> add domain rbbk-do.de

lib/domains/th/ac/damrong.txt
School Name :  Damrongratsongkroh
School Website :  [https://www.damrong.ac.th/](https://www.damrong.ac.th/)
=> Add domain damrong.ac.th

lib/domains/hk/edu/hkmakslo.txt
Let's add a domain hkmakslo.edu.hk for shcool Hong Kong Management Association K S Lo College
=> Add domain hkmakslo.edu.hk

lib/domains/in/satiengg.txt
Samrat Ashok Technological Institute
Institution/School Website
http://www.satiengg.in/
Email Users
[x] Students
[x] College (University) or Undergraduate School or equivalent
=> Adding Samrat Ashok Technological Institute file

lib/domains/com/technischools.txt
Niepubliczne Technikum Programistyczne Techni Schools
URL:
[TechniSchools](https://technischools.com)
[Programme](https://technischools.com/szczegoly-programu/)
[Year 2021/2022](https://technischools.com/2022/06/17/zakonczenie-roku-szkolnego/)
Official domain:
technischools.com
=> Niepubliczne Technikum Programistyczne Techni Schools

lib/domains/uk/ac/abbeygatesfc.txt
Abbeygate Sixth Form College
https://www.abbeygatesfc.ac.uk/
=> Add Abbeygate Sixth Form College

lib/domains/vn/edu/vief.txt
Cộng Đồng Giáo Viên Sáng Tạo Microsoft Việt Nam
Microsoft Vietnam Creative Teachers Community (MIE)
Website: https://vief.edu.vn/
=> add: Vietnam Creative Teachers Community (MIE) 

lib/domains/do/edu/ipl.txt
Website: https://superior.ipl.edu.do
IT related career: 
** https://superior.ipl.edu.do/carreras/ingenieria-redes-y-telecomunicaciones
** https://superior.ipl.edu.do/carreras/tecnologo-en-desarrollo-de-software
Proof of the domain:
=> Added New educational center: Instituto Especializado de Estudios Superiores Loyola

lib/domains/eu/ecm-meaux.txt
=> file to add my school

lib/domains/in/edu/isquareit.txt
International Institute of Information Technology (I²IT) is a college in Pune, Maharashtra, India affiliated with Savitribai Phule Pune University. The college offers Bachelor of Engineering courses in Electronics and Telecommunication, Computer Engineering, and Information Technology.
Website: [https://www.isquareit.edu.in/](https://www.isquareit.edu.in/)
Programmes Offered: [https://www.isquareit.edu.in/programmes-offered/](https://www.isquareit.edu.in/programmes-offered/)
=> Add International Institute of Information Technology (I²IT).

lib/domains/fr/esad-valenciennes.txt
Added  "esad-valenciennes.fr" to the domain pool.
=> added esad-valenciennes.txt to fr folder

lib/domains/ro/cnvapedia.txt
"Vasile Alecsandri" National College is a high-school located in Bacău, Romania. It offers a Mathematics and Computer Science educational offer, besides other offers.
**College's Website**: https://cnva.ro/
**Educational offers**: http://cnva.ro/elevi-2/clasa-a-ix-a-metodologie-admitere/oferta-educationala_clasa-ix/
=> Uploading file cnvapedia.txt

lib/domains/ru/tsutmb.txt
Domain for Derzhavin Tambov State University was added.
=> Added Derzhavin TSU https://tsutmb.ru/

lib/domains/de/neuefische.txt
Added neuefische - School and Pool for Digital Talent
[neuefische](https://www.neuefische.de/en)
=> Added neuefische 

lib/domains/kz/apk-edu.txt
The site is slow, so you will have to wait about 9 seconds for the download
=> Aktobe High polytechnical college

lib/domains/th/ac/dkttc.txt
I would like you to add DOKKHAMTAI TECHNICAL COLLEGE
=> Create DOKKHAMTAI TECHNICAL COLLEGE

lib/domains/np/edu/prime.txt
Official Website: https://www.prime.edu.np/
Course related to computer science: https://www.prime.edu.np/bsccsit/
Official email domain of the college: https://www.prime.edu.np/contact-us/
=> Added Prime College, Affiliated to Tribhuvan University

lib/domains/fi/jarvenpaa/edu.txt
Address form firstname.lastname@edu.jarvenpaa.fi is used by all schools (primary, secondary, and higher) in Järvenpää, Finland.
=> Add schools of Järvenpää, Finland

lib/domains/uk/ac/barton.txt
Website: https://barton-peveril.ac.uk
=> Add Barton Peveril College

lib/domains/com/p4ed.txt
Poliedro curso offers preparatory courses for the most competitives universitie in Brazil, like ITA (ita.br), and IME (ime.eb.mil.br).
- Institution's official website: https://cursopoliedro.com.br/
- Link to engineering military universities preparatory courses: https://cursopoliedro.com.br/curso/ita
The mail login page is available in the right upper corner button of the official page, like an "E" button.
=> add poliedro

lib/domains/ru/top-academy.txt
1) the university official website URL, if it is different from the domain you are submitting
https://msk.top-academy.ru/
2) a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university
https://online.top-academy.ru/programmer
3) a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.
https://online.top-academy.ru/contacts
>> How to add the domain quicker
We merge pull requests manually and check the information which you have provided us with before merging it. Thus, if you wish to make the verification process easier for us and therefore much quicker, please mention the following in your comment …
=> Added top-academy.txt https://top-academy.ru/

lib/domains/br/edu/umj/academico.txt
Centro Universitário Mario Pontes Jucá - UMJ
https://umj.edu.br
*That same URL contains a proof that recognizes that the institution uses this email domain for students. (Click on the name "Mauro Tony de Lima Anjos - COLEGIADO" to display the email)*
https://umj.edu.br/engenharia-da-computacao/
mauro.anjos134@academico.umj.edu.br
=> Adding a new domain for an institution

lib/domains/uk/ac/tmc.txt
=> The Manchester College

lib/domains/ru/i-klgtu.txt
https://klgtu.ru/, https://i-klgtu.ru/
https://klgtu.ru/abitur/bachelor/
=> Add Kaliningrad State Technical University

lib/domains/au/edu/qld/tss.txt
=> The Southport School

lib/domains/bo/edu/ueb.txt
University official website: https://ueb.edu.bo/
IT related career: https://ueb.edu.bo/ingenieria-de-sistemas/
=> Universidad Evangelica Boliviana request

lib/domains/hu/kkszki.txt
School site: [https;//kkszki.hu/](https://kkszki.hu)
Long term IT related course proof: https://kkszki.hu/kepzeseink/technikum-szakkepzo/szoftverfejleszto-es-tesztelo
Proof of them recognizing the email is in the footer of the main site as their contact email is kando@kkszki.hu
```
____________________________________________________
|.==================================================,|
||  I WILL MERGE AND REVIEW PULL REQUESTS QUICKLY   ||
||  I WILL MERGE AND REVIEW PULL REQUESTS QUICKLY   ||
||  I WILL MERGE AND REVIEW PULL REQUESTS QUICKLY   ||
||  I .----.ERG,                                    ||
||   / ><   \  /                                    ||
||  |        |/\                                    ||
||   \______//\/                                    ||
||   _(____)/ / …
```
=> Adding Miskolci SZC Kandó Kálmán Informatikai Technikum to the list.

lib/domains/ca/lssd.txt
Divisional site: https://www.lssd.ca/
School site: https://lsrcss.lssd.ca/
=> Added Lord Selkirk School Division

lib/domains/de/bkgut.txt, lib/domains/de/schueler-bkgut.txt
Teacher and Student email accounts of https://www.bkgut.de , vocational college for design and engineering, 3-year course finds e.g. at https://www.bkgut.de/bildungsangebote/detail/fachinformatiker-fuer-systemintegration/
Teacher accounts at domain bkgut.de
Student accounts at domain schueler-bkgut.de
=> Berufskolleg für Gestaltung und Technik Aachen

lib/domains/id/ac/upgrisba.txt
=> add upgrisba.txt

lib/domains/hk/edu/gsas.txt
GSAS stands for Hong Kong Graduate School of Advanced Studies
=> Add domain gsas.edu.hk

lib/domains/ng/edu/noun.txt
- University Official website: https://www.nouonline.net/
- URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university : https://www.admissions.nouonline.net/zzappl_ug.php
-   proof showing that the university recognizes the domain you submit as an official email domain for the enrolled students:
=> National Open University Of Nigeria

lib/domains/edu/mo/edu/mpu.txt, lib/domains/mo/edu/mpu.txt
Add Macau Polytechnic University into repo, please review.
=> Add Macau Polytechnic University

lib/domains/at/borg-eisenerz.txt
High school in Eisenerz, Austria
=> Add BORG Eisenerz

lib/domains/fr/lyceegalilee.txt
**University official website URL :** https://pia.ac-paris.fr/serail/jcms/s2_162376/fr/accueil
**URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university :** X
**URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain for email :**
=> Add domain lyceegalilee.fr

lib/domains/id/ac/widyamataram/simak.txt
request add simak.widyamataram.ac.id
=> simak.widyamataram.ac.id

lib/domains/de/fosbos-ush/stud.txt
=> Added FOS/BOS Unterschleißheim

lib/domains/ru/sibstrin.txt
Good day, add please NOVOSIBIRSK STATE UNIVERSITY OF ARCHITECTURE AND CIVIL ENGINEERING (SIBSTRIN)
=> Add files via upload - create sibstrin.ru

lib/domains/bd/edu/vu.txt
Institution Name: **Verendra University**
Location: Rajshahi, Bangladesh
Website: https://vu.edu.bd
=> Added Verendra University

lib/domains/eg/edu/gei.txt
1 - Official website: https://gei.edu.eg
2 - IT course page: https://gei.edu.eg/index.php/ar/scientific-depts/communications-engineering
=> Add Giza Engineering Institute ( GEI )

lib/domains/de/gywa.txt
=> Gymnasium Waldstraße, Germany

lib/domains/uk/ac/fife.txt
www.fife.ac.uk https://www.fife.ac.uk/courses/search-all-courses/hdcsd/
=> Fife College

lib/domains/uk/ac/nkc.txt
=> add: North Kent College

lib/domains/id/ac/itn.txt
=> Add National Institute of Technology Malang (ITN Malang)

lib/domains/pl/lodz/asp/edu.txt
Add 'Akademia Sztuk Pięknych im. Władysława Strzemińskiego w Łodzi'
Official website: https://www.asp.lodz.pl/index.php/pl/
=> Add 'Akademia Sztuk Pięknych im. Władysława Strzemińskiego w Łodzi'

lib/domains/dk/askovefterskole.txt
add askov efterskole.
for game design lectures
=> add Askov efterskole

lib/domains/de/lore-lorentz-schule.txt
**Official website**
http://lore-lorentz-schule.de/
**Related course**
- http://lore-lorentz-schule.de/np1.html
- http://lore-lorentz-schule.de/nc1.html
- http://lore-lorentz-schule.de/wi.html
**a URL of a page or some other proof**
Page 29:
[Broschuere fuer Schueler Stand 17082021.pdf](https://github.com/JetBrains/swot/files/9376205/Broschuere.fuer.Schueler.Stand.17082021.pdf)
-----------
=> Lore Lorentz Schule

lib/domains/br/com/faculdadebarretos.txt
=> Add Faculdade Barretos

lib/domains/co/edu/sena/soy.txt
create new domain @soy.sena.edu.co for students
=> create new domain @soy.sena.edu.co

lib/domains/uk/ac/solihull.txt
Add Solihull College to list of domains
=> Add Solihull domain

lib/domains/id/ac/global.txt
hi @philipto, this is my PR after 3rd reject with error message "connection timed out; no servers could be reached", but if I check domain global.ac.id is exist, can you tell me what I'm missing ?
- My faculty website is : [https://global.ac.id/](url)
- IT specific courses: [https://global.ac.id/information-technology/](url)
Thank You
=> Add Global Institute domain

lib/domains/id/sch/penabur/smpsipbpk.txt
https://bpkpenabur.or.id/bandung/smpk-bpk-penabur-singgasana
=> add: SMPK BPK Penabur Singgasana Pradana Bandung

lib/domains/ch/vs/edu.txt
=> Adding VS Swiss school

lib/domains/institute/ispring.txt
https://ispring.institute/
https://ispring.institute/about-institute-ispring
=> Add iSpring Institute

lib/domains/bd/ac/bauet.txt
Institution Name: Bangladesh Army University of Engineering & Technology
Location: Natore-6431, Rajshahi Division, Bangladesh
Website: https://bauet.ac.bd
=> Added BAUET

lib/domains/org/dcsok/student.txt
I have added Deer Creek Public Schools in Edmond, OK.
[Offical website](https://www.deercreekschools.org/)
=> Add Deer Creek Public Schools in Edmond, OK

lib/domains/ae/bips/school.txt
=> Add Brilliant International Private School to the list of schools

lib/domains/org/darienps.txt
added darienps.txt for darienps.org.
=> created file for Darien High School in Connecticut

lib/domains/uk/ac/falmouth.txt
https://www.falmouth.ac.uk/study/undergraduate/computer-science
=> add falmouth university

lib/domains/pt/aebenfica/aluno.txt
Escola Secundaria Jose Gomes Ferreira 
https://inovar.aebenfica.edu.pt/
The "edu" is not part of the email, email example "00000@aluno.aebenfica.pt"
=> Adding Escola Secundaria Jose Gomes Ferreira

lib/domains/vn/edu/vnp.txt
Create new School : 
Vietnam The Nerhetlands Progamme 
https://vi.vnp.edu.vn/
=> Create new School: Vietnam The Nerhetlands Progamme - vnp.txt

lib/domains/co/edu/tecnologicocomfenalco.txt
https://tecnologicocomfenalco.edu.co/tecnologia-en-desarrollo-de-software
=> Add tecnologicocomfenalco university

lib/domains/vn/edu/hue.txt
This domain is email of website https://thuathienhue.edu.vn
=> Add domain hue.edu.vn

lib/domains/tz/ac/aru.txt
ardhi university
aru@aru.ac.tz
[Uploading aru.txt…]()
=> add ardhi university.

lib/domains/uk/ac/cumbria/uni.txt
**University URL**: https://www.cumbria.ac.uk/
**IT-related courses**:
- [MSc | Computer Science and International Business](https://www.cumbria.ac.uk/study/courses/postgraduate/msc-computer-science-and-international-business/)
- [BSc (Hons) | Games Development](https://www.cumbria.ac.uk/study/courses/undergraduate/games-development/)
**Proof that the university recognizes the domain**
See the student guide on setting up Outlook email [here](https://my.cumbria.ac.uk/Student-Life/Learning/Skills-Cumbria/Digital-Skills/Microsoft-Office/Outlook-365---Student-email/) (screenshot attached)
=> Add University of Cumbria (`@uni.cumbria.ac.uk`)

lib/domains/pl/edu/ujd.txt
University main URL: http://www.en.ujd.edu.pl/
IT department URL: http://www.kmi.ujd.edu.pl/
=> Add Jan Dlugosz University in Czestochowa

lib/domains/se/storsjogymnasiet.txt
I'm the web development teacher in this high school and would like to provide Webstorm as a dev tool for my students. We have about 40 students yearly.
=> Added storsjogymnasiet.txt

lib/domains/org/lincolnps.txt
Add Lincoln Public Schools (lincolnps.org)
=> Add Lincoln Public Schools

lib/domains/ca/herzing.txt
=> adding herzing college

lib/domains/br/edu/ifrs/bento.txt
=> Add file bento

lib/domains/tw/edu/khc/cysh.txt
[file.zip](https://github.com/JetBrains/swot/files/9484748/file.zip)
location: No. 183, Nanjiang St., Fengshan Dist., Kaohsiung City 830034, Taiwan (R.O.C.)
web: http://www.cysh.khc.edu.tw/main.php
domain: cysh.khc.edu.tw
=> Add Cheng Yi Senior High School

lib/domains/uk/ac/leeds-art.txt
=> Add Leeds Arts University

lib/domains/ru/academicol.txt
The educational program provides training in the following areas:
09.02.07 INFORMATION SYSTEMS AND PROGRAMMING (3 years 10 months)
The educational organization has a license to conduct educational activities and accreditation
Proof: https://academicol.ru/sveden/document/
Training program:
https://academicol.ru/profes/programmirovanie-v-kompyuternykh-sistemakh/
=> Add Academicol.ru

lib/domains/tw/edu/cnu/o365.txt
since GSuite change policy, school has move gsuite to o365
=> add o365 to cnu.edu.tw

lib/domains/uk/ac/wakefield.txt
=> Added college

lib/domains/de/fcg-duesseldorf/schueler.txt
Freies Christliches Gymnasium
Buchenstrasse 1 
40599 Düsseldorf
Home page: https://www.freie-christliche-schulen.de/gymnasium/home.html
IT related course, under MINT and Informatik: https://www.freie-christliche-schulen.de/gymnasium/moeglichkeiten/faecher.html
Recognition of E-Mail domain: https://www.freie-christliche-schulen.de/gymnasium/digitale-schule/microsoft365.html
Thanky you very much :D
=> Add FCG to the domains list pls :)

lib/domains/ru/dstu.txt
1. a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university:
[Link](https://dstu.ru/sveden/faculty/fktvtie)
[Link with proof of long-term study](https://dstu.ru/fileadmin/priem/2020/Pravila_priema_v_DGTU_2020.pdf)
[Link with proof of long-term study](https://i.imgur.com/2crjcjW.png)
2. a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.
[Contacts](https://dstu.ru/sveden/contacts)
Address: 367026, Republic of Dagestan, Makhachkala ave. Imam Shamil, 70
=> Add Dagestan State Technical University

lib/domains/br/edu/fag.txt
Official URL: [www.fag.edu.br](http://www.fag.edu.br/)
Software Engineering URL: https://www.fag.edu.br/engenharia-software (4 year course)
=> Add email domain

lib/domains/it/edu/isradice.txt
The presentation page of the IT course (in Italian): https://www.isradice.edu.it/index.php/didattica/indirizzi-di-studio/informatica-e-telecomunicazioni
=> Added Italian high school

lib/domains/it/edu/istitutobalducci.txt
Website: https://www.istitutobalducci.edu.it
IT and robotics study plan: https://www.istitutobalducci.edu.it/tecnico-tecnologico/piano-degli-studi
=> Add Istituto Statale Superiore Ernesto Balducci

lib/domains/br/edu/unicv.txt, lib/domains/br/edu/unifcv.txt
The university domain just changed.
=> Rename unifcv.txt to unicv.txt

lib/domains/cl/uaysen.txt
Domain of emails for university students and teachers. (Univeridad de Aysén)
Here is the institution's website:
https://www.uaysen.cl
=> add universidad de aysen

lib/domains/it/edu/isisvarese.txt
I added the domain of my high school "Isaac Newton" from Varese in Italy, i hope i didn't make any mistakes and that the request get accepted.
=> Added ISIS "Isaac Newton" high school domain

lib/domains/cz/zaalejka.txt
Official school website: https://www.zszaaleji.cz/
Student Domain: @zaalejka.cz
Teacher Domain: @zszaaleji.cz
=> Add ZŠ Za Alejí School

lib/domains/pe/edu/vallegrande.txt
https://www.vallegrande.edu.pe/carreras-profesionales/analista-de-sistemas/2015-10-07-14-54-44
=> ADD I.E.S.T.P. VALLE GRANDE

lib/domains/vn/edu/utschool.txt
US Vietnam Talent International School
https://utschool.edu.vn/en/learning-program
=> Add UTSchool

lib/domains/np/edu/hcoe.txt
College official website [here](https://www.hcoe.edu.np/)
=> Add HCOE college

lib/domains/net/cesde.txt
Add cesde university from colombia https://www.cesde.edu.co/
=> ADD cesde univeristy

lib/domains/pe/edu/utec.txt
[School official website UR](https://utec.edu.pe/en)
Jr. Medrano Silva 165, Barranco, Lima - Peru
[Computer Science at UTEC](https://utec.edu.pe/en/undergraduate-programs/computer-science)
Can I send the proof by Email?
=> Add UTEC to domain

lib/domains/np/edu/tu/rrlc.txt
Added Ratna Rajya Laxmi Campus, Tribhuvan University
=> Added Ratna Rajya Laxmi Campus

lib/domains/mx/edu/uartesdigitales.txt
adding uad - universidad de artes digitales
=> adding uad - universidad de artes digitales

lib/domains/mx/edu/institutooviedo.txt
Instituto Oviedo home page:
https://institutooviedo.edu.mx/
=> add institutooviedo-edu-mx domain

lib/domains/lv/alberta-koledza.txt
Added Alberta College that is located in Riga, Latvia
=> ADD domain/lv/alberta-koledza.txt

lib/domains/cz/savs.txt
Kind request to list SKODA AUTO University
University official website (czech): https://www.savs.cz/
University official website (english): https://www.savs.cz/en/
URL of study programme (course) long-term: https://www.savs.cz/en/study-programmes-and-specializations/business-informatics-7
URL confirming that domain is used (see contact's email address): https://www.savs.cz/en/general or link to one student as example: https://is.savs.cz/lide/clovek.pl?id=6244;lang=en
=> Request to list SKODA AUTO Univeristy

lib/domains/cn/edu/uic.txt
Official website: https://www.uic.edu.cn (https://www.uic.edu.cn/en/)
CS related website: https://fst.uic.edu.cn/cst/ (https://fst.uic.edu.cn/cst_en/index.htm)
UIC STUDENT MAIL SYSTEM: https://webmail.uic.edu.cn
Student email example: example@mail.uic.edu.cn
Hope these information useful for you!
=> Add uic.txt(Beijing Normal University & Hong Kong Baptist University United International College)

lib/domains/br/edu/unifacol.txt
Here's the university website: https://unifacol.edu.br/
Please, check out and thank you for the oportunity.
=> Add UNIFACOL - Universitary Center FACOL

lib/domains/np/edu/licnepal.txt
Added Lincoln International College to the repo
=> Added Lincoln International College

lib/domains/uk/ac/aquinas.txt
Aquinas College, Nangreave Road, Stockport, Cheshire SK2 6TH
College Website: https://www.aquinas.ac.uk/
CompSci Course: https://www.aquinas.ac.uk/sixthform/computer-science/
=> Add Aquinas College

lib/domains/ro/cnunirea.txt
I have added the "Unirea" National College, located in Brasov, Romania, to the list.
=> Added "Unirea" National College to the list.

lib/domains/de/fos2-n.txt
Official website: https://fos2-n.de/
IT course website: https://fos2-n.de/index.php/fuer-schueler/wahlpflichtfach-12-klasse/informatik-vertieft
Email domain is mentioned on the right side or at the bottom of every page
=> Add fos2-n

lib/domains/vn/edu/vnuis.txt
add new school International School, Vietnam National University, Hanoi
=> add new school International School, Vietnam National University, Hanoi - vnuis

lib/domains/br/edu/ifrs.txt
=> Add IFRS files

lib/domains/ph/edu/up.txt
These are the different programs offered by a couple of the constituent universities of UP
https://crs.upv.edu.ph/views/DEGREE-PROGRAMS_updated_08.19.2019.pdf
https://upd.edu.ph/academics/graduate-and-postgraduate/
These domains can be seen recognized here on the Constituent Universities section
https://up.edu.ph/
=> Add up.edu.ph

lib/domains/mx/edu/ulsachihuahua.txt
https://www.ulsachihuahua.edu.mx
https://www.ulsachihuahua.edu.mx/tecnologias-de-la-informacion-inter
=> School Upload

lib/domains/cz/matfyz.txt
primary website: https://www.mff.cuni.cz
secondary website: https://www.matfyz.cz/
=> Add matfyz domain (secondary domain of MFF CUNI)

lib/domains/fr/edouardgand.txt
=> Add Edouard Gand High School

lib/domains/com/sjvhs.txt
URL of Curriculum Guide showing computer science courses - includes computer science courses that are dual enrollment with local community college:
https://www.sjvhs.com/uploaded/Academics/Course_of_Studies_Guide_2022-2023a.pdf
Student Email Evidence:
https://www.sjvhs.com/student-life/technology
=> Saint John Vianney High School Domain Request

lib/domains/ua/net/kkz.txt
Correct misspells and formatting for Kyiv College of Communication
=> Correct misspells and formatting

lib/domains/uk/ac/southdevon/student.txt
This is a British College/University that has many computing/computer science courses offered at numerous degree and certification levels.
=> Add South Devon College to list of schools

lib/domains/academy/lincroft.txt
UK High School: Lincroft Academy
https://lincroft.academy/
Computer Science GCSE:
https://lincroft.academy/wp-content/uploads/2022/01/ICT-and-Computer-Science.pdf
=> Added entry for Lincroft Academy

lib/domains/mo/edu/must.txt
https://www.must.edu.mo/en/
https://www.must.edu.mo/en/scse/programme/master-science/study-plan
=> https://www.must.edu.mo/en/

lib/domains/vn/edu/c3chuvanan.txt
add Chu Van An High School (Ha Noi) to support list.
--
Ad CVA High School, we do need the license to teach gifted students about IT. Please consider merging this request!
Thanks,
=> add Chu Van An High School (Ha Noi) to support list

lib/domains/org/leffellschool/student.txt
=> Add The Leffell School

lib/domains/uz/itpu/student.txt
University official website url - https://itpu.uz/en/
Page about long-term IT related courses https://itpu.uz/en/epam/
Email Proof https://snipboard.io/8Uhwr9.jpg
=> added student.itpu.uz domain

lib/domains/com/onmicrosoft/czerwonyogolniak.txt
https://www.google.com/search?q=czerwonyogolnaik&oq=czerwonyogolnaik&aqs=chrome..69i57.1437j0j7&sourceid=chrome&ie=UTF-8
https://goo.gl/maps/A5PVzYGr51MAB4sW9
=> Added czerwonyogolniak

lib/domains/net/darzo.txt
Add the high school(istituto superiore) Silvio D'arzo to the list of accepted institutions.
Its official website is: https://www.istitutodarzo.edu.it/ 
The school offers many educational programs(or courses), among which is a CS-related one, which lasts five years. A short description along with a syllabus of the aforementioned can be found here: https://www.istitutodarzo.edu.it/informatica-e-telecomunicazioni/ 
Unfortunately I couldn't find anywhere in the website something stating that each student will be provided with a scholastic email address, so I'm afraid a screenshot of mine is about as much evidence as I can present.
=> Add darzo.txt

lib/domains/ba/edu/ssst/stu.txt, lib/domains/ba/edu/stu.txt
https://ssst.edu.ba/page/5/computer-science
=> Sarajevo School of Science and Technology

lib/domains/mx/edu/uaeh.txt
https://www.uaeh.edu.mx/
https://www.uaeh.edu.mx/campus/icbi/oferta/licenciaturas/c_computacionales/
Hello I hope anybody could help me, I update de domain, because my school doesn't appear when I try to renovate my licence of student. Thank you
=> Added Universidad Autonoma del Estado de Hidalgo

lib/domains/mx/edu/utmetropolitana/alumno.txt
University official website: https://www.utmerida.edu.mx/
Facebook: https://www.facebook.com/utm.merida/
Enroll website: https://tsuregistro.utmetropolitana.edu.mx/
=> feat: adding new university

lib/domains/ba/edu/blc.txt
I have added a domain for the accredited college in Bosnia and Hercegovina.
=> Added Banja Luka College to domains

lib/domains/net/shermanisd.txt, lib/domains/net/shermanisd/stumail.txt
All relevant URLs and info in text files
=> Added Sherman Independent School District

lib/domains/be/gent/onderwijs.txt, lib/domains/be/onderwijs.txt
Add onderwijs.gent.be for ziekenhuisschool Gent (Hospital school Gent)
=> Add onderwijs.gent

lib/domains/tw/edu/nttu/cc2k.txt, lib/domains/tw/edu/nttu/gm.txt
Remove the testing files, which are committed accidentally.
These sub-domains don't exist.
=> fix:🔥remove test files

lib/domains/br/senai/al.txt
=> add my domain, please

lib/domains/co/edu/uniciencia.txt
=> upload uniciencia.edu.co

lib/domains/cn/edu/shjgu.txt
=> add a new branch

lib/domains/ph/edu/nvsu.txt
=> Added Nueva Vizcaya State University

lib/domains/ua/cv/chic.txt
added new domain into solution
=> Added Chernivtsi Industrial Vocational College

lib/domains/hr/vuv.txt
Adding Virovitca University of Applied Sciences to domains 
[Official page](https://vuv.hr)
=> Added Virovitca University of Applied Sciences

lib/domains/com/ibadual/stud.txt
Add my cooperative university to JetBrains list
=> add iba cooperative university

lib/domains/de/gymbuckhorn.txt
Website: [https://www.buckhorn.de](https://www.buckhorn.de/)
=> Added Gymnasium Buckhorn

lib/domains/ru/school603-spb.txt, school603-spb.txt
Request to add Saint-Petersburg State Budgetary Educational Institution School 603
=> add school603-spb.txt

lib/domains/uk/ac/fareham.txt
URL: https://www.fareham.ac.uk/
IT Courses: https://www.fareham.ac.uk/computing-it-game-development/#
The fareham.ac.uk email domain can be seen in use on this page: https://www.fareham.ac.uk/contact/
=> Added Fareham College

lib/domains/uk/ac/dumgal/student.txt
Added Dumfries And Galloway College.
=> Dumfries And Galloway College

lib/domains/org/tka/students.txt
The King's Academy is a christ centered college prep school for 6th to 12th graders, located at Sunnyvale, CA.
=> Add TKA to JetBrains school list

lib/domains/be/miniemeninstituut/stud.txt, lib/domains/school/miniemen.txt
Website: https://miniemeninstituut.be/
Address: Diestsestraat 163, 3000 Leuven
They changed domain so i made a new pull request
=> Miniemeninstituut domain change

lib/domains/pe/edu/ulasalle.txt
1. University official website: [URL](https://www.ulasalle.edu.pe/)
2. Page on the official website IT related course is offered: [Software Engineering](https://www.ulasalle.edu.pe/software/)
3. URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.
=> Added La Salle University

lib/domains/gt/edu/junkabal.txt
=> adding Junkabal.edu.gt

lib/domains/mx/edu/up.txt
Adding UP Universidad Panamericana
https://www.up.edu.mx/
=> Adding UP Universidad Panamericana

lib/domains/lc/edu/salcc/apps.txt
official domain is salcc.edu.lc
information technology related courses are
http://salcc.edu.lc/programmes/digital-humanities/front-end-web-development/
http://salcc.edu.lc/engineering/cit.php
http://salcc.edu.lc/engineering/computer-systems.php
=> Add Sir Arthur Lewis

lib/domains/uk/ac/cityofbristol.txt
IT programs listed here: https://www.cityofbristol.ac.uk/courses/diploma-in-web-application-development/
=> City of Bristol College

lib/domains/de/fkggoettingen.txt
I'm a student on the school FKG in Göttingen Germany and i would like to use the JetBrains api for learning and coding c++ in vs :) I can't afford the 100 something dollars would be nice to get it for free
Thx for support & help
=> Request to add Felix Klein Gymnasium Göttingen to Schools

lib/domains/np/edu/ncit.txt
Courses offered by the college- https://ncit.edu.np/courses
=> add ncit to domain list

lib/domains/ua/knu.txt
Added native language title to the file.
=> Update Taras Shevchenko National University of Kyiv

lib/domains/org/thayer.txt
https://www.thayer.org/
https://www.thayer.org/academics/upper-school/computer-science
=> Add Thayer Academy

lib/domains/org/interlochen.txt
=> Interlochen Arts Academy

lib/domains/pl/com/onlineszkolafilmowa.txt
Website: https://szkolafilmowa.pl/
Course: https://szkolafilmowa.pl/tworzeniegier
=> Added "Warsaw Film School"

lib/domains/mx/edu/itsta.txt
Request to add the Instituto Tecnologico Superior de Tantoyuca to the list of universities available to request access to JetBrains tools.
=> Add itsta.txt

lib/domains/mx/edu/maristas/umq.txt
Request to add Universidad Marista de Querétaro to the universities that can request education access to JetBrains tools.
=> Added Universidad Marista de Querétaro (UMQ)

lib/domains/com/greenecountyschools.txt
Request to add the Greene County Public Schools to the list.
- school website: https://www.greenecountyschools.com/
- school address: 40 Celt Road, Stanardsville, VA 22973
Thank you,
=> added Greene VA high

lib/domains/com/alzago.txt, lib/domains/es/alzago.txt
https://alzago.com
https://alzago.es
=> Alzago, Escuela de Nuevas Tecnologías

lib/domains/mx/edu/seq.txt, lib/domains/mx/tecnm/chetumal.txt
Agrega dominio para el Tecnológico de Chetumal
=> Agrega tec dominio chetumal

consfi/stud.txt, lib/domains/it/consfi.txt
Master in Electronic Music and Multimedia Medium
=> Request add for Conservatory of Music of Florence

lib/domains/np/edu/kcc.txt
Added kcc.edu.np email to the Distribution List.
visit: https://kcc.edu.np/  to know more
=> Added Kantipur City College mail address to the list

lib/domains/pl/katowice/zdz/sosnowiec.txt
Adding School Complex in Sosnowiec ZDZ in Katowice
https://www.szkoly.sosnowiec.zdz.pl/ - Website of a/m Faculty
=> Adding "School Complex in Sosnowiec ZDZ in Katowice"

lib/domains/vn/edu/jvn.txt
JVN Institute - Vietnam National University HCMC
=> Add JVN Institute

lib/domains/it/imperia/marconi.txt
domain `marconi.imperia.it`
This is the link to the IT related course (in italian) is: [https://www.istitutoistruzionesuperioremarconi.edu.it/informatica-e-telecomunicazioni-sede-di-sanremo/](https://www.istitutoistruzionesuperioremarconi.edu.it/informatica-e-telecomunicazioni-sede-di-sanremo/)
=> IIS G. Marconi - Imperia/Sanremo

lib/domains/pe/edu/unamba.txt
https://unamba.edu.pe/
https://unamba.edu.pe/pregrado/ingenierias/ingenieria-informatica-y-sistemas.html
=> Added file for Micaela Bastidas University

lib/domains/school/sptech.txt
University's URL: https://www.sptech.school
Everything is in this same page, their courses and the proof of the emails domain(by the footer).
=> adding São Paulo Tech School to the list

lib/domains/pe/edu/unfv.txt
Hello, please add my domain.
I get license for student in intellijidea
=> add domain university national in Peru

lib/domains/id/ac/driyarkara.txt
=> add domain for Sekolah Tinggi Filsafat Driyarkara student email addresses

lib/domains/br/com/censupeg.txt
Site
www.censupeg.com.br
Landing page course with one year or more
https://www.censupeg.com.br/academy/home/course/web-development/127
=> Added Faculdade CENSUPEG

lib/domains/sv/edu/utec/mail.txt
- Institution/School Name Univeridad Tecnologica de El Salvador
- Instiution/School Website https://www.utec.edu.sv/ https://www.utec.edu.sv/carreras/ingenieria_en_sistemas_y_computacion
- Email Users @mail.utec.edu.sv
- For Students
- Education Levels College (University) or Undergraduate School or equivalent
=> UTEC create mail.txt

lib/domains/com/aeasofia.txt
domain: @aeasofia.com
i am a student of this school.
official website: aeasofia.com
school offers CS AP classes.
=> add an aea school.

lib/domains/ph/edu/ssct.txt
https://snsu.edu.ph/
https://snsu.edu.ph/academics/college-of-engineering-and-information-technology/
https://snsu.edu.ph/#:~:text=info%40ssct.edu,Email%20Us
=> Add domain for Surigao del Norte State University

lib/domains/de/health-and-medical-university.txt
Domain: health-and-medical-university.de
=> Add domain for Health and Medical University

lib/domains/br/edu/baraodemaua.txt
website https://www.baraodemaua.br/
=> baraodemaua

lib/domains/ie/naascbs/student.txt
Méanscoil Iognáid Rís https://www.naascbs.ie
=> Méanscoil Iognáid Rís https://www.naascbs.ie

lib/domains/co/edu/utap.txt
The university official website URL: https://utap.edu.co/
IT course offered by the university: https://utap.edu.co/sitio/desarrollo-de-sistemas-informaticos/
=> Added UTAP to domains

lib/domains/pe/edu/ulasamericas.txt
* The university official website URL: https://www.ulasamericas.edu.pe/
* IT course offered by the university: https://www.ulasamericas.edu.pe/ingenieria-de-computacion-y-sistemas/
=> Added ULASAMERICAS to domains

lib/domains/cat/lasalle/mollerussa.txt
add mollerussa.lasalle.cat domain
=> La Salle Mollerussa domain

lib/domains/uk/co/broadway-academy.txt
Added Broadway Academy to the Domain list.
=> Add Broadway Academy

lib/domains/sv/edu/catolica.txt
Universidad Católica de El Salvador - UNICAES
https://www.catolica.edu.sv/
@catolica.edu.sv
=>  Addition of other domains-Universidad Católica de El Salvador (UNICAES)

lib/domains/cat/lasalle.txt
=> la salle domain

lib/domains/vn/edu/hcm/giadinh.txt
- Official website: https://thptgiadinh.hcm.edu.vn
- My school gives their students an email with domain @giadinh.hcm.edu.vn
- We have class (also known as gifted class) that learnt about Information Technology, it's like university but for High School-er.
=> add hcm and gia dinh highschool

lib/domains/com/aeasofia.txt, lib/domains/np/edu/gces.txt
Gandaki College of Engineering and Science (GCES)
https://gces.edu.np
=> Added GCES (Gandaki College of Engineering and Science)

lib/domains/org/fsbwit.txt
Fachschule der Bundeswehr für Elektrotechnik und Informatiktechnik
=> Added FSBWIT.org

lib/domains/mx/edu/unikino.txt
the university kino from mexico added to the list for students and teachers
=> Added universidad kino

lib/domains/np/edu/excelsior.txt
=> Excelsior school added

lib/domains/de/bs-schramberg.txt
Berufliche Schulen Schramberg
https://www.bs-schramberg.de/index.html
=> Add BS School

lib/domains/se/karlstad/edu.txt
Around 2 years ago this gymnasium was merged into one.
=> merged into one gymnasium

lib/domains/ru/1561.txt
=> Add school №1561

lib/domains/mx/edu/iest.txt
Instituto de Estudios Superiores de Tamaulipas
=> iest.edu.mx

lib/domains/org/iu.txt
=> adding IU's workers' domain (including teachers)

lib/domains/pl/ilo.txt
I Liceum Ogólnokształcące im. Adama Mickiewicza w Białymstoku
https://ilo.pl
[wikipedia](https://pl.wikipedia.org/wiki/I_Liceum_Og%C3%B3lnokszta%C5%82c%C4%85ce_im._Adama_Mickiewicza_w_Bia%C5%82ymstoku) page (in polish)
[wayback machine](https://web.archive.org/web/20030801000000*/ilo.pl) site records dating from 2003
=> Adding ILO

lib/domains/us/fl/k12/walton.txt
South Walton High School
https://swh.walton.k12.fl.us
=> Add Walton County Public Schools

lib/domains/edu/xavier.txt
Computer Science program: https://www.xavier.edu/computer-science/
=> Add Xavier University

lib/domains/mx/edu/ut-morelia.txt
Name: Universidad Tecnológica de Morelia
Domain: ut-morelia.edu.mx
=> Add Universidad Tecnológica de Morelia

lib/domains/pe/edu/tecsup.txt
Tecsup
[Tecsup](https://www.tecsup.edu.pe/)
=> Add Tecsup domain

lib/domains/uk/ac/src.txt
Southern Regional College pull request for addition to JetBrains learning
=> Southern Regional College

lib/domains/sv/edu/udb/alumno.txt
url: https://www.udb.edu.sv/udb/
=> Add Don Bosco University

lib/domains/ba/ipi-akademija.txt
URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university - https://ipi-akademija.ba/our-programs
=> University official website URL - https://ipi-akademija.ba/

lib/domains/id/ac/ulbi.txt
the university official website URL: ulbi.ac.id
=> add Universitas Logistik dan Bisnis Internasional

lib/domains/org/pusdk12.txt
=> Add Paradise High School, CA, US

lib/domains/ro/mviteazul.txt
http://www.mviteazul.ro
http://www.mviteazul.ro/catedre.php
=> Adding Technical College Mihai Viteazul to list

lib/domains/np/edu/bhagawatischool.txt
- Add https://www.bhagawatischool.edu.np
- Course Link: https://www.bhagawatischool.edu.np/facilities/computer-lab/computer-science
=> Add Shree Bhagawati Higher Secondary School

lib/domains/net/misdmail.txt
Lake Ridge is a part of the Mansfield Independent School District - https://www.mansfieldisd.org
Here is the link for Lake Ridge specifically - https://lakeridge.mansfieldisd.org/
Thank you.
=> Submission for Lake Ridge High School

lib/domains/ru/uspu.txt
Ural State Pedagogical University - https://uspu.ru
Sorry, but website could be unavailable outside of Russia :(
=> Adding USPU School - Ural State Pedagogical University

lib/domains/vn/edu/sitc.txt
registering https://www.sitc.edu.vn
=> sitc registration

lib/domains/hu/nyfbox.txt
University of Nyíregyháza
https://english.nye.hu/
Email Users
@nyfbox.hu
=> Add University of Nyíregyháza

lib/domains/de/mpg/mpsd.txt
Maybe we should add all max planck institues as a whole? (`*.mpg.de`)
=> Add Max Planck Institute for Structure and Dynamics of Matter

lib/domains/mx/edu/uaem.txt
Add school Universidad Autónoma del Estado de Morelos(Autonomous University of the State of Morelos) 
The official page from the university is https://www.uaem.mx/
=> Add School UAEM

lib/domains/se/kungalv/edu.txt, lib/domains/se/kungalv/elev.txt, lib/domains/se/kungalv/skola.txt
Our city is so small i just added Kungälv municipality as school name. If that is not allowed i will certainly correct that.
=> Kungälvs Kommun / Kungalv Municipality

lib/domains/mx/edu/um.txt
Montemorelos University Request
=> Add Montemorelos University

lib/domains/cn/edu/muc.txt, lib/domains/cn/muc.txt
Official website URL: [https://www.muc.edu.cn/](https://www.muc.edu.cn/)
Email domain: xx@muc.edu.cn
Official website URL of long-term IT related course: [https://www.muc.edu.cn/info/1037/7170.htm](https://www.muc.edu.cn/info/1037/7170.htm)
=> Add Minzu University of China

lib/domains/kr/go/goe/shinbongm.txt
=> Shinbong Middle School

lib/domains/cl/cesantarosa.txt, lib/domains/cl/cesantarosa/a.txt
Add my school so that future student developers can obtain a jetbrains license.
=> Add cesantarosa/a.txt

lib/domains/mx/edu/cecyteg.txt
https://www.cecyteg.edu.mx/cecyteg/
https://www.cecyteg.edu.mx/cecyteg/oferta-educativa/bachillerato-tecnologico/carreras-tecnicas/programacion/
=> Add Colegio de Estudios Cientificos y Tecnologicos del Estado de Guanajuato

lib/domains/pl/edu/bsr.txt
=> Added Bednarska Szkoła Realna

lib/domains/lv/isriga.txt
International School of Riga is a certified International Baccalaureate school and therefore it has an advanced computer science course.
=> add International School of Riga to the list

lib/domains/np/edu/kec.txt
Adding Kantipur engineering college, Dhapakhel, Lalitpur to the ist
=> added Kantipur Engineering College

lib/domains/ie/ricecollege/student.txt
This is a secondary school (highschool) in Ennis, Ireland
=> Added Rice College

lib/domains/pl/edu/zyrardow.txt
School website: http://lo.zyrardow.edu.pl
School name: Liceum Ogólnokształcące im. Stefana Żeromskiego w Żyrardowie
=> Add LO Żyrardów

lib/domains/pl/pans.txt
Reverts JetBrains/swot#15576
Not enough evidence of the domain recognition
=> Revert "Add PANS Nysa"

lib/domains/mx/edu/itculiacan.txt
=> added Technological Institute of Culiacán

lib/domains/mx/edu/upemor.txt
https://www.upemor.edu.mx/
email link at correo institucional in https://www.upemor.edu.mx/sitios-de-interes/
=> Universidad Politecnica del Estado de Morelos

lib/domains/ua/edu/ust.txt
=> add DIIT(ust.edu.ua) domain 

lib/domains/vn/edu/ngs.txt
=> Newton Grammar School, HN, VN

lib/domains/org/sineast.txt
https://sirisaacnewtoneast.org
2-year Computer Science A-Level course: https://www.sirisaacnewtoneast.org/38/subject-information/subject/13/computer-science
=> Sir Isaac Newton East Sixth Form

lib/domains/vn/edu/ctim.txt
Please add my College to the list. Thank you!
=> Adding CTIM College

lib/domains/uk/ac/nchlondon/students.txt
Website: https://www.nulondon.ac.uk/
Courses (over 1 year): https://www.nulondon.ac.uk/about-us/academic-handbook/student-handbooks/pg/digital_tech_sol/
Email Proof: https://www.nulondon.ac.uk/wp-content/uploads/2021/01/CruNCH-15.pdf (List of Student Union Officers, with email)
=> Add NCHLondon

lib/domains/ch/isr.txt
Website for school: [ISR](isr.ch) - Proof that it exists
=> Add ISR - International School Rheintal

lib/domains/ua/edu/lnma.txt
Link for the academy website: https://lnma.edu.ua/
=> Add Lviv National Music Academy

lib/domains/gr/labaki.txt
Please add my technology center
=> Adding Labaki - Technology Center

lib/domains/pk/edu/ntu.txt
=> Revert "pull request ntu.txt"

lib/domains/ca/cdicollege.txt
I am an instructor for the web and mobile development course at CDI college in Canada.
Website: https://www.cdicollege.ca/
Web and mobile development program: https://www.cdicollege.ca/study-online/programs-and-courses/technology/web-and-mobile-application-development/
=> Add CDI College

lib/domains/mx/edu/utleon/alumnos.txt
https://www.utleon.edu.mx/
Blvd. Universidad Tecnológica #225 Col. San Carlos
CP. 37670 León, Gto. Mex. l Tel (477) 7 10 00 20
=> Domain UTL

lib/domains/ph/edu/fatima/student.txt
Website: https://www.fatima.edu.ph/
on email we use:   @student.fatima.edu.ph
=> Fatima School

lib/domains/mx/edu/ucaribe.txt
University official website URL: https://unicaribe.mx
URL of a page on the official website with IT related course is offered by the university: https://unicaribe.mx/licenciaturas/ingenieria-datos
URL of a page showing that the university recognizes the domain: https://unicaribe.mx/directorio
=> Add Universidad del Caribe (@ucaribe.edu.mx)

lib/domains/info/egressy.txt
Create a file for the email domain "egressy.info" of the Hungarian Budapesti Műszaki Szakképzési Centrum Egressy Gábor Két Tanítási Nyelvű Technikum
=> Add Egressy

lib/domains/br/com/senacrs.txt
Added Senac rs. 
See **[website](https://www.senacrs.com.br/unidade/63)**
=> Add senacrs

lib/domains/com/academialuisvives.txt
> [First attempt PR](https://github.com/JetBrains/swot/pull/15694)
https://www.academialuisvives.com
- https://www.academialuisvives.com/educacion/angular
- https://www.academialuisvives.com/educacion/reactjs
=> Add new academialuisvives.com

lib/domains/mx/edu/cbtis278.txt
URL: https://www.cbtis278.edu.mx/
IT related course offer: https://www.cbtis278.edu.mx/ofimatica-2/
Proof of ownership: https://www.cbtis278.edu.mx/mensaje-director/
=> Add cbtis278.edu.mx

lib/domains/pe/edu/ucsp.txt
University official website URL: https://ucsp.edu.pe/
=> add universidad catolica san pablo (@ucsp.edu.pe)

lib/domains/ca/lbpearson.txt
Lester B. Pearson Schoolboard. Website: https://www.lbpce.ca/
=> Add Lester B. Pearson School Board

lib/domains/pe/edu/drelm/iestpmrap.txt
Add IESTP María Rosario Araoz Pinto
Official website URL:
https://www.gob.pe/iestpmrap
IT related course:
https://www.gob.pe/institucion/iestpmrap/informes-publicaciones/3365275-desarrollo-de-sistemas-de-informacion
Post where we recognize the new domain for our students:
https://www.facebook.com/photo/?fbid=512355554231926&set=a.450093307124818
=> Add IESTP María Rosario Araoz Pinto

lib/domains/be/tsaam.txt
Official website: www.tsaam.be
Long-term IT related course: https://www.tsaam.be/Informaticabeheer
=> Added 't Saam Diksmuide

lib/domains/uk/ac/telfordcollege.txt
College: https://www.telfordcollege.ac.uk/
Long-term Course: https://www.telfordcollege.ac.uk/course/computing-a-level/
Domain Recognisation: https://www.telfordcollege.ac.uk/resources/ (itsupport@telfordcollege.ac.uk)
Address (https://www.telfordcollege.ac.uk/about/contact-us/)
Telford College,
Haybridge Road,
Wellington,
Telford,
TF1 2NP,
United Kingdom
=> Add for UK Telford College

lib/domains/org/bbs-me.txt
+add bbs|me Student domain ending (.org)
=> Adding the Student e-Mail domain for the bbs|me Hannover

lib/domains/co/bootcode.txt
Thanks for adding Bootcode.co to the jetbrain authorized school.
A new way to learn coding and the clean architecture.
(We are a french based school, even if our domain finish by .co)
=> adding bootcode

lib/domains/ph/edu/ncst.txt
=> Add domain National College of Science and Technology, Dasmariñas

lib/domains/pk/edu/bnu.txt
university website: https://www.bnu.edu.pk/
I signed up with my university email two years ago and have had no issues on Jetbrains. I was going renew my license when I saw my university no longer appeared while reregistering, don't know whats up with that.
=> Added Beacon House National University 

lib/domains/fi/tampere/edu.txt
Official website: https://www.tampere.fi/tampereen-teknillinen-lukio
IT courses: https://www.tampere.fi/tampereen-teknillinen-lukio/opiskelijalle/opetussuunnitelma-ja-opintojaksojen-kuvaukset-lops2021/tieto-ja-viestintatekniikka
=> Add Tampere High School of Technology

lib/domains/ph/edu/usls.txt
Website: https://www.usls.edu.ph/
=> Add University of St La Salle

lib/domains/ec/edu/itsqmet.txt
por favor add Instituto Tecnologico Universitario Quito Metropolitano
=> add Instituto Tecnologico Universitario Quito Metropolitano

lib/domains/hu/szentgyorgyi-nmszc.txt
This URL links to the schools 5 year software developer and tester course (with high school education): https://szentgyorgyi-nmszc.hu/kepzeseink/technikum-szakkepzo/szoftverfejleszto-es-tesztelo
The front page has a Teams icon on the top right, where students can log in with their school provided Teams accounts, which come with @szentgyorgyi-nmszc.hu email addresses.
=> Add Nógrád Megyei Szakképzési Centrum Szent-Györgyi Albert Technikum

lib/domains/ph/edu/thelewiscollege.txt
Please add our school The Lewis College to your repository.
Thank you!
=> Add The Lewis College

lib/domains/cz/gpjp.txt
Please add our school to your repository.
Thanks,
David.
=> Add GPJP school

lib/domains/ba/edu/treca-gimnazija.txt
https://treca-gimnazija.edu.ba
https://treca-gimnazija.edu.ba/izborna-podrucja/
Screenshot of Information Technologies class subjects, that can be found on the link right above:
Screenshot proof of official student domain:
Our school would benefit from JetBrains professional IDEs for development in Java, C++, Python, PHP and more languages.
Your time is much appreciated!
=> Add Treca gimnazija Sarajevo to domains

lib/domains/gr/edu/medcollege.txt
College Website: https://www.medcollege.edu.gr
Active Programming Related Course (BSc and MSc): https://www.medcollege.edu.gr/en/schools/school-of-computing/
In the official contact page you may find contact emails using the respective domains: https://www.medcollege.edu.gr/en/contact/
=> Adding Mediterranean College

lib/domains/pk/edu/iunc.txt
Please add this university domain in your list
=> Added iqra university north campus edu domain

lib/domains/ph/edu/iacademy.txt
Official URL/Main Website: https://iacademy.edu.ph
iAcademy has been offering CS/IT courses for over 20 years, with the flagship course being Computer Science specialisation in Software Engineering.
Additional Links:
https://iacademy.edu.ph/homev4/computing
[TFIN BROCHURE SY 23-24.pdf](https://github.com/JetBrains/swot/files/10145333/TFIN.BROCHURE.SY.23-24.pdf)
=> iAcademy, Information Communications Technology Academy

lib/domains/in/ac/bvrit.txt
Official URL/Main Website: https://www.bvrit.ac.in/
BVRIT is providing quality technical education from past 25 years in various fields of Engineering and Technology with specializations in Information Technology like Artificial Intelligence, Machine Learning and Data Science at Hyderabad, India
Additinal Links:
https://www.bvrit.ac.in/cse-overview
https://drive.google.com/file/d/1L86z67lPwlRPynf2P99NaK_wRX2v__Vt/view
https://drive.google.com/file/d/13pc15dsy_HHp147dJvKT1ySJlsrfqNsk/view
https://www.bvrit.ac.in/cse-publications
=> Add B. V. Raju Institute of Technology

lib/domains/sa/com/maarif.txt
=> Added maarif

lib/domains/eg/edu/eslsca.txt
[ahmed.sengab22bg@eslsca.edu.eg](mailto:ahmed.sengab22bg@eslsca.edu.eg)
https://eslsca.edu.eg/
https://eslsca.edu.eg/diplomas/#tab3
=> Adding Eslsca University

lib/domains/se/sjolinsgymnasium/ga/elev.txt
Sjölings Gymnasium Södermalm
https://www.sjolinsgymnasium.se/sodermalm/
noa.vejrich@elev.ga.sjolinsgymnasium.se
=> Sjölins gymnasium södermalm. Stockholm Sweden

lib/domains/org/ascte.txt
=> Added Alabama School of Cyber Technology and Engineering

lib/domains/id/ac/stmik-sumedang/mhs.txt
STMIK Sumedang
https://fti.unsap.ac.id
student official email => [example@mhs.stmik-sumedang.ac.id](mailto:example@mhs.stmik-sumedang.ac.id)
=> Add STMIK Sumedang domain to the list

lib/domains/pe/edu/usat/estudiante.txt
Universidad Catolica Santo Toribio de Mogrovejo
http://www.usat.edu.pe/
- [x ] Alumni
- [ x] Post-graduate research
- [ x] Graduate School
- [ x] College (University) or Undergraduate School or equivalent
=> add estudiante.usat.edu.pe

lib/domains/eg/edu/deraya/student.txt
the university's official website => http://deraya.edu.eg/
student official email => example@student.deraya.edu.eg
=> add Deraya University - Minya, Egypt

lib/domains/uk/ac/wolvcoll.txt
Website: https://www.wolvcoll.ac.uk/
Emails: <Student ID>@students.wolvcoll.ac.uk
=> Add City of Wolverhampton College

lib/domains/my/edu/sc.txt
https://www.southern.edu.my/
https://www.southern.edu.my/faculty-of-engineering-information-technology/
=> Southern University College

lib/domains/kr/go/goe/shth.txt
Suwon Hi-tech High School add
main school site is https://sht-h.goesw.kr/index.do
=> Suwon Hi-tech High School add

lib/domains/stoplist.txt
=> Mapua University

lib/domains/at/htleisenstadt.txt
One of the related courses is "Angewandte Informatik und fachspezifische Informationstechnik" (applied informatics and field specific information technology), see "Stundentafel der Mechatronik" at https://www.htleisenstadt.at/en-us/ABTEILUNGEN/MECHATRONIK/Stundentafel (Sorry for the non existing translations there, although they have this flag suggesting a proper translation. Doesn't do anything besides changing the date format.)
=> added HTL Eisenstadt

lib/domains/ng/edu/gsu.txt
university website: https://gsu.edu.ng/home/
Department URL: https://gsu.edu.ng/home/computer-science/
=> Add Gombe State University

jcpsnj.txt, lib/domains/org/jcpsnj.txt
Add the Jersey City Public Schools to this.
=> Add JCPSNJ

lib/domains/cn/edu/sysu/mail.txt
Add mail.sysu.edu.cn for the staff in Sun Yat-sen University.
URL:https://www.sysu.edu.cn/.
About Sun Yat-sen University: https://www.sysu.edu.cn/sysuen/aboutSYSU/SYSU_Today.htm
=> add lib/domains/cn/edu/sysu/mail.txt

lib/domains/np/edu/tu/cdcsit.txt
=> Add CDCSIT TU

lib/domains/mx/edu/clavijero/alumno.txt
https://www.clavijero.edu.mx/
https://www.clavijero.edu.mx/tsu-licenciatura/ingenieria-en-sistemas-computacionales-tsu-licenciatura/
https://cursos.clavijero.edu.mx/cursos/TIE-2015/modulo3/contenidos/32_correo_electrnico_institucional.html
=> Add Instituto Consorcio Clavijero

lib/domains/br/edu/fapal/aluno.txt
=> Add base repository FAPAL

lib/domains/np/edu/tu/pmc.txt
This pull request contains the pmc.txt file to include Patan Multiple Campus (pmc.tu.edu.np) in Jetbrains licensing.
=> Add Patan Multiple Campus from Lalitpur, Nepal

lib/domains/mn/edu/nmit.txt
New mongol institute of technology
=> new university name nmit

lib/domains/tw/edu/ntpc/ntsh/g.txt
This is a senior high school located in NewTaipei City, Taiwan.
school's sites: https://www.ntsh.ntpc.edu.tw/
=> Add @g.ntsh.ntpc.edu.tw

lib/domains/hk/edu/tkogss.txt
=> Add @tkogss.edu.hk

lib/domains/org/calbrightcollege.txt
Calbright College
University official website URL: https://www.calbright.org
=> calbrightcollege

lib/domains/info/ucrso.txt
Adding university of Costa Rica, Western Headquarters
=> Adding ucrso domain to info folder.

lib/domains/pk/edu/nhu.txt
I have added Nazeer Hussain University at Karachi, Pakistan
=> Added Nazeer Hussain University

lib/domains/id/ac/pnc.txt
- PNC official website URL: https://pnc.ac.id/en/
=> Adding Politeknik Negeri Cilacap

lib/domains/br/edu/fesppr.txt
Course page: https://www.fesppr.edu.br/cursos/sistema-informacao/
=> Add fesppr.edu.br domain

lib/domains/cz/sos-jh.txt
Adding czech high school to domains
=> Add SOS a SOU Jindřichův Hradec to domains

lib/domains/tn/r-iset/beja.txt
Added "Higher Institute of Technological Studies Beja" located in Tunisia
=> Added "ISET Beja" located in Tunisia

lib/domains/pl/pansp/s.txt
Adding Państwowa Akademia Nauk Stosowanych pansp.pl domain
=> Adding Państwowa Akademia Nauk Stosowanych w Przemyślu

lib/domains/pe/edu/salazarbondy.txt
To add Instituto Superior Tecnologico Salazar Bondy
=> add salazarbondy.edu.pe

lib/domains/id/ac/icpa-banyuwangi.txt
please add akademi penerbang indonesia banyuwangi with official website : https://icpa-banyuwangi.ac.id/
=> please add akademi penerbang indonesia banyuwangi

lib/domains/gr/aspete/ta.txt, ta.txt
school 
Anotati Sxoli Paidagwgikwn Texnikwn Epistimwn
aspete
url
www.aspete.gr
user's email
Academic /Teaching Staff
Institution
Undergraduate Institution
=> add my school Aspete Heraklion Greece

lib/domains/tw/edu/ndmctsgh/ndmc.txt
https://wwwndmc.ndmctsgh.edu.tw/uniten/100011/3320
=> add NDMC domain

lib/domains/tw/edu/usc/gm7.txt
Shih Chien University
[https://www.usc.edu.tw/](https://www.usc.edu.tw/)
=> Add Shih Chien University new domain

lib/domains/pk/edu/cuiatd.txt
Homepage -->  [Link](https://www.cuiatd.edu.pk/)
Course Offered --> [Link](https://www.cuiatd.edu.pk/admission-cell/undergraduate/)
=> Added Comasts University Islamabad Abbottabad Campus Domain Entry

lib/domains/gt/edu/udeo.txt
add the university of the west, of guatemala
udeo.edu.gt
=> add universidad de occidente

lib/domains/np/edu/softwarica.txt
Tel : 01-4541577, 01-4525661
Email : hello@softwarica.edu.np
**name@softwarica.edu.np**
Official institution site can be visited at [Softwarica College of IT and E-Commerce](https://softwarica.edu.np/)
=> lib domain for softwarica.edu.np

lib/domains/mx/edu/itiguala.txt
Se agrega archivo para Instituto Tecnológico de Iguala
=> Instituto Tecnológico de Iguala

lib/domains/cn/edu/dlu/s.txt
Add the student email of Dalian University.
=> add s.dlu.edu.cn

lib/domains/pk/edu/uetpeshawar.txt
University Website URL:  https://www.uetpeshawar.edu.pk/
=> University of Engineering and Technology, Peshawar

lib/domains/br/org/germinare.txt
=> Escola Germinare

lib/domains/mx/edu/ut-tijuana.txt
Official university page: https://uttijuana.edu.mx/
=> Added Universidad Tecnológica de Tijuana

lib/domains/org/passerellesnumeriques/student.txt
https://www.passerellesnumeriques.org/en/our-actions/vietnam/
=> PNV - Passerelles numeriques Vietnam

lib/domains/tw/edu/ntua/mail.txt
Add National Taiwan University of Arts Email Domain
and Here's our official website,
I'm studying in the Visual Communication Design , thanks
https://aca.ntua.edu.tw/article.aspx?ca=211&id=140
=> Add NTUA Domain

lib/domains/it/consaq.txt
Request made by the School of Electronic Music of Conservatory "A. Casella"
=> Added Conservatory of L'Aquila

lib/domains/id/ac/umg.txt
=> Add Universitas Muhammadiyah Gresik

lib/domains/ua/kherson/ksaeu.txt
* Official website: http://www.ksau.kherson.ua/ (KSAU is a former name of the university)
* IT-related courses:
http://www.ksau.kherson.ua/files/robochi_programi/202/%d0%a0%d0%be%d0%b1%d0%be%d1%87%d0%b0%20%d0%bf%d1%80%d0%be%d0%b3%d1%80%d0%b0%d0%bc%d0%b0%20%d0%b4%d0%b8%d1%81%d1%86%d0%b8%d0%bf%d0%bb%d1%96%d0%bd%d0%b8%20%d0%86%d0%bd%d1%84%d0%be%d1%80%d0%bc%d0%b0%d1%86%d1%96%d0%b9%d0%bd%d1%96%20%d1%82%d0%b5%d1%85%d0%bd%d0%be%d0%bb%d0%be%d0%b3%d1%96%d1%97.pdf
http://www.ksau.kherson.ua/files/_robochi.progr/071%20%D0%A0%D0%BE%D0%B1%D0%BE%D1%87%D1%96%20%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B8%20%D0%BD%D0%B0%D0%B2%D1%87%D0%B0%D0%BB%D1%8C%D0%BD%D0%B8%D1%85%20%D0%B4%D0%B8%D1%81%D1%86%D0%B8%D0%BF%D0%BB%D1%96%D0%BD/I%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86i%D0%B9%D0%BDi%20%D1%81%D0%B8%D1%81% …
=> Added Kherson State Agrarian and Economic University, ksaeu.kherson.ua

lib/domains/uk/ac/woodhouse.txt
Website: [https://www.woodhouse.ac.uk](url)
=> Added Woodhouse College

lib/domains/at/ac/lbs.txt
Website: https://lbs.ac.at/
IT-related programs:
- Strategic Finance & Business Analytics Program: https://lbs.ac.at/study-programs/strategic-finance-business-analytics/  
In the course of studies, the students learn data analysis techniques using R and Python and are taught to work with SQL databases.
- LBS Innovation Center: https://lbs.ac.at/innovation-center/
Although the majority of the programs are business-related,  the administration is now introducing more IT courses into the curricula. In particular, LBS's own IT-hub is now acting as an incubator for [Insticore](https://insticore.com/).
=> Add Lauder Business School

lib/domains/tn/rnrt/crns.txt
Hello, 
This is a request to add crns.rnrt.tn domain to the list of academic institutions working on IT and computer science research subjects under the university of Sfax, Tunisia. 
Best regards
=> add crns.rnrt.tn

lib/domains/mt/edu/mcast.txt
=> Add mcast educational institute

lib/domains/com/altusps/stu.txt
Altus, Oklahoma, United States
=> Add Altus High School

lib/domains/uz/itpu.txt
I am adding my university to the domains list. I appreciate if you prefer to merge.Thank you!
=> Adding university 

lib/domains/la/edu/fe-nuol.txt
[fe-nuol.txt](https://github.com/JetBrains/swot/files/10328247/fe-nuol.txt)
=> Add new domain NUOL

lib/domains/edu/edhec.txt
this is one of the pages indexing the publications of the school: https://www.edhec.edu/fr/recherche-et-faculte/centres-et-chaires/chaire-prevision-innovation-et-transformation/publications
here is one the articles : https://www.tandfonline.com/doi/abs/10.1080/13675567.2022.2088707
on "Exploration of barriers and enablers of blockchain adoption for sustainable performance: implications for e-enabled agriculture supply chains"
the author is: Sachin S. Kamble with the email: [Sachin.kamble@edhec.edu](mailto:Sachin.kamble@edhec.edu)
=> Add EDHEC Business School (https://www.edhec.edu)

lib/domains/mx/edu/ieu/alumno.txt
Universidad IEU,  Instituto de Estudios Universitarios, Puebla, México
=> Universidad IEU,  Instituto de Estudios Universitarios, Puebla, México

lib/domains/ke/ac/spu.txt
=> Add: Request To Add St Paul's University Kenya

lib/domains/ca/visii.txt
**School**: Vancouver Island School of Innovation and Inquiry
**Website**: https://visii.ca
**Screenshot**:
=> Add visii.ca to Educational Institution List

lib/domains/ca/niagaracollegetoronto.txt
Add new college. 
Niagara College - Toronto ( https://www.niagaracollegetoronto.ca )
=> add Niagara College - Toronto

lib/domains/de/mis-munich.txt
School website: [https://www.mis-munich.de/](https://www.mis-munich.de/)
=> Add Munich International School

lib/domains/com/madeiratorres.txt
This file will allow students from madeiratorres.com to use JetBrains software
=> Added MadeiraTorres file

lib/domains/mn/edu/mnums.txt
=> Create mnums.txt file to domains

lib/domains/jo/edu/uopstd.txt
This PR adds support for the student email `@uopstd.edu.jo`
=> Add uopstd (University of Petra)

lib/domains/ph/edu/bicol-u.txt
Will be adding more information about request in the comments to this pull.
=> Added Bicol University (bicol-u)

lib/domains/mx/edu/cpds.txt
CPDS - Colegio de Posgrado en desarrollo de Software
Software Development Postgraduate College
- Official website
- [Translated - Official website](https://www-cpds-edu-mx.translate.goog/Maestria.aspx?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp&_x_tr_sch=http)
- [Original - https://www.cpds.edu.mx](https://www.cpds.edu.mx/Maestria.aspx) 
- [Translated - Who are we](https://www-cpds-edu-mx.translate.goog/QuienesSomos.aspx?_x_tr_sch=http&_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp)
- [Original - https://www.cpds.edu.mx/QuienesSomos.aspx](https://www.cpds.edu.mx/QuienesSomos.aspx)
- IT Related course
- [4 semester / 24-month duration course](https://www-cpds-edu-mx.translate.goog/Info_curso.aspx?id=1545&_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp&_x_tr_sch=http)
- …
=> Request to add CPDS to list of approved schools

lib/domains/ec/edu/iaen.txt
Add file of educational institute
=> Adding iaen institute

lib/domains/ar/edu/ugd.txt
* Institution: "Universidad Gastón Dachary"
* Main location: Salta 1912, Posadas, Argentina
* Website: https://ugd.edu.ar/
* Proof of course and email domain: https://ugd.edu.ar/es/oferta-academica-2/carreras-de-grado/ingenieria-y-ciencias-de-la-produccion/479-ingenieria-en-informatica
=> Add "Universidad Gaston Dachary"

lib/domains/be/ihecs.txt
IHECS is a Brussels university that has been training its communication students in code for only a few years
=> Add IHECS university

lib/domains/br/com/unifatecpr.txt
Computer Engineering graduation course at Unifatecpr -> http://www.unifatecpr.com.br/paginas/curso_co.html
=> Adding UNIFATECPR

lib/domains/net/bssdstd.txt
Added bssdstd (Blue springs school district student)
=> Added bssdstd (official domain is bssd)

lib/domains/pk/edu/abasynisb.txt
=> abasyn university islamabad domain added (https://abasynisb.edu.pk/)

lib/domains/uk/co/ormistonriversacademy.txt
https://ormistonriversacademy.co.uk/
https://ormistonriversacademy.co.uk/admin/wp-content/uploads/sites/29/2022/09/Sixth-Form-Prospectus-2023-for-Web-Single-Pages.pdf
=> Add ormistonriversacademy.co.uk

lib/domains/mx/edu/uttcampus.txt
Link to university page: https://www.utt.edu.mx/
=> Add UTT to JetBrains

lib/domains/org/flaglercps.txt
Official Website: https://www.fpcbulldogs.com/
Computer Science Discoveries Course: https://www.fpcbulldogs.com/academics/course-descriptions
=> Add Flagler Palm Coast High School

lib/domains/ua/edu/btsau.txt
Please, add Bila Tserkva National Agrarian University to repository. Thank you!
=> Add Bila Tserkva National Agrarian University

lib/domains/th/ac/rpu.txt
Name : Rajapruk University
Website : http://www.rpu.ac.th
Student Email : @rpu.ac.th
Who IS : https://who.is/whois/rpu.ac.th
=> add Rajapruk University

lib/domains/net/backwellschool.txt
=> Added Backwell School

lib/domains/ua/vn/vntu.txt
Вінницький Національний Технічний Університет
Vinnytsia National Technical University
=> Added vntu.txt

lib/domains/uk/co/maidenerleghschools.txt
Link to school page - https://www.maidenerleghschool.co.uk 
Link to the computing department - https://www.maidenerleghschool.co.uk/page/?title=Computer+Science&pid=329 
Link to sixth form page - https://www.maidenerleghschool.co.uk/page/?title=Computer+Science&pid=401
=> Added Maiden Erlegh school

lib/domains/np/edu/spictevt.txt
Added Shankharapur Polytechnic Institute, a Technical School of CTEVT in Nepal.
=> Added Shankharapur Polytechnic Institute

lib/domains/net/mcmsnj.txt, lib/domains/net/mcvts.txt
My school got renamed to "Woodbridge Academy - Middlesex County Magnet School of New Jersey" from "Middlesex County Academy for Allied Health & Biomedical Sciences". I am putting this request to add the file with this new name. Currently, I am unable to renew my JetBrains Product Pack for Students, as I have lost access to my old school email on the domain mcvts.net  
Here is the reference to the old PR for my school that my Dad helped me in 2020
https://github.com/JetBrains/swot/pull/10267
Here is the URL for my school: **https://www.mcmsnj.net/woodbridge**
=> Added file for "Woodbridge Academy - Middlesex County Magnet School of New Jersey"

lib/domains/no/oygardenskule.txt
Fjell Ungdomskule
https://www.oygarden.kommune.no/fjellungdomsskule/
- [ X] Students
- [ X] Elementary School or equivalent
format of email: "first 3 initial of first name""first 3 initial of last name""number".oygardenskule.no
example [bensek1@oygardenskule.no](bensek1@oygardenskule.no)
=> Add Fjell Undomskule

lib/domains/th/ac/lic.txt
วิทยาลัยการอาชีพลอง
Long Industrial and Community Education College
=> add lic.ac.th

lib/domains/pk/edu/scarsdale.txt
Hi, we would love to use IntelliJ, but we want to learn and develop with all tools necessary and are eligible for the student offer.
We would really appreciate if we had access to the full version to IntelliJ.
Thanks.
=> Add "Scarsdale International School" to the list.

lib/domains/mx/edu/centrogeo.txt
The official page: https://www.centrogeo.org.mx/ 
The courses taught can be found at the following URL: https://www.centrogeo.org.mx/posgrado 
Within it we handle the course of computational geointelligence, which involves programming with different languages such as .NET, R, Java, PHP, Python among others. 
In the same way you can notice that the page uses the domains centrogeo.edu.mx, for researchers, teachers and students. https://www.centrogeo.org.mx/areas-profile/emartinez
=> I request the addition of the educational domain: centrogeo.edu.mx

lib/domains/au/edu/nsw/scas.txt, lib/domains/scas.txt
Added St Columba Anglican School for educational purposes.
=> St Columba Anglican School Add

lib/domains/np/edu/tu/trc.txt
=> Added Tri-Chandra Multiple Campus

lib/domains/np/edu/tu/mahemc.txt
Add Mahendra Multiple Campus Nepalgunj
=> Added Mahendra Multiple Campus Nepalgunj

lib/domains/lv/edu/vtdt.txt
=> Add vtdt.edu.lv

lib/domains/com/onmicrosoft/cnogsibiu.txt
This is the highschool's website: http://cnogsibiu.ro
=> Request to add my highschool to jetbrains

lib/domains/mx/edu/univo-gdl.txt, lib/domains/mx/edu/univo.txt
Link to school page: http://www2.univo.edu.mx/web/
Link to IT course: http://www2.univo.edu.mx/web/licenciatura/licenciaturas.php#isc
Link to some help images that are shown by zoom to students on how to connect to their institutional school mail: https://drive.google.com/drive/folders/1FngqkjdM0vy_zEhSsiiTciZtShvdYVVl?usp=sharing
=> Universidad del Valle de Orizaba (UniVO)

lib/domains/net/iese.txt
IESE is a business school with a one year specialization on technology as you can see here:
https://mba.iese.edu/program/curriculum-content/year-2/electives/
=> Adding IESE Business School

lib/domains/com/onmicrosoft/tlkrakowpl.txt
=> tlkrakowpl

lib/domains/com/holbertonschool.txt, lib/domains/com/holbertonstudents.txt
request to update to the new Holberton domain: _holbertonstudents.com_
you can contact me at: 1536@holbertonstudents.com
=> holberton domain changed to holbertonstudents

lib/domains/mz/ac/ismonitor.txt
Website: https://ismonitor.ac.mz
IT Degree: https://www.ismonitor.ac.mz/cursos-de-licenciatura/gestão/licenciatura-em-gestão-e-informática/
=> Added ismonitor

lib/domains/ph/edu/feualabang.txt
**Official Name:** Far Eastern University
**Branch Name:** Far Eastern University Alabang / FEU Alabang 
-> This is the university I'm adding, it is under the official branch and it has a different domain Website: https://feualabang.edu.ph
**IT Related Courses Offered Link:** https://feualabang.edu.ph/academics/ccsma 
-> Courses take 4 years to complete with the exception of IT related courses which take 5 years to complete.
**Student Portal Link:** https://students.feualabang.edu.ph
-> This is the student portal link with the domain (I don't know if this serves as proof though)
Let me know if you have questions :)
**Screenshot:**
=> Added Far Eastern University Alabang

lib/domains/cat/iesdecelra.txt
Institut de Celrà
https://agora.xtec.cat/iesdecelra/
=> Add Institut de Celrà

lib/domains/pk/edu/quest.txt
Adding Quaid-e-Awam University of Engineering, Science and Technology, Nawabshah, District Shaheed Benazirabad, Sindh, Pakistan
=> Add Quaid-e-Awam University, Nawabshah, Pakistan

lib/domains/mx/edu/upslp.txt
Universidad Politécnica de San Luis Potosí
https://www.upslp.edu.mx/upslp/
=> Add files upslp.txt

lib/domains/org/umasd.txt
- Official website URL: https://www.umasd.org/site/Default.aspx?PageID=5276
- IT related course: https://www.umasd.org/Page/5440
=> Adding Upper Merion Area High School

lib/domains/sv/edu/udb/docente.txt
docente.edu.sv added to Universidad Don Bosco
=> Adding Universidad Don Bosco teacher

lib/domains/id/ac/uim.txt
Please add Universitas Islam Madura
=> add Universitas Islam Madura

lib/domains/mx/edu/unav.txt
I request to add the domain of this university that offers the Computer Systems Engineering degree. I attach the official website. [Universidad de Navojoa](https://unav.edu.mx/)
=> Add Universidad de Navojoa

lib/domains/uz/ajou.txt
Institution Name: Ajou University in Tashkent
Official Website: [ajou.uz](http://ajou.uz)
=> Request to add Ajou University in Tashkent

lib/domains/ph/edu/sorsu.txt
Official University Website of Sorsogon State University College of Information Communication Technology.
https://sorsu.edu.ph/courses-offered/undergraduate-programs-bulan-campus/
=> Sorsogon State University

lib/domains/pe/edu/istpargentina.txt
Official website of the institute: [http://www.istpargentina.edu.pe/](url)
Official Facebook: [https://www.facebook.com/instituto.argentina](url)
=> Add IESTP - Argentina

lib/domains/edu/stchas.txt
- https://stchas.edu/
- https://www.stchas.edu/pathways/computers-technology - List of Business Technology, Computer Science, and IT related degrees
=> Add Saint Charles Community College

lib/domains/edu/stchas.txt
=> Revert "Add Saint Charles Community College"

lib/domains/it/42roma.txt
42 Roma Luiss school
https://42roma.it/
=> Added 42 Roma Luiss

lib/domains/edu/sans.txt
Website: https://www.sans.edu/
=> Add SANS Technology Institute

lib/domains/uk/ac/hereford.txt
School Website: https://www.hereford.ac.uk/
=> Add Hereford Sixth Form College

lib/domains/ee/kbfi.txt
The National Institute of Chemical Physics and Biophysics gives courses at several Estonian universities. I gave a course last semester of Nuclear Reactor Physics at Tallinn Technical University where we used Python to make some scientific programs. It is a very similar situation to psi.ch, which I was a part of before and is also in the swot repository.
=> Added the National Institute of Chemical Physics and Biophysics

lib/domains/pe/edu/unaj.txt
add Universidad Nacional de Juliaca to jetbrains repository
=> add UNAJ to jetbrains repository

lib/domains/co/edu/pi.txt
URL of the institution which is different from the email domain name: https://politecnicointernacional.edu.co/
URL of a program lasting for more than one year (2.5 years):
[politecnico internacional](https://politecnicointernacional.edu.co/sw/es/aspirantes/programas/tecnologias/tecnologia-en-desarrollo-de-software-y-aplicativos-moviles)
=> Add politecnico internacional

lib/domains/gr/mc-class.txt
College Website: https://www.medcollege.edu.gr/
Active Programming Related Course (BSc and MSc): https://www.medcollege.edu.gr/en/schools/school-of-computing/
We have already added the domain: medcollege.edu.gr but our new students and stuff get emails under the domain: @mc-class.gr 
Please, let me know if you need any document I can request from the administration to prove that.
Regards
=> Adding Mediterranean College Students

lib/domains/world/hhc.txt
=> Added hhc.world to the lib/domains/world directory

lib/domains/uk/co/utcswindon.txt
https://www.utcswindon.co.uk/
https://www.utcswindon.co.uk/curriculum/
=> UTC Swindon

lib/domains/ng/net/lbs.txt
I added Lagos Business School, Pan-Atlantic University, a leading business school in Africa and as new generation managers, we do a lot of Data Analytic related work.
As part of a Student-Led Club on Data Analytics and a strong admirer of Jetbrains Products, we all will be more effective using Jetbrains offerings Like Jupiter Notebook and Datagrip for manipulating data. I find it more intuitive to use and will be more than willing to lead the wild adoption for Potential managers, which will have key decision roles to make in future organizations.
example: A manager who may have used a Jetbrains product while training will find it easier to accept developers' requests for the company to go full JetBrains when such a decision arises.
Official Website:  https://www.lbs.edu.ng/
=> Added Lagos Business School, Pan-Atlantic Universiry, Lagos

lib/domains/org/beehiveacademy/student.txt
"Beehive Science & Technology Academy is a platinum level STEM charter school in Sandy, Utah with programs for students in STEM Elementary, STEM Middle School and STEM High School.  Beehive Academy heavily focuses on STEM programs including engineering, computer science, math and health sciences while still providing traditional Utah core standards."
Domain: https://www.beehiveacademy.org/
=> Add Beehive Academy

lib/domains/np/edu/iimscollege.txt
Established in 2010, by enthusiasts & educationists, the ‘IIMS Education Foundation Pvt. Ltd.’ has long established its roots in Nepalese educational sector by promoting a wide variety of quality educational services.
Domain: https://iimscollege.edu.np/about-college/
=> Added Institute OF International Management Science domain

lib/domains/ph/edu/uic.txt
For me and future UIC students
=> University of the Immaculate Conception

lib/domains/id/sch/smktiannajiyah/siswa.txt
sekolah yang ada di indonesia fokus di teknologi informasi
=> add school smk ti annajiyah bu jombang

lib/domains/ke/ac/must/students.txt
File upload to add a university to listed domains
=> upload a file to add Meru University to listed domains

lib/domains/org/cmasas.txt
Contact Information:
503.226.7374
866.920.1619 (fax)
info@cmasas.org
5200 SW Meadows Rd. Ste. 150
Lake Oswego, OR 97035
=> Added Christa McAuliffe Academy School of Arts and Sciences

lib/domains/np/edu/thamescollege.txt
Thames International College, is an academic institution located at Surya Bikram Gyawali Mard, Old Baneswor, Kathmandu, Nepal offering a variety of undergraduate programs that leads to a degree from Tribhuvan University
Website: https://thamescollege.edu.np/
=> Added Thames College

lib/domains/pk/edu/uop.txt
Adding university of Peshawar for students to JetBrains.
=> Adding university of Peshawar

lib/domains/id/sch/smkpgripekanbaru.txt
Let's add a contributing file, so we can work, together!
=> Add SMK PGRI Pekanbaru to list

lib/domains/tn/u-monastir/fsegma.txt
Add FSEGMA to the university of monastir repository in Tunisia
=> Add Faculty of management

lib/domains/ke/ac/mpesafoundationacademy.txt
=> Added Mpesa Foundation Academy

lib/domains/ro/colegiulbanatean.txt
Colegiul Banatean Timisoara
Official web site 
http://www.colegiulbanatean.ro/
http://www.colegiulbanatean.ro/oferta-educationala/liceal/
http://www.colegiulbanatean.ro/prezentare/organigrama/catedre/
=> Add Colegiul Banatean Timisoara

lib/domains/cr/ac/ulead.txt
Adding Lead University from Costa Rica
=> Adding Lead University

lib/domains/ph/edu/stjude.txt
Active Domain of the School: https://www.stjude.edu.ph/
=> Adding STJUDE to the domain

lib/domains/it/unimercatorum.txt
=> add domain mercatorum.it

lib/domains/mx/edu/miutt.txt
Universidad Tecnologica de Tijuana
https://uttijuana.edu.mx/
Right now ut-tijuana.edu.mx is the main students email domain which is being assigned to new enrolled students (**this one was already added to the repo**).
But I would like to add miutt.edu.mx because its an old email domain which is still being used for some students who joined a couple years ago.
=> Added Universidad Tecnologica de Tijuana

lib/domains/hu/zipernowsky.txt
Added BMSZC Zipernowsky Károly Műszaki Technikum to domains/hu
=> Added zipernowsky.txt

lib/domains/ph/edu/palawan/psu.txt
Webiste link: https://psu.palawan.edu.ph/
=> Palawan State University

lib/domains/ph/edu/ust-legazpi.txt
Following instructions to add the school
=> feat: add ust-legazpi.txt

lib/domains/hk/edu/kis/is.txt
School: Korean International School (International Section)
School Website: https://kis.edu.hk
* Primary School (does not have school emails),
* Middle School,
* High School
=> Korean International School

lib/domains/ua/edu/ontu.txt, lib/domains/ua/edu/ontu/cloud.txt
Two files were created for one university: ua/edu/ontu.txt and ua/edu/ontu/cloud.txt
The Odesa National Academy of Food Technologies was reorganized and now renamed Odesa National University of Technology.
=> Add ONTU to the project

lib/domains/vn/edu/fitus/clc.txt
=> Add CLC - HCMUS

lib/domains/ua/edu/chpt.txt
Cherkasy Polytechnic Applied College
=> chpt.edu.ua domain added

lib/domains/in/itmvu.txt
http://itmvu.in/
Go to B.tech link from footer
=> Added itm vocational university

lib/domains/de/hs-gm.txt
Website
https://www.hs-geisenheim.de/en/
Unfortunately, there is no dedicated course relating to IT but many programs deal with statistics and IT systems.
Overview of degree programs: https://www.hs-geisenheim.de/en/studies/prospective-students/overview-of-degree-programs/
Website with example email domain: https://www.hs-geisenheim.de/en/footer/contact/
=> add domain file

lib/domains/bg/rndc.txt
=> Add Rakovski National Defence College

lib/domains/de/gsp-ploen.txt
Homepage: https://gymnasium-ploen.de/
Recognizes email: https://gymnasium-ploen.de/kollegium#:~:text=vorname.nachname%40gsp%2Dploen.de
IT related course: https://gymnasium-ploen.de/schule-des-jahres-2022#:~:text=Informatikunterricht%20in%20Klassenstufe%207
=> Added gsp-ploen.de

lib/domains/cn/ac/tfswufe.txt, lib/domains/cn/edu/tfswufe.txt
school website：https://www.tfswufe.edu.cn/index.htm
email example：**@tfswufe.edu.cn
=> The school domain name has changed, and the original domain name has been registered by others

lib/domains/ua/edu/dspu.txt
Added DSPU
https://dspu.edu.ua/eng/
https://goo.gl/maps/NEgqRD7BvDEB8uaX9
=> added Ukrainian DSPU

lib/domains/cr/ac/utn.txt
Domain: https://utn.ac.cr/
Universidad Tecnica Nacional.
Software engineering degree: https://utn.ac.cr/content/ingenieria-software-tecnologias-informaticas
=> UTN domain

lib/domains/ve/edu/unet.txt
Official Site: http://www.unet.edu.ve/
History: http://www.unet.edu.ve/institucion/historia.html
Pensum (Software Engineering): http://www.unet.edu.ve/informatica/Pensum.php
Students portal: https://control.unet.edu.ve/
=> UNET (Universidad Nacional Experimental del Tachira)

lib/domains/us/mi/k12/oakland.txt, lib/domains/us/mi/k12/oakland/student.txt
Adds Student email and teacher email.
student email is as follows: student@student.oakland.k12.mi.us
teacher email is as: follows teacher@oakland.k12.mi.us
=> Oakland Technical Campus Northwest

lib/domains/ke/ac/kisiiuniversity.txt
=> Kisii University

lib/domains/uk/ac/sthelens/students.txt
Added St Helens College (England, UK)
=> St Helens College

lib/domains/net/trinityhigh.txt
Website: https://www.trinity.worcs.sch.uk/
General Enquiries - office@trinityhigh.net
=> Add trinity high via file upload

lib/domains/id/sch/smaasbsolo.txt
School URL: [https://smaasbsolo.sch.id/](SMA Al Azhar Syifa Budi Solo)
=> SMA Al Azhar Syifa Budi Solo

lib/domains/pk/edu/mehrancolleges.txt
Files for mehrancolleges.edu.pk
=> Mehran Colleges files via upload

lib/domains/pe/edu/khipu.txt
Añadiendo Superior Privado Instituto Khipu
=> Añadiendo Instituto Khipu

lib/domains/org/norfolkacademy.txt
I love jetbrains products, it would be nice to get some free stuffs :)
Heres some links:
https://www.norfolkacademy.org/academics/upper-school - This includes some course offerings, CTRL+F "computer science" (also proves we offer high edu)
=> Add norfolk academy - Link included.

lib/domains/com/isbatuniversity.txt
This is the international School of Business and Technology found in kampala. the website is isbatuniversity.ac.ug
=> isbat university kampala (ISBAT)

lib/domains/mx/edu/yavne.txt
=> Colegio Isralita Yavne

lib/domains/mx/edu/tecmm/zapopan.txt
**University official website URL:** https://zapopan.tecmm.edu.mx/
**IT-related course is offered by the university:** https://tecmm.edu.mx/Carrera/Ingenieria-en-Sistemas-Computacionales
=> Add TecMM Unidad Academica Zapopan zapopan.tecmm.edu.mx

explore.txt, lib/domains/academy/explore.txt
=> Add Explore academy

lib/domains/uk/ac/morley.txt
Hello Dear,
Could you please add our college to the list? Our official website is https://www.morleycollege.ac.uk/ and our college do offer IT and Software courses including AI. Link to courses are https://www.morleycollege.ac.uk/courses/
Best regards.
=> Adding Morley College London

lib/domains/ph/edu/isatu/students.txt
Adding Iloilo Science and Technology University to the list.
=> Iloilo Science and Technology University

lib/domains/mx/edu/uaslp/alumnos.txt
* Official website: https://www.uaslp.mx/
* IT career: https://www.ingenieria.uaslp.mx/CienciasComputacion/Paginas/Oferta-Academica/4456#gsc.tab=0
=> Universidad Autonoma de San Luis Potosi added

lib/domains/org/elcachargers.txt
Eagles Landing Christian Academy
=> Adds Eagles Landing Christian Academy

lib/domains/edu/austincc/g.txt
Official site: https://www.austincc.edu
Link to CS & IT programs: https://www.austincc.edu/academic-and-career-programs/areas-of-study/computer-science-and-information-technology
Proof of email domain: https://www.austincc.edu/help/accmail
Relevant text in link:
IMPORTANT: The assigned format for ACC student email (ACCmail) is firstname.lastname @ g.austincc.edu.
=> Added Austin Community College file and folder

lib/domains/fr/42perpignan/student.txt
Hi, can you please add 42 Perpignan to the list of allowed schools
=> Add 42Perpignan school

lib/domains/pk/edu/crescentschool.txt
=> Adding crescent model school From Lahore Pakistan

lib/domains/pe/edu/untrm.txt
**Official Website:** https://www.untrm.edu.pe
**Faculty of Systems Engineering and Electrical Mechanics:** https://www.untrm.edu.pe/en/facultades/sistemas-mecanica/143-pregrado/ingenieria-de-sistemas.html
=> Add Toribio Rodríguez de Mendoza de Amazonas

lib/domains/vn/edu/mindx.txt
Offical website: https://mindx.edu.vn/
=> Add MindX Technology School
