lib/domains/eg/edu/oi.txt
=> ADD:: oi domain

lib/domains/mx/edu/universidadupp.txt
following the instruction ,I provide extra information, which i hope help you to accept the pull request:
- the university official website URL: https://www.universidadupp.edu.mx/
- a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university : https://www.universidadupp.edu.mx/oferta-educativa/ingenieria-en-desarrollo-de-software
=> add Universidad Privada de la Península (UPP)

lib/domains/mx/edu/uas.txt
Universidad Autonoma de Sinaloa
uas.edu.mx
mario.rangel@uas.edu.mx
- [X ] Academic/Teaching Staff
University
Master
PhD
- [X ] Post-graduate research
- [X ] College (University) or Undergraduate School or equivalent
=> Universidad Autonoma de Sinaloa Added

lib/domains/ph/edu/vsu.txt
vsu.edu.ph
Visayas State University, Philippines
=> Visayas State University 

lib/domains/ph/edu/informatics.txt
Website: https://informatics.edu.ph/
informatics.edu.ph
Informatics Philippines
=> adding Informatics Philippines

lib/domains/pe/edu/istrfa.txt
Please check the url of the institute
https://istrfa.edu.pe/web/
=> Add to I.S.T.R.F.A

lib/domains/tr/edu/alanyauniversity.txt
alanyauniversity added to the repo
=> alanyauniversity

lib/domains/mx/lania.txt
This is the application to add LANIA school to the list of mailing domains to obtain a student license.
Here is the page with the section that offers the master's degree in applied computer science
https://www.lania.mx/?page_id=7972
=> https://www.lania.mx/?page_id=7972

lib/domains/ca/ab/cbe.txt
Calgary Board of Education
Website: https://cbe.ab.ca
IT related courses: https://www.cbe.ab.ca/programs/program-options/Documents/CTS-KE-Occupational-Pathways-High-School-Facilities.pdf
=> Added CBE domain file

lib/domains/ro/armyacademy.txt
PR for https://www.armyacademy.ro/
Academia Forțelor Terestre Nicolae Bălcescu
Thank you!
=> PR for armyacademy.ro

lib/domains/ke/ac/embuni/student.txt
Am a student excited to use JetBrains products in my learning
https://embuni.ac.ke/
=> Added Embu University

lib/domains/ph/edu/newbrighton.txt
official website: https://newbrighton.edu.ph
IT related course is offered: https://newbrighton.edu.ph/college
=> add newbrighton.txt

lib/domains/vn/edu/dhtm.txt
=> Thuongmai University

lib/domains/id/sch/sman1samarinda.txt
https://www.sman1samarinda.sch.id
https://dapo.kemdikbud.go.id/sekolah/0BA7B7F2831087ED19D3
https://referensi.data.kemdikbud.go.id/tabs.php?npsn=30401066
https://sekolah.data.kemdikbud.go.id/index.php/chome/profil/498fbe5d-a6c0-489a-9477-2bd6e198fab0
=> SMAN 1 Samarinda

lib/domains/pk/edu/nfciet.txt
Added my institute in domains list
=> Added NFCIET

lib/domains/kr/hs/shinsung.txt
=> Adding ShinSung High School

lib/domains/au/edu/imc.txt
Please add 'imc college' ([Australian National Institute of Management and Commerce])
official website: https://www.imc.edu.au/
=> imc college added

lib/domains/pk/edu/bbsul.txt
Government University offering four years Degree in Computer Science and IT. 
https://bbsul.edu.pk/department_singlepage.php?id=3
=> Adds bbsul.edu.pk domain in jetbrains repo

lib/domains/de/wwschool/gisny.txt, lib/domains/it/istruzioneer/roiti.txt
This is my school in Ferrara, Italy
=> Create Roiti.txt inside "it/istruzioneer"

lib/domains/com/signesetformations.txt
official website : https://www.signesetformations.com/
official training course of developers : https://www.signesetformations.com/formation-webdesigner-pour-les-sourds-langue-des-signes/webdesigner-developpeur-web/
=> ajout signes & formations

lib/domains/ph/edu/csucc.txt
=> Add Caraga State University Cabadbaran City

lib/domains/kr/ac/kku.txt
Added Konkuk University Glocal campus
=> added Konkuk University Glocal campus

lib/domains/id/sch/smafg.txt
Please add our school to jetbrains institution list for us to teach & learn
our official website is in https://smafg.sch.id/ that we reditect to https://smafuturegate.com but https://smafg.sch.id/ is registered officialy to our school.
we use smafg.sch.id for our e learning and currently we're running a programming bootcamp.
please check https://bootcamp.smafg.sch.id/ and https://www.instagram.com/p/Cm4E-nnP42Y/
Best Regard
Lutfi
Head Of IT Development
=> add SMA Future Gate Bekasi West Java Indonesia

lib/domains/ph/edu/lpunetwork.txt
Official University website https://www.lpu.edu.ph/
Office 365 emails of students ends with @lpunetwork.edu.ph
=> Add Lyceum of the Philippines University

lib/domains/cat/iesterrassa.txt
Adding Institud de Terrassa(IESTerrassa)
=> Add file via upload - Adding Institud de Terrassa

lib/domains/br/fgvmail.txt
Add Fundacao Getulio Vargas as fgvmail.br, as is fgv.br
=> Add Fundacao Getulio Vargas as fgvmail.br

lib/domains/ch/ssbm.txt
Adding SSBM Geneva university (Swiss School of Business and Management Geneva)
=> Add files via upload - Adding SSBM Geneva university (Swiss School of Business and Management Geneva)

lib/domains/id/sch/smkmaliga.txt
https://dapo.kemdikbud.go.id/sekolah/F0150A4EF8E04C2B4F09
https://referensi.data.kemdikbud.go.id/tabs.php?npsn=69889006
https://sekolah.data.kemdikbud.go.id/index.php/Chome/profil/D47003DE-D29D-4A0A-8C30-3D20B73446BB
=> Add SMK Maarif 5 Kotagajah

lib/domains/ph/edu/cvsu.txt
IT course offered (>1 year): https://cvsu.edu.ph/course-offerings/
=> Other necessary informations

lib/domains/it/istruzioneer/iccodigoro.txt
Istituto Comprensivo di Codigoro (FE)
https://iccodigoro.edu.it
=> Added institute domain: iccodigoro.istruzioneer.it

lib/domains/cz/geukaplice.txt
Website: https://geukaplice.cz
=> Adding SOŠ a SOU Kaplice

lib/domains/com/42urduliz.txt
Created by JOKITON.
Thank you JetBrains!
=> Created 42 Urduliz Token

lib/domains/mn/edu/mandakh.txt
School webshites
MN: https://mandakh.edu.mn/
EN:  http://en.mandakh.edu.mn/
=> added mandakh.txt

lib/domains/np/edu/tuicms.txt
- Institute of Crisis Management Studies based on Tribhuvan University
- IT course: https://www.tuicms.edu.np/bachelor-in-computer-application.html
=> Add TUICMS

lib/domains/ve/edu/uptm.txt
Hi, add new university from the city Mérida, Ve.
=> added the university uptm.edu.ve

lib/domains/nz/school/wakatipu.txt
=> wakatipu high school

lib/domains/np/edu/tu/cct.txt
Add Central Campus of Technology  to list.
College official website: http://cctdharan.edu.np/ College Email Domain  http://cct.tu.edu.np/
college listed in Institute of Science and Technology  https://tuiost.edu.np/college/constituent
=> Update My college : Central Campus of Technology

lib/domains/org/dcp.txt
This is not a University but a High School level institution whose mission is to prepare students for college. Further details at https://www.dcp.org/
=> Add a file for Downtown College Preparatory

lib/domains/in/ltce.txt
Long term course offered: https://ltce.in/com_dep_about
=> Added ltce.txt

lib/domains/net/elisava.txt
Website: https://www.elisava.net
=> Add Fundació Privada Elisava Escola Universitària

lib/domains/pl/kwiatek365.txt
School site: https://kwiatek.edu.pl/
=> Add kwiatek365 domain

lib/domains/ba/edu/cetvrta-gimnazija.txt
URL of School's Website: https://cetvrta-gimnazija.edu.ba/
URL of list of subjects for IT program: https://cetvrta-gimnazija.edu.ba/wp-content/uploads/2019/04/IT-smjer.pdf
Screenshot of dedicated IT subjects:
=> Add Cetvrta gimnazija Ilidza to domains

lib/domains/mx/edu/lasallebajio.txt
University Domain : https://www.lasallebajio.edu.mx/
IT courses and careers :
https://www.lasallebajio.edu.mx/oferta/oferta1.php?n=1&p=42
https://www.lasallebajio.edu.mx/oferta/oferta5.php?n=6&p=46
https://www.lasallebajio.edu.mx/oferta/oferta5.php?n=6&p=21
https://www.lasallebajio.edu.mx/oferta/oferta1.php?n=1&p=42
=> Add lasallebajio.txt

lib/domains/pl/szczecin/am.txt, lib/domains/pl/szczecin/pm.txt
**Akademia Morska w Szczecinie** changed it's name to **Politechnika Morska w Szczecinie**
=> Updated Maritime University of Szczecin

lib/domains/ph/edu/evsu.txt
EVSU is Eastern Visayas State University from Philippines
=> Added EVSU to domains, for pull request

lib/domains/mx/edu/utn/alumnos.txt
Could you please add my college?: 
**Universidad Tecnológica de Nezahualcóyotl.** 
Kind regards, :)
=> Request add: Universidad Tecnológica de Nezahualcóyotl

lib/domains/de/bs1in.txt
Staatliche Berufsschule I Ingolstadt
bs1in
Thank you for your work!
=> Please add Staatliche Berufsschule I Ingolstadt

lib/domains/np/edu/hsm.txt
I added my college affiliated with Tribhuvan University i.e. Hetauda School of Management.
There are thousands of students at our college who are missing out on the chance to truly work with professional IDEs.
Hence, I ask you to consider adding my college name.
=> College "Hetauda School of Management" added

lib/domains/ph/edu/smciligan/my.txt
=> Request to add St. Michael's College

lib/domains/org/seafordhead.txt
Add Seaford head School, East Sussex, UK
=> Add Seaford head School, East Sussex, UK

lib/domains/mx/edu/universidadlatino/alumno.txt
agregar la universidad latino con el dominio de ejemplo:
...@alumno.universidadlatino.edu.mx
pagina de la escuela:
https://www.universidadlatino.edu.mx/
=> agregarUniversidadLatino

lib/domains/it/cnr.txt
Add cnr.it domain to the swot list
=> (Italian) National Research Council

lib/domains/pl/domeyko.txt
School domain:
https://domeyko.edu.pl/ 
Student's school emails follow prefix.surname@domeyko.pl format
https://domeyko.edu.pl/kontakt page has contact email. By writing to this email you can hopefully verify that student's emails follow the format given above.
=> Add CXXII Liceum Ogólnokształcące Warsaw

lib/domains/com/caistorgrammar.txt
https://www.caistorgrammar.com/
=> Add Caistor Grammar School

lib/domains/org/isneu.txt
=> Add isneu.text

lib/domains/ie/stepasideetss.txt
Adding new secondary school in Ireland:
Stepaside Educate Together Secondary School
=> adding Stepaside Educate Together Secondary School

lib/domains/mx/edu/ives.txt
Somos una universidad fundada hace más de dos décadas por el Dr. Carlos Arturo Luna Escudero y un grupo de mexicanos comprometidos con la educación
=> Please add IVES University

lib/domains/it/edu/studenti-ittfedifermi.txt
School website: https://www.ittfedifermi.edu.it/
Inside the school website there are all the courses and between them there's the IT one
=> Added ITTS Fedi Fermi Pistoia

lib/domains/edu/thapar.txt, lib/domains/edu/tiet.txt
College added- Thapar Institute of Engineering & Technology (TIET), Patiala
| Commit  |  College Website | Course page   | Email page  | 
|---|---|---|---|
| bc714a8215003603018117a03de5306f18e8f221  | https://www.thapar.edu/  | https://www.thapar.edu/academics   | https://www.thapar.edu/pages/contactus  |  
Signed-off-by- swastik <swastkk@gmail.com>
=> Thapar University added

lib/domains/cn/edu/zafu.txt
added the following university to the domain: zafu.txt. Official website https://https://en.zafu.edu.cn/ 
Computer Science program introduction: https://en.zafu.edu.cn/info/1012/1071.htm which offers undergraduate program and masters program.
=> Create zafu.txt 

lib/domains/ru/chgaki.txt, lib/domains/ru/chgik.txt
University's Link 1: https://chgik.ru
University's Link 2: https://chgaki.ru
It Course Link 1: https://chgik.ru/guidebook/bibliotechno-informacionnaya-deyatelnost-0
It Course Link 2: https://chgik.ru/guidebook/bibliotechno-informacionnaya-deyatelnost-3
Email Business Domain: https://biz.mail.ru/login/chgaki.ru
=> Added The Chelyabinsk State Institute of Culture and Arts

lib/domains/np/edu/tu/sdc.txt
Shanker Dev Campus Added for the jetbrains licence
=> Shanker dev campus added

lib/domains/uk/sch/oxon/warriner.txt
At lib\domains\uk\sch\oxon\warriner.txt
=> Request addition of school.

lib/domains/us/de/k12/charter/ncs.txt
[ncs_email_domain.pdf](https://github.com/JetBrains/swot/files/11142931/ncs_email_domain.pdf)
Official letter from school confirming email domain is attached. Please approve the request
=> Please add Newark charter school delaware

lib/domains/uk/ac/scarboroughtec.txt
Website: https://scarboroughtec.ac.uk/
Long time IT courses:
1. (game development) https://scarboroughtec.ac.uk/he-course/hnc-creative-media-production-game-development/
2. (computer science) https://scarboroughtec.ac.uk/full-time-course/computing/
The email domain is scarboroughtec.ac.uk
=> Add ScarboroughTEC

lib/domains/uk/ac/cnwl/student.txt
Adding College of North West London
=> Add College of North West London to list of authorized colleges 

lib/domains/ie/universityofgalway.txt
https://www.universityofgalway.ie/courses/undergraduate-courses/computer-science-and-information-technology.html
=> Add new domain for universityofgalway

lib/domains/rs/edu/mef.txt
mef.edu.rs - 11000 Belgrade, Serbia
=> Adding MEF faculty

lib/domains/np/edu/cit.txt
Added CITE college which is affiliated to Purbanchal University, website: https://cit.edu.np which is in Subidhanagar Tinkune Kathmandu that I believe fullfills all the criteria to be enlisted.
=> Added CITE college

lib/domains/au/com/wmac.txt
added au/com/wmac.txt
Not sure how the domain thing works, but it's wmac.com.au
=> Add WESTMAC to directory

lib/domains/tz/ac/aims.txt
added "swot/lib/domains/net/aims.txt" (African Institute for Mathematical Sciences (AIMS))
=> added "swot/lib/domains/net/aims.txt" (AIMS)

lib/domains/net/vvit.txt
Added new college Vasireddy Venkatadri Institute of Technology (VVIT)
=> added  "swot/lib/domains/net/vvit.txt" (Vasireddy Venkatadri Institute of Technology)

lib/domains/org/cummingtamilschool.txt
Please find the website for the school. https://www.cummingtamilschool.org/. The courses were yearly based, and students will learn the language in grades in parallel to their school year.
=> Added cumming tamil school to domain list

lib/domains/mx/edu/bab.txt
This is to add my domain educational
=> bab.edu.mx

lib/domains/in/edu/mujonline.txt
University's Link: https://www.onlinemanipal.com/np
It Course Link: https://www.onlinemanipal.com/np/bachelor-of-computer-applications
Domain recognition: https://ibb.co/D9HYZPN
=> add manipal university jaipur

lib/domains/np/edu/nou.txt
What the PR does ?
Adds nou.txt file to the lib/domains/np/edu directory
More details to the university
University website: https://nou.edu.np/
Faculty: https://nou.edu.np/faculty-of-science-health-technology
[Course Information.pdf](https://github.com/JetBrains/swot/files/11172701/tddbl7dz7yccxnh7.pdf)
=> Request to add Nepal Open University in domain list

lib/domains/org/phoenixunion/student.txt
add phoenixunion to the Jetbrains student program, allowing users from ```phoenixunion.org``` to access Jetbrains products.
=> Add Phoenix union high school district

lib/domains/edu/schoolcraft/apps.txt
Request to add apps.schoolcraft.edu
=> Add apps.schoolcraft.edu

lib/domains/org/mvsd21.txt
School websites:
https://www.mvsd21.org/
https://mveagles.org/
=> Added Marsh Valley High School, McCammon Idaho

lib/domains/mx/edu/cbtis217.txt
Please add Centro de Bachillerato Tecnológico Industrial y de Servicios 217, also known as CBTis 217.
=> Add CBTis 217

lib/domains/mx/edu/e-itesca.txt
Added e-itesca.edu.mx domain that that belongs to ITESCA (INSTITUTO TECNOLÓGICO SUPERIOR DE CAJEME)
=> Add e-itesca.edu.mx domain

lib/domains/mx/edu/cimav.txt
Pull request for The Center for Research in Advanced Materials (Centro de Investigación en Materiales Avanzados, Cimav) in Mexico.
Cimav is part of the CONACYT (National Council for Science and Technology) in Mexico.
Thanks!
=> Fork for CIMAV

lib/domains/ug/ac/ush.txt
This file is for adding the domain of the University of Sacred Heart Gulu to JetBrains Domains
=> University of the Sacred Heart Gulu

lib/domains/co/edu/laarboleda.txt
Web site: https://laarboleda.edu.co
=> Adding Colegio La Arboleda

lib/domains/tn/usf/isims.txt
Institut Supérieur d'Informatique et de Multimédia de Sfax
www.isimsf.rnu.tn
- [ x ] Students
- [ x ] Academic/Teaching Staff
- [x  ] College (University) or Undergraduate School or equivalent
[isims.txt](https://github.com/leereilly/swot/files/11270333/isims.txt)
[isims.txt](https://github.com/leereilly/swot/files/11270337/isims.txt)
=> Update ISIMS domain

lib/domains/mx/edu/cecati19.txt
- Official website: http://www.dgcft.sems.gob.mx/buscador_cecati/plantel/101 (Federal website (Mexico) with general information about the institutions)
- Emails provided to alumni and teachers on the 19 plantel: cecati19.edu.mx
- Educational programs: 
http://www.dgcft.sems.gob.mx/buscador_cecati/curso/22408
I plan to teach students web development with the aid of the Jetbrains IDE, I find it easier to install and offers more features than vscode.
- Proof of domain request:
=> add cecati19.edu.mx for revision purposes

lib/domains/com/ifnti.txt
Can you add IFNTI university from togo
=> add ifnti togo

lib/domains/ph/edu/aclcbutuan.txt
ACLC College of Butuan 
> - Website: http://www.aclcbutuan.edu.ph/ 
> - Facebook page: https://web.facebook.com/aclcbutuan/
ACLC College
> - Website: http://www.aclc.edu.ph/
> - Courses Offered: http://www.aclc.edu.ph/p/courses-offered.html
=> Add ACLC College of Butuan

lib/domains/np/edu/lict.txt
University/Campus official website URL - https://lict.edu.np/
Course - https://lict.edu.np/bsc-csit/
"showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students"
=> Add Lumbini ICT Campus

lib/domains/nz/rollestoncollege.txt
Add rollestoncollege.txt in /lib/domains/nz/ this is to add rollestoncollege.nz
=> Rolleston College

lib/domains/org/tbshs.txt
The Bishops Stortford High school:
site with comp-sci course: [https://tbshs.org/gallery/computer-science](https://tbshs.org/gallery/computer-science/)
Site that show email recognition: [https://tbshs.org/email-safe-senders-list](https://tbshs.org/email-safe-senders-list/)
=> Add tbshs.org domain

add_toulouse_INP/lib/domains/fr/toulouse-inp.txt, lib/domains/fr/toulouse-inp.txt
University URL: https://www.inp-toulouse.fr/en/index.html
a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: https://www.enseeiht.fr/fr/formation/masters/performance-in-software-media-and-scientific-computing-psmsc.html
a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students: https://www.inp-toulouse.fr/fr/contacts.html
=> Add Toulouse INP 

lib/domains/org/psdschools.txt
=> Poudre School District

lib/domains/kr/go/goe/hanambizh.txt
hanambizh.goe.go.kr add a domain
=> hanambizh add a domain

lib/domains/be/ksdiest.txt
Please add my domain ksdiest.be
=> Add ksdiest.be domain

lib/domains/mx/edu/ict.txt
add ict.txt for Instituto Cultural Tampico A.C. whit domain ict.edu.mx
=> Add ict.txt for Instituto Cultural Tampico

lib/domains/id/ac/pdbi.txt
> Website: https://www.pdbi.ac.id
=> Add Politeknik Digital Boash Indonesia

lib/domains/college/barker.txt
https://www.barker.college/
https://www.barker.college/student-life/secondary-school/elective-choices/information-and-software-technology
=> Add Barker College

lib/domains/np/edu/vac.txt
College/School : Vishwa Adarsha Academy
Domain Name: https://vac.edu.np/
IT Related Program URL: https://college.vac.edu.np/bca
Please Add ASAP thank you
=> Vishwa Adarsha Academy vac.txt

lib/domains/br/unisinos/edu.txt
- the university official website URL, if it is different from the domain you are submitting: https://www.unisinos.br/
- a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: https://www.unisinos.br/graduacao/ciencia-da-computacao/sao-leopoldo
- a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students: I'm posting some ss of proof that the e-mail that I use is for institutional purposes, UNISINOS is part of the "Jesuítas Brasil" network, that include some High Schools, Colleges and other institutions, so in some screenshots it may show "Jesuítas Brasil" as the logo/trademark.
=> Including Unisinos Domain

lib/domains/id/sch/sekolahathalia.txt
It is an Indonesian School called "Sekolah Athalia"
Domain: https://sekolahathalia.sch.id/
Contact: https://sekolahathalia.sch.id/kontak/
Official Email School: _admin@sekolahathalia.sch.id_
=> add sekolahathalia

lib/domains/mn/edu/mnun.txt
It is a Mongolian university named 'Mongolian National University'.
Home page: https://mnun.edu.mn/
For IT courses look here: https://mnun.edu.mn/school-of-information-technology-design/
For domain proof look at the contacts page: https://mnun.edu.mn/contacts/
=> Add Mongolian National University

lib/domains/ke/ac/scott/students.txt
Add https://scott.ac.ke/ domain
=> Add Scott Christian University

lib/domains/at/ksn/fbs.txt
Fachberufsschule 1 Klagenfurt
technical vocational school 1 klagenfurt
application development branch:
https://fbs-klagenfurt1.at/applikationsentwicklung-coding/
picture: email acceptance proof:
https://i.postimg.cc/pVh2XJ3J/Email-Proof-Teams-Screenshot.png
=> added Fachberufsschule 1 Klagenfurt

lib/domains/ca/qc/stanislas.txt
College Stanislas de Montréal
https://stanislas.qc.ca/
firstname.name@stanislas.qc.ca
- [x ] Academic/Teaching Staff
- [x ] College (University) or Undergraduate School or equivalent
- [x ] High School or equivalent
- [ x] Elementary School or equivalent
=> Add stanislas.txt

lib/domains/ve/edu/unexpo.txt
Universidad Nacional Experinmental Antonio Jose de Sucre
Antonio Jose de Sucre National Experimental University
{Website URL}
=> add unexpo

lib/domains/th/ac/ps.txt
=> add Potisarnpittayakorn School

lib/domains/com/pierrerouge.txt
Add Saint Joseph Pierre Rouge a French high school near Montpellier.
=> Add Saint Joseph Pierre Rouge

lib/domains/uk/org/stpetersyork.txt
Added St Peters, York to UK/ORG
=> St Peters York

lib/domains/hu/szigbp/diak.txt
Szent István Gimnázium Budapest
https://szigbp.hu/
email: @diak.szigbp.hu
=> diak.szigbp.hu

lib/domains/ro/cniasi.txt
This is the official website of my school - [colegiulnationaliasi.ro](http://www.colegiulnationaliasi.ro/). As a student of this high school, I am attending the[ "Excellence in Computer Science"](http://ler.is.edu.ro/~cex_is/pregatire.html) center. A list of all enrolled students can be found [here](http://ler.is.edu.ro/~cex_is/elevi.html), where my school's name is written as "COLEGIUL NAȚIONAL", Iasi (the city's name) being omitted since all students are from this city. 
I hope this is enough proof, I can come back at anytime with more details!
=> Add domain cniasi.ro

lib/domains/by/uoggmk.txt
Greetings, I decided to add another version of my college name.
Also, please note that even though my college is on this list, when I try to renew my license using my email with the domain of my college, I don't get any messages to it. My classmates are not getting any emails from JetBrains either. 
Maybe there is some kind of error or bug, please check it out.
Thank you.
=> Updated uoggmk.txt. Added another version of the college's name

lib/domains/edu/lccc.txt
Lehigh Carbon Community College
=> Created lccc.txt

lib/domains/in/mrce.txt
Added Malla Reddy College of Engineerinag University domain for Student verification
=> Added Malla Reddy College of Engineerinag University domain for Student verification

lib/domains/id/sch/smkn10jakarta.txt
School Profile Website: smkn10jakarta.sch.id
=> feat: add smkn10jakarta domain

lib/domains/kh/edu/aupp.txt
Official website URL: https://www.aupp.edu.kh/
Course URL: https://www.aupp.edu.kh/bachelors-programs/
=> Add AUPP to kh/edu domain

lib/domains/lt/vilniustech.txt
Vilnius Tech
https://vilniustech.lt/index.php?lang=2
Teacher email domain is: @vilniustech.lt
Student email domain is already present: @stud.vilniustech.lt
One of the IT related courses
(Study form must be selected to [Full-time studies (four years studies)])
https://vilniustech.lt/studies/study-programmes/bachelor-and-integrated-study-programmes/317407?element_id=320665&sp_id=340&f_id=1&qualification=a%3A2%3A%7Bi%3A0%3Bs%3A1%3A%22B%22%3Bi%3A1%3Bs%3A1%3A%22A%22%3B%7D#Modules
Vilnius Gediminas Technical University
Saulėtekio al. 11, LT-10223 Vilnius
For international students: +370 5 274 5026, [tsc@vilniustech.lt](mailto:tsc@vilniustech.lt)
For general information: +370 5 274 5030, [vilniustech@vilniustech.lt](mailto:vilniustech@vilniustech.lt)
Fax +370 5 270 0112
Legal entity code …
=> Vilnius Tech

lib/domains/pl/edu/gwsp.txt
Added file for Górnośląska Wyższa Szkoła Przedsiębiorczości im. Karola Goduli
=> Added GWSP

lib/domains/cy/ac/euc/students.txt
Added European University of Cyprus for students
=> Added European University of Cyprus

lib/domains/com/churchdownschool.txt
https://www.churchdownschool.com/
=> Churchdown School

lib/domains/th/ac/kru.txt
Add the demonstration school of kanchanaburi rajabhat university
http://dskru.kru.ac.th/
=> Add the demonstration school of kanchanaburi rajabhat university

lib/domains/br/edu/univassouras.txt
https://universidadedevassouras.edu.br/   <- University Official Web Page
https://universidadedevassouras.edu.br/graduacoes/engenharia-de-software/ <- Software Engineering course
https://universidadedevassouras.edu.br/e-mail-academico/ <- academic email proof
=> Universidade de Vassouras

lib/domains/ph/edu/capsu.txt, lib/domains/ph/edu/purisima.txt
=> Adding local schools in Capiz

lib/domains/uk/ac/loucoll/student.txt
website: https://www.loucoll.ac.uk
emails: ...@student.loucoll.ac.uk
sixth form and undergraduate courses, in computer science and otherwise
=> Add Loughborough College

lib/domains/ge/newvision.txt
=> New Vision University

lib/domains/kh/edu/puthisastra.txt
https://www.puthisastra.edu.kh/ <- University Official Web Page
https://www.puthisastra.edu.kh/faculty-of-business-entrepreneurship-technology/ <- IT course
=> Added University of Puthisastra

lib/domains/ph/edu/national-u/students.txt
Website: https://national-u.edu.ph
FB Page: https://web.facebook.com/NationalUniversityPhilippines
https://national-u.edu.ph/nu-lipa/computing-and-information-technologies/bachelor-of-science-in-information-technology/
=> Add National-U Philippines

lib/domains/id/sch/utschool.txt
UT School is a education institution since 2008. Start 2020, UT School add IT Class to their education program.
=> UT School Domain

lib/domains/eu/kgs-schneverdingen.txt
Added the KGS Schneverdingen to domains/eu/
=> Added KGS Schneverdingen

lib/domains/cr/ac/castrocarazo.txt
Main web site:
https://www.castrocarazo.ac.cr/
Careers: 
https://www.castrocarazo.ac.cr/web/oferta-academica/carreras/informatica/bachillerato-en-ingenieria-informatica
https://www.castrocarazo.ac.cr/web/oferta-academica/carreras/informatica/licenciatura-en-ciencias-de-la-computacion-con-enfasis-en
https://www.castrocarazo.ac.cr/web/oferta-academica/carreras/informatica/licenciatura-en-tecnologias-estrategicas-de-informacion-y
=> Add Universidad Castro Carazo

lib/domains/mx/edu/tua.txt
Please add my university domain to your list.
=> https://tua.edu.mx/ added

lib/domains/it/edu/matteirho.txt
[file.zip](https://github.com/JetBrains/swot/files/11505973/file.zip)
https://matteirho.edu.it/
https://matteirho.edu.it/corsi-serali-mattei-rho-milano/informatica-serale/
=> Adding domain matteirho

lib/domains/de/bs19hh.txt
website: https://www.bs19hamburg.de/
=> Added bs19hh.de

lib/domains/pk/edu/uow/student.txt
added university of wah email domain for student
=> University of wah email domain added for Pakistan

lib/domains/de/h2/stud.txt
Added "Hochschule Magdeburg-Stendal" aka "Magdeburg-Stendal University of Applied Sciences"
student-email addresses: ...@stud.h2.de
website: https://www.h2.de/en/home.html
=> Added Magdeburg-Stendal University of Applied Sciences

lib/domains/mx/edu/uais.txt
Universidad Autonoma Indigena de Mexico
=> Add files UAIS

lib/domains/fr/aege.txt
https://en.wikipedia.org/wiki/Economic_Warfare_School
domain aege.fr is for students, ege.fr for teachers
=> Ajout Ecole de guerre economique

lib/domains/id/sch/smkbinaessa.txt
SMK Bina Essa is Vocational High School in Indonesia that provide education majoring in: Teknik Bisnis Sepeda Motor (Motorcycle System and Business) and Otomatisasi Tata Kelola Perkantoran (Office Administration and Automation)
=> Add SMK Bina Essa

lib/domains/edu/spcollege.txt
the university official website URL, if it is different from the domain you are submitting
https://www.spcollege.edu/
a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university
https://www.spcollege.edu/future-students/degrees-training/technology/computer-information-technology
a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.
https://spcollege.edu/future-students/admissions/residency/residency-documents
=> Add spcollege.edu

lib/domains/ng/edu/babcock/pg.txt
This is a pull request to add .pg domain to babcock university
=> update babcock university with .pg domain

lib/domains/np/edu/academiacollege.txt
official domain: https://academiacollege.edu.np/
=> Add Academia International College

lib/domains/org/northeastacademy.txt
Add Northeast Academy for Aerospace and Advanced Technology (NEAAAT)
=> Add northeastacademy.org

lib/domains/uk/ac/law.txt
Adding University of Law to config
=> Add University of Law to config

lib/domains/com/goandalus.txt
Al Andalus private schools are all about learning and creating, the teachers and students are passionate about learning and applying new things every day. And I think the addition of JetBrains' software would make learning and applying much more productive.
=> Making JetBrains' software accessible to Goandalus students

lib/domains/id/sch/sekolahmuridmerdeka.txt, lib/domains/id/sch/smm.txt, lib/domains/id/sekolahmuridmerdeka.txt
Hello,
Our school has been migrate our email from @sekolahmuridmerdeka.id to @smm.sch.id
contact page : https://www.sekolahmuridmerdeka.id/bantuan/
Thank You
=> Domain name change

lib/domains/kh/edu/itc.txt, lib/domains/kh/edu/itc/gic.txt
ITC = Institute of Technology of Cambodia
=>  add university ITC at cambodia

lib/domains/com/ensworth.txt
Ensworth High School located in Nashville, TN. 
Website: [https://www.ensworth.com](url)
=> Add Ensworth High School

lib/domains/kr/djsch/dyshs.txt
=> Add Daejeon Yongsan High School

lib/domains/org/alamedaunified.txt, lib/domains/us/ausdg.txt
ausdg.us - Student Domain for AUSD (Alameda Unified School District)
alamedaunified.org - teacher and faculty domain for AUSD
=> Add ausdg.us and alamedaunified.org

lib/domains/rs/edu/gimnazijasm.txt
- Official website is the same domain as the email (gimnazijasm.edu.rs)
- Link to the computer major curriculum: https://gimnazijasm.edu.rs/ucenici_/smerovi/racunarski/ - here you are able to see that the high school offers 934 hours of classes related to computer science + unspecified number of hours for other subjects. At the bottom of the page there is also an image showing the curriculum for all 4 years of education
NOTE: Since the website is in Serbian, you can use something like google translate to be able to read it. I tried translating it to English from Serbian and it remains pretty authentic
=> Add gimnazijasm.txt

lib/domains/ua/edu/pdaa.txt
=> Poltava State Agrarian University

lib/domains/pe/edu/ue.txt
Let's add a contributing file, so we can work better, together!
This is the ESAN University website: https://www.ue.edu.pe/
=> Request for the addition of ESAN University PERU

lib/domains/id/ac/unimerz.txt
=> add Megarezky University

lib/domains/cat/bau/student.txt
BAU College of Arts and Design of Barcelona
https://www.baued.es
**More information:** 
https://es.wikipedia.org/wiki/BAU_Centro_Universitario_de_Dise%C3%B1o
https://www.baued.es/en/studies/masters-and-postgraduate-degrees/master-in-digital-experience-design
=> Adding the BAU College of Arts and Design of Barcelona

lib/domains/pl/edu/eppuz.txt
the university official website URL, if it is different from the domain you are submitting:  https://ppuz.edu.pl/
a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: https://ppuz.edu.pl/kandydat/kierunki-studiow/studia-i-stopnia/_informatyka_ekonomiczna_i/
a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students: https://ppuz.edu.pl/student/ppuz-online-ksztalcenie-zdalne/
(google classroom section)
=> add eppuz.txt

lib/domains/org/glenbrook225.txt
=> added Glenbrook North High School .txt file

lib/domains/pe/edu/jpardo.txt
#web
www.jpardo.edu.pe
https://jpardo.edu.pe/carreras/9-carreras/1-computacion-e-informatica
=> Add Institute Jose Pardo

lib/domains/ru/edu/agp.txt
AGP.EDU.RU Domain for Students and Teachers
=> Add AGP.EDU.RU Domain for Students and Teachers

lib/domains/id/sch/smkbwutalaga.txt
=> ADD SMKS BINA WIRA USAHA TALAGA

lib/domains/rs/edu/atvsspirot.txt
University Website: https://odsekpirot.akademijanis.edu.rs/
Page where IT related course is located: https://odsekpirot.akademijanis.edu.rs/osnovne/
Info document related to the IT related course 
https://odsekpirot.akademijanis.edu.rs/wp-content/uploads/2022/01/%D0%9A%D1%9A%D0%B8%D0%B3%D0%B0-%D0%BF%D1%80%D0%B5%D0%B4%D0%BC%D0%B5%D1%82%D0%B0-%D0%9F%D0%BE%D1%81%D0%BB%D0%BE%D0%BD%D0%B8-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%B8-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B8.pdf 
As domain for email is different that the website domain. Here the prof document that students are using domain on the added address. 
https://www.odsekpirot.akademijanis.edu.rs/wp-content/uploads/2021/10/Spisak-studenata-I-godine-za-skolsku-2021-22-OSS-vaspitaci.docx
=> Add atvsspirot.edu.rs

lib/domains/fr/eduhdf.txt
Add Edouard Branly Amiens high school, is a french school so cool ;).
Thanks you ♥
=> Add Edouard Branly high school

lib/domains/pk/edu/qu.txt
Please add my "Qarshi University"
=> https://www.qu.edu.pk/

lib/domains/np/edu/khwopa.txt
Request for adding khwopa college of engineering
website of the college:  https://khwopa.edu.np/
=> Add file for khwopa college of engineering

lib/domains/pl/edu/zsnr4.txt
Add email domain of Zespół Szkół Nr 4 im. Mikołaja Kopernika w Dębicy  (@zsnr4.edu.pl) to the list
=> Add new email domain: zsnr4.edu.pl

lib/domains/uk/ac/varndean.txt
Computer Science A Level - [link](https://varndean.ac.uk/courses/computing_a/)
And below is a screenshot of our Google Admin panel with our domains
=> Adding Varndean College

lib/domains/org/pacificcoastacademy.txt
Website: https://pacificcoastacademy.org/
=> Add files via upload: Pacific Coast Academy

lib/domains/id/ac/jak-stik.txt
You can access our university site at https://jak-stik.ac.id/
- [Informatics Management](https://jak-stik.ac.id/program-studi/manajemen-informatika)
- [Informatics System](https://jak-stik.ac.id/program-studi/sistem-komputer)
- [Computer System](https://jak-stik.ac.id/program-studi/sistem-komputer)
- [Magister](https://pascasarjana.jak-stik.ac.id/)
- [Ministry of Education Affairs](https://pddikti.kemdikbud.go.id/data_pt/ODA4MzNBOUUtREY4Ny00OTFELTg3NTYtRjNEM0ZGMTk0RjlE)
- https://jak-stik.ac.id
- Student Email (google)
=> add new jakstik email domain

lib/domains/am/42yerevan/student.txt
42 Yerevan is a branch of a 42.fr
You can contact us with info@42yerevan.am
Have a good day!!
=> Add Generated File

lib/domains/pk/edu/uot.txt
https://uot.edu.pk
https://uot.edu.pk/programs/bscs
=> uot.edu.pk

lib/domains/mx/edu/unidem.txt
University website: https://www.udemorelia.edu.mx/
University IT course website:  https://www.udemorelia.edu.mx/oferta-academica/licenciatura/videojuegos/
Proof of the email domain: 
The date is old, but is still the available
=> UNIDEM added

lib/domains/ke/ac/gretsauniversity.txt
added gretsa university under ke/ac folder.
=> added gretsa university under ke/ac

lib/domains/et/edu/wku.txt
https://www.wku.edu.et/en/index.php/en
https://www.wku.edu.et/en/index.php/en
https://www.wku.edu.et/en/index.php/en/about-us/about-wku/14-general/16-history
=> Wolkite university added

lib/domains/id/ac/polman-bandung/mhs.txt
University website**
https://polman-bandung.ac.id/
Proof as the university uses the domain**
https://polman-bandung.ac.id/tentang-kami/
=> add Politeknik Manufaktur Bandung

lib/domains/co/edu/ulibertadores.txt
Updated by Ricky Rhonaldo Ortega Vital
FULL - Sede Cartagena
=> Nuevo correo institucional

lib/domains/vn/edu/nctu/student.txt
- Official website: [https://www.nctu.edu.vn/](https://www.nctu.edu.vn/)
=> Add Nam Can Tho University

lib/domains/com/alunocesul.txt
We are an educational institution that started the technology course in 2022.
=> request for cesul

lib/domains/cm/edu/ictuniversity.txt
Adding my ICTU university to jetbrains. ICT University is an accredited private university located in Yaoundé, Cameroon. It aims to provide ICT and human management capacity development in developing countries.
Thanks 
Site: [ICT-U WEBSITE](https://ictuniversity.org/)
Facebook: [Facebook page](https://www.facebook.com/theictuniversity/)
Linkedin: [PROFIL ICTU](https://www.linkedin.com/company/the-ict-university)
|  <img src="https://github.com/codeurzebs/codeurzebs/blob/main/.github/workflows/Private/ictu-usa.jpg?raw=true" width="50%">  |  <img src="https://github.com/codeurzebs/codeurzebs/blob/main/.github/workflows/Private/ictu-usacameroon.jpg?raw=true" width="50%" >  |
| -- | -- |
=> Create ictuniversity.txt add by @codeurzebs 22/06/23

lib/domains/mx/edu/uptlaxponiente/sise.txt
Universidad Politécnica de Tlaxcala Región Poniente. Mexico, Tlaxcala, tlax
=> ADD - Universidad Politécnica de Tlaxcala Región Poniente

lib/domains/pl/zsgorowoil.txt
Liceum Ogólnokształcące w Górowie Iławeckim
https://zsgorowoil.edupage.org/
- [ x] Academic/Teaching Staff
- [ x] High School or equivalent
=> Górowo Iławeckie High School

lib/domains/ro/scoala-mihaieminescu.txt
Domain: @scoala-mihaieminescu.ro
Website: https://www.scoala-mihaieminescu.ro
=> Added Scoala Mihai Eminescu

lib/domains/eu/kielce/4lo.txt
IV Liceum Ogólnokształcące w Kielcach
High School no. 4 in Kielce
Official website: http://4lo.kielce.eu/
School's Statute (in Polish): http://4lo.kielce.eu/wp-content/uploads/2020/02/Statut_01.09.2019.pdf
Additional info about the school (in Polish): https://4lokielce.ssdip.bip.gov.pl/
=> IV Liceum Ogólnokształcące w Kielcach

lib/domains/cr/ina.txt
Hi! I'm a teacher at **Instituto Nacional de Aprendizaje** of **Costa Rica**! We are request that you add our student email domain to your list of Educational Centers, please ;-)
=> Please add the student email domain for INA, Costa Rica

lib/domains/eg/edu/nmu.txt
New Mansoura University
https://www.nmu.edu.eg/en
[s-mahmoud221101184@nmu.edu.eg](mailto:s-mahmoud221101184@nmu.edu.eg)
- [*] Students
- [*] Academic/Teaching Staff
- [*] Other/Support Staff
- [*] Alumni
- [*] College (University) or Undergraduate School or equivalent
=> New Mansoura University license request

lib/domains/br/edu/senaicimatec/aln.txt
university website: https://www.senaicimatec.com.br/ 
technical course website: https://www.tecnicosenai.com.br/unidade-salvador-cimatec/ Linkedin: https://www.linkedin.com/school/senaicimatec/
=> Add SENAI CIMATEC domain

lib/domains/com/ziv-school.txt
School Domain: https://sites.google.com/ziv-school.com/ziv  **website is in Hebrew!**
[School Verification!.pdf](https://github.com/JetBrains/swot/files/11930354/Arnon.Hacohen.pdf)
In the attached file is with the school official mail (upper corner after "דוא"ל" (right to left)), with an official message from my school that I'm student at the school.
=> Added My School!

lib/domains/uk/ac/aaschool.txt
school webpage https://www.aaschool.ac.uk/
=> ADD Architecture Association School of Architecture

lib/domains/ph/edu/udm.txt
Adding Universidad de Manila for udm student's access.
=> Add Universidad De Manila

lib/domains/eg/edu/ksiu.txt
King Salman International University
[KSIU](https://ksiu.edu.eg/en/)
=> Adding KSIU

lib/domains/pk/edu/ist.txt
This is a pull request being made for free license of Pycharm Professional
=> Institute of Space Technology

file/lib/domains/kr/go/cbe/cbs-h.txt, lib/domains/kr/go/cbe/cbs-h.txt
high school in south korea
충북과학고등학교
chungbuk science high school
=> request licenses

lib/domains/mx/edu/utcgg.txt
Verificar Universidad Tecnologica de la Costa Grande de Guerrero (UTCGG) https://utcgg.edu.mx/
=> Verifies and adds the Technological University of the Costa Grande de Guerrero

lib/domains/np/edu/indrenicollege.txt
IT College from Nepal located at the Chitwan district Bharatpur
=> Added Indreni College

lib/domains/tw/edu/wzu.txt, lib/domains/tw/edu/wzu/st95.txt, lib/domains/tw/edu/wzu/student.txt
The students often want to use the school google or Microsoft account, the teachers mail was also previously not included.
=> Make all subdomains available for wenzao university 

lib/domains/ua/dp/kre.txt
Added Dnipro Applied College of Radio Electronics in list
=> Added Dnipro Applied College of Radio Electronics

lib/domains/in/ycce.txt
Yeshwantrao Chavan College of Engineering (YCCE), Nagpur
=> Added YCCE, Nagpur

lib/domains/mx/edu/uptlax.txt
This is the file to the domain for the university uptlax.edu.mx
=> Add domain: uptlax.edu.mx

lib/domains/uk/sch/sutton/glenthorne.txt
Adding Glenthorne Highschool to access jet-brains.
=> Adding Glenthorne Highschool

lib/domains/sv/edu/liveusam.txt
official website: https://www.usam.edu.sv/
computer science engineering official site: https://nuevoingreso.usam.edu.sv/carreras/ingenieria-ciencias-computacion
=> Adding Universidad Salvadoreña Alberto Masferrer

lib/domains/ch/ksba/students.txt
Official school URL(s):
* https://www.ksba.ch  
* https://https://www.kanti-baden.ch/
IT related long-term courses:
* https://www.kanti-baden.ch/informatikmittelschule/  (German)
E-mail addresses used for students:
* https://www.kanti-baden.ch/kanti-abc/ (check under E -> E-mail)
=> Added Kantonsschule Baden

lib/domains/com/fpzornotza.txt
Hi!
I added my highschool to the repo
Here it is: https://fpzornotza.hezkuntza.net/eu/inicio1
=> FPZornotza added

lib/domains/at/hak-linz.txt
official website: https://www.hak-linz.at/
=> Adding Linz International Business School

lib/domains/org/spartandocs.txt
Highschool Website: http://slsd.org/
Link to List of CS Courses: https://sites.google.com/slsd.org/slhs-program-of-studies/departments/Math?authuser=0
School Full Name: Southern Lehigh High School
=> Adding Personal High School

lib/domains/mx/uadeo.txt
=> Adding UAdeO University

lib/domains/mx/edu/cetis108.txt
=> Adding CETis108

lib/domains/vn/edu/caodangvietmy.txt
=> caodangvietmy-college-added

lib/domains/de/fh-bielefeld.txt, lib/domains/de/hsbi.txt
The "Fachhochschule Bielefeld" (fh-bielefeld.de) was renamed into "Hochschule Bielefeld" (hsbi.de).
=> Update and rename fh-bielefeld.txt to hsbi.txt

lib/domains/py/edu/desarrollo.txt
Add Instituto Desarrollo - Development Institute Paraguay
**Domain** desarrollo.edu.py
**Website** https://desarrollo.edu.py/en/home/
**IT related course** http://cursos.desarrollo.edu.py/
**Contact email**
=> Add Instituto Desarrollo - Development Institute Paraguay

lib/domains/org/barstowschool.txt
- Official Site: https://www.barstowschool.org
- Upper School Curriculum: https://www.barstowschool.org/middle-upper-sub-detail
- Specific Courses Found Under Downloads
- Faculty Directory: https://www.barstowschool.org/directory
- Doesn't Show Student Emails for Privacy
- Students Have Emails Under the Same Domain
If you need additional proof of student emails, I have attached an email sent to students over the summer providing information for the following 2023-2024 school year.
=> Added The Barstow School

lib/domains/br/edu/faculdademetropolitana.txt
https://faculdademetropolitana.edu.br
=> added new educational institution

lib/domains/org/charterarts/student.txt
Accredited high school in Bethlehem, Pennsylvania, USA.
=> Adding student domain for Lehigh Valley Charter High School for the Arts in Bethlehem PA USA

lib/domains/ph/edu/tau.txt
Add tau.edu.ph domain for registration of student
=> add: tau domain

file/lib/domains/us/nmusd.txt, lib/domains/us/nmusd.txt
=> Newport Harbor High School

lib/domains/uk/sch/bham/wheelerslane.txt
This is the school website: https://www.wheelerslane.bham.sch.uk/ These are all the IT/Computing related courses https://www.wheelerslane.bham.sch.uk/app/os#!b5d49f8bc3325613ce7c7c0bb3f4bfa1/computing-2
=> Add Wheelers Lane Technology College

lib/domains/cz/sstas-karvina.txt
Website with courses: https://sstas-karvina.cz/nase-obory/
=> Add SŠTAS Karviná

lib/domains/tn/rnu/isetkl.txt
Please check domain name.
link of the instituion : [https://isetkl.rnu.tn/](url)
Thank you.
=> new doamin /lib/domains/tn/rnu/isetkl.txt

lib/domains/np/edu/ssha.txt
=> Add ssha.edu.np

lib/domains/net/hunau.txt
email address：http://mail.hunau.net/
Proof of domain ownership:https://xcb.hunau.edu.cn/
=> Add a new email suffix

lib/domains/cn/edu/ynit.txt, lib/domains/cn/edu/ynit/mail.txt
Yunnan Industry & Trade Vocational College
www.ynit.edu.cn
Introduction of IT teaching Department:
https://www.ynit.edu.cn/a/yuanxijieshao/20180426/234.html
[file.zip](https://github.com/JetBrains/swot/files/12135325/file.zip)
=> Please add ynit.edu.cn

lib/domains/net/zjtcm.txt
=> new email suffix

lib/domains/org/educadventista.txt
=> Centro Universitário Adventista de São Paulo

lib/domains/eu/teleinformatika.txt
Official url: https://www.teleinformatika.eu
=> Add teleinformatika.eu domain

lib/domains/ke/ac/riarauniversity.txt
Riara University
https://riarauniversity.ac.ke/
=> Added Riara University

lib/domains/pl/org/mans.txt
=> Revert "Menedzerska Akademia Nauk Stosowanych w Warszawie"

lib/domains/dk/ind-it.txt, lib/domains/dk/individualisterne.txt
To provide a bit more context about our school, I will give a short description of what we offer.
We are a small school with a 3 year long course for young people who has autism, through out their education here they are being introduced to multiple subjects within technology, including coding, database administration and deployment, which is the reason why we would love to offer your products to our students.
Our website is unfortunately only available in danish.
The school official website URL: https://www.individualisterne.dk/
School address is:
Kalundborgvej 39
4200 Slagelse
Denmark
URL for the IT related course: https://www.individualisterne.dk/stu-forside/stu/it-linje/
If further proof or materials is required, please let me know. 😊
=> Re-Added two domains for Individualisterne

lib/domains/br/cesul.txt
We are an educational institution that started the technology course in 2022. We made the release for the students' domain, I would like the release for the teachers as well.
the school official website URL :
https://cesul.br/
the school street address, including city and country :
Brazil, Francisco Beltrão - Parana - Av. Antônio de Paiva Cantelmo, 1222 - Centro. an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
https://cesul.br/graduacao/presencial/analise-e-desenvolvimento-de-sistemas/sobre-o-curso/ https://www.cesul.br/cesul-inicia-o-curso-de-analise-e-desenvolvimento-de-sistemas/ https://jornaldebeltrao.com.br/geral/cesul-inicia-o-curso-de-analise-e-desenvolvimento-de-sistemas/ a proof, which shows that the school recognizes the …
=>  add domain

lib/domains/pe/edu/ceticoempresarios.txt
=> Add Cetico Students

lib/domains/tw/edu/tnua/newmedia.txt
Hello, I found a past request: https://github.com/JetBrains/swot/pull/11737 from the same domain, but currently the school no longer provided gmcc account.
The domain to the degree is at: http://newmedia.tnua.edu.tw.
There are some courses on Computer Programming C#, Interactive 3D Programming you may find at:
https://selcrs1.tnua.edu.tw/CourseSearch/CourseSelect.aspx?Dept=CA162, but there isn't a full English version on details.
Thank you!
=> Add tnua.edu.tw

lib/domains/mx/edu/utch.txt
Added Universidad Tecnológica de Chihuahua to the edu.mx domains
=> Universidad Tecnológica de Chihuahua

lib/domains/ch/montana-zug.txt, lib/domains/lib/domains/ch/montana-zug.txt
School website: https://www.montana-zug.ch/en
Document proving my school offers IT courses (sadly, the document is only available in German): [https://montanaschule-my.sharepoint.com/personal/montana_admin_montana-zug_ch/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fmontana%5Fadmin%5Fmontana%2Dzug%5Fch%2FDocuments%2F3%5FSG%5FSchweizersGymnasium%5FSwissSeniorHighSchool%2F21%2D22%5FLehrpläne%2F2021%5F22%5FLehrplan%5FInformatik%2Epdf&parent=%2Fpersonal%2Fmontana%5Fadmin%5Fmontana%2Dzug%5Fch%2FDocuments%2F3%5FSG%5FSchweizersGymnasium%5FSwissSeniorHighSchool%2F21%2D22%5FLehrpläne](https://montanaschule-my.sharepoint.com/personal/montana_admin_montana-zug_ch/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fmontana%5Fadmin%5Fmontana%2Dzug%5Fch%2FDocuments%2F3%5FSG%5FSchweizersGymnasium%5FSwissSe …
=> Please add Institut Montana Zugerberg

lib/domains/mx/edu/ucma.txt
Official Website URL: https://ucma.edu.mx/
The Page for their IT school is https://ucma.edu.mx/sistemas-computacionales/
=> Add UCMA University

lib/domains/eg/edu/feps.txt
Faculty's official website: http://www.feps.edu.eg/arr/
Faculty's official socio computing minor department: http://www.feps.edu.eg/enn/departments/sc/index.php
Faculty's contact us page which uses the feps.edu.eg domain: http://feps.edu.eg/enn/contactus/index.php
=> Add Faculty of economics and political science, FEPS

lib/domains/edu/rowan/students.txt
Rowan University
rowan.edu
Proof of email address: https://irt.rowan.edu/service-catalog/collaboration/gmail/
Proof of computer science program: https://csm.rowan.edu/departments/cs/
=> Add Rowan University

lib/domains/com/universidadviu/student.txt
Following the instructions on your README:
- the university official website URL, if it is different from the domain you are submitting
https://www.universidadviu.com/es/
- a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university
https://www.universidadviu.com/es/grado-ingenieria-informatica
- a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.
Can't find anything public, but attaching a (lightly censored) sign up email. URLs clearly visible. Email came from a different domain that's already on this repo for the same university (campusviu.es).
=> Add Universidad Internacional de Valencia

lib/domains/ua/org/sfa.txt
Added "Flight Academy of National Aviation"
https://www.sfa.org.ua/
=> Added sfa.ua.org, "Flight Academy of National Aviation"

lib/domains/org/pottsboroisd.txt, pottsboroisd.txt
=> Pottsboro Independent School District

lib/domains/pk/edu/fccollege.txt
Forman Christian College (A Chartered University)
**Institution/School Website**
https://www.fccollege.edu.pk
{[muhammaddanish@fccollege.edu.pk](mailto:muhammaddanish@fccollege.edu.pk)}
Students
Academic/Teaching Staff
Other/Support Staff
Alumni
Graduate School
College (University) or Undergraduate School or equivalent
Community College or equivalent
High School or equivalent
Elementary School or equivalent
=> Add FC College. Here is Website Link : https://www.fccollege.edu.pk

donboscohoboken.txt, lib/domains/be/donboscohoboken.txt
I am a teacher @ Don Bosco tech institue in Hoboken (Antwerp - Belgium)
=> Domain DonBoscoHoboken.be added

lib/domains/de/heinrich-mann-schule.txt, lib/domains/de/hms-dtzb.txt
Hi,
please add Heinrich-Mann-Schule Dietzenbach https://www.hms-dtzb.de/ with both domains:
hms-dtzb.de (Faculty)
heinrich-mann-schule.de (Students)
TIA.
Regards,
Christian Hecker
=> Adding Heinrich-Mann-Schule Dietzenbach

lib/domains/uk/ac/rcl/student.txt
Thank you all for supporting students <3
=> Add RCL to list

lib/domains/mx/edu/tesco.txt
This is the university's official "About us" page:
http://www.tecnologicodecoacalco.edu.mx/TESCO/acerca/bienvenida.htm
This is where the university lists the courses it offers, being the first of them the Computer Software Engineering course:
http://www.tecnologicodecoacalco.edu.mx/TESCO/acerca/carreras.htm
This is the "contact us" page, where the email domain is acknowledged
http://www.tecnologicodecoacalco.edu.mx/TESCO/INICIO/contactanos.htm
=> School addition

lib/domains/it/edu/liceo-severi.txt
The official site is https://www.liceo-severi.edu.it/ 
is a high school that includes two hours per week of computer science with programming in C++ in my high school curriculum. In addition, there are additional computer courses such as ICDL (https://www.icdl.it/). The school is attended by over a thousand students
=> Add Liceo Francesco Severi

lib/domains/mx/edu/cenidet.txt
Added: Centro Nacional de Investigación y Desarrollo Tecnológico / Tecnológico Nacional de México
University official website -> https://cenidet.tecnm.mx/ Long-term (>1 year) 
IT related course is offered by the university -> https://cenidet.tecnm.mx/oferta_educativa.php
=> Added: Centro Nacional de Investigación y Desarrollo Tecnológico 

lib/domains/ph/edu/trimexcolleges.txt
=> Add Trimex Colleges Inc.

lib/domains/cn/ac/ios.txt
Institute of Software, Chinese Academy of Sciences
http://www.iscas.ac.cn
Additional information can refer to #9899.
=> add Institute of Software, Chinese Academy of Sciences

lib/domains/org/thekaustschool.txt
The Kaust School is a K-12 co educational high school part of the Kaust University organization
=> Adding thekaustschool.org domain

lib/domains/com/ncetmail.txt
College Name: Nagarjuna college of engineering and technology (NCET)
College official website URL: https://ncet.co.in/
IT related courses: https://ncet.co.in/admissions/
Computer Science and Engineering course: https://ncet.co.in/cse-department/
College mailing adrress:  https://ncet.co.in/contact-us-2/
=> Added Domain for Nagarjuna college of engineering and technology

lib/domains/org/btfiloh.txt
Adding new school (k-12) [Beth Tfiloh](https://www.bethtfiloh.com/school)
=> Add Beth Tfiloh (btfiloh.org)

lib/domains/br/edu/unipaulistana.txt
=> unipaulistana added

lib/domains/th/ac/ksu.txt
I've corrected it when I misunderstood something last time.
=> 📝 Create Kalasin University ✔️

lib/domains/hk/edu/tkhc.txt
Add Tai Kwong Hilary College domain
Official website: https://tkhc.edu.hk/
Course IT: https://tkhc.edu.hk/academics_curriculum-structure/
Email: nurgazysalanov@tkhc.edu.hk
=> Create tkhc.edu.hk extension

lib/domains/mx/edu/unicla.txt
Add Domain for Universidad Contemporánea de las Américas (UNICLA)
URL: https://unicla.edu.mx/
Course IT: https://unicla.edu.mx/licenciaturas/licenciatura-en-ingenieria-en-sistemas-computacionales-con-terminales/
Gmail: contacto@unicla.edu.mx
=> Add Universidad Contemporánea de las Américas

lib/domains/in/org/sanjivanicoe.txt
This commit adds sanjivanicoe.org.in
=> Adds sanjivanicoe.org.in

lib/domains/id/ac/hamzanwadi.txt
I add hamzanwadi.ac.id domain as our institution domain
=> add hamzanwadi.ac.id

lib/domains/id/ac/polimdo.txt, lib/domains/id/ac/polimdo/polimdo.txt
Politeknik Negeri Manado / Manado State Polytechnic
Official Site: https://polimdo.ac.id/
Address: Kampus Politeknik, Jl. Raya Politeknik Ds. Buha Kampus Manado PO BOX 1265
=> Politeknik Negeri Manado

lib/domains/lk/cclacademy.txt
official website URL: [https://cclacademy.lk/](https://cclacademy.lk/)
URL of a page related to an IT course: [https://cclacademy.lk/pearson-btec-hnd-in-computing-software-engineering/](https://cclacademy.lk/pearson-btec-hnd-in-computing-software-engineering/)
Example of student email:
=> Add CCL Academy

lib/domains/no/agderskolen/agderskolen.txt
The previous addition did not work under educational license application page.
=> Add agderskolen.txt

lib/domains/com/onmicrosoft/1lowbelchatowie.txt
=> Add 1lowbelchatowie

lib/domains/nl/lindecollege.txt
Added my school as i would like to use Pycharm Pro for my projects on O&O. :)
=> Added the Linde College

lib/domains/co/edu/usanjose.txt
Fundacion de educacion superior San Jose
https://sitio.usanjose.edu.co/
Email Users
Students
Academic/Teaching Staff
College (University) or Undergraduate School or equivalent
=> Added Universidad SanJose

lib/domains/org/gltech.txt
Official Website URL: https://www.gltech.org/
Long-Term IT Program (Page 55-57): https://www.gltech.org/site/handlers/filedownload.ashx?moduleinstanceid=1059&dataid=5685&FileName=2023-2024%20Program%20of%20Studies_English_1.3.23.pdf
Proof of Domain: The email domain uses the same domain as the official website.
=> Greater Lowell Technical High School

lib/domains/ng/edu/miva.txt
1. [University's official website URL](https://miva.university/)
2. [Page for long-term course](https://miva.university/bsc-software-engineering/)
3. [Domain proof url](https://photos.app.goo.gl/B15k6iPiFw9qvEzdA)
=> Add Miva Open University

lib/domains/pk/edu/shu.txt
[`University Url`](https://shu.edu.pk/)
=> Added shu file

lib/domains/mx/edu/itsur.txt, lib/domains/mx/edu/itsur/alumnos.txt, lib/domains/mx/tecnm/surguanajuato.txt
Dear JetBrains Administrators, we would like to kindly request the registration of three domains on your platform for our institution. The primary and longest-standing domain is itsur.edu.mx. In addition, we work closely with our students who utilize the subdomain alumnos.itsur.edu.mx. Recently, we have also adopted the domain surguanajuato.tecnm.mx, following our institution's integration into the esteemed Tecnológico Nacional de México.
Your approval in registering these three domains on your platform would greatly support our context. We believe that JetBrains' products are suitable for our needs in careers that are related with Computer Science. 
Thank you for your attention to this matter. We look forward to your positive response. 
Best regards, 
M.I.S. Fernando José Martínez López …
=> Instituto Tecnológico Superior del Sur de Guanajuato (TecNM Campus Sur de Guanajuato)

lib/domains/uk/ac/yorkcollege/student.txt
Long-term course: https://www.yorkcollege.ac.uk/study/computer-science-as-a-level
=> Add York College & University Centre

lib/domains/org/fuhsd/student.txt
See https://www.fuhsd.org/our-schools - all schools share the same `student.fuhsd.org` domain for students.
=> add more schools to student.fuhsd.org

lib/domains/com/42barcelona.txt
I would like to add 42 Barcelona as one of the schools which can have the free educational license
=> Added 42Barcelona domain

lib/domains/np/edu/ims.txt
=> IMS COLLEGE

lib/domains/mx/edu/uttc.txt
Ingeniería en Desarrollo y Gestión de Software
=> https://uttc.edu.mx/?p=218

lib/domains/jo/edu/aum/std.txt
Added American University of Madaba
=> Added American University of Madaba

lib/domains/net/ecoles-epsi.txt
My school at https://www.epsi.fr/
=> Add École professionnelle des sciences informatiques

lib/domains/dk/scu.txt
Not different, but here nonetheless: [scu.dk](https://scu.dk).
[HHX course overview](https://scu.dk/uddannelser/hhx-paa-scu/fag-og-opbygning/) (scroll to and expand **Informatik B**):
> **Informatik B**
Du får et dybere indblik i, hvordan den digitale verden hænger sammen. Du skal blandt andet lære om programmering, databaser, brugervenlighed, it-sikkerhed, teknologi-etik og it-baseret-innovation. I den forbindelse skal du arbejde projektorienteret med at skabe en række forskellige produkter som f.eks. apps, hjemmesider og spil.
... or, in English:
> **Informatics B**
You'll get a deeper insight into how the digital world operates. Amongst other things, you'll learn about programming, databases, UX, IT security, tech ethics and IT based innovation. Correlated to that, you'll work project …
=> Add Skanderborg-Odder Center for Education (scu.dk)

lib/domains/jp/ac/kbc/stu.txt
School Name
Added International Electronic Business College
Official Site
https://www.kbc.ac.jp/
IT Engineering
https://www.kbc.ac.jp/course/it-engineer/
=> Added International Electronic Business College

lib/domains/org/svsd410/students.txt
Mount Si High School is part of the Snoqualmie Valley School District (SVSD), their website is https://svsd410.org
=> Added Mount Si High School

lib/domains/org/dc-tech.txt
=> Add Dauphin County Technical School

lib/domains/ma/lm6e.txt
to make it faster:
website: https://lm6e.ma/
=> Lycée Mohamed 6 d'Excellence (lm6e)

lib/domains/mx/edu/ucq.txt
Universidad Cuauhtémoc Querétaro
-
University official website URL: https://www.ucq.edu.mx/
URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: 
- Ingenieria en Software y Sistemas Computacionales (Software Engineering): https://www.ucq.edu.mx/uc/oferta/carrera/Sistemas-Computacionales
- Ingenieria en Desarrollo de Videojuegos y Medios Interactivos (Game Development Engineering): https://www.ucq.edu.mx/uc/oferta/carrera/Desarrollo-de-Videojuegos-y-Medios-Interactivos
A URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students: https://www.ucq.edu.mx/uc/contacto
=> Universidad Cuauhtémoc Querétaro

lib/domains/university/stamford.txt
Added the domain of Stamford University Bangladesh.
University official website URL : [Official Website](https://www.stamforduniversity.edu.bd/)
Long Term courses offered by University : [Long Term Courses](https://www.stamforduniversity.edu.bd/index.php/stamford/details/66)
University Email Format : _<unique_numbers>@stamford.university_
=> Added Stamford University Bangladesh

lib/domains/bo/edu/usip.txt
University name
Universidad Simon I Patiño
Official website
https://www.usip.edu.bo/
My e-mail
[alvarocampos@usip.edu.bo](mailto:alvarocampos@usip.edu.bo)
=> please add usip.edu.bo  usip.txt

lib/domains/ro/lbi.txt
fixed the pull request, thanks
=> Add National College of Computer Science "Tudor Vianu"

lib/domains/it/studenti/unibs.txt
Università di Brescia
https://www.unibs.it/it
=> Added University of Brescia

lib/domains/mx/edu/colegiodelmayab.txt
Este documento corresponde al Colegio del Mayab
=> Solicitud de aceptación de colegio

lib/domains/pk/edu/alnafi.txt
=> Revert "Al Nafi E Learning"

lib/domains/np/edu/gomendracollege.txt
gomendracollege.edu.np domain added
=> gomendracollege.edu.np added

lib/domains/br/edu/unijui.txt
Hello, the domain user@sou.unijui.edu.br refers to students, but as I am an intern at the university, I have the email user@unijui.edu.br, so I would like you to accept my request to add Unijuí to the domains
=> add Unijui university to domains 

lib/domains/lt/ehu.txt
[Website](https://en.ehu.lt/)
[IT Bachelor's degree](https://en.ehu.lt/studies/computer-science/)
[Proof of using domain](https://en.ehu.lt/contacts/)
=> Add European Humanities University

lib/domains/sg/edu/sthua.txt
=> Added St.Hua Private School

lib/domains/mt/edu/aum.txt
Identifying AuM as an educational institute (https://aum.edu.mt/)
=> Adding AuM to JetBrains educational institues

file/lib/domains/com/cpsglobalschool.txt, lib/domains/com/cpsglobalschool.txt
[cpsglobalschool.txt](https://github.com/JetBrains/swot/files/12539642/cpsglobalschool.txt)
=> CPS GS SCHOOL ANN

lib/domains/sa/edu/oc.txt
{Onaizah Colleges}
{ https://oc.edu.sa/en }
=> ceate oc.txt

lib/domains/uk/ac/farn-ct.txt
- Website: https://www.farn-ct.ac.uk
- \>1 Year IT-related course: https://www.ucfarnborough.ac.uk/course/ba-hons-games-design-and-games-development/GDG1/
=> Add Farnborough College of Technology

lib/domains/it/edu/davincimilazzo.txt
- Official website: https://www.davincimilazzo.edu.it/
- Long term IT course: https://www.davincimilazzo.edu.it/index.php/2014-04-24-10-22-02/settore-tecnologico
=> Add ITET Leonardo da Vinci (Milazzo)

lib/domains/org/mbway.txt
Ajout de l'école MBway d'Angers
=> Ajout école MBway

lib/domains/uk/co/nwhsmail.txt
Added a new school file
School Website: https://www.nunnerywood.worcs.sch.uk/
IT course: https://www.nunnerywood.worcs.sch.uk/115/subjects/subject/12/computing-business
=> Added swot/lib/domains/uk/co/nwhsmail.co.uk

lib/domains/mx/edu/cbtis013.txt
=> Create domain cbtis013.txt

lib/domains/cat/insalfonscostafreda.txt
=> add domain insalfonscostafreda.cat

lib/domains/ma/ac/uiz/edu.txt
university website : https://www.uiz.ac.ma/
=> add edu.uiz.ac.ma domain

lib/domains/mx/edu/upzmg.txt
Add license for Universidad Politecnica de la Zona Metropolitana de Guadalajara
=> add upzmg license

lib/domains/br/edu/faculdadevincit.txt, lib/domains/faculdadevincit.txt
Registrador da Faculdade Vincit
=> Faculdade Vincit

lib/domains/id/ac/polsky.txt
Institution Official Website: polsky.ac.id
=> add polsky.ac.id

lib/domains/br/edu/ceunsp/cs.txt
This pull request is to add CEUNSP to the branch, the institution is located in the city of Itu and Salto, in the interior of the state of São Paulo, in Brazil.
Main page from institution: https://www.ceunsp.edu.br/
long-term IT course page: https://www.ceunsp.edu.br/graduacao/ciencia-da-computacao/
=> Added files from the institution CEUNSP.

lib/domains/mx/edu/iclasalle.txt
=> add new institute domain

lib/domains/dz/univ-guelma.txt
=> add guelma university

lib/domains/fi/kalajoki/edu.txt
firstname.lastname@edu.kalajoki.fi is the email used by students in all schools (primary, secondary and higher). The domain for the city is kalajoki.fi
=> Add edu.kalajoki.fi

lib/domains/pl/olsztyn/zsek.txt
Actual domain is .eu for school's website (zse.olsztyn.eu) but it uses @zsek.olsztyn.pl for students' emails so I'm not exactly sure where to put the file. I used the path JetBrains webpage autosuggested.
=> Added ZSE school from Olsztyn, Poland

lib/domains/uk/sch/towerhamlets/central.txt
- the university official website URL, if it is different from the domain you are submitting
**https://www.cfgs.co.uk/index.asp**
- a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university
**https://www.cfgs.co.uk/Computer-Science/**
- a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.
=> added file for domain central.towerhamlets.sch.uk for CFGS

lib/domains/ro/colpedms.txt
Hello!
I am a student at Colegiul National Pedagogic "Mircea Scarlat" and I want to add their college domain.
Here is the offical school website::https://www.cnpms.ro/
=> Add "Mircea Scarlat" college

lib/domains/ca/canctb.txt
Added the Canadian College of Technology and Business
=> Added CCTB

lib/domains/com/onmicrosoft/stasziczsp.txt
ZESPÓŁ SZKÓŁ PONADPODSTAWOWYCH w Białobrzegach, Poland
The official website of the school: https://zspbialobrzegi.edu.pl/
=> Add ZSP w Białobrzegach

lib/domains/cz/delta-skola.txt, lib/domains/cz/delta-studenti.txt
Hello,
I would like to ask you to add domains for DELTA - high school of informatics and economics. There are two domains in my pull request. One domain is delta-skola.cz. This domain is used by teachers. The second domain is delta-studenti.cz. This domain is used by students. Graduates do not have email addresses.
School website: https://www.delta-skola.cz/
Address with information on the field of information technology: https://www.delta-skola.cz/obor-informacni-technologie-18-20-m-01/
You can verify that the domain delta-skola.cz belongs to the teachers at this address: https://www.delta-skola.cz/kontakty and information about second domain (delta-studenti.cz) you can find on this address: https://www.delta-skola.cz/kontakty/#Studenti
Thank you very much.
=> added domain files for DELTA high school computer science and economics

lib/domains/hu/mcdaniel.txt
McDaniel College Budapest
https://mcdaniel.hu/
=> Added McDaniel College Budapest

lib/domains/kh/edu/paragoniu.txt
I would like to add Paragon International University to the domain list.
=> Add PIU at Cambodia to kh/edu domain

lib/domains/pt/aeen.txt
- Website: https://aeen.pt
- 1 year technology related courses can be found at: https://www.aeen.pt/es-emidio-navarro/
=> Add Secondary School Emídio Navarro

lib/domains/com/rcsi.txt
https://www.rcsi.com/
https://www.rcsi.com/dublin/postgraduate/taught-courses/technologies-and-analytics-in-precision-medicine-msc/why-rcsi-dublin
=> Please add my institution rcsi.txt

lib/domains/uk/ac/hcfe.txt
Added Hartlepool College of Further Education to the list.
=> Add hcfe.txt file.

lib/domains/ma/ac/enim.txt
=> add enim.ac.ma domain

lib/domains/tw/edu/cust/gms.txt
add China University of Science and Technology
=> add China University of Science and Technology

lib/domains/fr/estia.txt
Master of Science BIHAR, Big Data & AI: https://www.estia.fr/formations/formations-longues-diplomantes/msc-bihar
Engineering Degree: https://www.estia.fr/formations/ingenieur-generaliste-international
=> Add upper-level domain for ESTIA

lib/domains/mx/edu/iunis.txt
Agrego mi colegio Instituto Universitario del Sureste https://iunis.edu.mx/
=> Instituto Universitario del Sureste

lib/domains/vn/edu/ajc.txt
Academy of Journalism and Communication Vietnam
=> Academy of Journalism and Communication Vietnam

lib/domains/com/onmicrosoft/umistrzapaderewskiego.txt, lib/domains/pl/ciezkowice/zsoiz.txt
added 2 new school domains - school currently uses both microsoft and google e-mails, so I added both of them, however main website of the school is umistrzapaderewskiego.pl (e-mail accounts don't use that domain)
=> Added "U Mistrza Paderewskiego"

lib/domains/de/gs-ldk/student.txt
Added gs-ldk to lib/domains
Name: Gewerblichen Schulen Dillenburg
Official website: https://www.gs-ldk.de/
E-Mail: info@gs-ldk.de
E-Mail for students (Example): ia22.kem.brian@student.gs-ldk.de
Address: Herwigstraße 32, 35683 Dillenburg, Germany
IT related programs: 
https://www.gs-ldk.de/bildungsangebote/it-berufe/fachinformatiker-in-systemintegration-2.html
https://www.gs-ldk.de/bildungsangebote/it-berufe/fachinformatiker-daten-und-prozessanalyse.html
=> Add gs-ldk

lib/domains/com/cipfpvalledeelda/alu.txt
https://cipfpvalledeelda.com
https://cipfpvalledeelda.com/ciclo-formativo/tecnico-en-sistemas-microinformaticos-y-redes/
https://cipfpvalledeelda.com/ciclo-formativo/titulo-profesional-basico-en-informatica-y-comunicaciones/
=> Added CIPFP Valle de Elda

lib/domains/education/lycee-de-beauvoir.txt
- the university official website URL, if it is different from the domain you are submitting : https://lycee-gragnague.mon-ent-occitanie.fr/
-  a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university : https://lycee-gragnague.mon-ent-occitanie.fr/l-etablissement/formations/bts-ciel/
-  a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students : https://drive.google.com/file/d/1UJVdSizzUsP5lD11p6YVAiC2YrOUZ1Wt/view?usp=sharing
=> Add files of High School Simone de Beauvoir in lib/domains/education

lib/domains/org/dld.txt
**Name:** DLD College London
**Website:** https://www.dldcollege.co.uk/
**Email for students example:** example@dld.org
=> add DLD College London

lib/domains/org/sjnacademies.txt
=> adding St. John's Northwestern

lib/domains/com/andalusiaquranicschool.txt
Hi Team, 
I would like to request approval to my child school to learn about programming. Website: https://www.aqs.sch.id/ Please give your approval and thanks for your time.
Thanks,
Regards
Buddy Arifin
=> Add school "Andalusia Quranic School"

lib/domains/uk/co/olympustrust.txt
https://www.olympustrust.co.uk/
https://www.bradleystokecs.org.uk/
=> Add Bradley Stoke Community School

lib/domains/org/chigwell-school.txt
Hi, please add my Institute, this is the main domain:
www.chigwell-school.org
and this is the domain we use for email addresses:
@chigwell-school.org
Here you can see the 2 year A-Level course in Computer Science:
[https://www.chigwell-school.org/sixth-form/sixth-form-curriculum/](https://www.chigwell-school.org/sixth-form/sixth-form-curriculum/)
Thank you for your time!
=> added @chigwell-school.org domain

lib/domains/vn/edu/thptnguyenhuuhuan.txt
Domain: thptnguyenhuuhuan.edu.vn/thptnguyenhuuhuan.hcm.edu.vn
School name: Nguyen Huu Huan High School
=> Add Nguyen Huu Huan High School

lib/domains/it/edu/avoltapg.txt, lib/domains/it/risikamente.txt
Hi, please add my Institute, this is the main domain:
www.avoltapg.edu.it
and this is the domain we use for email addresses:
www.risikamente.it
Here you can see the 5 years course in IT and Telecommunications:
https://www.avoltapg.edu.it/pagine/informatica-e-telecomunicazioni
Thank you for your time!
=> added domains for Istituto Tecnico Tecnologico Alessandro Volta Perugia

lib/domains/id/sch/smkn2banjarbaru.txt
SMK Negeri 2 Banjarbaru
Domain: [smkn2banjarbaru.sch.id](https://smkn2banjarbaru.sch.id)
Additional information: [https://dapo.kemdikbud.go.id/sekolah/D23665DC0C3E20229812](https://dapo.kemdikbud.go.id/sekolah/D23665DC0C3E20229812)
=> Add SMK Negeri 2 Banjarbaru

lib/domains/mx/edu/colegioespanoldemorelos.txt
Please add my school Colegio Español de Morelos, the website is colegioespanoldemorelos.edu.mx, thanks!
=> add domain colegioespanoldemorelos.edu.mx

lib/domains/np/edu/ncmt.txt
- www.ncmtcollegenepal.edu.np (ncmpt)
=> Add NCMT - National College of Management and Technical Science

lib/domains/pl/edu/uniwersytetkaliski.txt
Changed name from Akademia Kaliska to Uniwersytet Kaliski
=> Add school Uniwersytet Kaliski

lib/domains/uz/newuu.txt
Our website domain was changed from newuzbekistanuniversity.uz to newuu.uz
=> Add newuu.uz - New Uzbekistan University

lib/domains/eu/ensiie.txt
Added French school ENSIIE https://www.ensiie.fr/
=> Added eu/ensiie.txt

lib/domains/org/waprep.txt, lib/domains/uk/sch/harrow/nowerhill.txt
https://waprep.org/
Main Website
https://waprep.org/courses/ib-computer-science-sl-hl/
Proof of enrollment in computer science course
=> adding Washington Preparatory School

lib/domains/ca/rubika-edu.txt
School website: [https://rubika-edu.ca/en/](https://rubika-edu.ca/en/)
Tech art 3 year course: [https://rubika-edu.ca/en/trainings/tech-art-video-game/](https://rubika-edu.ca/en/trainings/tech-art-video-game/)
Email using domain: admin@rubika-edu.ca. This is the account used for registering all educational s/w accounts. See attached screen shot for Adobe for example...
=> Add Rubika Montreal domain

lib/domains/es/educastur.txt
=> Add educastur.es

lib/domains/net/bts-malraux.txt
French high school with a university class
=> add bts-malraux.net

lib/domains/dk/eg-gym.txt
Official website URL: https://eg-info.dk/
=> Added the @eg-gym.dk domain

lib/domains/np/edu/asm.txt
Main Website - https://asm.edu.np
Proof of Computer Science related course - https://www.asm.edu.np/course/bsc-csit/
=> Added asm.edu.np

lib/domains/hr/algebra.txt
Official URL: https://www.algebra.hr/visoko-uciliste/en/
URL of one of the IT programmes offered: https://www.algebra.hr/visoko-uciliste/en/studij/graduate-professional-program/software-engineering/
and this is the domain we use for email addresses:
@algebra.hr
=> Added Algebra University Collage

lib/domains/eus/maltuna.txt
Adding Miguel Altuna LHII name to the domain list.
=> Miguel Altuna LHII domain

lib/domains/eg/edu/anu.txt
Its another branch of Alexandria University, more details here: 
https://alexu.edu.eg/index.php/%D8%A3%D8%AD%D8%AF%D8%AB-%D8%A7%D9%84%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/7116-%D8%A8%D8%AF%D8%A1-%D8%A7%D9%84%D8%AF%D8%B1%D8%A7%D8%B3%D8%A9-%D8%A8%D8%AC%D8%A7%D9%85%D8%B9%D8%A9-%D8%A7%D9%84%D8%A5%D8%B3%D9%83%D9%86%D8%AF%D8%B1%D9%8A%D8%A9-%D8%A7%D9%84%D8%A3%D9%87%D9%84%D9%8A%D9%80%D9%80%D9%80%D9%80%D8%A9
Their website (its always down tho): https://anu.alexu.edu.eg
Edit: it seems that only the medical programs site works for some reason (http://medportal.anu.edu.eg/) but you can check the 1st link to confirm that they provide CS programs
=> Request to add ANU University

lib/domains/it/accademiabari.txt
-university official website URL: https://www.accademiabelleartiba.it/
-URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: (DAPL06 - WEB DESIGN AND VISUAL COMUNICATION) https://drive.google.com/file/d/1BXyZ_Wq8Tl93SyI_1Tfr6lWt-L1RyoyT/view 
-proof showing that the university recognizes the domain which I am submitting as an official email domain for the enrolled students: https://www.accademiabelleartiba.it/opportunita.html
=> Add Accademia Di Belle Arti di Bari

lib/domains/id/ac/unira.txt
I can add my univercity to claim github student pack
=> added madura univercity

lib/domains/iq/edu/knu.txt
knowledge university of Iraq, Erbil.
knu.edu.iq
=> adding knowledge university,Iraq-Erbil

lib/domains/ie/cdcfe.txt
website: https://www.cdcfe.ie/
computer science course: https://www.cdcfe.ie/courses/computer-science/
=> Add Colaiste Dhulaigh College of Further Education

lib/domains/school/bgt.txt
Added my school. 
British Gymnasium of Technology (BGT)
https://bgt.school
=> Added "British Gymnasium of Technology"

lib/domains/kr/ac/deu.txt
I would like to add the domain `deu.ac.kr` for DONG-EUI University to the repository.
- Official University Website URL: [DONG-EUI University Official Website](https://eng.deu.ac.kr/eng)
- URL of IT related course: [IT Related Course at DONG-EUI University](https://computer.deu.ac.kr/computer/sub03_01.do)
Thank you for considering my request.
=> Added Dong-Eui University

lib/domains/com/stadjutor.txt
Lycée Saint-Adjutor
https://www.stadjutor.com/
imad.sghir@stadjutor.com
=> Add Saint-Adjutor school

lib/domains/pl/edu/wsi/stud.txt
Website: https://www.wsi.edu.pl/
University course example: https://www.wsi.edu.pl/specjalizacje/2/programowanie
=> Add WSIZ BB

lib/domains/org/bsacet.txt
B.S.A. College of Engineering and Technology
{[B.S.A. College of Engineering and Technology](https://www.bsacet.org/)}
=> Adding Bsacet.org

lib/domains/ma/ac/efet.txt
=> add efet file

lib/domains/ma/ac/enset-media/etu.txt
Adding ENSET Mohammedia 
@etu.enset-media.ac.ma
=> ENSET Mohammedia

lib/domains/uk/ac/newvic/students.txt
Newham Sixth Form College
https://www.newvic.ac.uk/
https://www.newvic.ac.uk/a-z-course-list - This contains a full list of their courses.
=> Add "Newham Sixth Form College"

lib/domains/ph/edu/heroes1979.txt
Bataan Heroes College
https://heroes1979.edu.ph/
Teaches undergraduate, high school, and senior high school.
=> Add heroes1979.txt

lib/domains/pe/edu/fhpa.txt
=> upload file fhpa-edu-pe

lib/domains/id/sch/smansajulok.txt
this is Senior High School 1 Julok, Aceh Timur, Aceh - Indonesia
=> sman 1 julok

lib/domains/pl/akademiabialska/dyd.txt, lib/domains/pl/akademiabialska/stud.txt, lib/domains/pl/pswbp/dydaktyka.txt, lib/domains/pl/pswbp/student.txt
**the university official website URL:** 
[https://akademiabialska.pl](https://akademiabialska.pl)
**a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university:**
[https://rekrutacja.akademiabialska.pl/study-in-english/computer-science](https://rekrutacja.akademiabialska.pl/study-in-english/computer-science)
[https://rekrutacja.akademiabialska.pl/oferta/informatyka-3.html](https://rekrutacja.akademiabialska.pl/oferta/informatyka-3.html)
**a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students:**
[https://akademiabialska.pl/aktualnosci/wirtualna-uczelnia-microsoft-teams--poczta-email-studenci-i-rok …
=> Add Akademia Bialska im. Jana Pawła II

lib/domains/school/sevenkings.txt
Adding Seven Kings School
For any queries, please also CC to this email kfardin906@gmail.com
=> Adding Seven Kings School

lib/domains/fr/diginamic.txt
[https://www.diginamic.fr/](https://www.diginamic.fr/)
[https://www.diginamic.fr/formation-concepteur-developpeur-application-fullstack/](https://www.diginamic.fr/formation-concepteur-developpeur-application-fullstack/)
[https://www.diginamic.fr/faq/#b1b0da4d79cd7936b](https://www.diginamic.fr/faq/#b1b0da4d79cd7936b)
```
Firstname Lastname<flastname@diginamic.fr>
```
```
Firstname Lastname<flastname@diginamic-formation.fr>
```
=> Add Diginamic

lib/domains/de/element-i-schule.txt
[The school's website](https://www.element-i.de/en/schools/freie-element-i-gemeinschaftsschule-at-the-bildungshaus-karlsruhe/)
=> Add Freie element-i Gemeinschaftsschule im Bildungshaus Karlsruhe

lib/domains/uk/ac/accesscreative.txt
https://www.accesscreative.ac.uk/courses/software-development-t-level/
=> Add Access Creative College

lib/domains/ac/scsd/k12.txt
* https://shs.stanwood.wednet.edu/
* For use by college credit classes under [`Running Start`](https://cdnsm5-ss19.sharpschool.com/UserFiles/Servers/Server_73299985/File/Academics/Running%20Start%20Information/Running%20Start%202022-2023%20Information.pdf) program
=> stanwood high school, stanwood, washington, usa

lib/domains/ph/edu/cpu.txt
- [https://cpu.edu.ph](https://cpu.edu.ph)
=> Central Philippine University (.cpu.edu.ph)

lib/domains/hu/lovassy/mail.txt
I would like to add the domain mail.lovassy.hu for Lovassy László High School to the repository.
Verification Details
Official School Website URL: [Lovassy László High School Official Website](http://web.lovassy.hu/)
URL of IT related course: [IT Related Course at Lovassy László High School](http://web.lovassy.hu/az-iskola-jelene/kepzesi-formaink/) (see number 4)
Thank you for considering my request.
=> Added Lovassy László Gimnázium

lib/domains/com/bbailigan.txt
=> Add bbailigan.com

lib/domains/th/ac/ftu.txt
https://ftu.ac.th/
https://fst.ftu.ac.th/
=> Add "Fatoni University"

lib/domains/pl/edu/ur.txt
Subdomains for e-mail addresses :
stud.ur.edu.pl
dokt.ur.edu.pl
=> Added to lib/domains/pl/edu/ur.txt  ".stud" ".dokt"

lib/domains/eu/alcampus.txt, lib/domains/it/alcampus.txt
Hello, I'm Carlo Di Cicco, a student pursuing a Master's degree in Intelligent Systems Engineering (Bachelor's in Computer Engineering). I'm attempting to add the alcampus.it email domain of my university to obtain a PyCharm Professional license. The official website of Campus Bio-Medico University of Rome is https://www.unicampus.it/. I'd like to express my gratitude for your assistance and support in this matter. Thank you for your help.
=> Add Email Domain for students of Campus Bio-Medico University of Rome

lib/domains/us/or/k12/bend/student.txt
Applying in hopes of advancing "Into to Computer Science" class with code with me plugin for PyCharm, applying on behalf of CTE Teacher.
=> License Request

lib/domains/ph/edu/cksc.txt
College site https://cksc.edu.ph
Offering courses in IT Education (BSCS, BSIT, BSIS)
=> Adding CKSC

lib/domains/org/sau41.txt
Sorry for creating a pr earlier, I accidentally put it in the wrong directory.
=> Add Sau 41

lib/domains/uk/ac/bradfordcollege.txt
https://www.bradfordcollege.ac.uk
=> Added Bradford College

lib/domains/de/bsz-wiesau.txt
Staatliches Berufliches Schulzentrum Wiesau
www.bsz-wiesau.de
=> Added BSZ-Wiesau

lib/domains/hu/boronkay.txt
This is our home page: https://boronkay.hu/
This is the information page for those who choose software developer and tester direction at our school:
https://boronkay.hu/kepzeseink/technikum-szakkepzo/szoftverfejleszto-es-tesztelo
In the left pane you can download 2 pdf documents (KKT/PPT) which contains (unfortunately available only in Hungarian) the detailed plan of subjects and lessons.
=> Add Boronkay

lib/domains/pl/merito/gdynia/student.txt
Fillia in my city does not have an ENG version of the website and redirects to the endpoint in Gdańsk.
Official website : https://www.merito.pl/gdynia/
Computer science related course: https://www.merito.pl/english/gdansk/our-offer/bachelors-degree/programs/information-technology-software-development
=> Added WSB Merito University Gdynia

lib/domains/lv/valmierastehnikums.txt
official website - https://valmierastehnikums.lv/en
IT related course - https://valmierastehnikums.lv/en/node/1672 
showing that the university recognizes the domain - At the bottom of any page on the official website is the schools email
=> Adding Valmieras tehnikums

lib/domains/br/urisantiago.txt
- University Website: [http://urisantiago.br/](http://urisantiago.br/)
Please note that the email address provided ([gustavo.reis@urisantiago.br](mailto:gustavo.reis@urisantiago.br)) is available for use by students and university collaborators only. If you have any questions or need further assistance, don't hesitate to get in touch.
Thank you for considering this update!
=> Add Uri Santiago to the JetBrains list

lib/domains/pl/wloclawek/pans.txt
PUZ (known before as PWSZ) has been renamed to PANS
School official website: https://pans.wloclawek.pl/
Computer Science Related course: https://pans.wloclawek.pl/informatyka/
=> Add PANS Włocławek University

lib/domains/net/conejousd/learn.txt
Added Westlake High School in Thousand Oaks, California of Conejo Valley Unified School District.
=> Added Westlake High School

lib/domains/uk/co/soas.txt
Here is the link if in doubt https://www.soas.ac.uk/
=> Add SOAS University

lib/domains/uk/ac/rnngroup/student.txt
=> Add college

lib/domains/com/globalopencampus.txt, lib/domains/com/globalopencampus/angers.txt
Hello, here i am again with the certificat i've been asking for
Here are the informations you asked
Respectfully
the school official website URL : https://globalopencampus.com/open-campus-angers/
the school street address, including city and country : 2 rue de la Martinellerie, Trélazé, 49800 Angers
an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course : https://globalopencampus.com/learn-it-ecole-ingenierie-informatique/
a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students. :
=> add opencampus

lib/domains/th/ac/pccchon.txt
**Official Website:** https://www.pccchon.ac.th/
**Domain Proof:** https://ac.pccchon.ac.th/group/10
=> Added pccchon.txt

lib/domains/br/edu/ugv.txt
Hello. I would like to attach the institutional website (https://ugv.edu.br/), (https://uniao.ugv.edu.br/). I had sent this request once before, but an error occurred when entering the website, so I would like to ask that if it happens again, if it is possible to search for it on the web (Ugv) and the result will appear immediately. The university is located in the state of Paraná, Brazil in the city União da Vitória.
=> Added new University

lib/domains/com/lepidorocco.txt
Lepido Rocco School, Website: lepidorocco.it
=> Add lepidorocco.txt

lib/domains/pl/edu/tychy/zs4.txt
Hi! I hope the domain description was successful And I'm very sorry if not
My school: https://www.zs4.tychy.edu.pl/
=> Add a new school

lib/domains/it/edu/liceofardellaximenes.txt
School official url: https://liceofardellaximenes.edu.it/
IT course: https://liceofardellaximenes.edu.it/orientamento-scienze-applicate/
=> Add school Liceo Fardella Ximenes

lib/domains/fr/it-students.txt
it-students.fr is a domain of it-akademy.fr
you can check the school validity on this url: https://www.it-akademy.fr/
=> add it-students.fr domain

lib/domains/es/cei/alumnos.txt
Web de la escuela: https://cei.es/
Web de cursos relacionados con IT:
https://cei.es/cei-curso/master-aplicaciones-web-marketing-digital/
https://cei.es/cei-curso/master-desarrollo-web/
https://cei.es/cei-curso/titulo-superior-desarrollo-web-marketing-digital/
https://cei.es/cei-curso/titulo-superior-diseno-grafico-web/
https://cei.es/cei-curso/posgrado-en-diseno-y-desarrollo-web/
https://cei.es/cei-curso/grado-superior-en-desarrollo-de-aplicaciones-web-daw-a-distancia-online/
=> Add CEI School

lib/domains/de/folkwang-uni.txt
added Folkwang University of the arts to the repo
=> adding Folkwang-uni

lib/domains/br/edu/ufra.txt
1) the university official website URL, if it is different from the domain you are submitting: http://ufra.edu.br
2) a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: https://graduacaobsipgm.ufra.edu.br
3) a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students: https://www.sigaa.ufra.edu.br/sigaa/public/docente/portal.jsf?siape=1210306
=> Add ufra.edu.br

lib/domains/et/edu/astu.txt
=> Create Adama Science and Technology University(ASTU)

lib/domains/de/franziskusgymnasium-it.txt
official website: https://franziskusgymnasium.de/
it related course: https://franziskusgymnasium.de/unterricht/faecherkanon/
official email domain: https://franziskusgymnasium.de/service/microsoft365-service-portal/ (recognizable through the text and the info email below)
=> Add franziskusgymnasium-it.de

lib/domains/ua/edu/bukuniver.txt
Please add https://bukuniver.edu.ua/
Bukovinian University (Chernivtsi, Ukraine) provides economic, law and IT eduction.
Thanks for approval!
=> Added bukuniver

lib/domains/ca/qc/crc-lennox.txt
Website: https://www.crc-lennox.qc.ca/
=> Adds Champlain college lennoxville

lib/domains/uk/org/macademy.txt
Macmillan academy and Post 16 College.
=> Add Macmillan Academy / Post 16 College

lib/domains/uk/ac/dbsinstitute.txt
https://www.dbsinstitute.ac.uk/all-courses/ba-hons-game-development-programming
=> Add dBs Institute

lib/domains/my/edu/disted/dmail.txt
Website : https://www.disted.edu.my
=> Add DISTED College

lib/domains/hk/edu/fkyc/ms.txt
add Fanling Kau Yan College
website: https://web2.fkyc.edu.hk/
email domain is [xxx@ms.fkyc.edu.hk](mailto:xxx@ms.fkyc.edu.hk)
=>  Fanling Kau Yan College

itp.txt, lib/domains/id/ac/itp.txt
Add Institut Teknologi Padang
link
https://itp.ac.id/
=> Institut Teknologi Padang

lib/domains/nl/newman.txt
Newmancollege Breda in the netherlands
=> Add Newmancollege to jetbrain list

lib/domains/org/csd117.txt
Discovery High School: https://camas.wednet.edu/schools/dhs/
Camas High School: https://camas.wednet.edu/schools/chs/
=> Add csd117.org domain

lib/domains/de/goetheschule-essen/office.txt
Website: www.goetheschule-essen.de
=> Goetheschule Essen

lib/domains/it/edu/icpieroangela.txt
=> ic Piero Angela

lib/domains/de/bsz-kulmbach/s.txt, s.txt
https://www.bsz-kulmbach.de/adalbert-raps-schule
=> Adalbert-Raps-Schule - Berufliches Schulzentrum Kulmbach

lib/domains/de/bayern/asv.txt, lib/domains/de/bayern/stmuk.txt
have to use commercial license instead
=> Delete lib/domains/de/bayern directory

lib/domains/ph/edu/ncf.txt
=> Naga College Foundation, Inc.

lib/domains/uk/ac/carmel/students.txt
Add Carmel College as student directory
=> Add Carmel College to JetBrains Directory

lib/domains/fr/jbrel.txt
Lycée Professionnel Jacques Brel
=> Added jbrel.txt

lib/domains/uk/org/solsch.txt
website is https://www.solsch.org.uk/ an email from the school would look like example@solsch.org.
=> Add Solihull School

lib/domains/mx/edu/itlp.txt
Adding the email domain of the university Instituto Tecnológico de la Paz.
Website URL: [http://www.itlp.edu.mx/](http://www.itlp.edu.mx/)
=> Adding itlp.txt domain file

lib/domains/cn/edu/dlnu.txt
dlnu
Dalian Minzu University
大连民族大学
url: https://new.dlnu.edu.cn/ 
computer specialty： https://www.dlnu.edu.cn/comd/xygk57/xyjj/index.htm
email-domain: mail.dlnu.edu.cn
=> Add Dalian Minzu University(dlnu)

lib/domains/it/parma/liceomarconi.txt
Website: https://www.liceomarconipr.edu.it
Unfortunately, I couldn't find any reference on the website to this being the official email address.
=> Add Liceo Scientifico G. Marconi

lib/domains/it/edu/branchina.txt
Add Istituto tecnico Pietro Branchina
Website: https://www.branchina.edu.it/
=> Add Istituto tecnico Pietro Branchina

lib/domains/uk/sch/kent/nks.txt
Add the Norton Knatchbull School ([nks.kent.sch.uk](nks.kent.sch.uk))
=> Add Norton Knatchbull School

lib/domains/jp/fsgcl.txt
website URL: https://www.nsg.gr.jp/list/006.html
IT related course example: https://wiz.ac.jp/course/info_technology/info_high/
ownership: https://wiz.ac.jp/tgs2021/portfolio/08/img/portfolio.pdf
=> Add fsgcl.jp

lib/domains/it/edu/voltafr.txt
Add IIS Alessandro Volta.
Website: https://www.voltafr.edu.it/
=> Add IIS Alessandro Volta

lib/domains/id/ac/peradaban/mt.txt
Universitas Peradaban
https://peradaban.ac.id/
=> Add Universitas Peradaban

lib/domains/id/ac/uici.txt
Official website: https://uici.ac.id
Informatic program: https://uici.ac.id/program-studi-informatika-s1/
=> add UICI domain

lib/domains/org/dlshs.txt
https://www.dlshs.org
https://www.dlshs.org/academics/academic-courses
https://www.dlshs.org/academics/academic-departments/mathematics
See Intro and AO computer science courses...
Intro to Computer Science - P
COURSE NUMBER: M601
STATUS: UC/CSU & NCAA Approved
CREDITS: 5
CAMPUS: DLS
PREREQUISITES: None
LEVEL: 9th-12th grades
This course exposes students to the fundamental principles and concepts of computer science and programming. Students will learn to code through hands-on assignments which include game design, lab completion, independent projects, and pair programming. This course serves as both an introduction to, and foundation for, further study in computer science.
=> Add De La Salle High School

lib/domains/hu/scheiber.txt, lib/domains/hu/somer.txt
scheiber.hu - Primary domain of Scheiber Jewish school, Budapest.
somer.hu - Secondary domain for the school's youth club.
Both teachers and youth club is planning to use YouTrack to increase their performance, efficiency, accountability.
For further consultation please contact info@scheiber.hu and titkar@somer.hu
=> Adding Scheiber Sándor Jewish School

lib/domains/ph/edu/csucarig.txt
[csucarig.txt](https://github.com/JetBrains/swot/files/13486664/csucarig.txt)
=> csucarig.txt

lib/domains/mx/edu/uhipocrates.txt
Adding the domain uhipocrates.edu.mx for "Universidad Hipócrates".
=> Adding uhipocrates.edu.mx

lib/domains/th/ac/utc.txt
Ubon Ratchathani Technical College
https://www.utc.ac.th/2020/
- [ x ] Students
- [ x ] College (University) or Undergraduate School or equivalent
=> add utc school

lib/domains/fr/metznumericschool.txt
Hi,
For more information, you can visit : [https://www.metz-numeric-school.fr/fr](https://www.metz-numeric-school.fr/fr)
Thanks !
=> Adding metznumericschool.txt

lib/domains/org/thesummitprep.txt
=> Add The Summit Preparatory School

lib/domains/org/bruntsacademy.txt
no longer apart of the evolve trust but now the greenwood academy trust
=> Brunts has migrated trusts

lib/domains/org/learningplanetinstitute.txt
Learning planet institute
https://www.learningplanetinstitute.org/en/
Education
https://www.learningplanetinstitute.org/en/education-2/
R&D
https://www.learningplanetinstitute.org/en/what-we-do/rd/
=> added Learning planet institute

lib/domains/org/aoiths.txt
School Name: Academy of Innovative Technology
Website: https://www.aoiths.org/en/
=> Added domain for the AIT

lib/domains/vn/edu/chauvanliem.txt
School official website: https://chauvanliem.edu.vn/
School on Wikipedia (in Vietnamese): https://vi.wikipedia.org/wiki/Tr%C6%B0%E1%BB%9Dng_Trung_h%E1%BB%8Dc_ph%E1%BB%95_th%C3%B4ng_Ch%C3%A2u_V%C4%83n_Li%C3%AAm,_C%E1%BA%A7n_Th%C6%A1
=> Add Chau Van Liem high school

lib/domains/lt/techin.txt, lib/domains/lt/vtmc.txt
After reorganization our training center changed domain and name to techin.lt.
=> Update and rename vtmc.txt to techin.txt

lib/domains/bd/ac/buet/cse/ugrad.txt
University CSE department Website: https://cse.buet.ac.bd/
Course List consisting Undergraduate: https://cse.buet.ac.bd/studies/ug_courses
Course List Masters/PhD: https://cse.buet.ac.bd/studies/pg_studies
Faculty Email: https://cse.buet.ac.bd/home/contact
Undergrad Email domain has a prefix - `ugrad`
=> Add BUET email domain

lib/domains/edu/ptc.txt
Add Piedmont Technical College
[Website](https://ptc.edu)
[Degree Program](https://catalog.ptc.edu/academic-programs/business-information-technology-public-service-commercial-art/computer-technology-curricula/computer-technology-aas/index.html)
[University recognition of address for students](https://catalog.ptc.edu/student-handbook/tips-for-students/pathway-user-guide/) (Under "What is my email address?")
=> Add Piedmont Technical College

lib/domains/uk/ac/leicestercollege/my.txt
This PR adds Leicester College to the SWOT list
Website: https://leicestercollege.ac.uk
Proof of email: If necessary, I can provide my student email here for verification. (Ideally I don't want to share it in a public thread)
Courses: Multiple long-term computing courses can be found here: https://leicestercollege.ac.uk/courses/all-courses/?fwp_subject_area=computing-and-digital&fwp_course_level=3
Thanks!
=> Add Leicester College

lib/domains/id/ac/poliban/mhs.txt
**University Name**
Politeknik Negeri Banjarmasin / State Polytechnic of Banjarmasin (English)
**Official Website**
[https://poliban.ac.id](https://poliban.ac.id/)
**Official Domain**
poliban.ac.id
=> Adding State Polytechnic of Banjarmasin (POLIBAN)

lib/domains/nz/ac/yoobeestudent.txt
NZ, Wellington, Has a bachelor of software engineering course
=> Yoobee College of Design

lib/domains/university/jala.txt
application to accept the university account of the Jala University
=> license application Jala University

lib/domains/id/sch/diandidaktika.txt
Request registering Dian Didaktika
=> Req(diandidaktika): Registering School of Dian Didaktika

lib/domains/uk/ac/acm/my.txt
My uni also has a game design and programming course, as well as web development and other forms of computer science :)
I thought it would be prudent to give JetBrains a try.
My schools links are as follows:
https://www.acm.ac.uk/
The Rodboro Buildings, Bridge Street, Guildford, GU1 4SB
[+44 (0)1483 500 800](<tel:+44 (0)1483 500 800>)
=> Added Academy of Contemporary Music

lib/domains/uk/ac/CCN/student.txt, lib/domains/uk/ac/ccn/student.txt
=> Added City College Norwich

lib/domains/rs/edu/fdb.txt
Added Faculty of Diplomacy and Security, University Union NT in lib/domains/rs/edu
=> Faculty of Diplomacy and Security, University Union NT

lib/domains/py/edu/americana.txt
Universidad Americana del Paraguay
Domain: americana.edu.py
Website: https://www.americana.edu.py
IT related course: https://www.americana.edu.py/carreras/ingenieria-informatica/
=> Add Universidad Americana

lib/domains/id/sch/praditadirgantara.txt
[Pradita Dirgantara High School](https://praditadirgantara.sch.id/en/) is an international high school located in Boyolali, Indonesia.
For further information about my school, click the link! (they didn't really translated the web into english for some reason)
We have a computer science class in there, and apparently I'm the first one to use IntelliJ IDEA as a preferred IDE.
Why? Because they use Java and I hate its boilerplate features, so I choose Kotlin and IntelliJ IDEA is the best for it.
=> Uploaded praditadirgantara.txt

lib/domains/id/ac/poliban/mahasiswa.txt
**University Name**
Politeknik Negeri Banjarmasin / State Polytechnic of Banjarmasin (English)
**Official Website**
[https://poliban.ac.id](https://poliban.ac.id/)
**Official Domain**
poliban.ac.id
Some new students use the subdomain 'mahasiswa.poliban.ac.id'
=> Update New Student's Subdomain for POLIBAN

lib/domains/cz/isp.txt
=> Add International School of Prague txt

lib/domains/pl/krakow/sobieski/student.txt
Entry for students of "II Liceum Ogólnokształcące
im. Króla Jana III Sobieskiego w Krakowie" high school in Kraków, Poland
The high school offers extended Computer Science classes over 4-year course.
1) High school website: http://www.sobieski.krakow.pl
2) Profiles (with class A having Computer Science as an extended subject): http://www.sobieski.krakow.pl/rekrutacja/profile-planowanych-klas/
3) Website does not provide information about student email addresses. Students have assigned accounts in the form of name.surname@student.sobieski.krakow.pl also registered in MS Teams as a part of an organisation, but I don't know how could I submit a proof.
=> Create student.txt in lib/domains/pl/krakow/sobieski

lib/domains/vn/edu/ric.txt
Helpful informations:
- Website: http://ric.edu.vn
- Proof of offer: http://tuyensinh.ric.edu.vn/trang-chu - as they mention that they do have "Cao đẳng Công nghệ thông tin" and "Trung cấp Tin học"/"Trung cấp Kế toán - tin học" - for a course of more than 2 - 4 years.
- About the proof of ownership, our email system use Google Workspace if we know it correctly, and they do offer email address for the students.
=> Rubber Industrial College

lib/domains/cz/ssphzuh.txt
The school has been renamed, but the web address remains the same. There are no plans to change the url from what I was told.
=> Update ssphzuh.txt to a new name

lib/domains/mr/supnum.txt
=>  add SupNum

lib/domains/mx/edu/utags.txt
lib/domains/mx/edu/utags.txt
[College domain](https://www.utags.edu.mx/)
[Software Development](https://www.utags.edu.mx/index.php/component/txeducation/course/IGS)
[Networking and Cybersecurity](https://www.utags.edu.mx/index.php/component/txeducation/course/IRIC)
=> Added domain for the Universidad Tecnológica de Aguascalientes.

lib/domains/com/onmicrosoft/technikumcyfrowe.txt
School homepage: [https://technikumcyfrowe.pl/](https://technikumcyfrowe.pl/)
=> Add Technikum Technologii Cyfrowych

lib/domains/ca/kuperacademy.txt
Kuper Academy is High school  in Montreal Quebec ,Canada
=> Added Kuper academy 

lib/domains/uz/centralasian.txt
=> centralasian.txt

lib/domains/tn/u-sfax/fss.txt
Name:
====
Faculte de sciences de sfax
Website:
=====
https://fss.rnu.tn/
Emails
====
@fss.u-sfax.tn
Used by:
=====
Students
Level:
===
University
=> add @fss.u-sfax.tn to the list of university emails

lib/domains/ve/edu/uny.txt, lib/domains/ve/edu/uny/micorreo.txt
Universidad Yacambu
https://www.uny.edu.ve/
@micorreo.uny.edu.ve
Students
University
=> Add files for Universidad Yacambu.

lib/domains/net/tusd/student.txt
Adding my high school for Jetbrains student license.
=> John C. Kimball High School, Tracy, CA

lib/domains/co/edu/ciaf.txt
Add new University of Colombia, City of Pereira
=> Add CIAF Educacion Superior University of Colombia, City of Pereira

lib/domains/vn/edu/lumina.txt
Hello JetBrains Team,
I would like to add Lumina Academy to the JetBrains/swot repository. Lumina Academy is a dedicated educational institution specializing in 3D programming for film production, advertising, and video games.
Our academy equips students with essential programming skills aimed at creating cutting-edge 3D content across various industries. We delve into the creative and technical aspects of 3D production, equipping our students with practical knowledge on game engines, visual effects, computer graphics, virtual reality, and more. Our students extensively use JetBrains tools in their curriculum.
Here's the official website for further verification: [[Lumina Academy Website]](https://www.lumina.edu.vn/)
Thank you for considering this request. Looking forward to our students …
=> Feat: Add new Lumina Academy School

lib/domains/my/edu/uptm.txt
Hi,
Please add my university, University Poly-Tech Malaysia (UPTM).
Below are the links for your verification process purposes: 
[Official Website](https://www.uptm.edu.my/index.php/bit-in-computer-application-development)
Some IT Courses:
[Diploma in Computer Science](https://www.uptm.edu.my/index.php/diploma-in-computer-science)
[BACHELOR OF INFORMATION TECHOLOGY (HONOURS) IN COMPUTER APPLICATION DEVELOPMENT](https://www.uptm.edu.my/index.php/bit-in-computer-application-development)
=> Add Universiti Poly-Tech Malaysia (UPTM)

lib/domains/np/edu/nationalinfotechcollege.txt
Added the file as requested with college name and website link.
=> Added National Infotech College, Birgunj, Nepal Info. 

lib/domains/ph/edu/nbsc.txt
Submitting a pull request to include Northern Bukidnon State College in the JetBrains academic/education library list.
School website:
[](https://nbsc.edu.ph/)
=> Northern Bukidnon College

lib/domains/mz/ac/unilurio.txt
[file.zip](https://github.com/JetBrains/swot/files/13815758/file.zip)
Please acept my university. This is called Lurio, located in mozambique.
=> Please acept my university - Lúrio University

lib/domains/be/technischatheneumkeerbergen.txt
Create for Technisch Atheneum Keerbergen 
@technischatheneumkeerbergen.be
=> Create for Technisch Atheneum Keerbergen

lib/domains/org/zone01normandie.txt
=> Adding Zone01Normandie

lib/domains/uk/org/kingsthorpecollege.txt
School website - https://www.kingsthorpecollege.org.uk/
=> Adding kingsthorpecollege to the url list

lib/domains/us/or/k12/bend.txt
Making another pull request for summit high schoolers so teachers can make accounts. Let me know if theres any questions.
=> Bend La Pine Summit High School Teachers Domain

lib/domains/ph/edu/clsu.txt
=> Add Central Luzon State University

lib/domains/pk/edu/imcbf10-3.txt
Adds Islamabad Model College for Boys College, Islamabad
College website url: https://imcbf10-3.edu.pk/
=> Adds IMCB F-10/3 College

lib/domains/rs/edu/politehnika.txt
Shool website: https://politehnika.edu.rs/
=> Add politehnika.txt

lib/domains/mx/com/umamexico.txt
Hello! 👋
- Added Universidad del Medio Ambiente [https://umamexico.com/] to lib/domains, following the convention. 
Thanks in advance!
=> Add Universidad del Medio Ambiente

lib/domains/mm/edu/ilbc.txt
Added the official domain of International Language Business Center (ILBC).
ILBC is an IGCSE & A-Level school in Myanmar.
=> Add International Language Business Center (ILBC)

lib/domains/pe/edu/tls/talento.txt
Add support for talento.tls.edu.pe domain
=> Add Toulouse Lautrec Institute Domain

lib/domains/id/sch/smkn4bdg.txt
I am a student from SMKN 4 Bandung, Indonesia, and I have an interest in using one of JetBrains' products, specifically GoLand.
=> Add SMKN 4 Bandung

lib/domains/com/ekyaschools.txt
School name :  Ekya Schools
Official website URL: https://www.ekyaschools.com/
Wiki page to confirm school domain : https://en.wikipedia.org/wiki/Ekya_Schools
=> Created ekyaschools.txt

lib/domains/uk/ac/macclesfield.txt
Added macclesfield college
Site link: https://macclesfield.ac.uk/
=> Added macclesfield college

lib/domains/np/edu/aadimcollege.txt
=> aadimcollege domain added

lib/domains/nl/theresialyceum/student.txt
Added theresialyceum from tilburg
=> added theresialyceum

lib/domains/pk/edu/muetkhp.txt
Adding my university for JetBrains student license.
=> muetkhp.edu.pk domain added

lib/domains/th/ac/rpca.txt
=> Royal Police Cadet Academy

lib/domains/id/sch/smaitmiftahulkhoir.txt
Add my school to access JetBrains student
=> Add miftahul khoir

lib/domains/de/carl-miele-berufskolleg.txt, lib/domains/de/cmb-gt.txt
**Carl-Miele-Berufskolleg für Technik**
**Domains:**
cmb-gt.de
carl-miele-berufskolleg.de
**Website:**
https://cmb-gt.de
**IT related courses offered by the school:**
https://cmb-gt.de/bildungsangebot/
**Proof of domain ownership:**
https://cmb-gt.de/kontakt/
https://cmb-gt.de/wp-content/uploads/2023/08/Lehrerliste.pdf
=> Add Carl-Miele-Berufskolleg für Technik

gim-pg.txt, lib/domains/me/edu/gim-pg.txt
Here is a request for adding Gimnazija Slobodan Škerović email domain to eligible license list
=> Domain gim-pg

lib/domains/org/asdk12.txt
Computer Science/IT courses can be viewed here: https://www.asdk12.org/cms/lib/AK02207157/Centricity/Domain/1179/REV_Sep19_2022-23_HSPOS_Accessible.pdf
The 2 year Career and Technical Education track can be viewed at: https://www.asdk12.org/Page/5358
Email addresses for employees, including teachers, is asdk12.org: https://www.asdk12.org/cms/lib/AK02207157/Centricity/Domain/1243/Anchorage%20School%20District%20Email%20Access.pdf
=> add Anchorage School District, Alaska, United States

lib/domains/uk/ac/lmas.txt
=> Domain Added

lib/domains/de/lernsax/guts.txt
URL: https://www.gutenbergschule-leipzig.de/
We recently added "Gestalter für immersive Medien" (https://www.ausbildung.de/berufe/gestalter-immersive-medien/) a new apprenticeship. Although it is no fully IT field, the students learn to work with Godot, Unreal and Unity and therefore need educational access to those tools and Jetbrains tools like Rider and Fleets to be able to make Applications in a modern way.
The E-Mail domain seems unrelated, but the official mail info[at]gutenbergschule-leipzig.de is only used for outside inquires. for Student mail all schools within Saxony now use LernSax and use the mails provided by LernSax for Students.
if you're still unsure you can write me at ar.schaub@(domain name that would be valid with this file).
=> Create guts.txt for Gutenbergschule Leipzig

lib/domains/pk/edu/ncbae.txt
ncbae.edu.pk university collage in pakistan lahore
=> ncbae.edu.pk

lib/domains/kg/bhu.txt
IT programs: https://bhu.kg/kafedry/kafedra-matematiki-i-informatiki/
Email confirm at the end of page: https://bhu.kg/#
=> Add Bishkek State University

lib/domains/kr/goept/vision-m.txt
https://vision-m.goept.kr/vision-m/main.do
=> Add Vision Middle School

lib/domains/tw/edu/kh/spec.txt
please re-check my added the school file。
I used the site(https://www.jetbrains.com/shop/eform/students/contributeUniversity) to generate the file。
The education organization's web site is https://www.spec.kh.edu.tw/.
Thks
=> add spec.txt school

lib/domains/ua/edu/hnpu.txt
http://hnpu.edu.ua/uk
http://smc.hnpu.edu.ua/node/41
http://smc.hnpu.edu.ua/files/Osvіtnі_programi/Osvitni_programu_bakalavr/2023_rik/Informatyka_v_zakladakh_osvity_bakalavr.pdf
=> Request on add H.S. Skovoroda Kharkiv National  Pedagogical University

lib/domains/org/ignatius/students.txt
=> Adding Saint ignatius

lib/domains/ve/edu/ujap.txt
Hello, i'm sorry for the previous request, i made a mistake commiting every file in the folder, please add my university:
Universidad José Antonio Páez
José Antonio Páez University
Domain: https://ujap.edu.ve/
Have a great day!
=> Add José Antonio Páez University

lib/domains/th/ac/asb.txt
Added The American School of Bangkok
=> Added The American School of Bangkok

lib/domains/mx/umov.txt
Please request the integration of my university to the domain list.
Thanks!
=> Add Universidad en Movimiento (UMOV) MX domain

lib/domains/ng/edu/nacest.txt
The Nigeria Army College of Environmental Science and Technology (NACEST) is officially hosted on www.nacest.edu.ng it is a military institution for civilians and serving personnel of the armed forces of the Federal Republic of Nigeria.
=> unzipped file for my school

lib/domains/be/vdabcampus.txt
{VDAB}
{https://www.vdab.be}
{https://www.vdab.be/opleidingen/aanbod/O-AMI-750430/cursus/C-AMI-207566/Full_stack_developer-WEVELGEM}
=> Add VDAB Campus

lib/domains/org/tscng.txt
This should be the correct filepath, I apologize for the inconvenience earlier.
WHOIS link: https://www.whois.com/whois/tscng.org
Official page of the school: https://vss.scng.si/
=> Add Higher Vocational College Nova Gorica

lib/domains/se/molndal/gafe.txt
Campus Mölndal (@molndal.se / @gafe.molndal.se)
https://campus.molndal.se/
=> Added Campus Mölndal, Sweden

lib/domains/br/com/unifaveni.txt
Adicionando o domínio da Unifaveni unifaveni.com.br
=> "Add unifaveni"

lib/domains/sa/edu/ibnroshd.txt
- Add Ibn Roshd Schools & Ibn Roshd International Schools
https://ibnroshd.edu.sa
=> Add Ibn Roshd Schools & Ibn Roshd International Schools

lib/domains/ro/traianlalescu.txt
Adding Liceul Teoretic "Traian Lalescu" 
Oficial website [http://traianlalescu.ro](http://traianlalescu.ro)
=> Adding Liceul Teoretic "Traian Lalescu"

lib/domains/uk/ac/wnc/students.txt
Official College Domain and Website: https://wnc.ac.uk/
List of IT 1+ Year courses: https://wnc.ac.uk/Courses/Area/computer-science-and-IT
Image proof of email:
=> WNC Student Subdomain

lib/domains/ie/loetbstudent.txt
Find here the course description:
https://www.itcarlow.ie/courses/type/undergraduate-cao-courses/computing-networking-courses/cw238.htm
as you can see the course is provided by setu carlow in partership with Loetb
https://www.itcarlow.ie/courses/type/undergraduate-cao-courses/computing-networking-courses/cw238.htm
=> Including Portlaoise institute student domain

lib/domains/uk/sch/bournemouth/bsg.txt
Added BSG for Bournemouth School for Girls (bsg.bournemouth.sch.uk)
Key Stage 3 - Computer Science
https://wearebsg.uk/teaching-learning/the-bsg-curriculum/
https://wearebsg.uk/school-information/contact-us/
=> Added BSG for Bournemouth School for Girls (bsg.bournemouth.sch.uk)

lib/domains/id/ac/ibbi.txt
Hi Jetbrains Team
I'm the Lecturer of this university, I would like to request add my university domain to your list and get benefit from your educational license. I hope with this support our student can learn more advanced feature that your provide in your product.
Thanks and Best Regards
=> Add new domain ibbi.ac.id

lib/domains/ke/ac/tukenya.txt
Website https://tukenya.ac.ke/
Program - https://intake.tukenya.ac.ke/index.php?r=courseApplication/default/home&prog=490
=> Added The Technical University of Kenya

lib/domains/bg/bas/ir.txt
=> Add Bulgarian Academy Of Scienece Email Domain

lib/domains/uk/ac/nscg.txt
=> Add NSCG Stafford College

lib/domains/uz/afu.txt
University official website URL: https://afu.uz/ 
Information about the Faculty of Digital Technologies can be found here: https://afu.uz/en/faculty 
location: https://maps.app.goo.gl/UwV32JfYGWmEhh3u7
=> ALFRAGANUS UNIVERSITY

lib/domains/net/besd.txt
the university official website URL, if it is different from the domain you are submitting:
https://www.besd.net/
https://www.besd.net/page/cte-pathways#:~:text=Programming%20and%20Software%20Development
a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.
Here's one: https://www.besd.net/page/report-a-concern#:~:text=Email%3A%20audit%40besd.net
=> Added domain for Box Elder School District

lib/domains/id/sch/smkn2tabanan.txt
=> Add domain smkn2tabanan.sch.id

lib/domains/pt/pupilos.txt
Website: https://pupilos.pt/
Course: Attached Flyer + Educational Offer Link - https://pupilos.pt/informacoes-e-candidaturas/
It is a vocational high school course. The course is called Technical in Management and Programming of Computer Systems and lasts for 3 years, from the tenth grade to the twelfth grade. More information in the Flyer.
=> Addiction of Instituto dos Pupilos do Exército

lib/domains/com/onmicrosoft/panimalarengg.txt
Description:
Panimalar Engineering Collage **Student email domain** is not present in the JetBrains list. So I added the domain. 
Collage website: https://panimalar.ac.in/
Collage email domains supported by GitHub: panimalarengg.onmicrosoft.com (For Students)
Email Domain Accepted by GitHub:
=> Added Panimalar Engineering Collage Student Email Domain

lib/domains/us/ok/k12/glenpool.txt
@philipto, I have removed file.zip. Sorry, I did not realize I had erroneously uploaded it to the repository as a whole, instead of adding its contents to the proper directory. This pull request should be correct.
=> Add Glenpool Public Schools

lib/domains/id/sch/dnm.txt
=> SDS IT Nur Muria

lib/domains/uk/sch/oxon/henrybox.txt
https://www.henrybox.oxon.sch.uk/
=> adding henrybox

lib/domains/org/crescentschool.txt
https://www.crescentschool.org
=> Add Crescent School

lib/domains/ec/edu/istvidanueva.txt
Website: [Tecnológico Universitario Vida Nueva](https://vidanueva.edu.ec)
Facebook Page: [Tecnológico Universitario Vida Nueva ](https://www.facebook.com/VidaNuevaITS/)
[Higher Technology in Software Development (Third Level Career) ](https://vidanueva.edu.ec/desarrollo-de-software/)
=> Added Tecnológico Universitario Vida Nueva

lib/domains/np/edu/spa.txt
Our college is locally known as Sudur Paschimanchal Academy where I am studying in 1st set BIM (Bachelor in Information Management).
=> New College: SPA college added

lib/domains/id/sch/smkn1pml.txt
=> add smkn1pml

lib/domains/cy/ac/intercollege/live.txt
https://www.intercollege.ac.cy
=> added intercollege university cyprus

lib/domains/education/paysdelaloire/0851390z.txt
Website of the university: https://vinci.paysdelaloire.e-lyco.fr
\>1 year course presentation url: https://vinci.paysdelaloire.e-lyco.fr/bac-sti2d
screen showing the domain is related to the university: https://postimg.cc/jLq3yR9b
=> adding lib/domains/education/paysdelaloire/0851390z.txt

lib/domains/uk/sch/sutton/WILSONSSCHOOL.txt, lib/domains/uk/sch/sutton/wilsonsschool.txt
Adding Wilson's School to the list.  
More details about our school's computing facilities given in the URL below. 
https://www.wilsons.school/curriculum/dept/computing/
=> Adding Wilson's school to the list

lib/domains/ua/zp/licey34.txt
Official website https://zplicey34.school.social/
has a [link](https://zplicey34.school.social/%d0%b4%d0%b8%d1%81%d1%82%d0%b0%d0%bd%d1%86%d1%96%d0%b9%d0%bd%d0%b5-%d0%bd%d0%b0%d0%b2%d1%87%d0%b0%d0%bd%d0%bd%d1%8f/%d1%81%d0%b0%d0%b9%d1%82-%d0%b4%d0%b8%d1%81%d1%82%d0%b0%d0%bd%d1%86%d1%96%d0%b9%d0%bd%d0%be%d0%b3%d0%be-%d0%bd%d0%b0%d0%b2%d1%87%d0%b0%d0%bd%d0%bd%d1%8f-%d1%83%d1%87%d0%bd%d1%96%d0%b2-%d0%b7%d0%b0/) to [google website created using that domain (lesson timetable)](https://sites.google.com/licey34.zp.ua/dystantsiina/%D1%80%D0%BE%D0%B7%D0%BA%D0%BB%D0%B0%D0%B4-%D1%83%D1%80%D0%BE%D0%BA%D1%96%D0%B2-5-11-%D0%BA%D0%BB%D0%B0%D1%81%D1%96%D0%B2)
=> Create a record for Zaporizhia Academic Lyceum No. 34

lib/domains/cat/insjoaquimmir/fp.txt
http://insjoaquimmir.cat/ ->   Redirect to  -> https://agora.xtec.cat/iesjoaquimmir/ (Official Website)
Courses:
- https://agora.xtec.cat/iesjoaquimmir/ensenyaments/cicles-formatius/grau-superior/desenvolupament-daplicacions-web/
- https://agora.xtec.cat/iesjoaquimmir/ensenyaments/cicles-formatius/grau-mitja/sistemes-microinformatics-i-xarxes/
- https://agora.xtec.cat/iesjoaquimmir/ensenyaments/cicles-formatius/grau-superior/administracio-de-sistemes-en-xarxa/
The 3 courses are 2 years each
https://moodle.insjoaquimmir.cat/ ( Institute Homework Official Website ) (Evidence)
[proof.pdf](https://github.com/JetBrains/swot/files/14227075/proof.pdf)
=> Add Ins Joaquim Mir

lib/domains/ph/edu/firstasia.txt
i uploaded the txt file request on domain/lib > ph > edu
file name: firstasia.txt
=> Added files on ph>edu via upload

lib/domains/kr/go/goe/jukgeonm.txt, lib/domains/kr/go/goe/jukjeonm.txt
school link : https://jukgeon-m.goeyi.kr/jukgeon-m/main.do
school name : jukgeon middle school
school domain : jukgeonm.goe.go.kr
=> Added jukgeonm

lib/domains/ee/tranquillity.txt
=> Request to add school: Tranquillity International School

lib/domains/sa/edu/tuwaiq.txt
Please Add Tuwaiq Academy thank you
=> add Tuwaiq Academy

lib/domains/ve/edu/uptvalencia.txt
Universidad Politécnica Territorial de Valencia (UPTValencia)
https://uptvalencia.edu.ve
jcguadama@uptvalencia.edu.ve
=> Add uptvalencia

lib/domains/in/ctgroup/stu.txt
Please approve my request to access the jetbrains product
1.My College official website link:-https://maqsudan.ctgroup.in/home
2.Kindly merge my request
=> feat: ct institute of technology and research

lib/domains/sg/edu/curtin/learning.txt
Please verify this university.
=> Add CurtinSingapore

lib/domains/si/sckr.txt
I am a teacher at Solski center Kranj and I have an e-mail ending with `@sckr.si`, as do many other workers at this school.
=> Add Solski center Kranj - sckr.si

lib/domains/nz/school/jameshargest.txt
https://www.jameshargest.school.nz
=> Add files via upload for James Hargest College

lib/domains/de/buhmann-hannover.txt
Change domain/e-mail address (the current one in the respository does not work anymore).
Link to old commit: https://github.com/JetBrains/swot/commit/d03b72a518570c5e297c91506e42334a9b55b162
(it was updated, but the updated version is wrong)
=> Update domain/e-mail address

lib/domains/tn/esprim.txt
Website of the university : https://www.esprim.tn/
=> Add Private Higher School of Engineers of Monastir - Esprim

lib/domains/net/edukl/bbs1.txt
School website: https://bbs1-kl.de/
School E-Mail: info@bbs1.edukl.net
=> Request for Vocational School I Technology Kaiserslautern

lib/domains/uk/sch/leics/delisle.txt
=> Added School | Delisle College

lib/domains/mx/edu/universidadlux.txt
=> chore: Added School | Lux University

lib/domains/it/edu/iiscolombo.txt, lib/domains/it/edu/isgiancardigalileiaicardi.txt, lib/domains/it/edu/istitutoistruzionesuperioremarconi.txt, lib/domains/it/iisruffini.txt, lib/domains/it/imperia/ruffini.txt
Link to courses and descriptions are inside each commit
=> Please add these Italian High Schools

lib/domains/de/wvsi.txt
=>  Werner-von-Siemens-Schule

lib/domains/ph/edu/southlandcollege.txt
Southland College is a school located in Kabankalan City, Philippines.
=> Request to add School to Student/Teacher Benefits - Southland College

lib/domains/org/metuchenschools.txt
https://metuchenschools.org/
Metuchen, New Jersey, 08840, United States | Public School District
=> Add Metuchen School District (High School)

lib/domains/br/com/colegioprovecto.txt
https://colegioprovecto.com.br
=> Colégio Provecto

lib/domains/com/nehrucolleges.txt
https://www.nehruinstitute.com
=> Add nehrucolleges.txt

lib/domains/edu/acg.txt
https://www.acg.edu/undergraduate/undergraduate-programs/school-of-liberal-arts-sciences/liberal-arts-sciences-majors/information-technology/
https://www.acg.edu/current-students/it-acg/it-services/email-calendar-collaboration/
=> Adding The American College of Greece (@ACG.edu)

lib/domains/edu/cscc.txt
Columbus State Community College is a public community college in Columbus, Ohio.
=> Added CSCC

lib/domains/edu/fortscott.txt
Fort Scott Community College is a public community college in Fort Scott, Kansas.
=> Added FSCC

lib/domains/cat/escolesfreta.txt
- [Website](https://www.freta.cat/)
- [CFGM courses](https://sites.google.com/calella.escolesfreta.cat/cicles-formatius-2023-24/cf-grau-mitjà) ([4th button is the IT one](https://drive.google.com/file/d/1WZv9J9nfnZrtJISwBmmeT2ZjBEOHT-Kp/view))
=> Add escolesfreta.cat

lib/domains/my/unitar.txt
Add unitar.txt file into lib/domains/my.
Official UNITAR International University webpage URL that offers long-term (>1 year) IT related course
- https://www.unitar.my/academic-programmes/information-technology/
- https://www.unitar.my/university/programme/bachelor-of-information-technology-hons/
Proof of supported email domain
=> Add unitar.txt

lib/domains/vn/edu/viendong.txt
=> add VienDong College

lib/domains/it/abana/studenti.txt
**Official WebSite:** https://www.abana.it/it/
**Address:** Via Santa Maria di Costantinopoli, 107, 80138 Napoli NA
**IT-related long-term courses:**
-  https://www.abana.it/it/triennio/   
- https://www.abana.it/it/triennio/nuove-tecnologie-per-l-arte/
**A proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students**: https://www.abana.it/media/files/guida%20utilizzo%20nuova%20email%20studenti.pdf
=> adds new University https://www.abana.it/it/

lib/domains/rs/edu/osvukknjazevac.txt
Website: www.osvukknjazevac.edu.rs
Student Email: @osvukknjazevac.edu.rs
Hello, please add my domain "osvukknjazevac.edu.rs" to your repository.
If you have any other requests, feel free to ask me!
Feel free to reach out if you need further assistance! 😊
=> osvukknjazevac

lib/domains/dz/univ-khenchela.txt
University of Khenchela Abbes Laghrour in Algeria (https://univ-khenchela.com/index.php)
=> add University of Khenchela 

lib/domains/fr/fabriquenumerique.txt
Merci de bien vouloir ajouter notre école à la liste des écoles accréditées.
=> Demande d'affiliation

lib/domains/id/ac/polines/mhs.txt
Homepage: https://polines.ac.id
student's email: @mhs.polines.ac.id
=> Adding of State Polytechnic of Semarang

lib/domains/uk/org/townleygrammar.txt
adding Townley Grammar secondary school in the UK 
https://www.townleygrammar.org.uk/
=> added Townley Grammar

lib/domains/au/edu/qld/abpat.txt
add A.B. Paterson College
https://www.abpat.qld.edu.au/
=> add A.B. Paterson College

lib/domains/in/ac/iitbhilai.txt
Indian Institute of Technology Bhilai
Homepage: https://www.iitbhilai.ac.in/index.php?pid=dept_cse
=> Added Indian Institute of Technology Bhilai

lib/domains/pt/aeestarreja.txt
Add https://www.aeestarreja.pt/
=> Add https://www.aeestarreja.pt/

lib/domains/nl/hoekschlyceum.txt
Added support for Hoeksch Lyceum
=> Added support for Hoeksch Lyceum

lib/domains/np/edu/ankuram.txt
An educational institution located in Bharatpur - 7 , Krishnapur , Chitwan Terashal Chowk Nepal .
Wesbite: https://ankuram.edu.np/
=> Ankuram Academy 

lib/domains/br/edu/fateccarapicuiba.txt
Add the domain fateccarapicuiba.edu.br
=> Create Fatec Carapicuiba

lib/domains/il/co/democrati.txt
School site:
https://www.democrati.co.il/
High school curriculum (only in hebrew - CS in hebrew is מדעי המחשב):
https://www.democrati.co.il/%D7%93%D7%A3-%D7%A8%D7%90%D7%A9%D7%99/btym-gylyym/%D7%91%D7%99%D7%AA-%D7%99-%D7%99%D7%91
3 year CS course uses Google classroom but authenticated for students.
=> Nadav Democratic school Modiin Israel

lib/domains/ch/bbz-cfp.txt
The informational page of the studies can be found here: https://bbz-cfp.ch/de/ausbildungsgange/berufsfachschule/mediamatiker-in-efz-1
=> Add bbz-cfp.ch domain

lib/domains/com/headstartphuket.txt, lib/domains/edu/headstartphuket.txt
This pull request adds HeadStart International School Phuket to the JetBrains SWOT repository to enable students and faculty members to request free JetBrains licenses.
Institution/School Name: HeadStart International School Phuket
Institution/School Website: https://headstartphuket.com
Proof of Official Email Domain: URL or attachment showing `@headstartphuket.com` is an official email domain for enrolled students
HeadStart International School Phuket offers a curriculum that includes IT-related classes, qualifying it for inclusion in the JetBrains SWOT repository. This addition will support the educational efforts of students and staff by providing access to JetBrains' suite of development tools.
=> Add HeadStart International School Phuket to JetBrains SWOT

lib/domains/th/ac/nts/gs.txt
Pull request for narathiwat school.
=> Add Narathiwat School

lib/domains/mx/edu/ilb.txt
This is the official site of the [Leonardo Bravo Institute](https://www.ipn.mx/dae/rvoe/nivel-medio-supeiror/ilb.html).
It is a university in the country of Mexico, exactly in CDMX.
=> Added ilb file

lib/domains/pl/edu/zsoiz-krobia.txt
=> Add my school domain - zsoiz-krobia.edu.pl

lib/domains/org/pathwaysschools.txt
School website is https://la.pathwaysineducation.org/
=> Add school domain

lib/domains/com/kcisg.txt
add KangQiao International School
=> Add the High/Middle School

lib/domains/hk/edu/stlouis.txt
=> New EDU school

file/lib/domains/org/coldwatercavs.txt, lib/domains/org/coldwatercavs.txt
Coldwater schools
website: [https://cw.noacsc.org/](url)
IT Class [https://cw.noacsc.org/profiles/Chuck_Alig_Profile/computer-science/](url)
=> Coldwater Schools

lib/domains/org/hunterschools.txt
=> added Hunter College Schools

lib/domains/org/carmelschools/students.txt
https://carmeltechengineering.wordpress.com/courses/
https://chs.carmelschools.org/
=> Added Carmel High School

lib/domains/net/dunlapcusd.txt, lib/domains/net/dunlapstudents.txt
School website: dunlapcusd.net
Course selection guide: https://docs.google.com/document/d/1fimI17WlzyA1bYXDf63yydceMxVw-AOo/edit (note: selection starts on page 43)
Computer Science Principles and Computer Science A are listed under Mathematics on page 50 of the guide
Digital Electronics is listed under Natural/Physical Sciences on the same page
Web Design I and II are listed on page 59
Page 60 has Computer Networking/Maintenance I 
On https://www.dunlapcusd.net/cms/one.aspx?portalId=2676846&pageId=2987063, it shows that the student email domain is dunlapstudents.net through the student helpdesk email. dunlapcusd.net is the staff email, so that is more prevalent on the district website, but the students would need access through the dunlapstudents.net domain.
=> Add Dunlap IL School District Emails

lib/domains/at/ac/ph-tirol.txt
please see https://ph-tirol.ac.at/node/512 for one of many courses that Pädagogische Hochschule Tirol offers
=> initial upload - Pädagogische Hochschule Tirol

lib/domains/de/gymnasium-marienstatt.txt
Added my School
Website: https://www.gymnasium-marienstatt.de
=> Added Privates Gymnasium Marienstatt

lib/domains/jp/ac/u-aizu.txt
[The University of Aizu](https://u-aizu.ac.jp/en/)
=> University of Aizu added

lib/domains/mx/edu/formacioninternacional.txt
=> Add formacioninternacional.txt

lib/domains/pl/edu/wab.txt
=> Wroclaw Business University of Applied Sciences

lib/domains/fr/univ-rennes.txt
www.univ-rennes.fr
https://en.wikipedia.org/wiki/University_of_Rennes
https://fr.wikipedia.org/wiki/Universit%C3%A9_de_Rennes
https://formations.univ-rennes.fr/en
=> Add Université de Rennes (www.univ-rennes.fr)

lib/domains/tw/edu/dyhu/gms.txt, lib/domains/tw/edu/dyhu/ms.txt
Sorry, my school have two email domains, last time I put wrong file
=> plz , change the school name from cku to dyhu

lib/domains/es/edu/ieschandomonte.txt
=> Added IES CDM domain

lib/domains/me/edu/ees-bp.txt
https://maps.app.goo.gl/BQYNfkxJwz6xPJnD7
=> Added SEEŠ Bijelo Polje to the list

lib/domains/ar/edu/uns/alu.txt
University site: https://www.uns.edu.ar/
Degree courses: https://www.uns.edu.ar/academicas/carreras/oferta-academica_carreras-grado
Computer Engineering course: https://servicios.uns.edu.ar/grado/plan.asp?dependen=16&carrera=186
Proof that the university recognizes the domain: 
Official email configuration tutorial: https://alu.uns.edu.ar/
=> Add Universidad Nacional del Sur

lib/domains/org/sevier.txt
=> Add SCHS (Sevier County High School)

lib/domains/org/aejics.txt
Add the school domain to allow for students and teachers for JetBrains registering.
Website: https://aejics.org
=> Add Agrupamento de Escolas Joaquim Inácio da Cruz Sobral to the list

lib/domains/vn/edu/caugiay.txt
please, add my school: Trương Công Giai Highschool
Thank you
=> Trương Công Giai Highschool

lib/domains/uk/ac/newvic.txt
Dear [Original Repository Owner's Name],
I hope this message finds you well. My name is Rubeena Parveen, and I am writing on behalf of the teaching staff at NewVic College. As part of our commitment to enhancing our educational resources, we have forked your repository [master] as per the instructions on https://www.jetbrains.com/shop/eform/students/contributeUniversity?email=rubeena.parveen%40newvic.ac.uk and would like to avail the free teachers JetBrains account.
We believe that our modifications would not only benefit our institution but could also enhance the original repository for the broader educational community. Therefore, we kindly request that you consider reviewing our changes and, if appropriate, incorporating them into the main branch of your repository.
Should you require …
=> Adding Newham Sixth Form College | Newvic

lib/domains/org/wchcs/student.txt
Add student.wchcs.org
URL: https://www.wchcs.org/washingtonhighschool_home.aspx
Address: 400 S Elm St, Washington Court House, OH 43160
Proof: ![proof_of_email](https://github.com/JetBrains/swot/assets/69666757/e6dbcfae-d421-40bb-81bc-7bdf8a3e29fd)
=> Add WCH Highschool

lib/domains/tn/ucar/isepbg.txt
=> Adding ISEPBG

lib/domains/kh/edu/camtech.txt
University website: https://camtech.edu.kh/
=> Add CamTech University domain

lib/domains/org/tavistockcollege.txt
added Tavistock College (https://www.tavistockcollege.org/)
=> add Tavistock College

lib/domains/uk/ac/lincolncollege.txt
https://www.lincolncollege.ac.uk
https://www.lincolncollege.ac.uk/search/courses?cf_courses_career_choice=20788
=> Adding the lincolncollege.ac.uk domain to the licence permission

lib/domains/lt/vda/stud.txt
University website: https://www.vda.lt/en/
=> Add Vilnius Academy of Arts
