JetBrains/swot

lib/domains/net/codeinstitute.txt
https://codeinstitute.net/
Ireland
1st Floor, Block 1, Blackrock Business Park, Carysfort Ave, Blackrock, Co Dublin Email: info@codeinstitute.net
Phone: 353 1 539 79 73
=> Add Code Institue (Ireland)

ifom.txt, lib/domains/eu/ifom.txt
Many Thanks for the really prompt answer and sorry for the previous misplacement.
=> Request for adding IFOM.eu as Edu

lib/domains/br/edu/ucpparana.txt
=> Add ucpparana domain

lib/domains/uy/edu/kennedy.txt
Added JF Kennedy School for use JetBrains products for learning
Domain https://kennedy.edu.uy
=> Added JF Kennedy School from Uy

lib/domains/np/edu/tu/ncc.txt
This pull request adds Nepal Commerce Campus (@ncc.tu.edu.np) email domain to the list of accepted domains in the IntelliJ IDEA Ultimate Student Pack. Currently, students with Nepal Commerce Campus email addresses face authentication barriers. By including Nepal Commerce Campus domain, this enhancement ensures smoother access for all eligible users, enhancing inclusivity and usability.
=> Add University Email Domain to IntelliJ IDEA Ultimate Student Pack

lib/domains/eg/edu/mnu/ai.txt
university url
https://mnu.menofia.education/
mail domain of university @mnu.edu.eg
mail domain of my college ( Faculty of Artificial Intelligence ) @ai.mnu.edu.eg
=> add my college

lib/domains/br/com/liceusantista.txt
Website; https://www.liceusantista.com.br/
Name: Liceu Santista (Maintained by philanthropic institution Sociedade Visconde de S Leopoldo)
=> Adding Liceu Santista

lib/domains/uk/ac/carlisle.txt
Website: https://www.carlisle.ac.uk
Email: info@carlisle.ac.uk
=> Add college 

lib/domains/cn/deshengzx.txt
School Official website:  http://www.deshengzx.cn/main
=> Add deshengzx

lib/domains/uk/ac/coventrycollege.txt
**URL:** https://www.coventrycollege.ac.uk/
**Address:** 50 Swanswell St, Coventry CV1 5DG, United Kingdom
**Course:** https://www.coventrycollege.ac.uk/courses/t-level-digital-production-design-development/
=> Add Coventry College

lib/domains/bh/indianschool.txt
I am a Student of Indian School, studying Computer Science in Python, and need to use Pycharm for all my projects
please help me with this request
=> Add Indian School Bahrain

lib/domains/it/edu/antonioscarpa.txt
Adding "IS. A. Scarpa, Motta di Livenza(TV)" to list
=> Adding "IS. A. Scarpa, Motta di Livenza(TV)"

lib/domains/in/edu/kdkce.txt
KDK COLLEGE OF ENGINEERING
KARMAVEER DADASAHEB KANNAMWAR COLLEGE OF ENGINEERING
KDKCE
The email we use is xyz@kdkce.edu.in
Official College Website: (https://www.kdkce.edu.in/)
URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: (https://kdkce.edu.in/index.php/department/Contentpage/index/RmJVcjdldERTZnhTWlZFPQ%3D%3D/SHZJMW8rOWFWdjVRWXc9PQ%3D%3D/)
URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students: 
1. {[Faculity Emails](https://kdkce.edu.in/index.php/Contentpage/index/RlBzMW8rOWFWdjVRWXc9PQ%3D%3D/)} (Please Check for Emails of Faculty)
2. [Please Check for Email of the College in …
=> Adding kdkce.edu.in

lib/domains/cn/dehong.txt
Add Dehong School to the list.
=> ADD dehong.cn to the list

lib/domains/de/wa-nord/schule.txt
Official Website: https://www.wa-nord.de
Email domain for students and teachers is: schule.wa-nord.de / wa-nord.de
The School is Located here:
Puschkinring 22a
17491 Greifswald
=> Add Wa-Nord

lib/domains/za/co/imconnect.txt
University official website URL: https://www.iiemsa.co.za/
Course: https://www.iiemsa.co.za/courses/bachelor-of-computer-and-information-sciences-in-application-development/
Email format is used here: https://portal.iiemsa.co.za/student-hub/GeneralEnquiry.aspx
=> add imconnect.co.za

lib/domains/es/tuniversformacion.txt
_a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university_
https://tuniversformacion.es/ciclos-formativos-modulos-fp-oficial/57-tecnico-superior-desarrollo-aplicaciones-multiplataforma-titulacion-oficial.html
(Under the description tab, under the initial introduction to the program, you can read that the Higher Vocational Training Course on Multiplatform Application Development is 2000 hours song and it takes 2 years to complete)
=> Add tunivers.txt

lib/domains/my/edu/umpsa.txt
Universiti Malaysia Pahang Al-Sultan Abdullah
=> Add umpsa.txt

lib/domains/edu/harpercollege.txt
official website URL:   https://www.harpercollege.edu/
URL of a page on the official website where a long-term (>1 year) IT related course is offered: 
https://www.harpercollege.edu/catalog/current/courses/csc.php
official email domain for the enrolled students:
https://www.harpercollege.edu/services/techsupport/index.php
https://mail.google.com/a/mail.harpercollege.edu
=> harpercollege.txt

lib/domains/ua/edu/nasbu.txt
University official website URL: https://nasbu.edu.ua
URL of a page on the official website where a long-term (>1 year) IT related course is offered:  https://nasbu.edu.ua/ua/79-osvitni-programi-studentam
=> National Academy of the Security Service of Ukraine

lib/domains/cat/martipous.txt
Added "Instituto Marti Pous", from Barcelona, Spain
Mail: ...@martipous.cat
=> Added Marti Pous

lib/domains/th/ac/spsm.txt
Add thai academy name "Prasarnmit Demonstration School (Secondary)"
domain: spsm.ac.th
=> Add thai academy spsm domain

lib/domains/cn/edu/hbhgkj.txt, lib/domains/com/hbhgkj.txt
our domain changed from hbhgkj.com to hbhgkj.edu.cn
=> move hbhgkj.txt

lib/domains/us/or/k12/gresham.txt
I'm adding Sam Barlow High School located in Gresham Oregon USA where I'm a student
=> Create Sam Barlow High School located in Gresham Oregon

lib/domains/org/mvcs/students.txt
Added Monte Vista Christian School.
=> Monte Vista Christian School

lib/domains/de/schulen-lev/whg.txt
I would like to commit this school to the list, since it's my school, and Im currently working in the IT-Club there and use CLion to program my Arduinos. Since Im a student, im not able to pay the license and would like to use the school program.
I hope for the Best!
Alexander
=> My School in Germany

lib/domains/us/nj/k12/monroe/students.txt
School website: https://www.monroe.k12.nj.us/
=> Added Monroe Townhall School

lib/domains/ro/scoalaghlazar.txt
Please let me know if any more information is needed.
=> Added domain: scoalaghlazar.ro

lib/domains/id/ac/ubs.txt
adding Universitas Bani Saleh / Bani Saleh University
https://ubs.ac.id/
=> Add Universitas Bani Saleh

lib/domains/it/edu/iistommasosalvini.txt, lib/domains/it/istitutosalvini.txt
@istitutosalvini.it is the official mail of my school for students. @iistommasosalvini.edu.it is the official mail of my school only for teachers. The website of my school is iistommasosalvini.edu.it and as you can see, the whois domain information are the same between istitutosalvini.it and iistommasosalvini.edu.it.
Thanks in advance!
=> Add Istituto Tommaso Salvini

lib/domains/cn/ac/sim/mail.txt, lib/domains/ps/edu/israa.txt
=> add email domain for SIMIT, CAS

lib/domains/edu/itiscardanopv.txt, lib/domains/it/edu/itiscardanopv.txt
fixed the position of the file to reflect correct domain name: itiscardanopv.edu.it
=> fixed the position of the file to reflect correct domain name: itiscardanopv.edu.it

lib/domains/sg/org/pathlight/student.txt
website: https://www.pathlight.org.sg/
wiki: https://en.wikipedia.org/wiki/Pathlight_School
=> add Pathlight School

lib/domains/be/ifapme/apprenant.txt
**Institut wallon de Formation en Alternance et des indépendants et Petites et Moyennes Entreprises**
=> Create Apprenants.txt for IFAPME

lib/domains/mx/edu/upbicentenario.txt
Universidad Politécnica del Bicentenario
=> Add UPB University

lib/domains/nl/porteum/ll.txt
Added my friend's school
https://www.porteum.nl
=> Add Porteum Lelystad

lib/domains/in/ac/medicaps.txt, lib/domains/org/ipsacademy.txt
IPS official website url : https://www.ipsacademy.org/
Medicaps official website url : https://www.medicaps.ac.in/
=> Added IPS Academy Indore and Medicaps University Indore

lib/domains/eus/tolosaldealh.txt
the schools website is this: [website](https://tolosaldea.hezkuntza.net/web/guest_english)
=> add tolosaldealh to eus schools

lib/domains/ax/gymnasium.txt
=> Add Ålands Gymnasium

lib/domains/de/wvs-ffm.txt
Added domain for Werner-von-Siemens-Schule in Frankfurt Germany.
=> added wvs ffm

lib/domains/berlin/afg-schule.txt
Added Anne-Frank Gymnasium in Berlin
=> Add Anne-Frank Gymnasium

lib/domains/uk/org/ballymenaacademy.txt
Added Ballymena Academy to the domains
=> Add files via upload ( Ballymena Academy)

lib/domains/ro/scoalaiorguiordan.txt
- School's official website URL: [http://www.scoalaiorguiordan.ro/](http://www.scoalaiorguiordan.ro/)
- IT-related course proof URL: [http://www.scoalaiorguiordan.ro/hardcore-hackathon.html](http://www.scoalaiorguiordan.ro/hardcore-hackathon.html)
=> Add "Iorgu Iordan" Secondary School Tecuci

lib/domains/es/facultyue.txt
Add email domain for teachers of the European University of Madrid
=> Universidad Europea faculty

lib/domains/net/wsd.txt
Per the instructions adding the school district.
=> Added Weber School District

lib/domains/com/brantfordcollege.txt
Adding branford college, we are approved Career College based out of Mississauga Canada
=> Added brantford College

lib/domains/org/amityregion5.txt
The email domain currently registered for Amity Regional High School, amityschools, is old and currently inaccessible. The current email domain is amityregion5
=> Add new Amity address 

lib/domains/org/aguafria.txt
Add Email Domains from Canyon View High School
=> Add Canyon View High School

lib/domains/mx/edu/utculiacan.txt
Incorporación de la Universidad Tecnológica de Culiacán
=> Universidad Tecnológica de Culiacán

lib/domains/th/ac/e-tech.txt
https://www.e-tech.ac.th/site/index.php
=> Add Eastern Technological College (E.TECH)

lib/domains/eg/edu/o6u.txt
This pull request adds the email domain `o6u.edu.eg` for October 6 University in Egypt to the JetBrains swot repository. October 6 University (O6U) is a private university located in Giza, 6th of October City, Egypt.
- **Name**: October 6 University (O6U)
- **Location**: 6th of October City, Giza, Egypt
- **Establishment**: Established by the Republican Decree no. 243 in 1996
- **Accreditation**: All awarded degrees are accredited and validated by the Egyptian Supreme Council of Universities
- **Associations**:
- Member of the Association of Arab Universities since 1997
- Member of the Association of African Universities
- Information Systems & Computer Science (Accredited by NAQAAE)
- Engineering
- Medicine (Accredited by NAQAAE)
- Pharmacy (Accredited by NAQAAE)
- Dentistry (Accredited …
=> Include October 6 University (o6u.edu.eg) in JetBrains swot repository

lib/domains/pk/edu/aror.txt
Aror University
Aror University of Art, Architecture, Design and Heritage
=> aror.edu.pk added

lib/domains/org/farnborough-hill.txt
**School Name:** Farnborough Hill
**Website:** https://www.farnborough-hill.org
**Computing & ICT Curriculum Page:** https://www.farnborough-hill.org/curriculum/curriculum/computing-and-ict
=> Add Farnborough Hill

lib/domains/ec/edu/uteg.txt
Universidad Tecnológica Empresarial de Guayaquil
=> Add name of the university I teach Java/Kotlin

lib/domains/mx/edu/unistmo/bianni.txt
Here is the main page of the Universidad del Istmo: https://www.unistmo.edu.mx/
Here is the page where they recognize the institutional email presented in the pull request: https://www.unistmo.edu.mx/correo.html
I attach the screenshot that shows that they recognize the email presented in the pull request (I only make the request for the bianni one domain)
=> Add University Of Istmo

lib/domains/mx/edu/utd.txt
Updated the universities list to include Universidad Tecnológica de Durango.
=> Add: utd university of mexico

lib/domains/pl/edu/uws.txt
University official website:  https://www.uws.edu.pl/
Official Website for Institute of Computer Science: https://ii.uws.edu.pl/
=> Add domain for University of Siedlce

lib/domains/pk/edu/zu.txt
=> Added Ziauddin University

lib/domains/com/zgym45.txt
Gymnasium 45
{[Website URL](https://www.zgym45.com/)}
=> Gymnasium 45

lib/domains/pl/edu/zs1mm/live.txt
We use live.zs1mm.edu.pl for student emails so I'm adding 'live.' and not the domain itself.
School website: http://zs1mm.edu.pl
=> Add Zespol Szkol Nr 1 im. Kazimierza Wielkiego at Minsk Mazowiecki, Poland

lib/domains/mx/edu/tecmartinez.txt
Dear JetBrains Administrator,
I would like to request verification of the institutional email from the **Instituto Tecnológico Superior de Martínez de la Torre**. It is worth mentioning that the domain of the institutional email (tecmartinez.edu.mx) is different from our official website. Attached are the resources.
**ITSMT website:**
[martineztorre.tecnm.mx](https://martineztorre.tecnm.mx/)
**Our university offers a degree in Computer Systems Engineering:**
[Computer Systems](https://martineztorre.tecnm.mx/g/computacionales)
=>  Request verification of the ITSMT

lib/domains/id/ac/utmj.txt
Add UTMJ as a university in Github Education
=> Add UTMJ as a university in Github Education

lib/domains/education/mile.txt
Lexicon Management Institute of Leadership and Excellence
=> Lexicon Management Institute of Leadership and Excellence

lib/domains/vn/edu/tnus.txt
- the school official website URL: https://tnus.edu.vn/
- the school street address, including city and country: Phường Tân Thịnh, TP. Thái Nguyên, Tỉnh Thái Nguyên Việt Nam
- an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course: https://en.tnus.edu.vn/undergraduates
- a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students: https://sinhvien.tnus.edu.vn/
Thank you 😄
=> Thai Nguyen University

lib/domains/in/edu/dsce.txt
College Name : **Dayananda Sagar College of Engineering**
College Official Website : https://www.dsce.edu.in
=> Add Dayananda Sagar College of Engineering

lib/domains/de/bbs-einbeck.txt
- [the university official website URL, if it is different from the domain you are submitting](https://www.bbs-einbeck.de/)
- [a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university](https://www.bbs-einbeck.de/it-berufe/#tab-id-7)
- [ a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.](https://www.bbs-einbeck.de/kontakt/)
=> added bbs-einbeck domain

lib/domains/pl/nysa/pans/st.txt
University official website:
https://pans.nysa.pl
URL where IT course is offered:
https://pans.nysa.pl/org/informatyka/strona/kierunek-informatyka
=> Add PANS Nysa to JetBrains

lib/domains/mr/edge.txt
Add Edge Business School domain: edge.mr
=> Add EDGE Business School

lib/domains/np/edu/gci.txt
=> To add my educational institution 

lib/domains/id/ac/politeknik-sampit.txt
add domain politeknik-sampit.ac.id
Website : https://politeknik-sampit.ac.id/
Address : Jalan Tjilik Riwut, Komplek Perumahan Wengga Metropolitan Barat No.KM 3, Baamang Tengah, Kec. Baamang, Kabupaten Kotawaringin Timur, Kalimantan Tengah 74312 , Indonesia
=> add domain politeknik-sampit.ac.id

lib/domains/tr/k12/bilfen/stu.txt
Bilfen schools from Turkey have been added.
=> Bilfen schools from Turkey have been added.

lib/domains/us/biu.txt
Broward International University
URL: https://www.biu.us/
Address: 801 Brickell Ave Office 736 - 7th Floor, Miami, FL 33131, United States URL Program IT: https://www.biu.us/en/program/masters-of-science-in-virtual-software-engineering
=> Add biu.txt

lib/domains/net/lycee-mermoz/etud.txt
- the university official website URL:  https://jean-mermoz-montpellier.mon-ent-occitanie.fr/
- a URL of a page on the official website where a long-term... : https://jean-mermoz-montpellier.mon-ent-occitanie.fr/formations-post-bac/bts/bts-sio-services-informatiques-aux-organisations-1743.htm
- a URL of a page or some other proof :
=> Request for mermoz high school

lib/domains/in/pgmozecoepune.txt
www.pgmozecoepune.in
https://www.pgmozecoepune.in/information-technology-department/
Prof. Abidali Shaikh
Head of Information Technology Department
=> Parvatibai Genba Moze college of Engineering Pune

lib/domains/us/ca/k12/husd.txt
Please add Tennyson High School which is in Hayward Unified School District and its related @husd.k12.ca.us email address
=> Add Tennyson High School 

lib/domains/mx/edu/uth.txt
Universidad Tecnologica de Huejotzingo
Institution/School Website
https://www.uth.edu.mx/
Email Users
=> add uth.txt

lib/domains/uk/org/bestacademies.txt
Education account required. bestacademies.org.uk file added to repository.
=> File Added to domain list

lib/domains/com/onmicrosoft/kpiapeps.txt
Changelog:
* Added kpiapeps.txt
=> Add new domain for Kiev Politechnical Institute 

lib/domains/be/iram/student.txt
IRAMPS website:
https://iramps.be/etudes/informatique-de-gestion/
=> Add IRAMPS 

lib/domains/au/edu/tas/tastafe.txt
TasTAFE is a vocational higher education institution based in Tasmania, Australia.
=> Added TasTAFE

lib/domains/de/ers-hm/schueler.txt
https://www.ers-hameln.de/index.htm
=> Add Eugen-Reintjes-Schule Hameln

lib/domains/au/edu/catholic/cabra.txt
**School URL:** https://www.cabra.catholic.edu.au/
**School Curriculum:** https://www.cabra.catholic.edu.au/wp-content/uploads/2024/02/7-12-Curriculum-and-Co-Curricular-Activities-Flyer-2024.pdf
* We offer Coding under Visual Art, Design and Digital Technologies, as well The Academic Challenge & Enrichment (ACE) programs we have coding in the Robocup.
**URL Showing Email Address in USE:** https://www.cabra.catholic.edu.au/learning/curriculum/
**School Address:** 225 Cross Rd, Cumberland Park, South Australia, Australia 5041
=> Add Cabra Dominican College Email Address (cabra.catholic.edu.au)

lib/domains/de/kapellen-ms.txt
Adds the kapellen-ms.de domain to the registry.
=> Added Kapellen-Middleschool

lib/domains/cz/sps-tachov.txt
/* Website:
https://sps-tachov.cz/
** Domain:
name@sps-tachov.cz
=> Added SPŠ Světce

lib/domains/vn/edu/tbd.txt
Information technology major 
https://tbd.edu.vn/nganh-hoc/cong-nghe-thong-tin/
=> Add Thai Binh Duong University

lib/domains/org/jimsindia.txt
=> add JIMS college

lib/domains/np/edu/tu/bimc.txt
1. The official website URL of the campus under affiliation of Tribhuvan university.
https://bimc.tu.edu.np/
2. A URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university.
https://bimc.tu.edu.np/pages/science-and-technology-courses-933
Screenshot from the offiicial website showing **Bachelor of Science in Computer Science and Information Technology** course:
3. A URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.
Screenshot from the official website showing the contact email address:
=> Adds 'Birendra Multiple Campus'

lib/domains/org/pinebushschools.txt
Hello, I am a student at Pine Bush High School going into my Sophomore year and I am learning Computer Science. I would be very grateful if JetBrains accepted this application. 
-David
=> Trying to get my HS added

lib/domains/in/anjarakandy.txt
This pull request adds the Institute of Paramedical Sciences Kannur Medical College to the JetBrains SWOT list. The institute's email domain is `anjarakandy.in`, and this addition will allow students from this institution to benefit from JetBrains' offerings for students, women in tech, and open source contributors.
Details:
- Name: Institute of Paramedical Sciences Kannur Medical College
- Domain: anjarakandy.in
Thank you for considering this addition.
=> Add Institute of Paramedical Sciences Kannur Medical College

lib/domains/nl/koncon.txt
our sonology and sound engineering departments frequently make use of coding
=> domain request for Royal Conservatoire The Hague

lib/domains/edu/umo.txt
=> umo.edu addition

lib/domains/sa/edu/effat.txt
1-https://www.effatuniversity.edu.sa/english/pages/default.aspx 
2-https://www.effatuniversity.edu.sa/english/academics/undergraduate/coe/pages/cs.aspx
=> Add Effat university

lib/domains/ec/edu/ube.txt
Domain: https://ube.edu.ec/
IT related course: https://ube.edu.ec/Ingenieria_sistemas_inteligentes
=> Add Universidad Bolivariana del Ecuador

lib/domains/org/devrijeruimte.txt
De Vrije Ruimte (in English: The Free Space) is a democratic school in Netherlands The Hague offering primary and secondary education at MAVO, HAVO, and VWO levels. The school emphasizes self-directed learning, sociocratic decision-making, and Living Values Education. Students, teachers, and parents collaboratively govern the school, ensuring everyone has a voice in decisions. The curriculum focuses on developing students' inner motivation, responsibility, and empathy through a values-based approach. The school is privately funded through parent contributions, donations, and subsidies for innovative projects.
For more details, visit https://www.devrijeruimte.org/.
=> De Vrije Ruimte: Empowering Self-Directed Learning in a Democratic School Environment

lib/domains/np/edu/tu/pkmc.txt
https://pkmc.tu.edu.np/ -> This college has IT related courses like BCA, BIM
=> Added padma kanya multiple campus domain

lib/domains/com/rayatbahra.txt
My school is not available in JetBrains student/teacher benefits hence adding it
=> Added New School Info

lib/domains/edu/otc.txt
College URL - https://www.otc.edu
College edu mail domian - "otc.edu"
=> Please Add OTC

lib/domains/com/fosbos-mm/schueler.txt
https://fosbos-mm.com/
email format:
firstname.lastname@schueler.fosbos-mm.com
Technical High School in southern germany
=> add FOSBOS Memmingen

lib/domains/org/esj.txt
School Name: Episcopal School of Jacksonville
Email Domain: esj.org
Website: esj.org
Year-Long Tech Course (TI122A Advanced Placement Computer Science Principles): https://esj.org/academics/coursecatalogue-us/technologyandinnovation/
=> Episcopal School of Jacksonville 

lib/domains/edu/umsystem.txt
https://missouri.edu/
https://webmail.missouri.edu/
=> Add University of Missouri to domain list

lib/domains/es/unia/estudiante.txt
Universidad Internacional de Andalucía, Spain
=> Added UNIA. Educational License.

lib/domains/de/best-sabel.txt
BEST-Sabel Designschule Berlin
=> Add BEST-Sabel Designschule

lib/domains/id/ac/iikmpbali.txt
School name: Universitas Bali Internasional
Email Domain: @iikmpbali.ac.id
Website: unbi.ac.id
Address: Jl. Seroja, Gang Jeruk, Kelurahan Tonja Denpasar Utara, Bali 80239, Indonesia
=> Add iikmpbali domain

lib/domains/pk/edu/fcoe.txt
Kindly merge it on master branch so i our staff can use jetbrain product
University website: https://fcoe.edu.pk/
Course: https://fcoe.edu.pk/bscs/
=> Add Fazaia college of education for women

lib/domains/edu/worcester.txt
[worcester.edu](https://www.worcester.edu/)
486 Chandler St,
Worcester, MA 01602
https://catalog.worcester.edu/undergraduate/school-education-health-natural-sciences/computer-science/major-computer-science/#requirementstext
=> Worcester State University

lib/domains/et/edu/bitscollege.txt
- School website -> _https://www.bitscollege.edu.et/_
-  Program link -> _https://www.bitscollege.edu.et/software-engineering/_
-
=> Added bitscollege.txt to appropriate folder.

lib/domains/com/stpetershyd.txt
This is my college official website check it out to verify 
https://spechyd.ac.in/
=> added St Peter's Engineering College

lib/domains/edu/kiet.txt
University official website : https://www.kiet.edu/
4 year undergrad in Computer Science & Engineering : https://www.kiet.edu/home/access_depart_data/NQ==
=> ADD KIET Group of Institutions

lib/domains/edu/clcillinois.txt
##College of Lake County
adding College of Lake County to domain list
https://www.clcillinois.edu/
Thank you.
=> College of Lake County. Grayslake Illinois.

lib/domains/org/watfordboys/students.txt
School website: https://www.watfordboys.org
=> Add Watford Grammar School for Boys

lib/domains/edu/massbay.txt
Add massbay.edu domain for JetBrains student access
=> Add massbay.edu

lib/domains/edu/dccc.txt
DCCC is a community college offering 2-year IT and computer science courses.
https://www.dccc.edu/academics/academic-divisions/business-computing-social-science
BCSS department offers multiple 2-year degree programs in Comp Sci and IT related fields (programming, web development, computer networking, etc)- and feeds into 4-year university programs locally and abroad (notably Drexel, Villanova, Temple and Westchester University).
=> Adding Delaware County Community College

lib/domains/eg/edu/moe/giza1.txt
Hello,
My name is Adam, and I am a student at El Saidia Secondary Military School for Boys. I hope to use JetBrains products for free for educational purposes. I use these products for programming in my classes and want to improve my skills.
Here is my school email: 494057643@giza1.moe.edu.eg.
I would like to explain a few things about the educational system in my country:
There is no email or domain for each individual school.
Each region has a different prefix domain. For example, Giza has giza1.moe.edu.eg, and other regions, like Sohag, have their own prefixes.
The website for our Ministry of Education is https://office365.emis.gov.eg/. This serves as proof of my educational email.
Lastly, I want to bring to your attention a similar case which might be relevant: …
=> Add giza1.txt

lib/domains/cl/inacap.txt, lib/domains/cl/inacapmail.txt
adding Inacap from chile to mailing @inacapmail.cl
=> adding Inacap

lib/domains/edu/4cd.txt, lib/domains/edu/dvc.txt
https://www.dvc.edu/about/accreditation/index.html https://www.dvcinquirer.com/archive/uncategorized/2020/03/12/4cd-student-trustee-election-its-dvcs-turn/
=> Add dvc.txt

lib/domains/edu/udc.txt
Attached are screenshots indicating that this is a real university domain and that they have a CS program.
=> new university domain

lib/domains/edu/phsc/student.txt
Official Website: https://phsc.edu/
Information about Student Email Format: https://phsc.smartcatalogiq.com/en/2023-2024/catalog-and-student-handbook/information-for-new-applicants/student-email-account/
Student Email Format: `<some-random-id>@student.phsc.edu`
List of example IT degrees PHSC provides: https://phsc.edu/academics/programs/technology
=> Add Pasco-Hernando State College

lib/domains/kr/ac/hs.txt
if there is problem in verifying, please let me know
=> Request for verification in the Hanshin University 

lib/domains/edu/hccs/student.txt
**Official website URL:** 
https://www.hccs.edu/
**Computer Science (A.S.) Degree Program (>1 Year):** 
https://catalog.hccs.edu/preview_program.php?catoid=23&poid=9662&returnto=1544
**Domain proof screenshot:**
=> Add student.hccs.edu

lib/domains/edu/american.txt
https://american.edu/
https://www.american.edu/cas/cs/
=> American University

lib/domains/hu/bme/math.txt
Mathematics department of Budapest University of Technology
https://math.bme.hu/?language=en
List of courses, including programming courses: https://www.ttdh.bme.hu/altalanos/nyilt/edu/MathMSc_curriculum.html
=> Added math.bme.hu

lib/domains/nz/school/farmcove/students.txt
Website: https://farmcove.school.nz/
=> Add Farmcove Intermeditate

lib/domains/org/subharti.txt
Subharti University has been accredited ‘A’ by NAAC and recognised by UGC as a private university. The university was established in the year 2008. The university has been recognised as (SIRO) Scientific and Industrial Research Organisation by DST and a Nodal Centre for ISRO Training initiative.
Primary Domain : https://subharti.org/
=> Added Swami Vivekanand Subharti University

lib/domains/tw/edu/tc/wufai.txt
Added domain wufai.tc.edu.tw
Website : https://wufai.tc.edu.tw/
=> add for wufai.tc.edu.tw

lib/domains/org/grps/students.txt
Grand Rapids Public Schools
[{Website URL}](https://grps.org/)
- [ x ] Students
- [ x ] High School or equivalent
=> Add Grand Rapids Public Schools

lib/domains/mx/edu/unisant.txt
1. https://unisant.edu.mx/
2. https://unisant.edu.mx/oferta-academica/licenciatura-informatica/ (10 month to 36 months )
3. Screenshot from my gmail account with my profesor notification of new activity of student
=> Add Universidad Santander

lib/domains/id/ac/unibi/student.txt
please help me to add my account email from university, cz i have a problem with apply free product for student
Your email address does not belong to any university that we know. You can apply with another method (see tabs above) or [add your school](https://www.jetbrains.com/shop/eform/students/contributeUniversity?email=figur.ua20%40student.unibi.ac.id) to JetBrains' list.
=> feat: Added subdomain student

lib/domains/id/sch/sdi-aliks.txt
Hello, jetBrain Admin,
Please give some free webstrom subcription or any discount for student at elementary school who wants to study coding.. 
Thank You
Cheers
=> add school for my daughter learning code

lib/domains/uk/ac/cityplym.txt
pull request from andrew reed at city college plymouth
=> Created cityplym.txt

lib/domains/edu/jeffersonstate.txt
URL: https://www.jeffersonstate.edu/
Program: https://www.jeffersonstate.edu/programs/computer-information-systems-technology/
Email Domain: https://www.jeffersonstate.edu/policies/policies-email/
=> Add Jefferson State Community College

lib/domains/institute/immune.txt
URL institute: https://immune.institute/en/
=> Immune institute

lib/domains/au/edu/vic/rt.txt
read more about us: http://ringwood.training
=> Added Ringwood Training domain text file.

lib/domains/edu/cocc.txt
University official website URL: https://www.cocc.edu/
URL of  official website where a long-term (>1 year) IT related course: https://www.cocc.edu/programs/cis/programs.aspx
URL of a page proving domain: https://www.cocc.edu/departments/its/student-tech-support/cocc-email.aspx
=> Adding Central Oregon Community College to SWOT

lib/domains/edu/columbusstate/students.txt
Previously submitted for this school (/domains/edu/columbusstate.txt) but the format submitted did not work so I am resubmitting in the format as from generated zip file. /domains/edu/columbusstate/students.txt
School URL:
https://www.columbusstate.edu/
URL of CS program:
https://www.columbusstate.edu/academics/degrees-and-programs/bs-computer-science.php
URL of Student Portal showing email format:
https://login.microsoftonline.com/0f04a099-6dc7-44fd-a875-00922906fc9b/saml2?SAMLRequest=jZLNbtswEITveQqBd4kUJUsWIStwaxQ1kLZG7PbQS0FRVEKUPy6XDJq3L%2BU0aE5Gr4PdnW92t7%2F9bXT2JD0oZzeoLAi6HW76bQyP9l7%2BihJCliosbFD0ljkOCpjlRgILgh23n%2B4YLQg7execcBpl%2B90G%2FRjXYzW3pG7K9TiTilYVp1LODeflelV1sh25XBG6ajqUfXv1TnNSO0CUewuB25AkQuuctHnZnghlNWG0%2FI6yXYJSlodL12MIZ2AYa%2FegbGGU8A7cHJzVyspCOIPJTGpOui5vJtHmdT1PO …
=> Adds correct format for Columbus State University

lib/domains/uk/co/kps.txt
=> Added Kensington Park School

lib/domains/org/miltonps.txt
Official website of mhs: https://www.miltonps.org/o/mhs
Proof of long term IT course: https://www.miltonps.org/o/mhs/page/career-tech
They have an AP comp sci principles class I am taking next year. 
Proof that this domain is used by our school. As you can see at the top the principals email has the same domain name as mine: https://www.miltonps.org/o/mhs/page/principal-corner
=> Adding mps to swot

lib/domains/net/fisdk12.txt, lib/domains/org/fisdk12.txt
=> add Friendswood High School

lib/domains/ec/edu/itsjapon.txt
Intituto Técnico Superior Japón
=> Intituto Técnico Superior Japón

lib/domains/uk/sch/sheffield/forgevalley.txt
Hi, Forge Valley School should be included as it is a secondary school and students there like myself should be given the chance to claim student benefits that JetBrains offer - thank you!
=> Adding a sheffield UK secondary school

lib/domains/kr/ac/gist.txt, lib/domains/kr/ac/gist/gm.txt
add Gwangju Institute of Science and Technology
=> feat: add 광주과학기술원 (gm.gist.ac.kr, gist.ac.kr)

lib/domains/edu/isb.txt
school name : https://www.isb.edu/en.html
email ends isb.edu
Attached images of [home page
](https://www.isb.edu/en.html) and also last year license details
=> Indian School of business Registration

lib/domains/br/com/objetivolorena/aluno.txt
- **Official website**: [Colégio Objetivo Lorena](https://objetivolorena.com.br)
=> Colégio Objetivo Lorena

lib/domains/kr/ac/uc/office.txt
Add education Ulsan College,
email: @office.uc.ac.kr
=> add Ulsan College

lib/domains/mm/edu/ucsmub.txt
Adding my university ,
University Of Computer Studies, Maubin
Myanmar.
=> Adding my university , University Of Computer Studies, Maubin

lib/domains/edu/sabanciuniv.txt
University url: https://www.sabanciuniv.edu/
=> Adding Sabanci University

lib/domains/kr/ac/ut/a.txt, lib/domains/kr/ac/ut/g.txt
Korea National University of Transportation
=> Korea National University of Transportation

lib/domains/edu/sofia.txt
https://www.sofia.edu/
https://www.sofia.edu/categories/masters-computer-science/
=> add sofia university

lib/domains/edu/hoseo.txt, vision.txt
add file /lib/domains/edu/hoseo/vision.txt to add a domain
=> add file /lib/domains/edu/hoseo/vision.txt to add a domain

lib/domains/edu/ceconline.txt
=> add College of Engineering Chengannur

lib/domains/edu/bristolcc.txt
Thank you for considering the request to add my school to your approved schools domain list!
Their website is located here: https://bristolcc.edu/
Here are [some] of their CS offerings
https://catalog.bristolcc.edu/computer-information-systems/computer-science-transfer <-What I am enrolled in
https://catalog.bristolcc.edu/computer-information-systems
https://catalog.bristolcc.edu/degrees <- all offered degrees
Here is the student log in page for BCC
https://id.quicklaunch.io/authenticationendpoint/login.do?client_id=n_vl98mknOeSxFq4Zs_Td6obomwa&commonAuthCallerPath=%2Foauth2%2Fauthorize&forceAuth=false&passiveAuth=false&redirect_uri=https%3A%2F%2Fmy.bristolcc.edu%2Fauth%2Funifyd%2Fpassport%2Fcallback&response_type=code&scope=openid&tenantDomain=bristolcc.edu&sessionDataKey=d94ad5a7-fc36-4c …
=> Adding Bristol Community College.

lib/domains/edu/Suffolk/su.txt
Hello, The domain should be correct now, Thank you :)
=> Adding "Suffolk University"

lib/domains/id/ac/hamzanwadi/student.txt
Official IT Course: https://elearning.hamzanwadi.ac.id/course/view.php?id=4095
Proof Images:
=> add: universitas hamzanwadi

lib/domains/np/edu/axisschool.txt
=> Axis Vidyashram

lib/domains/uk/ac/ua92/bootcamps.txt
Request to add University Academy 92 to the list of educational institutions.
=> Adding UA92

lib/domains/mx/edu/utdelacosta.txt
Add domain Universidad Tecnológica de la Costa
=> Add file UT de la Costa

lib/domains/dz/esas-eloued.txt
=> Submit of HSSAE

lib/domains/kr/ac/handong.txt
=> add Handong Global Univ.

lib/domains/kr/ac/cwnu/gs.txt
=> south korea

lib/domains/edu/amnh.txt
https://www.amnh.edu
https://www.amnh.org/research/richard-gilder-graduate-school
https://www.amnh.org/research/richard-gilder-graduate-school/academics/degrees/phd-comparative-biology
https://www.amnh.org/research/computational-sciences
=> Adding American Museum of Natural History - Richard Gilder Graduate School

lib/domains/edu/liu/my.txt
Add new Long Island University student emails (first.last@my.liu.edu)
=> Add Long Island University

lib/domains/edu/purdueglobal/student.txt
Please add Purdue Global University to list
=> Add Purdue Global University

lib/domains/edu/ctc/pierce.txt
CS Degree Homepage: https://www.pierce.ctc.edu/computer-science
Staff Directory:  https://www.pierce.ctc.edu/staff-directory   
Thanks!
=> pierce.ctc.edu

lib/domains/edu/kgi.txt
Keck Graduate Institute
535 Watson Dr.
Claremont, CA 91711
http://www.kgi.edu
=> Keck Graduate Institute

lib/domains/kr/ac/gwangju.txt
Add a domain : [Gwang-ju Univ](https://eng.gwangju.ac.kr/main)
=> Add domain : Gwang-ju univ of KR

lib/domains/edu/wellesley.txt
Wellesley College
https://www.wellesley.edu
CS Department: https://www.wellesley.edu/departments-programs/department/computer-science
Study Programs of CS: https://catalog.wellesley.edu/display.php?pos=25&doc_type=computer+science+major
=> add Wellesley College

lib/domains/vn/edu/kgmc.txt
Update information about Kien Giang Medical College, December 2024
=> Update, December 2024

lib/domains/hu/bme/epitesz.txt
=> add epitesz.bme.hu domain

lib/domains/edu/sac.txt
Santa Ana College
https://www.sac.edu/Pages/default.aspx
CS Department: https://www.sac.edu/AcademicProgs/Business/ComputerScience/Pages/default.aspx
=> add Santa Ana College

lib/domains/edu/tce/student.txt
=> Thiagarajar College of Engineering

lib/domains/kr/ac/cju.txt
Please add Cheongju University.
Their website is located here: [https://cju.ac.kr](https://cju.ac.kr)
Thank you for your time and consideration!
=> Add Cheongju University

lib/domains/edu/phoenix.txt
University of Phoenix
https://www.phoenix.edu/
=> add University of Phoenix

lib/domains/ro/eminescucj.txt
Add Highschool Mihai Eminescu, Cluj-Napoca
http://eminescucj.ro/pages/politica-educationala.htm
=> Add Highschool Mihai Eminescu Cluj-Napoca

lib/domains/edu/miracosta.txt
Request to add MiraCosta College to repository
=> Request to add MiraCosta College to repository

lib/domains/edu/mahidol.txt
=> Add Mahidol Edu Domain

lib/domains/edu/miamioh.txt
Miami University, Oxford, OH
https://miamioh.edu/
https://miamioh.edu/cec/departments/computer-science-software-engineering/index.html
https://miamioh.edu/policy-library/students/undergraduate/academic-regulations/student-email-policy.html
=> Added Miami University of Ohio (USA)

lib/domains/kr/ac/jj/office.txt
Homepage: https://www.jj.ac.kr
Department : https://www.jj.ac.kr/sw/
=> Add Jeonju university domain

lib/domains/id/ac/binainsani.txt
- Official Website : [Bina Insani University](https://binainsani.ac.id)
- Official E-Learning: [Ecampus Bina Insani University](https://ecampus.binainsani.ac.id)
- Domain email: @binainsani.ac.id
=> Add Bina Insani University

lib/domains/mx/edu/utvtol.txt
**This is the oficial web page of my university** 
- https://utvt.edomex.gob.mx/
**This is the course of IT in the university the name of the engineering is Engineer in IT and Digital Innovation** 
- https://utvt.edomex.gob.mx/carreras-perfil-profesional
=> Add Universidad Tecnologica del Valle de Toluca

lib/domains/edu/flcc.txt
Finger Lakes Community College
https://flcc.edu/
=> Add Finger Lakes Community College

lib/domains/edu/cvtc.txt
* https://www.cvtc.edu/academics/programs/it-software-developer
* https://www.cvtc.edu/academics/programs/it-data-analyst
[cvtc-official-email-domain.pdf](https://github.com/user-attachments/files/16363969/cvtc-official-email-domain.pdf)
=> Add cvtc.edu domain

lib/domains/edu/pmu.txt
=> Add pmu.edu domain

lib/domains/cn/swis.txt
This is an international school in Shenzhen China, the official website is here: https://www.swis.cn/#/. I'm a noob in github, hope my pull request is correct. Thank you!
=> Adding Shen Wai International School

lib/domains/org/cheltenhamcollege.txt
Please add Cheltenham College to your approved University/School list
=> Cheltenham College Add files via upload

lib/domains/com/iebschool/alumni.txt
With this PR I'd like to add IEBS Business School.
https://www.iebschool.com/
=> Add IEBS Business School

lib/domains/net/tcusd.txt
Temple City School District - https://www.tcusd.net/
For Temple City High School students
https://tchs.tcusd.net/for-students/course-offerings
email address format is as follow: <first initial><lastname>@tcusd.net
Thank you.
=> Adding Temple City Unified School District

lib/domains/kr/ac/snue/student.txt
University Official page -> https://en.snue.ac.kr/en/main.do
Major: Computer Education
https://en.snue.ac.kr/en/cm/cntnts/cntntsView.do?mi=3150&cntntsId=3147
https://www.snue.ac.kr/snue/cm/cntnts/cntntsView.do?mi=3017&cntntsId=3011
=> add student.snue.ac.kr

lib/domains/kr/ac/uhs/office.txt
https://www.uhs.ac.kr/english/index.do
=> Add Hyupsung University

lib/domains/kr/ac/scnu/s.txt
https://www.scnu.ac.kr/neweng/main.do
=> Add Sunchon National University

lib/domains/kr/ac/ocu/mail.txt
=> 한국열린사이버대학교추가

lib/domains/edu/ucjc.txt
Universidad Camilo Jose Cela
Camilo Jose Cela University
=> Add Camilo Jose Cela University

lib/domains/kr/ac/anu.txt
=> Add a domain for Andong National University

lib/domains/de/effner/schueler.txt
The domain for students is @schueler.effner.de
=> Create schueler.txt and add @schueler.effner.de to database

lib/domains/au/edu/vic/ringwoodsc.txt
Ringwood Secondary College - EDU.AU
=> Add Ringwood Secondary College

lib/domains/pk/edu/gcbskp.txt
This pull request adds the domain gcbskp.edu.pk for Govt. Graduate College, Civil Lines, Sheikhupura to the JetBrains swot repository.
University Details:
Official Name of the University: Govt. Graduate College, Civil Lines, Sheikhupura
Official Website URL: https://gcbskp.edu.pk/
URL of IT-related Course (long-term >1 year): https://gcbskp.edu.pk/department-description.php?id=Mw&facid=NA
=> Add Govt. Graduate College, Civil Lines, Sheikhupura to JetBrains swot

lib/domains/edu/hartnell/student.txt, student.txt
Website: https://www.hartnell.edu/
Course: https://www.hartnell.edu/academics-affairs/academics/stem/cis/computer-science-option.html
=> Hartnell College

lib/domains/edu/strayer/my.txt
Attempting to add Strayer University to the list of student email addresses.
=> Added strayer folder to edu directory

lib/domains/edu/saintpeters.txt
=> Add Saint Peters domain file

lib/domains/kr/ac/sjcu.txt
=> add : 세종사이버대학교

lib/domains/edu/murraystate.txt
This is an addition for Murray State University located in Murray, KY.
Here is a link to the Computer Science and Information Systems department webpage which offers a BSc in Computer Science among other IT related degrees: https://www.murraystate.edu/academics/CollegesDepartments/CollegeOfBusiness/Programs/CSIS/index.aspx
=> Create murraystate.txt for Murray State University

lib/domains/edu/middlesexcc/my.txt
=> middlesex college 

lib/domains/kr/ac/iscu.txt
=> Add Seoul Cyber University

lib/domains/edu/nist.txt
Please add NIST University, Berhampur to the repo. NIST is a Technical Institute which offers courses like BTECH, MTECH, MSC etc
=> Add NIST University, Berhampur

lib/domains/edu/frederick/frederick.txt
adds frederick.edu domain for https://frederick.edu/
Example emails with this domain: https://frederick.edu/about-fcc/contact-us.aspx
=> Creates frederick.txt

lib/domains/com/esc-cybersecurity.txt
**European School of Cybersecurity**
[https://www.esc-cybersecurity.com](https://www.esc-cybersecurity.com/)
=> Adding European School of Cybersecurity

lib/domains/mx/uacj.txt
[https://www.uacj.mx/](url)
> Note:
Alumni email ends with:  alumnos.uacj.mx
Teacher's and school employees email ends with:  uacj.mx
[https://www.uacj.mx/oferta/programas.html?programa=45120&121](url)
=> Add Universidad Autonoma de Ciudad Juarez

lib/domains/edu/alabama.txt
https://www.suscc.edu/
This is root email domain of my college, which is most students have.
=> Please add root domain of Southern Union State Community College

lib/domains/kr/ac/wsu/live.txt
Adding Woosong University, JetBrains SWOT repository.
University Name:  Woosong University
Official Website: https://www.wsu.ac.kr
Mail Domain : live.wsu.ac.kr
Please review it and merge. Thank you!
=> feat : add file

lib/domains/kr/ac/syuin.txt
Adding Sahmyook University, Computer Science and Engineering to the JetBrains SWOT repository.
University Name: Sahmyook University, Computer Science and Engineering
Official Website: https://www.syu.ac.kr/
Mail Domain : syuin.ac.kr
Please review and merge if everything is in order. Thank you!
=> Add Sahmyook university

lib/domains/edu/tms/my.txt
=> Added edu.tms

lib/domains/edu/elgin.txt
**College**: Elgin Community College
**Website**: https://elgin.edu
**Domains**: elgin.edu, student.elgin.edu
**IT Courses:** 
- Overview: https://catalog.elgin.edu/course-descriptions/cis/
- Courses: https://selfservice.elgin.edu:8173/Student/Courses/Search?keyword=computer+science
**Proof of Domain Ownership:**
- **Employees**:
Domain: elgin.edu
Reference: https://www.elgin.edu/directory/
- **Students**:
Domain: student.elgin.edu
Reference: https://elgin.edu/student-services/technical-help/ecc-email/
=> Add "elgin.edu" to JetBrains Swot Repository

lib/domains/edu/butlercc.txt
Added Butler Community College.
=> Added butlercc.txt

lib/domains/edu/wctc.txt, lib/domains/edu/wctc/my.txt
Adding files for my.wctc.edu and wctc.edu
=> Adding Waukesha County Technical College

lib/domains/lk/bci.txt
[bci.txt](https://github.com/user-attachments/files/16437876/bci.txt)
=> add BCI Campus

lib/domains/edu/t-bird.txt
Added Cloud County Community College to the lib/domain/edu/tbird.txt file
=> Updated t-bird.txt

lib/domains/edu/udem.txt, lib/domains/mx/udem.txt
Add Universidad de Monterrey to the domain
=> Universidad de Monterrey

lib/domains/edu/atc.txt
https://www.atc.edu/Study/Programs-of-Study/Technical-and-Continuing-Education/Computer-Technology
=> Aiken Technical College

lib/domains/br/edu/cesmac.txt
Requesting the addition of the institution Centro Universitário CESMAC
=> ADD CESMAC

lib/domains/eu/he-ferrer/stu.txt
Requesting the addition of the institution haute école francisco ferrer (Brussels)
=> Add  domain school he-ferrer

lib/domains/edu/canton.txt
Add State University of New York at Canton
=> Add SUNY Canton

lib/domains/ua/kyiv/ktepcknute.txt
=> add ktepcknute.kyiv.ua domain

lib/domains/py/edu/unp.txt
This is the URL of UNP: https://unp.edu.py/ you can go to the "Facultades" menu and select "Facultad de Ciencias Aplicadas" and then you can select the "Licenciatura en Analisis de Sistemas" option. In this option you can obtain information about the programming courses taught to UNP students.
=> add UNP to the list

lib/domains/ar/edu/unsada.txt
**The official website of the university:** [https://www.unsada.edu.ar/](https://www.unsada.edu.ar/)
**A URL of a page offering a long-term IT-related course:** [https://www.unsada.edu.ar/academico/oferta-academica](https://www.unsada.edu.ar/academico/oferta-academica)
- **Screenshot of the course offerings:**
**Proof of the university recognizing the domain:**
- **Screenshot of the institutional email tutorial page** ([source](https://www.unsada.edu.ar/2-uncategorised/591-tutorial-correo-institucional)) showing the use of `alumnos.unsada.edu.ar` for student emails.
=> Added UNSaDA (https://www.unsada.edu.ar/)

grandview.txt, lib/domains/edu/grandview.txt
IT Major: https://www.grandview.edu/academics/undergraduate/information-technology
Note from the [IT page](https://www.grandview.edu/student-life/services/information-technology) about email issuance:
=> Add Grand View University in Des Moines, Iowa

lib/domains/edu/missouristate.txt
MSU uses both live.missouristate.edu and missouristate.edu for student/faculty email addresses. See here for more information: https://missouristate.teamdynamix.com/TDClient/1931/Portal/KB/ArticleDet?ID=110683
=> Missouri State University

lib/domains/ph/edu/dwcc.txt
adding Divine Word College of Calapan
=> Added my college

lib/domains/edu/ccsnh/students.txt
=> Add College System

lib/domains/edu/moreheadstate.txt
=> Add our current domain via upload

lib/domains/edu/loyolacollege.txt
https://www.loyolacollege.edu/
=> loyola college

lib/domains/id/ac/fastikom-unsiq/mhs.txt
Feature Added: New Domain Identification
Summary:
This merge request introduces the functionality to identify email addresses or domain names associated with colleges or universities. The purpose is to enhance the automation process for approving or rejecting academic discounts by accurately recognizing educational domains.
Changes:
Added a new domain recognition module to identify educational institutions.
Integrated domain checking into the existing approval workflow for academic discounts.
Updated the repository documentation to reflect the new feature.
=> Merge req - new domain from mhs.fastikom-unsiq.ac.id

lib/domains/edu/aiims.txt
Added All India Institutes of Medical Sciences, India
=> AIIMS added

lib/domains/edu/tctc.txt
Adding Tri-County Technical College to the list for verification purposes.
**Official URL**: https://tctc.edu/
**IT-related course**: https://www.tctc.edu/programs/career-programs/computer-technology/
**Proof that email is used by college**: We only utilize [tctc.edu ](https://tctc.edu) as our email domain. A valid email address can be found on our application page: https://www.tctc.edu/admissions/apply-now/
Please let me know if anything is missing and I can provide more info. Thank you!
=> Add Tri-County Technical College to schools list

lib/domains/kr/ac/eulji/stuoffice.txt, lib/domains/kr/ac/stuoffice.txt
I'm a computer major student at Eulji University, and I want to become a contributor to get an intellij student license.
=> feat: add Eulji_University domain

lib/domains/com/onmicrosoft/itbildungshauseducation.txt
https://www.it-bildungshaus.de
https://www.it-bildungshaus.de/umschulung
[Screenshots_assignment_itbildungshauseducation_mailaddresses_to_students.pdf](https://github.com/user-attachments/files/16598687/Screenshots_assignment_itbildungshauseducation_mailaddresses_to_students.pdf)
[527763 AZAV Trägerzertifikat 2021-04-05 deutsch Logo.pdf](https://github.com/user-attachments/files/16598711/527763.AZAV.Tragerzertifikat.2021-04-05.deutsch.Logo.pdf)
[FI12_Maßnahmebogen.pdf](https://github.com/user-attachments/files/16598712/FI12_Massnahmebogen.pdf)
[FI12 HK Genehmigung VZ.PDF](https://github.com/user-attachments/files/16598713/FI12.HK.Genehmigung.VZ.PDF)
=> Add IT-Bildungshaus Domain

lib/domains/ca/pearsoncollege.txt
Hey, I'd like to add my college to the list for JetBrains, thanks.
=> Add files via upload for Pearson College UWC

lib/domains/co/edu/unicolombo.txt
=> Adding unicolombo domain

lib/domains/edu/butte.txt
Landing Page: www.butte.edu
Proof of technical classes: 
* Certificate that will use github [Computer Programming](https://programs.butte.edu/ProgramInfo/13/2761)
* Degree that will use github [Computer Science](https://programs.butte.edu/ProgramInfo/13/2719)
I'm happy to connect you with faculty if there are any questions they might be able to help with.
I know @butte.edu is used for faculty specifically, and is only active while they are.
Example: https://www.butte.edu/directory/faculty.php?username=krepelkaja
=> Add Butte College to Github Educational resources.

lib/domains/kr/ac/kopo.txt
create kopo.txt(Korea Polytechnics)
=> create kopo.txt(Korea Polytechnics)

lib/domains/np/edu/mmp.txt
=> Jetbrains Add files via upload

lib/domains/fr/cloud-campus.txt
As a student i'm proposing to add my school to the repo. It's an online school driven educationnal system centered on web developpement. Here is their website.
https://cloud-campus.fr/cloud-campus-ecole-de-developpement-web-full-stack-en-distanciel-alternance/
=> Requesting to add Cloud Campus. 

lib/domains/nl/scholenaanzee/ll.txt
Our school allows students to follow a 2/3 year long computer science course in high school.
=> Add Scholen aan Zee

lib/domains/ph/com/oed.txt
Add AMA University Online Education (https://oed.com.ph/) to universities
=> Add AMA University Online Education

lib/domains/pk/edu/kiet.txt
[KIET Website Link](https://kiet.edu.pk/)
Address:  KIET, PAF Airmen Academy, PAF Colony Paf Colony Korangi Creek, Karachi, Karachi City, Sindh 75190
County: Pakistan
Undergrad Programs: https://kiet.edu.pk/programs/?ungrad
proof for the domain emails, attachment contains the admission dept email with valid .kiet.edu.pk  domain:
=> feat: add the universty named kiet (.kiet) into the edu directory

lib/domains/sg/nlcssingapore.txt
Adding domain for NLCS Singapore
=> Adding domain for NLCS Singapore

lib/domains/university/atlasskilltech.txt
Liscence for Atlas Skilltech University
=> Liscence for Atlas Skilltech University

lib/domains/rocks/viona.txt
License Request for IBB Institut für Berufliche Bildung AG
As a student of the course for Software Developer by IBB
=> License Request for IBB Institut für Berufliche Bildung AG

lib/domains/kr/ac/induk/office.txt
=> Add Induk University Domain

lib/domains/edu/hbuhsd/student.txt
=> add hbuhsd/student.txt

lib/domains/kr/ac/eulji/g.txt
Eulji university
@g.eulji.ac.kr
=> Add @g.eulji.ac.kr

lib/domains/edu/sandburg/student.txt
https://www.sandburg.edu/
https://www.sandburg.edu/Academics/Pathways/CTE/Information%20Technology.html
=> Carl Sandburg College

lib/domains/edu/afit.txt
Adding an entry for the Air Force Institute of Technology.
Air Force Institute of Technology
2950 Hobson Way
Wright-Patterson Air Force Base, OH 45433-7765
Commercial: [937-255-6565](tel:937-255-6565) | DSN: 785-6565
https://www.afit.edu/
=> Adding afit.edu file

lib/domains/hu/bme/kjk.txt
Hungarian - Budapest University of Technology and Economics - KJK domain
=> hu bme kjk

lib/domains/de/ge-meiersheide.txt
The Gesamtschule Hennef Meiersheide is a school in Hennef with around 1,400 students (one of them is me 😄). We are currently working with Next.js in our computer science class, and we are allowed to choose the IDE we want to use. I would like to use the WebStorm IDE with a student account, but unfortunately, my school is not listed yet. Therefore, I would like to request the addition of Gesamtschule Hennef Meiersheide.
Best regards,
Jonas Zielke
web: [ge-hennef.de](https://www.ge-hennef.de/)
=> add Gesamtschule Hennef Meiersheide

lib/domains/edu/uafs.txt
The domain for the emails are @uafs.edu
=> Adding the University of Arkansas Fort Smith

lib/domains/edu/rose/raider.txt
Official website: https://www.rose.edu/
IT Degree Program information: https://www.rose.edu/content/academics/academic-divisions/business-information-technology/
Lists official email under Student Email Login: https://www.rose.edu/rose-state-student-login (Pertinent portion included in screenshot attached)
=> Rose State College

lib/domains/edu/ycp.txt
- Official Website Link: 
https://www.ycp.edu/
- IT related courses (B.S. Computer Science): 
https://catalog.ycp.edu/preview_program.php?catoid=46&poid=5038
- Proof of domain recognition by school:
https://service.ycp.edu/TDClient/219/Portal/KB/ArticleDet?ID=7372
=> Include York College of Pennsylvania (ycp.edu)

lib/domains/edu/francistuttle/student.txt
Added the student.francistuttle.edu domain to the repository.
=> Added Francis Tuttle Technology Center

lib/domains/mx/edu/tecdesoftware.txt
Instituto Tecnológico de Software
Tecnológico de Software
Official website URL: https://tecdesoftware.edu.mx/
Software Development Course: https://tecdesoftware.edu.mx/desarrollo-de-software-y-negocios-digitales/
=> Added Tecnologico de Software

lib/domains/edu/cinec/student.txt
=> Add student.txt

lib/domains/edu/esade.txt
To whom it may concert, 
I would like my university to be added here. 
Please check out their website and let me know in case of any question:
[https://www.esade.edu/](https://www.esade.edu/)
Thank you,
Cheers
=> Added Esade Business School

lib/domains/edu/waynecc.txt
[Here is the page](https://www.waynecc.edu/programs/ai/) for the AI Engineer program at Wayne Community College. Thank you for your time :]
=> Add Wayne Community College

lib/domains/edu/kish.txt
=> Add Kishwaukee College

lib/domains/edu/sf/cougars.txt
=> Add University of Saint Francis

lib/domains/edu/avc/students.txt
=> Add Antelope Valley College

lib/domains/in/res/ipr.txt
Website: [https://www.ipr.res.in/](https://www.ipr.res.in/)
Other Names: IPR
Description: It is a research institute which predominantly work in the field of plasma physics.
=> Add Institute for Plasma Research

lib/domains/ro/itpbucuresti.txt
Website of the institute: www.itpbucuresti.ro
=> Add Petecostal Theological Institute, Bucharest

lib/domains/kr/ac/kgu.txt
kgu.ac.kr is university of kyonggi domain THX
=> university of kyonggi domain

lib/domains/hu/bme/emk.txt, lib/domains/hu/bme/fmt.txt
Faculty and department subdomains used by the staff.
=> Add fmt and emk subdomains

lib/domains/edu/gvltec/my.txt
Please add the @my.gvltec.edu domain.
=> Add Greenville Technical College (SC USA) Faculty and Students

lib/domains/edu/turing.txt
Add [https://turing.edu/](https://turing.edu/)
=> add Turing School of Software and Design

lib/domains/edu/rknec.txt
Added the university email domain For my university
=> Adding the university email domain for the jet brains free student access 

lib/domains/edu/mga.txt
Adding Middle Georgia State University to the List of Schools.
Link to the schools website: https://www.mga.edu/
=> Add Middle Georgia State University to list of schools.

lib/domains/uk/org/jkhs.txt
=> Adding John Kyrle High School domain

lib/domains/de/mvl-gym.txt
=> Create mvl-gym txt

lib/domains/kr/ac/yc/st.txt
=> Add st.yc.ac.kr (Yonam Institute of Technology)

lib/domains/uk/co/highstorrs-mlt.txt
The school website: [https://highstorrs.co.uk/](url)
=> Added High Storrs School

lib/domains/com/pristineschool.txt
new file:   lib/domains/com/pristineschool.txt
Website: https://pristineschool.com
To add Pristine Private School of Dubai to swot
=>  Changes to be committed:

lib/domains/np/edu/premier.txt
Premier International IB Continuum School
=> premier.txt

lib/domains/edu/interbayamon.txt
Colleges official website: https://bayamon.inter.edu/
Information and Technology programs at Inter Bayamon: https://www.inter.edu/course/informatica-y-tecnologia/
=> added txt file with college name

lib/domains/uk/ac/crawley.txt
=> Added @stu.crawley.ac.uk

lib/domains/mx/edu/utna.txt
Added UTNA to the list of domains for whitelisting the use of JetBrains products for students and teachers.
=> UTNA institution added to the list of domains

lib/domains/np/edu/pusat.txt
Purbanchal University School of Science and Technology (PUSAT) was established in 1994 under the Purbanchal University Act, 2050 (1994). College runs different programs like BCA, BIT, PGDCA, MCA and MIT.
=> Added PU School of Science and Technology

lib/domains/uk/org/mybest.txt, mybest.txt
Added my school as a registered email
=> Adding Samuel Whitbread as a registered domain

lib/domains/de/bbssoltau.txt, lib/domains/eu/bbssoltau.txt
Hey there, I would like to add my vocational school to the list of schools.
Note: The school uses the bbssoltau.eu domain for students and bbssoltau.de for teachers and management. 
Website: https://bbssoltau.de
Imprint: https://www.bbssoltau.de/impressum
IT Classes (3 year training): https://www.bbssoltau.de/bildungsangebote/berufsfelder-1/it-informatik-1
Commits can be squashed if necessary
=> Added Berufsbildende Schulen Soltau

lib/domains/id/ac/sari-mutiara.txt
Add new domain sari-mutiara.ac.id
=> Add new domain sari-mutiara.ac.id

file/lib/domains/edu/maryville/live.txt, lib/domains/edu/maryville/live.txt
=> Add files via upload - My school

lib/domains/edu/ncuindia.txt
University official website - https://www.ncuindia.edu/
=> Added The NorthCap University

lib/domains/edu/pstcc.txt
Pellissippi State Community College
=> Add pstcc edu domain

lib/domains/edu/utahtech.txt, lib/domains/utahtech.txt
[utahtech.txt](https://github.com/user-attachments/files/16802367/utahtech.txt)
=> Utah Tech University

lib/domains/in/rbunagpur.txt
Pull request for adding my  university's domain i.e rbunagpur.in
=> a Pull request for adding my university's domain

lib/domains/edu/endicott/mail.txt
(1) the university official website URL, if it is different from the domain you are submitting:
[https://www.endicott.edu/](https://www.endicott.edu/)
(2) a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university:
[https://www.endicott.edu/academics/schools/science-technology/computer-science-program](https://www.endicott.edu/academics/schools/science-technology/computer-science-program)
(3) a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students:
Please see the second screenshot on this page:
[https://endicott.freshservice.com/support/solutions/articles/10000075813](https://endicott.freshservice. …
=> Create entry for Endicott College

lib/domains/edu/hvcc.txt
HVCC Website
https://www.hvcc.edu/
CISS 110 course description where we use IntelliJ IDEA and sections of this course offered Fall 2024.
https://hvcc.search.collegescheduler.com/courses/U2VhcmNoQ291cnNlOmh2Y2M6TWpBeU5URXdPa05KVTFNNk1URXc=
=> Add Hudson Valley Community College to domains

lib/domains/id/ac/asia/edu.txt
Add Intitut Teknologi dan Bisnis Asia Malang to repository
=> Intitut Teknologi dan Bisnis Asia Malang

lib/domains/bj/esgis.txt
[ESGIS Bénin](https://www.esgis.bj/)
=> Add ESGIS Bénin domain

lib/domains/ph/edu/sti/legazpi.txt
=> Legazpi.txt

lib/domains/edu/bonaventure.txt
School Website: https://www.sbu.edu
School email: gorenbb22@bonavemture.edu
=> Add St. Bonaventure University domain

lib/domains/edu/mvnu/mail.txt
Adds Mount Vernon Nazarene University. Emails like: user@mail.mvnu.edu
=> Added MVNU file

lib/domains/edu/usv.txt
=> Adds usv to the email list

lib/domains/tr/k12/tedistanbul.txt
https://www.tedistanbul.k12.tr    
Ted Istanbul College is a foundation school providing education in Turkey
=> Ted Istanbul College added

lib/domains/edu/stcc/student.txt
=> Add Springfield Technical Community College

lib/domains/edu/ma/westfield.txt
Adding westfield state university
=> Add westfield state university

lib/domains/edu/massasoit.txt
These attachments provide:
1. Official website of Massasoit Community College:
https://massasoit.edu/
2. Proof of Computer Science program (justification for needing JetBrains tools):
https://massasoit.edu/academics/department/computer-science
3. Proof of domain usage:
See the attached screenshot showing official communication from the @massasoit.edu domain.
=> Add Massasoit Community College to swot

lib/domains/net/ccsd15.txt
Added school in Palatine township to allow student licenses for JetBrains IDEs
=> Added ccsd 15 schools

lib/domains/se/futuregames/edu.txt
I don't know why it's not in there?
=> Adding futuregames to the license

lib/domains/pk/edu/fmhcmd.txt
Added Fatima Memorial College of Medicine and Dentistry, Pakistan: fmhcmd.edu.pk
Specifically for bioinformatics and LLM tuning based upon patient database
The official domain for College is https://fmhcmd.edu.pk
=> Added University from Pakistan

lib/domains/edu/maryville.txt
https://www.maryville.edu/
- [Computer Science](https://catalog.maryville.edu/content.php?filter%5B27%5D=COSC&filter%5B29%5D=&filter%5Bkeyword%5D=&filter%5B32%5D=1&filter%5Bcpage%5D=1&cur_cat_oid=23&expand=&navoid=2024&search_database=Filter#acalog_template_course_filter)
- [Web and Game Design](https://catalog.maryville.edu/content.php?filter%5B27%5D=ADIN&filter%5B29%5D=&filter%5Bkeyword%5D=&filter%5B32%5D=1&filter%5Bcpage%5D=1&cur_cat_oid=23&expand=&navoid=2024&search_database=Filter#acalog_template_course_filter)
Recognized [here](https://community.maryville.edu/s/article/What-is-my-Maryville-University-email-address)
=> Add Maryville University to the list of domains

lib/domains/pk/edu/nsu.txt
Please add NSU in domains.
Official Website: [NSU](https://nsu.edu.pk/)
=> Add National Skills University, Islamabad (NSU) in domains

lib/domains/pl/ekonomikzamosc.txt
Added my school's (Ekonomik Zamość) domain
=> Added Ekonomik Zamość

lib/domains/au/edu/wa/wesley.txt
[wesley.wa.edu.au](https://wesley.wa.edu.au)
=> Add Wesley College

lib/domains/id/ac/cakrawala.txt
Added support for cakrawala university students
=> feat: added cakrawala university

lib/domains/ar/uba.txt
Added support for Universidad de Buenos Aires students
=> Add Universidad de Buenos Aires Domain

lib/domains/in/ac/sreedattha.txt
Pleasea add Sree Dattha Institute of Engineering and Science college
College WebSite: http://sreedattha.ac.in/sdes/
=> Pleasea add Sree Dattha Institute of Engineering and Science college

lib/domains/au/edu/vic/elwood.txt
website:https://elwood.vic.edu.au/
We have applied computing classes, so we need to use brillian tools from jetBrians. Thanks!
=> requist for adding Elwood College

lib/domains/org/cottonwoodclassical.txt
School site:
https://www.cottonwoodclassical.org/
=> Adding Cottonwood Classical

lib/domains/it/edu/vonneumann.txt
Added file for vonneumann.edu.it domain
=> Add IISS J. Von Neumann

lib/domains/edu/citadel/student.txt
{The Citadel, Military College of South Carolina}
{https://www.citadel.edu/}
Email Users
{*@student.citadel.edu, *@citadel.edu, *@nation.citadel.edu}
[x] Students
[x] Academic/Teaching Staff
[] Other/Support Staff
[] Alumni
[]  Post-graduate research
[x]  Graduate School
[x]  College (University) or Undergraduate School or equivalent
[]  Community College or equivalent
[]  High School or equivalent
[]  Elementary School or equivalent
=> Add The Citadel to approved emails

lib/domains/au/edu/vic/ivanhoegirls.txt
Adding Ivanhoe Girls' Grammar School to the education domains
=> Add Ivanhoe Girls

lib/domains/in/ac/nitdgp.txt
Added National Institute of Technology, Durgapur to the domain list
=> Added National Institute of Technology, Durgapur 

lib/domains/edu/iccms.txt
Need to add my College to the Accepted list to Qualify for a free license
=> Adding the Itawamba Community College

lib/domains/edu/fitchburgstate.txt
https://www.fitchburgstate.edu/academics/programs/game-design-bs
https://www.fitchburgstate.edu/academics/faculty-profiles/xiaoying-meng
=> fitchburgstate

lib/domains/pl/radom/kochanowski.txt
There is also second schools webiste: kochanowski.iq.pl, but the one that i am submiting is used in e-mails.
=> Add kochanowski

lib/domains/com/shrikrishnacollege.txt, lib/domains/in/ac/krishnacollege.txt
http://www.shrikrishnacollege.com/
http://www.shrikrishnacollege.com/Programme.html
http://www.shrikrishnacollege.com/DELED2023/Minority%20Registration.html
University is having 2 domains, 1 for email purposes and 1 for official website. Added both in this PR.
=> Added krishna College

lib/domains/pl/edu/davinci.txt
Please add our school to the servers so we can ask for licenses.
=> Add davinci.edu.pl

lib/domains/edu/cfcc/mail.txt
=> Cape Fear Community College

lib/domains/edu/usuniversity.txt
Added the educational institution file to the list.
One of the courses related to this
https://www.usuniversity.edu/degrees/bachelor-of-science-in-information-technology
=> Added educational institution

lib/domains/edu/camdencc/students.txt
Add Camden County College (@camdencc.edu)
https://www.camdencc.edu/program/computer-science-2/
Thank you.
=> Add Camden County College

lib/domains/kr/ac/yeonsung.txt
=> Yeonsung University

lib/domains/edu/bmcc.txt
=> Add Bay Mills Community College

lib/domains/edu/endicott.txt
Endicott College: [https://www.endicott.edu/academics/schools/science-technology/computer-science-program](https://www.endicott.edu/academics/schools/science-technology/computer-science-program)
Student emails are of the form student@mail.endicott.edu, and have previously been added. This change adds faculty/staff who have @endicott.edu addresses
Thank you!
=> Add Endicott College faculty/staff

lib/domains/edu/richmond.txt
Official site: www.richmond.edu
Computer Science Major: https://cs.richmond.edu/
Reference to University email domain: https://spidertechnet.richmond.edu/TDClient/1955/Portal/Requests/ServiceDet?ID=35411
=> University of Richmond

lib/domains/kr/ac/seoultech.txt
Add Seoul National University of Science and Technology
https://www.seoultech.ac.kr/index.jsp
https://en.seoultech.ac.kr
=> Add Seoul National University of Science and Technology

lib/domains/org/susdgapps.txt
Desert Mountain High School website https://desertmountain.susd.org/
=> Desert Mountain High School

CONTRIBUTING.md
See #23522 
Updates `CONTRIBUTING.md` to prevent future PRs
=> Adds liberty.edu to stoplist documentation

lib/domains/in/ac/iiitl.txt, swot/lib/domains/in/ac/iiitl.txt
- Institute Name: **`Indian Institute of Information Technology, Lucknow`**
- Abbreviation: **`IIITL`**
- Website: [`iiitl.ac.in`](iiitl.ac.in)
- Undergraduate Program: [`Computer Science`](https://iiitl.ac.in/index.php/b-tech-in-cs-2/)
=> Add Indian Institute of Information Technology, Lucknow

lib/domains/ca/sk/rbe.txt
Allan Blakeney Adult Campus 
https://adultcampus.rbe.sk.ca/
=> Add Allan Blakeney Adult Campus

file/lib/domains/us/nc/k12/ucps/student.txt, lib/domains/us/nc/k12/ucps/student.txt
Adding my school to the domain list.
=> Adding Marvin Ridge Middle School from North Carolina, USA

lib/domains/edu/springfieldcollege.txt
https://springfield.edu/programs/computer-and-information-sciences
=> Springfield College Pull Request

lib/domains/ma/ac/fsr.txt
University official website URL:http://www.fsr.ac.ma
URL of IT related course is offered by the university: http://www.fsr.ac.ma/content/informatique-et-telecommunications
=> Pull request for fsr.ac.ma

lib/domains/fi/sallacampus.txt
official website URL: https://peda.net/salla/sallan-lukio
official website where a long-term (>1 year) IT related course is offered: https://peda.net/salla/sallan-lukio
=> sallacampus.fi

lib/domains/org/hopeccs.txt
add Hope Chinese Charter School
=> add Hope Chinese Charter School

lib/domains/uk/sch/sheffield/ecgbert.txt
Hi, just wanting to add my school here so I can use the student version of CLion.
Thanks
=> add King Ecgbert School

lib/domains/in/ac/iimkashipur.txt
Official site: https://www.iimkashipur.ac.in/
Computer Science/Information Technology Course: https://www.iimkashipur.ac.in/faculty/academic-areas/information-technology-systems
=> Adds IIM Kashipur

lib/domains/in/ac/iimranchi.txt
Adding Indian Institute of Management Ranchi
=> fix: add iimranchi domain

file/lib/domains/uk/co/morehouseschool.txt, lib/domains/uk/co/morehouseschool.txt
more house school is a school that has courses in computer science this is its main website https://www.morehouseschool.co.uk
the email domain is @morehouseschool.co.uk
=> add more house school

lib/domains/fr/notredamevalenciennes.txt
Add notredamevalenciennes to the fr domains.
THX
=> Add notredamevalenciennes

lib/domains/edu/git/students.txt
This PR is to reflect that and to provide access for students of GIT Belagavi .
=> Added domain for Gogte Institute of Technology

lib/domains/com/imsnoida.txt
I would like to request the addition of "IMS Noida" to the GitHub Student Developer Pack. Our institution provides students with a formal educational program, and many students could benefit from the tools and resources offered in the GitHub Education program. Please review the necessary information and documents attached to help facilitate the verification of our school.
Thank you for considering this request.
=> Request to Add "IMS Noida" to GitHub Student Developer Pack

lib/domains/eu/unint.txt
Dear Team,
below the information requested:
- The university official website URL: https://www.unint.eu/
- A URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: https://my.unint.eu/insegnamenti-e-programmi-2022/2023-13fde-
- A URL of a page showing that the university recognizes the domain which you are submitting as an official email domain: https://www.unint.eu/contatti/ (please collpase the contacts, where the domain @unint.eu is visible)
Please not that:
- @unint.eu is the email of Professors
- @studenti.unint.eu is the email of Students
Thank you in advance, I would really appreciate your help, 
Best Regards
=> Add UNINT university (UNINT Università degli Studi Internazionali di Roma)

lib/domains/com/onmicrosoft/zs10zabrze.txt
added Technikum Nr 7 Zabrze im. prof. Janusza Groszkowskiego w Zabrzu
=> added  lib/domains/com/onmicrosoft/zs10zabrze.txt

lib/domains/365/bc/ac/kr/Buchoen.txt, lib/domains/kr/ac/bc/365.txt
=> add Bucheon University

lib/domains/fi/karstula/student.txt
official website URL: https://peda.net/karstula/lukio
official website where a long-term (>1 year) IT related course is offered: https://peda.net/karstula/lukio/di-it-opinnot
=> student.karstula.fi

lib/domains/fi/karstula/edu.txt
official website URL: https://peda.net/karstula/lukio
official website where a long-term (>1 year) IT related course is offered: https://peda.net/karstula/lukio/di-it-opinnot
=> edu.karstula.fi

lib/domains/ua/net/ktbp.txt
Added support for Professional College of Technologies, Business and Law of Lesya Ukrainka Volyn National University.
official website - https://ktbp.lutsk.ua/ua
IT related course - https://ktbp.lutsk.ua/ua/entrant-nformation/detail/specialnosti/informaciyni-sistemi-i-tehnologiyi_515_6547?menu=4
=> Added domain for KTBP

lib/domains/edu/southalabama/health.txt
for email addresses like xxx@health.southalabama.edu
=> Added usouthal health

lib/domains/edu/mcc.txt
Computer Information Systems, A.A.S.: https://catalog.mcc.edu/preview_program.php?catoid=17&poid=2066&returnto=518
student domain proof: https://www.mcc.edu/its/password-information.shtml
=> Add Mott Community College

lib/domains/edu/pisd.txt
https://www.pisd.edu/
Plano ISD District Page
https://www.pisd.edu/pshs
Webpage for Plano Senior - one of the 3 Senior Highs
https://www.pisd.edu//Page/22082
Computer Science Courses offered by Plano ISD
=> Add Plano ISD to edu

lib/domains/edu/ucc.txt
- https://en.wikipedia.org/wiki/Union_College_(New_Jersey)
- https://www.ucc.edu/
=> Add Union College of Union County, NJ

lib/domains/edu/century.txt
School website: https://www.century.edu/
CSCI Degree: https://catalog.century.edu/preview_program.php?catoid=18&poid=5481&_gl=1*14q15uh*_gcl_au*MTMzNTMyNzg4OS4xNzI1NjY1NjEz*_ga*NzQ5NTAwMTkyLjE3MTM3MzQwMzU.*_ga_RN2ZB0LQV2*MTcyNjkzNDk2Ny41NC4xLjE3MjY5MzQ5OTUuMC4wLjA.
=> added school located in minnesota USA

lib/domains/kr/ac/osan/portal.txt
OSAN UNIVERSITY FROM SOUTH KOREA
https://www.osan.ac.kr/?menuno=298
=> Add domain for Osan University From South Korea

lib/domains/edu/unco.txt
University name and domain verification for student Jetbrains account
=> Added unco.txt for University of Northern Colorado domain

lib/domains/edu/simons-rock.txt
=> Added Bard College at Simon's Rock to list

lib/domains/com/dsbarcelona.txt
Deutsche Schule Barcelona
German School of Barcelona
IT related course (Informatik, for 1 year in years 5, 9 and 10): https://dsbarcelona.com/oberschule/facher-seki/
=> Add dsbarcelona.com

lib/domains/id/ac/umku.txt, lib/domains/id/ac/umku/std.txt, lib/domains/id/ac/umkudus.txt
Fixing Domain Requirements based on reply : https://github.com/JetBrains/swot/pull/23780#issuecomment-2367765119
=> Add universitas muhammadiyah kudus

lib/domains/sv/edu/agape/esfe.txt
adding file of Escuela Superior Franciscana Especializada/Agape
=> adding file of Escuela Superior Franciscana Especializada/Agape

lib/domains/ph/edu/uc.txt
=> Adding my university

lib/domains/mg/insi.txt
INSI: Institut National Supérieur d'Informatique
Madagascar - Antananarivo
=> Add INSI university

lib/domains/edu/ccga/student.txt
Adding College of Coastal Georgia as a domain - `student.ccga.edu`
https://www.ccga.edu/academics/artsandsciences/datascience/
=> Add College of Coastal Georgia domain

lib/domains/edu/mvnu.txt
email domains mvnu.edu (faculty/staff) and mail.mvnu.edu (student) should be recognized.
=> Add MVNU to domains

lib/domains/hu/eszi.txt
Request to add Energetikai Technikum és Kollégium Paks as a school to JetBrains supported institutions
=> Adding ESZI as an IT school

lib/domains/info/eci-liege.txt
URL: https://eci-liege.info/
You can see all courses here: https://www.eci-liege.info/sections/ including Bachelor's degree.
https://www.eci-liege.info/sections/technicien-en-informatique/
https://www.eci-liege.info/sections/bachelier-en-informatique-orientation-developpement-dapplication
[SECTION-Bachelier-en-informatique-orientation-developpement-d-applications.pdf](https://github.com/user-attachments/files/17076110/SECTION-Bachelier-en-informatique-orientation-developpement-d-applications.pdf)
[SECTION-Technicien-en-informatique.pdf](https://github.com/user-attachments/files/17076111/SECTION-Technicien-en-informatique.pdf)
You can see here https://www.eci-liege.info/notre-equipe/ that the mail i use is the same as the Teacher's/Director one.
Contact me if you need more informations.
=> Add ECI - École de commerce et d'informatique

lib/domains/ee/perg.txt
=> Add Pelgulinna State Upper Secondary School

lib/domains/br/com/uniceug/aluno.txt
University official URL: https://www.uniceug.com.br/
Long-term IT courses:
- https://www.uniceug.com.br/ensino/graduacao/tradicionais/ciencia_computacao.asp
- https://www.uniceug.com.br/ensino/graduacao/tecnologicos/analise_desenvolvimento_sistemas.asp
After-login page showing domain being utilized as my school e-mail: https://prnt.sc/wK2npMzhN6V_
=> Added UNICEUG university

lib/domains/edu/hbs.txt
=> Create hbs.txt,add Harvard Bussiness School

lib/domains/es/alumnatflorida.txt
Add new students email Florida Universitaria
- https://www.floridauniversitaria.es/
- https://www.floridauniversitaria.es/titulacion/desarrollo-de-aplicaciones-multiplataforma/
- https://www.floridauniversitaria.es/titulacion/desarrollo-de-aplicaciones-web/
=> Add new students email Florida Universitaria

lib/domains/org/teiacoltec.txt
UFMG website: https://ufmg.br/
COLTEC website: http://www.coltec.ufmg.br/coltec-ufmg/
Section of the COLTEC website about the Systems Development course: http://www.coltec.ufmg.br/coltec-ufmg/?page_id=65
=> Adding Colégio Técnico da UFMG - COLTEC

lib/domains/be/kjhasselt/student.txt
This is a School in Hasselt (Belgium)
https://www.kjhasselt.be/
=> Scholen Kinsheid Jesu

lib/domains/uk/ac/glasgowkelvin.txt
Hello please add glasgow kelvin college to your domain list
=> Consider adding this college

lib/domains/ro/cnmvturda.txt
add Colegiul National "Mihai Viteazul" to the list of allowed institutions
=> cnmvturda.txt

lib/domains/pe/edu/lisoft.txt
website: [https://lisoft.edu.pe](https://lisoft.edu.pe)
Lima International School of Tomorrow
=> Add lisoft.edu.pe

lib/domains/edu/apeejay.txt, lib/domains/edu/apeejay/learn.txt
Url for school is https://apeejay.edu/
The various branches/districts of the school are https://apeejay.edu/all-schools/
=> Request for adding Apeejay School

lib/domains/edu/atlantisuniversity.txt
[University Website](https://atlantisuniversity.edu/)
[Long term course page](https://atlantisuniversity.edu/program/bachelor-of-science-in-information-technology/)
Here are few screenshots that serve as proof that univesity recognizes this domain as official email domain for enrolled students(both sites require login with university email domain)
[Atlantis University Online Campus](https://onlinecampus.atlantisuniversity.edu/)
[Atlantis Univesity Student Portal](https://services.atlantisuniversity.edu/)
=> Added atlantisuniversity.txt

lib/domains/pl/edu/lo-ozorkow.txt
The school's website is [lo-ozorkow.pl](https://lo-ozorkow.pl) 
The school offers [cybersecurity classes.](https://lo-ozorkow.pl/klasa-cyberbezpieczenstwa)
=> Add I Lo ozorkow

lib/domains/sa/sek/student.txt
SEK - high school in Saudi Arabia
Official web page: https://sek.sa/
=> Adding SEK

lib/domains/edu/binus.txt
Add domain university is binus.edu
=> Add domain university is binus.edu

lib/domains/edu/ccri.txt
=> Add Community College of Rhode Island

lib/domains/edu/na.txt
Added "North American University (NAU)" to the list. 
website: https://www.na.edu/
=> Added "North American University" (NAU)

lib/domains/edu/rajagiri.txt
Name: Rajagiri College of Social Sciences
Official Website : [Rajagiri.edu](https://rajagiri.edu/)
=> Add rajagiri.edu domain

lib/domains/edu/uofn.txt
*Official website*: uofn.edu
*URL of all Technology courses*: https://uofn.edu/colleges/science-technology#courses
*Complementary Info*: Heroku feature a case study of a project implemented by UofN Staff and some students: https://www.heroku.com/customers/uofn
=> Adding uofn.txt file (uofn.edu)

lib/domains/it/edu/iispiscopo.txt
Website: https://www.iispiscopo.edu.it/
I.I.S. Don Geremia Piscopo
=> Add I.I.S. Don Geremia Piscopo - Italy

lib/domains/org/fallriverschools.txt
=> chore: Add Fall River Public Schools

lib/domains/br/org/educadventista.txt
Url: https://unasp.br/quem-somos/,  I hope it’s correct now. Thank you very much!
=> add file educadventista

lib/domains/hu/bme/gpk.txt
Please, add @gpk.bme.hu
We are the Faculty of Mechanical Engineering at the hungarian Budapest University of Technology and Economics (BME).
Homepage HU: https://gpk.bme.hu
Homepage EN: https://gpk.bme.hu/en
=> Please, add @gpk.bme.hu

lib/domains/mx/edu/cobatab.txt
https://cobatab.edu.mx/
https://cobatab.edu.mx/servdocentes/ProgEstudio/Desarrollo%20Software.pdf
=> [ADD] Cobatab

lib/domains/edu/unu/biolac.txt, lib/domains/edu/unu/cpr.txt, lib/domains/edu/unu/cris.txt, lib/domains/edu/unu/egov.txt, lib/domains/edu/unu/ehs.txt, lib/domains/edu/unu/flores.txt, lib/domains/edu/unu/ias.txt, lib/domains/edu/unu/iigh.txt, lib/domains/edu/unu/inra.txt, lib/domains/edu/unu/inweh.txt, lib/domains/edu/unu/macau.txt, lib/domains/edu/unu/merit.txt, lib/domains/edu/unu/vie.txt, lib/domains/edu/unu/wider.txt
The United Nations University is a global think tank and tertiary education institution headquartered in Japan with branches around the globe.
=> Adding all branches of the United Nations University

lib/domains/com/b-zvi.txt
Hi,
This High School is located in Israel. Please find herein the school's web page for its 3 year Computer sciences program (in Hebrew) https://www.b-zvi.com/computers
Also attached is a PDF printout (redacted password) from the school assigning this email hila.s0812@b-zvi.com to me:
[_Gmail - Fwd_ תיכון ע_ש הנשיא י.בן צבי קרית אונו - הודעה בדבר תהליך רישום של הילה.pdf](https://github.com/user-attachments/files/17167006/_Gmail.-.Fwd_._.-.pdf)
=> Request to add Ben Zvi High School

lib/domains/nl/jvo.txt
Please add my college Johan van Oldenbarnevelt (jvo.nl)
=> added Johan van Oldenbarnevelt (JVO)

lib/domains/it/liceocattaneotorino.txt
hi can you add my school please? if you need help contact abbagaeta@gmail.com and if you add the school contact the same email if possible. thanks in advance
=> add-school 

lib/domains/org/headroyce.txt
School web site: https://www.headroyce.org/
Curriculum: https://resources.finalsite.net/images/v1723153724/headroyce/yirw4b1imnfzxkog0o7t/us-curriculum-offerings.pdf
=> added head-royce school domain

lib/domains/hu/edu/zsoldos.txt
=> Add zsoldos.txt

lib/domains/no/mrfylke.txt
Adding our school to enable student and teacher requests for JetBrains' tools. 
The school is a member of the intranet in Møre og Romsdal fylkeskommune.  
Location: Molde, Møre og Romsdal, Norway
=> Romsdal high school

lib/domains/es/santamariadelosangeles.txt
Add new college: **C.D.P. Santa María De Los Ángeles**, Pl. Pío XII, 2, Cruz de Humilladero, 29007 Málaga (España). For more info about us visit [https://santamariadelosangeles.es/](https://santamariadelosangeles.es/)
=> Add new file: lib/domains/es/santamariadelosangeles.txt

lib/domains/kr/ac/bufs.txt
Region
- South Korea 
University name
- Busan University of Foreign Studies
=> Added Busan University of Foreign Studies

lib/domains/edu/umw/mail.txt
The university's official website URL: https://www.umw.edu/
[A URL of a page on the official website where a long-term (>1 year) IT-related course is offered](https://cas.umw.edu/computerscience/requirements/cs-major/)
[A URL or proof showing that the university recognizes mail.umw.edu as an official email domain for enrolled students](https://technology.umw.edu/hss/ms-office/)
=> Add University of Mary Washington

lib/domains/eg/edu/eia.txt
university domain : eia.edu.eg
=> adding my university The Egyptian Higher Institute of Alexandria Academy

lib/domains/ar/org/educacionadventista.txt
Details about my workplace:
- I work in the [ISAM Institute](https://isam.edu.ar/) in Misiones, Argentina.
- We teach PHP in the sophomore year of our carrer called [Analisis de Sistemas](https://isam.edu.ar/courses/analista-sistemas/)
- As an institute, we depend on the [Adventist Education Network](https://www.educacionadventista.com/)
- The domain of our institutional email is educacionadventista.org.ar
=> Request for adding Educacion Adventista

lib/domains/education/ueb.txt
This is an accredited Romanian unversity, offering multiple courses: https://www.ueb.ro/
The courses are Ecology, Financial Management, Communication & PR, Legal, Psychology etc.
Sample email is firstname-middlename.lastname.fepm@ueb.education (not sure if it's relevant)
=> Enrolling Ecological university from Bucharest 

lib/domains/org/gncasc.txt
=> Add domain name gncasc.org

lib/domains/com/eep-igroup.txt
The file “eep-igruop.txt” has been added for the eep-igruop institute, corresponding to the School of Professional Studies. 
Sample email to be accepted : my_name@eep-igroup.com
Thank you very much.
=> ADDED FILES FOR A NEW INSTITUTE

lib/domains/edu/dayanandasagar.txt
**Website:** https://dayanandasagar.edu/
**Email Format:** `<username>@dayanandasagar.edu`
=> Add "Dayananda Sagar University"

lib/domains/edu/spuvvn.txt
Added my university domain.
**University website:** https://www.spuvvn.edu/
**IT related course:** https://www.spuvvn.edu/academics/departments/computer-science/academic-programmes/
**Contact us:**: https://www.spuvvn.edu/contacts/
=> Added spuvvn.txt

lib/domains/uk/co/lordswoodtrust.txt
as my daughters email domain is lordswoodtrust.co.uk, adding this to your school list
=> adding lordswoodtrust.co.uk to the school list

lib/domains/edu/lowercolumbia.txt
[College Website:](https://lowercolumbia.edu/)
[URL to computer science course:](https://lowercolumbia.edu/publications/catalog/programs/STEM-AST-Computer-Science/
)
Screenshot of the college using the lowercolumbia.edu domain at the bottom of the page:
=> Adding my College to the list

lib/domains/edu/wccnet.txt
- The university official website URL: [Official Website](https://www.wccnet.edu/)
- A URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: [Associate of Science: Information Systems: Programming in C++](https://catalog.wccnet.edu/current/programs/asispc.php)
- A URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.: [Contact Page](https://www.wccnet.edu/contact/)
=> Add Washtenaw Community College - wccnet.edu

lib/domains/kg/krsu.txt
Our university has a new domain, please add it.
=> add new KRSU domain

lib/domains/nu/adelfors.txt
=> Add Ädelfors Folkhögskola

lib/domains/uk/ac/tedi-london.txt
=> TEDI-London

lib/domains/com/vcertk.txt
Adding  file for the vaish college of engineering .
=> Adding file for vaish college of engineering

lib/domains/pl/szczecin/lo14.txt
=> XIV LO w Szczecinie

lib/domains/vn/edu/ueb.txt
University of Economics and Business - Vietnam National University
=> add University UEB

lib/domains/it/itsumbria.txt
Added the genereted file for my school.
=> Added genereted file for my school

lib/domains/br/edu/faculdadepm.txt
https://www.faculdadepm.edu.br/
=> adição da faculdade da polícia militar ao repositório

lib/domains/vn/edu/dthu.txt
Dong Thap University - Vietnam
[https://en.dthu.edu.vn](https://en.dthu.edu.vn/ )
=> Add Dong Thap University

lib/domains/edu/easternct/my.txt
=> Eastern CT State University Domain

lib/domains/edu/raritanval.txt
Raritan Valley Community College
North Branch, NJ
=> Raritan Valley Community College

lib/domains/edu/oregoncoast.txt
Pull request to add Oregon Coast Community College to list of domains.
=> new pull request 

lib/domains/se/lidingo/skola.txt
Official website: https://lidingo.se/toppmeny/barnutbildning/grundskola/varakommunalagrundskolor/kallangensskola.4.11f7a65612084cba4e980007628.html
The email used for students is
name@skola.lidingo.se
Proof: https://imgur.com/a/Mtep2AL
=> Upload Källängens skola

lib/domains/edu/art.txt
student emails for Academy of Art University
https://www.academyart.edu/
phone: +1 415-274-2222
=> create domain art.edu for Academy of Art University student emails

lib/domains/edu/ctstate.txt
Gateway Community College
https://gatewayct.edu/
https://catalog.ctstate.edu/preview_program.php?catoid=19&poid=7701&returnto=2075 https://ctstate.edu/locations/gateway
Cheers!
=> Adding ctstate.edu as email domain

lib/domains/fr/st-nicolas.txt
ST-NICOLAS.fr , ST-NICOLAS.org
=> ST-NICOLAS ( PARIS )

lib/domains/au/edu/ciom.txt
- University Website:  [Canterbury Institute of Management](https://ciom.edu.au)
- An example of 2 years ICT course: [Master of Information & Communications Technology](https://ciom.edu.au/master-of-information-and-communication-technology/)
- Commonwealth Register of Institutions and Courses for Overseas Students: [CRICOS Provider 03809A](https://cricos.education.gov.au/Institution/InstitutionDetails.aspx?ProviderCode=03809A)
Thank you team JetBrains! 
Ayesh Jayasekara
=> Add Canterbury Institute of Management

lib/domains/com/letumongolia.txt
Added LETU Mongolia University / American University of Mongolia
=> Added LETU Mongolia University

lib/domains/sr/natin/student.txt
Hi there 
I added my school domain. The country of origin is Suriname. The vocational school has different types of streams and IT is one of them.
If you would like to know more about it feel free to contact me.
=> added NATIN domain

lib/domains/net/tomballschools.txt, tomballschools.txt
=> Grand Lakes Junior High

lib/domains/br/edu/uniateneu/professor.txt
"Adição do arquivo gerado para solicitação de licença"
=> Licença professor Uniateneu

lib/domains/mx/edu/tecmm/tequila.txt, tecnologico_superior_de_jalisco_tequila
This pull request adds Tecnológico Superior de Jalisco Tequila to the list of recognized educational institutions.
Institution details:
- Name: Tecnológico Superior de Jalisco Tequila
- English Name: Higher Technological Institute of Jalisco Tequila
- Location: Tequila, Jalisco, Mexico
- Website: [Add official website if available]
I confirm that this is a legitimate educational institution and the information provided is accurate.
=> Add Tecnológico Superior de Jalisco Tequila

lib/domains/mx/edu/uttecamac.txt
Add University Universidad Tecnologica de Tecamac, https://uttecamac.edomex.gob.mx this is the official website of the university, but the domain we use is @uttecamac.edu.mx.
=> Add University Universidad Tecnologica de Tecamac

lib/domains/kw/edu/iuk.txt
University official website: https://www.iuk.edu.kw/
Location: [Kuwait, Ardiya](https://maps.app.goo.gl/SNZyUoas2UT3j4hy5)
Proof of the university having an IT major: https://www.iuk.edu.kw/computer-and-cyber-department and https://dev-iuk-website.euwest01.umbraco.io/media/1tcnnztr/computer-science-cyber-security-study-plan.pdf
Note: I have already created pull request for AASU university, which is my university, but IUK is my friend's University
=> lInternational University of Kuwait (IUK)

lib/domains/kr/ac/eumc.txt
added eumc
the website is below.
https://www.eumc.ac.kr/
=> added eumc(Ewha Womans University Medical Center)

lib/domains/edu/uib.txt
This is a local University located in Batam Island, Riau Islands Province, Indonesia
Beware that some part of the website is still in local language ( Indonesia )
Home URL  = https://www.uib.ac.id/en/home-en
URL where IT course is offered = https://www.uib.ac.id/en/information-technology-study-program/
=> Add uib.edu email domain

lib/domains/ua/com/maup.txt, lib/domains/ua/edu/iapm.txt
Added Interregional Academy of Personnel Management
https://maup.com.ua/eng/index.html
=> Interregional Academy of Personnel Management

lib/domains/edu/wscc/email.txt
https://www.wsco.edu/academics/business/cyber-security-investigation/ 
thank you very much in advance
=> Washington State College of Ohio

lib/domains/net/institutodh.txt
Proposes to add the institutodh.net domain to the swot list
URL of the School website https://blogsaverroes.juntadeandalucia.es/institutodh/
=> Add institutodh.net domain

lib/domains/eg/edu/bnu.txt, lib/domains/eg/edu/bnu/cs.txt
URL of the university: https://bnu.edu.eg/
=> Added Benha National University

lib/domains/id/ac/undipa.txt
added Dipa Makassar University. 
Pull Request By Dipanegara Computer Club
#Ooka Pratama
=> add universitas dipa makassar

lib/domains/id/ac/methodist.txt
=> add domains methodist.ac.id

lib/domains/uk/ac/ekcgroup.txt
Main college group landing page to access courses
- https://www.ekcgroup.ac.uk/university-level-courses/
... leading to, for example, A T-Level 2-year course details pages
- https://www.ashfordcollege.ac.uk/study-with-us/school-leavers/t-levels/
- https://www.ashfordcollege.ac.uk/courses/t-level-digital-production-design-and-development-2/
attached screen grab of my contact details at the domain in question
Thanks! -- rich
=> Adding East Kent College Group

lib/domains/kr/ac/yonsei.txt
=> Add Yonsei University

lib/domains/edu/ensign.txt
Ensign College Domain: @ensign.edu
=> Added Ensign College domain

lib/domains/edu/betheluniversity.txt
Official University Website: https://betheluniversity.edu/
IT Related Courses: https://betheluniversity.edu/academics/majors-minors/computer-science/
Domain Ownership Proof: https://www.godaddy.com/whois/results.aspx?itc=dlp_domain_whois&domain=betheluniversity.edu
=> Add betheluniversity.edu

lib/domains/edu/northweststate/students.txt
=> Northwest State Community College

lib/domains/edu/coconino/students.txt
https://catalog.coconino.edu/preview_program.php?catoid=10&poid=582
=> Coconino Community College

lib/domains/edu/qcc.txt
adding quinsigamond community college. qcc.edu, qcc.edu/sites/default/files/2023-11/how_to_access_student_email.pdf, qcc.edu/courses/computer-science-i
=> quinsigamond community college

lib/domains/edu/ndu.txt
Website: ndu.edu
IT Related Program (s) : https://cic.ndu.edu/Academics/MS-in-Strategic-Information-and-Cyberspace-Studies/
=> Add domain: National Defense University

file/lib/domains/edu/uscga.txt, lib/domains/edu/uscga.txt
[uscga.txt](https://github.com/user-attachments/files/17498980/uscga.txt)
=> Educational License Request

lib/domains/edu/salisbury/gulls.txt
Add gulls.salisbury.edu
https://salisbury.edu/
=> Add domain gulls.salisbury.edu

lib/domains/edu/smccme.txt
Add edu domain for Southern Maine Community College
=> Add file for Southern Maine Community College

lib/domains/de/johannes-althusius-gymnasium.txt
Sorry, I didn't see your messages under my last pull-request.
_the school official website URL_
`https://www.jag-bad-berleburg.de/`
_the school street address, including city and country_
`Im Herrengarten 11, 57319 Bad Berleburg, Germany`
_an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course_
`https://www.jag-bad-berleburg.de/attachments/article/1082/Informatik_Vorstellung%202021.pdf`
_a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students._
`https://www.jag-bad-berleburg.de/organisiertesjag/77-schwerpunkt-unterricht/1053-regeln-des-virtuellen-jag `(paragraph 3)
I hope that's good.
=> Added Johannes Althusius Gymnasium (Germany)

lib/domains/uk/sch/coventry/barrshill.txt
Adding my high school
https://www.barrshill.coventry.sch.uk/
Barr’s Hill School
Radford Road
Radford
Coventry
West Midlands
CV1 4BU
=> adding high school barrs hill

lib/domains/id/sch/sman2-brebes.txt
Hello, I apologize in advance for my very poor English.
So, this pull request I added `Brebes State 2 Senior High School` 
You can check the school and location of my school at the following link 
[Google Search](https://www.google.com/search?q=sman+2+brebes)
[Wikipedia](https://id.wikipedia.org/wiki/SMA_Negeri_2_Brebes)
[Data Pokok Kemendikbud](https://dapo.kemdikbud.go.id/sekolah/571144B5D8DD5310DF27)
SMA Negeri 2 Brebes
sman2-brebes.sch.id
=> Add Brebes State 2 Senior High School

lib/domains/be/spectrumstudent.txt
https://www.spectrumcollege.be/
https://www.spectrumcollege.be/studieaanbod-campus-beringen-bovenbouw 3rd grade 5th point can be translated to computer science and communication sciences.
=> Added Spectrumcollege

lib/domains/edu/sarahlawrence.txt
https://www.sarahlawrence.edu/about/#acc-101-statement-of-accreditation-status-sas-and-program-approvals https://www.sarahlawrence.edu/undergraduate/science-mathematics/computer-science/
=> Add Sarah Lawrence College

lib/domains/at/borg-birkfeld.txt
Official Website: [https://www.borgbirkfeld.at/](https://www.borgbirkfeld.at/)
IT Route of Official Website: [https://borgbirkfeld.at/it-nawi/](https://borgbirkfeld.at/it-nawi/)
Proof that school recognizes domain name:
=> BORG Birkfeld

lib/domains/py/edu/usil.txt
Universidad San Ignacio de Loyola – Paraguay
=> Add Universidad San Ignacio de Loyola – Paraguay

lib/domains/edu/solacc/my.txt
Add South Louisiana Community College
https://www.solacc.edu
https://www.solacc.edu/academics/programs-offered/application-software-development/index https://www.solacc.edu/students/technology-resources
=> Add South Louisiana Community College

lib/domains/kr/ac/solbridge/student.txt
1. School Official website: https://www.solbridge.ac.kr/
2. Master of Science Program: http://solbridge.ac.kr/story/Master-of-Science/index.jsp?pagenum=2
3. Guideline for student email: https://my.solbridge.ac.kr/login_only -> https://bit.ly/mysolbridgewelcome
=> Add SolBridge International School of Business domain verification

lib/domains/es/ceacfp/alu.txt
https://www.ceac.es/fp-informatica-comunicaciones
=> Add CEAC.es institute

lib/domains/br/com/femaf.txt, lib/domains/femaf.txt
**Institution website**
https://femaf.com.br/
**Name institution**
Faculdade de Educação Memorial Adelaide Franco - FEMAF
**Email intitution**
hss@femaf.com.br
=> Add Faculdade FEMAF

lib/domains/co/edu/unisanitas.txt
Solicitud de agregar la Fundación Universitaria Unisanitas
=> Añadir unisanitas.txt

lib/domains/org/hdschools.txt
https://www.hdschools.org/en/shanghai/about/profile
=> Add HD Shanghai Bilingual School

lib/domains/de/heinrich-kleyer-schule.txt
https://www.heinrich-kleyer-schule.de/
Kühhornshofweg 27
60320 Frankfurt am Main
Germany
=> Add Heinrich-Kleyer-Schule

lib/domains/id/sch/sman1julok.txt, lib/domains/pl/tarnow/zst.txt
First of all, I'm sorry if you think I'm trying to cheat. You need to pay attention to the domain: sman1julok.sch.id, this is the new domain for our school website, previously we used the domain: smansajulok.sch.id, now it is no longer active, because the domain name no longer exists. active again. Because the name "smansa" was not relevant to the school name, namely "SMAN1", the school then changed its domain name to: sman1julok. sch.id., I hope you can understand my statement. Thank You
=> Add smansajulok.sch.id

lib/domains/in/net/theheritageschool.txt
School Name: The Heritage School
School Website: https://theheritageschool.org/
Mail pattern: [name,id]@theheritageschool.net.in
=> Added The Heritage School

lib/domains/co/edu/gimnasiodelnorte.txt
https://www.gimnasiodelnorte.edu.co/
=> Add Gimnasio del norte

lib/domains/org/theemcoe.txt
[Official Website](https://theemcoe.org)
[Course for Bachelors' in Computer Engineering](https://theemcoe.org/course-degree.php?dept=comp)
=> Add entry for theemcoe.org

lib/domains/edu/clarkstate.txt
https://www.clarkstate.edu/academics/degrees-and-certificates/ 
https://www.clarkstate.edu/media/tsqjegbsqlybmn4hh5phzqpbyu/information-technology-and-digital-arts-_cluster-brochure_2023.pdf
=> Сlark State College

lib/domains/id/sch/smknegeri1bagor.txt
=> SMK Negeri 1 Bagor

lib/domains/com/tanokullari.txt
The school domain is the same as the domain used on mail addresses.
I couldn't find the website for it but this school offers Robotan (Robot + Tan (which is the name of the school)) which is a social club focused on coding, programming and robotics, in the time period of one (1) school year.
=> Add tanokullari.com

lib/domains/kr/ac/syu.txt
It's just an additional Korean name
Please review, and if everything looks good, merge please
Thank you :)
=> Add sahmyook university Korean name

lib/domains/edu/caspercollege/mycc.txt
For use in the many computer science courses we have available here.
https://www.caspercollege.edu/program/computer-science/
=> Add Casper College to the list of approved institutions

lib/domains/edu/ncwu.txt
add North China University of Water Resources and Electric Power(https://ncwu.edu.cn/)
=> Add North China University of Water Resources and Electric Power

lib/domains/edu/cide/alumnos.txt
Higher education institution in Mexico.
=> Added Centro de Investigacion y Docencia Economicas

lib/domains/edu/mtc.txt
=> adding mtc.edu domain ( Marion technical college )

lib/domains/org/goierrieskola.txt
Goierri Eskola added
Goierri Eskola
https://www.goierrieskola.eus/en/
=> Goierri Eskola added

lib/domains/cn/ac/iggcas/mail.txt
Institute of Geology and Geophysics, Chinese Academy of Sciences (IGGCAS) is where I am earning my Ph.D. Please add it to the list for student application of JetBrains products. Thank you very much!
=> Application for student license

lib/domains/pl/atins.txt
https://atins.pl/uczelnia/informatyka/opis-wydzialu-informatyki/
https://atins.pl/wroclaw/kandydaci/rekrutacja/
https://atins.pl/en/school/informatics/faculty-of-informatics/
---
Known previously as horyzont.eu (Wrocławska Wyższa Szkoła Informatyki Stosowanej HORYZONT), the university has changed it's name and domain since
=> [University domain name change] horyzont.eu -> atins.pl

lib/domains/de/fos-karlsfeld/stud.txt
=> fos-karlsfeld

lib/domains/de/bbs-holzminden.txt
Add  bbs-holzminden.txt for  Georg-von-Langen-Schule in Holzminden, Germany
=> Add bbs-holzminden.txt

lib/domains/ke/ac/northcoastmtc.txt
I Added a North Coast Medical Training College, I want to use data grip
=> Added North Coast Medical Training College

lib/domains/cz/spsmb.txt
Link to school website: https://www.spsmb.cz/
=> Add spsmb to list

lib/domains/com/fpfomento.txt
Formación Profesional Fomento
* College URL - https://www.fpfomento.com
* https://www.fpfomento.com/ciclos-formativos-de-fp/area-de-informatica/ciclo-superior-de-desarrollo-de-aplicaciones-web-a-distancia/
* https://www.fpfomento.com/ciclos-formativos-de-fp/area-de-informatica/ciclo-superior-de-desarrollo-de-aplicaciones-multiplataforma-a-distancia/
* https://www.fpfomento.com/ciclos-formativos-de-fp/area-de-informatica/ciclo-superior-de-administracion-de-sistemas-informaticos-en-red/
* https://www.fpfomento.com/ciclos-formativos-de-fp/area-de-informatica/ciclo-medio-de-sistemas-microinformaticos-y-redes-a-distancia/
=> add-fpfomento

lib/domains/asia/mbu.txt
_Please add the university_
[https://www.mbu.asia/](https://www.mbu.asia/)
[https://www.mbu.asia/overview/](https://www.mbu.asia/overview/)
Mohan Babu University stands tall among India’s premier institutions, having an array of prestigious rankings and accreditations. Ranked in the 150-200 band of NIRF Rankings and the 51-100 band for NIRF Innovation Ranking, it has also secured the coveted Diamond band in the QS-IGauge. Its academic prowess is further validated by NAAC A+ and NBA accreditations, along with a platinum category distinction in the AICTE-CII survey. Remarkably, the university has emerged among the top 20 in the 2023 SII Green Rankings, showcasing its commitment to sustainability. These achievements solidify Mohan Babu University’s position as a trailblazer in higher …
=> Mohan Babu University

lib/domains/net/bsgg.txt
Proof of long-term IT course: https://www.bsgg.net/bildungsangebote/berufsschule/it-berufe/
=> Add bsgg.net (Berufliche Schulen Groß-Gerau)

lib/domains/cz/sostrinec/student.txt
https://www.sostrinec.cz/
https://sostrinec.cz/maturitni_obory.html (https://sostrinec.cz/EL.html)
=> Add Střední odborná škola Třineckých železáren

lib/domains/ar/edu/ucasal.txt
=> ucasal.txt

lib/domains/ro/eminescubucuresti.txt
Please add the National College "Mihai Eminescu" from Bucharest.
Thanks in advance
=> Academic access request for jetbrains

lib/domains/ar/edu/undef/fie.txt
I just follow jetbrains [instructions](https://www.jetbrains.com/shop/eform/students/contributeUniversity?email=jdelcourt%40fie.undef.edu.ar) to add a new school 
[Here](https://www.fie.undef.edu.ar/) and [here](https://www.undef.edu.ar/) to check existence of the university
=> arg undef added to school domains

lib/domains/ar/edu/unrn.txt
University website: [https://www.unrn.edu.ar/home](https://www.unrn.edu.ar/home)
IT/CS Proof (Bachelor’s Degree in Systems): [https://www.unrn.edu.ar/carreras/Licenciatura-en-Sistemas-16](https://www.unrn.edu.ar/carreras/Licenciatura-en-Sistemas-16)
=> Added Universidad Nacional de Rio Negro (UNRN)

lib/domains/pk/edu/comsats.txt
Added the domain for COMSATS University Islamabad student emails.
Thank you.
=> Add COMSATS University Islamabad student email domain

lib/domains/si/scpet.txt
New school Šolski center za pošto, ekonomijo in telekomunikacije Ljubljana
=> Added scpet.txt to lib/domains/si

lib/domains/th/ac/bcisphuket.txt
=> Added BCIS Phuket International School

lib/domains/org/istitutomarangoni.txt
Request for adding Istituto Marangoni to the list of schools accredited for teaching license
=> Istituto Marangoni | Add files via upload

lib/domains/hk/nais.txt
- official URL: https://www.nordangliaeducation.com/nais-hong-kong
- a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: https://www.nordangliaeducation.com/nais-hong-kong/academic-excellence/secondary/computing
- a URL of a page showing that the university recognizes the domain which I am submitting as an official email domain for the enrolled students: https://www.nordangliaeducation.com/nais-hong-kong/contact-us , a contact email address at the footer section <img width="1470" alt="Screenshot 2024-11-02 at 3 15 41 PM" src="https://github.com/user-attachments/assets/e080dfab-0400-455e-a422-bb5bcd944c3f"> <img width="244" alt="Screenshot 2024-11-02 at 3 15 46 PM" src="https://github.com/user-attachments/assets/4752e299-6df5-4 …
=> add Nord Anglia International School Hong Kong

lib/domains/mx/edu/lucerna.txt
=> Universidad Lucerna

lib/domains/uk/ac/col-westanglia.txt, lib/domains/uk/ac/cwa/edu.txt
URL: https://cwa.ac.uk/ and https://cwa.ac.uk/higher-education/about-ucwa
Course Example: https://cwa.ac.uk/courses/computing-games-design-and-it/bsc-hons-applied-computer-science
=> Added The College of West Anglia

lib/domains/bd/edu/bireswarpurghs.txt
I am writing to formally request approval for the educational use of JetBrains tools for our institution, [Bireswarpur Government High School](https://bireswarpurghs.edu.bd/), a government-regulated school in Bangladesh.
Our school adheres strictly to the regulations set forth by the National Curriculum and Textbook Board (NCTB). According to NCTB guidelines, Information and Communication Technology (ICT) education is mandatory for all classes in Bangladesh. In this context, having access to high-quality educational tools is essential for enhancing the learning experience and preparing our students for the future.
JetBrains' tools are widely recognized for their effectiveness and utility in teaching ICT and programming. We believe that incorporating these tools into our curriculum would …
=> added bireswarpurghs into domain list

lib/domains/de/inntal-gymnasium.txt
**https://www.inntal-gymnasium.de**
**Proof for validity of email attached below**
Also found at https://www.inntal-gymnasium.de/kontakt/ on the original home page
=> Adding inntal-gymnasium.de

lib/domains/org/stleonards-fife.txt
=> Add St Leonards school

lib/domains/org/universityprep.txt
University Prep is a high school in Seattle, Washington.
UPrep Technology Page (Over 1 year of CS-related course offered): https://www.universityprep.org/academics/upper-school/technology
=> Added University Prep to domain list

lib/domains/pl/thebritishschool.txt
Request to add the domain thebritishschool.pl for the school The British School Warsaw.
=> Add new domain: thebritishschool.pl

lib/domains/mx/itla.txt
Instituto Tecnólogico Latinoamericano
www.itla.edu.mx
ollinsoft@itla.mx
- [x ] Academic/Teaching Staff
- [ x] Post-graduate research
- [x ] Graduate School
- [x ] College (University) or Undergraduate School or equivalent
=> Instituto Tecnólogico Latinoamericano

lib/domains/com/ieselcalamot.txt
Multi-platform Application Development uses JetBrains IDEs like PyCharm, it would be beneficial if we could get access to the remainder of the suite.
=> Add IES El Calamot

lib/domains/com/lycee-saintdenis.txt
Website URL : https://lyceesaintdenis.com/
Licence course from the univerity URL : https://lyceesaintdenis.com/6027-2/
=> add institut supérieur saint denis 

lib/domains/abused.txt, lib/domains/stoplist.txt
=> anasehir-k12-highschool added

file/lib/domains/edu/hillcollege/student.txt, lib/domains/edu/hillcollege/student.txt
Website is https://www.hillcollege.edu/ and the email format is First.Last@student.hillcollege.edu
=> Add Hill College 

lib/domains/cz/sssenp.txt
Site: https://www.sssenp.cz/
Courses: https://www.sssenp.cz/studijni-obory/
=> Add sssenp.cz

lib/domains/us/malad.txt
not sure what other email addresses this will affect but i know malad.us
=> IHLA school

lib/domains/de/neg-velbert.txt
URL: 
https://www.neg-velbert.de/
https://www.neg-velbert.de/mint-faecher/
=> Add txt for Nikolaus-Ehlen-Gymnasium

lib/domains/edu/genesee.txt
This pull request is to add Genesee Community College to JetBrains' swot repo.
=> Add Genesee Community College to the JetBrains swot

lib/domains/ua/edu/ddpu.txt
Link to my [university](https://ddpu.edu.ua/)
=> add ddpu university

lib/domains/edu/ied/alumni.txt
Added IED University in the available university domains list.
To get more info: https://www.ied.edu/
=> Add IED University in domains

lib/domains/de/aibgym.txt
Hello, I would like to add this school to the list. The official website is https://aibgym.de. As for 12th November you can see the text at the bottom of the homepage saying:
> Für die Schülerinnen und Schüler ändert sich die Domäne im Anmeldenamen der Microsoft365-Accounts. Aus @gymaib.de wird @aibgym.de. Die Passwörter und die Daten in den Accounts bleiben unverändert.
It provides a proof, that the school uses this domain for students. Under the link https://aibgym.de/mint/informatik you can see that IT is one of the courses.
The website is in German, but maybe you could use some of the online translators to verify the information.
Best regards,
Nazar
=> Add Gymnasium Bad Aibling to the list

lib/domains/rs/ac/uns.txt
Website: [https://ftn.uns.ac.rs/](https://ftn.uns.ac.rs/)
Software engineering course: [https://ftn.uns.ac.rs/akreditacija-2020/SE0/1/1](https://ftn.uns.ac.rs/akreditacija-2020/SE0/1/1)
=> Add Faculty of technical sciences in Novi Sad

lib/domains/bd/edu/fec.txt
Our institution, Faridpur Engineering College (FEC), is officially affiliated with the University of Dhaka, as listed on their website [here](https://www.du.ac.bd/colleges/Constituent?page=6#:~:text=Faridpur%20Engineering%20College%2C%20Faridpur%20(2010)). FEC offers a 4-year BSc program in three main departments: Computer Science and Engineering (CSE), Electrical and Electronics Engineering (EEE), and Civil Engineering (CE). The official FEC website is accessible at [fec.ac.bd](https://fec.ac.bd/).
Students receive institutional emails in the format {name}.{reg_no}@fec.edu.bd; for instance, a student named Erfan with the registration number 3062 would have the email erfan.3062@fec.edu.bd.
and to get an edu mail a student from fec have to fillup this form hardcopy …
=> add faridpur engineering college

lib/domains/org/windhamsd.txt
Pull request to add windhamsd.org / Windham High School to JetBrains swot
=> Add Windham High School to JetBrains swot

lib/domains/ar/edu/umet.txt
Official website: https://umet.edu.ar/
Bachelor of Computer Science: https://umet.edu.ar/course/informatica/
=> Add Universidad Metropolitana para la Educación y el Trabajo - ARG

lib/domains/edu/tamusa.txt
Please add Texas A&M University-San Antonio
Thanks!
=> Add TAMUSA

lib/domains/edu/ncstatecollege/mail.txt
Hello, please add my college to the list, thanks!
https://ncstatecollege.edu
=> North Central State College

lib/domains/ua/edu/rkepk.txt
official site of edu
https://rkepk.edu.ua/
=> RKEP Collage

lib/domains/eg/edu/sut.txt
- the university official website URL, if it is different from the domain you are submitting:  
[sut.edu.eg](url)
- a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: 
[sut.edu.eg/academics/computer-science-technology-program/](url)
=> Add El Sewedy University of Technology

lib/domains/edu/saintpaul/my.txt
- the university official website URL, if it is different from the domain you are submitting
https://www.saintpaul.edu/
- a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university
-https://catalog.saintpaul.edu/preview_program.php?catoid=3&poid=415&returnto=120
- a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.
https://www.saintpaul.edu/current-students/student-email/
https://webapps.saintpaul.edu/emaillookup/Emaillookup.aspx
=> add saint paul college

lib/domains/kh/edu/ppiu.txt
Requested to Add Phnom Penh International University.
=> Requested to Add Phnom Penh International University

lib/domains/id/ac/ub.txt
Hi,
Could you please add domain that is used by lecturer here.
Thank you.
Official Website: https://www.ub.ac.id/en/
Computer Science Faculty: https://filkom.ub.ac.id/
=> Add Universitas Brawijaya

lib/domains/edu/giet.txt
University website - https://www.giet.edu/
=> Giet University addition

lib/domains/nz/school/naenaeint.txt
Adding Naenae Intermediate School
Website: https://www.naenaeint.school.nz/
=> Adding Naenae Intermediate School

lib/domains/edu/uceou.txt
Official School Website URL : https://www.uceou.edu/
CS Courses URL : https://www.uceou.edu/dept-cse.php   ->(go to courses section)  
email template : username@uceou.edu 
Address : CG49+PCF, Osmania University, Hyderabad, Telangana State, INDIA.
=> Added uceou

lib/domains/edu/cornellcollege.txt
Cornell college added to swot file
=> University addition

lib/domains/com/colfes, lib/domains/com/colfes.txt
Website:
www.colfes.com
Offers computer science at GCSE and A-Level:
https://www.colfes.com/senior-school/academic/computer-science/
=> Colfe's school

lib/domains/edu/klnce.txt
institute WebPage: https://klnce.edu/
=> Adding KLNCE to SWOT

lib/domains/edu/tricountyallied.txt
Adding Tricounty Allied School
=> Adding Tricounty Allied School

lib/domains/es/ciclosformativosceu.txt
https://www.uchceu.es/facultad/eset
=> ADD ESET Technical School of Engineering

lib/domains/edu/vinu/myvu.txt, myvu.txt
Website:
Vinu.edu
Email Page:
https://vinu.teamdynamix.com/TDClient/69/Portal/KB/ArticleDet?ID=18251&SIDs=1302
Courses (Catalog undergoing maintenance at the moment)
https://catalog.vinu.edu/index.php?catoid=50
https://www.vinu.edu/major/it-programming-and-game-development-concentration-as-transfer.html
https://www.vinu.edu/major/it-web-design-concentration-as-transfer.html
https://www.vinu.edu/major/computer-programming-technology-networking-concentration-as-career-tech-jasper.html
https://www.vinu.edu/major/computer-programming-software-development.html
https://www.vinu.edu/major/computer-programming-software-development.html
=> Adding Vincennes

lib/domains/ua/edu/kntu.txt
Add new e-mail domain of Kherson National Technical University
=> Add kntu.txt

lib/domains/np/edu/bicnepal.txt
=> Add bicnepal.edu.np to JetBrains swot

lib/domains/gh/edu/atu/st.txt
Screenshot of Active student email
=> added Accra Technical University domain

lib/domains/net/northrise.txt, lib/domains/net/northrise/Northrise University.txt
university URL =  https://northrise.edu.zm/
program URL = https://northrise.edu.zm/academics/schools-northrise-university/center-for-information-and-communication-technologies/#undergrad-tech-1
example email =  Student_id_number@northrise.net
=> Updated request for Northrise university

lib/domains/cz/svitavy/gy.txt
https://www.gyoa.svitavy.cz/
https://www.gyoa.svitavy.cz/ucitele/
// image contains proof of "@gy.svitavy.cz" being the official email domain of our school
https://www.gyoa.svitavy.cz/gymnazium-ctyrlete-studium/
// image contains proof of an available IT course in programming lasting 2 years, there isn't a full page about this, the text is at the bottom of this page
=> gy.svitavy.cz

lib/domains/study/student.txt, lib/domains/study/varsovia.txt
=> Add support for Varsovia

lib/domains/org/iss-lubumbashi.txt
https://www.iss-lubumbashi.org
=> Adding iss-lubumbashi.org

lib/domains/uk/ac/hsdc/student, lib/domains/uk/ac/hsdc/student.txt
Added `uk/ac/hsdc/student` for @student.hsdc.ac.uk email addresses.
=> Add @student.hsdc.ac.uk for HSDC

lib/domains/pl/krakow/uken.txt
Adding University of the National Education Commision, Cracow
=> Adding University of the National Education Commision, Cracow

lib/domains/edu/mtholyoke.txt
=> Add Mount Holyoke College

lib/domains/ng/edu/uat.txt
Here are the details of the school.
[Website](https://uat.edu.ng)
[Wikipedia](https://en.wikipedia.org/wiki/University_of_Africa,_Toru-Orua)
[Facebook](https://web.facebook.com/UniAfricaOrua/?_rdc=1&_rdr)
=> Add University of Africa Toru-Orua

lib/domains/it/pg/avolta.txt
The repo only has the main domain:
avoltapg.edu.it
but apple id uses another one:
avolta.pg.it
and I can't register as a student using that, so I'm adding it...
=> Added domain for school apple id `avolta.pg.it`

lib/domains/org/ittterni.txt
Add Istituto Tecnico Tecnologico "Allievi-Sangallo"
url : https://www.ittterni.edu.it/
gsuite for edu : @ittterni.org
=> Add Istituto Tecnico Tecnologico "Allievi-Sangallo"

lib/domains/pl/edu/kilar.txt
Added a school located in Katowice, Poland.
=> Added ZPSM POSM 1st. im. S. Moniuszki

lib/domains/bg/uniburgas.txt
=> Adding University Asen Zlatarov

lib/domains/ar/edu/taborin.txt
I am submitting a request to add the domain `taborin.edu.ar` for **Colegio Gabriel Taborin** to the JetBrains SWoT repository.  
- **University Name**: Colegio Gabriel Taborin  
- **Official Website**: [https://taborin.edu.ar/](https://taborin.edu.ar)  
- **IT-Related Course Page**: [https://taborin.edu.ar/portal/gabinete-de-informatica/](https://taborin.edu.ar/portal/gabinete-de-informatica/)  
This page describes the IT laboratory and long-term computer science-related courses offered by the school.  
- **Email Proof**:  
The domain `taborin.edu.ar` is actively used for official school communications. Proof can be found on the **Contact Page**:  
[https://taborin.edu.ar/portal/contacto/](https://taborin.edu.ar/portal/contacto/)  
Example email addresses listed:  
- …
=> "Add domain taborin.edu.ar for Taborin College"

lib/domains/uk/org/rbcs.txt
=> Reading Blue Coat School

file/lib/domains/it/edu/boscardin.txt, lib/domains/it/edu/boscardin.txt
the email ends with @boscardin.edu.it
=> Add IIS S. Bertilla Boscardin to school options

lib/domains/au/edu/wa/ccgs/student.txt
=> CCGS High school.

lib/domains/edu/ufairfax/students.txt
=> Add fairfax

lib/domains/it/ts/volta.txt
https://www.voltatrieste.edu.it/
=> add ITS Volta Trieste

lib/domains/iq/edu/almaaqal.txt
AKA Almaqaal Private University
AMIU (Almaaqal International University)
[the official website](https://almaaqal.edu.iq/)
[4 year control and computer engineering bachelor degree program](https://eng.almaaqal.edu.iq/%d9%82%d8%b3%d9%85-%d9%87%d9%86%d8%af%d8%b3%d8%a9-%d8%a7%d9%84%d8%b3%d9%8a%d8%b7%d8%b1%d8%a9-%d9%88%d8%a7%d9%84%d8%ad%d8%a7%d8%b3%d8%a8%d8%a7%d8%aa-2)
[A pdf file sent by the university in the 9th of January 2022 explaining some things about the student email address](https://github.com/user-attachments/files/17964810/_._._._._._._._.pdf)
=> Almaaqal International University

lib/domains/net/lycee-bordebasse.txt
This will add `Lycée polyvalent de la Borde Basse`
Visit school official website here: [Link](https://borde-basse.mon-ent-occitanie.fr/)
=> Adding the bordebasse school

lib/domains/edu/Asher.txt
Add Asher College, for asher.edu emails.
=> Add Asher college

lib/domains/edu/deepsprings.txt
Hello. I am a professor at Deep Springs College, which is a small two-year college at the eastern edge of California. The closest major cities are in Nevada. You can readily verify that we are an accredited institution offering courses to a small number of full-time students. To do that start at deepsprings.edu, go to the page footer, and follow the "Trustees and Accreditation" link. You can also go directly to our most recent re-accreditation letter, which is here: https://www.deepsprings.edu/next/wp-content/uploads/2024/07/ACCJCReaffirmationOfAccreditation2024-06-12.pdf Thanks very much for reviewing this pull request. ~Brian Hill
=> Added deepsprings.txt for Deep Springs College.

lib/domains/schule/bbs2.txt
[Official school website](https://www.bbs2goe.de/)
[About IT-Courses there](https://www.bbs2goe.de/cms/de/182/Fachinformatiker-fuer-Systemintegration-%E2%81%84-Anwendungsentwicklung)
[Here you can see that bbs2.schule is the official domain for emails](https://www.bbs2goe.de/cms/de/2/Kontakt)
[School iServ (School network and webportal/learning platform (needs student login)](https://bbs2.schule/)
IServ - logged in. Here you can also see my student email with the "bbs2.schule" domain.
As a German "Berufsschule", the BBS2 offers apprenticeships. For the IT field, any apprenticeship in Germany lasts for at least 2 years, while most go on for 3 years.
=> Added bbs2.schule, the German Berufsbildende Schulen II in Göttingen

lib/domains/edu/allegany.txt
Trying this again, without the student part of the domain.
If you decline this one aswell, can you please give me further instructions. I am following the instructions to the best of my ability.
My actual email is jscanlon@student.allegany.edu and jetbrains gave me the file and it was declined saying that domain doesn't exist. I am now trying to add just @allegany.edu
Please let me know if this is still incorrect and how I can fix this.
=> Added Allegany College of Maryland

lib/domains/de/gymbruck.txt
Official website: https://www.gymnasium-bruckmuehl.de/ 
Proof of computer science being taught actively:
- Translated website with Google Translate: https://www-gymnasium--bruckmuehl-de.translate.goog/?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=wapp
- Original website: https://www.gymnasium-bruckmuehl.de/informatik.html
=> Added Gymnasium Bruckmuehl

lib/domains/com/onmicrosoft/mescoeorg.txt
Adding the college MESCOE Pune under onmicrosoft folder.As it is not there.
=> Added MESCOEPUNE under onmicrosoft

lib/domains/uk/ac/city-of-portsmouth-college.txt, lib/domains/uk/sch/hants/hayling.txt
=> [+] THC & COPC

lib/domains/edu/anokaramsey.txt
Add Anoka Ramsey Community College
=> Add Anoka Ramsey Community College

lib/domains/edu/ttic.txt
Institute domain: **ttic.edu**
Institute website: https://ttic.edu
Institute name: TTI-Chicago (Toyota Technological Institute at Chicago)
Screenshot:
=> New school - TTI Chicago

lib/domains/uk/sch/cumbria/nts.txt
=> Added NTS Via Upload

lib/domains/ua/edu/viti.txt
Military institute of telecomunication and information technologies named after Heroes of Kruty added
=> MITIT added

lib/domains/edu/sfcc.txt
https://www.sfcc.edu/
https://sfccssb.sfcc.edu/PROD/pw_pub_sched.p_listthislist?term_in=202430&subj_in=ISCS
=> Add SFCC domain

lib/domains/bd/edu/butex/tem.txt
**School name:** Bangladesh University of Textiles
**Official website:** [https://www.butex.edu.bd/](https://www.butex.edu.bd/)
=> Added Bangladesh University of Textiles

lib/domains/cz/skolajecna.txt
Ofiicial website : vos.skolajecna.cz
Name of course: Informatics n healthcare
In attachemet screen from school´s system - where you can see course.
=> skolajecna.cz

lib/domains/bd/edu/simecinstitute.txt
Add SIMEC Institute of Technology
=> SIMEC Institute of Technology

lib/domains/org/marchwoodseniorschool.txt
May you please verify and add my school
=> Marchwood Senior School

lib/domains/in/rathinam.txt
Add Rathinam College Of Arts And Science
- official college website link https://rathinamcollege.ac.in/
=> Add Rathinam College Of Arts And Science

lib/domains/pe/edu/senati.txt
https://www.senati.edu.pe/
https://www.senati.edu.pe/especialidades/tecnologias-de-la-informacion/desarrollo-de-software
=> Add SENATI institute

lib/domains/com/gip-cei/etu.txt
site officiel https://gip-cei.com/
=> Add domains ESLI

lib/domains/th/ac/bkkthon.txt
https://bkkthon.ac.th/home/en/graduate/Master
=> add university file

lib/domains/ph/edu/sunn.txt
Adding sunn.edu.ph official domain of State University of Northern Negros
=> Add files via upload - Adding sunn.edu.ph

lib/domains/edu/monaco.txt
International University of Monaco (IUM)
https://www.monaco.edu
=> Adding domain for IUM

lib/domains/bo/edu/sanagustin.txt
Colegio San Agustin, Cochabamba Bolivia
=> San Agustin

lib/domains/vn/udn/dut/sv1.txt
- University official website: https://dut.udn.vn/  (In English language: https://en.dut.udn.vn/)
- A URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: https://en.dut.udn.vn/objectives-and-learning-outcomes-of-bachelor-architect-training-program-84.html
- A URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students:
This is my student info on the university's student information system website. As you can see, there's a line specifying the Office365 account that my university provides to students, which serves as my student email address.
=> Add request file for University of Science and Technology - University of Danang's email domain

lib/domains/io/csie.txt
National Chung Cheng University
https://cs.ccu.edu.tw/p/404-1094-6492.php?Lang=en
This page show we use csie.io as domain
https://csie.io/faq.html
=> adding National Chung Cheng University

lib/domains/bd/edu/bu.txt
Adding Bangladesh University
Domain is bu.edu.bd
Computer Science Department Official Page for 4 year course curriculum is https://cse.bu.edu.bd/curriculum
=> Adding Bangladesh University domain bu.edu.bd

lib/domains/cz/stavskola.txt
I am a teacher at the High school for construction in Havlickův Brod in the Czeche republic.  This year we sarted new branch of study at this school  Information technology.
=> Add Střední průmyslová škola stavební akademika Stanislava Bechyně Havlíčkův Brod to the  swot repository

lib/domains/mx/edu/ulsaoaxaca.txt
Solicitud para añadir archivo de escuela - Universidad La Salle Oaxaca
=> Añadido archivo de escuela para JetBrains

lib/domains/com/swa-jkt.txt
You can contact by email: adilet_yesbayev @ school domain dot com
=> Added Sinarmas World Academy school to the list

lib/domains/net/sau25.txt
Added my high school where I teach.
=> Added my high school.

lib/domains/ua/edu/suem.txt
Східноєвропейський університет імені Рауфа Аблязова
Rauf Ablyazov East European University
https://suem.edu.ua/
https://suem.edu.ua/fahovyi-koledj-specialnist-cyfrova-ekonomika
https://suem.edu.ua/osvitnyo-profesiyna-programa-cifrova-ekonomika
=> Add suem.edu.ua University

lib/domains/edu/heartland/my.txt
**Name:** Heartland Community College
**URL:** https://www.heartland.edu/
**Address**:
```
1500 West Raab Road
Normal, Illinois 61761-9446
United States of America
```
**URLs for IT-related long term courses:**
```
https://www.heartland.edu/computerScience/
https://www.heartland.edu/documents/pathways/AS_StudentPlan.pdf
```
**Proof of official email domain for students:**
```
Login page: https://mail.google.com/a/my.heartland.edu
Student portal leading to the login page: https://d29qfhnzl4hc38.cloudfront.net/index.html
Student handbook referencing the email domain: https://www.heartland.edu/studentHandbook/
```
=> Add Heartland Community College

lib/domains/ph/edu/ndmc.txt
Good afternoon, JetBrains team,
I hope this message finds you well. I would like to propose an update by adding my current college to the list of schools.
Here are the details:
• Official website: [Notre Dame of Midsayap College](https://www.ndmc.edu.ph/)
• Official School Email: [info@ndmc.edu.ph](mailto:info@ndmc.edu.ph)
• Undergraduate programs: [NDMC Undergraduate Programs](https://www.ndmc.edu.ph/content/undergraduates)
• Proof of legitimacy: [Notre Dame of Midsayap College - Wikipedia (https://en.wikipedia.org/wiki/Notre_Dame_of_Midsayap_College)
Thank you for your time and consideration!
Best regards,
zeykdev
=> Create ndmc.txt (Notre Dame of Midsayap College, INC)

lib/domains/au/edu/nsw/det.txt
Added Tuggerah Lakes Secondary College
=> Create det.txt (Public School)

lib/domains/org/isd273.txt
Website: [Edina Schools](https://www.edinaschools.org/)
=> Add Edina Schools

lib/domains/id/sch/bintangmulia.txt
**Educational Institution Name**: SMA Bintang Mulia
**Website**: https://bintangmulia.sch.id/
**Location**: Bandung, Indonesia
**School Description**
SMA Bintang Mulia is a private high school providing a three-year educational program recognized by the Indonesian Ministry of Education and Culture.
**Dedicated Email Address**
Students are granted unique email addresses in the format `[aa][bb][10][xxx]@bintangmulia.sch.id`, where:
aa: Year of enrollment.
bb: Year of enrollment + 1.
xxx: Unique student ID.
E.G. 242510047@bintangmulia.sch.id
=> Add SMA Bintang Mulia

lib/domains/pk/edu/aligarh.txt
**Website:** [https://aligarh.edu.pk/](https://aligarh.edu.pk/)
**Relevant Course:**  
[Software Engineering (3 years) - Diploma of Associate Engineering](https://aligarh.edu.pk/diploma-of-associate-engineering-in-software-engineering-technology/)
**Domain Usage:**  
Email addresses use `@aligarh.edu.pk`  
Example: `AIT-2024-SET-E-003@aligarh.edu.pk`
---
- The official website ([https://aligarh.edu.pk/](https://aligarh.edu.pk/)) prominently displays the domain `aligarh.edu.pk` as part of the contact information (e.g., `info@aligarh.edu.pk`).
- Screenshot provided for verification:
=> Added domain aligarh.edu.pk for Aligarh Institute of Technology
