JetBrains/swot

lib/domains/ar/edu/issd.txt
Add Santo Domingo Higher Institute to lib.
https://issd.edu.ar/
=> add ISSD to lib

lib/domains/bd/edu/adust.txt
request to add ADUST in university list [website](https://www.adust.edu.bd)
=> add adust in university list

lib/domains/edu/kirkwood.txt
- [URL of a page where a long-term IT related course is offered](https://www.kirkwood.edu/businessandit)
- [URL of a page showing the official email domain for enrolled students](https://www.kirkwood.edu/email)
=> Adding kirkwood.edu

lib/domains/bd/edu/fiu.txt
This university offers two long-term (>1 year) IT related degrees: B.Sc. in Computer Science & Engineering, and M.Sc. in Computer Science & Engineering. 
See here: https://www.fiu.edu.bd/program-syllabuses/
and here: https://www.fiu.edu.bd/tuition-fees/
=> Add Fareast International University

lib/domains/kr/ac/tw.txt
=> Added new domain for new TongWon University

lib/domains/dz/esgee-oran.txt
Add esgee-oran.dz to the list of supported domains.
=> Add esgee-oran.dz to the list of supported domains

lib/domains/edu/monroeu.txt
Requesting to add Monroe University to the edu domain.
=> Adding in Monroe University

lib/domains/edu/gmercyu.txt
Address:
1325 Sumneytown Pike
P.O. Box 901
Gwynedd Valley, PA 19437
CIS Major:
[https://www.gmercyu.edu/academics/programs/cis-major](https://www.gmercyu.edu/academics/programs/cis-major)
=> Add Gwynedd Mercy University (gmercyu.txt)

lib/domains/edu/porterchester/email.txt
new school YTI Career Institute
https://yti.edu/programs/computer-programs
=> Porterchester

lib/domains/eg/edu/rst.txt
Adding Al Ryada University For Science And Technology
=> Adding Al Ryada University For Science And Technology

lib/domains/edu/sjctni/mail.txt
Have Added St. Joseph's College (Autonomous)
=> Added St Jseph's College (Autonomous)

lib/domains/edu/ccsdetroit.txt
Add ccsdetroit(College for Creative Studies)
=> Add ccsdetroit(College for Creative Studies)

lib/domains/edu/purdueglobal.txt
adding Purdue Global University
=> purdue Add files via upload

lib/domains/de/giu-berlin/student.txt
Adding German international University
=> Adding giu-berlin

lib/domains/de/geskn.txt
Adding Gesamtschule Kürten (Kürten Comprehensive School)
=> Adding geskn

lib/domains/kg/edu/cpu.txt
Name：China Pharmaceutical University
WEB: https://cpu.edu.kg/
=> add China Pharmaceutical University

lib/domains/bd/edu/bsikm.txt
Institute Name: Bharella Shah Israil Kamil Madrasa
Website: [https://bsikm.edu.bd](https://bsikm.edu.bd)
Address: Varella, Barichong, Kumilla, Bangladesh.
Contact: hello@bsikm.edu.bd
=> Add New Kamil Madrasa

lib/domains/ba/edu/smts.txt
=> smts.edu.ba domain added

lib/domains/org/greenhill.txt
The school url is greenhill.org, it's a high school offering yearlong CompSci courses, so to my knowledge it fits the requirements.
=> Add Greenhill School

lib/domains/edu/jalc.txt
=> John A. Logan Community College

lib/domains/com/universityschools.txt
=> Create file for University Schools

file/lib/domains/pl/edu/zsp1piotrkow.txt, lib/domains/pl/edu/zsp1piotrkow.txt
Should be in line with the rules
=> Another school

lib/domains/tr/edu/istanbul.txt
Istanbul University
https://www.istanbul.edu.tr/
=> Add istanbul.txt file via upload

lib/domains/tr/k12/tubitakfenlisesi.txt
https://tubitakfenlisesi.meb.k12.tr/
https://tfl.tubitak.gov.tr/
=> Add Tübitak Fen Lisesi email domain

lib/domains/gh/edu/atu.txt
- Added Accra Technical University to the list of educational institutions eligible for free JetBrains licenses.
- Verified the institution's domain and eligibility.
- https://atu.edu.gh/
- Address: P. O Box GP 561, Barnes road, Accra.
- Digital Address:  GA-106-2535
-  Call: +233 544368159
- Office Number: 023333 2095371
=> add Accra Technical University to SWOT repository

lib/domains/ar/edu/unaj.txt
Universidad Nacional Arturo Jauretche
- [Home](https://www.unaj.edu.ar)
- [Computer Engineering](https://www.unaj.edu.ar/carreras/ingenieria-y-agronomia/ingenieria-informatica/)
=> Add domain unaj.edu.ar

lib/domains/pt/esfundao.txt
=> Agrupamento de escolas do Fundão

lib/domains/ch/zh/edu/stud.txt
Hi there!
My school recently changed its email domain format from name.surname@stud.kzn.ch (which currently works when applying for the student license) to name.surname@stud.edu.zh.ch. Unfortunately, the old email domain will likely be shut down in about three months.
Here are some details to help you verify the new domain:
Official school website: https://www.kzn.ch/
IT guide (Notion page): https://kzn.notion.site/IT-Handbuch-der-KZN-2cad7b4adc0642218d3e71655fc4fef4
Additionally, the new domain is officially recognized for student email addresses by our institution. I hope this information helps make the verification process easier.
Thank you for your time and support!
Best regards,
-Simyon
=> Request to Add a New Domain for Zurich North Cantonal School 

lib/domains/ph/edu/wlcormoc.txt
=> Western Leyte College of Ormoc

lib/domains/ca/myunfc.txt
Add myunfc.txt file to add the school University of Niagara Falls Canada. host is myunfc.ca.
=> Add myunfc.txt file to add the school University of Niagara Falls Canada

lib/domains/vn/edu/cmcu/st.txt
University Name: CMC University
University Website: https://cmcu.edu.vn/
Long-Term IT Program: https://cmcu.edu.vn/nganh-cong-nghe-thong-tin/
=> Add st.cmcu.edu.vn domain for CMC University

lib/domains/com/ecole-artcom.txt
Adding Ecole ArtCOM for the list of schools.
=> adding ecole artcom domain

lib/domains/edu/nobles.txt
=> adding nobles.edu domain list

lib/domains/kr/ac/anyang.txt
=> Add Anyang Univ South Korea

lib/domains/au/edu/vic/heathdale.txt
Website - https://www.heathdale.vic.edu.au
=> Added Healthdale Christian College

lib/domains/edu/feitian/stu.txt
Offic URL: feitian.edu
MS in Data Science URL: https://feitian.edu/academics/graduate-programs/ms-in-data-science/
=> Add Feitian.edu

lib/domains/id/ac/buddhidharma.txt
Added Universitas Buddhi Dharma
=> Add school file for BuddhiDharma

lib/domains/au/edu/vic/minaret/student.txt
=> Added Minaret College

lib/domains/bd/edu/smrc.txt
Govt. Shahid Moshiur Rahman College has updated its college data. Please accept our pull request so we can assign your developer team to develop some software for our project.
=> College data updated please accept the pull request. 

lib/domains/com/technoindiaeducation.txt
Add my university on the JetBrains domain ,
I want to add my university there . 
university : [**Techno India University , Salt Lake Sector V , WestBengal , India .**](https://www.technoindiauniversity.ac.in/)
=> Added My University File to the Domain

lib/domains/bd/edu/niter.txt
Need to add "National Institute of Textile Engineering & Research (NITER)" as an esteemed university listing.
=> Need to add "National Institute of Textile Engineering & Research (NITER)"

lib/domains/edu/drbu.txt
=> Register drbu.edu [Dharma Realm Buddhist University]

lib/domains/br/com/uniasselvi.txt, lib/domains/br/uniasselvi/uniasselvi.txt
Official institutional references:
university official website: https://portal.uniasselvi.com.br/institucional
Official Bachelor of Computer Science program: https://portal.uniasselvi.com.br/graduacao/bacharelado/ciencia-da-computacao/presencial
=> add Uniasselvi

lib/domains/org/breckschool/student.txt
=> Add Breck School

lib/domains/edu/ksbe.txt
=> Kamehameha Schools Bishop Estate

lib/domains/org/cittumkur.txt
Channabasaveshwara Institute of Technology
https://cittumkur.org
=> Add CIT, Tumkur

lib/domains/net/lions.txt
adding domain lions.net for South Fayette High School
=> adding domain lions.net

lib/domains/uk/ac/sunderlandcollege/my.txt
=> Add My College to Jet Brains List

lib/domains/ua/edu/kibit.txt
Add Kibit to the list of schools
https://kibit.edu.ua/
emails domain is @kibit.edu.ua
=> Add Kyiv Institute of Business and Technology to list of domains

lib/domains/id/sch/sttdanaksholeh.txt
=> Add sttdanaksholeh

lib/domains/edu/emcc.txt
**Official Website**: https://www.emcc.edu
**EMCC 24-25 Academic Catalog**: 
https://www.emcc.edu/wp-content/uploads/2024/09/24-25-Catalog-FINAL1.pdf 
Computer Technology Coding Program: pages 74-75
Screenshot of page 75:
**Proof of Domain Usage** - email from EMCC IT referencing my updated email addr:
=> Add Eastern Maine Community College

lib/domains/kr/ac/kyungnam.txt
=> Add Kyungnam.ac.kr

lib/domains/edu/csmd/mymail.txt
Website: https://www.csmd.edu/
Computer Science Degree: https://www.csmd.edu/programs-courses/program-finder/computer-science.html
Email Domain: https://www.csmd.edu/student-services/help-desk/microsoft/index.html
=> Add College of Southern Maryland(CSM / CSMD)

lib/domains/edu/ohiodominican.txt
1. https://www.ohiodominican.edu/academics/bachelors-degrees/computer-science/department-page.htmlhttps://www.ohiodominican.edu/academics/bachelors-degrees/computer-science/department-page.html
=> Add Ohio Dominican University domain

lib/domains/br/edu/faculdadegran.txt
URL do site oficial da escola - https://faculdade.grancursosonline.com.br/
o endereço da escola, incluindo cidade e país - Rua Luiz Parigot de Souza, 961, Portão, Curitiba, Paraná, PR, CEP 81070-050 - BRASIL
uma URL de uma página no site oficial onde a escola oferece um curso de longo prazo (>1 ano) relacionado a TI: https://faculdade.grancursosonline.com.br/curso/analise-e-desenvolvimento-de-sistemas/
uma prova que mostra que a escola reconhece o domínio que você está enviando como um domínio de e-mail oficial para os alunos:
=> Add files via upload - Gran Faculdade

lib/domains/de/fhdw/edu.txt
[www.fhdw.de](official webpage)
[https://www.fhdw.de/bachelor/wirtschaftsinformatik-software-engineering](>1 year IT related course (german))
=> Add Fachhochschule der Wirtschaft gGmbH

file/lib/domains/hu/puskas.txt, lib/domains/hu/puskas.txt
Official website URL: https://www.puskas.hu/100/
IT related course URL:  https://www.puskas.hu/100/oldal/szakkepzes-40
Proof showing that the High School recognizes the email domain (@puskas.hu):  https://www.puskas.hu/100/oldal/kapcsolat
=> Add Puskás Tivadar Távközlési Technikum (High School)

lib/domains/ae/brightoncollegedubai.txt
https://www.brightoncollegedubai.ae/
=> Added Brighton College Dubai

lib/domains/kr/ac/nuch.txt
it's just an additional Korean name
Please review, adn if everything looks good, merge please
Thank you :)
=> Add Korea National University of Heritage

lib/domains/edu/snow/students.txt
University url: https://snow.edu/
IT course: https://bit.ly/3C8cphp
Domain recognition: https://www.snow.edu/offices/it/student-email.html
=> Add Snow College

lib/domains/mx/edu/itsn.txt
Solicito que agreguen mi escuela
=> Se agrega instituto tecnologico de nochistlan

lib/domains/edu/pnw.txt
=> Add Purdue University Northwest

lib/domains/edu/ntc.txt
Add domain for Northcentral Technical College
=> Add Northcentral Technical College

lib/domains/edu/johnsonu.txt
Official website URL: https://johnsonu.edu/
IT related course: https://johnsonu.edu/bachelors/computer-science/
Students and Employees Email: https://johnsonu.blackbelthelp.com/it/what-are-the-username-default-password-formats/
=> Added Johnson University

lib/domains/vn/udn/ute/sv.txt
Added school info for requesting free JetBrains licenses.
=> add University of Technology and Education - The University of Danang

lib/domains/kg/edu/ust.txt
=> Kyrgyzstan University of Science and Technology

lib/domains/np/edu/gmmc.txt
Added Gupteshwor Mahadev Multiple Campus
=> Added Gupteshwor Mahadev Multiple Campus

lib/domains/edu/whccd.txt
West Hills College - Lemoore / West Hills College - Coalinga / Lemoore College / Coalinga College
=> Adding whccd.edu for Education Pack

lib/domains/com/fjaverianas/estudiant.txt
ETP Xavier is in Barcelona, Spain.
=> Added domain for ETP Xavier

lib/domains/com/smcsmail.txt
St. Michael's College School
St. Michael's College School
=> St. Michael's College School request 

lib/domains/it/vda/scuole/mail.txt
It's for a teacher account in medium school in Italy.
Thanks
=> Can you please add mail.scuole.vda.it ?

lib/domains/co/edu/meicol.txt
=> add meicol.edu.co domain

lib/domains/edu/mpm.txt
Please add the domain of the Milwaukee Public Museum to your list. We offer higher education in fields such as bioinformatics and computational biology in association with Marquette University and others. Thank you!
=> Adds mpm to list of domains

lib/domains/bd/edu/stamforduniversity.txt
Hello JetBrains Team! 👋
I would like to add my university - **Stamford University Bangladesh** - to the Swot repository.
University Information:
- University Name: **Stamford University Bangladesh**
- Official Website: https://www.stamforduniversity.edu.bd/
- Student Email Domain: **@stamforduniversity.edu.bd**
Program Details:
- Department: Computer Science and Engineering (CSE)
- Program Link: https://cse.stamforduniversity.edu.bd/
- Program Duration: 4 years (8 semesters)
QS Ranking:
- Link: https://www.topuniversities.com/universities/stamford-university-bangladesh
Additional Information:
- The university is approved by the University Grants Commission (UGC) of Bangladesh
- We offer multiple IT-related programs including BSc in CSE and BSc in Software Engineering
Thank you for …
=> [Added] `Stamford University Bangladesh`

lib/domains/edu/cypresscollege.txt
Official School URL: https://www.cypresscollege.edu/
Computer Science Program Page: https://www.cypresscollege.edu/academics/divisions-special-programs/business-cis/computer-science/
Student Email FAQ: https://www.cypresscollege.edu/2024/09/16/access-your-student-email-and-microsoft-365-apps/
=> Add cypresscollege.edu domain

lib/domains/kg/edu/knau.txt
Kyrgyz National Agrarian University
Official website:knau.edu.kg
Email Domain knau.edu.kg
Location:68 Mederova St, Bishkek
=> Add Kyrgyz National Agrarian University

lib/domains/id/ac/um-surabaya/ft.txt
add subdomain for universitas muhammadiyah surabaya
in ft.um-surabaya.ac.id
=> add subdomain for um-surabaya.ac.id

lib/domains/kg/edu/batmu.txt
Batken state university
Official website:batmu.edu.kg
Email Domain batmu.edu.kg
Location:Batken region, Batken city, I. Zhusupov street, 21
=> Add Batken state university

lib/domains/edu/highlands.txt, lib/domains/edu/highlands/student.txt
Official Website: [https://highlands.edu](https://highlands.edu)
We offer an Associates Degree program for Computer Science and Computer Information Systems which rely heavily on Java, Databases and Python courses.
Here is a link to our Mathematics and Technology department's page:
[https://sites.highlands.edu/stem/mathematics-and-technology/](https://sites.highlands.edu/stem/mathematics-and-technology/)
Here is the PDF of the curriculum requirements: [Pathway Map - Comp Science.pdf](https://github.com/user-attachments/files/18351411/Pathway.Map.-.Comp.Science.pdf)
=> Add Georgia Highlands College

lib/domains/cn/edu/aynu/stu.txt
This pull request adds the email domain for Anyang Normal University (stu.aynu.edu.cn) to the repository.
- Offical Website: https://www.aynu.edu.cn/
=> Add Anyang Normal University domain

lib/domains/in/gov/delhi/doe.txt
Adding my school's Name to Jetbrains as my school provides Web development and Information technology subjects and we would require Jetbrains tools for web, python, Data and other
=> Adding School 

lib/domains/kg/edu/oshtu.txt
Osh Technological University
Official website:oshtu.edu.kg
Email Domain oshtu.edu.kg
Location:Kyrgyz Republic, Osh, Isanov street, 81
=> Add Osh Technological University

lib/domains/et/edu/adu.txt
Official website http://www.adu.edu.et/
IT-related courses   http://www.adu.edu.et/admission/undergraduate-programs/
=> Adding the domain of Adigrat University to the repository

lib/domains/uk/ac/wcs/live.txt
This pull request adds school details for West College Scotland, including the appropriate email domain for student licenses.
=> Added school detailes for West College Scotland

lib/domains/education/jda-gex.txt
Added Joan of Arc High School _(Lycée Jeanne d'Arc)_ (Cessy, France)
Website: https://www.jda-gex.org/
=> Added jda-gex

lib/domains/mx/edu/itcj.txt
Adding Technological Institute of Ciudad Juárez to JetBrains SWOT repository.
**Institution Name:** Technological Institute of Ciudad Juárez
**Location:** Cd. Juárez, Chihuahua, México
**Email Domain:** itcj.edu.mx
**Official Website:** http://cdjuarez.tecnm.mx/
=> feat: Add Technological Institute of Ciudad Juárez

lib/domains/ar/edu/uvq.txt
Add file for "Universidad Nacional de Quilmes"
=> Add files for UVQ

lib/domains/nz/school/Otahuhu College.txt, lib/domains/nz/school/otahuhucollege.txt
College web domain:  https://otahuhucollege.school.nz/
Course selection (Digital Technologies) https://otahuhucollege.school.nz/course-selection/
=> Otahuhu College request

lib/domains/ph/edu/cultural.txt
School website
https://www.philippineculturalcollege.edu.ph/programsoffered.html
sample student email
xxx@cultural.edu.ph
=> Philippine cultural college

lib/domains/kr/ac/gangseo.txt
it's just an additional Korean name
Thank you:)
=> Add gangseo.txt

lib/domains/ar/edu/ort.txt
=> Adding Instituto de Tecnología ORT

lib/domains/tr/k12/almanlisesi.txt
File added for Deutsche Schule Istanbul
=> Deutsche Schule Istanbul

lib/domains/kr/ac/yi.txt
I am submitting the required details for the verification of the official school email domain for my institution. Please find the requested information below:
1. School Official Website URL:
- https://www.yongin.ac.kr
- http://yi.ac.kr
- http://yiu.ac.kr
2. School Street Address (Including City and Country):
- 286, Yongin-daehak-ro, Cheoin-gu, Yongin-si, Gyeonggi-do, South Korea
3. URL of a Page on the Official Website Where the School Offers an IT-Related Long-Term Course:
- https://www.yongin.ac.kr/cmn/wvtex/nibr/colDept/COL_DEPT_00000000181/colDeptMain.do
Please let me know if additional information or documents are required for verification.
=> add youngin university domain

lib/domains/edu/canyons.txt
=> Adding College of the Canyons

lib/domains/org/greenwichacademy.txt
=> Create greenwichacademy.txt domain

lib/domains/net/netkentuni.txt
Official website:https://international.netkentuni.net student entry:https://ois.netkentuni.net/auth/login/ln/en Email example: name.lastname@campus.netkentuni.net Location: North Cyprus Turkish Republic.Netkent Mediterranean Research and Science University Netkent has undergraduate and graduate online interactive degree programs in English medium. Undergraduate Programs are ''Business Administration'', ''Software Engineering'', ''Management Information Systems Engineering'', ''Computer and Information Systems Engineering'' and Graduate Program is MBA. You can read more information about its history at this link https://international.netkentuni.net/about-us/history
=> Netkent University

lib/domains/edu/lssc/student.txt
https://www.lssc.edu/
https://www.lssc.edu/academics/associate/computer-science-transfer/
=> Add LSSC to approved domains

lib/domains/lv/id/gmbh/xtv.txt
Laipni lūgti Jelgava X Tālmācības Vidusskola, inovatīvā vispārizglītojošā vidusskolā Jelgavā, Latvijā. Mūsu “X” logotips simbolizē daudzveidīgu un atvērtu izglītības filozofiju, kuras mērķis ir attīstīt inovatīvas un starptautiski domājošas nākotnes paaudzes. Skola piedāvā vispusīgu un padziļinātu akadēmisko pieredzi, kuras pamatā ir datorzinātnes, apvienojot modernākās tehnoloģijas ar tradicionālajiem mācību priekšmetiem. Šeit skolēni apgūs jaunākās tehnoloģiskās zināšanas, attīstīs problēmu risināšanas prasmes un paplašinās savu redzesloku daudzkultūru vidē, apvienojot praktisko un teorētisko mācīšanos. Mēs ticam, ka katram skolēnam ir neierobežots potenciāls un ka Jelgava X Tālmācības Vidusskola ir atslēga uz viņu nākotnes atraisīšanu.
=> Add Jelgava X Tālmācības Vidusskola domain name

lib/domains/edu/ccbcmd.txt
https://ccbcmd.edu
https://www.ccbcmd.edu/Programs-and-Courses-Finder/Program/computer-science.html
https://ccbcmd.teamdynamix.com/TDClient/84/Portal/KB/ArticleDet?ID=1975
=> Add Community College of Baltimore County

lib/domains/de/goldberg-gymnasium/schueler.txt
Goldberg-Gymnasium Sindelfingen
[https://www.goldberg-gymnasium.de/](https://www.goldberg-gymnasium.de/)
=> Add Goldberg-Gymnasium Sindelfingen

lib/domains/edu/atlantic/buccaneer.txt
Additional information:
https://www.atlanticcape.edu/
Students emails are in the form [username@bucaneer.atlantic.edu](mailto:username@bucaneer.atlantic.edu)
Thank you for reviewing this request!
=> Added Atlantic Cape Student Email

lib/domains/ar/edu/uncaus.txt
- University official website URL:
[https://uncaus.edu.ar](https://uncaus.edu.ar)
- Long-term IT related course URL:
[Ingeniería en Sistemas de Información | Engineering in Information Systems](https://uncaus.edu.ar/index.php/component/sppagebuilder/?view=page&id=96)
- Students and teachers emails are in the form [username@uncaus.edu.ar](mailto:username@uncaus.edu.ar)
Thank you for reviewing this request!
=> Add uncaus.edu.ar domain

lib/domains/eg/edu/minianu/CAI.txt
adding CAI.minianu.edu.eg domain
=> adding CAI.minianu.edu.eg domain

lib/domains/bd/edu/uttarauniversity.txt
Adding file for Uttara University's domain.
=> Uttara University

lib/domains/edu/trcc/mymail.txt, lib/domains/edu/trcc/trcc.txt
Official Website - https://trcc.edu/
IT Program - https://trcc.edu/academics/degrees-programs/information-technology-specialist-2/
Email Domain Acknowledgement - https://trcc.edu/login-assistance/]
Removed trcc.edu.txt so the pull request only contains mymail.trcc.edu
=> add mymail.trcc.edu domain

lib/domains/ec/edu/delfos.txt
adding the Delfos Bilingual Private Educational Unit
=> Delfos Bilingual Private Educational Unit

lib/domains/ec/edu/delfos.txt
It is likely that I made a mistake when putting "private", it was not part of the name of the school, sorry for the inconvenience, something to take into account is: that the email format is different, it is usually est_example@delfos.edu.ec or est.example@delfos.edu.ec or example@delfos.edu.ec , check https://www.delfos.edu.ec/ , the school has agreements with others that also apply such as ECOTEC or ''ESPIRITU SANTO" both from Ecuador. Thank you for reading and reviewing this. 
<br>
-spanish-
es probable que me haya equivocado al momento de poner "private", no era parte del nombre del colegio, perdon por los incovenientes, algo a tomar en cuenta es: que el formato de correo es diferente, suele ser est_example@delfos.edu.ec o est.example@delfos.edu.ec or example@delfos.edu.ec , revisar …
=> Add delfos.edu.ec

lib/domains/tr/k12/ielev.txt
IELEV school added, you can access our school web site from this URL: https://www.ielev.k12.tr/en
=> IELEV school added

lib/domains/pl/edu/snc.txt
please add my college, thanks.
https://snc.edu.pl/technik-elektroniki-i-informatyki-medycznej.html
=> Medical School

lib/domains/il/co/tiltan.txt
Official website URL: https://www.tiltan.co.il/
[Game Design and Development course (Hebrew)](https://www.tiltan.co.il/%d7%90%d7%95%d7%93%d7%95%d7%aa/%d7%97%d7%96%d7%95%d7%9f-%d7%94%d7%9e%d7%9b%d7%9c%d7%9c%d7%94/%d7%97%d7%93%d7%a9%d7%95%d7%aa/%d7%91%d7%99%d7%aa-%d7%94%d7%a1%d7%a4%d7%a8-%d7%9c%d7%a4%d7%99%d7%aa%d7%95%d7%97-%d7%95%d7%a2%d7%99%d7%a6%d7%95%d7%91-%d7%9e%d7%a9%d7%97%d7%a7%d7%99%d7%9d-%d7%aa%d7%99%d7%9c%d7%aa%d7%9f-2-2/)
[Game Design and Development course (English)](https://www.tiltan.co.il/en/courses/school-of-game-design-and-development/)
The course is 3 years
=> Tiltan - College of Design and Visual Communication

lib/domains/me/jasukg.txt
Add a domain alias for your school.
=> Jalal-Abad State University

lib/domains/live/oshsu.txt
Add a domain alias for my school.
=> Osh State University

lib/domains/tech/unirsm.txt
Add a domain alias to my school.
=> University of San Marino

lib/domains/me/yuxify.txt
=> Kyrgyz National University

lib/domains/edu/sunybroome.txt
Attempting to add SUNY Broome Community College domain for @sunybroome.edu and subdomains.
=> Add lib/domains/edu/sunybroome.txt via upload

lib/domains/me/kbtu/email.txt
Add my university (Kazakh-British Technical University) domain alias to the list.
=> Add my university (Kazakh-British Technical University) domain alias to the list.

lib/domains/np/edu/divyagyan.txt
Divya Gyan College
https://www.divyagyan.edu.np/
=> Added Divya Gyan College (divyagyan.edu.np) to JetBrains SWOT

lib/domains/edu/escoffier/staff.txt
=> Adding Auguste Escoffier School of Culinary Arts

lib/domains/uk/ac/pursglove.txt
College Website: https://pursglove.ac.uk/
Computer Science Course: https://pursglove.ac.uk/16-19-courses/computer-science-asa-level/
=> Add Prior Pursglove College, pursglove.ac.uk

lib/domains/edu/indianatech.txt
Indiana Institute of Technology
=> Indiana Institute of Technology

lib/domains/top/umpsa.txt
Pls add the domain alias of my school.
=> Universiti Malaysia Pahang Al-Sultan Abdullah

lib/domains/edu/dcc.txt
Delgado Community College  (dcc.edu)
=> Delgado Community College

lib/domains/tech/upscmd.txt
Add the domain alias of my school.
=> State Pedagogical University of Chisinau

lib/domains/ro/cnmirceavl.txt
Colegiul National Mircea cel Batran Rm. Valcea, Romania; site: https://cnmirceavl.ro/
=> Add CNMBVL to Jetbrains list 

lib/domains/uk/org/foxespiece.txt
Apply to add a school domain name @foxespiece.org.uk
Address：Newfield Road, Marlow, Buckinghamshire, SL7 1JW
=> Foxes Piece School

lib/domains/vn/udn/sict/daotao.txt
Added university info for requesting free JetBrains licenses
=> Add School of Information and Communication Technology - The University of Danang

lib/domains/rs/edu/osboskovic.txt
Used by students of Rudjer Boskovic School (high school). https://osboskovic.edu.rs Student emails are given in the format of firstname.lastname@osboskovic.edu.rs
=> Add rudjer

lib/domains/ar/edu/colegiocolinasverdes.txt
Official domain for Colinas Verdes School :: https://www.colegiocolinasverdes.edu.ar/
-  We have computer science and more informatics subjects, we are in the process of starting to process programming as a subject.
=> Create colinas verdes school

lib/domains/edu/ntcc.txt
Add Northeast Texas Community College with email domain "@ntcc.edu" to the verified student emails list.
=> Add Northeast Texas Community College

lib/domains/org/wawmsd.txt
The website for the school is https://central.wawmsd.org/
=> West Allis Central High School

lib/domains/edu/stmartins.txt
https://www.stmartins.edu/
https://www.stmartins.edu/#computing
=> Saint Martin's Institute of Higher Education

lib/domains/net/bisdmail.txt
https://www.burlesonisd.net/Domain/1660
=> Adding new domain

lib/domains/edu/santarosa.txt
https://www.santarosa.edu/ => main school webpage
https://welcome.santarosa.edu/bearcubs-email => student email
https://catalog2024-2025.santarosa.edu/catalog-2024-2025/2024-2025-list-courses => current semester offerings
=> please add santarosa.edu

lib/domains/edu/uiwtx/student.txt
=> Add The University of the Incarnate Word

lib/domains/kr/ac/edu.txt, lib/domains/kr/ac/ok.txt
chungcheong university Korean name is 충청대학교
Please review Thk :)
=> Add chungcheong university Korean name

lib/domains/it/edu/iiscopernico.txt, lib/domains/it/iticopernico.txt
IIS N.Copernico A.Carpeggiani
Emilia Romagna - Ferrara - Italy
Website:
https://www.iiscopernico.edu.it/
Email domain:
iticopernico.it
Google Workspace
=> IIS N.Copernico A.Carpeggiani

lib/domains/co/simplon.txt
Simplon.co is a dev school located in Montreuil, France
=> Add simplon.co

lib/domains/edu/IC.txt, lib/domains/edu/llcc.txt
A page that mentions the email domain near the bottom under IT Information: https://www.llcc.edu/info/current-students
The list of computer science classes https://selfservice.llcc.edu/Student/Courses/Search?subjects=CSC . I'm not sure if this counts, but the combination of CSC 170 followed by CSC 270 is one year of Java-based programming.
=> Added llcc.txt

lib/domains/br/senai/cetiqt/educacao.txt
I would like to get my student permission for free Jet Brain developer tools such as Php Storm. However, when i tried to add my student email, it was shown that my University was not registered on the website. So i would like if my email @educacao.cetiqt.senai.br was added to the database so i can start using the developer tools. Thanks in advance.
=> add @educacao.cetiqt.senai.br school email

lib/domains/br/edu/domalberto.txt
ADD: Faculdade Dom Alberto from Santa Cruz do Sul/RS - Brazil.
=> ADD: Faculdade dom alberto

lib/domains/no/fhs/voss.txt
=> Voss Folkehøgskule

lib/domains/in/ac/gecrajkot.txt
Domain for Government Engineering College, Rajkot
College website:  https://gecrajkot.ac.in/
=> added my college domain

lib/domains/it/iismarconipieralisi.txt
Iscrizione del dominio iismarconipieralisi.it
=> Educational domain subscription

lib/domains/mx/tecnm/morelia.txt
Hello, I would like to add the university where I study so I can access to the different tools
=> Adding the Morelia Institute of Technology

lib/domains/eu/ebert-net.txt
Website: https://ebert-gymnasium.de/
Mailserver: https://ebert-net.eu/
=> Added Friedrich Ebert Gymnasium

lib/domains/pl/spolecznaczworka.txt
Website: https://liceum.spolecznaczworka.pl/
=> Added Liceum Społeczna Czwórka

lib/domains/kr/ac/anyang.txt
University name : Anyang University
University Domain : @gs.anyang.ac.kr
University URL : https://www.anyang.ac.kr/main/index.do
my email : M202357019@gs.anyang.ac.kr
My university is not in abuse, but it says my email is blocked. Please my email solve it
=> add Anyang University

lib/domains/es/lasallefelipebenito.txt, lib/domains/lasallefelipebenito.txt
=> new unregistered school

lib/domains/bd/ac/bsmmu.txt, lib/domains/bd/edu/bsmmu.txt
=> Add Bangabandhu Sheikh Mujib Medical University

lib/domains/tw/edu/ctbc.txt
This pull request adds CTBC Business School (中信金融管理學院) to the JetBrains/swot repository to recognize its academic domain ctbc.edu.tw. This inclusion will allow students and faculty members from CTBC Business School to access JetBrains educational benefits.
Changes:
Added ctbc.txt under swot/lib/domains/tw/edu/
Included both the Chinese and English names of the institution
Please let me know if any additional verification is required. Thank you! 🚀
=> Submitting a Pull Request to JetBrains/swot: Adding CTBC Business School

lib/domains/org/la-favorite/eleve.txt
I would like to add La Favorite school in order to benefit from JetBrain's products.
=> ajout la-favorite

lib/domains/in/ac/bitsathy.txt
Added Bannari Amman Institute of Technology
=> Added a college

lib/domains/edu/otis/student.txt
Added Otis College of Art and Design
=> Add Otis College of Art and Design

lib/domains/edu/highland.txt
Wanted to add the college I go to, most people use Visual studio (and I use Emacs), but these are some useful IDE's to have.
=> Adding Highland community college. 

lib/domains/pl/edu/t1piaseczno.txt, lib/domains/pl/zs1piaseczno.txt
The school's email domain has changed
=> Domain change

lib/domains/de/iserv-herderschule-giessen.txt
Hi JetBrains Team,
I'd be great if you could add the domain "iserv-herderschule-giessen.de".
Name of school: Herderschule Gießen
Official Website: https://www.herderschule-giessen.de/
The official website also links to the mentioned domain, which is used for the email addresses.
Thank you!
=> Add Herderschule Gießen

lib/domains/in/ac/sfit.txt
Smeet Rakesh Patil 
2nd Year 
Information Technology 
College PID: 231083
=> Added St. Francis Institute of Technology to lib/domains/in/ac

lib/domains/edu/isi.txt
ISI is an institute part of University of Southern California (https://www.isi.edu) but with a different domain.
=> Create isi.txt for ISI.edu

lib/domains/in/ac/hbtu.txt
https://hbtu.ac.in/
(Official Website)
https://erp.hbtu.ac.in/
(ERP Portal)
=> Add HBTU(hbtu.ac.in) to Indian University Domains

lib/domains/au/edu/kent.txt
The previous file was named student.txt and I am a lecturer and my email was not being recognized. So adding the file. URL: https://kent.edu.au/ . Course URL: https://kent.edu.au/bachelor-of-information-technology/ .
=> Add kent institute

lib/domains/kr/ac/chu.txt
Please, review my university and merge this,,,
Thank you :)
=> Add CHEJU HALLA UNIVERSITY

lib/domains/edu/sseriga.txt
Stockholm School of Economics in Riga
=> Added sseriga

lib/domains/in/ac/rguktn.txt
college website: [https://rguktn.ac.in](https://rguktn.ac.in)
=> config: added rgukut (iiit nuzvid) college

lib/domains/id/ac/poltera.txt
Politeknik Negeri Madura domain registration
=> Politeknik Negeri Madura

lib/domains/in/ac/cmrit.txt
added CMRIT college, Bangalore
=> Added new college "CMRIT Bangalore"

epiccharterschools.txt, lib/domains/org/epiccharterschools.txt
=> Pull request

lib/domains/org/mykolbe.txt
Kolbe Academy
Main School Page - https://kolbe.org
Domain Proof - https://help.kolbe.org/kb/article/26-mykolbe-microsoft-account-access/ 
Courses - https://courses.kolbe.org/
=> Kolbe Academy

lib/domains/pt/aluno.txt, lib/domains/pt/colegiomoderno.txt
This pull request contains a new school in Portugal called Colegio Moderno.
Information about the school can be seen here: https://colegiomoderno.pt/
The format of emails of students is as show: aXXXXX@aluno.colegiomoderno.pt
For teachers: NAME@prof.colegiomoderno.pt
Therefor the domains are "aluno.colegiomoderno.pt" and "prof.colegiomoderno.pt".
Best regards, fellow student from Colegio Moderno.
=> Please add this domain from the school "Colegio Moderno" in Portugal.

lib/domains/bo/edu/esam.txt
Official website URL: https://www.esam.edu.bo/
IT related course: https://www.esam.edu.bo/postgrado.php?post=5909
Proof showing that the domain is regognized: The official site and the students accounts have the same domain esam.edu.bo
=> adding esam.edu.bo ESAM

lib/domains/in/ac/iiitkota.txt
domain => 
long term Courses => https://iiitkota.ac.in/ug-procedure
=> add : add domain IIIT Kota

lib/domains/de/fichtenberg-oberschule.txt
The school uses this url for the website:
https://fichtenberg-oberschule.net/schulinformationen/unterichtsangebot/ (you can finde the available classes here)
and uses this url for emails:
fichtenberg-oberschule.de
=> add fichtenberg-oberschule.de

lib/domains/jm/edu/ucc/stu.txt
This pull request adds the generated school details file to the repository for JetBrains Products for Learning. The file was created using the provided form and has been unzipped and placed following the required directory structure. This change adheres to the repository rules for submitting school details and is part of the process to add my school to JetBrains for student licensing.
=> Add genrated file with proper directory structure

lib/domains/edu/aiias.txt
Website: https://www.aiias.edu
AIIAS offer an MBA program with Information Technology Emphasis where JetBrains tool are helpful, this is their site:
https://www.aiias.edu/academics/graduate-school/master-of-business-administration/
=> aiias.edu domain addition

lib/domains/au/edu/wesleycollege.txt
This file is to add Wesley College, Melbourne, Australia
=> Adding Wesley College, Melbourne, Australia

lib/domains/in/ac/nitap.txt
Adding National Institute of Technology, Arunachal Pradesh (https://www.nitap.ac.in)
=> Request to add NIT-AP (nitap.ac.in)

lib/domains/hk/edu/harrowschool.txt, lib/domains/hk/harrowschool.txt
Please add Harrow International School Hong Kong (after fix)
https://www.harrowhongkong.hk/his/
=> Harrow International School Hong Kong (Fix)

lib/domains/in/ac/iiitn.txt
=> Added Indian Institute of Information technology, Nagpur

lib/domains/in/ac/srmcem.txt
Shri Ramswaroop Memorial College of Engineering and Management, Lucknow Added
=> Add SRMCEM

lib/domains/in/ac/sharda/ug.txt
This is for Sharda University in Greater Noida, India.
Link for our B.Tech course that's for 4 years
https://www.sharda.ac.in/programmes/btech-computer-science/
This course will equip us with website, applications and database development.
=> Add Sharda University please

lib/domains/abused.txt, lib/domains/edu/nwfsc.txt
this is for 
Evanglical Theological Seminary in Cairo
link to our 3 years program that Has IT componants 
https://etsc.org/mml/
the program is designed to equip students withthe latest media tech and leadership skills
part of that is dealing with building websites
=> Add ETSC.ORG please

lib/domains/kz/wjfs.txt
West Kazakhstan University of Juridical and Fintech (site wjfs.kz)
=> Add West Kazakhstan Juridical and Fintech 

lib/domains/rs/edu/xku.txt
Сајт наше школе:
[1.pdf](https://github.com/user-attachments/files/18931709/1.pdf)
xku.edu.rs
Сајт курса:https://xku.edu.rs/2025/01/30/%d0%bf%d0%be%d1%87%d0%b5%d0%bb%d0%b8-%d1%81%d1%83-%d0%bf%d1%80%d0%b8%d1%98%d0%b5%d0%bc%d0%bd%d0%b8-%d0%b7%d0%b0-%d0%bf%d1%80%d0%be%d0%bb%d0%b5%d1%9b%d0%b5-2025-%d0%b3%d0%be%d0%b4%d0%b8%d0%bd%d0%b5/
Доказ о квалификацији：Види прилог 1.pdf,Ово је потврда о образовној квалификацији наше школе коју је издала званична владина агенција
=> Молимо додајте Универзитет науке и технологије Србије

lib/domains/de/berlin-international.txt
- University official URL - https://www.berlin-international.de/en/programs/
- Tech related Course - https://www.berlin-international.de/en/programs/data-science-and-business/
- Universities linkedin page - https://www.linkedin.com/school/berlininternational/about/
=> Add domain for berlin international uni

lib/domains/gh/edu/upsa.txt
**University website** => https://upsa.edu.gh/
**University IT faculty** -> https://upsa.edu.gh/academics/schools-and-faculties/itcs/
**University recognizes domain** => https://admissions.upsa.edu.gh/admissions/help-desk/
=> Add University of Professional Studies, Accra 

lib/domains/in/ac/iitdh.txt
=> Adding Missing IIT

lib/domains/org/lwshanghai.txt
{上海闵行区美高教育培训学校}
{Living Word Shanghai}
{http://www.lwshanghai.org/}
mohamed.elkomy@lwshanghai.org
=> add school: LW Shanghai

lib/domains/org/csd99.txt
Added Community School District 99 to the list of schools
=> Added CSD99.org (community school district 99)

lib/domains/in/ac/ietlucknow.txt
URL - https://www.ietlucknow.ac.in/
Computer Science Engineering Faculty - https://www.ietlucknow.ac.in/people/vkansal
=> Add IET Lucknow, India under AKTU

lib/domains/edu/claflin.txt
=> Add claflin.txt

lib/domains/in/ac/keck.txt
=> Please add our school keck

lib/domains/it/edu/iisfalcone-righi/studenti.txt
=> IISFalcone-Righi.txt

lib/domains/edu/millersville.txt
Added Millersville University of Pennsylvania to the list of educational domains.
=> Millersville University | Added Millersville Domain

lib/domains/in/ac/nitmanipur.txt
The official website of Nit Manipur is https://www.nitmanipur.ac.in/
This page is for  the programs offered in Computer Science and Engineering Department https://www.nitmanipur.ac.in/DisplayDeptPage.aspx?page=iq&ItemID=eo&nDeptID=k
Unfortunately the attached screenshot with the writing managed by nitmanipur.ac.in is the only  proof that i have with me.
=> Request to add NIT Manipur to JetBrians' swot list

friendsseminary.txt, lib/domains/org/friendsseminary.txt
Add Friends Seminary to lib/domains/org
=> Friends Seminary

lib/domains/ma/ac/enset-media.txt
https://www.enset-media.ac.ma/
=> Adding enset-media

lib/domains/br/edu/fapipinhais/cs.txt
The name of our course is Systems Analysis and Development.
Website — https://www.fapipinhais.edu.br/
Long term page URL, our course is 2 years (on the website it shows 4 semesters) — https://www.fapipinhais.edu.br/graduacao/analise-e-desenvolvimento-de-sistemas/
Image — At the end of the page, it shows your National Registry of Legal Entities and also your accreditation with the Brazilian Ministry of Education.
=> add FAPI - Centro Universitario de Pinhais

lib/domains/tn/ucar/fsegn.txt
this domain is for "Faculty of Economic Sciences and Management – University of Carthage – Nabeul -Tunisia " the faculty's web site is "https://fsegn.rnu.tn/fr", in the footer of the websit you could find the administration mail which is " fsegn.administration@fsegn.ucar.tn " . and yes it faculty of economic and management has a informatics course "business computing" 
hope that this could help and makes it easier to verify! Thanks again.
=> Please add this domain "@fsegn.ucar.tn" .. THANK YOU IN ADVANCE <3

lib/domains/ac/in/delhitechnicalcampus.txt
**URL - https://delhitechnicalcampus.ac.in/**
**Course - B.Tech 'CSE' (4 Years)**
=> Add delhitechnicalcampus.ac.in domain for Delhi Technical Campus

lib/domains/bd/edu/mmacademy.txt
please add this domain https://www.mmacademy.edu.bd for education fee license
=> https://www.mmacademy.edu.bd domain added

lib/domains/it/edu/convittonovara.txt
Add Liceo Scientifico to domains
=> Add Convitto Novara

lib/domains/nl/gymnasiumhilversum.txt
This is a high school: https://www.gymnasiumhilversum.nl/
The programming is in lesson(start programmeerklas): https://www.gymnasiumhilversum.nl/storage/file/51b2f398-e9f8-42c6-a78e-1357c86bfde9/aristoteles_programma_per_leerjaar_v2-(1).pdf
=> Adding gymnasiumhilversum

lib/domains/in/ac/nits/ee.txt
Added files for National Institute of Technology Silchar, Department of Electrical Engineering
=> Added EE, NIT Silchar

lib/domains/in/bvcgroup.txt
Checkout: [1], [2]
[1]: https://bvcec.edu.in/contact-us/
[2]: https://bvcec.edu.in/
=> Add BVC Engineering College

lib/domains/in/ac/iiitmanipur.txt
Hello ,
My name is kesari devaraya i am a student from Indian Institute of Information Technology I am requesting free access to pyCharm Professional edition
=> requesting free pycharm access for iiitm collage

lib/domains/de/hamburg/fifa.txt
Please add our School "Stadtteilschule Fischbek-Falkenberg" in Hamburg, Germany as a new domain 
(Our School-Web-Site: fifa.hamburg.de). - Thank You!
=> Add files via upload - New School Domain

lib/domains/ac/in/iimraipur.txt, lib/domains/in/ac/iimraipur.txt
Adding IIM Raipur domain for any CS related projects
=> IIM Raipur domain

lib/domains/bd/edu/bau.txt
Institution Name:
**Bangladesh Agricultural University**
Official Website URL:
https://bau.edu.bd
IT-related Faculty/Department Website URLs:
1. https://aet.bau.edu.bd (Faculty of Agricultural Engineering & Technology)
2. https://csm.bau.edu.bd (Dept. of Computer Science and Mathematics)
3. https://stat.bau.edu.bd (Dept. of Agricultural and Applied Statistics)
4. https://bie.bau.edu.bd (Dept. of Bioinformatics Engineering)
Bangladesh Agricultural University (BAU), established in 1961, is one of the leading agricultural universities in South Asia. It has over 5,000 undergraduate students and nearly 3,000 postgraduate students enrolled in BSc (Hons), Master's, and PhD programs. While primarily focused on agriculture, BAU integrates information technology into agricultural studies, fostering …
=> Add bau.edu.bd

lib/domains/nz/school/sacredheart/students.txt
https://www.sacredheart.school.nz/
=> Add Sacredheart college

lib/domains/kr/seoultech.txt
it just add lower case
my email is ~~@seoultech.ac.kr but it isn't checked so i added it.
please review and if it is good merge please.
Thank you :>
=> Add seoultech

lib/domains/ro/ltmeliade.txt
Presentation: https://ltmeliade.ro/oferta-educa-ional-.html & Departments: https://ltmeliade.ro/matematic--informatic-.html
Please, use Google Translate or any other tool for this job. Sadly, my school is not supporting international readers :(
=> Add Theoretical Highschool "Mircea Eliade"

lib/domains/pe/edu/upn.txt
=> Add University calls Universidad Privada del Norte

lib/domains/in/edu/chitkarauniversity.txt
1. **University Name:** Chitkara University  
2. **University’s Website:** [https://www.chitkarauniversity.edu.in/](https://www.chitkarauniversity.edu.in/)  
3. **IT-Related Course Page (Computer Science Stream):**  
- **Computer Science & Engineering (CSE):** [https://www.chitkarauniversity.edu.in/cse/](https://www.chitkarauniversity.edu.in/cse/)  
- **Bachelor in Computer Applications (BCA):** [https://www.chitkarauniversity.edu.in/bachelor-of-computer-application-bca/](https://www.chitkarauniversity.edu.in/bachelor-of-computer-application-bca/)  
4. **Official Student Email Proof:**  
- Screenshot from the official student portal showing a valid student email with the domain `@chitkarauniversity.edu.in`.  
- This submission is for **Chitkara University, Himachal Pradesh campus**. …
=> Added Chitkara University Himachal Pradesh domain for student verification

lib/domains/in/ac/iiitsonepat.txt
Summary
This pull request adds IIIT Sonepat (iiitsonepat.ac.in) to the JetBrains swot repository, allowing students to access JetBrains' free educational licenses.
Details
Institution Name: Indian Institute of Information Technology, Sonepat
Domain: iiitsonepat.ac.in
Official Website: https://iiitsonepat.ac.in/
Eligibility: IIIT Sonepat offers long-term IT-related courses, including Computer Science and Engineering.
Domain File Path: lib/domains/in/ac/iiitsonepat.txt
Why This Change?
Adding this domain will enable students from IIIT Sonepat to apply for free JetBrains educational licenses, benefiting their academic and research work.
=> Add IIIT Sonepat , India

lib/domains/in/edu/bmu.txt
1. Offical website - https://www.bmu.edu.in/ 2.school of Engineering (IT or computer science)
https://www.bmu.edu.in/courses/b-tech/b-tech-computer-science-engineering/
3. Screenshot attached below
=> Bml munjal university

lib/domains/bd/ac/hstu.txt
Domain file for Hajee Mohammad Danesh Science and Technology University (HSTU), Dinajpur, Bangladesh is added.
=> Domain file for HSTU is added - please approve this new domain

lib/domains/edu/htu.txt
Please add Huston-Tillotson University to edu domain list
=> Adding Huston-Tillotson University to edu domain list

lib/domains/bd/ac/aub.txt
Please Add Asian University of Bangladesh
=> Please Add Asian University of Bangladesh 

lib/domains/pl/poznan/lo4/edu.txt
=> Add IV Liceum Ogólnokształcące im. Komisji Edukacji Narodowej

lib/domains/in/ac/cus.txt
Adding Central University of Sikkim on behalf of arprakash@cus.ac.in (Assistant Professor Department of Management CUS)
=> Created entry for Central University of Sikkim

lib/domains/uk/ac/rncm.txt
[https://www.rncm.ac.uk](url)
[https://www.rncm.ac.uk/research/research-activity/research-centres-rncm/prism/prism-teaching/](url)
[https://www.rncm.ac.uk/people/bofan-ma/](url)
=> Added Royal Northern College of Music (RNCM) / @rncm.ac.uk

lib/domains/net/jksmail.txt
School Name: Jeddah Knowledge International School
Official Website: https://www.jks.edu.sa
IT-Related Courses (Confirmed in the Upper School Handbook 2024-25): https://jksportal.net/sites/default/files/files/PS%20Handbook%20Upper%202024-25.pdf (taken from page 68-69)
Software Development (Grade 12 Boys, 1 year, 1 credit) - "This course includes a practical and theory component and a quarterly exam. Students will be introduced to the survey of current mobile platforms, mobile application development environments, mobile device input methods, as well as application development. Students will design and build a variety of applications (apps) for daily use."
Digital Media and Film Studies (Grade 11-12 Boys, 2 years, 1 credit) - "This course offers students an introduction into videography, …
=> Adding jksmail.net domain for Jeddah Knowledge International School students

lib/domains/in/ac/zhcet.txt
Add my college to known domains.
=> Add Zakir Husain College of Engineering and Technology to lib.

lib/domains/br/com/alunomelies.txt
Faculdade Méliès
[Faculdade Méliès - Website](https://melies.com/)
=> Add Faculdade Melies

lib/domains/ci/edu/ena.txt
Add a domain alias for my school.
=> Ecole Nationale d'Administration

lib/domains/dk/rg/rgnet.txt
Computer Science at Rødovre High School
=> Rødovre Gymnasium

lib/domains/mrsdmail.txt, lib/domains/org/mrsdmail.txt
Application of Masconomet Regional High School for JetBrains Products for Learning.
=> Add Masconomet Regional High School

lib/domains/org/istitutodionigiscano.txt
Create file istitutodionigiscano.txt in lib/domains/org/
=> Create file istitutodionigiscano.txt

lib/domains/de/fgs-bln.txt
Added file for Friedenauer Gemeinschaftsschule Berlin.
=> Added fgs-bln.txt

lib/domains/ua/zp/vybor.txt
=> add ua.zp.vybor new domain

lib/domains/br/com/colegionovo.txt
www.colegionovo.com.br
Colégio novo de Araguari. 
New College, of Araguari, Minas Gerais, Brazil
=> Add Domain colegionovo.com.br

lib/domains/in/edu/aec.txt
* Aditya Engineering College, which is Aditya University
- Address: Aditya Nagar, ADB Road, Surampalem, Andhra Pradesh - Pin:533437
- Domain: https://aec.edu.in/
=> Adding Aditya Engineering College, Which is Aditya University

lib/domains/in/edu/heritageit.txt
Institute website - https://www.heritageit.edu/
Page showing Computer Science Degree - https://www.heritageit.edu/CSE.aspx
=> Adding Heritage Institute of Technology

lib/domains/ph/edu/kcast.txt
=> kcast school

lib/domains/kg/edu/msu/stu.txt
Please add a domain name for my school, thank you.
The school's official website is https://www.msu.edu
=> Adding MSU

lib/domains/edu/binghamton.txt
https://www.binghamton.edu/computer-science/index.html
https://www.binghamton.edu/computer-science/people/
=> Binghamton University

lib/domains/org/kbtcoe.txt
Domain request for `@kbtcoe.org`
My email: `desaiprasad@kbtcoe.org`
- university official website => https://kbtcoe.org/
- more than 1 years (>1) => https://kbtcoe.org/computer-department/
- university domain proof (contact us email domain) => https://kbtcoe.org/contact-us/
=> KBTCOE DOMAIN REQUEST

lib/domains/bd/ac/nu.txt
I have added National University, Bangladesh to the list.
=> National University, Bangladesh added to the list

lib/domains/ch/santiskurs.txt, lib/domains/ch/santismail.ch, lib/domains/ch/santismail.txt
Second attempt, after wrong filenames last time
=> Student and Trainer Domains at SANTIS Training AG

lib/domains/edu/pointpark.txt
=> pointpark.edu

lib/domains/bzh/assomption.txt
[Official high school website](https://www.essfa.fr/college-lycee-prepa-assomption/)
[Informations on the course](https://www.essfa.fr/college-lycee-prepa-assomption/vie-de-letablissement/informations-pratiques/)
=> Add Collège, Lycée, Prépa Assomption (assomption.bzh)

lib/domains/es/formacionchios.txt
Add Center Formacion Chios A Coruña
=> Add Formacion Chios

file/lib/domains/id/sch/ibnutaimiyah.txt, lib/domains/id/sch/ibnutaimiyah.txt
please help to include my school Ibnu Taimiyah Islamic Boarding School to use JetBrains Freely, tq
=> please help to include my school Ibnu Taimiyah Islamic Boarding School to use JetBrains Freely, tq

lib/domains/py/edu/campoalto.txt
Adding Campoalto High School to the domain list
=> Adding Colegio Campoalto to the domain list

lib/domains/np/edu/adhyayan.txt
Added Adhyayan School to the list of known institutions.
School website  https://adhyayan.edu.np/
=> Add Adhyayan School

lib/domains/vn/edu/naem.txt
The purpose of this change is to add a new field to the JetBrains Education project, enhancing its functionality and flexibility.
=> Add new field to education project

lib/domains/nl/ichthuscollege.txt
Add Ichthus college to JetBrains
=> add Ichthus college

lib/domains/bd/ac/cstu.txt
This PR adds Chandpur Science and Technology University (CSTU) to the JetBrains SWOT repository. The university's official domain is cstu.ac.bd, and students use email addresses in the format @student.cstu.ac.bd.
University Name: Chandpur Science and Technology University (CSTU)
Domain: cstu.ac.bd
Student Email Format: @student.cstu.ac.bd
Website: https://cstu.ac.bd/
=> Added Chandpur Science and Technology University (CSTU) domain

lib/domains/edu/ied.txt
https://www.ied.edu/
Long-term IT related course offered by the university:
https://www.ied.edu/courses/rome/three-years-diploma/media-design
Proof showing that the university recognizes the domain as an official email domain for the enrolled students:
Please remove this screen capture after the PR is accepted :)
=> Add Istituto Europeo di Design italian university

lib/domains/hu/dng-bp.txt
Upload base domain file due to school registration.
School's website: https://www.dng-bp.hu/
=> Upload dng-bp.txt file

lib/domains/ro/liceultonitza.txt
Email pattern is @liceultonitza.ro
Website domain is https://www.liceultonitza.ro/
=> add liceultonitza.txt

lib/domains/ro/isb.txt
Despite the fact that International School of Bucharest is a secondary school, every Computer Science student must create a project using a modern IDE as part of their course requirement. So I highly request a professional version of the product rather than a comment version.
www.isb..ro
=> domain added for International School of Bucharest

lib/domains/kw/edu/dbs.txt
please add Dasman Bilingual School to your repository
=> Dasman Bilengual School:

lib/domains/org/hcrhs.txt
email domain: hcrhs.org
website domain: hcrhs.org
Proof of domain:
Staff registry (witch uses hcrhs.org domain): https://www.hcrhs.org/contact-information/search-new
=> added school HCRHS

lib/domains/edu/WalshCollege.txt
HI
I am student of Walsh College  with id :  XXXX@mail.walshcollege.edu 
I am trying to add Walsh college in list
=> Adding "Walsh College" under edu domain

lib/domains/org/smmacademy.txt
The name of the sixth form I attend at N7 8pg
=> Add smmacademy.txt file via upload

lib/domains/mk/edu/vision.txt
I created a JetBrains login for the students of International Vision University to benefit from.
=> Add vision statement for International Vision University

lib/domains/edu/buffalostate.txt
Added (SUNY) Buffalo State University.
https://suny.buffalostate.edu/
=> Add Buffalo State University

lib/domains/nl/andreascollege.txt
website is https://www.andreascollege.nl/
with schools:
- Pieter Groen https://www.pietergroen.nl/
- Rijnmond vakcollegerijnmond.nl 
- Limes https://limes-katwijk.nl/
^Proof for use of email.
=> new file:   lib/domains/nl/andreascollege.txt

lib/domains/se/herrljunga/skola.txt
Here is their website (in swedish, since they dont provide a english one): https://kunskapskallan.se/
=> Added kunskapskällan's mail domain

lib/domains/vn/edu/saidiait.txt
domain: saidiait.edu.vn
website: https://saidiait.edu.vn/
=> Add information Saidia University of Vietnam

lib/domains/edu/ossm.txt
Add file for the Oklahoma School of Science and Mathematics
=> Add ossm.txt

lib/domains/kr/itc.txt
it's just an additional Korean name
Please reivew, and if everything looks good, merge please
Thank you :)
=> Add Inha Technical College

lib/domains/edu/wheaton.txt
**Additional Info:**
- **the university official website URL, if it is different from the domain you are submitting**
- https://wheaton.edu 
- _(same as domain being submitted)_
- **a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university**
- https://www.wheaton.edu/academics/programs/computer-science/
- **a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.**
- ![sc 2025-03-25 at 12 04 08 PM](https://github.com/user-attachments/assets/6c7b510e-f343-49cb-9065-8ed127f944f2)
- _Student emails are @my.wheaton.edu, faculty emails are @wheaton.edu_
=> Add Wheaton College, IL to domains

lib/domains/id/ac/polibatam.txt
This PR adds Politeknik Negeri Batam (Polibatam) to the JetBrains SWOT repository.
- Institution Native Name : Politeknik Negeri Batam
- Institution English Name : Batam State Polytechnic
- Main Website : https://www.polibatam.ac.id
- IT Course / Sylabus : https://www.polibatam.ac.id/wp-content/uploads/2022/02/Silabus-Publish-Teknologi-Rekayasa-Perangkat-Lunak.pdf#page=5
- Official Email Domain : @polibatam.ac.id
This institution offers various IT-related courses, including Software Engineering, Informatics, and Computer Engineering.
Thank you
=> Add new domain to Politeknik Negeri Batam

lib/domains/school/csb.txt, lib/domains/school/csb/student.txt
Hello,
I suggest to add the CSB.School to the list of schools.
Official website URL: https://www.csb.school/
Dev course are available here: https://www.csb.school/formations/cyberprepa/
Thanks!
=> Add CSB.SCHOOL to the list of domains

lib/domains/tj/tnu.txt
This commit introduces a new domain file at lib/domains/tj/edu/tnu.txt for Tajik National University. The file includes the institution's official names:
- "Донишгоҳи миллии Тоҷикистон"
- "Tajik National University"
Verification details:
• Official Website: https://tnu.tj/index.php/en/main/
• Contact Information: https://tnu.tj/index.php/en/contacts/
This addition meets the criteria for the JetBrains SWoT repository by confirming that:
• The university offers long-term (>1 year) IT-related courses
=> Add domain for Tajik National University (tnu.tj)

lib/domains/dz/enset-skikda.txt
adding the ENSET Skikda domain
=> ENSET Skikda

lib/domains/net/ichthuscollege.txt
the .nl was accepted that is te website domain(that is my fault submitting the wrong domain) but the email domain is .net
=> add Ichthuscollege.net

lib/domains/dz/univ-djelfa/mail.txt
Ziane Achour University of Djelfa
Ziane Achour University of Djelfa
=> added Support for University  Djelfa Ziane Achour

lib/domains/edu/cecil.txt
Cecil College, North East, MD, USA
=> Add Cecil College

lib/domains/edu/osumc.txt
We use osumc.edu for our email, as seen in the department chair page 
https://medicine.osu.edu/find-faculty/clinical/internal-medicine/rama-mallampalli-md
=> Adding Ohio state university - college of medicine

lib/domains/org/axiscolleges.txt
Adding Axis Institute of Technology and Management to the JetBrains Student Verification system.
=> Added Axis Institute of Technology and Management

lib/domains/iq/edu/mtu.txt
https://eetc.mtu.edu.iq/com-dep/
https://mtu.edu.iq/
=> Middle Technical University

lib/domains/kr/ac/stu.txt
It's an additional Jeju International University student name.
I hope there isn't problem, Please review and merge.
Thank you.
=> Add Jeju International University

lib/domains/co/edu/udes.txt
Greetings from Colombia
The university is present in 4 cities in the country: bogota, valledupar, bucaramanga and cucuta
Domain: [udes.edu.co](https://udes.edu.co/)
It offers three Bachelor's degrees of 5 years, [software engineering ](https://bucaramanga.udes.edu.co/estudia/pregrados/ingenieria-de-software) (also virtual, [engineering in computer science and artificial intelligence](https://bucaramanga.udes.edu.co/estudia/pregrados/ingenieria-en-ciencias-de-la-computacion-e-inteligencia-artificial) and [systems engineering](https://cucuta.udes.edu.co/estudia/pregrados/ingenieria-de-sistemas-cuc) 
The Universidad de Santander was present in the previous archived repository.
=> feat: added universidad de santander

lib/domains/kr/ac/songwon/office.txt
=> https://www.songwon.ac.kr/

lib/domains/de/iservigs-embsen.txt
An add of the school: IGS Embsen with the email extension: iservigs-embsen.de
=> Iservigs-embsen Add

lib/domains/kr/ac/stu.txt
It's real Name of Jeju National University.
Please review and merge, if there is not problem.
Thank you.
=> Add Jeju National University

lib/domains/edu/nhcc.txt
Added North Hennepin Community College
=> adding North Hennepin Community College

lib/domains/bd/edu/dpsc.txt
please accept the request for free education pack for "Dwood public school and college, Jashore cantonment"
=> Dwood public school and college added for Jetbrains free education pack

lib/domains/pl/edu/zseeim.txt
Adding Zespół Szkół Elektronicznych, Elektrycznych i Mechanicznych to JetBrains educational program.
=> Add zseeim.edu.pl

lib/domains/edu/monmouthcollege.txt
[Official URL](https://www.monmouthcollege.edu/)
[Computer Science program](https://www.monmouthcollege.edu/academics/computer-science/)
=> adding monmouth college

lib/domains/ar/edu/ifts18.txt
https://www.ifts18.edu.ar/home
=> Add ifts18

lib/domains/ro/britishschool.txt
British School of Bucharest
https://britishschool.ro/
student@bsbonline.net
teacher@britishschool.ro
=> Add British School of Bucharest to Jetbrains Pycharm Access

lib/domains/gh/edu/accramet.txt
Added Accra Metropolitan University
=> Added Accra Metropolitan University

lib/domains/mx/edu/cbtis156.txt
This is a request to add the cbtis156.edu.mx school domain from Mexico to the list.
=> Added: cbtis156.txt for domain cbtis.edu.mx

lib/domains/bd/ac/prstu/cse.txt
Add files from Pirojpur Science and Technology University
Official website of the University: https://prstu.ac.bd
=> Add Pirojpur Science and Technology University (prstu.ac.bd)

lib/domains/ec/edu/istcarloscisneros.txt
=> istcarloscisneros

lib/domains/ug/ac/unik.txt
Added files from the University of Kisubi
=>  Added files from the University of Kisubi

lib/domains/edu/yccc.txt
Long term degree/ course infomation can be found at [](https://www.yccc.edu/degree/information-technology-aas/)
=> Add yccc.edu

lib/domains/cl/cftpucv.txt
- https://cftpucv.cl/
- https://cftpucv.cl/carreras-por-area/area-administracion-negocios/tns-en-computacion-e-informatica/
=> Add cftpucv

lib/domains/bo/edu/uap.txt
_Estimado equipo de JetBrains,_
Mi nombre es **Alex Yanahuaya Arce** , soy estudiante de la Universidad Amazónica de Pando, ubicada en la región amazónica, en el departamento de Pando, Bolivia. Estoy interesado en acceder a las herramientas educativas que JetBrains proporciona, ya que serían de gran apoyo para mi desarrollo académico y profesional.
He completado los pasos necesarios para generar un archivo con los detalles de mi universidad según las instrucciones proporcionadas, y lo he añadido a mi bifurcación del repositorio en GitHub, respetando la estructura y requisitos establecidos.
Por la presente, solicito amablemente que la Universidad Amazónica de Pando sea incluida en la lista de universidades admitidas para aprovechar las licencias educativas de JetBrains. La información …
=> **Asunto:**  Solicitud para añadir la Universidad Amazónica de Pando a la lista de universidades admitidas

lib/domains/br/edu/famef.txt
Dear JetBrains Team,
I would like to request the inclusion of the educational domain for **Faculdade Metropolitana São Mateus (FAMEF)** in the list of recognized institutions eligible for educational licenses.
- **Official university website:** [FAMEF](https://www.famef.edu.br/)
- **Long-term IT-related course (>1 year):** [Artificial Intelligence and Educational Technologies](https://www.famef.edu.br/curso-pos-ead/1507/)
- **Proof of official email domain:** The domain is mentioned on the institution’s contact page ([Contact Us](https://www.famef.edu.br/fale-conosco/)). If needed, I can provide a screenshot or additional document.
I appreciate your review and look forward to your response! 🚀
Best regards,  
Peterson
=> Request for Educational Domain Inclusion FAMEF

lib/domains/lv/lbtu.txt
Adding lbtu.lv domain for Latvia University of Life Sciences and Technologies (LBTU) to support JetBrains student license verification.
=> Add LBTU domain for student license request

lib/domains/ca/hwcdsb.txt
=> Add HWCDSB school boardAdd files via upload

lib/domains/br/einstein.txt
Albert Einstein is the best hospital in Latin America, as ranked by the News Week Best Hospitals (https://rankings.newsweek.com/worlds-best-hospitals-2025). It's health sciences college is among the best in Brazil and leads in academic production. It offers a myriad of data science related courses with a focous on health data.
https://ensino.einstein.br/Big%20Data?O=OrderByScoreDESC%26PS%3D9%26map%3DspecificationFilter_251
=> Adds einstein.br to the domain linst

lib/domains/de/gs-wn.txt
Gewerbliche Schule Waiblingen **(https://www.gswn.de/)**
Technisches Gymnasium Waiblingen **(https://www.gswn.de/gymnasium-berufskolleg/gymnasium)**
3-years IT course **(Informationstechnik)**
=> feat: added gs-wn.txt

lib/domains/bd/edu/fcub.txt
This pull request includes a small change to the `lib/domains/bd/edu/fcub.txt` file. The change adds the name of a new university.
* [`lib/domains/bd/edu/fcub.txt`](diffhunk://#diff-d8d1ef3d8302b33aef3b4b7340fe904f72790e9648572b41a5910020e645da6cR1): Added "First Capital University of Bangladesh".
=> Add First Capital University of Bangladesh

lib/domains/bd/edu/sss.txt
This pull request includes a small change to the `lib/domains/bd/edu/sss.txt` file. The change adds the name of a school in both Bengali and English.
=> Add Samonta High School for domain verification

lib/domains/do/edu/intec.txt
Dear JetBrains Team,
I hope you’re doing well.
I would like to kindly request that the email domain @intec.edu.do, which belongs to Instituto Tecnológico de Santo Domingo (INTEC) in the Dominican Republic, be added to your list of approved domains for JetBrains educational licenses—specifically for faculty and teaching staff.
INTEC is one of the country’s leading institutions in science, technology, and engineering education. Providing access to JetBrains tools for professors using this domain would significantly support their teaching efforts and improve the academic experience for students.
University Website: https://www.intec.edu.do/
Allowed Domain: @intec.edu.do
I have seen another pull request regarding the student domain (@est.intec.edu.do). This request, however, specifically …
=> Request to Allow @intec.edu.do Domain for JetBrains Educational Licenses

lib/domains/edu/southalabama.txt
School of Computing programs can be found at: https://www.southalabama.edu/colleges/soc/
=> Request to add EDU domain

lib/domains/edu/gallaudet.txt
University official website: https://gallaudet.edu/
This university has IT programs: https://gallaudet.edu/information-technology/
=> Add Gallaudet University

lib/domains/vn/edu/hathitrannhien.txt
High School
http://thptvovankietkg.edu.vn/
=> Vo Van Kiet High School

lib/domains/dz/ensti-annaba.txt, lib/domains/dz/esti-annaba.txt
Hello,
Our institution has changed its name:
Old name: École Supérieure de Technologies Industrielles d'Annaba  
New name: École Nationale Supérieure de Technologie et d'Ingénierie d'Annaba
As a result, the domain has changed from esti-annaba.dz to ensti-annaba.dz.
I would like to update this accordingly.
=> Update and rename esti-annaba.txt to ensti-annaba.txt

lib/domains/pe/edu/roncalli.txt
ADD Instituto Roncalli del Peru
https://www.roncalli.edu.pe/
=> roncalli.edu.pe

lib/domains/cl/ecas.txt
Adding ECAS Training School of Chile
=> ECAS Training School of Chile

lib/domains/kr/ac/kyuh.txt
Konyang university "건양대학교"
URL: https://www.konyang.ac.kr/
=> Add Konyang university

lib/domains/edu/nyfa.txt, lib/domains/edu/nyfa/student.txt
Added **New York Film Academy** (United States)
Academy Website: [https://www.nyfa.edu/](https://www.nyfa.edu/)
=> Add New York Film Academy (NYFA) domain

lib/domains/mv/edu/dharuma.txt
Add Dharumavantha School domain
=> Add Dharumavantha School

lib/domains/gr/edu/parvis.txt
Add school:  Parvis Exeter Academy
=> Add school:  Parvis Exeter Academy

lib/domains/edu/leeu.txt
=> Add files vAdd leeu.edu domainia upload

lib/domains/mw/ac/must.txt
=> Add: added new home school

lib/domains/uk/ac/ucb.txt
Added University College Birmingham.
=> Added University College Birmingham

lib/domains/tw/edu/tn/yrhs.txt
School name (Traditional Chinese): 臺南市立永仁高級中學  
Domain: yrhs.tn.edu.tw  
Website: https://www.yrhs.tn.edu.tw
This school provides official student email addresses (e.g., s112052@yrhs.tn.edu.tw).  
Although I may currently be the only applicant, students from this high school could benefit from JetBrains educational tools.
=> Add yrhs.tn.edu.tw domain for JetBrains student license

lib/domains/kr/ac/koreait.txt
=> add: add koreait domain

lib/domains/edu/villa.txt
I am attempting to add Villa Maria College to the list of schools for the educational bundle of Rider. The institution has a degree for Game Design and a educational key would be beneficial to the students.
=> Requesting to add a school

lib/domains/ua/org/uhmi.txt
Added Ukrainian Hydrometeorological Institute to the list of educational institutions eligible for JetBrains educational license.
Website: https://uhmi.org.ua  
Email domain: uhmi.org.ua  
Focus: Hydrology, Meteorology, Climate Research, with long-term scientific training and IT-based modeling (Python, GIS, etc.)
=> Add UHMI domain for JetBrains educational license

lib/domains/edu/bluecc/my.txt
Pull request for adding Blue Mountain Community College to the education license program
=> Create Blue Mountain Community College

lib/domains/br/edu/unig.txt, lib/domains/br/edu/unig/aluno.txt
- official website url university: https://unig.br/
- IT courses related 
- https://unig.br/cursos-de-graduacao-presencial-e-semipresencial/ciencia-da-computacao/
- https://unig.br/cursos-de-graduacao-presencial-e-semipresencial/analise-e-desenvolvimento-de-sistemas/
proof of domain university
=> request to aluno.unig.edu.br

lib/domains/es/uf3ceu.txt
Universidad CEU Fernando III
Digital Tech Faculty - [https://uf3ceu.es/estudios/master/master-derecho-tecnologico-digital/](https://uf3ceu.es/estudios/master/master-derecho-tecnologico-digital/)
=> Add Universidad CEU Fernando III

lib/domains/org/golapolytechnic.txt
Gola Polytechnic School
Computer Science Diploma & Degree [https://golapolytechnic.org/diploma-in-computer-science-engineering/](https://golapolytechnic.org/diploma-in-computer-science-engineering/)
=> Add Gola Polytechnic School

lib/domains/edu/kansascity.txt
Kansas City University
Computer Programming for Bioinformatics & Algorithms and Development for Bioinformatics
[https://www.kansascity.edu/programs/college-of-biosciences/curriculum](https://www.kansascity.edu/programs/college-of-biosciences/curriculum)
=> Add Kansas City University

lib/domains/eu/escp.txt
ESCP Business School
Science programmes - [https://escp.eu/programmes/specialised-masters-MSc](https://escp.eu/programmes/specialised-masters-MSc)
=> Add ESCP Business School

lib/domains/be/sgr20/leerkracht.txt
Original PR can be found here https://github.com/JetBrains/swot/pull/16478 
Add's the teacher email
=> Addition to PR !16478

lib/domains/com/desheng-school.txt
School domain: [Desheng School (International)](http://www.desheng-school.com) [Desheng School](http://www.desheng-school.cn)
=> Add Desheng School

lib/domains/edu/judsonu/student.txt
Added student support subscription for Judson University
=> Add Judson University

lib/domains/edu/dsdt.txt
Detroit School Of Technology
Full-stack Developer Program - [https://dsdt.edu/programs/full-stack-developer-program/](https://dsdt.edu/programs/full-stack-developer-program/)
=> Add Detroit School Of Technology

lib/domains/edu/nmc.txt
Northwestern Michigan College
Computer Science Courses - [https://catalog.nmc.edu/course-descriptions/cit/](https://catalog.nmc.edu/course-descriptions/cit/)
=> Add Northwestern Michigan College

lib/domains/edu/upike.txt
University Of Pikeville
IT Specialty, Scripting and Programming - [https://www.upike.edu/programs/information-technology-mgmt/](https://www.upike.edu/programs/information-technology-mgmt/)
=> Add University Of Pikeville

lib/domains/org/dsatulsa.txt
Dove Science Academy Tulsa
STEM academics - [https://www.dsatulsa.org/academics/stem](https://www.dsatulsa.org/academics/stem)
=> Add Dove Science Academy Tulsa

lib/domains/org/jeppiaarcollege.txt
Jeppiar Engineering College
Computer Science and Engineering faculty - [https://jeppiaarcollege.org/jeppiaar/cse/](https://jeppiaarcollege.org/jeppiaar/cse/)
=> Add Jeppiar Engineering College

lib/domains/edu/northcentralcollege.txt
North Central College
Computer Science faculty - [https://www.northcentralcollege.edu/program/computer-science](https://www.northcentralcollege.edu/program/computer-science)
=> Add North Central College

lib/domains/edu/stonehill.txt
Stonehill College
Computer Science Programs - [https://www.stonehill.edu/programs/computer-science/](https://www.stonehill.edu/programs/computer-science/)
=> Add Stonehill College

lib/domains/org/dpsindore/student.txt
Delhi Public School (DPS) Indore, a leading educational institution in Madhya Pradesh.
Affiliated with the prestigious Delhi Public School Society, the school provides comprehensive education from Nursery to Class XII. Please find website [https://dpsindore.org](https://dpsindore.org)
=> Added DPS Indore School

lib/domains/np/edu/nast.txt
Please verify i have added the Nast college in the domain nast.edu.np
=> nast.edu.np domain add

lib/domains/pe/edu/iestpmotupe.txt
official website: https://iestpmotupe.edu.pe/
[MALLA CURRICULAR.pdf](https://github.com/user-attachments/files/19930325/MALLA.CURRICULAR.pdf)
=> add INSTITUTO DE EDUCACIÓN SUPERIOR TECNOLÓGICO PÚBLICO MOTUPE

lib/domains/edu/germanna.txt
Germanna Community College
Science, Technology, Engineering, & Mathematics academics - [https://germanna.edu/degrees-programs/science-technology-engineering-mathematics](https://germanna.edu/degrees-programs/science-technology-engineering-mathematics)
=> Add Germanna Community College

lib/domains/edu/rtc.txt
Renton Technical College
IT academics - [https://rtc.edu/academics/areas-of-study/information-technology/index.php](https://rtc.edu/academics/areas-of-study/information-technology/index.php)
=> Add Renton Technical College

lib/domains/edu/bridgevalley.txt
BridgeValley Community and Technical College
Computer Science Program - [https://www.bridgevalley.edu/academics/technology/computer-science-technology-software-developer.html](https://www.bridgevalley.edu/academics/technology/computer-science-technology-software-developer.html)
=> Add BridgeValley Community and Technical College

lib/domains/au/edu/vic/staughtoncollege.txt
Add Staughton College to Victoria Australia Colleges List.
=> Add Staughton College

lib/domains/edu/sfbu/alumni.txt
=> add sfbu/alumni.txt

lib/domains/bd/edu/bau/students.txt
> The main domain (`bau.edu.bd`) is already added (#27726). But the university authority is now providing students email from the `students` subdomain. This PR will add the subdomain `students.bau.edu.bd`. The institute's information is provided for your convenience.
Institution Name:
**Bangladesh Agricultural University**
Official Website URL:
**https://bau.edu.bd/**
IT-related Faculty/Department Website URLs:
1. https://aet.bau.edu.bd/ (Faculty of Agricultural Engineering & Technology)
2. https://csm.bau.edu.bd/ (Dept. of Computer Science and Mathematics)
3. https://stat.bau.edu.bd/ (Dept. of Agricultural and Applied Statistics)
4. https://bie.bau.edu.bd/ (Dept. of Bioinformatics Engineering)
Bangladesh Agricultural University (BAU), established in 1961, is one of the leading …
=> Add students.bau.edu.bd

lib/domains/ar/edu/imagecampus.txt
Website: https://www.imagecampus.edu.ar/
VideoGame Programming career: https://www.imagecampus.edu.ar/carreras-titulo-oficial/tecnico-superior-desarrollo-videojuegos
Mail proof:
=> Add Image Campus institution

lib/domains/org/ueuromed.txt
Just added my university on the list
=> adding euromed university of fez

lib/domains/edu/richland.txt
Richland Community College
CS degree: [https://www.richland.edu/academics/programs-degrees/computer-science-and-information-technology/](https://www.richland.edu/academics/programs-degrees/computer-science-and-information-technology/)
=> Add Richland Community College

lib/domains/edu/isothermal.txt
Isothermal Community College
Computer Engineering Technology: [https://isothermal.edu/academics/computer-engineering-technology/index.html](https://isothermal.edu/academics/computer-engineering-technology/index.html)
=> Add Isothermal Community College

lib/domains/edu/meridiancc.txt
Meridian Community College
Software Coding Technology program: [https://meridiancc.edu/programs/career_and_technical_programs/division_of_business/software_coding_technology/index.html](https://meridiancc.edu/programs/career_and_technical_programs/division_of_business/software_coding_technology/index.html)
=> Add Meridian Community College

lib/domains/edu/lattc.txt
Los Angeles Trade Technical College
Computer Information Systems: [https://www.lattc.edu/academics/aos/computer-information-systems](https://www.lattc.edu/academics/aos/computer-information-systems)
=> Add Los Angeles Trade Technical College

lib/domains/in/ac/iisc.txt
Indian Institute Of Science
Division of Electrical, Electronics, and Computer Sciences: [https://iisc.ac.in/academics/divisions/division-of-electrical-sciences/](https://iisc.ac.in/academics/divisions/division-of-electrical-sciences/)
=> Add Indian Institute Of Science

lib/domains/edu/montcalm.txt
Montcalm Community College
Information Technology Cybersecurity, A.A.S.: [https://montcalm.edu/sub-header/academics/degrees/information-technology-cybersecurity-associate-degree/](https://montcalm.edu/sub-header/academics/degrees/information-technology-cybersecurity-associate-degree/)
=> Add Montcalm Community College

lib/domains/edu/phoenixcollege.txt
Phoenix College
CS Programs: [https://www.phoenixcollege.edu/degrees-certificates/computer-and-information-technology](https://www.phoenixcollege.edu/degrees-certificates/computer-and-information-technology)
=> Add Phoenix College

lib/domains/edu/postech.txt
Pohang University Of Science And Technology
Faculty dedicated page: [https://ecse.postech.ac.kr/](https://ecse.postech.ac.kr/)
Faculty list on original website: [https://www.postech.ac.kr/eng/academics/department_info.do#univer10](https://www.postech.ac.kr/eng/academics/department_info.do#univer10)
=> Add Pohang University Of Science And Technology

lib/domains/ng/edu/acu.txt
Ajayi Crowther University
Engineering faculty: [https://acu.edu.ng/faculty-of-engineering/](https://acu.edu.ng/faculty-of-engineering/)
=> Add Ajayi Crowther University

lib/domains/cn/hzvtc.txt
Add Hanzhong Vocational and Technical College
=> Add Hanzhong Vocational and Technical College

lib/domains/edu/minerva.txt
university official website URL: [https://www.minerva.edu/](https://www.minerva.edu/)
URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: [https://www.minerva.edu/concentrations/computer-science-and-artificial-intelligence/](https://www.minerva.edu/concentrations/computer-science-and-artificial-intelligence/
)
=> Add Minerva university

lib/domains/edu/midland/mail.txt
College official website: https://www.midland.edu/
https://www.midland.edu/academics/degrees/computer-tech/computer-programming.php
=> Add Midland College

lib/domains/eu/gs-ldk.txt
https://www.gs-ldk.de
The School teaches IT. https://www.gs-ldk.de/bildungsangebote/it-berufe.html
The website is in german. I dont know if it has other languages.
gs-ldk.eu is their IServ, for teachers and students to access email amongst other stuff
=> Added Gewerbliche Schulen Dillenburg

lib/domains/ec/edu/paradox.txt
Jetbrains free licenses request
=> Add Paradox - Instituto Tecnológico de Imagen y Sonido

lib/domains/id/sch/latansa.txt
La Tansa High School is an islamic boarding school that embraces technology to be foundation of its overall system.
=> La Tansa High School - Indonesia

lib/domains/es/utamed.txt
Spanish University Official Website URL: https://www.utamed.es/
URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: https://www.minerva.edu/concentrations/computer-science-and-artificial-intelligence/
=> Add Universidad Tecnológica Atlántico Mediterráneo - UTAMED

lib/domains/vn/edu/uel.txt
Trường Đại học Kinh tế – Luật, Đại học Quốc gia Thành phố Hồ Chí Minh
=> Add University of Economics and Law HCM – UEL

lib/domains/kg/edu/qh.txt
This is our school website:  https://qh.edu.kg/
Here is the URL for our course description: https://qh.edu.kg/admissions.html  
Here are the necessary supplementary explanations:
=> Request to add school: QH

lib/domains/cn/edu/hnucm.txt
Reverts JetBrains/swot#29319
Hello ,The license application was successful, but when using the student email, it prompted that it could not be used. What should I do?
=> Revert "Create hnucm.txt"

lib/domains/edu/chop.txt
New edu domain to be added for The Children's Hospital of Philadelphia
website: https://www.chop.edu/
Department of Biomedical and Health Informatics: https://www.chop.edu/centers-programs/department-biomedical-and-health-informatics-dbhi
=> New edu domain

lib/domains/bd/edu/cdcmn.txt
Add our university email to your list..
=> Add new university email

lib/domains/edu/sunyrockland.txt
https://sunyrockland.edu/
Rockland Community College is a SUNY (State University of New York) school in Rockland County, New York.
=> Add sunyrockland.edu (Rockland Community College)

lib/domains/org/gymnasium-melle.txt
School Website: https://www.melle-gymnasium.de/
Email Adresses: *@gymnasium-melle.org
Idk why they have two separately.
This school is from Germany so sorry if my English is bad :(
=> Gymnasium Melle

lib/domains/eu/ensitech.txt
School website link : https://www.ensitech.eu/
=> ADDED ENSITECH IT INNOVATION SCHOOL

lib/domains/edu/ccm.txt
County College Of Morris
IT faculty: [https://www.ccm.edu/departments/information-technologies/](https://www.ccm.edu/departments/information-technologies/)
=> Add County College Of Morris

lib/domains/edu/gadsdenstate.txt
Gadsden State Community College
Tech Programs: [https://gadsdenstate.edu/programs-of-study/technical-programs.cms](https://gadsdenstate.edu/programs-of-study/technical-programs.cms)
=> Add Gadsden State Community College

lib/domains/edu/bemidjistate.txt
Bemidji State University
CS faculty link: [https://www.bemidjistate.edu/academics/catalog/current/programs/bs__comswbux](https://www.bemidjistate.edu/academics/catalog/current/programs/bs__comswbux)
=> Add Bemidji State University

lib/domains/edu/jeffco.txt
Jefferson College
Computer Systems faculty: [https://www.jeffco.edu/program/computer-information-systems/](https://www.jeffco.edu/program/computer-information-systems/)
=> Add Jefferson College

lib/domains/pl/swps.txt
SWPS University
Computer Science faculty (Informatika): [https://swps.pl/oferta/informatyka](https://swps.pl/oferta/informatyka)
=> Add SWPS University

lib/domains/edu/southeasttech.txt
Southeast Technical Institute
Computer Programming Faculty: [https://www.southeasttech.edu/programs/information-technology/computer-programming/index.php](https://www.southeasttech.edu/programs/information-technology/computer-programming/index.php)
=> Add Southeast Technical Institute

lib/domains/edu/northeast.txt
Northeast Community College
STEM faculty link: [https://northeast.edu/academics/fields-of-study/stem](https://northeast.edu/academics/fields-of-study/stem)
=> Add Northeast Community College

lib/domains/edu/saic.txt
School Of The Art Institute Of Chicago
Art & Technology Faculty: [https://www.saic.edu/atsp](https://www.saic.edu/atsp)
=> Add School Of The Art Institute Of Chicago

lib/domains/edu/mnstate.txt
Minnesota State University Moorhead
CS faculty link: [https://www.mnstate.edu/academics/majors/computer-science/](https://www.mnstate.edu/academics/majors/computer-science/)
=> Add Minnesota State University Moorhead

lib/domains/mx/edu/oxfordacambaro.txt
=> Add file via upload

lib/domains/ec/edu/tecnologicoloja.txt
la dirección de mi institución es https://tecnologicoloja.edu.ec/
=> add my school Tecnologico Loja

lib/domains/sn/edu/cesag.txt
Hi, 
I just add a new domain name for my school CESAG
=> Adding CESAG domain name for senegal education

lib/domains/uk/ac/wnc.txt
West Notts is a Education provider based in the east midlands
=> Add West Notts College 

lib/domains/edu/luzerne.txt
Luzerne County Community College
Computer Information Systems department: [https://www.luzerne.edu/academics/catalog/dept.jsp?m=4&a=Computer%20Information%20Systems](https://www.luzerne.edu/academics/catalog/dept.jsp?m=4&a=Computer%20Information%20Systems)
=> Add Luzerne County Community College

lib/domains/edu/lasell.txt
Lasell University
Data Analytics degree: [https://www.lasell.edu/academics/schools-and-programs/school-of-health-sciences/programs/data-analytics.html](https://www.lasell.edu/academics/schools-and-programs/school-of-health-sciences/programs/data-analytics.html)
=> Add Lasell University

lib/domains/edu/principia.txt
The Principia School
"IDEA Labs" (tech learning curve): [https://www.principiaschool.org/academics/signatureprograms](https://www.principiaschool.org/academics/signatureprograms)
=> Add The Principia School

lib/domains/edu/imperial.txt
Imperial Valley College
Math & Sciences: [https://imperial.edu/courses-and-programs/divisions/math-and-sciences/index.html](https://imperial.edu/courses-and-programs/divisions/math-and-sciences/index.html)
=> Add Imperial Valley College

lib/domains/edu/fdltcc.txt
Fond Du Lac Tribal And Community College
Geographic Information Systems: [https://fdltcc.edu/degrees-certificates/degree-programs/geographic-information-systems/](https://fdltcc.edu/degrees-certificates/degree-programs/geographic-information-systems/)
=> Add Fond Du Lac Tribal And Community College

lib/domains/edu/sautech.txt
Southern Arkansas University Tech
Computer Information Technology degree: [https://www.sautech.edu/programs-degrees/computer-information-technology/](https://www.sautech.edu/programs-degrees/computer-information-technology/)
=> Add Southern Arkansas University Tech

lib/domains/edu/edisonohio.txt
Requesting verification for Edison State Community College.
=> Create Edison State Community College

lib/domains/br/com/sempreuninassau.txt
**the university official website URL, if it is different from the domain you are submitting:**
The official website is https://www.sereducacional.com/
They have https://www.uninassau.edu.br/ as one of the colleges, as can be seen at https://www.sereducacional.com/instituicoes.html
But the email is userid@sempreuninassau.com.br
**a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university:**
https://vestibular.uninassau.edu.br/PS_Nassau/curso/85/9013/3/superior-de-tecnologia-em-analise-e-desenvolvimento-de-sistemas/Fortaleza-CE
Address of the institution:
[https://www.uninassau.edu.br/estrutura-fisica/doroteias](https://www.uninassau.edu.br/estrutura-fisica/doroteias)
Av. Visconde do Rio Branco, 2078 – Joaquim Távora 
Fortaleza, …
=> Add sempreuninassau

lib/domains/edu/frontrange.txt
Front Range Community College
Computer Science & Programming: [https://frontrange.edu/programs-courses/program-list/computer-science-programming.html](https://frontrange.edu/programs-courses/program-list/computer-science-programming.html)
=> Add Front Range Community College

lib/domains/edu/mesalands.txt
Mesalands Community College
Digital Arts Certification (including software engineering): [https://www.mesalands.edu/academic-programs/degrees-certificates/digital-arts/](https://www.mesalands.edu/academic-programs/degrees-certificates/digital-arts/)
=> Add Mesalands Community College

lib/domains/edu/montgomery.txt
Montgomery Community College
IT Curriculum link: [https://www.montgomery.edu/programs/information-technology/](https://www.montgomery.edu/programs/information-technology/)
=> Add Montgomery Community College

lib/domains/edu/parisjc.txt
Paris Junior College
Cybersec, programming, industrial and STEM: [https://www.parisjc.edu/program/industry/](https://www.parisjc.edu/program/industry/)
=> Add Paris Junior College

lib/domains/edu/atlantatech.txt
Atlanta Technical College
Cybersec & programming faculty link: [https://atlantatech.edu/programs/cybersecurity-computer-information-systems/](https://atlantatech.edu/programs/cybersecurity-computer-information-systems/)
=> Add Atlanta Technical College

lib/domains/edu/ncmissouri.txt
North Central Missouri College
Computer Science (Programming) faculty link: [https://www.ncmissouri.edu/academics/computer-science-and-information-systems/](https://www.ncmissouri.edu/academics/computer-science-and-information-systems/)
=> Add North Central Missouri College

lib/domains/pk/edu/niit.txt
URL: https://niit.edu.pk/
4 years bachelor's in AI: https://niit.edu.pk/programs/artificial-intelligence
=> Adding NIIT lahore,PK to jetbrains

lib/domains/kr/go/gen/gsuite.txt
My high school uses the gsuite.gen.go.kr domain.
=> add "Salesio High School"

lib/domains/gr/cti.txt
Pull request for Computer Technology Institute and Press “DIOPHANTUS” (CTI)
=> Computer Technology Institute and Press “DIOPHANTUS” (CTI)

lib/domains/dz/univ-eloued.txt
Hello
please accept our domain for University Of El Oued  Algeria.
=> Add University Of El Oued

lib/domains/ar/edu/isp20.txt
www.isp20.edu.ar
https://isp20.edu.ar/nuevo/tecnico-superior-en-desarrollo-de-software/
https://isp20.edu.ar/nuevo/tecnico-superior-en-soporte-de-infraestructura-en-tecnologias-de-la-informacion/
=> Add www.isp20.edu.ar

lib/domains/bd/edu/ranguniacollege.txt
Adding Rangunia Government College domain as part of educational email verification.
=> Add ranguniacollege.edu.bd domain

lib/domains/ge/edu/sabauni.txt
The domain for this university is: Sabauni.edu.ge
Thank you!
=> Adding my university of "Sulkhan-Saba Orbeliani University" to the available universities list

lib/domains/edu/yvcc.txt
Yakima Valley Community College
STEM degrees: [https://yvcc.edu/academics/stem.php](https://yvcc.edu/academics/stem.php)
=> Add Yakima Valley Community College

lib/domains/edu/kellogg.txt
Kellogg Community College
Computer Programming degree program: [http://catalog.kellogg.edu/preview_program.php?catoid=27&poid=2356&returnto=2182](http://catalog.kellogg.edu/preview_program.php?catoid=27&poid=2356&returnto=2182)
=> Add Kellogg Community College

lib/domains/edu/netc.txt
Northeastern Technical College
Tech study program link: [http://netc.edu/academic_pathways.php?Academic-Programming-Programs-of-Study-45](http://netc.edu/academic_pathways.php?Academic-Programming-Programs-of-Study-45)
=> Add Northeastern Technical College

lib/domains/edu/mvc.txt
Moreno Valley College
STEM faculty link: [https://mvc.edu/academics/stem.php](https://mvc.edu/academics/stem.php)
=> Add Moreno Valley College

lib/domains/edu/shawneecc.txt
Shawnee Community College
Computer Systems degree: [https://shawneecc.edu/academics/programs/computer-systems-and-security-specialist/](https://shawneecc.edu/academics/programs/computer-systems-and-security-specialist/)
=> Add Shawnee Community College

lib/domains/edu/swic.txt
Southwestern Illinois College
IT degrees: [https://www.swic.edu/academics/career-degrees/information-technology-degrees/](https://www.swic.edu/academics/career-degrees/information-technology-degrees/)
=> Add Southwestern Illinois College

lib/domains/edu/gfcmsu.txt
Great Falls College Montana State University
Tech faculty link: [https://www.gfcmsu.edu/academic-program/computer-programming/](https://www.gfcmsu.edu/academic-program/computer-programming/)
=> Add Great Falls College Montana State University

lib/domains/edu/robeson.txt
Robeson Community College
IT programs: [https://www.robeson.edu/business-technologies/information-technology/](https://www.robeson.edu/business-technologies/information-technology/)
=> Add Robeson Community College

lib/domains/edu/bluefieldstate.txt
Bluefield State College
Software Engineering faculty link: [https://bluefieldstate.edu/degree/computer-science-software-engineering-concentration-bs/](https://bluefieldstate.edu/degree/computer-science-software-engineering-concentration-bs/)
=> Add Bluefield State College

lib/domains/edu/beaufortccc.txt
Beaufort County Community College
Programming faculty: [https://catalog.beaufortccc.edu/preview_program.php?catoid=4&poid=453&returnto=177](https://catalog.beaufortccc.edu/preview_program.php?catoid=4&poid=453&returnto=177)
=> Add Beaufort County Community College

lib/domains/edu/northgatech.txt
North Georgia Technical College
IT programs: [https://northgatech.edu/academic-programs/business/computer-information-technology/](https://northgatech.edu/academic-programs/business/computer-information-technology/)
=> Add North Georgia Technical College

lib/domains/edu/sunyocc.txt
Onondaga Community College
Tech department: [https://www.sunyocc.edu/tec](https://www.sunyocc.edu/tec)
=> Add Onondaga Community College

lib/domains/edu/martincc.txt
Martin Community College
IT foundations course: [https://www.martincc.edu/programs?q=programviewer&degree=157](https://www.martincc.edu/programs?q=programviewer&degree=157)
=> Add Martin Community College

file/lib/domains/de/bs-mil-obb.txt, lib/domains/de/bs-mil-obb.txt
official website:
https://www.bs-mil-obb.de/
course IT specialist for application development - 3 years:
https://www.bs-mil-obb.de/berufsbild/fachinformatiker-fachrichtung-anwendungstechnik
proof:
=> Berufsschule Miltenberg Obernburg

lib/domains/au/edu/vic/Werribeesc.txt
=> Werribeesc

lib/domains/edu/sbts/students.txt
=> Adding file for SBTS

lib/domains/it/studenti/unige.txt
i am trying to add my university to your repository, it is Unige, from Genoa, Italy
=> Add new university files via upload

lib/domains/vn/edu/vhu.txt
The Van Hien University site:
https://vhu.edu.vn
=> Van Hien University

lib/domains/edu/cctech.txt
Central Carolina Technical College
=> Adding CCTC

lib/domains/id/sch/darmabangsa.txt
Add Darma Bangsa School to List Jetrbrains Educational Pack
=> Add Darma Bangsa School to List Jetrbrains

lib/domains/org/dncoe.txt, lib/domains/org/dnusd.txt, lib/domains/org/mydnschools.txt, lib/domains/us/ca/k12/delnorte.txt
**Added the following Educational institutions.**
**Del Norte County Office of Education**
- dncoe.org
- delnorte.k12.ca.us
**Del Norte Unified School District** 
- dnusd.org
- delnorte.k12.ca.us
**Del Norte County Student Accounts** 
- mydnschools.org
=> Added Del Norte County Schools Domains

lib/domains/com/uw.txt
Per instructions [here](https://www.jetbrains.com/shop/eform/students/contributeUniversity) added University of Washington
=> Add University of Washington

lib/domains/tw/edu/tc/cgsh/gs.txt
Offical website:
https://cgsh.tc.edu.tw
=> Add Taichung Municipal Chung Gang Senior High School

lib/domains/cn/edu/cqie.txt
add Chongqing Institute of Engineering, home page: https://www.cqie.edu.cn
=> add Chongqing Institute of Engineering

lib/domains/ec/edu/ucuenca.txt
Solicito agregar la Universidad de Cuenca (Ecuador) al repositorio swot.
Dominio institucional: ucuenca.edu.ec
=> Add Universidad de Cuenca (ecuador) - ucuenca.edu.ec

lib/domains/pk/edu/froebels.txt
Added a froebels.edu.pk domain to known schools
=> Added Froebels.edu.pk to known domains

lib/domains/kr/hufs.txt
=> fix: Update hufs.txt (add hufs)

lib/domains/edu/incae.txt
https://incae.edu/en/programs/master-in-analytics-innovation-and-technology/
=> INCAE Business School

lib/domains/edu/raiuniversity.txt
Official website: https://www.raiuniversity.edu/
IT-related course: https://www.raiuniversity.edu/rai-school-of-engineering-rse/
Proof of email domain: https://drive.google.com/drive/folders/11wHgLJQfBdiTSUBtG2vOUEiAxK-1ZSYT?usp=sharing
Note: This is a screenshot from RAI University’s ERP system showing my student profile with the email 24BTCSE025@raiuniversity.edu. I currently don’t have access to emails sent to or from this address, but I’m working with the university’s IT department ([info@raiuniversity.edu](mailto:info@raiuniversity.edu)) to gain access or obtain an official document confirming the domain. I can provide additional proof if needed.
=> Add Rai University domain (raiuniversity.edu)

lib/domains/au/edu/aieinstitute/students.txt
University URL: https://aieinstitute.edu.au/
URL of Programming Course: https://aieinstitute.edu.au/course/bachelor-of-game-development-major-in-game-programming/
=> Add AIE Institute

lib/domains/cn/edu/nfu/stu.txt
University official website address：https://www.nfu.edu.cn/
=> add:Nanfang College, Guangzhou

lib/domains/mv/edu/hulhudhuffaaruschool.txt
Add hulhudhuffaaruschool.edu.mv for Hulhudhuffaaru School
Official Website (Under construction)
http://hulhudhuffaaruschool.edu.mv/
Our Official Details in Government Page (Ministry of Education)
https://www.moe.gov.mv/en/schools/503
=> Add Hulhudhuffaaru School domain hulhudhuffaaruschool.edu.mv

lib/domains/jp/kosen-ac/sendai.txt
=> Add Domain Please

lib/domains/ch/bqu.txt
Add Switzerland "Add University of Bareda Queen".
=> Add University of Bareda Queen

lib/domains/ch/uome.txt
Add Switzerland Institute "University of Marist Eastbay"
=> Ad Institute "University of Marist Eastbay"

lib/domains/edu/pugetsound.txt
Add University of Puget Sound
Official Website: https://pugetsound.edu/
Computer Science program website: https://www.pugetsound.edu/academics/computer-science
From the Contact Details page on the student portal:
=> Add University of Puget Sound

lib/domains/org/newarkcityschools.txt
Newark City Schools, Newark Ohio
Office Website - [https://www.newarkcityschools.org/](https://www.newarkcityschools.org/)
=> Add Newark City Schools

lib/domains/il/org/manhischools.txt
Added manhischools.txt to the domain list
=> Added manhischools.txt to domains

lib/domains/edu/sunyempire.txt
**Link to Computer Science courses in academic catalog:** [CSCI](https://catalog.sunyempire.edu/courses/csci/)
**Link to list of IT related degree programs:** [School of Science, Mathematics, and Technology](https://catalog.sunyempire.edu/undergraduate/areas-study-degrees-certificates/areas-study-concentration-guidelines/science-mathematics-technology/#concentrationdetailstext)
=> Add SUNY Empire State University

lib/domains/edu/sfcollege.txt
Add Santa Fe College to the domains list
=> Add Santa Fe College

lib/domains/ro/bolyai.txt
Added a new file bolyai.txt under lib/domains/ro to include institution details for Romania
=> Add bolyai.txt for Romania domain

lib/domains/edu/cwi.txt
Adding cwi.edu domain
Software Development Program - https://cwi.edu/program/software-development
Email address verification - https://support.cwi.edu/TDClient/30/Portal/KB/ArticleDet?ID=104
=> Adding cwi.edu for the College of Western Idaho

lib/domains/es/ecam.txt, lib/domains/es/ecam/ecam.txt
This PR corrects the file location introduced in #30300.  
The file was placed in the wrong directory, and this commit moves it to the appropriate location according to the project structure.
Sorry for the oversight!
Thank you.
=> Move file to correct directory (follow-up to #30300)

lib/domains/es/ifp.txt
I've tried before but now i think it  is correct, sorry for the inconveniences
=> Adding ifp.es as a domain

lib/domains/in/edu/pec.txt
official college site : https://pec.ac.in/
undergraduate courses : https://pec.ac.in/programmes/ug/structure
https://pec.ac.in/programmes/ug/structure/cse-syllabus
=> Adding PEC chandigarh college for student access

lib/domains/com/colegioanamariamatute.txt
https://www.colegioanamariamatute.com
=> Add school Ana María Matute

lib/domains/edu/essex.txt, lib/domains/edu/essex/email.txt
📌 Pull Request: Add essex.edu for Essex County College
Hello JetBrains Team,
I’m submitting a request to add Essex County College to the list of supported institutions for student licenses. Below are the required details for verification:
- School name: Essex County College
- Official website: https://www.essex.edu/
- Email domain: email.essex.edu
- My school email: sbamba@email.essex.edu
- File added: lib/domains/edu/essex/email.txt
🎓 IT-Related Programs
Essex County College offers  IT-related programs:
- https://www.essex.edu/metcs/
📧 Proof of Email Domain Usage
Students (including me) are issued email addresses in the format @essex.edu. I’ve attached a screenshot of my student email inbox as proof.
=> Add Essex County College (essex.edu)

lib/domains/th/ac/western.txt
Add western to the domain list
=> Add western to the domain list

lib/domains/mv/edu/cyryxcollege.txt
Added cyrex college [https://cyryxcollege.edu.mv/](https://cyryxcollege.edu.mv/)
=> added cyrex college

lib/domains/bd/edu/royal.txt
Please add Royal University of dhaka in school list. the university domain is https://www.royal.edu.bd/
=> Add Royal University of Dhaka (Bangladesh)

lib/domains/org/creightonprep.txt
https://www.creightonprep.org/student-life/activities-clubs#fs-panel-5179/
https://www.creightonprep.org/uploaded/Academics/Course_Catalog.pdf#page=6/
=> Add Creighton Preparatory School

lib/domains/in/edu/bennett.txt
Bennett University, Greater Noida, India
=> Add Bennett University

lib/domains/edu/stcc.txt
Request for Springfield Technical Community College The domain is stcc.edu
=> stcc.edu request

lib/domains/in/edu/cmr.txt
created branch as mentioned in documentation for CMR university university  link https://www.cmr.edu.in/admissions/doctoral/
=> cmr university

lib/domains/edu/cstu.txt
Add California Science And Technology University
=> Add California Science And Technology University

lib/domains/my/edu/chhsban.txt
Our School Website:https://chhsban.edu.my/
=> Add Chung Hua High School

lib/domains/in/edu/atmiyauni.txt
=> Added Atmiya University , Rajkot

lib/domains/in/edu/adypu.txt
Please add Ajeenkya DY Patil Univerity, Pune, Maharashtra. 
Website: https://adypu.edu.in/
UG Engineering Program Page: https://soe.adypu.edu.in/soe/b-tech-computer-science-and-engineering-software-engineering
=> Add Ajeenkya DY Patil University Mail

lib/domains/org/imitsuriname.txt
=> PleaseverifyIMIT

lib/domains/my/edu/ytl-ichm.txt
Official college website: https://www.ytl-ichm.edu.my/
=> Add YTL International College of Hotel Management

lib/domains/de/schulen-gelsenkirchen/bk-btg.txt
The Berufskolleg für Technik und Gestaltung is a vocational college located in Gelsenkirchen, Germany. The school offers a wide range of technical and creative educational programs, preparing students for both professional careers and higher education in engineering, design, and related fields.
=> Added BTG school for education license

lib/domains/pt/esramada.txt
Escola Secundária da Ramada(Odivelas)
=> Escola Secundária da Ramada

lib/domains/in/edu/kccitm.txt
add kcc institute of technology and management
=> add kcc itm

lib/domains/edu/nmims.txt
=> NMIMS Domain

lib/domains/in/edu/sanjivani.txt
To  whomever it may concern,
I wish to add my college named Sanjvani University which is situated in Kopargaon, Maharashtra, India. I hope you would see this and accept this pull request
=> Adding Sanjivani University to the List of colleges

lib/domains/cz/skolagaia.txt
adding "GAIA Kindergarten and Elementary School"
=> added https://skolagaia.cz/

lib/domains/ec/edu/uniandes.txt
Por favor agregar la universidad Regional Autònoma de los Andes
=> Universidad Uniandes Agregada

lib/domains/ch/bttok.txt
BTTok Technische Hochschule Biel
=> add BTTok Technische Hochschule Biel

lib/domains/pe/edu/idat.txt
Please add the Peruvian Technical Institute "Instituto Superior Tecnológico Idat".
=> add idat.edu.pe domain

lib/domains/in/edu/hnbgu.txt
website : https://hnbgu.ac.in/
=> Added hnbgu collage

lib/domains/org/summitcds/students.txt
This pull request adds students.summitcds.org under lib/domains/org/summitcds/students.txt following the repository structure guidelines.
Verified the domain ownership.
Follows the required .txt file format.
=> Add students.summitcds.org domain file

lib/domains/com/onmicrosoft/buddhidharma1.txt
https://www.buddhidharma.ac.id/ --- Official Website
=> Add Universitas Buddhi Dharma

lib/domains/de/media-uni.txt
Official Website: https://www.media-university.de
=> add Media University domain

lib/domains/ca/rdcrs.txt
Add rdcrs.ca domain for Red Deer Catholic Regional Schools
=> Add rdcrs.ca domain for Red Deer Catholic Regional Schools

lib/domains/com/universitatunipro.txt
**_the university official website URL_**
https://www.universidadunipro.com/
_**URLs of pages on the official website where a long-term (>1 year) IT related course is offered by the university**_
https://www.universidadunipro.com/bachelor-en-ingenieria-informatica-B21.html
https://www.universidadunipro.com/bachelor-en-ciencia-de-datos-B20.html
_**a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.**_
https://www.universidadunipro.com/aviso-legal.html
=> Add domain to Jetbrains/swot

lib/domains/in/edu/andhrauniversity.txt
Added domain for Andhra University
=> Add domain for Andhra University

lib/domains/mx/edu/cobachih.txt
Website: https://cobachih.edu.mx/
=> Add cobachih.edu.mx

lib/domains/org/tantasqua.txt
School Website at Tantasqua.org
Technical Division has IT program
=> Add tantasqua.org domain

lib/domains/kr/ac/gknu.txt
- University website: https://www.gknu.ac.kr/global/index.do
- Curriculum web page (Korean): https://ai.andong.ac.kr/module/subject/list.php?mid=/intro/curriculum/hakbu&sbsite=ai&sbcode=curriculum&sbhakyun=1%ED%95%99%EB%85%84&sbhakyun_only=
1. 인공지능(Artificial Intelligence): Python in practice
2. 딥러닝(Deep Learning): Python in practice
3. 디지털영상처리(Digital Image Processing): Python in practice
4. 멀티미디어프로그래밍(Multimedia Programming): Python in practice
5. 컴퓨터비전(Computer Vision): Python in practice
6. Java프로그래밍(Java Programming): Java in practice
7. 웹마스터과정(Webmaster Course): Javascript in practice
=> Add gknu.txt at lib/domains/kr/ac/ (Gyeongkuk National University)

lib/domains/fr/digitalschool/etu.txt
Commit : Added @etu.digitalschool.fr domain for pull request to identify as a student organisation.
=> Pull Request to add @etu.digitalschool.fr domain name.

lib/domains/in/edu/cvmu.txt
The Charutar Vidya Mandal (CVM) University
Beside BVM College, Opp Shastri Maidan, 
Vallabh Vidhyanagar-388120 
Gujarat-india
https://www.cvmu.edu.in/
=> Add CVMU Domain

lib/domains/in/edu/dypvp.txt
Offers 4 year Batchelor of Engineering Course for fields of CS, IT, and other related fields under Pune University.
=> Hey, Please add @dypvp.edu.in for Dr. D. Y. Patil Institute of Technology.

lib/domains/kr/ac/wsu.txt, lib/domains/kr/wsu.txt
Please review and merge if everything looks good.
Thank you :)
=> Add woosong university

lib/domains/ch/untre.txt
=> Revert "add Unternehmerische Technikum für Reale Erfindungen"

lib/domains/im/uiied.txt
University of the Isle of Interdisciplinary Excellence
=> add University of the Isle of Interdisciplinary Excellence

lib/domains/in/edu/gift.txt
Official URL: https://top-autonomous-college-in-odisha.gift.edu.in
B.Tech CSE's HOD page: https://top-autonomous-college-in-odisha.gift.edu.in/cse/hods-message/
=> feat: GIFT Autonomous College

lib/domains/in/edu/ssn/it.txt
- Official website - [https://www.ssn.edu.in/](https://www.ssn.edu.in/)
- Proof of IT-related course(>1 year) offering - [https://www.ssn.edu.in/college-of-engineering/programs-overview/](https://www.ssn.edu.in/college-of-engineering/programs-overview/)
- Proof for the domain added - [https://www.ssn.edu.in/wp-content/uploads/2020/06/identITy_Volume-3-Issue-1.pdf](https://www.ssn.edu.in/wp-content/uploads/2020/06/identITy_Volume-3-Issue-1.pdf) - IT Department magazine having email of the students who wrote the articles:
=> Add SSN College of Engineering, India

lib/domains/ua/edu/nau/sfk.txt
This pull request adds the domain sfk.nau.edu.ua (Slovyansk Professional College) to the JetBrains swot database to verify student and teacher status for JetBrains educational licenses.
=> Add sfk.nau.edu.ua to JetBrains swot

lib/domains/id/sch/santa-laurensia.txt
Please add school Santa Laurensia. Thank you.
Website : www.santa-laurensia.com
Email domain : santa-laurensia.sch.id
Country : Indonesia
State : Banten
City : South Tangerang / Tangerang
=> Add Santa Laurensia School

lib/domains/com/ellabts.txt
Dear JetBrains Team,
This PR adds the ellabts.com domain, which is currently used by students and staff of the 2-year BTS Services Informatiques aux Organisations (SIO) program (option SLAM/SISR) at Lycée Ella Fitzgerald. This domain is provisioned via Google Workspace and issues official email addresses of the form firstname.lastname@ellabts.com to enrolled students and teachers.
BTS SIO Program Details
Program: BTS Services Informatiques aux Organisations (SIO), duration 2 years, specializing in SLAM (software development) or SISR (network infrastructure).
Proof of program structure and content: https://dossier.parcoursup.fr/Candidats/public/fiches/afficherFicheFormation?g_ta_cod=4950
This confirms that the curriculum is IT-related and runs for at least two academic years.
official …
=> add domain ellabts.com for BTS SIO at Lycée Ella Fitzgerald

lib/domains/im/uaolen.txt
Uralach Academy of Oceanic Life & Environmental Nexus
=> Add Uralach Academy of Oceanic Life & Environmental Nexus

lib/domains/in/btup.txt
Baruda Technological & Practical University
=> add Baruda Technological & Practical University  thank

lib/domains/in/edu/sittechno.txt
https://www.sittechno.org/
https://www.sittechno.org/computer-science-engineering-engineering-technology.html
=> Added domain file

lib/domains/edu/uthsc.txt
https://www.uthsc.edu, The University of Tennessee Health Science Center
=> Add new uthsc domain

lib/domains/co/edu/unincol/alumnos.txt
**Institute Name:** Fundación Universitaria Internacional de Colombia UNINCOL
**Domain:** unincol.edu.co
**Website:** https://www.unincol.edu.co/
**Country:** Colombia
=> Add alumnos.unincol.edu.co to JetBrains Swot

lib/domains/sn/ucad.txt
This pull request adds the domain `ucad.edu.sn` to the JetBrains/swot repository to include Université Cheikh Anta Diop de Dakar in the JetBrains Student Program.
Students with an email address ending in `@ucad.edu.sn` should be eligible for free JetBrains educational licenses after this PR is merged.
=> Add Université Cheikh Anta Diop (ucad.edu.sn)

lib/domains/in/edu/tib.txt
Added tib.edu.in domain for Techno International Batanagar.
=> Add tib.edu.in domain

lib/domains/fr/steanne-sav.txt
Lycée Privé Sainte-Anne Savoisienne
Website: https://www.steanne-sav.fr
Name: Lycée Privé Sainte Anne - Savoisienne
Location: France
Domain: steanne-sav.fr
=> steanne-sav.txt

lib/domains/gt/edu/continentalamericano.txt
Dear JetBrains Team,
I am submitting this pull request to kindly request the addition of my educational institution, Colegio Continental Americano (Continental American College), to the JetBrains educational domain list.
Institution Details:
- Name: Colegio Continental Americano
- Domain: continentalamericano.edu.gt
- Country: Guatemala
- Website: https://www.continentalamericano.edu.gt
This will allow students with official institutional email addresses to apply for JetBrains educational licenses.
Thank you very much for your time and support. Please let me know if any adjustments are needed.
Sincerely,  
Sergio Ramírez
=> Add my college domain: continentalamericano.edu.gt

lib/domains/mz/edu/unisced.txt
Add Universidade Aberta ISCED to the domain list.
=> Add domain unisced.edu.mz

lib/domains/de/amberg/gmg.txt
Add Gregor-Mendel-Gymnasium Amberg
=> Create gmg.txt - Add Gregor-Mendel-Gymnasium Amberg

lib/domains/de/biioe.txt
Biionisches Institut fur okologische Energieforschung
=> Create add Biionisches Institut fur okologische Energieforschung

lib/domains/in/edu/ssn/it.txt
Create entry for SSN College of Engineering
=> Create entry for SSN College of Engineering

lib/domains/in/edu/sxca.txt
Add St. Xavier's College, Ahmedabad
website: https://sxca.edu.in/
=> added st xaviers ahmedabad

lib/domains/kr/ac/kbtus.txt
added one of Korean Universities, which is Korea Baptist Theological University/Seminary.
=> added kbtus

lib/domains/in/edu/jspmrscoe.txt
Adding my college domain for student verification for JetBrains Student License.
Email domain: jspmrscoe.edu.in
=> Add JSPM's Rajarshi Shahu College of Engineering (jspmrscoe.edu.in)

lib/domains/bd/edu/recr.txt
institution name:Rangpur Engineering College
Domain:recr.edu.bd
website:https://recr.edu.bd
my student email is   kaushik@recr.edu.bd
=> Add Rangpur Engineering College (recr.edu.bd)

lib/domains/rs/edu/teslabg.txt
Elektrotehnical Middle School Nikola Tesla in Belgrade https://teslabg.edu.rs/
=> Elektrotehnical Middle School Nikola Tesla

lib/domains/pl/edu/augustyniak.txt
[augustyniak.txt](https://github.com/user-attachments/files/21559882/augustyniak.txt)
name: Prywatna Szkoła Podstawowa Krzysztofa Augustyniaka w Łodz
website: https://www.augustyniak.edu.pl/
type: non-public, but partly-funded by the government primary school
e-mail domain: firstname_lastname@augustyniak.edu.pl
The school is worth adding, it prepares students that are interested in programming
for big competitions and exams. The students who really like IT can take part in bonus classes and clubs, or get additional exercises. I really hope you'll add the school.
adress: Deotymy 7 street, Łódź, Poland
=> Add Prywatna Szkoła Podstawowa Krzysztofa Augustyniaka w Łodzi (polish primary school) to swot

lib/domains/in/edu/skct.txt
Adding Sri Krishna College of Technology to swot :)
=> Add Sri Krishna College of Technology

lib/domains/edu/harcum.txt
=> harcum college added

lib/domains/eg/edu/moe/qaliobia2.txt
**Add my high school domain qaliobia2.moe.edu.eg :**
This pull request adds the domain qaliobia2.moe.edu.eg, which belongs to El-Manayel Secondary School in Egypt, to support email verification for students.
@JetBrains
=> Add my High School with domain qaliobia2.moe.edu.eg

lib/domains/ar/edu/colegiosanignaciotandil.txt
Adds Colegio San Ignacio Tandil from Argentina
=> Adds Colegio San Ignacio Tandil from Argentina

lib/domains/ec/edu/sanjuanpablo.txt
Add sanjuanpablo.edu.ec – San Juan Pablo Segundo
Official website: https://sanjuanpablo.edu.ec/
=> Add San Juan Pablo Segundo IT

lib/domains/de/idueo.txt
Digitale Unternehmensentwicklung Ostfalen
=> Create add Digitale Unternehmensentwicklung Ostfalen

lib/domains/uk/sch/herts/onslow.txt
=> Onslow St Audrey's SchoolAdd files via upload

lib/domains/com/acdeducation.txt
**School Name**: Assumption College of Davao
**Domain**: acdeducation.com
* **Official Website**: https://www.acd.edu.ph/acd/
* **IT-Related Program**: https://www.acd.edu.ph/acd/information-technology/
**Verification of Domain Ownership:** The official school website's contact page uses an email address under the requested domain (`acdofficial@acdeducation.com`), confirming its official use. This can be seen in the footer of the homepage under the "Contact Us" section.
=> Add Assumption College of Davao

lib/domains/in/edu/centurionuniv.txt
Add this domain . 
Centurion University of Technology and Management
i added lib/domains/in/edu/centurionuniv.txt
=> Add centurionuniv.edu.in domain

lib/domains/in/edu/slsh/student.txt
URL of the page where the IT course on law and cybersecurity is provided: https://www.slsh.edu.in/cscls
=> Add Symbiosis Law School to Jetbrains

lib/domains/mv/edu/mnu.txt
adding maldives national univertsity
=> feat(uni): Create mnu.txt

lib/domains/ac/mncu.txt, lib/domains/id/ac/mncu.txt
[mncu.txt](https://github.com/user-attachments/files/21515610/mncu.txt)
=> mncu.ac.id

lib/domains/kr/ac/police.txt
Add police.ac.kr to support student license
homepage: 
https://grad.police.ac.kr/home.do?lang=en
https://www.police.ac.kr/police/eng/index.do
=> Add police.ac.kr

lib/domains/de/nordic-campus.txt
Added nordic-campus.de to JetBrains swot list for educational license verification.
=> Berufsbildungswerk Nordic Campus Bremen

lib/domains/pt/edu/ufp.txt
University URL:
https://www.ufp.pt/
Contacts (evidencing the domain):
https://www.ufp.pt/inicio/contactos/
=> Add file for Fernando Pessoa University

lib/domains/ng/edu/kum.txt
Please add Khadija University, Majia to the list of educational institutions eligible for free JetBrains licenses.
- 🏫 Official Name: Khadija University, Majia
- 🌐 Official Website: https://www.kum.edu.ng
- 💻 IT-related Programs (1+ year courses): https://kum.edu.ng/faculty-of-science-and-computing/
- 📧 Student Email Domain: @kum.edu.ng
- 🧑‍🎓 Student Portal (proof of email usage): https://myportal.kum.edu.ng
Khadija University offers accredited long-term IT-related programs such as Computer Science and Software Engineering. Students are provided with official email addresses under the domain `@kum.edu.ng`.
Thank you for reviewing and considering this submission.
=> Add khadija.edu.ng - Khadija University, Majia

lib/domains/fr/maol.txt
Universite Catholique de lOuest Litoral
=> ADD Universite Catholique de lOuest Litoral

lib/domains/ch/auvk.txt
Alpine Universitat Vallis Konstanz
=> add Alpine Universitat Vallis Konstanz

lib/domains/edu/gtcc.txt
=> Add Guilford Technical Community College

lib/domains/in/ovan.txt
Odisha Vidyapeeth Academic Nexus
=> ADD Odisha Vidyapeeth Academic Nexus

lib/domains/hr/kifos.txt
University web page:  https://www.kifos.hr/
This is the link to the official Croatia domain provider: https://domene.hr/en/portal/home
=> Add kifos.hr

lib/domains/pk/edu/pscit.txt
I want to add my school domain so that i can use JetBrain for my learning.
=> peak solutions school domain added

lib/domains/kh/org/jpa.txt
Domain: jpa.org.kh
Official website: https://www.jpa.org.kh
IT-related courses: https://www.jpa.org.kh/high-school
=> Upload jpa.txt

lib/domains/in/edu/rvei.txt
RVITM: Uday Kumar S - 2026 - ISE
=> RV Institute of Technology and management

lib/domains/my/edu/chsbp.txt
=> Add Chinese High Scholl Batu Pahat domain

lib/domains/id/ac/itbu.txt
Institut Teknologi Budi Utomo
Budi Utomo Institute of Technology
=> Add Institut Teknologi Budi Utomo

lib/domains/com/onmicrosoft/weska.txt
Homepage: https://www.walter-eucken-schule.de/
IT-Related course(s): [link one](https://www.walter-eucken-schule.de/berufskolleg/bk-wirtschaftsinformatik-1/), [link two](https://www.walter-eucken-schule.de/berufsschule/it-berufe/)
=> Add weska.onmicrosoft.com

lib/domains/bd/ac/jnu/psy.txt
Added Jagannath University (psy.jnu.ac.bd) to the list of educational institutions.
- Official website: https://www.jnu.ac.bd
- Domain for Psychology department student emails: psy.jnu.ac.bd
- Example academic email: b170603027@psy.jnu.ac.bd
=> Add Jagannath University (psy.jnu.ac.bd)

lib/domains/edu/vvc/student.txt
Adding Victor Valley College to the JetBrains educational institutions list. 
Domain: student.vvc.edu
=> Add Victor Valley College (student.vvc.edu)

lib/domains/in/edu/velammalvidhyashram.txt
https://velammal.org/velammal-vidhyashram-surapet/
https://velammal.edu.in/dept/005
=> Create velammalvidhyashram.txt 

lib/domains/kh/edu/sbubb.txt
please add my our University at Cambodia. thank you
=> Pheah Sihanouk Raja Buddhist University

lib/domains/ar/edu/dachary.txt
Add Universidad Gastón Dachary (dachary.edu.ar)
=> Add Universidad Gastón Dachary (dachary.edu.ar)

lib/domains/ch/bms-w/lernende.txt
BMS Winterthur
Official website:
https://bms-w.ch/
Student mail:
https://lernende.bms-w.ch/
=> Added BMS Winterthur

lib/domains/in/edu/karnavatiuniversity.txt
Adding Karnavati University and its institute Unitedworld Institute of Technology to the JetBrains swot repository.
- **Official website:**  
https://karnavatiuniversity.edu.in
- **IT-related course:**  
https://karnavatiuniversity.edu.in/uit/b-tech-computer-science-and-engineering/
- **Proof of email domain:**  
Students receive official email addresses in the format:  
name@karnavatiuniversity.edu.in
- **Additional details:**
=> Add Karnavati University (karnavatiuniversity.edu.in)

lib/domains/ro/cevmpl.txt
i added Colegiul Economic "Virgil Madgearu" Ploiesti
=> added Colegiul Economic "Virgil Madgearu" Ploiesti

lib/domains/de/gymnasiumkerpen, lib/domains/de/gymnasiumkerpen.txt
official name: Europagymnasium Kerpen
official website: https://www.gymnasiumkerpen.eu/
website talking about the IT courses: https://www.gymnasiumkerpen.eu/unterricht/faecher/informatik
I dont really know what proof to add here other than maybe the fact that every student gets a teams account like:
olibil27@gymnasiumkerpen.de
"oli" first three letters of the first name
"bil" first three letters of the last name
"27" year of finishing school
"@gymnasiumkerpen.de" domain
this is a screenshot of me in the teams account if that helps
=> Add my school Europagymnasium Kerpen

lib/domains/mx/edu/itdelicias.txt
This PR adds a new txt file to add the Technological Institute of Delicias to the list of universities to get access to the all JetBrains tools.
Here is the university website for reference: https://delicias.tecnm.mx/inicio
=> feat: create itdelicias.txt

lib/domains/es/iescapdellevant.txt
https://www.iescapdellevant.org/
https://www.iescapdellevant.org/projectes-de-centre/comissio-tac/
I don't know what would qualify as evidence of the mail linked to the school
=> Ies Cap de llevant

lib/domains/ar/edu/cts.txt
Domain: cts.edu.ar
long-term related study plan: https://cts.edu.ar/plan_de_estudio.html
=> add cts.txt

lib/domains/ar/gov/gba/iuv.txt
I added a new txt document with information about the University (Instituto Universitario Vucetich).
=> Add new txt with information : Education

lib/domains/ro/avramiancucluj.txt
Website: https://www.avramiancucluj.ro/
Proof of courses: https://www.avramiancucluj.ro/despre-noi/resurse-umane-2/
=> Liceul Teoretic "Avram Iancu"

lib/domains/in/edu/geetauniversity.txt
=> Geeta university Added

lib/domains/mx/edu/institutouniversitarioibr.txt
Official website: institutouniversitarioibr.edu.mx
IT-related course: institutouniversitarioibr.edu.mx/Sistemas.html
Proof that the domain is used for student/teacher emails:
=> Create institutouniversitarioibr.txt and add institutouniversitarioibr.edu.mx domain for Instituto Universitario Iberoamericano

lib/domains/ph/edu/nu-eastortigas/students.txt
Added the National University - East Ortigas branch student email domain
=> Added National University - East Ortigas student email domain

lib/domains/mx/edu/ucnl/estudiantes.txt
=> ucnl.edu.mx

lib/domains/uk/sch/herts/jhn.txt
School URL: https://www.jhn.herts.sch.uk
A-Level 2 years courses page: https://www.jhn.herts.sch.uk/2119/year-11-12-bridging-work
=> Add JHN - John Henry Newman

lib/domains/in/ac/iimcal.txt
I have added my institute, "Indian Institute of Management Calcutta," abbreviated as IIM Calcutta.
=> Add generated file: IIM Calcutta Added

lib/domains/jp/ac/ttc.txt
Official website: https://tec.ttc.ac.jp/
=> Add Tokyo Technical College

lib/domains/edu/niacc/my.txt
This commit would allow Computer Science students to access the student pack from their my.niacc.edu email domain.
School: North Iowa Area Community College
Website: niacc.edu
Student subdomain: my.niacc.edu
=> Addition: North Iowa Area Community College

lib/domains/bd/edu/uctc.txt, lib/domains/id/ac/its.txt
- University of Creative Technology Chittagong
=> Added University of Creative Technology Chittagong

lib/domains/at/ac/phwien.txt
Pädagogische Hochschule Wien
Official website: https://phwien.ac.at/
Study (Information und Kommunikation (Angewandte Digitalisierung): https://phwien.ac.at/bac_information_kommunikation/
Email accounts: https://phwien.ac.at/wp-content/uploads/2021/05/Office365_phwien_studenInnen.pdf
Incoming Guid: https://phwien.ac.at/wp-content/uploads/2023/02/DE_Study-Guide.pdf
Contact: christian.tomaschitz@phwien.ac.at, martin.berger@phwien.ac.at
=> phwien.ac.at

lib/domains/in/ac/akgec.txt
Adding "[Ajay Kumar Garg Engineering College, Ghaziabad](https://www.akgec.ac.in/)" to the list (@akgec.ac.in)
=> Add AKGEC college

lib/domains/pe/edu/autonomadeica.txt
Página Web Oficial: https://portal.autonomadeica.com/
Enlace de programa de estudios: https://portal.autonomadeica.com/pregrado/ingenieria-de-sistemas/
actualmente el dominio @autonomadeica.edu.pe se usa para correos de estudiantes.
=> Add Universidad Autónoma de Ica

lib/domains/vn/vnu.txt
university website: https://uet.edu.vn/
=> Add UET-VNU

lib/domains/in/ac/ldrp.txt
Here, is the latest details about to update "LDRP Institute of Technology and Research"
=> LDRP Institute of Technology and Research

lib/domains/aimt.txt, lib/domains/in/edu/aimt.txt
added  Ambalika Institute of Management and Technology
=> added college domain

lib/domains/in/ac/psit.txt
Added my college name to the repository, please help me with providing the student offer of JetBrains.
=> Add pranveer singh institute of technology college, kanpur, india

lib/domains/id/ac/utu.txt
=> Add Universitas Teuku Umar 

lib/domains/in/edu/rkgit.txt
College Official URL - https://rkgit.edu.in/
College Courses URL - https://rkgit.edu.in/Departments/courses/
=> Raj Kumar Goel Institute Of Technology

lib/domains/at/ac/hak-reutte.txt
Added domain of Bundeshandelsakademie Reutte und HTL Reutte to the repository
=> Added Bundeshandelsakademie Reutte und HTL Reutte

lib/domains/id/ac/pradita.txt
Add a domain/university (pradita.ac.id/Pradita University) that hasn't been recognized by JetBrains
=> Add Pradita University / Universitas Pradita

lib/domains/mt/edu/epicode.txt
=> Added epicode.txt

lib/domains/org/nandhaarts.txt
College Website: https://www.nandhaarts.org/
College Website Image:
=> Nandha arts and science college

lib/domains/in/edu/manuu.txt
University Addition: Maulana Azad National Urdu University
I am happy to contribute by adding **Maulana Azad National Urdu University** (MANUU), a highly regarded central university.
This integration expands the repository's reach to include another key institution from India, contributing to a more robust and complete list for all JetBrains users and consumers of this repository.
=> Add Maulana Azad National Urdu University

lib/domains/in/ac/iiitdm.txt
Adding Indian Institute of Information Technology, Design and Manufacturing, Kancheepuram - IIITDM K
=> Adding Indian Institute of Information Technology, Design and Manufacturing, Kancheepuram

lib/domains/in/co/bmionline.txt
=> Added BMIT College 

lib/domains/pk/edu/stmu.txt
Adding a new University
Shifa Tameer e Millat University
=> Shifa Tameer e Millat University 

lib/domains/jp/ac/chitose/photon.txt
Chitose Institute of Science and Technology
Official website: https://www.chitose.ac.jp/
English : https://www.chitose.ac.jp/english/ 
IT related course website: https://www.chitose.ac.jp/course/rikou/ise
English: https://www.chitose.ac.jp/english/info/rikou/ise/
=> Add photon.txt with university names

lib/domains/jp/ac/nanzan-u.txt
Add Nanzan University.
Official Web (in Japanese)  https://www.nanzan-u.ac.jp/
Official Web (in English)  https://www.nanzan-u.ac.jp/English/
IT related course (in Japanese)  https://www.nanzan-u.ac.jp/Dept/fot.html
IT related course (in English)  https://www.nanzan-u.ac.jp/English/academics/undergraduate/ts/
=> Add Nanzan University

lib/domains/jp/ac/iput.txt
International Professional University of Technology in Osaka
https://www.iput.ac.jp/osaka/english/
=> add International Professional University of Technology in Osaka

lib/domains/in/ac/cusat.txt
Hello, I added Cochin University of Technology and Science.
=> added graduate Cochin University

lib/domains/ch/metas.txt
Info about METAS as an accredited academic institution: 
https://www.metas.ch/metas/de/home/metas/institut.html 
Courses offered by METAS:  
https://www.metas.ch/metas/de/home/dl/kurs_uebersicht.html#-1865450343
=> Swiss Federal Institute of Metrology

lib/domains/ph/edu/fia.txt
- Official Website: fia.edu.ph
- We are a western style K-12 Academy in Davao City, Philippines. Our staff is comprised of volunteer missionaries. We offer coding electives including php on a case by case basis. Largely driven by class interest, to high-schoolers. We also host a rapidly growing internal code base for our hot lunch program that I (the admin) am working to expand over the next few years that is written in Laravel PHP. It would suit our school well to be able to offer php coding as an elective and give the students access to your excellent IDE platform! I plan to volunteer to host such an elective if we are approved. Thank you for your consideration!
=> Adding Faith International Academy

lib/domains/de/medicalschool-hamburg.txt
see https://www.medicalschool-hamburg.de/
=> add medical school hamburg

lib/domains/de/esgy/schueler.txt
Ernst Sigle Gymnasium
Site: https://esgy.de/
=> Ernst Sigle Gymnasium

lib/domains/jp/ac/neec/g.txt
Adding my school domain neec.ac.jp for JetBrains student license verification.
=> Add [School Name] domain for JetBrains student license

lib/domains/cl/correoaiep.txt
Add correoaiep.cl (Instituto Profesional AIEP)
- Official website: https://www.aiep.cl
=> Add files via uploadAdd correoaiep.cl (Instituto Profesional AIEP)

lib/domains/et/edu/ju2.txt
This PR adds the domain `ju2.edu.et` used for student email accounts at **Jimma University** in Ethiopia.
- `ju.edu.et` is already listed in the repository.  
- Website: https://ju.edu.et
- IT Departments: https://ju.edu.et/jit/faculties-and-schools/faculty-of-computing-and-informatics/departments-chairs/
- `ju2.edu.et` is a secondary domain operated by Jimma University IT for student emails.  
1. Screenshot of an inbox showing a valid `@ju2.edu.et` email account (attached below).  
2. Raw email headers proving emails originate from this domain:
```
Delivered-To: kitessafikadu@gmail.com
Received: by 2002:a05:6504:1acb:b0:2c3:c5d7:2ccb with SMTP id q11csp40114ltx;
Sat, 6 Sep 2025 02:45:51 -0700 (PDT)
X-Google-Smtp-Source: AGHT+IHOk6y0+RrVuEcVeNkr/cZzJAOSah1LiwTJXmT/UXyTHByiRIoGEzAaiPN6JXZLD …
```
=> Add Jimma University student email domain ju2.edu.et

lib/domains/de/osztiem-edu.txt, osztiem-edu.txt
{OSZ TIEM (Oberstufenzentrum Technische Informatik, Industrieelektronik, Energiemanagement)}
{[Website URL](https://www.osztiem.de/)}
my school mail domain: 
https://osztiem-edu.de/
[majed.asaad@osztiem-edu.de](mailto:majed.asaad@osztiem-edu.de)
please unlock the domain to let all Students join @osztiem-edu.de domain
=> Add OSZ TIEM (Oberstufenzentrum Technische Informatik, Industrieelektronik, Energiemanagement)

lib/domains/np/edu/pahs.txt
Added Patan Academy of Health Sciences (PAHS).
=> Added Patan Academy of Health Sciences (PAHS)

lib/domains/id/ac/hacktiv8.txt
This pull request adds Hacktiv8 to the list of domains in `lib/domains/id/ac/hacktiv8.txt`, expanding the domain coverage.
=> Add Hacktiv8 domain file (hacktiv8.ac.id)

lib/domains/kr/ac/namhae.txt
Add new domain University Of Gyeongnam Namhae
namhae.ac.kr
=> Add new domain University Of Gyeongnam Namhae

lib/domains/kz/kazgasa.txt
University: Kazakh Leading Academy of Architecture and Civil Engineering
Domain: kazgasa.kz
File: lib/domains/kz/kazgasa.txt
Website: https://kazgasa.kz/
=> Add Kazakh Leading Academy of Architecture and Civil Engineering

lib/domains/in/ac/skuastkashmir.txt
Please add Sher e Kashmir University of Agricultural Sciences and Technology of Kashmir "https://skuastkashmir.ac.in/".
=> skuastkashmir

lib/domains/np/edu/viswaniketan.txt
Added the domain viswaniketan.edu.np for Viswa Niketan Secondary School in Nepal.
=> Add viswaniketan.edu.np domain

lib/domains/ar/edu/undav.txt
Institution name:
•	Universidad Nacional de Avellaneda
•	National University of Avellaneda
Official website: https://www.undav.edu.ar
=> Add Universidad Nacional de Avellaneda (undav.edu.ar)

lib/domains/pk/edu/mykasbit.txt
University: KASB Institute of Technology
Website: https://kasbit.edu.pk/
Bachelors Degree: https://kasbit.edu.pk/bs-software-engineering/
Proof of Email Domain: See attached screenshot showing student email address (std_xxxx@mykasbit.edu.pk) managed by mykasbit.edu.pk
=> Add KASB Institute of Technology (mykasbit.edu.pk) domain

lib/domains/pe/cibertec.txt
Hello, I'm asking to review this commit about my institute located in Peru to access to the IntelliJIDEA Educational License.
=> Add Cibertec.txt

lib/domains/com/onmicrosoft/jdarcbretigny.txt
Sorry, I accidentally removed my previous fork and pull request.
=> Add lib/domains/com/onmicrosoft/jdarcbretigny.txt
