- lib/domains/rs/singimail.txt
Even though there is @singidunum.ac.rs as and email option for Singidunum University mails, it is used only by professors. Students use @singimail.rs only
> Added Singidunum University

- lib/domains/dk/elevcampus.txt
Adding EUC Syd - Teknisk Gymnasium Sønderjylland (Higher Technical Examination Programme) with the website http://eucsyd.dk
> Adding elevcampus.dk

- lib/domains/it/unikore.txt
- lib/domains/it/unikorestudent.txt
Added main domain (unikore.it) and students domain (unikorestudent.it) for Università degli Studi di Enna "Kore" (Enna - Italy)
> University of Enna "KORE" adedd

- lib/domains/org/madeiracityschools.txt
Added Madeira City Schools (http://www.madeiracityschools.org). A school district in Madeira, OH.
> Add Madeira City Schools

- lib/domains/de/hochschule-rhein-waal.txt
- lib/domains/eu/hsrw.txt
_hochschule-rhein-waal.de_ => `lib/domains/de/hochschule-rhein-waal.txt`
_hsrw.eu_ => `lib/domains/eu/hsrw.txt`
> Entries for "Hochschule Rhein-Waal" domains added

- lib/domains/net/uninettunouniversity.txt
The UniNettuno University (Italian: Università telematica internazionale UniNettuno), often simply abbreviated as "UniNettuno" is a private university founded in 2005 in Rome, Italy.
Website: www.uninettunouniversity.net
> Add Universita telematica internazionale UniNettuno

- lib/domains/pl/torun/gimakad.txt
Part of Nicolaus Copernicus University in Toruń. To check site, use
adress with 'www' (www.gimakad.torun.pl - website have a problem with adress without 'www').
> Add www.gimakad.torun.pl

- lib/domains/com/epschoolsri.txt
This is a pull request to add East Providence Public Schools to swot. epschoolsri.com is the primary domain used for email by all students and faculty in the district, including East Providence High School. The district is k-12.
Primary school website: eastprovidencehighschool.com
District website: epschoolsri.com
Student emails are in the format of: [last two digits of graduation year][first initial][last name][first two digits of student id]@epschoolsri.com
Thank you! :)
> Adding East Providence Public Schools 

- lib/domains/be/openuniversiteit.txt
After ou.nl (Its Dutch counterpart) has already been added openuniversiteit.be should be added too.
> Added openuniversiteit.be

- lib/domains/uk/co/wg6.txt
Adds the wg6.co.uk School's domain.
> Add wg6.co.uk to education domains

- lib/domains/nu/reggesteyn.txt
http://reggesteyn.nl is school domain (emails at .nl are for staff, .nu is for students.)
Location: 2 schools in Nijverdal, 1 in Rijssen
> Add CSG Reggesteyn

- lib/domains/aero/mstuca.txt
Added Moscow State Technical University of Civil Aviation (mstuca.aero)
https://en.wikipedia.org/wiki/Moscow_State_Technical_University_of_Civil_Aviation
> Add MSTU CA

- lib/domains/org/lsrhs.txt
lsrhs.org is the new google apps domain for Lincoln-Sudbury Regional
High School which is being fully implemented next academic year.
> Added lsrhs.org

- lib/domains/org/park6.txt
Park6.org is the official domain of Park County School District #6 in Cody, WY.  All associated email accounts are faculty and students. [Link](http://www.park6.org)
> Add Park6.org (K-12 public school)

- lib/domains/ua/kiev/unicyb.txt
Added Cybernetics Faculty, National Taras Shevchenko University of Kiev, we have separate mail server as you can see on our website main page: http://www.cyb.univ.kiev.ua/en.html
Oleksandr Maksymets, Professor Assistant
> Added Cybernetics Faculty, Taras Shevchenko National University of Kyiv

- lib/domains/mk/fon.txt
FON University is currently providing student emails at the fon.mk domain, and only uses the fon.edu.mk domain for staff emails.
> Add fon.mk domain

- lib/domains/com/kkumail.txt
Khon Kaen University has two domain for... 
teacher & staff : kku.ac.th
student : kkumail.com (please add this).
Thank you in advance.
> Add Khon Kaen University's Domain for student email.

- lib/domains/ua/net/univ.txt
new (from 2009) mail server of National Taras Shevchenko University of Kiev.
mail.univ.net.ua
> mail server of National Taras Shevchenko University of Kiev

- lib/domains/ie/mumail.txt
NUI Maynooth recently changed its name, see here
https://www.maynoothuniversity.ie/communications-marketing/university-identity-guidelines
@mumail.ie is our mail server
@nuim.ie is still used by some staff
> Adding mumail (Maynooth University)

- lib/domains/org/erpsk12.txt
This domain is used by the Eaton Rapids Public Schools district.
One question, will this cover a subdomain for students (eg, `students.erpsk12.org`)? If not, should I create another text file to cover that?
> Added erpsk12 to the list

- lib/domains/org/wctech.txt
[Warren County Technical School](http://www.wctech.org) is a technical high school in New Jersey.  While it isn't a university, the age-range is comparable to colleges in other countries.
> Add wctech.org

- lib/domains/com/cqumail.txt
CQU (www.cqu.edu.au) put their student email on cqumail.com. Detailed
here : http://policy.cqu.edu.au/Policy/policy_file.do?policyid=642
> Add Central Queensland University

- lib/domains/br/lncc.txt
Adding LNCC - Laboratório Nacional de Computação Científica as an academic institution.
link: http://www.lncc.br/
> Add Laboratório Nacional de Computação Científica

- lib/domains/au/edu/tas/education.txt
- lib/domains/au/edu/tased.txt
- lib/domains/au/gov/tas/education.txt
Adds the three email domains belonging to Department of Education schools in Tasmania, Australia.
These domains are:
- `education.tas.gov.au`
- `education.tas.edu.au`
- `tased.edu.au`
> Add Department of Education Tasmania, Australia

- lib/domains/ca/ocadu.txt
ocadu.ca is the primary domain for OCAD University, formerly known as the Ontario College of Art & Design.
> Added domain for OCAD(Ontario College of Art and Design) University

- lib/domains/nl/edu-kw1c.txt
The students of koning willem 1 college are using a @edu-kw1c.nl domain for there mail.
> Added edu-kw1c.nl

- lib/domains/de/hswt.txt
Add a file for Weihenstephan-Triesdorf University of Applied Sciences,
(HSWT), formerly known as fh-weihenstephan.de
> Add Weihenstephan-Triesdorf University of Applied Sciences

- lib/domains/com/manukaumail.txt
The students use manukaumail.com. Manukau.ac.nz is only for school staff. Thank you.
> Create manukaumail.txt, please

- lib/domains/fi/hanken.txt
Staff accounts at the base domains, students from student.hanken.fi.
> Added Hanken School of Economics

- lib/domains/pe/urp.txt
Universidad Ricardo Palma changed its domain from @urp.edu.pe to @urp.pe
> Added Universidad Ricardo Palma

- lib/domains/fi/turku/edu.txt
Most higher education schools in Turku have a domain of edu.turku.fi
> Add Turku schools with edu mail addresses

- lib/domains/org/friscoisd.txt
Added Centennial High School as part of the Frisco Independent School District.
Student Emails: first.last.XXX@k12.friscoisd.org
Staff Emails: last(FirstLetterOfFirstName)@friscoisd.org
Only School Administration can create emails.
> Add Centennial High School

- lib/domains/ca/ab/mtroyal.txt
- lib/domains/ca/stmu.txt
@smtu.ca is the email domain for students, @smu.ca is for teachers. smu already exists... just added  @stmu.ca and corrected the name for mount royal as it is now a university and identifies with their new name.
> 2 Calgary, Ab, Canada Institutions

- lib/domains/be/ucll.txt
Hello,
A part of GroepT has been split of and merged into a new college collaboration; UCLL
I have added the domain here so our students can continue to benefit having access to the JetBrains software which we use for our ICT education programs.
Thank you.
Koen.
> Adding UCLL (University College Leuven-Limburg)

- lib/domains/cat/uib.txt
Alias for the University of the Balearic Islands (the other one is es/uib.txt).
> Added cat/uib.txt

- lib/domains/gr/ssl-unipi.txt
You can validate it at http://ssl-unipi.gr
> Add Systems Security Laboratory, University of Piraeus

- lib/domains/nl/alfa-college/student.txt
Alfa College is situated in both Groningen and Hoogeveen in the Netherlands
The school has been taking benefit of using Jetbrain products for a while now, but only just recently got their own domain and email addresses for students.
Website: http://alfa-college.nl
> Add @student.alfa-college.nl domain for Alfa College

- lib/domains/cl/udd.txt
- lib/domains/cl/udd/ingenieros.txt
these are the current domains for universidad del desarrollo, as a proof you can go to the university page
http://www.udd.cl/contacto/
and check the admission email at the botom : admision@udd.cl
the ingenieros.udd.cl is the subdomain for the engineers.
> This are the current domains for universidad del desarrollo chile

- lib/domains/de/udk-berlin.txt
http://www.udk-berlin.de/ Domain only accessible with www.
> http://www.udk-berlin.de/ Universität der Künste Berlin

- lib/domains/de/fh-duesseldorf.txt
- lib/domains/de/hs-duesseldorf.txt
'Fachhochschule Düsseldorf' is now called 'Hochschule Düsseldorf'.
> Update and rename fh-duesseldorf.txt to hs-duesseldorf.txt

- lib/domains/de/dhbw/mosbach/lehre.txt
New domain for http://dhbw-mosbach.de/ (old one is still in use).
> Added lehre.mosbach.dhbw.de

- lib/domains/hamburg/avh.txt
domain is only in use for the school server and emails
webpage is at http://avh.schulhomepages.hamburg.de/
proof of use: http://avh.schulhomepages.hamburg.de/?page_id=36 email of
the "Betreuer der Homepage"
> added avh.txt

- lib/domains/ru/nnov/uic.txt
Added uic.nnov.ru that hosts mail server of Lobachevsky State University of Nizhni Novgorod
> Lobachevsky State University of Nizhni Novgorod

- lib/domains/kr/kau.txt
Korea Aerospace University has been added since its previous name
(Hankuk Aviation University) is no longer used recently and we replaced
it to Korea Aerospace University.
PLEASE NOTE IT :D
And I located this file beneath the direct location of ‘kr’ rather than
file replacement. Because our web-mail system has been ended and they
encourages to use Office 365 account associated with Academic domain.
Our previous domain was account@kau.ac.kr but now we can use web mail
with account@kau.kr.
> Add Korea Aerospace University

- lib/domains/org/ttsdstudents.txt
Adding lib/domains/org/ttsdstudents.txt - Tualatin High School (http://tuhs.ttsdschools.org). You can verify that ttsdstudents.org is the student's email domain by going to http://google.ttsd.k12.or.us/students.html. That's the login page students use to check their email where you can see the domain name listed as part of the user name.
> Adding lib/domains/org/ttsdstudents.txt - Tualatin High School

- lib/domains/cc/cwidaho.txt
The College of Western Idaho has two email domains: "@mycwi.cc" for student emails, and "@cwidaho.cc" for faculty members.  This commit adds the faculty domain.
> Add the faculty domain for the College of Western Idaho

- lib/domains/zm/unza.txt
The current text file describing the University of Zambia -> /lib/domains/zm/unza/www.txt is invalid as it assumes the domain name for the University is www.unza.zm when www is simply a subdomain. This raises an issue as subdomains like cs.unza.zm cannot be identified as valid sub domains.
This submission corrects the entry to /lib/domains/zm/unza.txt which is the correct representation of the *.unza.zm domain names
> Create Valid University of Zambia Domain Name

- lib/domains/hr/gradst.txt
University of Split Faculty of Civil Engineering, Architecture and Geodesy
Webiste - http://gradst.unist.hr/
> University of Split Faculty of Civil Engineering, Architecture and Geodesy

- lib/domains/ca/on/wrdsb.txt
- lib/domains/ca/wrdsb/googleapps.txt
- lib/domains/ca/wrdsb/ins.txt
[Waterloo Region District School Board](http://www.wrdsb.ca/) has three email paths for students and staff: @ins.wrdsb.ca, @googleapps.wrdsb.ca, and @wrdsb.on.ca.
> Add WRDSB (Canada) email domains

- lib/domains/ch/ge/edu.txt
Added edu.ge.ch, aka the Département de l'Instruction Publique du Canton de Genève, aka the public schools of Geneva.
> Added edu.ge.ch

- lib/domains/in/ac/iitbbs.txt
- lib/domains/in/ac/iitgn.txt
- lib/domains/in/ac/iitj.txt
- lib/domains/in/ac/iitp.txt
- lib/domains/in/ac/iitrpr.txt
These colleges offer 4 years B.Tech program in Computer Science and Engineering. These are new IITs ([info](https://en.wikipedia.org/wiki/Indian_Institutes_of_Technology)) missing from the list
- iitbbs.ac.in ([curriculum](http://www.iitbbs.ac.in/btech-curriculum.php))  
- iitgn.ac.in ([info](http://cs.iitgn.ac.in/?page_id=44))
- iitj.ac.in ([PDF](http://iitj.ac.in/uploaded_docs/Curricula/Curricula%20CSE.pdf))
- iitp.ac.in ([curriculum](http://www.iitp.ac.in/index.php/academics/programmes/undergraduate/course-curriculum.html))
- iitrpr.ac.in ([info](http://www.iitrpr.ac.in/cse))
> Add missing IITs

- lib/domains/org/smolny.txt
Please add the Faculty of Liberal Arts and Sciences (_Smolny College_) of Saint Petersburg State University. 
The official website is http://artesliberales.spbu.ru, however, email is hosted at http://mail.smolny.org (http://smolny.org also redirects to the official website). 
To verify this, you may look for contacts in the footer of the website.
The faculty has a fully-fledged computer science major track. Most of the courses from the curriculum are listed here: http://artesliberales.spbu.ru/academics/katalog-kursov?bm=bakalavr&ct=&programm=cmsc&lang=  This page is in Russian language only, though.
Besides, WHOIS info (https://who.is/whois/smolny.org) points at Bard College in NY, since the faculty actually provides a joint degree program between Bard College and Saint Petersburg State …
> Add Smolny College of Saint Petersburg State University

- lib/domains/jp/kosen-ac/fukushima.txt
Please add the domain of National Institute of Technology, Fukushima College.
This collage is affiliated with the National Institude of Technology.
So, Whois Infomation is the same of Hachinohe Collage.
> Add NIT, Fukushima College

- lib/domains/in/edu/nitk.txt
Added to the list is - National Institute of Technology Karnataka.
Official website address - http://nitk.ac.in
Mail server - http://nitk.edu.in
[This JSON from WHOIS API](https://www.whoisxmlapi.com/whoisserver/WhoisService?domainName=nitk.edu.in&outputFormat=json) from WHOIS shows proof that http://nitk.edu.in is indeed owned by our college.
http://www.nitk.ac.in/webmail proves on our college site that the domain is indeed owned by our college AND is used by the students
Please note that our college is commonly abbreviated as NITK
> Added "National Institute of Technology Karnataka"

- lib/domains/org/rhsfultonschools.txt
rhsfultonschool.org is the email domain for Roswell High School
in Roswell, Georgia, USA, part of Fulton County Schools.
Note: fultonschools.org is already in the list of accepted
domains, but covers the entire county K-12. rhsfultonschools.org
is only for Roswell High School.
> Add rhsfultonschools to the list of .org academic domains.

- lib/domains/ua/ks/university.txt
Add synonym for Kherson State University.
This university already in the list with domain university.kherson.ua, but university.ks.ua is synonym for it and the most of students use the short version
> Add synonym for Kherson State University

- lib/domains/ch/ti/edu.txt
Added the domain edu.ti.ch, this domain is used by a lot of school in south of Switzerland (swiss italian). It's used by almost all professional school (http://www4.ti.ch/decs/) like this one http://www4.ti.ch/decs/ds/portale-scuole/scuole-professionali/dettaglio/?user_decsscuole_pi1%5Bscu_id%5D=69 where I work and I teach Software Developing in Java, Swing and PHP (http://www.spailocarno.ch/spai/download.php?id=233).
> Added domain edu.ti.ch

- lib/domains/de/hsw-hameln.txt
http://www.hsw-hameln.de/
http://www.hsw-hameln.de/bildungs-studienangebote/duales-studium/programm/wirtschaftsinformatik-bsc/
> add Hoschule Weserbergland as de/hsw-hameln

- lib/domains/no/vfk.txt
Domain used by multiple schools that specialize in different things.
**Subdomains:**
skole.vfk.no - used by students
> Added Vestfold Fylkeskommune (vfk.no)

- lib/domains/jp/ac/tokuyama.txt
Please add the domain of National Institute of Technology, Tokuyama College.
This college is affiliated with the National Institute of Technology.
> Add NIT, Tokuyama College

- lib/domains/ch/phlu.txt
Lucerne University of Teacher Education (PHLU Luzern)
> Add Lucerne University of Teacher Education (Switzerland)

- lib/domains/ru/rggu.txt
rggu.ru is the new domain for the Russian State University for the Humanities
> rggu added to domain list

- lib/domains/org/fa.txt
This pull request adds an entry for [Friends Academy](www.fa.org), an independent Quaker college-preparatory private school located in Long Island, serving Early Childhood through 12th grade.
Please see page 13 of the [Academic Pathways document](https://www.fa.org/uploaded/US_Attachments/2016-17_Pathways.pdf) for proof of a long-term IT-related course offering.
Please see [this partial screenshot](http://ww2.fa.org/static/swot-pull-request-screenshot.png) of the faculty-accessible student directory, showing that student email addresses use the domain @fa.org.
> Add Friends Academy (fa.org)

- lib/domains/br/ucdb.txt
UCDB - Universidade Católica Dom Bosco
(or Dom Bosco Catholic University)
[http://site.ucdb.br/](http://site.ucdb.br/)
One of their IT courses:
[http://site.ucdb.br/cursos/4/graduacao/26/engenharia-de-computacao/193/](http://site.ucdb.br/cursos/4/graduacao/26/engenharia-de-computacao/193/)
> added UCDB to domains

- lib/domains/uk/org/etoncollege.txt
The main url is http://www.etoncollege.com/
They offer a 2 year GCSE course (equivalent of first two years of high school) in Computer Science [here](http://www.etoncollege.com/e_d_block.aspx)
All emails on the site (for example the web clerk webclerk@etoncollege.org.uk at the bottom of every page) use the .org.uk domain. They don't have many emails publicly but every one there uses the etoncollege.org.uk domain.
See also http://www.etoncollege.com/EtonEmail.aspx which links to a page where the domain is verified.
> Add Eton College

- lib/domains/fr/ecetech/edu.txt
- lib/domains/fr/edu/ecetech.txt
New email address for ece.fr to edu.ecetech.fr
(http://www.ecetech.fr/) is a French IT university.
The edu extension is only for email addresses.
(Maybe my path is wrong ? I want @edu.ecetech.fr)
> New address for ECE

- lib/domains/edu/Olivet.txt
- lib/domains/edu/olivet.txt
- lib/domains/edu/olivetuniversity.txt
Before this PR, there was lib/domains/edu/Olivet.txt file with content Olivet University. However, domain of Olivet University is olivetuniversity.edu while olivet.edu is domain for Olivet Nazarene University. This PR distinguish those 2 different institution with correct name and domain.
> Distinguish Olivet University and Olivet Nazarene University

- lib/domains/de/fh-brandenburg.txt
- lib/domains/de/th-brandenburg.txt
See commit comments.
you can see that the name changed in multiple official news and the uni's website. Here's one such link from the news:
http://www.skb-tv.de/news/fh-brandenburg-bekommt-neuen-namen/
> Name Change of Fachhochschule Brandenburg to Technische Hochschule Brandenburg

- lib/domains/no/bfk/vgs.txt
Domain used by multiple schools in Buskerud, Norway.
Majority of the schools has technology oriented studies.
**Mail domain:**
vgs.bfk.no
**Buskerud county website:**
[bfk.no](http://bfk.no)
**List of schools:**
[http://www.bfk.no/Tjenesteomrade/Utdanning/videregaende-skole/Skoler-og-Arbeidsinstitutt/](http://www.bfk.no/Tjenesteomrade/Utdanning/videregaende-skole/Skoler-og-Arbeidsinstitutt/) (In Norwegian)
> Add Buskerud fylkeskommune

- lib/domains/uk/ac/qmul.txt
Information for adding the domain quicker:
- [University official website URL](http://www.qmul.ac.uk)
- [BSc (Hons) Computer Science](http://www.qmul.ac.uk/undergraduate/coursefinder/courses/80043.html#second), 3 year course
- On the [email section](http://www.its.qmul.ac.uk/services/students/email/) of Services for students is a link to information for [setting up email in an IMAP client](http://www.its.qmul.ac.uk/support/self-help/email_setup/settingupemail/143256.html), which indicates the students email address is their  Username followed by @qmul.ac.uk.
> Added domain file for Queen Mary, University of London

- lib/domains/jp/kosen-ac/kagawa.txt
Please add the domain of National Institute of Technology, Kagawa College.
This collage is affiliated with the National Institude of Technology.
So, Whois Infomation is the same of Kagawa Collage.
> Add NIT, Kagawa College

- lib/domains/se/goteborg/educ.txt
Added university Yrgo, one of many under the educ.goteborg.se domain. Emails for those universities under the domain is formatted _firstname.lastname@educ.goteborg.se_.
The main site for Yrgo is [http://yrgo.se](http://yrgo.se)
The web development program that I am a teacher at has an information page located at [http://yrgo.se/utbildningar/media-och-kommunikation/webbutvecklare/](http://yrgo.se/utbildningar/media-och-kommunikation/webbutvecklare/)
You can see that all contact information is using email addresses containing educ.goteborg.se  - including this pdf [http://yrgo.se/wp-content/uploads/auto-pdf-generation/webbutvecklare/webbutvecklare-20160422.pdf](http://yrgo.se/wp-content/uploads/auto-pdf-generation/webbutvecklare/webbutvecklare-20160422.pdf)
The content is in Swedish, I hope …
> Added Yrgo university

- lib/domains/se/goteborg/skola.txt
Added student mail domain for Yrgo University & Gothenburg education. Emails for the students are formatted as: _firstname.lastname@skola.goteborg.se_.
This pullrequest is a follow up to: https://github.com/JetBrains/swot/pull/2212
The students are using Google Apps For Education to sign in to their emails, so I do not have a portal available with more information. The information they get say that they will sign in at http://epost.skola.goteborg.se. 
Pleas let me know if you will need something more. Regards.
> Added Yrgo, gothenburg education student mail domain

- lib/domains/ro/umf.txt
- lib/domains/ro/univermed-cdgm.txt
Hello,
This is a PR to modify the older, unused domain name 'univermed-cdgm.ro' of the 'Carol Davila University of Medicine Bucharest'. The domain in use is 'umf.ro' for web and email. See http://www.univermed-cdgm.ro vs. http://www.umf.ro.
Our university offers 1-year pre-graduate courses in IT (including biostatistics and medical informatics) and also a master in Medical Biophysics and Cell Biotechnology. Unfortunately, there is no description on the University web site of the former, but details are available (in Romanian) regarding the latter [here](http://umf.ro/index.php/facultati/medicina-generala/89-facultati/medgen/departamente-discipline/477-masterat-biofizica-si-biotehnologie-celulara). There is also a [brochure](http://umf.ro/images/PDF/Departamente_Discipline/brosuramartie_201 …
> Modify the domain name for the University of Medicine Bucharest

- lib/domains/us/tn/k12/rcs/central.txt
I'm interested in having my school added to this list.
The domain of my school is [central.rcs.k12.tn.us](http://central.rcs.k12.tn.us). However, the domain for the district is simply [rcschools.net](http://rcschools.net).
This school has an AP Computer Science class and two other programming courses, all of which last one year. Proof for all of these classes' existence can be found [here](http://central.rcs.k12.tn.us/courses.html) on page 8.
My school issues email addresses. This can be proved by going to [email.rcschools.net](http://email.rcschools.net), which brings up a login field, showing there is an email server there.
I understand that the school emails are issued at a different domain than that of the school website. If this means that I need to change the pull request in some …
> Add Central Magnet School

- lib/domains/at/or/klg.txt
Website: http://www.klg.or.at/
Post-secondary 3-year specialization in informatics see http://www.klg.or.at/faecher/wahlpflichtfaecher?s=INF_plus
Staff and students use this mail domain, see e.g. http://www.klg.or.at/lehrer
> Add Konrad Lorenz Gymnasium (klg.or.at)

- lib/domains/at/htlkrems.txt
- lib/domains/com/onmicrosoft/htlkrems3500.txt
HTL Krems changed its network and domain. Actually, the webpage is only accessible via the old URL: http://www.htlkrems.ac.at; In future, all services should be migrated to htlkrems.at
Changes: htlkrems3500.onmicrosoft.com -> htlkrems.at
[photo_2016-09-15_18-06-49](https://cloud.githubusercontent.com/assets/21141148/18557486/7528b9e4-7b6f-11e6-9243-d9e4bad6b71d.jpg)
> HTL Krems changed its domain

- lib/domains/ca/yrdsb.txt
A simple visit to yrdsb.ca reveals that it is the York Region District School Board instead of just Thornhill Secondary School (which is in the YRDSB).
> yrdsb.ca is York Region District School Board

- lib/domains/fr/etu-webschoolfactory.txt
- lib/domains/fr/prof-webschoolfactory.fr
- lib/domains/fr/webschoolfactory.txt
Added the 3 domains of the Web school factory.
This is a 5 year web school, in Paris, France.
The domains are : 
`webschoolfactory.fr` : main domain
`etu-webschoolfactory.fr` : Domain used for students e-mail addresses
`prof-webschoolfactory.fr` : Domain used for teachers e-mail addresses
> Added Web school factory

- lib/domains/de/gymnasium-rhauderfehn.txt
- lib/domains/eu/gymnasium-rhauderfehn.txt
Moved gymnasium-rhauderfehn.de to gymnasium-rhauderfehn.eu
> Updated Gymnasium Rhauderfehn

- lib/domains/pl/pollub.txt
This domain is available only for teachers.
> Added Lublin University of Technology (pollub.pl)

- lib/domains/se/ju.txt
Old domain is hj.se, new one is ju.se  (This changed took place earlier and no longer are mails forwarded)
> New domain for Jönköping University.

- lib/domains/gr/teiwest.txt
Technological Educational Institute of Messolonghi (TEIMES) and Technological Educational Institute of Patras (TEIPAT) were merged in 2013 to Technological Educational Institute of Western Greece (TEIWEST).
This change reflects this merge.
Student email addresses are now in the process of migrating to the new teiwest.gr domain.
Not removing the old teipat.gr and teimes.gr as I expect most of the emails there are still being used.
> Add teiwest.gr to the school domains data

- lib/domains/jp/kosen-ac/toyota.txt
Please add the domain of National Institute of Technology, Toyota College.
Our college is also called Toyota Kosen.This collage is affiliated with the National Institude of Technology.
So, Whois Infomation is the same of Toyota Collage.
> Add NIT, Toyota College

- lib/domains/kr/ac/incheon.txt
- lib/domains/kr/ac/inu.txt
They have 3 domains; incheon.ac.kr, inu.ac.kr, and inchon.ac.kr(deprecated).
> Added more domains for Incheon National University

- lib/domains/nl/driestarleerling.txt
> "driestarleerling.nl" is the domain for school-related Microsoft-accounts (+ e-mail) assigned to pupils of the Driestar College.
Pull request #2507 closed, cannot reopen it as I'm not an owner or editor.
my [last comment](https://github.com/JetBrains/swot/pull/2507#issuecomment-269216445) there should resolve the issue of verifying if the domain actually belongs to the school.
> Add Driestar College

- lib/domains/nl/csgaugustinus.txt
"csgaugustinus.nl" is the domain for school-related Microsoft-accounts (e-mail included) assigned to pupils of CSG Augustinus.
> Added CSG Augustinus (Groningen)

- lib/domains/fr/bde-insa-lyon.txt
- lib/domains/org/insa-lyon.txt
Register alternate domain for INSA Lyon.
This domain is an alias of bde.insa-lyon.org and is used by the student organization of the school.
> Add domain for INSA Lyon

- lib/domains/org/dcsdk12.txt
- lib/domains/org/dcsdk12/s.txt
The normal dcsdk12.org domain is for the teachers, and s.dcsdk12.org is
for the students
Website: [https://www.dcsdk12.org/high-school-education](https://www.dcsdk12.org/high-school-education)
Year-long Course (Page 34, AP Computer Science A): [http://www.legendtitans.org/assets/courseguide.pdf](http://www.legendtitans.org/assets/courseguide.pdf)
Proof of student email:
NOTE: I'm not quite sure whether I needed to create a file for the s.dcsdk12.org domain if the dcsdk12.org file is already in there.
> Added Douglas County School District

- lib/domains/nl/hetbaarnschlyceum.txt
hetbaarnschlyceum.nl is the e-mail domain used by teachers/students at Het Baarnsch Lyceum
> Added Het Baarnsch Lyceum

- lib/domains/ca/qc/clg.txt
Quebec CEGEP / College.
Here is its website: http://www.clg.qc.ca/
> Added clg.qc.ca domain

- lib/domains/org/ccaschools.txt
Adds Clear Creek Amana High.
http://www.ccaschools.org/index.php/high-school
> Add Clear Creek Amana High School

- lib/domains/de/mpg/tue.txt
Max Planck Institute for Intelligent Systems, Tuebingen, Germany with domain names *.tue.mpg.de
> Adding tue.txt

- lib/domains/de/mpg/is.txt
The Institute for [Intelligent Systems](http://www.is.mpg.de/institute) has two campuses (Tuebingen and Stuttgart) with separate IT services, and thus separate e-mail domains.
> add domain os Intelligent Systems Stuttgart campus

- lib/domains/uk/co/cowbridgecomprehensiveschool.txt
- lib/domains/uk/co/cowbridgecs.txt
Add Cowbridge Comprehensive School Sixth Form
http://www.cowbridgecomprehensiveschool.co.uk/cms/_files/AS%20Options%20Booklet%20September%202017.pdf
Computer Science Page 19
Information and Communication
Technology (ICT) Page 43
Both of which are 2 Year A Level Courses
> Add Cowbridge Comprehensive School Sixth Form

- lib/domains/edu/matc.txt
"**matc.edu**" is the domain for faculty at _Milwaukee Area Technical College_.
Official website URL:
[http://www.matc.edu](http://www.matc.edu)
Specific course pages can't be linked to directly, but these pages list 1-year IT courses (e.g., Web Programming):
[IT Web & Software Developer](http://www.matc.edu/student/offerings/2015-2016/degrees/it-web-and-software-developer.cfm)
[IT Programmer Analyst](http://www.matc.edu/student/offerings/2012-2013/degrees/it_programmer_analyst.cfm)
This page lists subjects, from which you can access specific course pages:
[http://infonline.matc.edu/live-infonline/html/subject.html](http://infonline.matc.edu/live-infonline/html/subject.html)
Email address examples for faculty "@matc.edu":
[http://www.matc.edu/matc_news/ExpertList.cfm](http://www.matc.edu/m …
> Added matc.txt for matc.edu

- lib/domains/net/epita.txt
- lib/domains/org/ens2m.txt
- Add epita.net domain for "École pour l’informatique et les techniques avancées"
- Add ens2m.org domain for "École nationale supérieure de mécanique et des microtechniques"
> epita.net & ens2m.org 

- lib/domains/dk/ciid.txt
Please add the Copenhagen Institute of Interaction Design (CIID) to your list of education institutes http://ciid.dk/
> Add the Copenhagen Institute of Interaction Design (CIID)

- lib/domains/nl/kabk.txt
@GaborK moved this to kabk/student.txt in c4e724517932b7b1ee63fa865ab26800e14a6693
But teachers use the top-level `kabk.nl` domain.
Merci!
> Add top-level domain kabk.nl back in

- lib/domains/uk/ac/edgehill.txt
- lib/domains/uk/ac/edgehill/go.txt
edgehill.ac.uk and go.edgehill.ac.uk each host student email addresses of varying ages.
https://www.edgehill.ac.uk/courses/computer-science-bsc/
https://www.edgehill.ac.uk/itservices/microsoft-office/ references both domains as being email domains for our students.
> Add Edge Hill University

- lib/domains/org/ep-student.txt
- lib/domains/us/mn/k12/edenpr.txt
Added emails for student's and staff of Eden Prairie School District.
Student emails use the convention of __`studentID`__`@ep-student.org` and teacher emails use the convention of __`firstName`__`_`__`lastName`__`@edenpr.k12.mn.us` (spaces are caused accidentally by Markdown). Emails can only be created by District Administration.
Eden Prairie High School offers multiple AP Computer Science classes each taking up ~2 terms (1/2 of the year).
Website of the school district is `edenpr.org`, [here](https://www.edenpr.org/cms/lib/MN01909581/Centricity/Domain/269/2017-18%20Course%20Guide%20.pdf#7) is a link to the course offerings of next year (already at the section for Computer Science, if not it is at the top of page 7).
> Add Eden Prairie High School

- lib/domains/email/woodrushhigh.txt
Added Woodrush High School to the repository.
School website: woodrushhigh.worcs.sch.uk (however the student email pattern follows studentname@woodrushhigh.email)
Course list: http://woodrushhigh.worcs.sch.uk/index.phtml?d=554632 (here you can see the BTECT ICT course listed.
Thanks!
> Add Woodrush High School

- lib/domains/org/avcoe.txt
Amrutvahini College of Engineering, is a technical education institute in the taluka of Sangamner, Ahmednagar district, Maharashtra, India.
> Amrutvahini College of Engineering (avcoe.org)

- lib/domains/fr/centralelille/ig2i.txt
The IG2I is now officially part of Centrale Lille. The students are encouraged to use the new address @ig2i.centralelille.fr, even if the old @ig2i.fr address is still working for now.
fr/ig2i.txt is already registered, same for fr/ec-lille.txt (which is the main engineer school from Centrale Lille).
> Add ig2i.centralelille.fr

- lib/domains/in/ac/gcek.txt
Government College of Engineering, Kannur is one of the premier institutes among the 9 Government Engineering Colleges in Kerala and was established in 1986. The college is functioning in a sprawling 68-acre scenic campus, having sound and self-sufficient infrastructure, at Mangattuparamba, near the National Highway, 15 k.m from the headquarters of Kannur district.
The college is affiliated to Kerala Technological University. It offers 5 B.Tech Degree programs in Civil, Mechanical, Electrical and Electronics, Electronics and Communication and Computer Science and Engineering branches. The College also offers 4 M.Tech programs in Civil Engineering (Computer Aided Structural Engineering), Mechanical Engineering(Advanced Manufacturing and Mechanical Systems Design), Electrical and …
> added kannur engg collage,kerala

- lib/domains/ru/ostu.txt
Former name of current Orel State University.
Main site now -- [oreluniver.ru](http://oreluniver.ru)
> Added Orel State Technical University domain

- lib/domains/be/scheppers.txt
- lib/domains/be/scheppersinstituut.txt
Our school‘s website is found at http://www.scheppers.be/. Both scheppers.be and scheppersinstituut.be are used as email domains by the institution for students as well as teachers.
On the page: http://www.scheppers.be/studierichtingen.html#id-se-n-se you can find information about our post-secondary degree in Web development and Network Administration (Webontwikkeling en Netwerkbeheer). From next school year onwards I would like to use the Webstorm IDE with my students in our Web Development classes.
> Email domains for Scheppersinstituut Deurne & Antwerpen

- lib/domains/ru/icmm.txt
[Here](https://www.icmm.ru/images/files/education/postgraduate/pg_student/edu_process/01_02_05_class_schedule_2016-2017.pdf) is our schedule with courses, but it is only in .pdf file and in Russian.  The name of the IT course is "Параллельные вычислeния в механике сплошных сред" (Parallel computing in continuous media mechanics)
In fact, it is the only e-mail domain for all the Institute employees and PhD students. Anyway, I have attached an official document regarding e-mail accounts provisioning (but it is in Russian again).
[resource_access_provision.pdf](https://github.com/JetBrains/swot/files/1019154/resource_access_provision.pdf)
> Add icmm.txt for the ICMM UB RAS

- lib/domains/co/net/uco.txt
This file is the domain to university email (..@uco.net.co), and university domain (web page) is uco.edu.co that is already created in folder lib/domains/co/edu/uco.txt. The university has that 2 domains.
> Create Universidad Catolica de Oriente file

- lib/domains/org/mynbps.txt
- lib/domains/org/nbps.txt
Adds [nbps](https://nbps.org) to the list.
[Course Catalog](http://www.nordangliaeducation.com/our-schools/florida/north-broward-preparatory-school/academics/our-curriculum/high-school/course-descriptions) -> [Academic Technology Courses](https://www.thinglink.com/scene/902996363493507073)
[WHOIS showing domain ownership](https://whois.icann.org/en/lookup?name=mynbps.org)
> Add North Broward Prepatory School

- lib/domains/sg/edu/nyp.txt
Official university website
- [Nanyang Polytechnic official website](http://www.nyp.edu.sg)
3-year IT related program
- [Diploma in Information Technology](http://www.nyp.edu.sg/schools/sit/full-time-courses/information-technology.html)
Proof of use of domain name (@nyp.edu.sg)
- [Official email address listed on their contact page](http://www.nyp.edu.sg/be-part-of-nyp/contact-us.html)
- Official email address for general enquiries - askNYP@nyp.edu.sg
- [Student handbook (PDF)](http://www.nyp.edu.sg/content/dam/nyp/current-students/academic-matters/student-handbook/student-handbook.pdf)
> Submit school domain for Nanyang Polytechnic

- lib/domains/pt/novasbe.txt
NovaSBE is part of Universidade Nova de Lisboa
www.novasbe.unl.pt/
> Add Nova School of Business and Economics.

- lib/domains/uk/co/poolehigh.txt
- lib/domains/uk/sch/poole/poolehigh.txt
The current official website is: [https://poolehigh.co.uk](https://poolehigh.co.uk) ([poolehigh.poole.sch.uk](http://poolehigh.poole.sch.uk) redirects there)
The proof that IT related courses are offered:
[https://poolehigh.co.uk/sixth-form/courses/computer-science/](https://poolehigh.co.uk/sixth-form/courses/computer-science/) (A level Computer Science Course)
[http://poolehigh.co.uk/wp-content/uploads/2016/10/Sixth-Form-Prospectus.pdf](http://poolehigh.co.uk/wp-content/uploads/2016/10/Sixth-Form-Prospectus.pdf) Page 6 (Shows that this is a 2 Year Course)
The proof that students are given and use poolehigh.co.uk domain emails:
[https://poolehigh.co.uk/wp-content/uploads/2016/11/E-Learning-Summary-for-Year-11.pdf](https://poolehigh.co.uk/wp-content/uploads/2016/11/E-Learning-Summary-for-Ye …
> Added Poole High School's email Domains.

- lib/domains/ch/usb.txt
The University Hospital Basel works in association with the University of Basel (unibas.txt). The medical teaching and research is done at the University Hospital Basel. 
Main Website 
http://www.usb.ch (will be forwarded to http://www.unispital-basel.ch)
Teaching and Research
https://www.unispital-basel.ch/en/lehre-forschung/
Whois entry
https://www.nic.ch/whois/?domain=usb.ch&language=en&tld=ch
E-Mail Domain is: usb.ch
Thanks,
Joshy
> Please add University Hospital Basel

- lib/domains/ch/edulu.txt
Edulu stands for Education Lucerne and includes the "Berufsbildungszentrum Wirtschaft, Informatik und Technik" *.
All the "Berufsbildungszentrum" of the canton of Lucerne share the same domain (edulu.ch / beruf.lu.ch).
There are only @edulu.ch email addresses, there is no real website for that domain. The Website itself is:
https://beruf.lu.ch/berufsbildungszentren/bbzw
As you can see on the teachers contact page
https://beruf.lu.ch/berufsbildungszentren/bbzw/Kontakt/Kontakt_Sursee/Lehrpersonen_Sursee
All the teachers have an @edulu.ch email address.
\* In Switzerland we have the dual education system on which students attend lessons at "Berufsschulen"/"Berufsbildungszentren" such as the "Berufsbildungszentrum Wirtschaft, Informatik und Technik" …
> Education Lucerne

- lib/domains/de/bfw-oberhausen.txt
- lib/domains/de/bfwob.txt
Berufsförderungswerk Oberhausen. 
Apprenticeship for Software Developers, Sysadmins and Telecommunications-Electricians.
Primary domain for information and verification is http://www.bfw-oberhausen.de/
Provided Domain file is primarily used for student email addresses.
> Added Domain for Berufsförderungswerk Oberhausen

- lib/domains/in/csiriicb.txt
Institute Name: CSIR-Indian Institute of Chemical Biology
Institute Website: http://www.iicb.res.in/
Domain: csiriicb.in
> add csiriicb.txt

- lib/domains/de/wwschool/gnr.txt
The domain does not match the home page of the school as we are using a different system/domain for student email addresses. Please contact the administration "Frau Milsch" or "Frau Oesterschling" (see http://www.nepomucenum-rietberg.de/kontakt/) to verify the domain gnr.wwschool.de as student email domain. Thanks in advance.
> Add new school "Gymnasium Nepomucenum Rietberg"

- lib/domains/ie/mu.txt
Adding @mu.ie for [Maynooth University](http://maynoothuniversity.ie).
See [here for details](https://www.maynoothuniversity.ie/it-services/muie-email-change).
> Adding @mu.ie for Maynooth University.

- lib/domains/az/edu/qafqaz.txt
- lib/domains/az/edu/qu.txt
Qafqaz University has been closed in 2016. All the staff and students have been moved to newly established "Baku Engineering University". But "qu.edu.az" domain is still in use by BEU.
> Update and rename qafqaz.txt to qu.txt

- lib/domains/fr/imt-lille-douai.txt
Add École nationale supérieure Mines-Télécom Lille-Douai (imt-lille-douai.txt)
Website : http://imt-lille-douai.fr/
Informations about courses : http://en.calameo.com/read/005222720e147288eaa83
> Add IMT LILLE DOUAI to FR domains

- lib/domains/eu/sheffield/citycollege.txt
- lib/domains/gr/academic/city.txt
The University of Sheffield International Faculty, CITY College changed their Email.
Old Email: @city.academic.gr
New Email: @citycollege.sheffield.eu
Proof: [PDF](https://www.dropbox.com/s/6aaxbvbrfyrhlry/The%20University%20of%20Sheffield%2C%20International%20Faculty%20Mail%20-%20%5BComputer%20Support%5D_%20New%20CITY%20Email%20Addresses.pdf?dl=0)
> City College Email Change

- lib/domains/in/ac/mctrgit.txt
- lib/domains/in/ac/vjti.txt
Added Manjara Charitable Trust's Rajiv Gandhi Institute of Technology aka Rajiv Gandhi Institute of Technology aka RGIT and Veermata Jijabai Technological Institute which is a college in city of Mumbai in India.
> Added Manjara Charitable Trust's RGIT and VJTI

- lib/domains/net/grb-online.txt
The official homepage of the Gymnasium Riedberg is gymnasium-riedberg.com. The mailing domain used is `grb-online.net`. http://gymnasium-riedberg.de/de/service/downloads/send/3-/2-riedbergonline shows the relation between the two domains. This school also offers informatics as an advanced or basic lesson after the 10th Grade.
> Added grb-online.net

- lib/domains/org/rdale.txt
Adds a whole district which uses the same domain ([rdale.org](https://rdale.org)) for their elementary schools (uses scratch.mit.edu and code.org to teach basic programming concepts without a text editor), middle schools (expands on scratch.mit.edu and uses Python), **high schools (has full-fledged computer science classes).**
> Add Robbinsdale Area Schools (https://rdale.org)

- lib/domains/za/ac/unisa/mylife.txt
University of South Africa: Added student_num@mylife.unisa.ac.za
I noted the comment: **We intentionally exclude alumni domains (like john.smith@alumni.stanford.edu) as well.**
For UNISA, the **mylife** subdomain is important as we use a hosted Microsoft Office email plan.
> UNISA: Add "student_num@mylife.unisa.ac.za" mail

- lib/domains/ch/sluz.txt
The offical website is "https://beruf.lu.ch/berufsbildungszentren/bbzw" (it's in german).
> Added a domain for "Berufsbildungszentrum Wirtschaft, Informatik und Technik"

- lib/domains/dk/tradium/elev.txt
Added Tradium, a large school in Randers, Denmark
> Added Tradium

- lib/domains/org/gmsdk12.txt
- lib/domains/org/gmsdk12/students.txt
District Website: [gmsdk12.org](http://gmsdk12.org)
2017 - 2018 Houston High School Course Catalog: [HHS Course Catalog 2017-18.pdf](http://filecabinet5.eschoolview.com/F2ED651E-240C-4D18-AFC6-5F29034FE4C8/HHS%20Course%20Catalog%202017-18.pdf)
"AP Computer Science Principals", "AP Computer Science A", "Coding I", "Coding II Honors", "Programming & Software Development Dual Enrollment", and "Mobile App Development" are all on pages 11 and 12
I hope that this counts as official proof that students.gmsdk12.org is the students' email domain for GMSD: [Logging into Office365.pdf](http://www.gmsdk12.org/Downloads/Logging%20into%20Office365.pdf)
> Added Germantown Muncipal School District

- lib/domains/at/ac/fernfh.txt
URL for IT-related long-term courses (3 Years: Bachelor/2 Years: Master): http://fernfh.ac.at/studienrichtungen/wirtschaftsinformatik/
> Add FernFH

- lib/domains/net/promsocatc.txt
Official website:
http://www.promsocatc.com
Bachelor in IT program:
http://www.promsocatc.com/formation/bachelier-en-informatique-de-gestion/
The public website is in .com, but students/teachers mails are in .net
See http://www.promsocatc.com/plateforme/Plateforme_promsocatc.pdf p. 2
(point 1.3)
> Add promsocatc.net - Collège Technique "Aumôniers du Travail"

- lib/domains/uk/org/s6f.txt
- lib/domains/uk/org/s6f/student.txt
Add Scarborough Sixth Form College domain and student subdomain.
Official Domain : s6f.org.uk
Relevant Courses : Computer Science (https://s6f.org.uk/course/computing/) , Information Technology (https://s6f.org.uk/course/information-technology/)
NUS Page : https://www.nus.org.uk/en/students-unions/scarborough-vi-form-college-students-council/
> Add S6F teacher and student domains

- lib/domains/net/pdsb.txt
- lib/domains/org/pdsb.txt
Adding Peel District School Board E-Mail domains for students. One is through Office 365 (pdsb.org) and the other is through G Suite (pdsb.net).
Different teachers make use of one of the two based on preference. Provided below is a link to the info document on Office 365 and a screenshot of a students G Suite inbox.
[Office 365 Info Document](http://schools.peelschools.org/1506/Documents/Office%20365.pdf)
Additional Info on the Computer Science Courses can be found below. Common language taught are Python, Java, C, C++.
[Course Descriptions and Prerequisites (Page 27 for Computer Science)](http://www.peelschools.org/students/commoncoursecalendar/2017-18/Documents/Course%20Descriptions%20and%20Prerequisites.pdf)
> Peel District School Board (http://peelschools.org)

- lib/domains/ru/mcag.txt
Please add Moscow College of Architecture and Urban Planning
Official Website: http://mcag.mskobr.ru/
Mail Domain (mcag.ru) is provided via 3rd-party server.
State standard for specialty: Applied Informatics (qualification technician-programmer, duration of training 3 years 10 months)
http://mcag.mskobr.ru/files/230701_prikladnaya_informatika.pdf
> Add Moscow College of Architecture and Urban Planning

- lib/domains/de/gsz-bl.txt
- lib/domains/de/gsz-zak.txt
This PR adds the Philipp-Matthäus-Hahn-Schule – Gewerbliches Schulzentrum Balingen. It's a secondary school ("Gymnasium" in German) and a professional school ("Berufsschule" in German). Several subjects having something todo with information technology, electronics, crafting and personal hygiene are taught there.
There are two domains used for e-mailing: *@gsz-zak.de for students and *@gsz-bl.de for teachers. They're both redirecting to the homepage of the school, [gsz-zak.de](http://gsz-zak.de).
> Adding Philipp-Matthäus-Hahn-Schule

- lib/domains/ca/qc/cegepst.txt
Cégep de Sorel-Tracy
http://www.cegepst.qc.ca/
> Add cegepst.qc.ca domain

- lib/domains/cn/com/qypt.txt
add domain for Qingyuan Polytechnic in Guangdong Province, China.
> Add Qingyuan Polytechnic

- lib/domains/us/mi/k12/rochester.txt
- lib/domains/us/rcs-k12.txt
URL: http://www.rochester.k12.mi.us
`@rochester.k12.mi.us` is for teachers
`@rcs-k12.us` is for students and teachers (all teachers have a `@rochester.k12.mi.us` and `@rcs-k12.us` email)
Course descriptions for computer science class: http://www.rochester.k12.mi.us/pages/129583/computer-science
Proof that `@rcs-k12.us` is a valid email address for the district: http://www.rochester.k12.mi.us/rochester-high-school/announcements/45705/rcs-student-google-account
http://www.rochester.k12.mi.us/stoney-creek-high-school/pages/9786/mr-bliss
http://www.rochester.k12.mi.us/rochester-high-school/pages/133778/ms-smith
> Add rcs-k12.us, rochester.k12.mi.us

- lib/domains/dk/skolekom.txt
Skolekom is a shared domain for all Elementary Schools in Denmark, it doesn't have anything with coding to do, and in Denmark, it's not student discount oblige.
> Deleted Skolekom

- lib/domains/fr/ensta-paristech.txt
```
host ensta-paristech.fr
ensta-paristech.fr has address 147.250.10.70
ensta-paristech.fr mail is handled by 20 ns4.ensta.fr.
ensta-paristech.fr mail is handled by 20 ns3.ensta.fr.
```
> Adding ensta-paristech

- lib/domains/nl/leeuwenborgh.txt
- lib/domains/nl/rocleeuwenborgh.txt
They changed the name of the school from ROC Leeuwenborgh to Leeuwenborgh
> Update and rename rocleeuwenborgh.txt to leeuwenborgh.txt

- lib/domains/us/ga/k12/henry.txt
Both Office 365 and GSuite are enabled for students under the domain "@henry.k12.ga.us". Teachers also have email addresses under the domain. Student have unique numerical IDs (for instance, mine, when I attended, was "084182@henry.k12.ga.us"). Teachers have normal email addresses.
> Add Henry County School District

- lib/domains/de/hg-gf.txt
Gymnasium(Highschool) in Germany
Public domain: [Website](http://humboldtgymnasium.de) 
Information regarding CS courses: [link](http://www.humboldtgymnasium.de/CM/index.php?option=com_content&view=category&layout=blog&id=52&Itemid=77)
Its outdated for whatever reason but they still offer the courses.
Proof that the domain belongs to the school and offers student email: [link](http://www.humboldtgymnasium.de/CM/index.php?option=com_content&view=article&id=1459:anmeldung-an-der-weboberflaeche-iserv-der-schule&catid=140:elterninfo&Itemid=96)
> Add Domain of Humboldt-Gymnasium Gifhorn

- lib/domains/de/fh-flensburg.txt
This is the old domain of Fachhochschule Flensburg, renamed to Hochschule Flensburg.
The domain ist still in use for student email accounts.
Homepage: https://fh-flensburg.de redirected to https://hs-flensburg.de
Sample courses:
* https://hs-flensburg.de/studium/bachelor/mi
* https://hs-flensburg.de/studium/bachelor/ai
> Enable old domain for hs-flensburg.de

- lib/domains/uk/ac/cambria.txt
https://www.cambria.ac.uk/
Email Addresses of Students are in form of [ID Number]@cambria.ac.uk
This college offers Computing Science at BTEC, A-Level, and GCSE with School Links (School Links students are given a Cambria email address).
https://www.cambria.ac.uk/courses/course-detail/?subject=1&course_id=258
> Coleg Cambria

- lib/domains/nl/vova/leerling.txt
Added leerling.vova.nl the email domain for the students of VOvA. Voortgezet Onderwijs van Amsterdam http://vova.nl/ and http://hyperionlyceum.nl
> Added VOvA student domain

- lib/domains/jp/kosen-ac/toba.txt
I can prove my domain.
Our college is also called Toba Kosen.This collage is affiliated with the National Institude of Technology.
So, Whois Infomation is the same of Toba Collage.
Here is our collage's official web site.
http://www.toba-cmt.ac.jp/
And I’m sorry, I can’t show you any reference page saying we use the domain. There’s no page about that anywhere.
In addition, I show you WHOIS information about toba.kosen-ac.jp.(from http://whois.jp/) 
-------------------------------------------
Domain Information: [ドメイン情報]
[Domain Name]                   KOSEN-AC.JP
[登録者名]                      独立行政法人　国立高等専門学校機構
[Registrant]                    National Institute of Technology, Japan
[Name Server]                   ns1.dns.ne.jp
[Name Server]                   ns2.dns.ne.jp
[Signing Key] …
> add toba-kosen

- lib/domains/pl/torun/loiv.txt
a.k.a. General Tadeusz Kosciuszko High School #4 in Torun
https://pl.wikipedia.org/wiki/IV_Liceum_Og%C3%B3lnokszta%C5%82c%C4%85ce_im._Tadeusza_Ko%C5%9Bciuszki_w_Toruniu
A well recognized Polish high school with strong ties to the Nicolaus Copernicus University in Torun.
> Added IV Liceum Ogólnokształcące im. Tadeusza Kościuszki w Toruniu

- lib/domains/pl/waw/staszic.txt
Official school homepage: https://staszic.waw.pl/
Wikipedia page: https://pl.wikipedia.org/wiki/XIV_Liceum_Og%C3%B3lnokszta%C5%82c%C4%85ce_im._Stanis%C5%82awa_Staszica_w_Warszawie
Some pupils acquired student license by submitting their ID, but I think it would be easier for them, simply by providing official school email.
> Add XIV LO in Warsaw

- lib/domains/de/fh-nb.txt
- lib/domains/de/hs-nb.txt
The Fachhochschule Neubrandenburg renamed itself to Hochschule Neubrandenburg.
The domain also changed from fh-nb.de to hs-nb.de accordingly.
[Base URL](https://www.hs-nb.de/en/)
[Course Information Geoinformatics](https://www.hs-nb.de/en/courses-of-study/undergraduate-courses/geoinformatics-beng/) Bachelor of Engineering, seven semesters.
> Fachhochschule -> Hochschule Neubrandenburg

- lib/domains/si/sers.txt
Roughly translates to "High school for electrical engineering and computer science" (Maribor, Slovenia).
Website: http://www.sers.si
Only students and faculty have emails `@sers.si`.
> Added SERŠ Maribor

- lib/domains/br/fasp.txt
- lib/domains/br/faspmail.txt
Please merge to add the domain used by FASP (Faculdades Associadas De Sao Paulo) for the students email (@faspmail.br) and teachers and staff (@fasp.br). Thanks.
> Please add FASP University domains

- lib/domains/nl/os3.txt
Official URL: https://www.uva.nl/
Official URL about the course: http://gss.uva.nl/content/masters/security-and-network-engineering/security-and-network-engineering.html
On that page it also shows that os3 is its branding name. You can find more information on the https://www.os3.nl/ website.
> Add os3 as education

- lib/domains/se/gavle/edu.txt
This adds the three main "Gymnasium" (high school/secondary school) in Gävle.'
[This page has links to all three](http://www.gavle.se/Utbildning--barnomsorg/Gymnasieskola/Lista-over-gymnasieskolor-i-Gavle/)
Links directly to the schools:
[Borgarskolan](http://borgarskolan.gavle.se/)
[Polhemsskolan](http://polhem.gavle.se/)
[Vasaskolan](http://vasa.gavle.se/)
> Add schools in Gävle

- lib/domains/it/itispininfarina.txt
Added itispininfarina.it to domains
Official GOV Domain: itispininfarina.gov.it
Official IT Domain: www.itispininfarina.it
(www.itispininfarina.it redirects to www.itispininfarina.gov.it)
> Added ITIS PININFARINA

- lib/domains/uk/ac/bangor.txt
Bangor University left the University of Wales 10 years ago
> Update Bangor to modern name

- lib/domains/uk/ac/gllm.txt
The college has quite a few physical locations across North Wales
Link to a page on their website showing one of the degrees in computing that they offer - https://www.gllm.ac.uk/courses/bsc-(hons)-computing-(software-development)/
Link to a policy which states that all students are given an email address in the form of studentnumber@gllm.ac.uk. All staff are also given email addresses directly under this domain - https://www.gllm.ac.uk/policies/learner/4294967426.pdf
Hopefully that should be enough to get it included, but if it isn't let me know and I'll do what I can to help
> Add Grŵp Llandrillo Menai

- lib/domains/uk/org/nlcs.txt
North London Collegiate School is a prestigious girls' day school covering school and further education curriculum in London, UK. The website for the school is http://www.nlcs.org.uk . The email domain is the same.
> Adding North London Collegiate School

- lib/domains/cn/edu/ccu.txt
- lib/domains/cn/edu/ccu/mails.txt
Institution: Changchun University
Location: Changchun, Jilin, China
Official website: http://www.ccu.edu.cn/
Staff Mail Domain: ccu.edu.cn
Student Mail Domain: mails.ccu.edu.cn
Changchun University (Chinese: 长春大学) is a multi-disciplinary university in Changchun, Jilin. It includes three campuses all together covering 1,129,000 squaremeters. Established in 1946, Changchun University has trained more than 40,000 undergraduate students.
> Add Changchun University

- lib/domains/org/westportps.txt
- lib/domains/us/ct/k12/westport.txt
Westport, CT public schools - including Staples High School, has changed domains. Previously student emails were address to <student>@students.westport.k12.ct.us. This has been changed to <student>@students.westportps.org.  Staff will now use the @westportps.org domain as well.
Notice of this change can be found here: 
[Notice](http://support.westport.k12.ct.us/announcements/publicdomainnamechangefaq)
The Westport Public Schools website (with new domain) can be viewed [here](https://www.westportps.org/)
I am submitting this request as I have a child who attends Staples High School and he is a user of JetBrains student products.
Thank you!
> Westport, CT public schools domain change

- lib/domains/de/gd-serv.txt
School website: http://www.gymnasium-damme.net
IServ panel: https://gd-serv.de
Please notice that the Email system (IServ: https://gd-serv.de) is seperated from the main website (http://www.gymnasium-damme.net).
If you look at the right hand side of the main website, you will see "Häufig verwendet" (which means "Often used") and "IServ gd-serv.de" which redirects to our Email system.
> Add gd-serv

- lib/domains/kg/knu.txt
- lib/domains/kg/university.txt
1. Official university website: https://www.knu.kg/ru/
2. Bachelor and Master's programmes in IT:
https://www.fiit.knu.kg/index.php?option=com_content&view=category&id=46&Itemid=512&lang=ru
3. Proof that university.kg domain belongs to knu.kg:
https://www.knu.kg/ru/index.php?option=com_content&view=article&id=935&Itemid=577
> Kyrgyz National University named after Jusup Balasagyn

- lib/domains/nl/bsnstudent.txt
Add The British School in The Netherlands as a valid educational
institute since they have a computer science course.
Their website can be seen [here](https://britishschool.nl).
Their curriculum can be seen [here](https://issuu.com/bsnetherlands/docs/bsn_20sixth_20form_20curriculum_20s?e=26621386/55452267). (Note Computer Science)
To prove this is their email provider you can see it is used to connect with their AppleID [here](https://www.bsngateway.nl/sites/ext/Pages/HowdoIfindmyAppleID.aspx) (This is on their internal site). The page can be seen properly by removing a "margin-left", then you'll see [this](https://share.vedsted.me/chrome_2018-02-10_19-02-30.png). The important sentence is *"Usually students will (and should)​ have an Apple ID e-mail address ending in @bsnstudent.nl."*. …
> Add The British School in The Netherlands

- lib/domains/ca/herzing/mtl.txt
Herzing College Montreal
created mtl.txt to add mtl.herzing.ca college domain
Herzing College Montreal
Instiution/School Website:
https://www.herzing.ca/montreal/
Programming courses:
- Computing support (14 months)
https://www.herzing.ca/montreal/training/computing-support/
- Programmer Analyst (15 months)
https://www.herzing.ca/montreal/training/programmer-analyst/
- Graphic Design for the Web (12 months)
https://www.herzing.ca/montreal/training/graphic-design-web/
Domain proof:
this is found under https://www.herzing.ca/montreal/
but i cant find one with mtl.herzing.ca we only use it internally
Email Users:
- Academic/Teaching Staff
- Other/Support Staff
Education Levels:
- College (University) or Undergraduate School or equivalent
> created mtl.txt

- lib/domains/ch/bwz-rappi.txt
Please add the bwz-rappi (see https://www.bwz-rappi.ch/grundbildung) domain to the JetBrains students index so it will be possible to teach the students Java by using the latest JetBrains tools.
> Add BWZ-Rapperswil to JetBrains index.

- lib/domains/vn/edu/dhxd.txt
- lib/domains/vn/edu/nuce.txt
"dhxd" is the abbreviation of National University of Civil Engineering (NUCE) in Vietnamese. In fact, our university's domain name is nuce.edu.vn, not dhxd.edu.vn. The email domain of the student is also @nuce.edu.vn. And the official website where the IT-related long-term course provided by this university is http://fit.nuce.edu.vn/.
> Update and rename dhxd.txt to nuce.txt

- lib/domains/corsica/universita.txt
- lib/domains/fr/univ-corse.txt
This is currently used along with univ-corse.fr.
> New domain for Université de Corse Pascal Paoli

- lib/domains/net/gymbay.txt
Homepage: gymbay.de
Adress: Bayreuther Str. 35, 42115 Wuppertal Germany
E-Mail domain: gymbay.net
Reason for the difference: Our school uses the iserv.eu system on a different domain https://gymbay.net/iserv/ for the web-interface of iserv
> Gymnasium Bayreuther Straße

- lib/domains/com/springbranchisd.txt
- lib/domains/org/mysbisd.txt
These are top-level domains for the emails of students and staff in my school district respectively. There is no difference in the email domains for middle school and high school. I am not sure if this causes issues.
> Create org/mysbisd.txt and com/springbranchisd.txt

- lib/domains/br/com/sempreuninassau.txt
This is about [UniNassau](https://www.uninassau.edu.br/) university.
The mail domains is `.com.br` but web page is `.edu.br`, why ? i don't know.
The university is well-known on brazil, and recently (this year) launched email service.
> add brazilian university of UniNassau

- lib/domains/ch/gibz.txt
official site: http://www.gibz.ch
for example we provide the ability to study computer science: https://www.zg.ch/behoerden/volkswirtschaftsdirektion/gibz/grundbildung/02-technik-informatik/informatiker-in-efz
here you find the documentation about the course for 4 years: https://www.zg.ch/behoerden/volkswirtschaftsdirektion/gibz/grundbildung/02-technik-informatik/informatiker-in-efz/downloads/lektionentafel-infm-2008-2013-mh.pdf/download
here you find a list of the teachers: https://www.zg.ch/behoerden/volkswirtschaftsdirektion/gibz/personen/lehrpersonen/lehrpersonen-gibz/Lehrpersonen%20GIBZ%20ohne%20KursLP_2017-01-16.pdf/download
as you can see the most of them have the e-mail address @gibz.ch which is the official school address
> added "Gewerblich-industrielles Bildungszentrum Zug"

- lib/domains/mx/uaa/correo.txt
University official website URL: http://uaa.mx
URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: http://www.uaa.mx/direcciones/dgdp/catalogo/ciencias_basicas/ing_sist_computacionales.pdf
URL of a page showing that the university recognizes the domain submitted as an official email domain for the enrolled students: http://www.uaa.mx/centros/ccb/directorio.php
> Add UAA domain

- lib/domains/jp/kosen-ac/tsuyama.txt
Please add the domain of National Institute of Technology, Tsuyama College.
This collage is affiliated with the National Institude of Technology.
So, Whois Infomation is the same of Hachinohe Collage.
> Add NIT, Tsuyama College

- lib/domains/hu/uni-sopron.txt
University of West Hungary changed its name to University of Sopron
> University of West Hungary changed its name

- lib/domains/ca/uwaterloo/edu.txt
https://uwaterloo.ca/email
University of Waterloo changed the email system from `@uwaterloo.ca` to `@edu.uwaterloo.ca`, and redirects `@uwaterloo.ca` to `@edu.uwaterloo.ca`
> Add new University of Waterloo email

- lib/domains/rs/edu/ict.txt
School website: https://ict.edu.rs/
Name: Visoka ICT Škola (eng. ICT College of Vocational Studies)
Full name: Visoka škola strukovnih studija za informacione i komunikacione tehnologije
IT studies: https://ict.edu.rs/studijski-programi/osnovne-studije/internet-tehnologije/plan-studija-2017-0
Site containing all schools and universities in Serbia, link to this school: http://fakulteti.edukacija.rs/drzavne-visoke-skole/beograd/visoka-skola-strukovnih-studija-za-informacione-i-komunikacione-tehnologije/
There is also an English version of the website en.ict.edu.rs but it is not updated as frequently as local version.
> Added ICT College of Vocational Studies (ict.txt)

- lib/domains/fr/imt-atlantique.txt
IMT Atlantique results from the merge of Télécom Bretagne and École des Mines de Nantes. For more information see http://www.imt-atlantique.fr/en.
Note that at some point in the future, the old names should be removed (eu/telecom-bretagne.txt and fr/mines-nantes.txt).
Hope to help
Fabien
> Added IMT Atlantique

- lib/domains/cn/edu/stu.zucc.txt
- lib/domains/cn/edu/zucc.txt
- lib/domains/cn/edu/zucc/stu.txt
add Zhejiang University City College
Here are the requested links:
Official web page [浙江大学城市学院](http://www.zucc.edu.cn/)
Other proofs :
[Wiki about Zhejiang University City College（Chinese Simplified）](https://zh.wikipedia.org/wiki/%E6%B5%99%E6%B1%9F%E5%A4%A7%E5%AD%A6%E5%9F%8E%E5%B8%82%E5%AD%A6%E9%99%A2)
[The email web page of Zhejiang University City College](http://webmail.zucc.edu.cn/)
Thank you!
> Add Zhejiang University City College

- lib/domains/pl/edu/pg.txt
http://pg.gda.pl is redirecting to new domain https://pg.edu.pl
and here is an example page with the informations about Computer Science courses:
https://eti.pg.edu.pl/field-3
> Technical University of Gdansk has new domain: pg.edu.pl

- lib/domains/fr/ipag.txt
School home page (different TL domain than requested ) : https://www.ipag.edu
long-term (>1 year) IT related course is offered by the university : https://www.ipag.edu/etudiants/formation/master-2-marketing-digital-data
School page on the domain requested : https://ipagora.ipag.fr/ (domain used as an extranet for students and teachers)
> Added ipag.fr

- lib/domains/cn/edu/scuec.txt
The university official website URL : http://english.scuec.edu.cn
> Adding Domain for South-Central University for Nationalities

- lib/domains/cn/edu/shnu/smail.txt
Official Site(English) : http://english.shnu.edu.cn/     
URL to prove College and Courses related to IT ever exists(in Chinese) : http://xxjd.shnu.edu.cn/a4/d1/c14330a369873/page.htm    
URL to prove this domain is related to student affairs , originates from school IT Department , please check 三、学生电子邮件(in Chinese) : http://xxb.shnu.edu.cn/159/list.htm
> add Shanghai Normal University

- lib/domains/pl/edu/po/student.txt
[Official website (ENG version)](http://www.po.opole.pl/lang/en/)
[URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university (ENG version)](http://www.po.opole.pl/lang/en/index.php?mod=rekrutacja;kierunki_pl;weaii_informatyka)
[URL of a page showing that the university recognizes submitted domain as an official email domain for the enrolled students(POLISH version, sadly lack ENG version)](https://uoi.po.opole.pl/index.php/uslugi/poczta-elektroniczna)
Last link have proof at quote: 
> Każdy student Politechniki Opolskiej może posiadać konto pocztowe w domenie **@student.po.edu.pl**. Studenci konta pocztowe mogą założyć poprzez uczelniany portal eStudent funkcjonujący pod adresem: https://estudent.po.opole.pl.
> Added email domain for students of Opole University of Technology

- lib/domains/org/desmet.txt
- Official URL: https://www.desmet.org/
- Proof of long term (1+ year) IT Related course offered by the University: While there isn't a direct link on the site, a year long AP Introduction to Computer Science course can be found on page 30 of the [Curriculum Guide PDF here](https://www.desmet.org/academics-arts/academics/curriculum-guide)
- URL of a page (Or some other proof) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students: While I couldn't find a direct URL or any info on the website about student emails, I can attach screenshots of official school emails sent to this address (although for privacy reasons, I'd rather not attach them unless it is absolutely necessary, seeing as they might contain personal …
> Add De Smet Jesuit High School

- lib/domains/edu/udg.txt
Official website of university: www.udg.edu
If offers Bachelor's and Master's in Computer Science among others:
https://www.udg.edu/ca/study-at-the-udg
http://wenes.udg.edu/tabid/10104/Default.aspx?ID=3105G0710&language=en-us&IDE=847
> Added University of Girona domain (Spain)

- lib/domains/edu/uoc.txt
**Website:**
www.uoc.edu (catalan)
http://www.uoc.edu/portal/en/index.html (english)
**Courses, full list:**
http://studies.uoc.edu/en/all-courses
**Examples of 4-year IT courses (I'm sorry it's in spanish, they're not available in english)**
http://estudios.uoc.edu/es/grados/ingenieria-informatica/plan-estudios
http://estudios.uoc.edu/es/grados/multimedia/plan-estudios
http://estudios.uoc.edu/es/grados/tecnologias-telecomunicacion/plan-estudios
**Proof of students using the uoc.edu domain as an educational resource:**
http://www.uoc.edu/portal/en/_peu/avis_legal/index.html
It's a legal notice. In section 4, paragraph 3, it states:
The UOC provides all members of the Virtual Campus community with a free email account using the uoc.edu domain and provides the technological and hosting …
> Added domain for Universitat Oberta de Catalunya (uoc.edu)

- domains/cn/edu/nuit.txt
- lib/domains/cn/edu/nuit.txt
In pull request #4885, file was placed in `domains/cn/edu/nuit.txt`
but file should be in `lib/domains/cn/edu/nuit.txt`
missing `lib/`
> Fix error in pull request #4885

- lib/domains/nl/osgh.txt
"osgh.nl" is the domain for school-related Microsoft-accounts (e-mail included) assigned to pupils of Openbare Scholengemeenschap Hengelo. The normal site (which is also used for teacher e-mail accounts) is osghengelo.nl
> Added osgh.txt

- lib/domains/edu/hccfl/hawkmail.txt
Requesting to add Hillsborough Community College to the education discount. Per your request, please see proof below:
School URL: [hccfl.edu](url)
Proof of computer science related course:[https://www.hccfl.edu/media/3509913/2018-2019-catalog-6-14-18-accessible.pdf](url) Page 44 lists Computer Science (Engineering) as an Associates Degree (2 year college program).
Proof of use of email address: [https://www.hccfl.edu/hawknet.aspx](url) Please see HawkMail365 module. This leads to [http://outlook.com/hawkmail.hccfl.edu](url) which shows that students use hawkmail.hccfl.edu domains.
> Add Hillsborough Community College

- lib/domains/edu/olin.txt
Added the college Olin College of Engineering in Needham, MA, USA
Website [http://www.olin.edu/](http://www.olin.edu/)
Website Major Page [http://www.olin.edu/academics/programs-majors/](http://www.olin.edu/academics/programs-majors/)
> Add Olin.edu, Olin College of Engineering,

- lib/domains/de/lo-net2/by/gd.txt
Schmuttertal-Gymnasium Diedorf
https://schmuttertal-gymnasium.de
Emails run with lo-net2.de in the subdomain gd.by.lo-net2.de
> Add Schmuttertal-Gymnasium Diedorf

- lib/domains/us/andoverma/k12.txt
Andover Public Schools recognizes this domain here:
https://sites.google.com/k12.andoverma.us/apsdigitallearning/for-students?authuser=0
It is the technology department's page instructing students on how to login to their school emails.
The Andover Public Schools website:
http://www.aps1.net
Email domain to be added:
@k12.andoverma.us
> Add Andover Public Schools from Andover, MA to the database

- lib/domains/uk/org/bl6.txt
Website URL: http://bl6.org.uk/
Course URL: http://bl6.org.uk/course-directory/ (In the PDF document)
[Screenshot of usage](https://i.gyazo.com/21cf334a54fb6dbf23eaff4f1c8302cf.png) (email seen at top-right corner) - Note that the website shown in the screenshot (https://webmail.brineleas.co.uk) is the address used to login to email accounts, which is linked to on the homepage (http://bl6.org.uk/) in the navigation bar (EMAIL).
> Add Brine Leas Sixth Form (BL6)

- lib/domains/de/lernsax/gsg-loebau.txt
lernsax.de is a project by the German state Saxony that provides all sorts of IT solutions (including email accounts for students and teachers) for schools. The actual website of the Geschwister-Scholl-Gymnasium Löbau is http://gsg-loebau.de
> add Geschwister-Scholl-Gymnasium Löbau

- lib/domains/com/wbbroncos.txt
- lib/domains/us/oh/k12/wb.txt
As of August 2018, Western Brown updated their domain, they went from username@wb.k12.oh.us to username@wbbroncos.com, which messed with validation on Jetbrains registration.
> Update Western Brown

- lib/domains/org/sstx.txt
High school in Austin, Texas. Website sstx.org
> Add Saint Stephen's Episcopal School

- lib/domains/uk/ac/shrewsbury.txt
Interesting situation here, 2 colleges (Shrewsbury College and Shrewsbury Sixth Form College) merged - as far as I can tell, they used the infrastructure from Shrewsbury College. Up until recently both colleges retained their separate websites, though that is no longer the case and a single site is used for the group.
Currently emails are given out on the shrewsbury.ac.uk domain, though there may still be some students/staff on the ssfc.ac.uk domain. It may also be the case that they use scg.ac.uk in the future. Frankly, I don't know. Though I'd be willing to update the PR to include all 3, there's no rush on this - I'm just getting prepared for renewal in October :)
Group Site: https://www.scg.ac.uk/
Legacy SSFC Site: https://www.ssfc.ac.uk/ (redirects to the group site, not used for …
> Shrewsbury Colleges Group

- lib/domains/uk/ac/ssfc.txt
Follow up to #5233, it turns out that there are indeed students/staff
with emails using the legacy @ssfc.ac.uk domain.
> Update Shrewsbury Colleges Groups domains

- lib/domains/edu/maricopa.txt
**In reference to #4537, #2393 and #1673:**
**The instructions in the post referenced by #1673 are no longer valid and MCC has completely deprecated any functionality allowing non-students and non-faculty members from obtaining an email under maricopa.edu** - these changes were made years ago, and the instructions afforded in the post referenced by #1673 haven't been valid for nearly 5 years.
Maricopa Community Colleges encompasses 10 different schools in Maricopa County, Arizona, all of which are listed here: https://www.maricopa.edu/why-maricopa/colleges - all 10 of these schools utilize the maricopa.edu SLD for student email.
Each college has a course catalog available at their respective website, each school offers multi-semester and multi-year courses in CIS and CS. Rio Salado, for …
> Add maricopa.txt - obtaining non-student addresses through maricopa is no longer possible

- lib/domains/cat/fedac.txt
All FEDAC schools in Catalonia use the http://fedac.cat domain.
Some schools offer the scientific/technological baccalaureate. (For example: http://www.fedac.cat/horta.php)
Email adresses are of style studentname@fedac.cat or studentname@schoolname.fedac.cat
> Add FEDAC Schools

- lib/domains/in/ac/utu.txt
Added email domain for Uka Tarsadia University. More details about university can be found at http://utu.ac.in
> Adding domains for Uka Tarsadia University

- lib/domains/in/ac/charusat.txt
- lib/domains/in/edu/charusat.txt
Hi team, 
The above university has different domains for administrative purpose and student enrolment. 
- [https://charusat.ac.in](https://charusat.ac.in) is main domain which is used for administrative purpose and 
https://charusat.edu.in is used for students enrolment. 
- https://www.charusat.ac.in/all-courses/ug-programs/   
Link of all undergrad/postgrad/PhD programs.
- https://www.charusat.ac.in/CSPIT/about-us/    
Link of one of the institute (Engineering Institute) under the university.
- https://www.charusat.ac.in/CSPIT/computer-engineering/   
Link to Computer Engineering department details.
> Adding CHARUSAT domains.

- lib/domains/pl/edu/elodz/lo31.txt
aka Ludwik Zamenhof 31st High School in Lodz
More and more pupils received their licenses in other ways, such as ID submission. Official pupils' email can be much easier option for them.
Official website: http://lo31.pl/
Wiki, PL only: https://pl.wikipedia.org/wiki/XXXI_Liceum_Og%C3%B3lnokszta%C5%82c%C4%85ce_im._Ludwika_Zamenhofa_w_%C5%81odzi
> Added XXXI LO High School [Łódź, Poland]

- lib/domains/de/lgbk.txt
Name: Lessing Gymnasium | Berufskolleg
URL: http://lgbk.de
Schooltype: Highschool or equivalent
Email users: (students and) teachers
Proof of Email-adress usage by school: http://www.lgbk.de/das-lessing/das-kollegium/
> add german school Lessing

- lib/domains/nz/ac/aucklanduni.txt
Website: https://www.auckland.ac.nz/en.html
> Add another domain for University of Auckland

- lib/domains/nz/ac/aucklanduni.txt
Website: https://www.auckland.ac.nz/en.html
The student email domain is aucklanduni.ac.nz instead of auckland.ac.nz
Cheers
> Added University of Auckland student email

- lib/domains/eu/yschools.txt
- lib/domains/fr/yschools.txt
Groupe ESC Troyes changed name to Yschools (www.yschools.fr)
> www.yschools.fr

- lib/domains/fr/uphf.txt
Université Polytechnique des Hauts de France (**uphf**) is already registered but with **etu.uphf.fr** subdomain only (used for studiants). **uphf.fr** is for teachers.
> Université Polytechnique des Hauts de France

- lib/domains/de/wara.txt
Name: Walther-Rathenau Gewerbeschule
Website: http://www.wara.de/
Computer science course: http://www.wara.de/index.php/berufsschule/fachinformatikerin
Email proof: http://www.wara.de/index.php/impressum
> added Walther-Rathenau Gewerbeschule Freiburg

- lib/domains/de/mpg/mpia-hd.txt
Hello!
https://www.imprs-hd.mpg.de/
IMPRS-HD is an independent part of HGSFP 
http://www.fundamental-physics.uni-hd.de/
IMPRS-HD is uniting many institutes in Heidelberg, each one provides its own email. Max Planck Institute for Astronomy is the HQ and the biggest of them.
https://www.imprs-hd.mpg.de/3521/IMPRS-officials
Computing and programming, in general, is a vital part of astrophysics, and astronomers, especially students, spend a lot of time programming.
MPE, that plays the same role in Munich, is already in the repository.
> Add mpia-hd

- lib/domains/nl/ahk.txt
The domain: student.ahk.nl was already added to this repository a long time ago, but that leaves out teachers which have an ahk.nl email address.
Official website: https://www.ahk.nl/en/
Long term course: https://www.filmacademie.ahk.nl/en/study-programmes/visual-effects-immersive-media (interactive media uses Unity)
Not sure how to proof the domain other than that it's used for a general contact email address: https://www.filmacademie.ahk.nl/en/about-the-academy/contact/
> add ahk.nl domain

- lib/domains/com/twynhamschool.txt
Adding Twynham School, Secondary School/Sixth Form.
http://www.twynhamschool.com
http://www.twynhamschool.com/197/subjects/subject/14/computing
http://www.twynhamsixthform.com/
http://www.twynhamsixthform.com/388/subjects/subject/32/computer-science
Students have twynhamschool.com as their domain emails.
Thanks.
> Adding Twynham School

- lib/domains/nu/tibble.txt
- lib/domains/nu/tibble/edu.txt
tibble.nu for faculty and edu.tibble.nu for students.
> Added Tibble Gymnasium, a Swedish high school in Täby outside of Stocholm

- lib/domains/de/kreuzgymnasium/mail.txt
mail.kreuzgymnasium.de belongs to the "Evangelisches Kreuzgymnasium Dresden" in Dresden/Saxony/Germany
> Added domain mail.kreuzgymnasium.de

- lib/domains/net/radyr.txt
Added Radyr Comprehensive School, a comprehensive school and Sixth Form college in Cardiff, Wales. Computing is offered to GSCE students and Sixth Form students.
School website: [radyrcs.co.uk](http://radyrcs.co.uk)
Internal email domain (as found in website footer): [radyr.net](http://radyr.net)
Computing on the prospectus: [Sixth Form Computing Page](https://www.radyrsixthform.org/computing-and-ict) - [Sixth Form Computing Video](https://www.youtube.com/watch?v=Pkq0axxfZrw)
> Added Radyr Comprehensive School

- lib/domains/be/itlg/portail.txt
Adding ITLG domain for http://webitlg.portail.itlg.be/
The long-term IT related formation: http://webitlg.portail.itlg.be/nos-formations/bachelier-en-informatique-industrielle
> Add itlg.be

- lib/domains/pl/edu/umg.txt
- lib/domains/pl/gdynia/am.txt
Renaming domain for Gdynia Maritime University/Academy
was am.gdynia.pl
is umg.edu.pl
The university changed its name and domain.
A proper university which issues diplomas: http://umg.edu.pl/en/Studies
Has studies for Computer Science (Polish only): http://www.we.umg.edu.pl/specjalnosc/4238 and http://www.we.umg.edu.pl/specjalnosc/4237
Already in repo, just renaming domain.
> Renaming domain for Gdynia Maritime University/Academy

- lib/domains/com/mutacth.txt
University Name: Mahanakorn University of Technology
Main URL (different from e-mail domain): http://www.mut.ac.th/
IT related course URL: http://www.it.mut.ac.th/
> Adding Mahanakorn University of Technology

- lib/domains/be/vspw.txt
PCVO VSPW - PCVO Vormingsleergang voor Sociaal en Pedagogisch Werk Gent
Website: www.vspw.be
> Added PCVO Vormingsleergang voor Sociaal en Pedagogisch Werk Gent

- lib/domains/de/hhg-kl.txt
Heinrich-Heine-Gymnasium is a German Highschool located in Kaiserslautern. It offers computer sience classes for students in grades 7 to 13. The classes last one year (grades 7 to 10) or three years (grades 11 to 13).
The PDF https://hhg-kl.de/images/stories/pdf/faecherinformationen/Informatik.pdf contains information about the way computer sience is lectured at Heinrich-Heine-Gymnasium.
> Added Staatl. Heinrich-Heine-Gymnasium KL

- lib/domains/org/qes.txt
- lib/domains/org/uk/qes.txt
QES renamed their email from queenelizabeth.cumbria.sch.uk to qes.org.uk
> Queen Elizabeth School

- lib/domains/de/mpg/brain.txt
The Max Planck Institute for Brain Research is part of the
"International Max Planck Research Schools" (IMPRS) program.
Relevant links
* Homepage: https://brain.mpg.de
* Educational program: https://brain.mpg.de/graduate-studies/edu.html
> Add Max Planck Institute for Brain Research

- lib/domains/com/galvanize.txt
Reverts JetBrains/swot#3241, i.e. remove galvanize.com from the list.
Reason: Galvanize stop its MS Data Science Program.
Proof: https://www.quora.com/Why-did-Galvanize-stop-its-MS-Data-Science-Program-GalvanizeU
http://galvanizeu.newhaven.edu/
> Revert "Added Galvanize to education list"

- lib/domains/de/hhg-kl
Added hhg-kl.de (Heinrich-Heine-Gymnasium [Heinrich-Heine-Highschool] Kaiserslautern)
> Heinrich-Heine-Gymnasium Kaiserslautern

- lib/domains/tn/u-sousse/issatso.txt
This commit addes the Higher institute of applied science and technology of sousse students mail domain
- The university official website URL: http://www.issatso.rnu.tn
- URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: http://www.issatso.rnu.tn/fo/planetude/plan_etudes_2016-2017/PlanEtude-FING-16-17.pdf
- A proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students: emails using this domain are obtained through my365 which is a program created by the Tunisian Ministry of Higher Education that gives Tunisian students access to Microsoft office 365 accounts (please see the screenshot ) also you can check page 19 from this …
> Addes Issatso 

- lib/domains/hr/vub.txt
https://vub.hr
URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the university:
https://vub.hr/strucni-studij-racunarstvo/
> Added Veleučilište u Bjelovaru

- lib/domains/ca/qc/colval.txt
-official website URL: [https://www.colval.qc.ca/](https://www.colval.qc.ca/)
-URL of a page where a long-term IT related course is offered: [https://www.colval.qc.ca/index.php/programmes-etudes/du-cegep/informatique](https://www.colval.qc.ca/index.php/programmes-etudes/du-cegep/informatique)
> Added colval.qc.ca

- lib/domains/fr/ipgp.txt
The Institut de Physique du Globe de Paris (IPGP; French for "Paris Institute of Earth Physics") is a French governmental, non-profit research and **higher education establishment** located in Paris, dedicated to the study of earth and planetary sciences by combining observations, laboratory analysis and construction of conceptual analogical and numerical models.
Web page: www.ipgp.fr
[This page](http://www.ipgp.fr/fr/master/international-master-in-solid-earth-sciences) shows that several IT related classes are given at Master level, for instance:
-  Inverse Problems & Signal Processing
-  Scientific Computing for Geophysical Problems
-  Advanced Numerical Modelling
-  Geophysical Data Acquisition
The `@ipgp.fr` domain is used for master students emails. Attached is a screenshot from an …
> Please add ipgp.fr

- lib/domains/nl/stedelijkgymnijmegen.txt
Website: [https://stedelijkgymnijmegen.nl](https://stedelijkgymnijmegen.nl) (same domain)
Link to proof that course exists: [Page](https://www.scholenopdekaart.nl/Middelbare-scholen/2036/1087/Stedelijk-Gymnasium-Nijmegen/Examencijfers)
This pages lists the course 'Informatica' (translation: Informatics)
Acceptance of email domain: [Contact page of institute](https://www.stedelijkgymnijmegen.nl/contact): Shows the email domain used on their website
> Added Stedelijk Gymnasium Nijmegen

- lib/domains/tn/u-carthage/insat.txt
- the university official website URL: www.insat.rnu.tn
- a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: http://www.insat.rnu.tn/upload/1410510895.pdf
- proof showing that the university recognizes the domain:
> added insat.u-carthage.tn

- lib/domains/net/carlsbadusd.txt
URL to official website: https://www.carlsbadusd.k12.ca.us/
URL to IT courses offered (different because it is a district email). Additionally, you need to click on the 2020 academic plan and ctrl f "computer science" which will list the computer science classes offered.: https://carlsbadhs.schoolloop.com/pf4/cms2/view_page?d=x&group_id=1530973341864&vdid=i13c2b1w8thb2id
URL proving that the school recognizes this email. My high school has the same email for students and teachers, but only teacher names are allowed to be listed: https://carlsbadhs.schoolloop.com/pf4/cms2/view_page?d=x&group_id=1530973342012&vdid=i13b51wythb4c0
> Adding carlsbadusd.net

- lib/domains/za/co/stjohnscollege.txt
St John's College, South Africa offers IT as a subject and is physically located in Houghton, Johannesburg.
https://www.stjohnscollege.co.za/
> Added St John's College

- lib/domains/nz/ac/nmit/live.txt
A polytech in New Zealand, which offers several multi-year IT courses
> Add the Nelson Marlborough Institute of Technology

- lib/domains/br/senai/pe.txt
PE represents the Brazilian state of Pernambuco. We would like to add this domain so the teachers and students from Pernambuco could have access to the free license of JetBrains products.
> Add file for pe.senai.br

- lib/domains/hr/mef.txt
* Official url:
hr version: http://mef.unizg.hr/
en version: http://mef.unizg.hr/en/
* Classes that use programming:
http://mef.unizg.hr/en/studies/class?studij=Medicina&kol=5503&kolegij=Medicinska%20informatika&semestar=10&pid=440
http://mef.unizg.hr/en/studies/class?studij=Medicina&kol=3403&kolegij=Medicinska%20statistika&semestar=10&pid=440
(more information about the classes is available *only* in hr version of the page)
* Recognizing the `@mef.hr` domain:
http://mef.unizg.hr/o-nama/ustroj/strucne-sluzbe/odsjek-za-informaticku-djelatnost
On this url there are a number of official email addresses that use the `@mef.hr` domain.
> created hr/mef

- lib/domains/ua/edu/puet.txt
- lib/domains/ua/edu/pusku.txt
Name and domain of university was changed from "Poltava University of Consumer Cooperatives in Ukraine" to "Poltava University of Economics and Trade".  http://en.puet.edu.ua/
> Poltava University of Economics and Trade

- lib/domains/nl/sintlucas.txt
Added the domain for teachers of SintLucas. The students already had the domain sintlucasedu.nl added but teachers have emails that use the sintlucas.nl domain.
> Added the teachers email domain for SintLucas.

- lib/domains/by/bsut.txt
**Belarusian State University of Transport** is a non-profit public higher education institution located in Gomel (Republic of Belarus)
**Website:** [http://bsut.by](http://bsut.by)
> Belarusian State University of Transport added

- lib/domains/nz/ac/ara.txt
add Ara Institute of Canterbury
The domain of this Institute is www.ara.ac.nz, and its student mail account domain is arastudent.ac.nz, and its teacher mail domain is ara.ac.nz
> add ara.txt

- lib/domains/ch/unidistance/etu.txt
Adding the swiss university Unidistance (also named FernUni)
https://unidistance.ch/
> Adding etu.Unidistance.ch

- lib/domains/pl/edu/m.txt
- lib/domains/pl/edu/pwsz/student/m.txt
Jan Amos Komeński State School of Higher Vocational Education in Leszno, Poland
https://pwsz.edu.pl/index.php/en/
@m.student.pwsz.edu.pl
> Adding PWSZ Leszno

- lib/domains/se/harryda.txt
Both students and teachers have their email adresses at this domain.
The home page for the school is at http://hule.harryda.se/
> Added Hulebäcksgymnasiet

- lib/domains/au/com/cqumail.txt
- Link to University [https://www.cqu.edu.au/](url)
- Email Domain cqumail.com or cqumail.com.au
> Added CQUniversity to domain list.

- lib/domains/hk/edu/hsu.txt
[The Hang Seng University of Hong Kong](https://www.hsu.edu.hk/en/) is the second private university in Hong Kong and also have offer 4-year degree programmes regarding to IT. See [here](https://www.hsu.edu.hk/en/academics/).
Their email address domain is hsu.edu.hk (Note they used hsmc.edu.hk before but since the have status upgraded to university, it became hsu.edu.hk instead)
See [https://itsc.hsu.edu.hk/user-services/account-service/](https://itsc.hsu.edu.hk/user-services/account-service/)
> Adding The Hang Seng University of Hong Kong

- lib/domains/im/sch/online.txt
Ballakermeen High School is a Secondary School located on the Isle of Man.
All manx schools use "@online.sch.im" emails for their school accounts.
> Added Ballakermeen High School

- lib/domains/ca/cegepgim.txt
Adding Cégep de la Gaspésie et des Îles to allowed domains.
Official website (Montreal Campus website): http://www.cegepgim.ca/montreal/
IT programs: http://www.cegepgim.ca/montreal/certifications/technology
Contact info as proof of email domain: http://www.cegepgim.ca/montreal/contact.php 
Cheers and thanks to the whole team!
> Add Cegep de la Gaspesie et des Iles

- lib/domains/net/ppsstudents.txt
Adding the student email addresses used by all students of schools that fall under PPS Schools.
Official Website: https://www.pghschools.org/
Further Detail: "The Pittsburgh Public School District is the largest of 43 school districts in Allegheny County and second largest in Pennsylvania. The District provides students, in PreK through Grade 12"
There is a variety of schools that provide a variety of courses using this email for students.
> Pittsburgh Public Schools

- lib/domains/de/ibs-ol.txt
Added the domain "ibs-ol.de" for the IBS IT & Business School Oldenburg e. V. ([Website](https://ibs-ol.de/)). IBS offers long-term (3.5 years) economic computer science courses (see [https://www.ibs-ol.de/studium/duales-studium-wirtschaftsinformatik/](https://www.ibs-ol.de/studium/duales-studium-wirtschaftsinformatik/)).
This domain is used for email addresses of professors. Students use the subdomain "student.ibs-ol.de", so they are included.
Please let me know if you need anything else. Thank you!
> Adding "ibs-ol.de" IBS IT & Business School Oldenburg

- lib/domains/uk/co/utcw.txt
School Name: UTC Warrington
Website: https://utcw.co.uk/
IT Related Course: https://utcw.co.uk/sixth-form-curriculum/ [SEE Cyber Pathway]
Evidence:
> Added utcw.co.uk

- lib/domains/de/bbw-rki-berlin.txt
official website: https://www.rkibbw.de/
URL of a page where a long-term (>1 year) IT related course is offered: https://www.rkibbw.de/angebote/berufsausbildung/fachinformatiker-anwendungsentwicklung.html
URL of a page showing that the community college recognizes the domain as an official email domain for the enrolled students and staff: https://www.rkibbw.de/angebote/berufsschule.html. The email addresses is shown on the right side under "Kontakt".
Thanks in advance.
> Added Rotkreuz-Institut Berufsbildungswerk

- lib/domains/fr/lbsi14.txt
Please add my school, the school website is https://labruyeresainteisabelle.fr/ and our mails use the lbsi14.fr domain.
> + school La Bruyère Sainte Isabell, Paris, France

- lib/domains/de/berufskolleg.txt
- lib/domains/de/berufskolleg/schueler.txt
Name of the University:
Berufskolleg Hilden des Kreises Mettmann
(Berufskolleg Hilden) 
Official Link:
https://www.berufskolleg.de/
Links with IT related course:
https://www.berufskolleg.de/it/start
https://www.berufskolleg.de/ita/start
https://www.berufskolleg.de/itb/start
https://www.berufskolleg.de/it/fachinformatiker/fiae
> Berufskolleg Hilden des Kreises Mettmann

- lib/domains/ch/ksbg.txt
Name: Kantonsschule am Burggraben St. Gallen
Website: https://www.ksbg.ch
English landing page: https://www.ksbg.ch/sprachen/en/ (no other pages translated)
Course: https://www.ksbg.ch/portraet/faecher/fachgruppen/informatik/fg-informatik/
Education level: High school or equivalent
Email format: firstname.lastname@ksbg.ch
> Added ksbg.ch

- lib/domains/uk/co/iubs.txt
This fraudulent "university" is a scam targeting foreign students and should be removed from the list:
- https://news.bbc.co.uk/1/hi/england/london/8308685.stm
- https://www.independent.ie/life/family/learning/exposed-scandal-of-the-bogus-degrees-25956498.html
- https://hedd.ac.uk/viewInstitution?id=757
- https://theconnection.ece.org/NewsItem/574
> Delete iubs.txt (fake)

- lib/domains/de/th-owl.txt
It is the new name of the former Hochschule Ostwestfalen-Lippe (HS OWL), which already is part of this repo.
> Added TH OWL

- lib/domains/ch/ibw-schule.txt
ibW Hohere Fachschule Sudostschweiz
[https://ibw.ch](https://ibw.ch)
**Example course**
[https://www.ibw.ch/angebote/technik-informatik/informatik/dipl-techniker-in-hf-informatik/](https://www.ibw.ch/angebote/technik-informatik/informatik/dipl-techniker-in-hf-informatik/)
\> [Flyer](https://www.ibw.ch/fileadmin/user_upload/customers/ibw/Dokumente/Broschueren/Technik_Informatik/ibW_Flyer_HF-Informatik.pdf)
**Additional info**
The official website is [ibw.ch](https://ibw.ch). For the domain ibw-schule.ch there isn't much public information available (most of it is kept on an intranet), …
> Add definition for ibw-schule.ch

- lib/domains/es/evg/correo.txt
Add Escuela Virgen de Guadalupe, Badajoz (Spain).
School link: www.evg.es
> Add Escuela Virgen de Guadalupe

- lib/domains/se/kth.txt
The Royal Institute is currently referred to as a "lnstitute", this just fixes the misspelling
> Fix misspelling in kth.se

- lib/domains/uk/org/kegs.txt
this is a secondary school in the UK that reaches sixth form. It is located in Chelmsford.
> Please Add King Edward VI Grammar School (KEGS)

- lib/domains/org/seq.txt
- seq.txt
seq.org
San Francisco bay area schools in Menlo Park, Redwood City, and Woodside.
> Add the SUHS District

- lib/domains/in/ac/nitrkl.txt
Add National Institute of Technology Rourkela (nitrkl.ac.in) domain.
> Add NIT Rourkela

- lib/domains/jp/ac/tsukuba.txt
This PR adds "University of Tsukuba" in Japan.
Here is the official website of the university: <http://www.tsukuba.ac.jp/en/>
Thank you.
> Add University of Tsukuba, Japan (tsukuba.ac.jp)

- lib/domains/co/edu/upc.txt
School Name: Universidad Piloto de Colombia
Website: https://www.unipiloto.edu.co
The domain is: @unipiloto.edu.co 
Also there is an extra domain for students: @upc.edu.co
> Extra domain for existing university

- lib/domains/cat/iespaucasesnoves.txt
- lib/domains/cat/paucasesnovescifp.txt
The name of the school has changed and now is CIFP Pau Casesnoves and its new domain is paucasesnovescifp.cat
Website: http://paucasesnovescifp.cat (the old website http://iespaucasesnoves.cat has a link pointing here)
Courses urls: 
- https://paucasesnovescifp.cat/?page_id=1249
- https://paucasesnovescifp.cat/?page_id=1402
Thank you!
> Update and rename iespaucasesnoves.txt to paucasesnovescifp.txt

- lib/domains/uk/org/kcs.txt
KCSW is a private school in South London, and it does go through Sixth Form (ages 16-18).
School website: https://www.kcs.org.uk/
Email domain usage: https://www.kcs.org.uk/useful-information/contact
> Add King's College School Wimbledon

- lib/domains/org/olatheschools.txt
An entry already exists for Olathe Public Schools at "/lib/domains/com/olatheschools/students.txt" however, that is the domain used for students. This is the domain used by educators.
> Olathe Public Schools USD 233

- lib/domains/org/techvalleyhigh.txt
This is the domain for Tech Valley High School, in Albany NY.
Additional info requested:
1. Official URL (Same as PR): https://www.techvalleyhigh.org
2. Link to Courses Offered https://www.techvalleyhigh.org/course-catalog/ -- As this is a HS Computer Science (now in both Python for 11th grade, and Java for 12th grade) is offered, but listed together as "Computer Science". (Page pending updates for this fall's courses.)
3. Unfortunately we don't have a page that lists that students will get email addresses on this domain (tho they do). As they are minors and HS students it's not something the school advertises. If needed I can get a letter on school letterhead to that effect.
> Tech Valley High School, Albany NY USA

- lib/domains/us/apsva.txt
This changes the name of Washington-Lee to Washington-Liberty as seen here:[https://www.apsva.us/post/new-school-names-and-buildings-for-the-2019-20-school-year/](url)
This also adds the Arlington Career Center to the list.
> Additions and Changes - APSVA

- lib/domains/nz/school/selwyn.txt
Description of our digital technologies course:
http://www.selwyn.school.nz/Web/5217/
http://www.selwyn.school.nz/DataStore/Pages/PAGE_191/Docs/Documents/def661fb-8d61-4303-8057-0f84a7d5a0cb-Senior%20Course%20Descriptions%202020.pdf
Page: 15
The description on the website is extremely out of date and we have since moved on to using laguages like basic, C# and Python with tools like picaxes, unity and raspberry pi.
This is the closest I could find to the school claiming that this is the official email domain for students.
http://www.selwyn.school.nz/Web/5834/
> Add selwyn college

- lib/domains/de/bcw-gruppe-net.txt
Adding the domain bcw-gruppe-net.de (Domain from FOM Hochschule für Oekonomie und Management)
> Adding bcw-gruppe-net

- lib/domains/uk/org/tgacademy/solihull.txt
Main website: https://solihull.tgacademy.org.uk
It is both a secondary school and a sixth form (11-16, 16-18) and offer Computer Science for both
> Added Tudor Grange Academy Solihull

- lib/domains/no/t-fk.txt
- lib/domains/no/vfk.txt
- lib/domains/no/vtfk.txt
While Telemark and Vestfold County is not offically merging until the first of January all accounts were moved into a dedicated domain this summer, so both t-fk.no and vfk.no are now defunct. 
All students and teachers in both counties have been moved onto the new domain: `vtfk.no`.
The teaches have their mails on `*@vtfk.no` and students on `*@skole.vtfk.no`
> merge Telemark and Vestfold County into "Vestfold and Telemark County"

- lib/domains/ch/ksb-sg.txt
Kantonsschule am Brühl offers a 4 year CS course called IMS (Informatikmittelschule) which roughly translates to "Computer Science Highschool". 
Link to the School: https://ksb-sg.ch/
Link to the CS course in particular: https://ksb-sg.ch/ims/allgemein/
List of staff with Email adresses for proof that the domain belongs to the School: 
https://ksb-sg.ch/portrait/lehrerschaft/
> add Kantonsschule am Brühl

- lib/domains/ua/edu/zieit.txt
- lib/domains/ua/zp/econom.txt
The institute official website URLs:
Old commercial domain: http://econom.zp.ua/
New government domain: https://zieit.edu.ua/
A URL of a page on the official website where a long-term (>1 year) IT related course is offered by the institute:
https://zieit.edu.ua/?page_id=213
A URL of a page showing that the institute recognizes the domain which you are submitting as an official email domain:
https://www.zieit.edu.ua/?page_id=283
You can choose English in the footer of the websites. Just look for "Мова" there and choose an option "англійська".
> Adding Zaporizhzhya Institute of Economics and Information Technology

- lib/domains/cz/mendelu.txt
The correct name of the University is "Mendel University in Brno". The "Mendel University of Agriculture and Forestry" is old naming.
> updated name

- lib/domains/cn/jx/jxvc.txt
add Jiangxi Vocational College of Finance and Economis
School website：[www.jxvc.cn](http://www.jxvc.jx.cn/)
School courses lists: [http://www.jxvc.jx.cn/zsjy/zszy.htm](http://www.jxvc.jx.cn/zsjy/zszy.htm)
Official email domain for the enrolled students `318255030110@st.jxvc.jx.cn` :
> add Jiangxi Vocational College of Finance and Economis

- lib/domains/net/pps/student.txt
This is for a student account at Metropolitan Learning Center in Portland OR. 
https://www.pps.net/Domain/142
The school uses @pps.net accounts for staff. and the sub domain of @student.pps.net for 9x12 Students. 
Thanks for your help! We have a young future devloper waiting to use the awesome software!!!
> adding pps.net domain

- lib/domains/nl/ooz.txt
This is a request in addition to the existing record: capellen.txt
The ooz.nl domain is used by us, new teachers.
See also https://ooz.nl/onze-scholen/van-der-capellen/
> Added Openbaar Onderwijs Zwolle

- lib/domains/in/res/hri.txt
* lib/domains/in/res/hri.txt: New file.  Adds the domain of
Harish-Chandra Research Institute (HRI), Allahabad, India.
Information that may be relevant:
- The [official Web site](http://www.hri.res.in/) of HRI.
- HRI runs a  [doctoral program in mathematics (five years or longer)](http://www.hri.res.in/~math/mathgradp/), and [masters (two years) and doctoral programs (five years or longer) in theoretical physics](http://www.hri.res.in/~physgradp/).
- The graduate study and  research areas at HRI include cryptography, and [quantum information and computing ](http://www.hri.res.in/~qic/).
> Add hri.res.in

- lib/domains/cn/ac/iphy.txt
Add a file about IOP, Institute of Physics, Chinese Academy of Sciences.
offical website (in Chinese):
http://www.iop.cas.cn/
Offical Graduate education website (in Chinese):
http://edu.iphy.ac.cn/
> Add a file about IOP, Institute of Physics

- lib/domains/il/ac/mta.txt
- The [School of Computer Science](https://www.int.mta.ac.il/school-of-computer-science) offers B.Sc in Computer Science (>= 3 years)
and the [School of Economics and Management](https://www.int.mta.ac.il/school-of-economics-and-management) offers B.Sc in Information
Systems (>= 3 years).
- All [academic staff](https://www.mta.ac.il/he-il/about_us/staff) and students emails are using @mta.ac.il domain.
> Add domain of The Academic College of Tel Aviv-Yaffo

- lib/domains/koeln/schule.txt
Added the Georg-Simon-Ohm Berufskolleg in Cologne.
> GSO-BK-Cologne

- lib/domains/net/kes.txt
Domain:
...@kes.net
[Institution Website](http://kes.net)
As a sixth form and secondary school based in Stratford, UK, the school offers both GCSE and A-Level computing courses, which are each over 1 year in study duration. The institution is a physical entity with student attendance and is recognized as providing a learning curriculum for the UK educational system.
> Add King Edwards VI School, Stratford

- lib/domains/de/kisd.txt
Text file for Köln International School of Design (as a part of the TH-Köln, while KISD-Students don't have th-koeln mail adresses)
> Added kisd.txt

- lib/domains/ch/bict.txt
Dear Master
the BiCT is an educational institute in the field of computer science and multimedia education. More than 200 apprentices in these area are between 1 and 4 years in study and learn the ict handcraft. I was in contact with Natalia Kuznetsova (Sales) and she gives me a teachers (e*****.b****@bict.ch) license. But we need the students licenses for all of our developer students. 
Thanks a lot for your acceptance.
Kind regards
Enrico
> new domain for bict

- lib/domains/org/fcs.txt
- lib/domains/org/fcstu.txt
Fulton County Schools (Already approved under fultonschools.txt) has an additional domain (fcstu.org for students)
> Add Additional Fulton Country Schools (FCS) Domain

- lib/domains/de/th-ab.txt
for the university of applied sciences Aschaffenburg/ Technische Hochschule Aschaffenburg
the Faculty that is having mandatory computer science modules is the engineering one(IW Fakultät). You can visit the offical website under www.th-ab.de. The engineering courses available can be seen under https://www.th-ab.de/ueber-uns/organisation/fakultaeten/ingenieurwissenschaften/. The fact that @th-ab.de is the domain for this institution can be seen under https://helpdesk.th-ab.de/otrs/customer.pl?Action=CustomerFAQZoom;ItemID=331.
> integration of th-ab.de

- lib/domains/fr/lyceepergaud
- lib/domains/fr/lyceepergaud.txt
Lycée Louis Pergaud 
91-93 boulevard Léon BLum
25000 Besançon
France
www.lyceepergaud.fr
https://www.lyceepergaud.fr/wp-content/uploads/2011/11/Plaq-INFORM.pdf
> Lycée Louis Pergaud - Besançon

- lib/domains/de/egb-koeln.txt
Long term IT course on official website: 
https://www.egb-koeln.de/index.php/bildungsgaenge/it-systemkaufleute-informatikkaufleute
Proof school recognizes domain: 
https://www.egb-koeln.de/index.php/adressen-ansprechpartner
Thank you!
> Add domain egb-koeln.de

- lib/domains/ar/edu/ispi4038.txt
Hi guys, we have recently acquired the .edu.ar domain for our institute and we'll start deploying email addresses under it soon.
We already have a JetBrains verified domain here -> https://github.com/JetBrains/swot/blob/master/lib/domains/ar/com/ispi4038.txt
You can check both domains are pointing to the same server.
Do you need something else?
Could we keep both at least temporary? Or you need me to remove the .com.ar?. In that case, what happen with those students (if any) who already have created a JetBrains account using the .com.ar domain.
Cheers!
Edit: 
ispi4038.com.ar PR -> https://github.com/JetBrains/swot/pull/4596
> Add ispi4038.edu.ar

- lib/domains/org/ccsdut.txt
- lib/domains/org/ccsdut/stu.txt
- lib/domains/org/loganschools.txt
Please add loganschools.org domain for Logan High School located in Logan, UT, USA.
> Add domains for schools located in and near Logan, UT, USA

- lib/domains/nl/pantarijn/live.txt
High school RSG Pantarijn has the option to follow computer science classes from year four till six.
Website of the school: https://www.pantarijn.nl/
Special website where the students follow their computer science lessons: https://codepanta.nl/
> Request to add RSG Pantarijn

- lib/domains/cn/harrowbeijing.txt
北京哈罗国际学校
Harrow International School Beijing
www.harrowbeijing.cn
> Adds Harrow International School Beijing

- lib/domains/de/gymhum.txt
Official web site:
https://www.gymnasium-hummelsbuettel.de
IT course:
See the following URL. Scroll down to "Informatik: Programmieren kann jeder" and also note the PDF "Fachcurriculum Informatik" that describes the course in the final two years of education (there are also computer science courses in earlier years).
https://www.gymnasium-hummelsbuettel.de/unterricht/unterrichtsf%C3%A4cher/naturwissenschaften/
Proof for mail domain:
That's a bit tough because the e-mail domain "gymhum.de" is different from the web site domain "gymnasium-hummelsbuettel.de" (a short form of it, obviously).
Also, the e-mail system's web ui is only visible for logged-in users. However, see for example  the web page at the following URL and notice the e-mails links: …
> Added Gymnasium Hummelsbuettel, Hamburg, Germany

- lib/domains/org/dasd/student.txt
- Official website URL: https://www.dasd.org/STEM
- IT related course: https://www.dasd.org/Page/2328
- URL to proof the dasd.org domain name: https://www.dasd.org/domain/1623
> Added Downingtown S.T.E.M. Academy.

- lib/domains/org/cornwallhill.txt
https://www.cornwall.co.za/ is the official website for Cornwall Hill College.
https://www.cornwall.co.za/index.php/contact/contact-form shows that @cornwallhill.org is used for official emails
@cornwallhill.org is hosted on Gmail.  There is an option to "Create Account" on http://www.cornwallhill.org/, but it allows the public to create @gmail.com accounts, not @cornwallhill.org addresses.
> Add Cornwall Hill College

- lib/domains/dk/euclive.txt
I added the domain of EUC North high school. The primary use of the subscription is to be used in our programming and information technology classes. We primary work in PHP, Ruby and upcoming database work
> Added EUC North school to the list of highschools to access jetbrains student subscriptions

- lib/domains/org/cusd200.txt
The district's main website is https://www.cusd200.org
Both of the high schools have business and programming classes as listed under the _Career and Technical Education Program_ part of the [course catalog](https://www.cusd200.org/site/Default.aspx?PageID=364).
I do not have documentation supporting it but all staff and students share the same domain name (cusd200.org) for their email accounts.
> Add CUSD 200 in Wheaton, IL

- lib/domains/ie/stlouishighschool.txt
@philipto The high school URL is [St Louis High School](https://stlouishighschool.ie). It runs a Computer Club (information available under [Extra Curricular Activities](https://www.stlouishighschool.ie/list/extra-curricular/Extra-Curricular-Activities)).
> Add St Louis High School to IE domain

- lib/domains/ie/terenurecollege.txt
@philipto 
Adding Terenure College to the ie domain. Terenure College is one of the pilot schools for a two-year Computer Science course at Leaving Certificate level.
[State Exam Commission Doc showing pilot schools](https://www.examinations.ie/misc-doc/BI-EX-69048771.pdf)
[Terenure College website showing Computer Studies](http://www.terenurecollege.ie/index.php/school-information/academic/leaving-cert-curriculum)
> added Terenure College to ie domain

- lib/domains/br/edu/unipinterativa.txt
Alternative domain for Universidade Paulista e-learning mailbox.
> Add Universidade Paulista, Brazil

- lib/domains/vn/edu/tlu.txt
Hanoi water resources domain changed from wru.edu.vn to tlu.edu.vn
> Hanoi water resources domain changed

- lib/domains/org/eduil/raanana.txt
Ostrovsky High School
Website: http://ostrov.schooly.co.il
The school offers a [3-year CS program](http://ostrov.schooly.co.il/2016/01/12/תחרות-מחשבים-וסייבר-אפריל2015/).
All students use an email with a `@raanana.eduil.org` domain which belongs to the municipality's online education program.
> Add Ostrovsky High School

- lib/domains/br/simonsen.txt
Adding [Simonsen.txt](http://www.simonsen.br) as an instituition
You can find some information about the institution on [Wikipedia](http://pt.wikipedia.org/wiki/Faculdades_Integradas_Simonsen)
Here is its specific course page: http://www.simonsen.br/2.0/TADS
P.S.: Links in pt_br
> Adding simonsen.txt

- lib/domains/nl/novi-education.txt
NOVI University is rebranding to NOVI Education for its students. The coming months the novi-education.nl domain will start replacing noviuniversity.com.
> Added novi-education.nl

- lib/domains/uk/org/valeacademy.txt
Proof of email: http://mail.valeacademy.org.uk/
This school provides Secondary education to GCSE's but also up to A levels as a part of Brigg Sixth Form. The Computer Science classes (Both at GCSE and A level) are held at The Vale Academy.
http://www.briggsixthform.co.uk/
> Add The Vale Academy

- lib/domains/tw/edu/nkust.txt
- National Kaohsiung First University of Science and Technology
- National Kaohsiung Marine University
- National Kaohsiung University of Applied Sciences
The three old schools have been combined together, 
new name is National Kaohsiung University of Science and Technology. (NKUST)
> Add NKUST to tw

- lib/domains/bg/mon/edu.txt
This is a bit of a weird one - almost every student in Bulgaria is going to recieve an Office 365 account, which includes an email address ending in `@edu.mon.bg`. The addresses are owned by the Ministry of Education and Science, which controls all the educational institutions here.
> Add Ministry of Education and Science student domain

- lib/domains/pl/edu/pspo.txt
A domain for high school Liceum Ogólnokształcące Niepubliczne nr 43 z Oddziałami Dwujęzycznymi
http://pspo.edu.pl/o-nas/nauczyciele/
> Add pspo.edu.pl domain

- lib/domains/de/mpg/eva.txt
The Max Planck Institute for Evolutionary Anthropology ("MPI EVA") is a publicly funded research and educational institution in Leipzig, Germany.
* The institute's official website is https://www.eva.mpg.de/
* The MPI EVA offers an accredited post-graduate (Ph.D.) study programme in collaboration with the University of Leipzig — the [Leipzig School of Human Origins](https://www.leipzig-school.eva.mpg.de/) (LSHO).  This forms part of the Max Planck Society's initiative of International Max Planck Research Schools (IMPRS).
* As part of the LSHO, students receive training in bioinformatics, including a course in Python programming for genomics analysis — this is mentioned in the [Ph.D. course outline](https://www.leipzig-school.eva.mpg.de/phd-program.html). The bioinformatics and programming …
> Please consider adding: Max Planck Institute for Evolutionary Anthropology

- lib/domains/vn/edu/ndun.txt
We are Nam Dinh University of Nursing - a public university in Vietnam, research and teaching in medicine. We are very interested in JetBrains' tools and we want to use your tools for our teachers and students. Thank you very much!
Our information:
- Vietnamese name: Trường Đại học Điều dưỡng Nam Định
- English name: Nam Dinh University of Nursing
- English acronym: NDUN
- Type of education: Higher Education
- Official website: http://ndun.edu.vn
- Email: dieuduong@ndun.edu.vn
- Address: 257, Han Thuyen street, Nam Dinh city, Nam Dinh province, Vietnam
> Request to add Nam Dinh University of Nursing

- lib/domains/ru/uran/imm.txt
N.N. Krasovskii Institute of Mathematics and Mechanics (IMM UB RAS)
https://www.imm.uran.ru/rus/Pages/default.aspx
> add domain of IMM UB RAS imm.uran.ru

- lib/domains/si/sts.txt
Full name: Srednja tehniška šola Koper
Abbreviation: STŠ
Official website: http://www.sts.si
Contact person - IT courses: Katarina Novoselec
Email: katarina.novoselec@sts.si
Address: Šmarska cesta 4, 6000 Koper - Capodistria, Slovenia
> Request to add Srednja tehniška šola Koper

- lib/domains/uk/org/wmgacademy.txt
https://coventry.wmgacademy.org.uk/students/curriculum/
Detailed on this page are the curriculum listings for both KS4 (2-year) and KS5 (2-year) courses, both of which include Computer Science
> PR for WMG Academy

- lib/domains/nl/ichthuslyceum.txt
This is a high school in Driehuis, The Netherlands
Official site: [www.ichthuslyceum.nl](https://ichthuslyceum.nl)
Contact person: M. Hoogstoevenbeld (One of my IT teachers)
Email: m.hoogstoevenbeld@ichthuslyceum.nl
Address: Wolff en Dekenlaan 1 1985 HP Driehuis
> Request to add Ichthus Lyceum

- lib/domains/be/hers.txt
- **the university official website URL, if it is different from the domain you are submitting**: <https://hers.be>
- **a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university**: <http://progcours.hers.be/cocoon/en/programmes/E1INFO01_C.html>
- **a URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students.**: <https://hers.be/vie-etudiante/organisation/office-365-pour-tous>
> Add domain of Haute École Robert Schuman hers.be

- lib/domains/ru/lit1533.txt
Mail domain: lit1533.ru (scolars and teachers have e-mails at this domain)
Web-site (with forward from lit1533.ru): https://www.lit.msu.ru
Web-site at Moscow Department of Education and Science: https://lyc1533.mskobr.ru
> Adding domain lit1533.ru

- lib/domains/pt/ucpcrp.txt
Although there is already a Universidade Catolica Portugesa, the campus from Oporto is missing. It is important to be there because the email ends with "ucpcrp".
> add Universidade Catolica Portuguesa - Porto

- lib/domains/com/saintluc-cambrai.txt
School Name : Ensemble Saint Luc Cambrai (in the north of France)
Official URL Website : https://www.saintluc-cambrai.com/
IT Formation in the school : https://ltpes.saintluc-cambrai.com/bts-sio.html
Proofs that the school recognizes the domain name : 
1) https://prnt.sc/sact0g
2) https://prnt.sc/sactzj in the footer of LTPES Page in our website (https://ltpes.saintluc-cambrai.com/)
3) https://prnt.sc/sacwfh
> Add Domain Saintluc-cambrai.com to JetBrains List

- lib/domains/nl/dominicuscollege.txt
This PR adds DominicusCollege.nl, which is used for both the [website](http://www.dominicuscollege.nl/onze-school/over-het-dominicus-college) and e-mailaccounts (see page footer).
> Add Dominicus College

- lib/domains/gr/edu/mitropolitiko.txt
Metropolitan College student e-mails were previously added, I would like to add our professors mail acount.
College homepage: https://mitropolitiko.edu.gr/
Article confirming the e-mail domain is what it is: https://www.newsbeast.gr/greece/arthro/5521119/giorgos-paxinos-athanasios-fokas-dyo-koryfaioi-epistimones-syzitoyn-sto-mitropolitiko-kollegio
Thanks for giving us the best tools! We appreciate it.
> Add AMC Metropolitan College professors accounts

- lib/domains/de/schulbistum/gjo.txt
This adds support for the "Gymnasium Johanneum", which is more commonly known as "Die Loburg" (Gymnasium is equivalent to High School).
Website: https://die-loburg.de
Course Site for IT: https://die-loburg.de/informatik
As the school is part of the "Schulbistum" network, teachers of this school are assigned an email-account at the sub-domain gjo.schulbistum.de. Other schools in this network have other subdomains, e.g. the already merged "St. Michael Gymnasium Ahlen" (https://github.com/JetBrains/swot/blob/master/lib/domains/de/schulbistum/gsma.txt).
Thanks!
> Added Gymnasium Johanneum

- lib/domains/de/ms/stein.txt
This adds the Freiherr-vom-Stein Gymnasium Muenster, which is the local Gymnasium (equivalent to american High School).
School Website: [fsg-ms.de](http://fsg-ms.de/) or [freiherr-vom-stein-gymnasium-muenster.de](http://www.freiherr-vom-stein-gymnasium-muenster.de/)
As the mail server for local schools is managed by the municipality, every school gets a subdomain of `ms.de` in our case it is `stein.ms.de`. Teachers as well as students get an email adress following the `lastname@school_subdomain` scheme.
Thanks!
> Add FSG Muenster

- lib/domains/jp/ac/numazu-vtc.txt
Numazu Vocational Training Center
Website: http://numazu-vtc.ac.jp/
> Add numazu-vtc.ac.jp domain

- lib/domains/il/org/tzfonet.txt
It's not a typo: the domain is tzfonet but the name is tzafonet.
i.e: example@tzfonet.org.il
Proof: [youtube video](https://youtu.be/WrcF4iT4d9M) tzafonet is a well known educational organization in Israel
it includes a group of schools.
> add tzfonet

- lib/domains/it/edu/liceogalileicatania.txt
There is no mention of the school email on the website itself, however, the domain is the same. 
I hope that is enough.
> Added Liceo Galileo Galilei Catania

- lib/domains/ca/on/scdsb.txt
The school website is http://ban.scdsb.on.ca/. The student domain is scdsb.on.ca, as it is a part of the Simcoe Country District School Board. Thank you.
> Add Banting Memorial High School text file

- lib/domains/net/29zx.txt
- lib/domains/net/nj29jt.txt
After another two months' attempt, we finally got the paper you need.
Sorry for the inconvenience. The domain 29zx.net is usually used to allocate email accounts for our teachers and students. For that reason, we usually don't make it accessible as a website.(In China, it's really tough to make a website available for a long period of time: you need to BeiAn, a very complicate matter.) That's why you can't access the domain 29zx.net.
At present, as we have got the paper you need, the website 29zx.net will be available for a few days for you to validate.
> Nanjing No.29 High School

- lib/domains/us/ny/k12/northport.txt
Add Northport High School.
E-Mail Domain: `@northport.k12.ny.us`.
> Add Northport High School

- lib/domains/fr/univ-catholille.txt
official website : http://www.univ-catholille.fr/
it courses : https://www.univ-catholille.fr/formations/fiche/3182
email address domain : @univ-catholille.fr
Note: The domain used to be in this repo before it was renamed to "lacatholille.fr" (commit 478148c1), however teachers still have their emails with the univ-catholille.fr domain as you can see on that IT course page with "Julie Jacques" who is the head of this course.
> add univ-catholille.fr back

- lib/domains/br/eep.txt
- The university official website URL: https://www.eep.br/
- URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university:
https://www.eep.br/informacoes-ciecomputacao
https://www.eep.br/informacoes-engenharia-comp
- URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students:
https://sway.office.com/KVbEhdMOGw4JTb7T?ref=Link
> Add EEP Domain

- lib/domains/hk/edu/twghlkss.txt
Adding the school above whose official website is: https://twghlkss.edu.hk/
> Include TWGHs Li Ka Shing College

- lib/domains/com/ecole-hexagone.txt
École Hexagone is a post-graduate school based in Versailles, France and also in Riyadh, KSA.
It offers a 5-years program in IT.
Students, staff, faculty and alumni have a lifetime email from ecole-hexagone.com domain.
> École Hexagone

- lib/domains/net/hayscisd/g.txt
Please add hayscisd.net for Johnson High School in Hays Consolidated Independent School District (Hays CISD) 
Official School Website https://www.hayscisd.net/Domain/2797 
Technology Classes https://www.hayscisd.net/Page/6225 
School Email Contact Info https://www.hayscisd.net/Page/7071 
School Physical Address:
Johnson High School
4260 FM 967 
Buda, TX 78610
> add Johnson High School for Hays CISD

- lib/domains/rs/ac/bg/etf.txt
Primary domain for University of Belgrade, School of Electrical Engineering, used together with etf.rs
> Add full domain for University of Belgrade, School of Electrical Engineering

- lib/domains/fr/u-psud.txt
- lib/domains/fr/universite-paris-saclay.txt
Paris Sud University has become Paris Saclay University since January 1, 2020
> Update and rename u-psud.txt to universite-paris-saclay.txt

- lib/domains/pl/edu/teb.txt
This pull request adds the _TEB Edukacja_ school located in Poland.
Official websites: https://technikum.pl and https://teb.pl/
**VERY IMPORTANT NOTE**:
I am aware the domain in my pull request (**_teb.edu.pl_**) refers to a non-existent website that doesn't point to any school. This is really not my fault that they don't know how to redirect the user to one of their websites.
... hovewer the **_teb.edu.pl_** domain is indeed **in use by every teacher's and every student's e-mail address** (`name.surname@teb.edu.pl`), for example `krystian.kolucki@teb.edu.pl` (which is my e-mail on Outlook, for Office 365 for schools).
If you don't believe me, you can try looking the domain up on websites like https://whois.domaintools.com/teb.edu.pl, and you'll see that the domain **is** registered to …
> Add "teb.edu.pl" domain for TEB Edukacja

- lib/domains/co/edu/elpoli.txt
Add subdomain `elpoli` associated with Politecnico Colombiano Jaime Isaza Cadavid institute in order so we can apply for student licenses when we're using `@elpoli.edu.co` email's domain.
https://politecnicojic.edu.co/index.php
> Added Politecnico Colombiano Jaime Isaza Cadavid - elpoli

- lib/domains/tw/edu/kl/gm.txt
the school official website URL
> https://mcjh.kl.edu.tw/
an URL of a page on the official website where an IT-related long-term (>1 year) course is offered by the school
> It's a junior high school and they have some STEM course, but there is no page about it.
a proof showing that the school recognizes the domain which you are submitting as an official email domain for the students.
> kl.edu.tw is the official domain of Keelung Bureau, they provide a common domain `gm.kl.edu.tw` for all the junior high school in Keelung
> Add Keelung Municipal Ming Chwan Junior High School

- lib/domains/net/achievementtraining.txt
Second attempt.
Realised the I did not state in the original pull request that Achievement Training is part of City College Plymouth.
https://www.achievementtraining.com/about-us/
The company is a full member of the Devon Cornwall & Plymouth Training Providers Network that acts as a forum for local training providers and have formed good relationships with a wide range of other external organisations, including our parent company, **City College Plymouth**. These partnership arrangements are extremely useful and enable ATL to provide a service to employers and learners which go beyond just training.
We are also monitored by OFSTED, like schools and colleges throughout the UK.
> Achievement Training 

- lib/domains/co/edu/misena.txt
El Servicio Nacional de Aprendizaje SENA de colombia (https://www.sena.edu.co/es-co/Paginas/default.aspx) Utiliza el dominio misena.edu.co para las cuentas estudiantiles de aprendices.
> Se agrega el dominio misena.edu.co

- lib/domains/co/edu/usantoto.txt
Please add the usantoto.edu.co domain.
It is a branch of the 'Universidad Santo Tomás' in Tunja, Boyacá, Colombia.
- Web site: https://www.ustatunja.edu.co
- Systems Engineering web page: https://www.ustatunja.edu.co/inicio-ingenieria-sistemas
- Career contents: https://www.ustatunja.edu.co/plan-de-estudios-sistemas#primer-semestre (per semester)
Thank you.
> Add usantoto.edu.co domain

- lib/domains/jp/chibakoudai/p.txt
University Website:
https://www.it-chiba.ac.jp/english/
IT related courses:
https://www.it-chiba.ac.jp/english/graduate/
A page that shows p.chibakoudai.jp is used for email address for staff at the university:
https://www.it-chiba.ac.jp/career/cp_recruit/professor/
s.chibakoudai.jp is used for students and already added
> add Chiba Institute of Technology (staff email domain)

- lib/domains/in/ac/gectcr.txt
Add domain operated by Government Engineering College, Thrissur, Kerala, India.
Courses offered: http://gectcr.ac.in/academics/
> Add Government Engineering College, Thrissur

- lib/domains/cr/ac/ufide.txt
**Description of changes**
- Adding a second domain for Universidad Fidélitas, ufidelitas.ac.cr is already registered.
- ufide.ac.cr is used for students email addresses.
**Things you can do to verify the information**
- Go to [nic.cr/whois](https://www.nic.cr/whois/), from the drop down menu choose **`.ac.cr`** and type **`ufide`** in the search box and hit "Buscar". You'll see that this domain registered under Universidad Fidélitas.
- You can do the same with ufidelitas.ac.cr to see how both domains match.
- This is the official page with details about their program (Computer Systems Engineering): https://ufidelitas.ac.cr/carrera/bachillerato-ingenieria-sistemas-de-computacion/
**Additional Information**
- Official University Website: https://ufidelitas.ac.cr/
If there's anything else …
> Student mail domain for Universidad Fidelitas

- lib/domains/com/onmicrosoft/gymro.txt
Official Website: http://gymnasium-rodenkirchen.de (yes, still no https in 2020)
School Contact email: gymro@stadt-koeln.de
> Add Gymnasium Rodenkirchen

- lib/domains/de/thu.txt
added the domain file for Technische Hochschule Ulm / Ulm University of Applied Science
Webpage www.thu.de which is redirected to the old domain hs-ulm.de
A link to a Computer Science Course : https://studium.hs-ulm.de/en/Pages/Studiengang_CTS.aspx
The Mail Addresses have the schema {forname}.{surname}@thu.de
> Add the Ulm University of Applied Science

- lib/domains/nl/cals/leerling.txt
Official website URL: https://www.cals.nl/  
Long term IT related course: https://www.cals.nl/nieuwegein/onderwijs/technasium/over-technasium/
Official email domain for the enrolled students: https://www.cals.nl/nieuwegein/wp-content/uploads/sites/2/2020/03/Cals-mail-lln-NG-instructies.pdf
> Add Cals College

- lib/domains/com/lpssonline.txt
Requesting to add lpssonline.com to the Educational List.
> Adding domain for Lafayette Parish School System a US K-12 school

- lib/domains/br/edu/pucgoias.txt
Our university has two domains, one of them was already submitted. But the main domain is this one.
Our site is: https://www.pucgoias.edu.br/
> Add Pontificial Catholic University of Goiás

- lib/domains/br/edu/ifal.txt
Official Website (English): https://www2.ifal.edu.br/en
URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: https://www2.ifal.edu.br/en/courses/graduation
URL of a page or some other proof (.pdf or a screenshot are OK) showing that the university recognizes the domain which you are submitting as an official email domain for the enrolled students: http://webmail.ifal.edu.br/
> Added ifal.edu.br

- lib/domains/com/fallschurchrobotics.txt
Falls Church High School's Robotics Club uses Jetbrains products (currently using 2x open-source licenses). Our district, Fairfax Co. Public Schools, is already on this repo but due to a country restriction with our email servers, we cannot sign up. This domain is used by FCHS students. We're planning on using this to allow for members to code while we do distance learning.
> Falls Church High School

- lib/domains/fr/supagro.txt
L'institut Agro | Montpellier SupAgro
**Institution/School Website**
https://supagro.fr/ redirects since January to https://www.montpellier-supagro.fr/
<user>@supagro.fr e-mails can be found all across the website
- contact@supagro.fr in the footer
- Teaching programs have contact cards for related directors of studies and teachers like [here](https://en.montpellier-supagro.fr/programs/degree-programs/engineering-master-degrees) and [there](https://en.montpellier-supagro.fr/training/option-data-science-agronomy-and-agri-food)
**IT-related course**
https://www.montpellier-supagro.fr/formations/catalogue-des-formations/recherche-d-une-formation/option-data-science-pour-lagronomie
> Adding supagro.fr

- lib/domains/pt/autonoma.txt
- lib/domains/pt/ual.txt
- lib/domains/pt/ual/students.txt
Added the new domain for Universidade Autónoma de Lisboa, and updated the existing information. We are migrating to @autonoma.pt
Institution website: https://autonoma.pt/
Computer Science Engineering BSc course information: https://autonoma.pt/cursos/engenharia-informatica/
> Update UAL access

- lib/domains/ng/edu/adelekeuniversity/student.txt
Official url of Adeleke University: https://adelekeuniversity.edu.ng/
The Faculty of Science page: https://adelekeuniversity.edu.ng/faculty-of-science/
> Include Adeleke University

- lib/domains/ua/edu/ukma.txt
Add National University Of Kyiv-Mohyla Academy to the domains list.  
Website: https://www.ukma.edu.ua/eng/
> Add NaUKMA to domains

- lib/domains/us/ga/k12/rockdale/students.txt
Salem High School in Rockdale County School District
Google Maps Link to the district
Rockdale County School District: https://www.google.com/maps/place/Rockdale+County+School+District,+GA/@33.6808979,-84.1197578,11z/
> Salem High School

- lib/domains/org/hspu.txt
- lib/domains/ru/edu/herzen.txt
- lib/domains/ru/spb/herzen.txt
Now only the domain herzen.spb.ru has been added, but it is issued only to teachers. There is a domain for students herzen.edu.ru, so I added it. But by 2025, the university plans to ditch these domains in favor of a single hspu.org. As evidence, I attached a response from the university administration by hiding my personal email (in Russian).
<details>
<summary>Email</summary>
[email-hspu.pdf](https://github.com/JetBrains/swot/files/5214574/email-hspu.pdf)
</details>
I also added the name of the university in Russian for the domain herzen.spb.ru.
- Official site: https://herzen.spb.ru/
- About hspu.org: https://eos.herzen.spb.ru/ and https://id.hspu.org/
> Add new The Herzen State Pedagogical University of Russia (HSPU) domains

- lib/domains/fr/toulouse-inp/etu.txt
Hello,
The new students mail addresses now given at [INP Toulouse](https://www.inp-toulouse.fr/fr/index.html) are of the format `@etu.toulouse-inp.fr`.
Should the `lib/domains/fr/inp-toulouse.txt` be removed? Some people might still be using it...  
Some student also have an `inp-toulouse.fr`, but I am not sure if those are also given to new students.
I also do not know if there are other subdomains in `toulouse-inp.fr` that should be added.
> Add new student toulouse-inp mail address

- lib/domains/org/dcrustm.txt
http://dcrustm.ac.in/departments/engineering/computer-science-and-engineering
Only dcrustm.org used to be there but recently(https://ernet.in/content/domain-registration) migrated to dcrustm.ac.in for website but emails still on dcrustm.org for backward compatibility
> Add Deenbandhu Chhotu Ram University of Science and Technology

- lib/domains/au/edu/ballarat.txt
- lib/domains/au/edu/federation.txt
University of Ballarat changed to Federation University Australia in 2014.
> Rename University of Ballarat to Federation University Australia

- lib/domains/np/edu/keckist.txt
the university official website URLs: https://www.keckist.edu.np/, https://www.kecktm.edu.np/
long-term (>1 year) IT related courses:
-- https://www.kecktm.edu.np/category/academics/computer_engineering
> Add kathmandu engineering college

- lib/domains/li/schulen.txt
Berufsmaturitäts Schule Liechtenstein für Informatikzwecke
> Add BMS Liechtenstein

- lib/domains/cz/gkolin.txt
Gymnázium, Kolín III, Žižkova 162
Grammar school in Kolín, the Czech Rep.
> Gymnázium Kolín - gkolin.txt

- lib/domains/ie/coccork.txt
Link to site: https://corkcollegeofcommerce.ie/
> Added Cork College of Commerce

- lib/domains/it/iiscuriesraffa.txt
IIS Curie Sraffa Milano
https://www.iiscuriesraffa.it/
http://www.iiscuriesraffa.it/wp-content/uploads/2019/12/PTOF_2019_2020_aggiornato_al_26_11_19.pdf
https://whois.domaintools.com/iiscuriesraffa.it
> Domain iiscuriesraffa.it

- lib/domains/pl/erzeszow/edu.txt
The city of Rzeszów has an e-mail for students of public schools. Almost 30,000 students use it! In a few cases, these are also primary schools, but this function is used mainly by high schools.
The email address has the form:
{three letters of the name}{three letters of the surname}.{three random numbers}@edu.erzeszow.pl
More information can be found on the verification and account creation page in Office 365: https://edu.erzeszow.pl/o365Web
Or on the microsoft website: https://customers.microsoft.com/en-us/story/753634-rzeszow-education-office365-poland-pl
Warning! You have to use google translate, the pages are in Polish.
> Adding mail for students of the city of Rzeszów

- lib/domains/nl/novi-youngcapital.txt
Added Novi Hogeschool second domain
First domain is: novi-education.nl
**Website:** https://www.novi.nl/
**Software development course (undergraduate) in dutch:** https://www.novi.nl/software-development/
> Added Novi Hogeschool second domain

- lib/domains/np/edu/islingtoncollege.txt
Adding Islington College, where I am currently doing my undergraduate Networking and IT Security degree!
Islington College is located at Kamal Marg, Kamal Pokhari, Kathmandu, Nepal and is affiliated to London Metropolitan University, London.
The official domain of the institution is islington.edu.np, and the website homepage is located at https://islington.edu.np/.
> Adding islington college

- lib/domains/pt/ips/estsetubal.txt
- lib/domains/pt/ips/estudantes.txt
The email domain for Escola Superior de Tecnologias de Setúbal, part of Instituto Politécnico de Setúbal is @estsetubal.ips.pt
Institution website: https://www.estsetubal.ips.pt/
Computer Science BSc information page (in portuguese): https://www.estsetubal.ips.pt/cursos/licenciaturas/ei
> Update ESTS IPS domain

- lib/domains/in/ac/nitandhra.txt
a link to the site:
https://nitandhra.ac.in/
> Adding National Institute of Technology, Andhra Pradesh

- lib/domains/it/edu/isfalcone/alu.txt
Site of the school: http://isfalcone.edu.it/
Students domain:
> Add  Institute of Higher Secondary Education "Giovanni Falcone" Loano, Italy

- lib/domains/uk/ac/ed/sms.txt
Add student email domain of @sms.ed.ac.uk
Link providing info about this email domain being used for students: [https://www.ed.ac.uk/information-services/computing/comms-and-collab/email/directories](https://www.ed.ac.uk/information-services/computing/comms-and-collab/email/directories)
Link about this university having a Computer Science program: https://www.ed.ac.uk/informatics/about
Let me know if any other information is needed.
> added UE student domain

- lib/domains/de/hzdr.txt
- lib/domains/de/mpi-cbg.txt
This PR adds the domains for the Max Planck Institute of Molecular Cell Biology and Genetics and the Helmholtz-Zentrum Dresden-Rossendorf. Both offer post-graduate programs, see http://imprs-celldevosys.de and https://www.hzdr.de/db/Cms?pNid=1908
> Add MPI-CBG and HZDR domains

- lib/domains/pl/edu/legnica/pwsz/gsuite.txt
- lib/domains/pl/edu/legnica/pwsz/stud.txt
As The Witelon State University of Applied Sciences in Legnica started using GSuite, I'm adding new domains to the list:
* `@stud.pwsz.legnica.edu.pl` for students,
* `@gsuite.pwsz.legnica.edu.pl` for academic teachers.
The old ones are working too.
> PWSZ Legnica new domains added

- lib/domains/fr/u-paris/etu.txt
from janurary 2020, university of Paris 5 (Descartes) and university of Paris 7 (Diderot) made an alliance and became University of Paris. Since then we students have email under the domain name of " etu.u-paris.fr "
> ADD university of Paris

- lib/domains/de/tu-braunschweig.txt
- lib/domains/de/tu-bs.txt
Both `tu-bs.de` and `tu-braunschweig.de` are owned by the same university — Technische Universität [Carolo-Wilhelmina zu] Braunschweig (Technical University of Braunschweig). So I think the names of the university should match across both domain files.
The 'Carolo-Wilhelmina' part is to be used with 'zu', this is why I also updated the `tu-bs.txt`
> Update tu-bs.txt and tu-braunschweig.txt so that they match

- lib/domains/au/edu/griffith.txt
- lib/domains/au/edu/gu.txt
Main website: https://www.griffith.edu.au
IT Degree: https://www148.griffith.edu.au/programs-courses/Program/1042/Overview/Domestic
email format for staff: https://staffhelp.secure.griffith.edu.au/app/answers/detail/a_id/3188/kw/email
Students use the @griffithuni.edu.au domain that it already stored.
> Griffith University academic email domain

- lib/domains/es/ieselrincon.txt
We previusly only used to give students the licenses, we now have teachers on the same domain, I didnt see a way whitelist only the domain and the subdomain,
Changelog:
Added IES El Rincon Domain ( didnt remove subdomain)
> Update IES El Rincon domains

- lib/domains/org/imdea.txt
The IMDEA Institutes are public research centers of excellence based in the Region of Madrid. They were established as independent foundations between 2006 and 2007 at the initiative of the regional government. They are focused on seven strategic areas for society from a business, scientific and technological point of view: water, food, energy, materials, nanoscience, networks and software. 
IMDEA Software institute professors and students are the ones that will mostly use JetBrains products for teaching and research activities. 
* website of the foundation: www.imdea.org/en
* website of the software institute: www.software.imdea.org
* one of the courses taught by IMDEA professors: http://muss.fi.upm.es/en/asigCS.php
> added IMDEA Institute (imdea.org) domain

- lib/domains/us/va/k12/wcps/students.txt
Website is https://www.wcps.k12.va.us/
Domain is students.wcps.k12.va.us
Proof:
> Add the Warren County Public Schools domain

- lib/domains/se/gti.txt
The official website of the school: https://www.gti.se/
Technical program: https://www.gti.se/te.php
Science program: https://www.gti.se/na.php
> Added Gothenburgs Institute of Technology (GTI) to the domains list

- lib/domains/at/ac/htl-kaindorf.txt
Website URL (German): [www.htl-kaindorf.at](www.htl-kaindorf.at)
Informatics Department: [https://www.htl-kaindorf.at/abteilungen/informatik](https://www.htl-kaindorf.at/abteilungen/informatik)
There already is a entry for only the `htl-kaindorf.at` email but the `ac.at` one did not exist
> Added htl-kaindorf.ac.at (academic email of HTBLA Kaindorf)

- lib/domains/ch/eduvaud.txt
With the COVID a region of Switzerland has created a domain for all the schools, and so we have change our mail addresses.
Example:
**@epsic.educanet2.ch** become **@eduvaud.ch,** also **@educanet2.ch** will be shutdown the 31 december 2020, so a lot of the schools with _educanet2_ will use _eduvaud_ if they are in the Vaud region of Switzerland.
I don't know if you want to delete the files under lib/domains/ch/educanet2
> Add @eduvaud.ch

- lib/domains/org/lhprep.txt
- lib/domains/org/lhps.txt
Adds two domains used by current Lake Highland Preparatory School students (lhprep.org) and faculty (lhps.org). Alumni do not retain access to their email addresses. 
LHPS offers high school and college-level (AP) courses in computer science: https://www.lhps.org/academics/upper-school/curriculum
> Add Lake Highland Preparatory School

- lib/domains/academy/campus.txt
- lib/domains/eu/campus-academy.txt
- lib/domains/fr/imie-nantes.txt
- lib/domains/fr/imie.txt
imie domains are no longer active, with some warnings : 
- imie.fr and imie-nantes.fr shall not be used by anyone because these mailboxes are going deleted
- imie-paris.fr is not the same entity and its management shall be done on separate requests
> imie domains no longer active

- lib/domains/de/genoapps.txt
URL genoapps.de resolves to genokolleg.de (Official Site)
In the footer there is a link to mail.genoapps.de for Webmail access. The Student Mails are @genoapps.de
A site that proves there are Informatic Course offers can be found here: https://genokolleg.de/bildungsangebot/informatik/
> Added Genokolleg Münster

- lib/domains/au/edu/opencolleges.txt
Hello!
Open Colleges (https://www.opencolleges.edu.au/) is a registered learning institute in Australia which provides a variety of courses including diploma courses.
It'd be great to have it added to this list so staff/students can use some of the JetBrains products. Thanks
> Add Open Colleges

- lib/domains/cn/org/sis.txt
Official school website URL: [](https://www.sis-shekou.org/)
School address: 1089-51 Wanghai Road, Nanshan, Shenzhen, Guangdong, People's Republic of China
> Add Shekou International School

- lib/domains/be/efpl.txt
Domain: [efpl.be](http://efpl.be) (open in new tab)
Which points to the education section website of the Province of Liège (an administrative subdivision in Belgium), officially called "Enseignement Provincial" or "Enseignement de la Province de Liège" if you are mentioning it outside of thesaid province. This groups several public education institutes under a common network.
Example of relevant education program: [Bachelor degree in Management Information Technology](http://www.provincedeliege.be/node/2919) which is a 3-4 years college program organized by two institutes from the following network. This program is described by the following (translated from the given page):
> Develops skill sets in different axes:
> 
> Procedural, management-oriented and object-oriented programming.
> …
> Add `Enseignement de la Province de Liège`

- lib/domains/de/hss-wi.txt
- lib/domains/de/hss-wiesloch.txt
Website of the school: https://www.hss-wiesloch.de/
The school changed the email from **myhss.de** to **hss-wi.de** for students and to **hss-wiesloch.de** for teachers.
You can find the new emails on this page:
https://www.hss-wiesloch.de/ueber-uns/personen/kollegium/
The domain **myhss.de** is still in use for old accounts.
Pull-Request of [de/myhss.txt](https://github.com/JetBrains/swot/blob/master/lib/domains/de/myhss.txt):
https://github.com/JetBrains/swot/pull/3088
> Add hss-wi and hss-wiesloch (Hubert-Sternberg-Schule Wiesloch)

- lib/domains/fr/cyu.txt
- lib/domains/fr/cyu/etu.txt
https://www.cyu.fr/
Transition in progress from u-cergy.fr and eisti.fr to cyu.fr
Mail addresses for students are on etu.cyu.fr domain.
> Add CY Cergy Paris Université

- lib/domains/org/palihigh/pchs.txt
School URL: https://www.palihigh.org/
IT course URL(Look page 71 and beyond for info): https://www.palihigh.org/pdfs/Course%20Catalog%2032819.pdf
> Add Palisades Charter High School

- lib/domains/de/uni-a.txt
university official website URL: https://www.uni-augsburg.de/en/
a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: e.g.: https://www.uni-augsburg.de/en/studium/studienangebot/uebersicht/computer-science-msc/
Proof of address, wehere you can see that I'm enrolled as a student (i'm enrolled in courses), and that my official University address is @uni-a.de
> Added @uni-a.de for University Augsburg

- lib/domains/be/dbz.txt
https://dbz.be/ict-als-vak-en-ict-in-de-vakken
> Don Boscocollege Zwijnaarde

- lib/domains/com/plaiaundi.txt
- lib/domains/eus/plaiaundi.txt
- lib/domains/net/plaiaundi.txt
There are two domains for teacher emails (com and eus), and one for student emails (net):
-  [http://www.plaiaundi.com](http://www.plaiaundi.com)
-  [http://www.plaiaundi.net](http://www.plaiaundi.net)
-  [http://www.plaiaundi.eus](http://www.plaiaundi.eus)
> Add IES Plaiaundi BHI

- lib/domains/jp/ac/kobedenshi.txt
Kobe Institute of Computing(Japanese: Kobedenshi Senmon-gakko) is a technical shcool in Kobe, Japan.
> add domain(kobedenshi.ac.jp)

- lib/domains/com/onmicrosoft/1lokutno.txt
1lo im. gen. J. H. Dabrowskiego is a high school in Kutno, Poland. They also offer curriculum with extended computer science, mathematics and physics. The official website of the school: https://www.dabrowszczak.pl/
Educational offer with a mention of written above educational program: https://www.dabrowszczak.pl/index.php?c=page&id=173
> added 1lo im. J. H. Dabrowskiego w Kutnie

- lib/domains/ro/pub.txt
- lib/domains/ro/upb.txt
I corrected the university name since the documents demand that the official english name has the word "POLITEHNICA" in all capitals.
> Corrected University POLITEHNICA of Bucharest's name

- lib/domains/gr/edu/anatolia.txt
1) Official URL address of Anatolia College: https://anatolia.edu.gr/en/
2) Anatolia College follows the education curriculum provided by the Greek Ministry of Education. Because of that, students are enrolled in IT and Computer Science classes during all the 6 years of gymnasium and lyceum. An outline of the Greek education system is presented in the website below:
https://en.wikipedia.org/wiki/Education_in_Greece#Lyceum
In addition, Anatolia College provides IB studies, which also include a Computer Science class. The following is a document from Anatolia College that proves my claim:
http://anatolia.edu.gr/images/highschool/IBDP/ibdp_brochure_april2019_english.pdf (page 15)
3) On [this](https://anatolia.edu.gr/en/contact) page there can be seen the e-mail addresses of some of the …
> Add Anatolia College

- lib/domains/id/ac/stis.txt
Politeknik Statistika STIS, Jakarta, Indonesia
https://stis.ac.id/
> Add stis.ac.id domain of STIS Polytechnic of Statistics

- lib/domains/de/bs1traunstein.txt
Homepage-URL: https://bs1ts.de/
Course-URL: https://bs1ts.de/bs1/berufe/elektroberufe/
The URL bs1traunstein.de redirects to bs1ts.de
If you scroll down on Course-URL, you can see teacher E-Mails, which end with this URL.
~~While this URL is also used for student E-Mails there is, to my knowledge, nothing on the website that confirms these are used for students.~~
Added an anonymized screenshot of me being logged into my student E-Mail.
> Add Staatliche Berufsschule I Traunstein

- lib/domains/eg/edu/moe/t3.txt
Non-commercial school's teachers belong to Ministry of Education
> Add teachers of non-commercial schools of ministry of education (moe)

- lib/domains/uk/co/chesterfieldhigh.txt
Note: Website is chesterfieldhigh.org.uk, email domain is chesterfieldhigh.co.uk.
> Added Chesterfield High School

- lib/domains/in/ac/iiitp.txt
Adding the domain of Indian Institute of Information Technology, Pune (IIITP) of India.
Official Website: [https://www.iiitp.ac.in/](https://www.iiitp.ac.in/)
Course Page: [https://www.iiitp.ac.in/btech-cse](https://www.iiitp.ac.in/btech-cse)
Email Page: [https://mail.google.com/a/iiitp.ac.in](https://mail.google.com/a/iiitp.ac.in)
> Add IIIT Pune

- lib/domains/uk/org/excalibur/stjohns.txt
Academy Website  - [St Johns Marlbrough](https://www.stjohns.excalibur.org.uk/)
St Johns offers various higher education courses such as A-Levels and BTECs. Notably it offers a two year A-Level course in Computer Science which teaches many in depth software devlopment techniques.
The course detail PDF can be found on this [Course Details](https://www.stjohns.excalibur.org.uk/sixth-form/courses/#1583486728415-e6feb5cd-f627) page
Additionally, proof of recoginzation of the domain added can be seen on the Academy [Contact](https://www.stjohns.excalibur.org.uk/about-us/contact/) page
> Add St Johns Academy, Marlborough

- lib/domains/de/musin/wsg.txt
Please add our Werner-von-Siemens-Gymnasium München
the school official website URL:
http://www.wsg.musin.de/
an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course:
http://www.wsg.musin.de/unterricht/informatik
a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students:
http://www.wsg.musin.de/kontakt/kontaktformular - compare to the email domain mentioned on this page
> Adding Städtisches Werner-von-Siemens-Gymnasium München

- lib/domains/sk/gmet.txt
Official website: https://gmet.edupage.org/
However, teachers and studens use `@gmet.sk` emails (see https://gmet.edupage.org/contact/).
> Add gmet.sk

- lib/domains/ba/size.txt
Hope I didn't mess anything up.
All of the domains for my faculty are in the size.ba most of the time they will be formatted as name-surnameYEAR@size.ba.
https://unze.ba/ - website of my university
https://ptf.unze.ba/ - website of my faculty which offers a full 3 year course in software engineering
Above link is a screenshot of my university mail being used in google classroom as proof.
> added files

- lib/domains/de/bbs1-mainz/unterricht.txt
Please add the BBS1 Mainz.
Official Website: http://bbs1-mainz.de/ & http://bbs1-mainz.com/
a URL of a page on the official website where a long-term (>1 year) IT related course is offered by the university: http://www.bbs1-mainz.com/bildungsgaenge/berufsschule/berufsfelder-elektrotechnikinformatik.html
German: 
English (Google Translate):
> Adding BBS1 Mainz

- lib/domains/de/maxplanckschools.txt
email domain @maxplanckschools.de. Find info on the program [here](https://www.maxplanckschools.de/en/cognition).
> added Max Planck School of Cognition

- lib/domains/ru/sibguti.txt
When switching to remote leaning, our university acquired a new domain for organizing work in Google services. The redirection from the new domain (sibguti.ru) to the old one (sibsutis.ru) is also configured.
> Add new domain for SibSUTIS

- lib/domains/com/burygrammar.txt
Bury Grammar School is a British secondary school/sixth form college that provides GCSE Computer Science and A-Level Computer Science to its students (as can be found here - https://www.burygrammar.com/academic/academic-faculties/social-sciences-and-computer-science-faculty/computer-science).
Its main URL is https://burygrammar.com/
Proof of email using this domain:
> Add Bury Grammar School

- lib/domains/de/hansenberg/edu.txt
- lib/domains/schule/smmp-eb.txt
URL of my school: https://www.hansenberg.de/
URL of the page showing my school offering an IT-Course: https://www.hansenberg.de/lernen/unterricht/faecher.html
As to the school recognising the domain: in footer of the homepage, you can see the school using the domain themselves, meaning one cannot get an email of said domain without them knowing. I hope that is enough proof for you to accept that as them recognising a student's email having their domain as an official one.
> added 'hansenberg' folder to lib/domains/de

- lib/domains/org/seattleschools.txt
Added Garfield high School to the Seattle public schools(SPS) domain.
> Added Garfield high school

- lib/domains/tr/edu/ticaret.txt
Adding Istanbul Commerce University to the fork, the previous domain is iticu.edu.tr which is already in the list, the updated domain is ticaret.edu.tr for Istanbul Ticaret Universitesi.
> Add files via update

- lib/domains/education/eichendorffschule.txt
- lib/domains/net/eichendorffschule.txt
Hello!
I have added two domains, eichendorffschule.net, which is the official website and email domain of all teachers and eichendorffschule.education, which is the school's email domain for students, but also some teachers.
Eichendorffschule Kelkheim is a state comprehensive school in Hesse, Germany.
Link to the German imprint on the school's homepage, which confirms all legal details: https://www.eichendorffschule.net/Datenschutz-Kontakt-Impressum/Impressum-E1022.htm
For the domain eichendorffschule.education there is no publicly visible evidence apart from the matching WHOIS and the domain forwarding, but if you give me an email address of yours I can send you a letter from the school management confirming the domain.
Kind regards
Marvin
Note: You merged an identical pull request …
> Eichendorffschule Kelkheim

- lib/domains/uk/co/bolnoreschool.txt
School website uses different domain - https://www.bolnorevillageprimary.org.uk - the email is managed under Google Classrooms.
> Added Bolnore School

- lib/domains/br/edu/unimetrocamp.txt
added unimetrocamp.edu.br
university official website: https://www.wyden.com.br/unimetrocamp/
URL of a page on the official website where a long-term (>1 year) IT related course: https://www.wyden.com.br/unimetrocamp/cursos/graduacao/tecnologia/ciencia-da-computacao
> added unimetrocamp.edu.br

- lib/domains/br/com/uscsonline.txt
This adds [Universidade Municipal de São Caetano do Sul](https://uscs.edu.br), which recently changed their domain for students accounts.
> Add domain for USCS

- lib/domains/ng/edu/bazeuniversity.txt
Added Baze University Abuja, Nigeria to the list.
University Website Link: https://bazeuniversity.edu.ng
List of Full-Time Undergraduate and PG courses: https://bazeuniversity.edu.ng/search/
List of Staff: https://bazeuniversity.edu.ng/academics/faculties-and-staff.php
> Added Baze University Abuja

- lib/domains/at/ac/htlstp.txt
Homepage: https://www.htlstp.ac.at/
we are a higher technical school with departements of electronic, information technologie, electrical engineering, 
the duration of study is five years.
> HTBLuVA St.Pölten

- lib/domains/org/nbexcellence.txt
- lib/domains/org/nbexcellence/stu.txt
This Pull Request adds [New Berlin Eisenhower Middle / High School](https://www.nbexcellence.org/schools/eisenhower/) to your database. [The New Berlin school district](http://www.newberlinschooldistrict.com/) shares a common email domain that is unfortunately not a `.edu` domain. Students are identified by `@stu.nbexcellence.org` whereas teachers and staff are identified by `@nbexcellence.org`.
[The school district website](https://www.nbexcellence.org/district/information-technology.cfm) describes how it offers courses in Information Technology and Computer Science. Specifically, there is an intro to programming course offered at Eisenhower that uses Java.
> add New Berlin, WI USA school district domain

- lib/domains/com/mac-eg.txt
Misr American College - www.mac-eg.com
Students are provided a their own school email address (xxxx@s.mac-eg.com) for their duration at Misr American College. Our main website is: www.mac-eg.com
Address: 20 Tunis St., 6th District, New Maadi. Beside Maadi Public Library، المعادى، Cairo Governorate
Misr American College a private Egyptian school based in Maadi, Cairo. This school was established in 2001. The curriculum follows American education, provided by the Massachusetts regulations, from Pre-K to Grade 12 and is accredited by the CITA board of education and the Ministry of Education in Egypt. 
We're mentioned by many websites;
https://en.wikipedia.org/wiki/Misr_American_College
https://www.easyschools.org/en/schoolProfile/misr-american-college …
> Misr American College - www.mac-eg.com

- lib/domains/com/chethams.txt
The main website is at [chethams.com](https://chethams.com/), which is used for email addresses, but the website for the school is at [chethamsschoolofmusic.com](https://chethamsschoolofmusic.com/).
The school offers **Further Mathematics**, including **Statistics** and **Decision Mathematics**, which can be seen from [this document](https://chethamsschoolofmusic.com/wp-content/uploads/sites/2/2020/10/Sixth-Form-Curriculum-Handbook-2019-2020-final-Julia-Harrison-1.docx), detailing 6th form options, which is from the [parent's information page](https://chethamsschoolofmusic.com/admissions/parent-information/).
You can find contact information showing the chethams.com domain being used for email addresses [here](https://chethamsschoolofmusic.com/about/contact-us/).
> Added Chetham's School of Music

- lib/domains/de/lernsax/ars-bsz.txt
Official school name: Arwed-Rossbach-Schule, Berufliches Schulzentrum der Stadt Leipzig
Official website: https://ars-leipzig.de/
Lernsax is the school cloud of saxony. Students get studentname@ars-bsz.lernsax.de mail addresses.
This page shows you a map of the schools using this provider:
https://www.lernsax.de/wws/9.php#/wws/858466.php
Here's a quick guide to find the school in that mess of green circles:
https://prnt.sc/zhbnrf
You'll find the school website and address there. (www.arwed-rossbach-schule.de redirects to ars-lepizig.de)
Here's the website showing the school name when logged in:
https://prnt.sc/zhco9p
> Added school ars-leipzig (Arwed-Rossbach-Schule)

- lib/domains/th/ac/pongsawadi.txt
Pongsawadi Technological College domain.
College's official website URL : [https://pongsawadi.ac.th](https://pongsawadi.ac.th)
> Add Pongsawadi Technological College

- lib/domains/uk/clf.txt
The[ Cabot Learning Federation](https://www.clf.uk) is a collective of multiple schools. Their Post-16 branch offers a 2 year computer science course: https://post16.clf.uk/computer-science/. Also, here's an example document from one of their schools showing how to access remote learning, step 4 clearly has an email that is supposed to be a student/staff email with the ending "@clf.uk": https://bristolmetropolitanacademy.clf.uk/wp-content/uploads/How-to-Access-Home-Learning.pdf
> Add clf.uk

- lib/domains/cn/com/suis/wy.txt
URL of the school: https://wanyuan.suis.com.cn
Email address is @wy.suis.com.cn
> Add Shanghai United International School, Wanyuan Campus

- lib/domains/org/moorheadschools.txt
Added domain for Moorhead High School in Moorhead, MN, US
Official School url: https://www.moorheadschools.org/schools/high-schools/moorhead-high-school/
> Added moorheadschools.org

- lib/domains/eg/edu/miniauniv.txt
Adding the second email domain for Minia University (Already verified here) owned by the university, you can find a teacher email (with this second email domain) in this official university pages:
https://www.minia.edu.eg/minia20/Edeputy.aspx
https://mc.minia.edu.eg/research/Publications/DetailsMember/25307301601533
> Add second email domain for minia university

- lib/domains/id/ac/upri.txt
Adding Pejuang University of Republic of Indonesia
University url: https://upri.ac.id/
> add Pejuang University of Republic of Indonesia

- lib/domains/edu/mcckc.txt
Metropolitan Community College, Kansas City is not in your db. Please review and add the same.
> Add MCC KC

- lib/domains/nl/hlz.txt
This PR adds hlz.nl, which is used for both the website and e-mailaccounts (see page footer). https://hlz.nl
> Add hervormd lyceum zuid

- lib/domains/ca/langleyschools.txt
`langleyschools.ca` is the domain that students of SD35 in BC Canada. District Site is at https://www.sd35.bc.ca/, and they manage DNS for this domain.
> Add Langley School District 35

- lib/domains/br/com/souunigoias.txt
- lib/domains/br/edu/anhanguera.txt
- lib/domains/com/unigoias.txt
Domains added:
anhanguera.edu.br (Main address)
souunigoias.com.br (Used only for email access in outlook)
unigoias.com.br (Alias for the main address)
The domain souunigoias.com.br does not have an entry of type A or CNAME, but it does have an entry of type MX, which is used to provide access to email on outlook.com.
If necessary, you can confirm this information by viewing the student's webmail configuration step by step at the link https://unigoias.com/tutorial-webmail/. This link is available in the "FOR THE STUDENT" -> "WEBMAIL" section of the main website.
If there is any problem with the domain souunigoias.com.br please explain to me how to proceed in this situation. Thanks.
> Add UNIGOIÁS to repository.

- lib/domains/fr/ipag.txt
Domain name ipag.fr of the ipag business school based in france (www.ipag.edu)
> Added ipag business school domain name

- lib/domains/si/student-erudio.txt
Added Erudio Educational Center.
Website: https://www.erudio.si/en/
Domain name emails that belong to students (+ subdomains): student-erudio.si
The domain can be checked here (it belongs to the institution Erudio which belongs to erudio.si):
https://www.register.si/en/
Registrar owner screenshot: https://ibb.co/cvRsqQC
> Add Erudio Educational Center

- lib/domains/eg/edu/moe.txt
For teachers who work directly at the ministry of education.
Note that only teachers (and a very select subgroup of ministry employees) can access email addresses at this domain.
> Create moe.txt (moe.edu.eg)

- lib/domains/net/nycstudents.txt
It seems that Mark Twain has already been added before, but they have since changed to use the general `nycstudents.net` addresses, meaning this will affect students other than those who attend Mark Twain.
[Official website](https://www.twain239.com/)
[Computer Science Course (scroll down)](https://www.twain239.com/apps/pages/index.jsp?uREC_ID=372360&type=d&termREC_ID=&pREC_ID=692623) 
This image was pretty much the only proof I could find, but you'll see that it is a message from my school (Mark Twain), asking me if I want to forward all the mail from my previous `twain239.org` address to my new `nycstudents.net` address. I have blacked out all of my personal information
> Add Mark Twain, but also any New York public school that uses the nycstudents domain

- lib/domains/ug/ac/mubs.txt
Makerere University Business School is a sister University to another one here, Makerere University (mak.ac.ug)
Our website is here:
[https://mubs.ac.ug](https://mubs.ac.ug)
We are in the process of revamping our website and migrating to the cloud so you might find a few errors. However, we are running a production LMS (Moodle) for our students. You can see the website here:
[https://mubsep.mubs.ac.ug](https://mubsep.mubs.ac.ug)
And you can see some of the programmes we offer (timetable)
[Click Here](https://drive.google.com/file/d/1SZES4oQMG1DfXXV4IaVcoXdzEX5gAvIr/view)
We also have a research platform (DSpace) here:
[https://mubsir.mubs.ac.ug/](https://mubsir.mubs.ac.ug/)
As you can see, we quite a number of ICT classes.
Our students would be thrilled to be able to access JetBrains …
> Added mubs.ac.ug to list of Universities

- lib/domains/br/edu/uergs.txt
Adicionando nome da Universidade Estadual do Rio Grande do Sul (UERGS), Brasil
> Add unviversity BR RS Uergs

- lib/domains/de/siwiwissen/bkt.txt
- lib/domains/de/siwiwissen/bkt/mg.txt
* [Official website](https://berufskolleg-technik.de/)
* [Long-term IT related course](https://berufskolleg-technik.de/berufsschule/) (This is a German vocational school. Here the three-year apprenticeship "Fachinformatiker"/IT specialist is taught.)
* [Siwiwissen](https://www.siwiwissen.de/) (All schools of the district Siegen Wittgenstein use Siwiwissen with the abbreviation of the school as subdomain. On the Siwiwissen website, Berufskolleg Technik Siegen is also listed below.)
> bkt.txt added and mg.txt removed due to new email address

- lib/domains/be/montfort.txt
School in Belgium, can be referred to as MCR
edit: extra info for easier verification:
Main website: https://www.montfort.be
We use Office365 for email addresses and only the admin can create them.
> Add Montfort College Rotslaar

- lib/domains/org/brevardschools/learn.txt
> the school official website URL
https://www.brevardschools.org/
> the school street address
2700 JUDGE FRAN JAMIESON WAY
VIERA, FL 32940
> an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course
The school district doesn't have an IT-related long-term course, would you like one of an individual school?
> a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students.
Their costumer support email is: [CSC@brevardschools.org](mailto:CSC@brevardschools.org)
> Add  brevardschools School District

- lib/domains/hu/sulinet/blathy-bp.txt
School page: [http://www.blathy-bp.sulinet.hu] (http://www.blathy-bp.sulinet.hu)
School  Address: Hungary - 1032 Budapest, Bécsi út 134. [Google Map] (https://goo.gl/maps/SHtGrRtVd8nviFGw7)
Proof that the email domain ** blathy-bp.sulinet.hu ** is under managment of the school.
- **The school address itself contain 'blathy-bp.sulinet.hu'** 
- **Our teachers too uses these mail domains. The page is avalible at: [http://www.blathy-bp.sulinet.hu/contact.php](http://www.blathy-bp.sulinet.hu/contact.php)**
> Added the following school: Budapest Technical Vocational Training Center Ottó Titusz Bláthy Informatics Technical School

- lib/domains/ca/mynbcc.txt
mynbcc.ca email domain is used for NBCC students
> New email domain for students

- lib/domains/com/adenformations.txt
- lib/domains/school/laclick.txt
Hi I'm trying to add my two domains used by my school ADEN Formations for IT formations.
One of these domains is for teachers and the other for students.
The main web site is https://aden-formations.fr/
The page of our IT formations are : 
https://aden-formations.fr/formations/?_filieres[]=620
Two formations pages : 
https://aden-formations.fr/formations/analyste-developpeur-dapplications/
https://aden-formations.fr/formations/concepteur-de-systemes-dinformation/
Attached file is a screen capture of the members of one of our IT formations
> Adding domains for ADENFormations IT school

- lib/domains/dz/univ-mascara.txt
This pull request adds the domain name of the Univerity of Mascara. A state-run university in the city of Mascara, western Algeria.
- URL : [Main website](https://www.univ-mascara.dz/)
- URL of the faculty of exact sciences, which houses the Informatics department: https://www.univ-mascara.dz/fse/index.php/fr/
- The Informatics department offers a three years Informatics Licence (Bachelor) program, and three, two years Master's programs, as well as multiple Ph.D. programs.
- The domain is used as an email domain for students, I know this because I study there. (Sorry, there is no proof on the website, G Suit is used for handling emails)
Thank you. 
(Sorry for the typo in the commit message)
> Add the domain name of the University of Mascara

- lib/domains/de/lernsax/afra.txt
[Sächsisches Landesgymnasium Sankt Afra zu Meißen](https://sankt-afra.de/)
[sankt-afra.de](https://sankt-afra.de/)
> Sächsisches Landesgymnasium Sankt Afra

- lib/domains/ma/emsi.txt
> [**emsi.ma**](https://emsi.ma) is the domain name used by the professors and campus directors.
> [**emsi-edu.ma**](https://github.com/JetBrains/swot/blob/master/lib/domains/ma/emsi-edu.txt) is the domain name for students.
> Added emsi.ma

- lib/domains/nl/cgu.txt
leerling.cgu.nl already existed but my school changed to .cgu.nl leerling still works for backwards compatibility but this is better for when they remove it
> added cgu.txt

- lib/domains/it/itisandria.txt
Official website: http://itisandria.edu.it/
However, the website http://itisandria.it/ is still a valid website.
IT course: http://itisandria.edu.it/index.php/la-scuola/carta-d-identita-della-scuola/l-informatica
> Itisandria it

- lib/domains/org/holychild.txt
Connolly School of the Holy Child
http://www.holychild.org/
High School
> Connolly School of the Holy Child, high school in Potomac 

- lib/domains/es/navarra/educacion.txt
After the first request, you asked for some information, but you closed the first PR before we replied. So we open now a new PR with the requested info:
-the school official website URL: http://www.cuatrovientos.org/
-the school street address, including city and country: Av. de San Jorge Etorbidea, 2, 31012 Pamplona, Navarra, Spain
-an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course: -http://www.cuatrovientos.org/formacion/cfs-desarrollo-de-aplicaciones-multiplataforma/
-a proof, which shows that the school recognizes the domain you are submitting as an official email domain for the students: I attach a document for two example students proving that they have the email address "@educacion.navarra.es" (Attached pdf) …
> Add 'Cuatrovientos centro integrado' to educational institutions

- lib/domains/jp/kosen-ac/hakodate.txt
domain "hakodate.kosen-ac.jp"
College Website: https://www.hakodate-ct.ac.jp/
National Institute of Technology, Hakodate College is one of the 57 national colleges of technology in Japan. The school is designed to provide students with specialized knowledge in the field of engineering.
It is the same type as  [National Institute of Technology, Tokyo College](https://github.com/JetBrains/swot/pull/2349) and [National Institute of Technology, Numazu College](https://github.com/JetBrains/swot/pull/5028) that have been added in the past.
Here is the syllabus for the mechanical, electrical and electronic, information, chemical, and architectural fields.
https://www.hakodate-ct.ac.jp/wp-content/uploads/2019/04/%E6%95%99%E8%82%B2%E8%AA%B2%E7%A8%8B%E8%A1%A8%EF%BC%88%E7%94%9F%E7%94%A3%E3%82%B7%E3%8 …
> add hakodate.txt

- lib/domains/se/suni.txt
The existing domain contained in the "sh.txt" file leading to Södertörns University College is outdated and leads to nonexistent domain sh.se
> Added correct domain for Södertörns Högskola

- lib/domains/gov/nyc/schools.txt
schools.nyc.gov accounts are only teacher accounts
> Request to add NYC Technical High Schools.

- lib/domains/nl/rsm.txt
Previously known as Faculteit Bedrijfskunde
> Rotterdam School of Management, Erasmus University Rotterdam

- lib/domains/br/edu/fat-al.txt
Formerly known as "Faculdade de Tecnologia de Alagoas". Website is http://fat-al.edu.br/.
> Adds Centro Universiátio Mário Cesar Jucá

- lib/domains/id/ac/stiteknas.txt
- lib/domains/ro/apizal.txt
Colegiul Tehnic "Alesandru Papiu Ilarian" Zalau, Romania
"Alesandru Papiu Ilarian" Technical College from Zalau, Romania
> Add apizal.ro

- lib/domains/pl/edja/live.txt
School website: https://jadwiga.lublin.pl/
live.edja.pl is a domain for students' e-mail addresses
It is listed in swot/lib/domains/pl/lublin/jadwiga.txt but not added
> Add live.edja.pl domain for Jadwiga Lublin

- lib/domains/nz/school/lbc.txt
Website: https://www.longbaycollege.com/
Email domain: lbc.school.nz
> Added Long Bay College, Long Bay, Auckland, New Zealand

- lib/domains/academy/esoft.txt
esoft.academy is another domain for student emails at ESOFT Metro Campus (esoft.lk) which is already added here.
> Add esoft.academy

- lib/domains/my/edu/britishschool.txt
School website: https://www.nordangliaeducation.com/our-schools/malaysia/kuala-lumpur/british-international
School adress: No.1, Changkat Bukit Utama, Bandar Utama, 47800 Petaling Jaya, Selangor, Malaysia
Subject website (course: A level & iGCSE Computer science (2 years)) : https://www.nordangliaeducation.com/our-schools/malaysia/kuala-lumpur/british-international/learning/our-curriculum/sixth-form/subjects
> Add my school

- lib/domains/uk/ac/ox/worc.txt
Worcester College is one of the 39 colleges making up the University of Oxford.
Worcester College website: https://www.worc.ox.ac.uk
University of Oxford website: https://www.ox.ac.uk
> Add Worcester College, University of Oxford

- lib/domains/pl/com/wst.txt
The University of Technology in Katowice offers  3.5 year long IT related course at first university grade (according to Polish law). The course website in English can be found here: <http://www.en.wst.com.pl/education_offer/computer_science>.
> Add entry for University of Technology, Katowice, Poland --> wst.com.pl

- lib/domains/ie/ccathlone/student.txt
**Note: My school's website is [colaistechiarainathlone.ie](https://www.colaistechiarainathlone.ie), not `ccathlone.ie`, incase you were wondering why this error appears when going to `ccathlone.ie`:**
> Add Coláiste Chiaráin, Summerhill, Athlone, Ireland

- lib/domains/ug/ac/ciu.txt
- lib/domains/ug/ac/ciu/student.txt
This adds Clarke International University domains for **staff** and **student** email.
The University was re-branded from `ihsu.ac.ug` to `ciu.ac.ug`. 
Couldn't find any entries for `IHSU` to  change :) so here we go.
- `ciu.ac.ug` - for staff emails
- `student.ciu.ac.ug` - for student emails
> Add Clarke International University - CIU domains

- lib/domains/uk/ac/leedsbeckett/student.txt
Add a new email domain ending with student.leedsbeckett.ac.uk
> Add Leeds Beckett University student email domain

- lib/domains/pk/edu/numls.txt
The above screenshot shows that the domain '@numls.edu.pk' is controlled by NUML. There is already a domain '@numl.edu.pk' in the registered domains list which is only for NUML Staff. The requested domain '@numls.edu.pk' is allocated for students of the university. The university offers different undergraduate and masters courses in different IT fields including Software Engineering. Different IT courses of the university can be checked through the given link below: 
https://www.numl.edu.pk/programs/functional
> Add numls domain

- lib/domains/de/gsso/student.txt
I already got accepted to githubs student developer programm, but it would be nice to have the scool on this list.
GSSO features a profile Subject "Information Technology", which you have to attend to till your A-Levels.
https://gsso.de/index.php/events/info/2020-21/TG/freiePlaetze
Screenshot that proves that "student.gsso.de" is on the same cert then gsso.de:
https://gsso.de/index.php/events/info/2020-21/TG/freiePlaetze
> Please add "student.gsso.de"

- lib/domains/it/embl.txt
Hi, I created the file to allow EMBL Rome to get JetBrain's educational license. [EMBL Heidelberg](https://github.com/JetBrains/swot/blob/master/lib/domains/de/embl.txt) already has such access.
> add embl.it domain

- lib/domains/jp/ac/uec.txt
Website(English): https://www.uec.ac.jp/eng/about/
This university has a faculty of related IT. https://www.uec.ac.jp/eng/education/
This university use "uec.ac.jp" as email address. https://www.cc.uec.ac.jp/ug/en/mail/index.html
> Add domain "uec.ac.jp"

- lib/domains/es/educastillalamancha.txt
This is the domain used by many schools in Castilla-La Mancha's region of Spain.
The official website is www.educa.jccm.es
And this is a screenshot of my email inbox (I'm a student, showing that the emails are used by students):
> Add Castilla-La Mancha's education domain

- lib/domains/org/ifheindia
- lib/domains/org/ifheindia.txt
1. Official Website https://www.ifheindia.org/
Address:-
The ICFAI Foundation for Higher Education (IFHE), Hyderabad
IFHE Campus
Donthanapally, Shankarapalli Road
Hyderabad - 501203, Telangana, India.
3. https://icfaitech.admissions.ifheindia.org/
> Add Domain for IFHE(Icfai Foundation For Higher Education)

- lib/domains/uk/ac/kent.txt
university official website URL: https://www.kent.ac.uk/
long-term (>1 year) IT related course is offered by the university: https://www.kent.ac.uk/courses/undergraduate/124/computer-science
> Add University of Kent

- lib/domains/co/edu/ustadistancia.txt
URL: https://www.usta.edu.co
Added domain for remote students from Universidad Santo Tomas. Already added before for resident students
> Added domain for Universidad Santo Tomas (Colombia)

- lib/domains/ie/lmetb.txt
add Louth and Meath Education and Training Board Group
This domain is used by the school in Counties Louth and Meath.
> add lmetb domain

- lib/domains/com/mrjaffesclass.txt
This is my (Roger Jaffe) domain for CS classes at Patrick Henry High School.  See my website at https://www.mrjaffesclass.com. The school website is https://patrickhenryhs.net -- you can find me on the staff directory page. I have a paid Jetbrains license under my personal email (rogerjaffe@gmail.com) but I would like my students to be able to get an educational license with their mrjaffesclass.com email address.
> mrjaffesclass.com domain added

- lib/domains/uk/co/sphcs.txt
St Philip Howard Sixth Form
https://www.sphsixthform.co.uk/
CS course: https://www.sphsixthform.co.uk/course.php?id=13 (scroll down)
Proof the domain is officially used: https://www.sphsixthform.co.uk/contactus.php
> Add SPH Sixth Form

- lib/domains/ge/bsu.txt
**University name**
Georgian: ბათუმის შოთა რუსთაველის სახელმწიფო უნივერსიტეტი
English: Batumi Shota Rustaveli State University
**Links**
https://bsu.edu.ge/ (bsu.ge redirects here)
https://bsu.edu.ge/sub-59/news/index.html (Faculty of Exact Sciences and Education)
https://bsu.edu.ge/main/page/313/index.html (Contact information)
> Add Batumi State University

- lib/domains/nl/ash.txt
School URL: https://ash.nl
Course Catalog (PDF: See pages 99-104) indicating full year Computer Science/Programming courses (IB Computer Science, AP Computer Science) https://drive.google.com/file/d/1uvHJ-TlARxTqjXo-q8nr-dvEA12LI_aO/view
Course Outlines: https://ash-nl-public.rubiconatlas.org/Atlas/Browse/View/Curriculum?BackLink=Atlas_Browse_View_Curriculum&Page=1&SchoolTypeFilter%5B%5D=2&SchoolTypeFilter%5B%5D=3&SchoolFilter%5B%5D=3&SubjectFilter%5B%5D=5&NowViewing=Atlas_Browse_View_Curriculum
Apologies for any mistakes in making this PR.
> Add American School of the Hague (ash.nl)

- lib/domains/net/boiseschools.txt
boiseschools.org already exists in this repo with the same school name, but it is reserved for teachers.
> Add boiseschools.net for student emails

- lib/domains/vn/edu/dhcnhn.txt
Add Hanoi University of Industry at: https://dhcnhn.vn/
> Add HaUI - Trường Đại học Công Nghiệp Hà Nội

- lib/domains/fi/lappee.txt
The `@lappee.fi` is used by students of public schools at the city of Lappeenranta.
Two first search results by `lappee.fi`:
Translated to English using Google Translate:
> Lappeenranta schools use Google G Suite tools. Log in to the G Suite cloud services with @ edu.lappeenranta.fi IDs (teachers) and @ lappee.fi (students).
> 
> The key tools in the G Suite are:
> 
> -Drive cloud service
> -@lappee.fi e-mail service for students
> -Office tools (Docs, Sheets, Slides)
> -Calendar (calendar.google.com doesn't sync with Outlook calendar)
> -Sites sites
> -Classroom learning environment
> -Forms questionnaires
> 
> ...
Translated to English using Google Translate:
> STUDENT WILMA AND @ LAPPEE.FI ID
> A reminder to students and their guardians.
> 
> The ID used for students at school …
> Add public schools of the city of Lappeenranta

- lib/domains/il/org/tad/shavatz.txt
new domain for Shavatz High school (abbreviation for Shimon Ben Tzvi)
Shavatz's School Site (English): https://shavatz.co.il/shimon-ben-zvi-high-school/
> Shavatz School domain

- lib/domains/us/va/k12/harrisonburg.txt
Please add Harrisonburg High School (https://harrisonburg.k12.va.us/hhs/)
Engineering Related Course: https://www.harrisonburg.k12.va.us/hhs/Department/83-HHS-STEM
> Add Harrisonburg High School

- lib/domains/fi/vaasa/student.txt
The website of the school is http://vamia.fi/.
Link to a long-term IT course offered by the school: https://vamia.fi/tutkinto/ohjelmistokehittaja/.
Here's the login page of the school. You can log in using a '*@student.vaasa.fi' account.
> Added Vamia, a vocational school in Vaasa, Finland.

- lib/domains/com/makeschool/students.txt
As of July 30th, Make School is no longer in operation.
https://www.dominican.edu/news/news-listing/dominican-welcomes-applied-computer-science-students
> The Applied Computer Science program was officially handed over to Dominican on July 30.
> Remove Make School

- lib/domains/org/lancastercountryday.txt
Official school website URL: lancastercountryday.org
URL of a page on the official website where a long-term (>1 year) IT related course is offered by the school: https://www.lancastercountryday.org/curriculum-detail?fromId=240743&LevelNum=1057&DepartmentId=18765
a URL of a page or some other proof showing that the school recognizes the domain which you are submitting as an official email domain for the enrolled students: https://www.lancastercountryday.org/directory
> Add Lancaster Country Day School

- lib/domains/nrw/tsst/schueler.txt
Name: Technischen Schulen des Kreises Steinfurt
Shortcut: TSST (Technische Schule Steinfurt)
State: NRW (North Rhine Westphalia)
Website: https://www.tssteinfurt.de/
Domain: @schueler.tsst.nrw
The school is a: Vocational college, vocational grammar school, technical college, technical secondary school and Vocational college (https://www.tssteinfurt.de/index.php/bildungsgaenge)
> Please enter this domain in your system 

- lib/domains/fi/siikalatva/edu.txt
The email addresses of `@edu.siikalatva.fi` are used by students at Siikalatva high school.
Website(s):
- https://www.siikalatva.fi/varhaiskasvatus-ja-koulutus/siikalatvan-lukio-on-vahva-yleislukio/
- https://peda.net/siikalatva/siikalatvan-lukio
IT courses: https://peda.net/siikalatva/siikalatvan-lukio/opinnot/lops2019/oppiaineet/tietotekniikka
Proof of domain(?): https://peda.net/siikalatva/siikalatvan-lukio/henkil%C3%B6kunta
(Apparently school staff doesn't use the `edu.` subdomain, didn't pull request that domain as it's probably used by non education employees as well)
> Add Siikalatvan lukio

- lib/domains/my/edu/djzhlc.txt
- lib/domains/my/edu/neivce.txt
Adding the vocational wing of our institution.
djzhlc.edu.my was previously used before switching to the current domain name neivce.edu.my.
> Add NEIVCE

- lib/domains/org/coleacademy.txt
- Official site https://www.coleacademy.org/
- There is no page on the site that describes the programming / IT courses. Simple programming courses have been provided for students for the past couple of years, and the school wanted to see if JetBrains IDEs could help us out.
- The site does not mention the student emails, but teachers and students use emails from the same domain. The bottom footer of each page on the site shows the email address for the school uses the coleacademy.org domain.
> Adding school domain information for Cole Academy

- lib/domains/br/edu/uniruy/alunos.txt
- lib/domains/br/uniruy/alunos.txt
Domain is "alunos.uniruy.edu.br" instead of "alunos.uniruy.br"
> Add Centro Universitário Ruy Barbosa

- lib/domains/de/mdg-hamburg.txt
School's sites:
https://www.marion-doenhoff-gymnasium.de/ (Homepage)
https://www.mdg-hamburg.de/ (IServ and E-Mail domain)
> Add Marion Dönhoff Gymnasium (High School)

- lib/domains/mobi/jamsa.txt
Added jamsa.mobi to domains.
This domain is owned by Jämsä, a town in Finland.
The email addresses under jamsa.mobi are only students and teachers, other personnel of the town have @jamsa.fi domains.
We have also G Suite setupped for the domain for school purposes.
> Add jamsa.mobi domain for Jämsän sivistyspalvelukeskus

- lib/domains/edu/umgc.txt
- lib/domains/edu/umuc.txt
The formerly University of Maryland University College changed its name to University of Maryland Global Campus. This link on the official website explains the name change: https://www.umgc.edu/about/university-of-maryland-global-campus/index.cfm
> Change UMUC to UMGC

- lib/domains/ie/mtu.txt
New Domain for Munster Technological University. Merging of CIT and ITTralee colleges. Old domains still active. MTU.ie is new  (as of September 2021) domain for Lecturers and Researchers and will eventually replace cit.ie and ittralee.ie at some point in the future. Website for merged college: www.mtu.ie. Old websites: www.cit.ie and www.ittralee.ie
> Munster Technological University domain: mtu.ie

- lib/domains/cz/oa-opava.txt
Obchodní akademie a Střední odborná škola logistická, Opava, příspěvková organizace
School domain: oa-opava.cz
The student's emails are on the same domain @oa-opava.cz
Address: Hany Kvapilové 20, 746 01  Opava, Czech republic
Contact information on our website: https://oa-opava.cz/index.php/kontakt
School offers an IT-related long-term (4 years) course Inforamtion Technology in Economics
Computer since subject: https://oa-opava.cz/index.php/uchazeci/obor-informacni-technologie
Education plan for Information Technology: https://oa-opava.cz/images/soubory/ke_stazeni/2019_svp_it.pdf
> Add OA Opava

- lib/domains/org/eduservices.txt
Added eduservices.org
Eduservices regroups several schools and that is the domains used for the teachers addresses.
I personally teach at MyDigitalSchool (which is already part of this repo my-digital-school.org) but I have an @eduservices.org email as a teacher.
Eduservices webpage :  http://www.groupe-eduservices.fr/en
MyDigitalSchool legal page that mention the eduservices group ownership : https://www.mydigitalschool.com/mentions-legales
Some of the MyDigitalSchool courses related to IT : 
- https://www.mydigitalschool.com/mba-architecte-web
- https://www.mydigitalschool.com/bachelor-developpeur-digital-web
Have a great day!
> Add domain eduservices.org

- lib/domains/info/ramat-gan.txt
Adding Green Village School (Ha-Kfar Ha-Yarok School) in Ramat Ha-Sharon, Israel.
Some info about the school: https://en.wikipedia.org/wiki/HaKfar_HaYarok#Junior_High_School.
The school site in Hebrew: https://kfaryarok.org.il/.
> Adding Green Village School

- lib/domains/cz/oaopava.txt
oaopava.cz is the second domain we use for emails and for a lot of students are this primary domain.
> OA Opava second domain

- lib/domains/school/governors.txt
The South Carolina Governor's School for Science and Mathematics is transitioning from the previously accepted gssm.k12.sc.us to the newly updated governors.school
The old domain is in the process of being phased out and should be obsolete by the end of the 2021-2022 school year.
> add new SCGSSM domain

- lib/domains/net/kellerisd.txt
Keller Center for Advanced Learning (https://www.kellerisd.net/kcal) is the CTE center for Keller ISD. The .net emails are the faculty emails.
> Keller Center for Advanced Learning

- lib/domains/ch/ibz.txt
- lib/domains/ch/ipso.txt
See https://campus.ibz.ch/#section-100500
> IBZ Schulen AG changed its email domain.

- lib/domains/at/ac/fhgooe.txt
- lib/domains/at/ac/fhgooe/stud.txt
Added the domains fhgooe.ac.at and stud.fhgooe.ac.at.
The first one is used for teachers and the second one is used for students.
The IT related course is medical technology and medical informatics.
The homepage is [https://www.fh-gesundheitsberufe.at/](https://www.fh-gesundheitsberufe.at/).
> FH Gesundheitsberufe OÖ GmbH

- lib/domains/de/hhek.txt
Heinrich-Hertz-Europakolleg der Bundesstadt Bonn
Address: Herseler Straße 1, 53117 Bonn, Germany
Website: https://hhek.bonn.de/
More information about IT courses offered at hhek can be found here: https://hhek.bonn.de/informationstechnik/
Heinrich-Hertz-Europakolleg is using two different domains:
hhek.bonn.de, which is used for its public website and teacher's email addresses, was already added earlier this year (https://github.com/JetBrains/swot/blob/master/lib/domains/de/bonn/hhek.txt)
hhek.de is used for internal tools and student's email addresses
As proof that hhek recognizes the domain hhek.de, you can find multiple links to it in the "Internal" page of their official website: https://hhek.bonn.de/intern/
> Add Heinrich-Hertz-Europakolleg Bonn

- lib/domains/com/onmicrosoft/dypisp.txt
Website: https://dypsoe.in/
Address: Dr D Y Patil Knowledge City, Charholi (Bk), Via Lohgaon, Pune- 412105, Maharashtra, India
URL where the school offers an IT-related long-term course: https://www.dypic.in/dypsoepoly/pages/computer_academics.html, https://dypsoe.in/compPG.html
> Add Dr. D. Y. Patil School of Engineering

- lib/domains/in/ac/itbhu.txt
- Official Website: https://iitbhu.ac.in/
- IT related course: https://iitbhu.ac.in/dept/cse
On the following link https://iitbhu.ac.in/cf/cis which is our Computer Facilities Page you can find the `check mail` button in the footer whose hyperlink reference is to http://mail.itbhu.ac.in/ which is our primary domain apart from iitbhu.ac.in
The reason for the two domains is because our institute was renamed to Indian Institute of Technology in the year 2012 before that it was Institute of Technology ([Reference](https://en.wikipedia.org/wiki/Indian_Institute_of_Technology_(BHU)_Varanasi)). Hence for compatibility reasons both domains are kept in use but students are first provided itbhu.ac.in so they can only login using it but mail can be sent and received using iitbhu.ac.in as well.
> feat: domain for iitbhu (primary)

- lib/domains/com/onmicrosoft/sabje.txt
Please can you add SABJE's external email address.
I earlier added sabje.co.za, but have just been informed that will only work for internal mail. To use external emails we need to use sabje.onmicrosoft.com. 
King David Schools
https://kingdavid.org.za/
Sorry for any inconvenience caused.
> Add SABJE external email address

- lib/domains/org/combertonvc.txt
Comberton Village College has the domain https://www.combertonvc.org/ and postcode CB23 7DU, I'm not sure what verification I can give other than a test register message
> Comberton Village College

- lib/domains/es/uneatlantico.txt
- lib/domains/es/uneatlantico/alumnos.txt
Hi everyone,
I'm a teacher in "European University of Atlantic". My students are abled to use educational licenses but the teachers are not, because our email uses the main domain of the school (uneatlantico.es). This commit removes the folder and file 'alumnos.txt' and adds a single file 'uneatlantico.txt' to allow both, students and teachers, use this kind of licenses.
> Use base domain 'uneatlantico.es' 

- lib/domains/berlin/ong.txt
- lib/domains/de/otto-nagel-gymnasium.txt
Hello, I opened a pull request to add the Otto-Nagel-Gymnasium located in Berlin.
Some notes:
* the website otto-nagel-gymnasium.de redirects to ong.berlin
* students get student.ong.berlin for their E-Mails
* Teachers get both a ong.berlin Mail and a otto-nagel-gymnasium.de Mail
* the school offers a [2 year IT course](https://ong.berlin/wahlpflichtunterricht/) (the text is in German, and its one of an arrangement of courses that students have to pick 2 from) 
Edit:
This page proofs that student actually use these E-Mails: [Link](https://portal.ong.berlin/anleitungen/e-mail/zugriff-ueber-apple-mail-schueler/) (its a guide how to set them up)
Edit 2:
[This](https://who.is/whois/ong.berlin) whois pages proofs that the school owns the domain ong.berlin .
> Requested Otto-Nagel-Gym

- lib/domains/eg/edu/dmu.txt
Wiki page : https://en.wikipedia.org/wiki/Damanhour_University
University Official website : https://www.damanhour.edu.eg/en/pages/default.aspx
https://dmu.edu.eg/
http://portal.mohesr.gov.eg/en-us/Pages/governmental-universities.aspx#accordionV1Collapse19
> add damnhour university domain

- lib/domains/io/oclock.txt
the school official website URL :  https://oclock.io/
the school street address, including city and country : 10 RUE DE PENTHIEVRE 75008 PARIS FRANCE (O'clock is a real-time remote school )
an URL of a page on the official website where the school offers an IT-related long-term (>1 year) course : 
https://oclock.io/formations/alternance#info
s
> add Ecole O'clock

- lib/domains/at/sti2.txt
This PR adds Semantic Technology Institute in Innsbruck, Austria, to the repo.
> Adds Semantic Technology Institute

- lib/domains/br/com/sempreuninorte.txt
Another domain owned by UniNorte
Centro Universitário do Norte - UniNorte is a part from Ser Educational Group
> University add: UniNorte

- lib/domains/education/ukr/lgk.txt
Heroes of Kruty State Lyceum of Lviv - is a military oriented state lyceum in Lviv (Ukraine). One of the speciality (cyber security) is orientated to form future developpers for state cyber security domain 
Official website (in ukrainian):
https://ldl-gk.lviv.ua/
Official FB page:
https://www.facebook.com/lgkrut/
> add Heroes of Kruty State Lyceum of Lviv

- lib/domains/org/puyallupsd.txt
Here's main domain for the district, https://puyallup.k12.wa.us. It can be verified of authenticity as it has an official K-12 domain provided by the Washington Office of Superintendent of Public Education (https://www.k12.wa.us/). Here is a page verifying authenticity of student email, https://puyallup.k12.wa.us/cms/One.aspx?portalId=141151&pageId=3257594. If this can still not be authenticated or added, I understand.
> Add PSD Student Email

- lib/domains/il/org/tad/shavatz.txt
- lib/domains/il/org/taded.txt
https://shavatz.co.il/shimon-ben-zvi-high-school/
> new domain for Shavatz high school

- lib/domains/de/hector-seminar.txt
This PR adds the domain `hector-seminar.de` to the repository.
The Hector Seminar is an institution for the promotion of highly gifted pupils at high schools in northern Baden, Germany. It promotes pupils in mathematics, computer science, natural sciences and technology. Everyone of them gets an email address for the time until their graduation and the domain seems to be missing from the swot repository.
Website of the Hector Seminar: https://hector-seminar.de/startseite
> Add file for Hector Seminar

- lib/domains/at/ac/htlmistelbach.txt
"HTL Mistelbach for biomedical engineering"
Karl Katschthaler-Straße 2, 2130 Mistelbach, Austria
School offers 5 years with matura.
https://www.htlmistelbach.ac.at/Fachrichtung-Biomedizin--und-Gesundheitstechnik-in-Mistelbach.html
Focus on electronics, computer science (IT) and biomedical engineering
> Add HTL Mistelbach

- lib/domains/uk/org/beauchampcity.txt
Afternoon,
Would like to add the domain for the Beauchamp City Sixth Form, Leicester.
Website is [here](https://www.beauchampcity.org.uk/), we offer Computer Science A level [here](https://www.beauchampcity.org.uk/curriculum/curriculum/course-information/computer-science/) and students can access their emails through the standard Microsoft Office Portal.
> Added BCSF sixth form

- lib/domains/tz/ac/mustnet.txt
1. Currently, mustnet.ac.tz has transitioned to must.ac.tz but the emails are still under mustnet.ac.tz
2. Link to a Bachelor degree in computer science program [here](https://must.ac.tz/programmes/NDA%3D)
> Mbeya University of Science and Technology

- lib/domains/nz/ac/developers.txt
- lib/domains/nz/ac/developersinstitute.txt
Contributing an NZ accredited tertiary institution: See www.developers.ac.nz
> Add Developers Institute to Jetbrains list
